### ISSUE TITLE
Wheel build test failures on urlopen with handshake failure

### ISSUE THREAD

**Issue by matthew-brett** [matplotlib/matplotlib#10066]
Look like new errors of form:

```
    @pytest.mark.network
    def test_load_from_url():
        req = six.moves.urllib.request.urlopen(
>           "http://matplotlib.org/_static/logo_sidebar_horiz.png")
/venv/local/lib/python2.7/site-packages/matplotlib/tests/test_image.py:605: 
[... snip ...]
>           raise URLError(err)
E           URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
```

For some reason on Linux Python 2.7 (not 3.4 through 3.6), and OSX 2.7, 3.4 and 3.5 (not 3.6):

https://travis-ci.org/MacPython/matplotlib-wheels/builds/318642602

Restarting the build a couple of times just repeated the error.

Same error yesterday (same pattern).

https://travis-ci.org/MacPython/matplotlib-wheels/builds/318642602

Builds failing for 4 days previously were for an unrelated travis-ci error - but these may have concealed these ones starting.  These also coincide with a new travis-ci Ubuntu image, but that cannot explain the OSX  failures.

**Comment by matthew-brett** [comment]
Failures continue : https://travis-ci.org/MacPython/matplotlib-wheels/builds/320609234

**Comment by peircej** [comment]
I think this might be due to an issue with SSL formats. I've had a similar error in the past. Python3.6 may have  a different set of SSL protocols installed as defaults. Try adding `pip install requests[security]` to your travis setup (you're already getting requests, but this installs 3 additional packages`

See:

 - https://stackoverflow.com/questions/33778516/handshake-failure-in-python-ssl-c590
 - https://stackoverflow.com/questions/31811949/pip-install-requestssecurity-vs-pip-install-requests-difference

What puzzles me a bit in your case is that you're accessing an https url when the error occurs, whereas I would expect SSL issues only at an http address. Then again, I'm no SSL expert! :-)

**Comment by matthew-brett** [comment]
@peircej - nice - it looks as though that fixed it : https://github.com/MacPython/matplotlib-wheels/commit/20708af5183884320af7d7ff339ecfbdc10b992c ; https://travis-ci.org/MacPython/matplotlib-wheels/builds/349279589
