### ISSUE TITLE
NonUniformImage ignores origin='upper' options during drawing and reset canvas origin to 'lower'

### ISSUE THREAD

**Issue by liubenyuan** [matplotlib/matplotlib#10113]
### Bug report

**Bug summary**

NonUniformImage ignores origin='upper' options during drawing and reset canvas origin to 'lower'

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.image import NonUniformImage
from matplotlib import cm

interp = 'nearest'

# Linear x array for cell centers:
x = np.arange(10)
y = np.arange(10)
z = x[:, np.newaxis].dot(y[:, np.newaxis].transpose())

# fig, axs = plt.subplots(nrows=2, ncols=2)
# ax = axs[0, 0]
fig, ax = plt.subplots()
im = NonUniformImage(ax, interpolation=interp, extent=(0, 9, 0, 9),
                     cmap=cm.Purples, origin='upper')
im.set_data(x, y, z)
ax.images.append(im)
ax.set_xlim(0, 9)
ax.set_ylim(0, 9)
ax.set_title(interp)
```

**Actual outcome**

The origin is located at the lower (left-bottom corner).

And if there is a preceding imshow(image, origin='upper') command, the origin will be reset if I am using NonUniformImage later.

**Expected outcome**

I can set the origin in NonUniformImage.

**Matplotlib version**

  * Operating system: windows 7 x64
  * Matplotlib version: 2.1.1
  * Matplotlib backend: qt5
  * Python version: 3.6
  * Other libraries:

**Comment by liubenyuan** [comment]
BTW, I want to use `NonUniformImage` as a interpolated version of `pcolor`, which can show smooth (x, y, z) 2D data.

**Comment by efiring** [comment]
The real bug here is that NonUniformImage is half-baked; it should reject the origin and extents arguments, and it should require a full x, y, z set of inputs in its initializer.  Actually, I think NonUniformImage is a bad idea and should be deprecated.  It is interpolating before stretching to the new grid, which makes little sense.  Furthermore, with a non-uniform grid, specifying centers is not a good idea because there are too many ways that what is really needed--the edges--could be calculated.

**Comment by liubenyuan** [comment]
It seems there lacks an interpolating method that accepts (x, y, z) as plotting parameters where z=f(x, y). `pcolormesh` has problems in rendering pdf files with alpha channels on. The edges of quadmesh are more visible than patches. I do not know it is a matplotlib problem or pdf rendering problem.
