### ISSUE TITLE
Adapt stem plot

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#10165]
### Proposed changes

Inspired by the [example stem plot](https://matplotlib.org/gallery/lines_bars_and_markers/stem_plot.html#sphx-glr-gallery-lines-bars-and-markers-stem-plot-py).

**1. Z order**

Currently the stems are on top of the markers. This is in agreement with the MATLAB behavior http://de.mathworks.com/help/matlab/ref/stem.html#btrw_xi-94

However, it looks a bit untidy. I propose to place the markers on top.

**2. Example coloring**

The example cycles through the stem colors. IMO this is an untypical use case. The example (in particular if we just have one) should show a typical diagram. Therefore, we should change it to just one stem color.

**Comment by anntzer** [comment]
I would also argue that it should be considered a bug that `ax.stem([1, 2])` does not cycle the colors but `ax.stem([1, 2],"-.")` does...  not sure if #9565 helps with that.

**Comment by AdamsonMA** [comment]
I've also found that the lines overlapping the markers looked untidy.  My solution was to create a new pyplot method for personal use that allows users to re-order which items appear on top when plotting.  I would be glad to share the code if this issue is still open!

An example of the reordered plot:
![image](https://user-images.githubusercontent.com/18506100/35781143-fa49df9e-09b3-11e8-8912-0468b310c0fd.png)

**Comment by timhoffm** [comment]
It seems that https://github.com/matplotlib/matplotlib/pull/9565#issuecomment-340501010 also fixes the z-order. To prevent duplicate work, I wouldn't do anything here until the above is merged.

**Comment by jklymak** [comment]
I mildly disagree about the zorder.  Its easier to pick off a precise number when a solid line ends at the end to the stem.

**Comment by timhoffm** [comment]
Ok, let's keep the zorder.

The example coloring is adapted in #13687.
