### ISSUE TITLE
mark_inset axis mismatch for invert negative Y-axis

### ISSUE THREAD

**Issue by agallenne** [matplotlib/matplotlib#10227]
### Bug report

**Bug summary**
When using mark_inset for increasing negative numbers in y-axis, i.e. from -2 to -10 for instance, the lines of the boxes do not match and crossed. This might be due to the use of negative numbers. Here is an example code with one plot ok when plotting the y-axis from -10 to -2, and the one not working (lines are crossed) when plotting from -2 to -10.

[ok.pdf](https://github.com/matplotlib/matplotlib/files/1621109/ok.pdf)
[nok.pdf](https://github.com/matplotlib/matplotlib/files/1621110/nok.pdf)

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.inset_locator import mark_inset, inset_axes

x = np.linspace(-10, -2, 100)
y = x*1.
ax = plt.subplot(111)
plt.plot(x,y)
ax.set_ylim(-2, -10)

ax1 = inset_axes(ax, bbox_to_anchor=(.0, .07, 1., 1.),
                         bbox_transform=ax.transAxes,
                        width='40%', 
                        height='30%', 
                        loc=4)
plt.plot(x,y)
ax1.set_ylim(-8, -9)
# ax1.set_ylim(-9, -8)
ax1.set_xlim(-9, -8)
mark_inset(ax, ax1, loc1=2, loc2=3, fc="none", ec="0.5")
```

**Matplotlib version**

  * Operating system: macOS 10.12.6
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: python 2.7.14 / ipython 5.4.1
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by afvincent** [comment]
Based on @ImportanceOfBeingErnest in #10738 , a workaround may be to manually set `loc1` and `loc2` after calling `mark_inset`. For example in the case of the snippet above, something like
```python
_patch, pp1, pp2 = mark_inset(ax, ax1, loc1=1, loc2=3, fc="none", ec="0.5")
pp1.loc1, pp1.loc2 = 1, 4  # inset corner 1 to origin corner 4 (would expect 1)
pp2.loc1, pp2.loc2 = 3, 2  # inset corner 3 to origin corner 2 (would expect 3)
```
produces
![figure_1](https://user-images.githubusercontent.com/17270724/37227465-332263de-2392-11e8-8ce7-f9b05746de5b.png)
which seems rather OK to me.

However, I had to find the location codes among {1, 2, 3, 4} by trial-and-error because the meaning of those codes seems indeed to be horizontally flipped in the case of the upper left rectangle (i.e. the values `pp*.loc2` are not intuitive).

**Comment by tacaswell** [comment]
Moved to 3.0 milestone as this is not a regression and there is a user-accessible workaround
