### ISSUE TITLE
Matplotlib stylesheet warnings: Key boxplot.medianprops.color: 'C1' does not look like a color arg`

### ISSUE THREAD

**Issue by MoritzImendoerffer** [matplotlib/matplotlib#10406]
### Bug report

I  adapted a  stylesheet from this official [source](https://matplotlib.org/tutorials/introductory/customizing.html?highlight=customizing%20matplotlib)

when I uncomment line 148:
`boxplot.medianprops.color     : 'C1'`

I do get a warning. I think this warning is not specific to line 148 but has something to do with either the boxplot styles or the color argument.

**Code for reproduction**
`from matplotlib import pyplot as plt`
`plt.style.use('custom_style.mplstyle')`

**Actual outcome**

`UserWarning: Bad val "'C1'" on line #148
    Key boxplot.medianprops.color: 'C1' does not look like a color arg`

**Matplotlib version**
  * Operating system: Windows 7 enterprise
  * Matplotlib version: 2.1.2
  * Matplotlib backend : tried Agg, TkAgg, Qt4Agg
  * Python version: 3.6
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: 

i used conda defaults channel for installing matplotlib.

**Comment by ImportanceOfBeingErnest** [comment]
This is indeed a confusing thing. 

Since the matplotlib rc file is (as of now) not a python file, strings are not to be escaped in quotes. 

A working matplotlib rc file should therefore look like

```
boxplot.medianprops.color : C1
```
without the single quotes `''`.  

There are currently a lot of arguments which use quotes in the example file. So I guess this issue translates into "Please remove all string escapes from the [matplotlib rc example file](https://matplotlib.org/users/customizing.html#a-sample-matplotlibrc-file) and the documentation".

(Or to be more precise all `''` except for the `axes.prop_cycle` where they are actually needed. This is a really confusing thing.)

**Comment by ImportanceOfBeingErnest** [comment]
@tacaswell What is the reason to postpone this to v3.0? Isn't it pretty straight forward to do right now? 

If I see it correcty, we would just need to edit `matplotlibrc.template` because the documentation is automatically generated from it. Most part is straight forward, removing any `''`.  

One tricky bit, I currently would not know if and how to change, are the arguments to the animation section, because they contain "empty strings" and path names. So I could imagine to leave them like they are, but add example usage comments behind them.

https://github.com/matplotlib/matplotlib/blob/0ec46336fd142313fa12de936e002e94e2a0dce5/matplotlibrc.template#L580-L599

**Comment by tacaswell** [comment]
Because I want to tag 2.2 ASAP, if you have a PR :+1: to merging it, but not willing to block anything on it.

We have a history of 'just-one-more-fix'-ing releases.
