### ISSUE TITLE
Should points with a single infinite coordinate be masked or clipped?

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#10452]
Initially raised in https://github.com/matplotlib/matplotlib/pull/9305#issuecomment-337787891 (and following comment).

We realized in 2.1 that there is a reasonable argument for `plt.plot([1, 1], [1, np.inf])` to draw a semi-infinite vertical line and `plt.plot([1, 1], [-np.inf, np.inf])` to draw an infinite vertical line by default (by having the renderer clip infinities instead of masking them).  Right now log scale allows both clipping and masking behavior, but linear scale always masks.

Of course this is a breaking change, so I'm just opening this for discussion.

**Comment by efiring** [comment]
I think that infinities should be treated as invalid for plotting purposes, and therefore they should be masked.  Building in special treatment for `inf` adds considerable complexity for very little gain.

**Comment by ImportanceOfBeingErnest** [comment]
If I understand this proposal correctly you would want to add some vertical line from the last valid point towards infinity. So with this code

```
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-3,3,13)

plt.plot(x, x/(x-1), marker="o")
plt.margins(y=0.3)
plt.show()
``` 

the result would be the following?

![image](https://user-images.githubusercontent.com/23121882/36233339-d1d15efe-11e5-11e8-9697-554551ebcb30.png)

That is hardly understandable. And you have no chance of knowing the user wanted to plot `x/(x-1)` in order to produce the first line correctly pointing towards `-inf`.

Next how about the margins? If the lines are clipped at the axes boundary, this effectively ignores the margin set. However, a margin is usually set precisely not to have the plot be tight to the boundaries.

**Comment by anntzer** [comment]
Most arguments have already been made in the linked issue, so I'm just giving the short version here.

1) The suggested behavior is not particularly complex to support, because we *already* need to clip values larger than `2**24` because they would overflow the fixed point representation internally used by agg (and cairo, and ghostscript (which has an even lower limit), etc.).  We even have a test for that (test_simplification::test_clipping).  So it would just be a matter of only masking out nans instead of masking out both nans and infs, and then let the infs be clipped by the already existing codepath.

2) When using log-scale, there are many cases where the expected behavior is to clip and not to mask (see #9305 and linked issues, we noticed this shortly after 2.1.0 was released with a change in behavior towards masking, and reverted to (modified) clipping in 2.1.1).  Now it is true that clipping can also give confusing results (as mentioned by @ImportanceOfBeingErnest) so it's a tradeoff as always.  @tacaswell did mention support for the suggestion, so I was just opening this for discussion.

I don't see how the margins are a problem, they would as always be computed ignoring the infinite points.

**Comment by ImportanceOfBeingErnest** [comment]
The point about margins is not how they are calculated, but about the expected visual appearance. If I set some margin around the plot I would expect there to be no lines within this margin. The proposed change would counteract this expectation, because those infinity-line would appear in the plot in the region where I don't want to have any lines due to my setting of `margins`.

In that sense, whatever you do, just make sure to include the option to turn those infinity-lines off in the rcParams.

**Comment by anntzer** [comment]
Let's close this as "unlikely to ever happen".
