### ISSUE TITLE
In Axes.hist, 'range' kwarg shadows builtin 'range' needed for Py3

### ISSUE THREAD

**Issue by cclauss** [matplotlib/matplotlib#10526]
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L6413

**Comment by phobson** [comment]
Hmmm,

I'm not sure this is the case, though I can't explain why.

![image](https://user-images.githubusercontent.com/1163939/36358281-f6c3d16e-14c0-11e8-807d-a5f57ff6ad36.png)

Are you having trouble using `range` after called `Axes.hist`?

**Comment by efiring** [comment]
The error is that the `del range` statement isn't doing anything useful.  I think that the intention was to get the equivalent of 
```python
import builtins
range = builtins.range
```
which would undo the shadowing of the builtin by the `range` kwarg name.  This would matter only if the `range` function is needed within the hist method, because that is where the shadowing is occurring.  Presently it is using `xrange`, but this should now be changed to `range`, so the change suggested above will be needed.

**Comment by cclauss** [comment]
This was fixed in #10525
* https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L6413
