### ISSUE TITLE
Unexpected behaviour when setting axes limits after using "imshow" with a clip path in Jupyter Notebook.

### ISSUE THREAD

**Issue by KelSolaar** [matplotlib/matplotlib#10529]
### Bug report

**Bug summary**

I'm experiencing some unexpected behaviour when settings axes limits after using `imshow` with a clip path in Jupyter Notebook. The axes are using the defined x and y limits but I have now a massively large white margin around my image:

*Reference Clipped*
![image](https://user-images.githubusercontent.com/99779/36369106-ed0d15d2-15be-11e8-8e57-fa2d91fe8b57.png)

*Limits Broken*
![image](https://user-images.githubusercontent.com/99779/36369124-f9d209a8-15be-11e8-9967-d07c93b57646.png)

**Code for reproduction**
I created a Jupyter Notebook for reproducibility convenience: https://gist.github.com/KelSolaar/f3f711d96b83caca391f5355c8d1afce

And here is the relevant code snippet:

```python
% matplotlib inline
import matplotlib.pyplot
import numpy as np
import pylab
from matplotlib.patches import Circle

figure = matplotlib.pyplot.figure()
axes = figure.gca()
RGB = np.random.random((32, 32, 3))

circle = Circle([0.5, 0.5], 0.5, facecolor='none', edgecolor='none')
axes.add_patch(circle)
pylab.imshow(
        RGB, interpolation='bilinear', extent=(0, 1, 0, 1), clip_path=circle)

pylab.xlim(0.4, 0.6)
pylab.ylim(0.4, 0.6)

pylab.show()
```

**Actual outcome**

*Limits Broken*
![image](https://user-images.githubusercontent.com/99779/36369124-f9d209a8-15be-11e8-9967-d07c93b57646.png)

**Expected outcome**

I would not expect to have such a massively large white margin around my image

**Matplotlib version**

  * Operating system: macOs
  * Matplotlib version:  2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 2.7.13
  * Jupyter version (if applicable): 5.0.0
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
You will get the desired outcome by not adding the circle to the axes. Instead just set the axes transform.

```
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle

figure = plt.figure()
axes = figure.gca()
RGB = np.random.random((32, 32, 3))

circle = Circle([0.5, 0.5], 0.5, facecolor='none', edgecolor='none', transform=axes.transAxes)
plt.imshow(RGB, interpolation='bilinear', extent=(0, 1, 0, 1), clip_path=circle)

plt.xlim(0.4, 0.6)
plt.ylim(0.4, 0.6)

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/36381611-76db2e68-1586-11e8-9dff-1f0c8a1a5005.png)

I would guess that it is still undesired to have some artist which is used as clip_patch to be accounted for with `bbox_inches="tight"`. Not sure what exactly causes this.

**Comment by WeatherGod** [comment]
The patch was added to the axes. It doesn't matter that it was also set as
a clip-path. I am not sure if we would want to try and treat an artist
specially if it was also assigned as a clip path.We don't keep a central
list of the clip-paths. Each artist keeps track of their own clip paths.

**Comment by ImportanceOfBeingErnest** [comment]
(Apologies for my previous now deleted comment, that didn't make sense because I had a different axes variable floating in my notebook when testing.)

The point here is precisely that some mechanism distinguishes between a Patch being in the axes and a Patch being used as clip_path. So the issue is rather the inverse, you do *not*  want to treat them differently, but they currently are treated differently - at least in the the notebook's `bbox_inches="tight"` context.
I think the issue best becomes clear is by removing `clip_path=circle` in the code; this would then produce the expected output. 

```
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()
ax.set_xlim(0.4, 0.6)
ax.set_ylim(0.4, 0.6)
RGB = np.random.random((32, 32, 3))

circle = plt.Circle([0.5, 0.5], 0.5, facecolor='none', edgecolor='none')
ax.add_patch(circle)

for clip in [None, circle]:
    im = ax.imshow(RGB, extent=(0, 1, 0, 1), clip_path=clip)
    plt.savefig("test_{}.png".format(clip), bbox_inches="tight")
```

This code produces two images, the one with `clip_path=None` is the expected one, the one with `clip_path=circle` is the undesired one shown in the post above.

I guess the problem starts [here in line 2221 of backend_bases.py].

**Comment by WeatherGod** [comment]
Ah, I see now. I got mixed up in the description.

So, most artists get a clip path of the plot box by default when added to
the axes. When we added circle patch to the clip path of the image artist,
I think it replaced the default clip path of the plot box in the image
artist. Now, perhaps that isn't a problem, because the circle patch, having
been added to the axes should itself have the plot box as a clip path... so
I am not sure what is wrong here.

Nothing jumps out as wrong to me in that section of code in the
backend_bases, either.

**Comment by KelSolaar** [comment]
Hi,

I think I saw a comment in my mails (probably the one deleted) that was hinting to some potential workaround. Am I incorrect @ImportanceOfBeingErnest ?

Cheers,

Thomas

**Comment by ImportanceOfBeingErnest** [comment]
Yes, but if that workaround had been working I wouldn't have deleted it. 

As of now the only workaround you have is not to use a clip_path (this would produce the desired plot anyways).

**Comment by KelSolaar** [comment]
Right, unfortunately, what my example does not show is that I might want to zoom on the circle border, or anywhere within the clipped image, e.g using an image already bounded at its pixel level:

**Full**

![image](https://user-images.githubusercontent.com/99779/36498886-9a100c6c-17a4-11e8-9e57-5e03a58f6710.png)

**Zoom**

![image](https://user-images.githubusercontent.com/99779/36498910-a5fb32ea-17a4-11e8-8e0e-b555d18a4bcc.png)

**Comment by ImportanceOfBeingErnest** [comment]
### Problem
As said, the problem starts in the `backend_bases.py` 

https://github.com/matplotlib/matplotlib/blob/206b5fe566a5a06375cb7e1cf27b5890920d42f0/lib/matplotlib/backend_bases.py#L2221-L2238

Printing some of the used variables here reveals that the resulting `bbox_inches` in the case of the clip_path being set is 
```
Bbox(x0=-5.96, y0=-6.864, x1=12.52, y1=11.616)                   # in case of clip_path set
Bbox(x0=0.938527777778, y0=0.290777777778, x1=5.3255, y1=4.279)  # in case of no clip
```

This is due to the `_bbox` being
```
union _bbox:  [ -596.   -686.4  1252.   1161.6]    # in case of clip_path set
union _bbox:  [ 139.7   49.3  516.3  425.9]        # in case of no clip
```

The reason is that because if there is a clip_path (L2226), the intersection between the clip_path bounding box and the image bounding box, which are both very large, is added (`bbox` in L2228) to the `bbox_filtered` list. 

So the problem then tracks further to `imshow` which does not have a `clip_box` once a `clip_path` is set.
Indeed, 

```
im = ax.imshow(..., clip_path=None)
print im.get_clip_on()      # True
print im.get_clip_box()     # TransformedBbox(  ....  )
print im.get_clip_path()    # None

im = ax.imshow(..., clip_path=circle)
print im.get_clip_on()      # True
print im.get_clip_box()     # None
print im.get_clip_path()    # <matplotlib.transforms.TransformedPatchPath object at 0x0...>
```

At this point I find it hard to judge whether this is expected or not and hence whether the problem should be handled inside the `backend_bases`' `print_figure` function or on the artist level, giving the image its clipbox back. 

<hr>

### Workaround

In any case it seems setting the clip_path externally to the image seems to solve the issue:

 Instead of `im = ax.imshow(RGB, extent=(0, 1, 0, 1), clip_path=None)` using 

```
im = ax.imshow(RGB, extent=(0, 1, 0, 1), clip_path=None)
im.set_clip_path(circle)
```

produces the desired image.

**Comment by KelSolaar** [comment]
@ImportanceOfBeingErnest : Thanks for the workaround, this fixed the issue on my end.
