### ISSUE TITLE
pyqt error while importing pyqt5

### ISSUE THREAD

**Issue by BlcaKHat** [matplotlib/matplotlib#10543]
Importing PyQt4 disabled by IPython, which has
    already imported an Incompatible QT Binding: pyqt5

I am trying to import  
In [3]: import hyperspy.api as hs      ( in ipython) .
I have python 2.7

**Comment by tacaswell** [comment]
What is happening is you have (maybe implicitly) imported pyqt5 while starting up IPython to use the qt5agg backend, but hyperspy seems to have an explicity pyqt4 import.  Due to restrictions from Qt you can not have both imported at the same time.

You can explicitly set the backend to qt4agg (see https://matplotlib.org/tutorials/introductory/usage.html?highlight=what%20backend#backends ).  You may also want to report this as a bug to hyperspy.

If you have further questions please direct them to matplotlib-users@python.org (https://mail.python.org/mailman/listinfo/matplotlib-users you will need to register to post un-moderated).
