### ISSUE TITLE
Take too much memory and too long to save into figure

### ISSUE THREAD

**Issue by wheretobegin** [matplotlib/matplotlib#10641]
### Bug report

**Bug summary**
fig.savefig(fname) step take to long to save a pcolormesh figure

**Code for reproduction**
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
N = 10000
S = np.random.rand(N, N)
fig = plt.figure()
plt.pcolormesh(S)
plt.colorbar()
plt.xlim([0,N])
plt.ylim([0,N])
fig.savefig('test.pdf')

**Actual outcome**
Take ~20G memory and didn't finished running after 10 hours. I had to killed the process. 

**Matplotlib version**
  * Operating system: Ubuntu 14.04.5
  * Matplotlib version: 1.5.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): u'GTKAgg'
  * Python version: 2.7
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: numpy: 1.14.0

**Comment by efiring** [comment]
This is not a bug.  You are trying to write 100 million quadrilaterals to a pdf file. I don't see how that could be useful.  If you would like help with an application, you could ask on stack overflow or the Matplotlib-users <matplotlib-users@python.org> mailing list.

**Comment by WeatherGod** [comment]
matplotlib 1.5.0 is (relatively) ancient. There has been numerous updates
since then.

However, I will point out that you are trying to save a vector form of a
10,000 x 10,000 pcolormesh. That is going to be a somewhat large file, I
would expect. Perhaps there are some things that could be made more
efficient, and might already be so if you run in py3k. Have you tried a
more recent version of matplotlib and python to see if the problem still
persist?

**Comment by jklymak** [comment]
... you can also rasterize... `pcolormesh(S, rasterized=True)`

**Comment by wheretobegin** [comment]
ok, thanks for the advice, I will upgrade matplotlib and python, and rasterize to see if any of them help.

Also @efiring, I forgot to mention that it also didn't work when I try to save the image as '.png'

**Comment by wheretobegin** [comment]
@jklymak rasterize works, thanks!
