### ISSUE TITLE
Suggestion: improve mark_inset by letting user choose all four corners (locs) 

### ISSUE THREAD

**Issue by JacobEFO** [matplotlib/matplotlib#10738]
Dear Matplotlib contributors

I first of all love your software and the project, it is so inspiring. I came across an idea myself using Matploblib (instead of my full Matlab license).

Let the user chose which corners from mark_inset refer to which corners on the zoom. Say lower-left corner of zoomed_inset_axes to upper-right on zoom. Is it clear, or do I need to elaborate?

Test code:

```python
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1.inset_locator import zoomed_inset_axes
from mpl_toolkits.axes_grid1.inset_locator import mark_inset

def func(x):
    return x**2

x = np.linspace(-10, 10, 100)
y = func(x)

fig, ax = plt.subplots()
ax.plot(x,y)

axins = zoomed_inset_axes(ax, 2, loc=2)
axins.plot(x,y)

x1, x2, y1, y2 = -2.5, 2.5, -2, 5
axins.set_xlim(x1,x2)
axins.set_ylim(y1,y2)

mark_inset(ax, axins, loc1=3, loc2=1, fc="none", ec="0.5")
plt.xticks(visible=False)
plt.yticks(visible=False)

plt.savefig("demo_mark_inset.png")
plt.show()
```

The previously shown code results in:
![demo_mark_inset](https://user-images.githubusercontent.com/22648097/37212917-d13ef636-23b0-11e8-8776-9bad1620ebb3.png)

For which I might want to control the line from the lower-left corner on the zoom in the upper-left corner to go to the upper-left corner of the zoom in the bottom.

I am very sorry for all this upper-left/lower-right stuff, but I am not entirely sure, which is the zoomed_inset_axes and which is the mark_inset.

If this is an easy task / contributor-friendly, I would love to help you guys out by implementing it and documenting it. 

Best regards JacobEFO

**Edit:** Simply added the syntax highlighting. I hope that you do not mind. @afvincent

**Comment by ImportanceOfBeingErnest** [comment]
You may specify the connection points of both connectors individually by changing the respective `loc1` and `loc2` attributes. 

```
patch, pp1,pp2 = mark_inset(ax, axins, loc1=3, loc2=1, fc="none", ec="0.5")
pp1.loc1 = 3 # inset_axes connector at lower left
pp1.loc2 = 2 # zoom patch connector at upper left
```

![image](https://user-images.githubusercontent.com/23121882/37225498-17cf4ad0-23d7-11e8-9749-89a6600a887b.png)

I'm not sure if it is necessary to include those as arguments, but there are indeed cases where it would be desireable (see e.g. what happens if you invert the axes [here](https://stackoverflow.com/questions/48976845/matplotlibs-inset-locator-with-inverted-axes)).

**Comment by afvincent** [comment]
xref #10227 , which is the issue that @ImportanceOfBeingErnest is referring to (if I am correct).

**Comment by JacobEFO** [comment]
Aha, I didn't know of that. Smart idea making the locs objects.

Seems like I need to find something else to contribute with :)

**Comment by ImportanceOfBeingErnest** [comment]
Well since the `loc1` and `loc2` attributes are not [documented](https://matplotlib.org/2.0.2/mpl_toolkits/axes_grid/api/inset_locator_api.html) anywhere, there might still be the need to decide if documentation can be improved or if setting those externally is even the proclaimed way to do it (I was just saying that it works.).

**Comment by JacobEFO** [comment]
Maybe it might be mote intuitive to decide that in the call of mark_inset. Maybe such as:

mark_inset(ax, axins, loc1=[1,1], loc2=[2,3])

or something similar. At least the documentation could use an improvement in that regard.
