### ISSUE TITLE
imshow crashes when in non blocking mode

### ISSUE THREAD

**Issue by smiddy** [matplotlib/matplotlib#10839]
### Bug report

**Bug summary**

When trying to use imshow in a non-blocking way, the image crashes. After the set pause of three seconds (when the image is responsive), the window with the image crashes and is not responsive anymore.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from skimage import data

img = data.coins()
imgplot = plt.imshow(img)
plt.show(block=False)
plt.pause(3)
check = input("is image correct?")
```

interactive mode
```python
import matplotlib.pyplot as plt
from skimage import data

img = data.coins()
plt.ion()
imgplot = plt.imshow(img)
plt.pause(3)
check = input("is image correct?")
```
**Actual outcome**
Window with plot crashes.

**Expected outcome**
Window should be still accessible

**Matplotlib version**

  * Operating system: Win 10, 64bit
  * Matplotlib version: 2.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): I tried Qt5Egg, WXEgg, TkEgg
  * Python version: 3.6.4
  * Jupyter version (if applicable):
  * Other libraries:  anaconda 5.0.1 64bit

Installed using anaconda 5.0.1 64 bit.

**Comment by tacaswell** [comment]
This is the expected behavior, see the text at https://github.com/matplotlib/matplotlib/pull/4779 for more details, but in short for the figure to be interactive there needs to be an event loop running to notice and do something about the user input.  `plt.pause` runs that loop while it is waiting and in interactive mode that event loop time-shares with the prompt which is also waiting for user input.  If you have not set up that integration then when you are waiting at the prompt the event loop is not running so the figure is non-responsive.  If you call `plt.pause` again the figure will be 'live' again.

**Comment by smiddy** [comment]
Thanks for the quick response. I was not aware of that. The problem is, that the window seems to be hanging/crashing and I receive error from windows when attempting to close it.
I have to search for another alternative to ask for user input while surfing/analysing a figure.

**Comment by tacaswell** [comment]
Windows thinks it is hung because GUI is not responding back to the OS either! It many meaningful senses windows is not wrong that the window has crashed (but it is just that you are not spinning the event loop).

Matplotlib has some gui-independent widgets (https://matplotlib.org/api/widgets_api.html) that you can use to build simple things like "Y/n" questions or you could commit to a GUI framework and just make a dialog window.

**Comment by smiddy** [comment]
Thank you Thomas for the information. I will have a look at the widgets. They should suit my case.
