### ISSUE TITLE
Toolbar icons too large in PyQt5 (Qt5Agg backend)

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#10891]
I just found out that the `Qt5Agg` has much more spacing around its toolbar buttons than the `Qt4Agg`

![image](https://user-images.githubusercontent.com/23121882/37978555-9f119fbc-31e6-11e8-9f23-59dba7e9c6dc.png)

Is this by design? I find the toolbar anyways takes a lot of unnecessary space, and in the Qt5Agg backend this is just too much.

Code for reproduction.
```
import matplotlib
import matplotlib.pyplot as plt
plt.figure(matplotlib.get_backend())
plt.plot([1,3,1])
plt.show()
```

**Qt4Agg-Case**: Windows 8.1, python 2.7, PyQt4, matplotlib 2.2.2, backend: Qt4Agg
**Qt5Agg-Case**: Windows 8.1, python 3.6, PyQt5, matplotlib 2.2.0.post634+gc29d9b21c (master?), backend: Qt5Agg

Spyder has equally sized icons in both versions.

![image](https://user-images.githubusercontent.com/23121882/37978838-53d0af2e-31e7-11e8-92e0-fc2c880b8cae.png)

and I would argue the same should be the case for matplotlib as well.

**Comment by tacaswell** [comment]
My knee-jerk guess is that this is related to the hi-dpi support....

**Comment by liches** [comment]
Verified that this issue is due to Qt5's hi-dpi support.
I tried running setting an environment variable to make it work for legacy apps as stated on [https://doc.qt.io/qt-5/highdpi.html](url) and it seems to fix it, but might lead to scaling/painting artifacts so probably not a long term fix.
Tested on Windows 10, python 3.7, PyQt5, matplotlib 3.0.2, backend: Qt5Agg
![image](https://user-images.githubusercontent.com/11037698/53739281-6216fe00-3e5f-11e9-9417-ab71063c653d.png)

**Comment by anntzer** [comment]
I think this has been fixed by #14509.

**Comment by ImportanceOfBeingErnest** [comment]
Well, no, it hasn't. The main issue is the space the icon bar takes vertically and that has stayed unchanged by #14509

**Comment by anntzer** [comment]
Ah, I see, sorry.
