### ISSUE TITLE
Get original image values from a colormap array

### ISSUE THREAD

**Issue by ChaitanyaKolluru1** [matplotlib/matplotlib#10916]
I have the following piece of code:

````
import matplotlib.cm as cm
# define arbitrary array
array = np.ones((100, 100))
jet_array = np.uint8(cm.jet(array) * 255)
````

I would like to know if there is a way to recover array from jet_array. Thanks!

**Comment by ImportanceOfBeingErnest** [comment]
This seems more like a question of how to efficiently use numpy, not really an issue with matplotlib, is it? 
Or would you like to propose to add this inverse mapping as a feature to the library?  
I can already tell you that since this inverse mapping is not generally possible (just in some cases where the colormap consists of unique colors) it's quite unlikely to be considered useful. You rarely want to have a function which may work in some cases and won't in others. 

If you need help implementing such a function, consider asking a question on Stackoverflow about it; or prior to that search for related questions. I happen to have answered a similar question over there, which would be a good place to start: [how-to-decode-color-mapping-in-matplotlibs-colormap](https://stackoverflow.com/questions/45177154/how-to-decode-color-mapping-in-matplotlibs-colormap).
