### ISSUE TITLE
"Bad" deprecation warning: "Invalid escape sequence" warning incorrectly flags LaTeX

### ISSUE THREAD

**Issue by kmtac** [matplotlib/matplotlib#10945]
### Bug report

**Bug summary**

"Bad" deprecation warning: LaTeX $\pm$ raises a DeprecationWarning: Invalid escape sequence \p. 
**Code for reproduction**

```python
import warnings
import matplotlib.pyplot as plt
warnings.simplefiler('always')
plt.text('Silly Error $\pm$ silliness')
```

**Actual outcome**

```
# If applicable, paste the console output here
>>> plt.title('Silly error $\pm$ silliness')
<stdin>:1: DeprecationWarning: invalid escape sequence \p
Text(0.5,1,'Silly error $\\pm$ silliness')

```

**Expected outcome**

No error -- This is LaTeX, surrounded by $ $, not an escape sequence.  (Note that the plot itself looks fine, with a plus-minus sign.)

**Matplotlib version**

  * Operating system: MacOs X
  * Matplotlib version: 2.2.2  
  * Matplotlib backend: notebook, Qt, MacOSX,  Tk
  * Python version: 3.6.2
  * Jupyter version (if applicable): 4.3.0
  * Other libraries: warnings

 conda
 default, conda-forge

**Comment by tacaswell** [comment]
This is not a Matplotlib warning, this is a warning from cpython

```
17:11 $ python
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import warnings
>>> warnings.simplefilter('always')
>>> a = '\p'
<stdin>:1: DeprecationWarning: invalid escape sequence \p
>>> 

```

The fix is to write it as `plt.text(r'Silly Error $\pm$ silliness')`

**Comment by WeatherGod** [comment]
Just wondering... is it at all possible to "intercept" these kinds of
warnings and add more information to it? Just wondering if it is at all
possible.

**Comment by tacaswell** [comment]
I suspect the best place to do that would be a PR into upstream cpython.

**Comment by WeatherGod** [comment]
I was thinking more along the lines of adding on a message that would be
relevant in the specific case of matplotlib text labels, like "..., if you
were making a LaTeX string, you should make a raw string like so: r'....'"

But as I think of it more, I realize that it is impossible because the
interpreter spots these problems without any context. Also, the string
could be getting passed in via other functions, or being saved as a
variable elsewhere. And I doubt that cpython pointing out exactly the
invalid escape sequence would be any more useful because that wouldn't
solve the confusion that LaTeX has a larger set of escape sequences.

I wonder if it is at all possible to detect if a string originated from a
raw string literal or not? We could then issue a warning ourselves if we
detect a non-raw string.

**Comment by tacaswell** [comment]
I'm pretty sure that we can not tell the difference between `r'\foo'` and `'\\foo'` (and for now '\foo') just as we can not tell the difference between `{}` and `dict()`.  The 'r' is an instruction to python on how to interpret the next bit of literal text as it parses it (see https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals).

I think the best we can do is make sure all of the mathtext / latex docs suggest using 'r'.
