### ISSUE TITLE
Adding a special color name for 'last color'.

### ISSUE THREAD

**Issue by rainwoodman** [matplotlib/matplotlib#10946]
### Bug report

Currently the CN color in color= keyword cycles through the color table. This provides a way to fix the color for several lines. But it is not as convenient. For example

```
plot(x, y1_1, color='C1', ls='-')
plot(x, y1_2, color='C1', ls='--')
plot(x, y1_3, color='C1', ls=':')

plot(x, y2_1, color='C2', ls='-')
plot(x, y2_2, color='C2', ls='--')
plot(x, y2_3, color='C2', ls=':')
```

If we want to change the color of y2 or y1, several (three) modifications must be made. 

The current way of eliminating the redudant color keyword is through the get_color() method of the returned object.

```
l, = plot(x, y1_1, color='C1', ls='-')
plot(x, y1_2, color=l.get_color(), ls='--')
plot(x, y1_3, color=l.get_color(), ls=':')

l, = plot(x, y2_1, color='C2', ls='-')
plot(x, y2_2, color=l.get_color(), ls='--')
plot(x, y2_3, color=l.get_color(), ls=':')
```
It breaks the alignment of code, and does not rhyme.

I propose adding a special color name `^` that represents the last color used. (I think `~` works as well, but we can support repeating the character for better alignment.) e.g.
```
plot(x, y1_1, color="C1", ls='-')
plot(x, y1_2, color="^^", ls='--')
plot(x, y1_3, color="^^", ls=':')

plot(x, y2_1, color="C2", ls='-')
plot(x, y2_2, color="^^", ls='--')
plot(x, y2_3, color="^^", ls=':')
```

Implementing this would require the axes object, in addition to storing the current position in the color cycle, another variable for the last used color.

Or perhaps this is already implemented recently -- just I couldn't find it in the documentation?

**Comment by anntzer** [comment]
What's wrong with `c = "C1"; plot(..., c=c)`?
I don't think it's worth adding such a feature.

**Comment by timhoffm** [comment]
I also think this is not needed.

Another alternative can be to adapt the [property cycle](https://matplotlib.org/tutorials/intermediate/color_cycle.html#cycling-through-multiple-properties).

**Comment by fredrik-1** [comment]
I would like such a feature and think it would be useful and simpler than the current solution when you use the default color when ploting in for example a function and want several plots with the same color. For example
```
def ploting(ax, x, y):
      ax.plot(x,y)
      ax.plot(x, y+1, color='^^', linestyle='--')

for y in ys:
      ploting(ax, x, y)
```




`

**Comment by efiring** [comment]
I'm strongly opposed to this; it just isn't worth the extra code and accompanying documentation.

**Comment by ImportanceOfBeingErnest** [comment]
I wouldn't oppose this idea as strongly as others do here because there isn't actually any way to get the current cycler color (see e.g. [this post](https://stackoverflow.com/questions/13831549/get-matplotlib-color-cycle-state)). So you can do `next(cycler)` but not `current(cycler)`. There is also no `ax.get_last_added_artist()` from which to get the color. 

So in total I do see that this would be non-trivial to implement, but I don't see that it wouldn't be useful.

**Comment by timhoffm** [comment]
There is no concept of "current" in iterators, so a simple `current(cycler)` does not exist. One can intercept and buffer the latest returned object and make it available via `cycler.current()`. And indeed, this sounds like a reasonable extension of the cycler API.

Would have to be discussed and implemented over there. There are some things to watch out. What's `current` for a new cycler: `None`  or an exception equivalent to `StopIteration`? What's current for a cycler  composed from a new and a used cycler?

**Comment by ImportanceOfBeingErnest** [comment]
Isn't that exactly the point? The user shouldn't need to care about such stuff; hence if something like `"^^"` (or name it as you wish) existed, it would simplify certain things a lot. 

Of course one can argue why not just specify the color manually (as this is usually easy) but with that argument one would not even need a cycler in the first place. 

In that sense (note that this is not meant to be runnable, it's to get the idea accross):

```
color=None  <==> cycler.next()
color="^^"  <==> cycler.current()
```
maybe even `.previous` could make sense. In the case of `current` pointing into nirvana it should of course fall back to `next`.

Finally mind that I'm not saying that this *needs* to be done urgently or at all, but just closing the idea seems a bit short-sighted.

**Comment by dstansby** [comment]
I'll re-open - I think this needs a fix in cycler first to be able to get the current state, and then we can thing of a good API on the Maptlotlib side to access it.

**Comment by jklymak** [comment]
I'm in the camp that this is not necessary, and would add another fragile piece of cruft to the API.  The original post gives two perfectly appropriate methods to achieve the same thing within the existing API.

**Comment by efiring** [comment]
A little perspective, please: we have very limited developer resources.  Is this *really* an enhancement at all, and if so, is it one that *really* is worth moving on now?  We have over 1000 open issues and close to 300 open PRs.  @dstansby was right to close it.

**Comment by tacaswell** [comment]
Regarding adding `.current` to cycler, one of the features (from my point of view) is that none of the iteration state lives on the `Cycler` object and `__iter__` return a plain generator object.  I think that all of this logic should live on the Matplotlib side ;)

If we were going to do this, I would probably adjust the logic where we decide if we need the next color from the cycle or not to look for the sentinal and instead of holding just the iterator of the propery cycle to play games with `tee` to also hold a on-back version.  On normal 'get next' we tee the leading one and then get the next color, for '^^' we would tee the trailing one and then get the next color.  You have to do it this way because we maintain 2 separate 'live' cycles on the Axes object.  Given that we can now hold more than color in the property cycle, would you want `^^' to work on all of them too?  We opted to only give the `'C*'` shortcuts for color, but not clear the same logic would apply here.
