### ISSUE TITLE
Cannot set text alignment in pie chart

### ISSUE THREAD

**Issue by mverleg** [matplotlib/matplotlib#10941]
This code:

    ax.pie(data.values(), labels=data.keys(), labeldistance=0.4, textprops=dict(horizontalalignment='center'))

Yields:

    TypeError: text() got multiple values for keyword argument 'horizontalalignment'

Caused by:

https://github.com/matplotlib/matplotlib/blob/cc44f57f49e98a5bff3da606a9e222bbb5e93f74/lib/matplotlib/axes/_axes.py#L2702
https://github.com/matplotlib/matplotlib/blob/cc44f57f49e98a5bff3da606a9e222bbb5e93f74/lib/matplotlib/axes/_axes.py#L2711

Possible solution:

The code sets the text alignment to left or right based based on where the label is. The error could be solved by putting ``horizontalalignment`` in (a copy of?) ``textprops`` instead of passing directly. It would onbly be added if ``textprops`` does not contain ``horizontalalignment``.

Analysis:

I'm not sure whether it's intentionally or accidentally impossible to override this. I would be happy if it were possible, but maybe not everyone agrees that it's desirable?

**Comment by ImportanceOfBeingErnest** [comment]
I cannot decide if this is worth "fixing" or not. Just note that you may use one of the two following methods to get your labels centered:

1. You may trick the `Text` by supplying `ha` instead of `horizontalalignment`; this is because `horizontalalignment` will be set first in the `Text`, further keyword arguments will be updated later.

       plt.pie(data, labels=labels, textprops=dict(ha='center'))
   This will work for horizontalalignment (ha) and verticalalignment (va) but not for `rotation`.

2. You may set the properties afterwards

       _, texts = plt.pie(data, labels=labels)
       plt.setp(texts, horizontalalignment="center")

**Comment by mverleg** [comment]
I think it would be elegant if the 'normal' way worked. But I don't foresee making a lot of pie charts, so I have no strong feelings one way or the other.

**Comment by ImportanceOfBeingErnest** [comment]
Ok, I changed the code in #10943. Let's see if people think that is useful.
