### ISSUE TITLE
Feature Request: Add annotations to heatmaps (imshow or pcolor*)

### ISSUE THREAD

**Issue by raheson** [matplotlib/matplotlib#10956]
I noticed that imshow or pcolor* do not have an option to add annotations to each box. 
Currently, MPL creates heatmaps such as the one below:
![image](https://user-images.githubusercontent.com/14614682/38330726-59899f3c-381f-11e8-9801-3b064ff138ab.png)

However, MPL does not have the ability to add values to each grid box such as the image below: 
![image](https://user-images.githubusercontent.com/14614682/38326052-c740c1e8-3812-11e8-8702-481c1f052da9.png)

This seems like a standard feature, which can enhance the readability of these heatmaps.  In addition, this can be very helpful when values are 0.01 apart. It can help the user distinguish the heatmap values more efficiently. A proposed solution to turn on these values would look like plt.pcolor(data, showvalues=true). 

Shouldn't this be included?

**Comment by ImportanceOfBeingErnest** [comment]
Labeling an imshow plot is as easy as 

```
data = ... # 2D numpy array
ax.imshow(data)
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        ax.text(j, i, "{:.2f}".format(data[i,j]), ha="center", va="center")
```

Plus you have all the freedom to do the labeling just the way you wish instead of relying on some automatism.  
Also note that seaborn allows autolabeling of their heatmaps. The reason is that those heatmaps are categorical by design, while pcolor and imshow are general purpose image plots. And you wouldn't want to label the latest image you took with your camera that way I guess.  
So I'm a bit sceptical if this is really needed, given how easy it is to invoke manually.

**Comment by efiring** [comment]
Maybe this should be in a gallery example or addition to a tutorial.

**Comment by ImportanceOfBeingErnest** [comment]
There is now a [heatmap example](matplotlib.org/gallery/images_contours_and_fields/image_annotated_heatmap.html) in the docs (via #11017).
