### ISSUE TITLE
How to initiate the format of a line in matplotlib?

### ISSUE THREAD

**Issue by lyw615** [matplotlib/matplotlib#10988]
For example,the declaration of a point :
my_point, = plt.plot([], [], 'bx', alpha=.5).But it comes to wrong,when i use the format like :
my_line, = plt.plot([,], [,], color='brown', linestyle='-')
or my_line, = plt.plot([[],[]], [[],[]], color='brown', linestyle='-').
Because i want to plot a line between two points with data storaged in list. I want to get the right format

# Paste your code here

#my_point, = plt.plot([], [], 'bx', alpha=.5)
#my_line, = plt.plot([,], [,], color='brown', linestyle='-')
```
  * Python version:3.6.4

**Comment by timhoffm** [comment]
@lyw615 This is not in a format we can work with.

1. Please state clearly: Is this a bug report a feature request or a request for help?
Only the former two should be posted as issues. As mentioned in reply to your first post #10985, use the mailinglist or stackoverflow for help.

2. Make sure that your post is readable, i.e. use markdown formatting. In particular, use triple-backquotes for code blocks.

**Comment by lyw615** [comment]
The statement is a  request for help.

**Comment by dstansby** [comment]
If you're looking for help, the best places to post are either:

- Stackoverflow: https://stackoverflow.com/questions/tagged/matplotlib
- The mailing list: https://mail.python.org/mailman/listinfo/matplotlib-users

I'm going to close this since it looks like you've posted it on Stackoverflow; if you thing you come across something that is a bug feel free to open an issue here.
