### ISSUE TITLE
Create independent option classes for each plotter class (Line2D, etc.) so as to ease integration in other libs

### ISSUE THREAD

**Issue by smarie** [matplotlib/matplotlib#11044]
This is a feature proposal, not a bug. Please let me know if this is not the right place to file it.

It seems from the matplotlib version that I am using, that the list of valid plotting options are directly declared in their respective plotter constructor, i.e. options for [Line2D](https://matplotlib.org/api/_as_gen/matplotlib.lines.Line2D.html#matplotlib.lines.Line2D) are directly listed in the `Line2D` constructor. This makes it quite difficult for other libraries such as `pandas` to easily validate and/or specify the set of valid options accepted, leading to a 'rush to args completeness' (such as in [pandas.DataFrame.plot](http://pandas.pydata.org/pandas-docs/version/0.18/generated/pandas.DataFrame.plot.html)), and eventually to the 'giving up' option (the generic `kwds` argument at the end of the list, containing "Options to pass to matplotlib plotting method"). Users then stop getting any help from their IDE to get a list of valid options and description.

The absence of such objects makes it also more difficult to perform higher-level automation, such as reusing the same options (or part of the same options) for several plots in a row - which is actually the use case for `pandas.DataFrame.plot`.

I think that a better way exist and is quite simple to do. It would require two steps:
 * for each plotter object, create an independent class containing the configuration options. For example `Line2DOptions` for `Line2D`. The constructor of `Line2D` would continue to accept all keyword arguments as usual but would in addition also accept an instance of `Line2DOptions`  instead.
 * optionally, create a parent class `PlotterOptions` for all such options class, so that it is relatively easy to both retrieve all such options, and also for other libraries such as pandas to do some basic typechecking.

Food for thoughts...

**Comment by timhoffm** [comment]
This is the right place for feature proposals.

Passing options around is indeed a big topic in matplotlib. Since matplotlib uses several layers of abstraction and there are many parameters that influence a plot, we currently resort to the `**kwargs` strategy and discuss the possible values in the docstrings (better documentation is work in progress).

Option objects are an interesting approach. Let's see what this can do. Essentially, we would add an API for

~~~
plt.plot(x, y, options=Line2DOptions(linewidth=2, color='red'))
~~~

which would be equivalent to

~~~
plt.plot(x, y, linewidth=2, color='red')
~~~

#### Completion
You still won't get any help from your IDE for argument completion when using kwargs.
You will get completion for `Line2DOptions` but that's more verbose to read and write. I would use it only in special cases, when there are may parameters or when I want to reuse them.

#### API documentation for pass-through arguments
With `pandas.DataFrame.plot` I don't think it's a 'rush to args completeness' and eventually 'giving up'. This function is essentially putting a lot of matplotlib functions in a single call (e.g. legend, title, xlims, ...). This is motivated by a more compact notation for defining a plot. One can debate this approach but it has nothing to do with options for plot methods, e.g. there is not a single explicit argument for Line2D options.

All options are still part of the `kwds`. Moreover, this is quite a complicated case, because the supported parameters depend on  on the `kind` parameter. So even, with an `Options` class, they would have to document all the different option classes. Then again, it's not much of a difference if they link to a Line2DOptions class in matplotlib or link to Line2D and state that the kwargs are passed on.

#### Reusing
You can already achieve this by dict-unpacking
~~~
options = {'linewidth': 2, 'color': 'red'}
plt.plot(x, y, **options)
plt.plot(x, y2, **options)
~~~
A dedicated object has no advantage here.


### Summary
I don't see that options classes solve the issues you are proposing them for particularly well. Just for them, I would not want to introduce them.

However, option classes may have other benefits (maybe even only for internal use):
1. Parameter checking: `Line2DOptions.from_kwargs()` would be a standardized way for checking that the provided arguments are valid options. This could also encapsulate the handling of abbreviated names.
2. Type/Value checking: `Line2DOptions.from_kwargs()` could optionally check that the provided argument values are valid.
3. One could collect all the options in a single attribute `Line2D.options`(maybe only private). This would reduce the number of attributes and add a more clear structure what's really a configurable option parameter and what's some other variable. -- Not sure this really a good approach, but one can at least think about it.

**Comment by anntzer** [comment]
Honestly this just looks like trying to come up with our own half-baked version of traitlets -- in which case I'd rather have the full (if elusive) switch to traitlets.

**Comment by dopplershift** [comment]
In general I appreciate the problem you've identified here, and it's something that would be nice to deal with.  In this specific case, though, `Line2DOptions` would seem to be decoupling from `Line2D` things that really should be coupled with it.

**Comment by smarie** [comment]
thanks for the detailed answer @timhoffm !

@anntzer although interesting indeed, using traitlets is a separate/independent concern. 
 - You could use `traitlets` (or `attrs`, or the new data class PEP, or `autoclass` or equivalent) *without* separating out the options from the `Line2D` constructor into a dedicated `Line2DOptions` object, 
 - or you could create a dedicated `Line2DOptions` object *without* using traitlets, 
 - or you could do **both** (defining a `Line2DOptions` class with traitlets/attrs/dataclass/autoclass/...). +1 on this, I would totally encourage usage of one of those, to implement clearly defined type and value validation.

@dopplershift : think of this as a "companion class". Its purpose is not to be independent/decoupled, just to provide a convenient object to define options for a `Line2D` plot, without needing to actually create one (at least, not at the same instant). Of course as @timhoffm mentionned, users could just create a dictionary and store it in a variable, and use it later with the double-asterisk notation (`**opts`). That's just less convenient.

**Comment by dopplershift** [comment]
Fair enough. As far as `**opts` is concerned, you could make `Line2DOptions` work with that with proper implementations of `__iter__` and `__getitem__`.

**Comment by smarie** [comment]
Note that when using autoclass this comes out of the box:

```python
@autoclass
class Foo:
    def __init__(self, a, b):
        pass

f = Foo(1, 2)
# you can now use **f since it behaves like a dict
```

Such behaviour is sometimes desirable and sometimes not, that's why in `attr` they rather provide a `todict` method. But you can similarly do `**f.todict()`

**Comment by timhoffm** [comment]
I don’t think dedicated classes are the way to go. The supported kwargs should come out of the class, not be managed separately. We already use this concept of “artist properties” to generate the list of supported kwargs in the docs. A solution should be from this direction. Note also that there are ideas to define these more explicit. See  #22749 and topics linked therein.
