### ISSUE TITLE
handling datetime labels

### ISSUE THREAD

**Issue by mikkokotila** [matplotlib/matplotlib#11078]
Is there a best practice for handling datetime labels in terms of the frequency. Or at least something simple that actually works. The priority would be in an easy way to set the frequency of the labels. None of the below works:

```
plt.locator_params(nticks=4)

plt.locator_params(numticks=4)

plt.locator_params(nbins=4)
```
(from slackoverflow answers). 

At the moment the best way I found was using the Locators, which is IMO incredibly confusing, and seems to require figuring out the ideal frequency for a given dataset as opposed to just being able to say "5 ticks" and then having and even distribution of labels based on that.

**Comment by dstansby** [comment]
Have you tried setting the locator to a [MaxNLocator](https://matplotlib.org/api/ticker_api.html?highlight=ticker#matplotlib.ticker.MaxNLocator)? Something like
`ax.xaxis.set_major_locator(matplotlib.ticker.MaxNLocator(nbins=4)`.

**Comment by ImportanceOfBeingErnest** [comment]
You need to distinguish. There is the default `AutoLocator`, which does have a `nbins` argument, because it subclasses the MaxNLocator. This is used in cases where numeric values are shown on linear axes. 

There is also the `AutoDateLocator`, which is chosen if dates are plotted and which does not allow to set the "frequency". This is mainly because chosing some datetime interval according to a given number of ticks would generally result in pretty arbitrary tick locations. E.g. having 5 equally spaced ticks between March 3rd, 19:00 and March 5th, 03:00.. where would you put them?   
Instead, the `AutoDateLocator` by default tries to find out which time difference is usefully shown and adjusts the ticks accordingly. This mostly gives good results. But if it doesn't, you are free to use any of the other Locators, provided [in the dates API](https://matplotlib.org/api/dates_api.html#date-tickers).

That being said, `AutoDateLocator` actually does provide arguments `minticks` and `maxticks`. So in theory you could set them to the same number to obtain the desired result. In practice however this does not work, and you still end up with some other number of ticks (in the case below 3 instead of 6).

```
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from datetime import datetime

t = [datetime(2018,3,3,19), datetime(2018,3,5,3)]
plt.plot(t, [0,1])

loc = mdates.AutoDateLocator(minticks=6, maxticks=6)
plt.gca().xaxis.set_major_locator(loc)
fmt = mdates.AutoDateFormatter(loc)
plt.gca().xaxis.set_major_formatter(fmt)

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/38948909-24a259b2-4341-11e8-920b-714fc0f5c7dd.png)

I guess this can be an issue by itself though.

**Comment by mikkokotila** [comment]
Thanks a lot @dstansby , that's great. The set_major_locator works well. I'm looking at later to moving to a more flexible approach, and it looks like what @ImportanceOfBeingErnest is proposing, will allow doing just that. Thanks a lot!
