### ISSUE TITLE
Some API removals not documented

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#11252]
As noted in https://github.com/matplotlib/matplotlib/pull/10436#issuecomment-388945436, some APIs removed in https://github.com/matplotlib/matplotlib/pull/10426 were not documented as such and need an entry in the API changes.

**Comment by ImportanceOfBeingErnest** [comment]
The current online docs (the ones of version 2.2.2) still advertise to use `NavigationToolbar2TkAgg` in [the gallery example](https://matplotlib.org/gallery/user_interfaces/embedding_in_tk_sgskip.html) as well as in the [API docs](https://matplotlib.org/api/backend_tkagg_api.html#matplotlib.backends.backend_tkagg.NavigationToolbar2TkAgg).

![image](https://user-images.githubusercontent.com/23121882/40202941-dfa9e95c-5a23-11e8-9c37-ae067b4e02e4.png)

It doesn't tell anything about potential alternatives.


In view of this I think the deprecation is going too fast here. Even if the code isn't changed, at least a meaningful error should be raised instead of an ImportError with no indication what's wrong.  
And the documentation should already now clearly state the alternatives.
