### ISSUE TITLE
Histogram plot to support specifying colors for each patch as part of the color argument

### ISSUE THREAD

**Issue by AtmaMani** [matplotlib/matplotlib#11487]
### Enhancement request
**Enhancement summary**
Today the `bins` argument in `plt.hist()` supports explicit bin edges. Similarly, I would like to be able to specify exact color for each patch (bin) as a list of RGBA values. The list matches each custom bin I specify. This will allow me to create a multi-colored histogram. I plan to use the same set of colors for other charts so I can easily associate each patch across multiple charts.

**Code for reproduction - proposed**
```python
n, bins, patches = plt.hist(df['column'], bins=my_bins, color=cmap_list)
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/6750179/41793841-33bac4da-7612-11e8-94e4-c8075081d5a7.png)

**Workaround**
Today my workaround is to loop through each patch and update the `facecolor`
```python
import matplotlib.pyplot as plt
# build a histogram for the same class breaks as earlier chart
n, bins, patches = plt.hist(df['POPULATION'], bins=cbs_list)

# apply the same color for each class to match the map
idx = 0
for c, p in zip(bins, patches):
    plt.setp(p, 'facecolor', cmap_list[idx])
    idx+=1

plt.title('Histogram of POPULATION column')
```

**Matplotlib version**

  * Operating system: OSX
  * Matplotlib version: 2.0.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by timhoffm** [comment]
I'm against making it possible to style individual bars using the `hist()` API. `hist()` is rather a high-level function. It has the capability to handle multiple datasets to plot sets of side-by-side or stacked bars. In this context, `color` is already a list defining a bar color per dataset. Interweaving this with a per-bar color assignment would make the internal code more complex and the API more difficult to understand.

Since explicitly styling individual bars in a histogram is rather an edge-case. I don't want to take the burden on the code and API.

However, you can simplify the for loop in your example so that it's just two straight-forward lines:

~~~
import matplotlib.pyplot as plt

data = np.random.normal(size=1000)
nbins = 20
colors = plt.get_cmap('viridis')(np.linspace(0, 1, nbins))
n, bins, patches = plt.hist(data, bins=nbins)

# apply the same color for each class to match the map
for patch, color in zip(patches, colors):
    patch.set_facecolor(color)
~~~

**Comment by AtmaMani** [comment]
@timhoffm thanks for the context and explanation. I think your suggestion is good and I was not aware that you can plot histograms of multiple datasets in the same command. I agree, the `color` parameter would become complex in this case.

Closing the issue.
