### ISSUE TITLE
Matplotlib.pyplot.quiver does not accept X, Y, U, V and C as keyword arguments

### ISSUE THREAD

**Issue by niwatori1217** [matplotlib/matplotlib#11526]
### Bug report

**Bug summary**

Bug: matplotlib.pyplot.quiver cannot accept X, Y, U, V and C as keyword arguments, such operation leads to an `IndexError: pop from empty list` (if all of them are keyword arguments) or an `AttributeError: Unknown property *` (if part of them are keyword arguments). This error arises because line 444 in `quiver.py`, inside the constructor of Quiver class, only uses `*args` but excludes `**kw` for parsing of arguments X, Y, U, V and C, and thus nothing can be parsed from `*args` in the function `_parse_args` on line 385 if these arguments are given by keywords.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

x, y, u, v = 0, 0, .01, .02

plt.quiver(X=x, Y=y, U=u, V=v, units='xy', scale=1)
plt.show()
```

**Actual outcome**

```
Traceback (most recent call last):
  File "untitled.py", line 5, in <module>
    plt.quiver(X=x, Y=y, U=u, V=v, units='xy', scale=1)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3425, in quiver
    ret = ax.quiver(*args, **kw)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4872, in quiver
    q = mquiver.Quiver(self, *args, **kw)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/quiver.py", line 444, in __init__
    X, Y, U, V, C = _parse_args(*args)
  File "/usr/local/lib/python3.6/site-packages/matplotlib/quiver.py", line 393, in _parse_args
    V = np.atleast_1d(args.pop(-1))
IndexError: pop from empty list
```
And the error disappears if we write the code as `plt.quiver(x, y, u, v, units='xy', scale=1)`.

**Matplotlib version**
  * Operating system: Mac OS High Sierra
  * Matplotlib version: 2.2.2 (installed from pip3)
  * Matplotlib backend: MacOSX
  * Python version: 3.6.5

**Comment by tacaswell** [comment]
That does seem like a mistake, want to take a crack at fixing it @niwatori1217 ?

**Comment by niwatori1217** [comment]
Sure, I will open a PR today or tomorrow.

**Comment by anntzer** [comment]
Looking at this again I am tempted to say that we should just declare that these arguments are positional-only.  The problem is that adding keyword support is only going to make a confusing API even more worse: for example, do we expect that in
```
quiver(arg1, arg2, U=u, V=v)
```
`arg1` and `arg2` are considered as X and Y, but in
```
quiver(arg1, arg2, X=x, Y=y)
```
`arg1` and `arg2` are considered as U and V?
(Of course you can imaging even more funky cases involving passing e.g. X positionally and Y as keyword, but they are a bit artificial, whereas I don't think the above is.)

I think there's some similarly, the builtin `range` takes no keyword arguments.  Again, it would be pretty terrible if `range(3, stop=5)` meant `range(3, 5)` but `range(3, step=5)` meant `range(0, 3, 5)`...

**Comment by tacaswell** [comment]
I agree that the mix is very confusing, but would allowing all kwarg or all arg make sense?

**Comment by anntzer** [comment]
Honestly I don't really see the point... Documenting xyuvc as positional only seems simpler than "positional only, or all keyword".

**Comment by tacaswell** [comment]
fair enough.

**Comment by tacaswell** [comment]
@niwatori1217 Thanks for the suggestion, however we are probably not going to implement this :disappointed: .  Hopefully we will hear from you again!
