### ISSUE TITLE
pcolormesh with and without colorbar changes plot

### ISSUE THREAD

**Issue by muma7490** [matplotlib/matplotlib#11704]
### Bug report

**Bug summary**

Using pcolormesh to plot a spectrogram, the plot changes when applying a colorbar on the right hand side of the plot. This is only reproducable if the plot has sufficient points. Using less points creates the wished behaviour, i.e. both plots "look" the same. Looking at older plots done with this method, it seems the plot without colorbar is the "correct" one.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as pl

t = np.linspace(0,20,20)
f = np.linspace(0,20,10000)
i = np.sin(f*10000) + np.cos(f*7000)

for j in t:
    try:
        iMatrix = np.vstack((iMatrix,i))
    except NameError:
        iMatrix = i

pl.pcolormesh(f, t, iMatrix,cmap="gnuplot",vmin=np.amax(iMatrix)/10,vmax=np.amax(iMatrix))
pl.savefig("without_colorbar.png")
pl.colorbar()
pl.savefig("with_colorbar.png")
```

**Actual outcome**
![without_colorbar](https://user-images.githubusercontent.com/13886384/42930420-3ee3e586-8b3d-11e8-820d-4acbfc667ebd.png)
Result without colorbar
![with_colorbar](https://user-images.githubusercontent.com/13886384/42930415-3cfa206e-8b3d-11e8-819f-185768d992c1.png)
Result with colorbar.

**Expected outcome**
Both plots should look the same.

**Matplotlib version**

  * Operating system: Ubuntu 16.04, MacOS High Sierra, Windows 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend: TkAgg
  * Python version:3.5.2
  * Other libraries: numpy == 1.14.2

Libraries installed using pip, Python build from sources.

**Comment by jklymak** [comment]
Not following what you mean by "look the same".  Do you mean the data looks different?  One thing to keep in mind is the dpi you save your figure at - you have 10,000 points, but your figure (and monitor) only has 1200 pixels across a 6" figure.  So the individual points will be averaged; if you make the axes even smaller they will be averaged differently.  Try saving the above with 

I'm going to close because I don't think this is a bug.  Matplotlib has to downsample your data to display it.  If you don't like how the downsampling is happening you can downsample before plotting...
