### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by Tjerken** [matplotlib/matplotlib#11840]
I cannot install matplotlib. I do not know what to do. I also do not know how to handle the GitHub installer. I 'cloned,' but do not know how to install it. Can you help me out?

I want to use it with Sublime Text 3 (Python is already installed).

```
C:\Users\T>cd matplotlib
The system cannot find the path specified.

C:\Users\T>python -mpip install .
Directory '.' is not installable. File 'setup.py' not found.
```

**Comment by jklymak** [comment]
Thanks for your interest in matpltolib. This is not a matplotlib bug and is better handled on stackexchange or the mailing list.  GitHub is for bug reports or feature requests.

**Comment by ImportanceOfBeingErnest** [comment]
Note that if you want to install matplotlib in order to *use*  it, there is no need to install the development version; better use pip as shown in [installing an official release](https://matplotlib.org/users/installing.html#installing-an-official-release).

In case you want/need to install the development version as in [install from source](https://matplotlib.org/faq/installing_faq.html#install-from-source), the approach you took is in principle correct and something went wrong when cloning.

**Comment by jklymak** [comment]
... or install w/ anaconda (https://anaconda.org)...

**Comment by Tjerken** [comment]
Yes, I used anaconda, but that did not work.

**Comment by Tjerken** [comment]
Ah, this one worked, and thank you for your both responses.
```
python -mpip install -U pip
python -mpip install -U matplotlib
```
