### ISSUE TITLE
Errors in rendering boundaries between filled paths and within a quadmesh

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#1188]
This is the underlying problem raised in #1178.
It is illustrated by the test below; note that boundary anomalies are visible in all forms--agg on the screen, and pdf and svg displayed with a viewer--but in different places depending on the viewer and the size of the figure as rendered.
Note that the colorbar is rendered using pcolormesh, which has its own renderer with agg but otherwise is handled by draw_path_collection.

<pre>
import numpy as np
import matplotlib.pyplot as plt

z = np.arange(150)
z.shape = (10,15)

fig, axs = plt.subplots(2,2)

ax = axs[0,0]
cs0 = ax.contourf(z, 20)
cbar0 = fig.colorbar(cs0, ax=ax)

ax = axs[0,1]
cs1 = ax.contourf(z, 20, alpha=0.3)
cbar1 = fig.colorbar(cs1, ax=ax)

ax = axs[1,0]
im2 = ax.imshow(z, interpolation='nearest')
cbar2 = fig.colorbar(im2, ax=ax)

ax = axs[1,1]
im3 = ax.imshow(z, interpolation='nearest', alpha=0.3)
cbar3 = fig.colorbar(im3, ax=ax)

plt.savefig("test1.pdf")
plt.savefig("test1.svg")
plt.show()
</pre>

**Comment by dkxls** [comment]
Is there still somebody looking into this one? I'm using matplotlib 1.4.2 (linux-x64) and still get these white stripes in the colorbar or contourf plots.

I tested the pdf-files with various readers, i.e. okular (libpoppler), google-chrome, Adobe Reader/Acrobat XI‎ (both Windows), and always see these stripes. 
Interestingly, for the ps-files the issue is less pronounced but I would say still present.
The svg-files also have the same issue as the pdf-files.

The stripes almost disappear when I plot the same data twice (see the script below), but I consider this as a very bad workaround.

The only fix that works consistently is to set `edgecolor="face"`, but I guess that was also regarded as a workaround and not a fix.

Here is a script that shows how to reproduce and work around the white stripes for contourf plots and the colorbar. I hope it helps to debug and fix this problem.


```
#!/usr/bin/env python

""" This script illustrates a rendering bug for PDF and SVG files
"""

from matplotlib import pyplot as plt
import numpy as np

plt.close('all')

def gaussian_2d(x, y, x0, y0, xsig, ysig):
    return np.exp(-0.5*(((x-x0) / xsig)**2 + ((y-y0) / ysig)**2))

delta = 0.025
x = np.arange(-3.0, 3.0, delta)
y = np.arange(-2.0, 2.0, delta)
X, Y = np.meshgrid(x, y)
Z = gaussian_2d(X, Y, 1., 1., 1.5, 0.5)

fig, axs = plt.subplots(2, 2, sharex=True, sharey=True)

ax = axs[0,0]
C = ax.contourf(X,Y,Z, 50, cmap='gnuplot')
fig.colorbar(C, ax=ax)
ax.set_title('contourf')

ax = axs[0,1]
C = ax.contourf(X,Y,Z, 50, cmap='gnuplot')
C = ax.contourf(X,Y,Z, 50, cmap='gnuplot')
fig.colorbar(C, ax=ax)
ax.set_title('2x contourf')

ax = axs[1,0]
C = ax.contourf(X,Y,Z, 50, cmap='gnuplot')
Cbar = fig.colorbar(C, ax=ax)
Cbar.solids.set_edgecolor("face")
plt.setp(C.collections, edgecolor="face")
ax.set_title('contourf + edgecolor="face"')

ax = axs[1,1]
C = ax.contourf(X,Y,Z, 50, cmap='gnuplot')
plt.setp(C.collections, rasterized=True)
fig.colorbar(C, ax=ax)
ax.set_title('contourf + rasterized')

fig.savefig('./Gaussian2D.ps')
fig.savefig('./Gaussian2D.pdf')
fig.savefig('./Gaussian2D.svg')
fig.show()
```

**Comment by jenshnielsen** [comment]
As far as I understand this is a bug in the pdf renders which there is very little we can do about. If you draw 2 faces next to each other with no overlap a gab will often show due roundoff/snapping (Adobe seems to handle this better than most others in my tests). 

We can't draw them with an overlap in general since that would break partially transparent contours with alpha< 1. Try adding alpha=0.5 to all your contourf calls to see what I mean i.e ```ax.contourf(X,Y,Z, 50, cmap='gnuplot', alpha=0.5)``` and so on. 

Using `edgecolor='face' ` is a workaround which adds a small border to all faces. The border gives an non zero overlap which looks strange when alpha<1 but is otherwise perfectly fine. I would consider that a way better solution than plotting the data twice.

**Comment by dkxls** [comment]
Alright, I see! So it really is related to the PDF renderer after all, this hasn't been clear to me from the discussion above.
But, as I said all PDF renderer I tested, including the newest Adobe ones, show the same issue. I cannot even say that Adobe is doing better then the other ones. 

So the reason why `edgecolor='face'` is not set by default is due to issues related to transparency. In that case, couldn't one add `edgecolor='face'` for all plots where alpha is not explicitly set, something like:
```python
if edgecolor=None and alpha=None:
    edgecolor='face'
```
I have no idea of the matplotlib internals, so I don't know where this should be best implemented.

**Comment by jenshnielsen** [comment]
It might be possible to do something like that. I would have to think some more about this. 

In my original use case way back in 2012 this was only an issue for colorbars where the edges are straight. In this case Adobe seems to handle it correctly and the patch in the attached bug report fixed it for Evince on Ubuntu. It seems to be somewhat worse in your use case and still not really fixed.

Briefly:

Using preview on OSX:
I see stripes in both the contourf and the colorbar.

Using Adobe reader XI: 
I only see the stripes in the contourf but the colorbar looks fine.

**Comment by dkxls** [comment]
I actually agree with you that for plots with alpha=1 this workaround just works "perfectly fine".

So, I took a look at the source code, and for `contourf` plots, this workaround could probably be implemented like this:
```diff
--- anaconda/lib/python2.7/site-packages/matplotlib/contour.py	2014-10-23 20:53:19.000000000 +0300
+++ tmp/contour.py	2015-02-03 16:45:46.267598199 +0200
@@ -942,10 +942,14 @@
                 paths = self._make_paths(segs, kinds)
                 # Default zorder taken from Collection
                 zorder = kwargs.get('zorder', 1)
+                if self.alpha is None:
+                    edgecolors='face'
+                else
+                    edgecolors='none'
                 col = mcoll.PathCollection(
                     paths,
                     antialiaseds=(self.antialiased,),
-                    edgecolors='none',
+                    edgecolors=edgecolors,
                     alpha=self.alpha,
                     transform=self.get_transform(),
                     zorder=zorder)
```

**Comment by dkxls** [comment]
For `pcolormesh` this could be fixed directly in the high level function declaration like this:
```diff
--- anaconda/lib/python2.7/site-packages/matplotlib/axes/_axes.py       2015-02-03 16:35:25.849881579 +0200
+++ tmp/_axes.py        2015-02-03 17:27:50.467826037 +0200
@@ -5083,7 +5083,10 @@
         vmax = kwargs.pop('vmax', None)
         shading = kwargs.pop('shading', 'flat').lower()
         antialiased = kwargs.pop('antialiased', False)
-        kwargs.setdefault('edgecolors', 'None')
+        if alpha is None:
+            kwargs.setdefault('edgecolors', 'face')
+        else
+            kwargs.setdefault('edgecolors', 'None')
 
         allmatch = (shading == 'gouraud')
```

Please note that all these suggestions are untested, and the colorbar would still need some additional work, since the function call to `pcolormesh` sets `edgecolors='None'` explicitly.

**Comment by tacaswell** [comment]
@dkxls Sorry your comments went unnoticed for so long.  Can you put those changes in a PR?

**Comment by efiring** [comment]
I'm uncomfortable with this hack; at the very least it needs to be checked with all backends to see what it actually does.  Although the postscript standard is for linewidths of zero to be a device-dependent minimum, I think that in all backends we are treating linewidths of zero as "don't draw that line at all".  If so, the hack will need some arbitrary small value for the linewidths.

**Comment by efiring** [comment]
As far as the colorbar is concerned, the problem has been reduced by #4481, which is also a bit of a hack.

**Comment by mlincett** [comment]
Is this bug the reason why saving an `hist2d` (which from the source I see it is drawn with `pcolormesh`) to PDF results in artifact grid? (Looks like aliasing from the pixels boundaries, and it is viewer-dependent.)

![sample](https://user-images.githubusercontent.com/1234470/115737843-ce7d5000-a38c-11eb-9452-12f82ddf236c.png)

As there are several workarounds suggested online, is there a recommended best practice?

**Comment by jklymak** [comment]
> is there a recommended best practice?

It depends on what you are trying to do and what you are trying to save to.    `edgecolor='face'` is a reasonable workaround for most cases.

**Comment by mlincett** [comment]
> > is there a recommended best practice?
> 
> It depends on what you are trying to do and what you are trying to save to. `edgecolor='face'` is a reasonable workaround for most cases.

I am trying to save the product of `Axes.hist2d` as a vector graphics file, and I had naively chosen PDF a output format. Since the final aim is the embedding into LaTeX documents, probably I could try with `(e)ps` but I am not sure if the problem could reappear in the final PDF output.

By the way, trying `edgecolor='face'` produces a funny jigsaw artifact (regardless of png/pdf output), see attachment. (It is not my intention to turn this issue into a support request, but since the `edgecolor` workaround was been proposed as a solution to be implemented in `pcolormesh` itself I thought it was worth mentioning.)

![jigsaw](https://user-images.githubusercontent.com/1234470/115746648-c88b6d00-a394-11eb-9478-f7d89a68786a.png)

**Comment by jklymak** [comment]
Try `hist2d(... rasterized=True)` and then specify an appropriate dpi for `savefig`.   That rasterizes the 2-d grid, but usually you don't need the polygons for a 2-D histogram.

**Comment by mlincett** [comment]
> Try `hist2d(... rasterized=True)` and then specify an appropriate dpi for `savefig`. That rasterizes the 2-d grid, but usually you don't need the polygons for a 2-D histogram.

Thanks, I think this is viable.

**Comment by jklymak** [comment]
I almost always do that *anyways* because usually a raster is smaller than a saved QuadMesh.  

The real problem is `contour` which does not rasterize so far as I know.

**Comment by gkatev** [comment]
Re: github-actions, this is still present in 3.6.3.

**Comment by jklymak** [comment]
@gkatev Can you tell us exactly what is still present?  This thread has _many_ different issues.

**Comment by gkatev** [comment]
Hi, yes, sorry for being vague. Below is where the issue is exhibited for me -- please let me know if it's not relevant.

This script reproduces the issue. Use this dataset: [data.txt](https://github.com/matplotlib/matplotlib/files/10843896/data.txt)

```python
#!/usr/bin/python

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('data.txt', delim_whitespace=True)
df = df.pivot(index='core_1', columns='core_2', values='latency')

plt.pcolor(df, cmap='YlGnBu', rasterized=False)
plt.savefig('c2c.svg')
```

The resulting svg file has unexpected white lines between the cells (viewing it in eog or in firefox).

![c2c](https://user-images.githubusercontent.com/31203804/221674937-bd395bbb-3952-4128-a6c5-c5c1c0e50a3d.svg)

**Comment by QuLogic** [comment]
I know I assigned this ages ago, but I'm planning to work on it for 3.8. Though at the moment, I don't know that there is any way to fix SVG.

**Comment by jklymak** [comment]
I think this is really hard to fix.  This is basically the same issue as with contours and arises because it is impossible to anti-alias properly: https://github.com/jklymak/contourfIssues. If you make your svg viewer not anti-alias this problem goes away.  However, I really suggest rasterizing the pcolor.  It can make for larger files, but pdf/svg viewers are pretty efficient at dealing with images in the svg.  

I actually think this should be closed as "can't fix", but maybe someone has a solution.

**Comment by QuLogic** [comment]
The original post is about all formats, and at least Agg and PDF can be fixed.
