### ISSUE TITLE
Streamplot supporting irregular grids with 2D x and y

### ISSUE THREAD

**Issue by lbdreyer** [matplotlib/matplotlib#12025]
Are there any plans to support streamplotting data on irregular grids?

Currently, the streamplot documentations states:
```
Draws streamlines of a vector flow.

x, y : 1d arrays
    an evenly spaced grid.
```

If my data is on an irregular grid, I currently have to interpolate to an evenly spaced grid before I can create a streamplot. This becomes a problem when the data is very large and interpolating takes a long time. 

To add more roadbloacks, my x and y values are 2D arrays. Are there plans to support 2D x and ys as input to the streamplot?

(cc @pp-mo for reference)

**Comment by pp-mo** [comment]
Just to add to this : If I **do** pass 2-D x + y arrays (same shape as the u + v) ... 
  * there is currently no error or warning
  * it produces a plot often quite plausibly correct
  * but on closer inspection, wrong (!)

That is nasty behaviour IMHO.  Certainly, it had me thinking it did work, for a while ...  :blush:  :flushed:  :nauseated_face:

**Comment by jklymak** [comment]
There is no reason that streamlines couldn’t be rewritten assuming non equal steps but it’d be a lot more code. Having it be a matrix of x and y points seems a lot harder.

**Comment by ImportanceOfBeingErnest** [comment]
The [streamplot example](https://matplotlib.org/gallery/images_contours_and_fields/plot_streamplot.html) takes in 2D arrays for X,Y,U, and V. So is the example wrong? It looks good to me on first sight. Also, it produces the same output when X and Y are supplied as 1D arrays.

What is the problem with 2D input that you experience? (A code with image and a description of undesired behaviour would be helpful for that.)

Concerning the problem of irregular grids, one can always interpolate onto a regular grid first. Whether this is done by matplotlib internally or by the user externally does not make either way more or less efficient, only more convenient to use.  
There are some other functions which only take regular grids. So if such internal solution is desired it might make sense to introduce it for all functions which would benefit from it. 
Because matplotlib has a `matplotlib.tri.LinearTriInterpolator`, there would not be too much work involved. Still, because it is so easy to do the interpolation externally, I would doubt this has high priority.

**Comment by jklymak** [comment]
Theoretically, the integration for making the streamplot need not be done on regularly spaced 1-d x/y grids.  You just need to replace dx/dy = constant by a varying function.  But the streamplot code is all written assuming dx/dy are constant;  I'm not wholly convinced that the streamplot code could not be simplified a fair bit *and* made to accept vadying dx/dy, but thats not a project I'm going to take on. 

We could always make a regular grid for users, but I'd be against us doing that versus making the user do it because gridding data often requires some artistic license, and better to let the user decide what works best for them.

**Comment by pp-mo** [comment]
> gridding data often requires some artistic license
> We could always make a regular grid for users, but I'd be against us doing that versus making the user do it because gridding data often requires some artistic license

I agree.  There is no such thing as a general-purpose regrid algorithm.
Though in the case of streamplots, the relationship between the original data and what you see is in any case much less direct :  Compared to contouring, for example, you can't easily either predict or control where it will draw the lines.

From our parochial point of view, we will generally be drawing out plots onto maps via Cartopy.
So if we did use regridding, then the Iris code probably has better context for defining a suitable target grid than matplotlib does.

However, the existing facility still seems a bit clunky to me. 
At the least, when it produces a plot that is plausible but wrong, with no warning, that is a nasty gotcha !

**Comment by afvincent** [comment]
I did not have time to read the post very carefully but there may be some implementation ideas [here](https://www.flannaghan.com/2013/02/23/interpolation) on unevenly gridded data (even though it is likely to be based in a rather old version of streamplot).

**Comment by liangwang0734** [comment]
One possible mechanism to integrate 1-step from `(x0, y0)` to `(x1, y1)`:
- Interpolate to find velocity `(u, v)` at `(x0, y0)`
  - Nearest or bilinear interpolation.
- Step to `(x1, y1)` using `(u,v)` in a standard `rk12` scheme (that `streamplot` is using)
- Check location of `(x1, y1)` for termination.

Additional processings like re-scaling the coordinates and velocities could also be important for getting optimal results.

**Comment by jonnyhtw** [comment]
I'd love for this to be a possible feature! Thanks.

**Comment by jhollowed** [comment]
Commenting in the hopes that this can be revisited (do issues work like that)? The limitation of evenly-spaced data for `steamplot()` is a pretty significant one, and it is not consistent with the rest of matplotlib. While I understand the sentiment that it's difficult to obtain a general-purpose regridding solution that won't be incompatible with at least some use cases... Matplotlib seems to already have a precedent for this, in that all of the `contour` functions must be applying some interpolation, no? In any case, this fix linked to by @afvincent seems so straightforward that it should be worth implementing.

**Comment by jklymak** [comment]
Contour does _not_ do any regridding.  It just decides where between two consecutive points the contour should pass and doesn't care about how far apart any pair are. 

Streamplot could pretty readily do the same thing.  But it would need to be rewritten.  As noted above, I don't think regridding is necessary or even desirable.  However it is likely that a more general code would best done in c rather than Python.
