### ISSUE TITLE
Move visibility check to allow_rasterization

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#12040]
Currently, most implementations of draw() start with a check on get_visible() to immediately return if the artist is not visible.  Most implementations of draw() are also decorated with allow_rasterization to, well, allow rasterization.

An exception to the former is QuiverKey; modifying e.g. the quiver_simple_key demo shows that QuiverKey does not respect the visibility flag.

While this could be fixed in place, I'd suggest instead to move the visibility check to the top of allow_rasterization, which will allow removing it from all actual implementations (of course, if there are artists that really don't want to be rasterizable (if there are any?), then they will need their own visibility check, and converserly if they don't want to obey the visibility flag (but I'd think most cases are just bugs)).

... in which case it may be worth renaming allow_rasterization to e.g. draw_wrapper or check_visibility_and_allow_rasterization (depending on the extent to which we want the name to state the functionality).  Or we can just add another check_visibility decorator, but I guess it's a bit performant to have just one wrapper instead of two (no numbers to confirm that statement).

**Comment by ImportanceOfBeingErnest** [comment]
Having `allow_rasterization` manage whether the function decorated with it would actually do something would be confusing, simply because there is no way of judging on that behaviour from its name. 

Using a `check_visibility_and_allow_rasterization` decorator will lead to the need of a `check_visibility_and_dont_allow_rasterization` as well, which creates an unnecessary double structure. 

An additional and independent decorator `check_visibility` may be an option, but is it really good style to defer a check like this to a decorator? Also the net gain would be to replace two lines 

    if not self.get_visible():
        return

by a single line

    @check_visible

One would also need to make sure different draw methods do not use some more sophisticated and/or more individualized logic, in which case at least part of the logic still needs to exist in the `draw` method itself. 

Readability matters; and I feel like in this case the benefits of using a decorator are too low to sacrifice readablity. 

I think this would be different if a performance *gain* was to be expected from using a decorator. But I don't see that to be the case.

**Comment by anntzer** [comment]
Well, the point above is that the first case I found of not checking visibility is a bug (quiverkey), and I'd be puzzled if there were cases where we really don't want to check it -- just like not allowing rasterization for 3D artists was an oversight (https://github.com/matplotlib/matplotlib/pull/10013).
Having a single decorator to apply around draw() would make this less likely to be forgotten.  I agree that splitting into a second decorator mostly defeats the purpose of the proposal.

**Comment by anntzer** [comment]
Let's just track the actual visibility bug at #25890.
