### ISSUE TITLE
Weird behaviour of suptitle() when horizontalalignment is not 'center'

### ISSUE THREAD

**Issue by gansanay** [matplotlib/matplotlib#12197]
### Bug report

**Bug summary**

`horizontalalignment = 'left'` aligns the title on the right, `horizontalalignment = 'right'` aligns a short title on the left, `horizontalalignment = 'right'` displaces a longer title on the far left

**Code for reproduction**

```python
# Left alignment test, short title
fig = plt.figure(figsize=(9,4))
ax = fig.add_subplot(111)
fig.suptitle('This figure suptitle should be on the left', horizontalalignment = 'left')
ax.set_title('This axis title should be on the left', loc='left');
fig.savefig('left_align.png')

# Right alignment test, short title
fig = plt.figure(figsize=(9,4))
ax = fig.add_subplot(111)
fig.suptitle('This figure suptitle should be on the right', horizontalalignment = 'right')
ax.set_title('This axis title should be on the right', loc='right');
fig.savefig('right_align.png')

# Right alignment test, longer title
fig = plt.figure(figsize=(9,4))
ax = fig.add_subplot(111)
fig.suptitle('This figure suptitle should be on the right but it is far left', horizontalalignment = 'right')
ax.set_title('This axis title should be on the left', loc='left')
fig.savefig('far_left.png');
```

**Actual outcome**

* Left alignment test, short title
![left_align](https://user-images.githubusercontent.com/3726359/45871500-f435b900-bd8d-11e8-9d57-754958f583b4.png)

* Right alignment test, short title
![right_align](https://user-images.githubusercontent.com/3726359/45871566-116a8780-bd8e-11e8-968c-58f873505e19.png)

* Right alignment test, longer title
![far_left](https://user-images.githubusercontent.com/3726359/45871581-192a2c00-bd8e-11e8-8540-e78304e9ccc6.png)

**Expected outcome**

The following code manually sets the figure title at the expected position:

```python
fig = plt.figure(figsize=(9,4))
ax = fig.add_subplot(111)
fig.suptitle('This figure suptitle is long but it is manually positioned', x = 0.38)
ax.set_title('This axis title should be on the left', loc='left')
fig.savefig('manual_pos.png');
```
Which gives:
![manual_pos](https://user-images.githubusercontent.com/3726359/45871836-b4bb9c80-bd8e-11e8-94e9-e453adc39fda.png)

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 2.1.2 and 2.2.3
  * Matplotlib backend: agg
  * Python version: 3.6.4
  * Jupyter version: 4.4.0

**Comment by ImportanceOfBeingErnest** [comment]
This is all expected. The `suptitle` is in all cases positionned in the horizontal center of the figure. `horizontalalignment` aligns the text relative to this center position, i.e. if for `horizontalalignment=left`, the left end of the text is at the center position, for `horizontalalignment=right` the right end of the text is at the center.

![image](https://user-images.githubusercontent.com/23121882/45878172-6dd6a280-bda0-11e8-8d67-fbad7502cc1e.png)

The `suptitle` does not have a `loc` parameter. In order to position a `suptitle`  you may however use the `x` and `y` arguments. The position is in figure coordinates. So if you want to have a suptitle aligned with the (only) subplot in a figure you may set its position according to the subplot paramters, e.g. the left parameter (`fig.subplotpars.left`) is 0.125. You will still need to set the aligment as well.

```
fig = plt.figure(figsize=(9,4))
ax = fig.add_subplot(111)
fig.suptitle('This figure suptitle should be on the left', 
             horizontalalignment = 'left', x=fig.subplotpars.left) # x=0.125
ax.set_title('This axis title should be on the left', loc='left');

# Right alignment test, short title
fig = plt.figure(figsize=(9,4))
ax = fig.add_subplot(111)
fig.suptitle('This figure suptitle should be on the right', 
             horizontalalignment = 'right', x=fig.subplotpars.right) # x=0.9
ax.set_title('This axis title should be on the right', loc='right');

# Right alignment test, longer title
fig = plt.figure(figsize=(9,4))
ax = fig.add_subplot(111)
fig.suptitle('This figure suptitle should be on the right and it actually is.', 
             horizontalalignment = 'right', x=fig.subplotpars.right) # x=0.9
ax.set_title('This axis title should be on the left', loc='left')

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/45878701-513b6a00-bda2-11e8-8d80-e0418cc07ab5.png)


I will close this because I don't think there is anything wrong with the library here. Feel free to reopen in case you disagree.

**Comment by gansanay** [comment]
Thank you for your answer!

Do you agree this should be documented?

**Comment by ImportanceOfBeingErnest** [comment]
[`subtitle`](https://matplotlib.org/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.suptitle) documents 
> `x` : float, default 0.5 The x location of the text in figure coordinates.
 `y` : float, default 0.98 The y location of the text in figure coordinates.
 `**kwargs`: Additional kwargs are [`matplotlib.text.Text`](https://matplotlib.org/api/text_api.html#matplotlib.text.Text) properties.

[`matplotlib.text.Text`](https://matplotlib.org/api/text_api.html#matplotlib.text.Text) documents

> horizontalalignment: {'center', 'right', 'left'}

There is the [Text alignment example](https://matplotlib.org/gallery/text_labels_and_annotations/text_alignment.html) which shows the different alignments. 

At which point exactly do you think the documentation should be extended? We're always open to improvements of the docs, so feel free to make a suggestion here.

**Comment by timhoffm** [comment]
`suptitle` could be more precise in documenting `horizontalalignment` and `verticalalignment` e.g.

`The horizontal alignment of the text relative to (*x*, *y*)`.

Feel free to open a PR.

**Comment by ImportanceOfBeingErnest** [comment]
Since `horizontalalignment` isn't really an argument of `suptitle` but part of the kwargs, which are passed on to `Text`, do you feel one should make an exception here and document this kwarg explicitely?

I would have though maybe documenting `Text`'s [horizontalalignment](https://matplotlib.org/api/text_api.html#matplotlib.text.Text.set_horizontalalignment) in a bit more than half a sentence could make sense? 

(reopening this to let the discussion evolve)

**Comment by thoo** [comment]
Should I also need to generate any file? Thanks.
