### ISSUE TITLE
c and cmap for plot

### ISSUE THREAD

**Issue by jessebett** [matplotlib/matplotlib#12298]
I want to produce a plot where the colour along the curve changes according to a colours array. I'd expect this to have the same api as `scatter` but it appears `plot` doesn't have a `cmap` attribute?

Can someone tell me what settings I need to give to `scatter` so that it behaves like default `plot` but with `cmap` provided to it?

**Comment by jessebett** [comment]
`plt.scatter(xs, ys, s=0.5, marker=None, linestyle='-', c=ys, cmap= 'viridis')` for example. Why couldn't `plot` take colormap to produce something like this?

**Comment by jklymak** [comment]
@jessebett Please run these sorts of things past stackoverflow before opening an issue.  You will get lots of community support there...

https://matplotlib.org/examples/pylab_examples/multicolored_line.html

**Comment by jessebett** [comment]
@jklymak I opened the issue here because I was wondering if there's a reason the plot api doesn't handle cmap.

**Comment by WeatherGod** [comment]
Yes, there is a reason. The plot() command is intended to be used for
generate uniformly colored markers. The python objects that backs a plot()
is optimized by assuming that all the markers for a line are the same and
will "stamp" them, greatly reducing the memory and time needed to render
them. Meanwhile, the scatter() function is intended to be used as a
"ScalarMappable" where the markers can exhibit a peroperty (i.e., color or
size) that is a function of some other parameter. The colormap is one way
to apply such a function.

**Comment by jklymak** [comment]
The `plot` API is already greatly overloaded.  If someone wanted to take the example linked above and make it a new axes API that might be looked upon favourably.

**Comment by WeatherGod** [comment]
Indeed, the ability to have lines that changes color would be great! See
this example:
https://matplotlib.org/gallery/lines_bars_and_markers/multicolored_line.html

It is kludgy. Part of the problem is that with our current design, a "line"
is assumed to have a uniform property: color, width, style, etc. So the
example above gets around that by creating a LineCollection of many line
segments, which are all passed to the renderer as separate lines. If we
want true dynamic line support, we would need to expand our API with AGG
and Cairo.
