### ISSUE TITLE
Matplotlib plt.Rectangle Incoherent Results

### ISSUE THREAD

**Issue by totyped** [matplotlib/matplotlib#12335]
### Bug report

**Bug summary**

Matplotlib plt.Rectangle does not produce coherent pdf results: Overlap where there should be none !
Maybe other shapes have the same issue.

**Code for reproduction**
```python
import matplotlib.pyplot as plt

def save_fig(layer):
    # Hide the right and top spines
    ax.spines['right'].set_visible(False)
    ax.spines['top'].set_visible(False)
    # Sacale axis
    plt.axis('scaled')
    fig.savefig(layer+'.pdf', dpi=fig.dpi)
    fig.savefig(layer+'.jpeg', dpi=fig.dpi)

gap =10
fig, ax = plt.subplots()
rectangle_gap = plt.Rectangle((0-gap, 0), 500+2*gap, 100+gap, color ="green");
plt.gca().add_patch(rectangle_gap);
rectangle = plt.Rectangle((0, 0), 500, 100, color = "red");

plt.gca().add_patch(rectangle)
rectangle = plt.Rectangle((0, 100+gap), 500, 100, color = "blue");
plt.gca().add_patch(rectangle);


save_fig("test")
```

**Actual outcome**
 
![image](https://user-images.githubusercontent.com/32427425/46242729-6cbefa00-c3cc-11e8-99b9-bdcd05d4aea5.png)

This seems okay, but when I increase the length of the top blue rectangle to 2000:

![image](https://user-images.githubusercontent.com/32427425/46242742-937d3080-c3cc-11e8-9051-d82a8f584e92.png)

Zoom in:
![image](https://user-images.githubusercontent.com/32427425/46242748-9e37c580-c3cc-11e8-993a-86342d907801.png)

The overlap gets worse with the increasing length along x-axis. 
See: https://stackoverflow.com/questions/52518140/weird-behavior-of-matplotlib-plt-rectangle?noredirect=1#comment91989045_52518140

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.5
  * Jupyter version (if applicable): 1.0.0

 conda
 default

**Comment by jklymak** [comment]
Set the linewidth property of all your Rectangles to 0 (`linewidth=0`).  I'm going to close, but feel free to comment if you think that doesn't fix your problem.

**Comment by totyped** [comment]
Yes ! This fixes the problem ! Thanks a lot !! 
However, why would it not work "out of the box" ? I don't understand if I made something wrong, or if it is really a bug in matplotlib.

**Comment by jklymak** [comment]
The line is 1 pt wide and 0.5 pt overlaps your rectangle edge.  You were making plots so small this was visible.

**Comment by totyped** [comment]
I understand ! Thank you so much !! 👍

**Comment by tacaswell** [comment]
I don't think you did anything wrong nor do I think this is a bug, just that the default behavior is not what you needed.

By default patches (of which `Rectangle` is a subclass) are drawn with a 1 pt think border which defaults to the same color as the patch with the edge of the patch going through the center of the border line.  You could argue that the default line width of the border should be 0, but then if users want to change the color of the border would be surprised when it had no effect (with out also changing the line width).  Making the default linewidth depend on if the border is the same color as the face would also be very confusing (as the on-screen shape would change based on the colors!). 

Another tricky thing about this is that the position and shape of the rectangle is specified in data-units, but the thickness of the border is in absolute units (pts, which are 1/72 of an inch).  If you zoomed in by changing the axis limits (rather than by zooming in on the pdf) you would have gotten different results.

**Comment by totyped** [comment]
@tacaswell Thanks a lot for your comment !!
