### ISSUE TITLE
Function to draw angle between two lines

### ISSUE THREAD

**Issue by daniel-s-ingram** [matplotlib/matplotlib#12414]
Would anyone be interested in having a function to draw an angle? I made a function for this that you can see here:  

https://github.com/AtsushiSakai/PythonRobotics/blob/master/ArmNavigation/two_joint_arm_to_point_control/Planar_Two_Link_IK.ipynb  

If this is something enough people are interested in, I can clean the code up and submit a PR for it.

**Comment by ImportanceOfBeingErnest** [comment]
Thanks for reaching out. I think this is probably a bit too specialized to get its own function in the library; on the other hand, I suppose a lot of people might make use of something like that. So to strike a balance, one could opt for providing this as an example in [the gallery](https://matplotlib.org/gallery/index.html).  
Let's see what others think.

From the code perspective I'm wondering if using a [`matplotlib.patches.Arc`](https://matplotlib.org/api/_as_gen/matplotlib.patches.Arc.html) wouldn't be better suited? I also think one would usually desire this arc to be at a fixed distance/radius to the intersecting point, independent on the axis limits or zoom level, and also have it appear circular even with unequal aspect. An example showing this would definitely be useful.  
I haven't thought this through, so I don't know if there is a good solution possible only with transforms or whether one would need to write a callback for this.

**Comment by WeatherGod** [comment]
I have wondered if it would make sense to update join-style a bit to allow
for drawing arcs like this. Gotta watch out though, because usually such
arcs are drawn as a different color or linewidth than the original line.

**Comment by daniel-s-ingram** [comment]
@ImportanceOfBeingErnest 

I agree about having the arc appear circular for any aspect ratio; that's something I can look into. I disagree about the fixed radius, however, as I found it useful to be able to increase or decrease the radius for my diagrams, so why not have that as an optional argument?

**Comment by ImportanceOfBeingErnest** [comment]
Of course the radius should be a parameter to be set programmatically. By "fixed" I mean if you zoom in and out, the radius on screen should be the same. I.e the radius is fixed in screen coordinates, not fixed in data coordinates.

<details>
 <summary>Detailed description</summary>
 
### Original View
![image](https://user-images.githubusercontent.com/23121882/46563394-759a5900-c901-11e8-8ced-6b3cdc80d37b.png)

### Zoom
The angle is scaled together with the data.
![image](https://user-images.githubusercontent.com/23121882/46563407-8e0a7380-c901-11e8-9d50-dad4d14dbc0c.png)

### Expected when zooming

The angle marker should still be the same amount of pixels distant to the intersecting point.

![image](https://user-images.githubusercontent.com/23121882/46563571-839ca980-c902-11e8-9174-4efa0a026e64.png)


</details>

<p> 
<p> <br>
<p> 

The `join-style` idea is interesting, except I don't see how one can equip this with different linestyle, color etc. In addition the usual use case does not necessarily contain a single line, but probably several, or some polygon shapes. So the limit might be to create a single object of same color, linestyle etc. 

![image](https://user-images.githubusercontent.com/23121882/46564031-340bad00-c905-11e8-95f5-e85f36486d95.png)



Here everything that's black would be the line with the "funny" joint-style. Is that the idea?

**Comment by daniel-s-ingram** [comment]
Ah, my mistake, I misunderstood. I'll see if I can put together something more robust over the next few weeks. I think you're right that this may work better as a submission to the example gallery, so should I update here or is there a better place for this exchange?

**Comment by ImportanceOfBeingErnest** [comment]
Yes, we can discuss here. Or, once you have something ready, you can submit a pull request with the example (examples are in [matplotlib/examples/](https://github.com/matplotlib/matplotlib/tree/master/examples), though I don't currently know which category this would best fit into).
