### ISSUE TITLE
Simple plot spacing bug: ylabel gets wrongfully removed from plot

### ISSUE THREAD

**Issue by Volker-Weissmann** [matplotlib/matplotlib#12428]
### Bug report

**Bug summary**

Matplotlib removes part of the plot

**Code for reproduction**

```python
import matplotlib.pyplot as plt
plt.ylabel("yLabel")
x = [1,4]
n = -4 #bug occurs if n is -4, -5 -6, or 6
y = [1*10**n, 4*10**n]

plt.plot(x,y, "r+")
plt.show()

```

**Actual outcome**

![-4](https://user-images.githubusercontent.com/39418860/46583726-62030580-ca5b-11e8-8fe8-67477c6520be.png)

As you can see: The ylabel is partly missing

**Expected outcome**

There should be a "yLabel" written on the y-Axis.

**Matplotlib version**

  * Operating system: Linux (Ubuntu 18.04)
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.6.6
  * Jupyter version (if applicable):
  * Other libraries: 

matplotlib was installed via pip3 install matplotlib

**Comment by jklymak** [comment]
Thats why things like `constrained_layout` and `tight_layout` are necessary.  By default, the axes only makes enough room for "normal" labels, but yours have a lot of decimal places, so the label is off the plot.

`plt.figure(constrained_layout=True)`

`plt.figure(tight_layout=True)`

or 
`plt.savefig(bbox_inches='tight')`

are the ways to handle this sort of problem.  

Closing because there is nothing automatic we can do to fix this.

**Comment by Volker-Weissmann** [comment]
Sorry, I did not know that these options exist. Thank you for your help.
