### ISSUE TITLE
pyplot signatures need more tests

### ISSUE THREAD

**Issue by jklymak** [matplotlib/matplotlib#12425]
_Originally posted by @jklymak in https://github.com/matplotlib/matplotlib/pull/12293/comment#issuecomment-427611217_

**Comment by timhoffm** [comment]
Not sure how to do this. Do you have anything particular in mind?

I don't think it's reasonable to test the whole API again. It should already be tested in the underlying Axes or Figure functions.

Essentially, #12293 was about the mapping of parameters. The boilerplate code should just pass everything through. That used to be simple with `*args, **kwargs` signatures. However, since we switch to explicit signatures where possible, the mapping must be done a bit more carefully.

One possibility might be to test the boilerplate code generator.

**Comment by timhoffm** [comment]
I don't see something useful to be done here. @jklymak Please reopen if you have a specific proposal.
