### ISSUE TITLE
Navigation toolbar loose track of zoom history when using LassoSelector on multiple subplot with commant plt.sca

### ISSUE THREAD

**Issue by VaelK** [matplotlib/matplotlib#12534]
### Bug report

**Bug summary**
Hello,
Navigation toolbar looses track of zoom history when using LassoSelector on a figure with multiple subplot and using the command plt.sca in the callback function of LassoSelector.

**Code for reproduction**
Below is a working exemple. The manipulation is the the following. First zoom somewhere and then use LassoSelector, drawing anything with the mouse in the first plot. Then try go back to the origina view. It doesn't work. 
The only thing I can tel is that the zoom history is erased while executing plt.sca(ax[0])
*Edit Note:*
This is a simplifyed working excerpt of my application. In this application, I can only modify the funIHaveControlOver function. Thus I am bound to use the plotting handle function pltFun = plt.plot. There is no way I can write ax[0].plot instead because pltFun can be plt.scatter or some other plotting function instead. The code should be generic.

```python
import matplotlib.pyplot as plt

def funIHaveControlOver(pltFun,x,y,x1,y1):
    #This is the function I can modify
    from matplotlib.widgets import LassoSelector
    f, ax = plt.subplots(2, sharex=True)
    ax[0].scatter(x,y)
    ax[0].plot(x1,y1)
    ax[1].scatter(x,y)
    def onselect(x):
        plt.sca(ax[0])
        pltFun(x1,y1)
    lasso = LassoSelector(ax[0], onselect , button=[1])# only use left mouse button
    plt.show(block = True)

#This part of code cannot be modified (out of scope)
x = [0,1,2,3]
y = [4,5,6,7]
x1 = [0,3]
y1 = [4,7]
pltFun = plt.plot
funIHaveControlOver(pltFun,x,y,x1,y1)
```
**Initial plot**
![capture](https://user-images.githubusercontent.com/28605424/47021784-68306a80-d15c-11e8-8365-779587c181f1.PNG)

**Actual outcome after zooming somewhere and trying to go back to initial state by clicking "home"**

![capture](https://user-images.githubusercontent.com/28605424/47023973-1a6a3100-d161-11e8-9916-4ef2f11f8238.PNG)

In this plot I cannot go back to the original view

**Expected outcome**
I should have that after clicking "home":
![capture](https://user-images.githubusercontent.com/28605424/47024046-379eff80-d161-11e8-9551-d8cc1c37550d.PNG)

**Matplotlib version**
  * Operating system:  Windows 7
  * Matplotlib version: 3.0.0
  * Matplotlib backend : TkAgg
  * Python version: 3.6
matplotlib has been installed via anaconda (pip) with the default channel.

Thanks!

**Comment by ImportanceOfBeingErnest** [comment]
How exactly do you arrive at the "Actual outcome"? Why is the "expected outcome" a plot ranging from 0 to 4, when the initial plot ranges from 0 to 3?

It seems `sca` is not required here (but it shouldn't be responsible for anything related to the problen either). Is there a reason not to use 

```
def onselect(x):
    ax[0].plot(x1,y1)
```
?

However I would think that you need to draw the canvas after changing something. So in total, 

```
import matplotlib.pyplot as plt
from matplotlib.widgets import LassoSelector

x = [0,1,2,3]
y = [4,5,6,7]
x1 = [0,4]
y1 = [4,7]

f, ax = plt.subplots(2, sharex=True)
ax[0].scatter(x,y)
ax[1].scatter(x,y)
def onselect(x):
    ax[0].plot(x1,y1)
    f.canvas.draw_idle()
lasso = LassoSelector(ax[0], onselect , button=[1])
f.canvas.manager.toolbar.push_current()
plt.show()
```

**Comment by yvandenis** [comment]
Thanks for your reply,
I have update my post to be more specific about how I get the outcome. The expected outcome go to 4 because after using lasso selector we plot a line that goes up to 4. 
This is a non sens exemple, but it is just here to simlply show the problem. In real life i cannot use ax[0].plot(x1,y1) because the plotting function is stored in a variable instead :
'''
pltFun = plt.plot
...
pltFun(x1,y1)
'''

**Comment by yvandenis** [comment]
All right, my bad, its confusing so I edited my post. I realy want to go back to my initial state, with x ranging from 0 to 3, so my screenshot where wrong indeed. Should be correct now. In my real application, I do not add extra point outside the initial range, so it should be ok. 
That being said, the bug is still there. 
You said it is possible to manually modify the "home" view? May be there is a workaround here?

**Comment by yvandenis** [comment]
Well the code you provided is working but it uses the commande ax[0].plot(x1,y1) to draw the line. I can't use it like that since I have to use the function handle pltFun instead. To be more specific, in my application, this whole plotting code is actually embed in a function that takes the ploting function hanlde pltFun as input argument.
So, to make that clear what can be changed and what cannot, i edited my initial post.
Of course one solution is to make a if statement inside the function and check a whitelist of plotting function that are valid, however this approach is not generic and pretty ugly. 
I still think there is a bug here with matplotlib. I can't see any reason why plotting something else after zooming would erase the zoom history, but may be I missed something.
I will dive into matplotlib's code when I have time to find out more about it.

**Comment by anntzer** [comment]
Indeed, it appears that calling `sca()` destroys the navigation history.  This appears to take place via a callback installed in backend_bases
```
        @self.canvas.figure.add_axobserver
        def notify_axes_change(fig):
            # Called whenever the current axes is changed.
            if self.toolmanager is None and self.toolbar is not None:
                self.toolbar.update()
```
which I have moved recently to the base class, but has existed in each individual backend since forever (18dca6619db9c3844bcfc56580362f3a60b54f53, 2004).
(and `update()` does
```
    def update(self):
        """Reset the axes stack."""
        self._nav_stack.clear()  # <- the offending line.
        self.set_history_buttons()
```
)
I haven't thought much about why jdh intended to clear the nav history on sca() (perhaps there's a good reason for it), but in any case just deleting the offending line appears to fix the problem.

Haven't checked either what happens when using the toolmanager.
