### ISSUE TITLE
Overlapping 3D objects

### ISSUE THREAD

**Issue by Chutlhu** [matplotlib/matplotlib#12620]
### Bug report
When plotting a 3D plane, a segment and a few points, there are visualization issues:
The 'filling' of the plane cover the line and the points

```
import mpl_toolkits.mplot3d as a3
import matplotlib.pylab as plt
import numpy as np    

fig = plt.figure()
ax = a3.Axes3D(fig)

# create an orizontal plane
corners = [[0,0,0],[0,5,0],[5,5,0],[5,0,0]]
tri = a3.art3d.Poly3DCollection([corners], alpha=1)
tri.set_color('w')
tri.set_edgecolor('k')
ax.add_collection3d(tri)

# plot a vector
ax.plot([2,2],[2,2],[0,4], c = 'r')

# plot some points
ax.scatter([1,3],[1,3],[1,3], c = 'r')

ax.set_xlim([0, 5.0])
ax.set_ylim([0, 5.0])
ax.set_zlim([0, 2.5]);

plt.show()
```
output figure
![image](https://user-images.githubusercontent.com/15570009/47452193-ed092d00-d7c9-11e8-9ad4-87bf80dbfb7f.png)

expected output:
the red segment should at [2, 2, 0] in the middle of the plane. It looks as it is 'under' it

[stackoverflow thread](https://stackoverflow.com/questions/52923540/matplotlib-3d-workaround-for-plot-order)

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 3.0.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5, GTK and WX
  * Python version: 3.6.6

Installed with pip

**Comment by tacaswell** [comment]
Pushed out as I don't think this is going to be fixed in the next 6-12 hours.

**Comment by tacaswell** [comment]
Sorry @WeatherGod This looks like my mistake to merge :sheep:

**Comment by anntzer** [comment]
Looking at it again I am tempted to close this as "not worse than the known issues with mplot3d".

In 2.2, things would "work" if you had only two PolyCollections, but not three:
```
import mpl_toolkits.mplot3d as a3
import matplotlib.pylab as plt
import numpy as np

fig = plt.figure()
ax = a3.Axes3D(fig)

# create an orizontal plane
corners = [[0,0,0],[0,5,0],[5,5,0],[5,0,0]]
tri = a3.art3d.Poly3DCollection([corners], alpha=1)
tri.set_color('w')
tri.set_edgecolor('k')
ax.add_collection3d(tri)
corners = [[0,0,1],[0,5,1],[5,5,1],[5,0,1]]
tri = a3.art3d.Poly3DCollection([corners], alpha=1)
tri.set_color('w')
tri.set_edgecolor('k')
ax.add_collection3d(tri)
corners = [[0,0,2],[0,5,2],[5,5,2],[5,0,2]]
tri = a3.art3d.Poly3DCollection([corners], alpha=1)
tri.set_color('w')
tri.set_edgecolor('k')
ax.add_collection3d(tri)

# plot a vector
ax.plot([0,0],[5,5],[-10,10], c = 'r')

# plot some points
ax.scatter([1,3],[1,3],[1,3], c = 'r')

ax.set_xlim([0, 5.0])
ax.set_ylim([0, 5.0])
ax.set_zlim([0, 2.5])

plt.show()
```
![test](https://user-images.githubusercontent.com/1322974/47677355-26251100-dbbf-11e8-92e9-12137c33dcd0.png)
because the PolyCollections would get assigned increasing zorders -- 0, 1, 2 and thus at some point crosses the (default) zorder of Line2D's (which is 2).  The change in #9094 is that the numbering of PolyCollection zorders now start higher (2.5) and is now above the default Line2D zorder from the beginning.

The solution in either case is to set the zorder of the line to a high enough value, e.g. `ax.plot(..., zorder=10)` works in all cases.

**Comment by jklymak** [comment]
Based on the above solution, I'm closing.  Agree this is suboptimal, and indeed may have changed in 3.0.0, but I don't think we should bother fixing it given the limitations on draw order in mplot3d.
