### ISSUE TITLE
Memory leak with plt.plot in Jupyter Notebooks?

### ISSUE THREAD

**Issue by wjgan7** [matplotlib/matplotlib#12644]
### Bug report

**Bug summary**

If I call plt.plot on an array with 50M entries, then run plt.cla(), plt.clf(), plt.close('all'), I'm still left with 3 GB more memory than before I call plt.plot. This is done in a Jupyter notebook.

**Code for reproduction**
```python
# [1]
import matplotlib.pyplot as plt
import numpy as np
import gc

# [2]
plt.plot(np.random.normal(size=50000000))

# [3]
plt.cla()
plt.clf()
plt.close('all')
gc.collect()
```

**Actual outcome**

htop shows my memory usage is 3 GB higher.

**Expected outcome**

The memory usage is the same as before.

**Matplotlib version**
  * Operating system: Ubuntu 18.04.1 LTS
  * Matplotlib version: 2.2.2
  * Matplotlib backend: Qt5Agg ?
  * Python version: 3.6.5
  * Jupyter version: 1.0.0

**Comment by WeatherGod** [comment]
jupyter (or more specifically, ipython in this case), likes to store all of
the results from lines that aren't saved anywhere. So, the call
`plt.plot(...)` returns a list of line collection objects, one of which has
5 million points in it. That gets saved by ipython. So then, when it comes
time to clear stuff out, the garbage collector can't clear it all out
because ipython is holding a reference to it.

**Comment by jklymak** [comment]
:+1:  I just tested all this, and gc seems to work fine for python, but not for ipython...

So I think this is an ipython issue.  I'm closing, but feel free to ping if you can reprduce w/o ipython, or you think there is something matplotlib should be doing about this.
