### ISSUE TITLE
Process finished with exit code -1 due to matplotlib configuration

### ISSUE THREAD

**Issue by idohi** [matplotlib/matplotlib#12696]
### Bug report

**Bug summary**
Running code that include `import pandas` on debug mode (I am using pycharm 2018.2 community eddition). The result is **Process finished with exit code -1** .
After correspondence with "JetBrain" development team I have got the following work around, that fix the problem:
Add the following commands to matplotlib configuration file (the file can be found by the command `matplotlib.matplotlib_fname()` ) :

```
import matplotlib
matplotlib.use("TkAgg")
```
Is there properly solution like new matplotlib version with a fix for this issue?

**Code for reproduction**
```
import pandas as pd

def main():
    x = 1
    return
if __name__ == '__main__':
    main()
```
**Actual outcome**

```
Process finished with exit code -1
```

**Code with work a round**

```
import pandas as pd
import matplotlib
matplotlib.use("TkAgg")

def main():
    x = 1
    return
if __name__ == '__main__':
    main()
```

**Expected outcome**

```
Process finished with exit code 0
```

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.2.3
  * Matplotlib backend (`print(matplotlib.get_backend())`):   Qt5Agg
  * Python version: 2.7.15
  * Jupyter version (if applicable):
  * Other libraries: matplotlib installed thru anaconda windows installer

**Comment by jklymak** [comment]
Don’t see how we can help with this.  Whatever backend pycharm uses must be causing the problem.  If you can isolate an issue to matpltolob feel free to reopen.

**Comment by ImportanceOfBeingErnest** [comment]
I noted that you report the backend to be Qt5Agg and your python version as 2.7. While it seems possible to get pyqt5 running on py2, this is pretty non-standard and would require a lot of tweaks and a manual build process (as far as I know). 
I think pandas tries to import matplotlib at some point (they wanted to get rid of that, but that just broke at lot), and when matplotlib cannot load the qt5agg backend, because pyqt5 is not installed or worse, half-installed, it might fail with a non-zero exit code. There might be some traceback hidden, which PyCharm does not display?

**Comment by idohi** [comment]
@tacaswell, I get exit code -1without any errors.
In the description exist 2 short codes: one reproduce the issue and one with work a round fix. (the work a round fix was given to me by Pycharm development team).
