### ISSUE TITLE
`import matplotlib.pyplot as plt` will abort silently

### ISSUE THREAD

**Issue by jdhao** [matplotlib/matplotlib#12758]
### Bug report

**Bug summary**
I am using Matplotlib on Windows system. I have found that python will exit silently if I try to import pyplot module. 
**Code for reproduction**

1. Open Windows command line and execute python.
2. Try `import matplotlib.pyplot as plt`
3. Python exit silently without any error or warning.
![video_2018-11-06_182241](https://user-images.githubusercontent.com/16662357/48058430-5db04080-e1f1-11e8-92ee-9bd8a193f2b2.gif)

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 2.2.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.5
  * Jupyter version (if applicable): 
```
λ conda list|grep jupyter
jupyter                   1.0.0                    py36_4
jupyter_client            5.2.3                    py36_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0            py36h56e9d50_0
jupyterlab                0.32.1                   py36_0
jupyterlab_launcher       0.10.5                   py36_0
```

Both Python and Matplotlib are installed through conda.

**Comment by jklymak** [comment]
Are you sure the python you are using is the conda python?  Usually crash on import errors like this are due to setup issues.

**Comment by jdhao** [comment]
Yes, I am sure that I am using the Python shipped with Anaconda. It is the only python executable on my system. You can see Anaconda in the above image.

**Comment by tacaswell** [comment]
if you do `matplotlib.use('agg')` before importing `pyplot` does in work?

**Comment by jdhao** [comment]
After using `matplotlib.use('agg')`, I can now import pyplot. But I can not show image with `plt.show()`. Is there a better solution? Why can not I use the `Qt5Agg` backend? (I have never met this issue before.)

**Comment by jdhao** [comment]
The output of `conda list|grep qt` is:
```
pyqt                      5.6.0                    py36_2
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
qtawesome                 0.4.4            py36h5aa48f6_0
qtconsole                 4.3.1            py36h99a29a9_0
qtpy                      1.4.1                    py36_0
```

Using `matplotlib.use('tkagg')` works fine and I can show the image.

**Comment by QuLogic** [comment]
> ```
> pyqt 5.6.0 py36_2
> qt 5.6.2 vc14_1 [vc14] conda-forge
> ```

I would guess that you do not want to be mixing qt from conda-forge and pyqt from defaults. Try to install them both from the same channel, or re-create the entire environment with conda-forge enabled from the beginning.

**Comment by jdhao** [comment]
The default qt from Anaconda is replaced by qt from conda-forge when I [installed opencv from conda-forge channel](https://anaconda.org/conda-forge/opencv). 

I removed both qt and pyqt and reinstalled them plus matplotlib (removing qt will also remove matplotlib):

```
conda install qt
conda install -c anaconda pyqt
conda install matplotlib
```

Now the problem is gone.

**Comment by jdhao** [comment]
Is this issue a problem of pyqt in the conda-forge channel?

**Comment by QuLogic** [comment]
No I think it's a problem of mixing the two channels.

**Comment by ckarras** [comment]
I'm having this issue too and the solution tested by @jdhao didn't work. I don't think the issue should be closed, at the very least there should be more information provided to help investigate the issue instead of having to resolve it by trial and error.

**Comment by jklymak** [comment]
Please follow the steps in https://matplotlib.org/3.1.1/faq/troubleshooting_faq.html

**Comment by ckarras** [comment]
Hi @jklymak, 

Unfortunately this did not really help. I enabled logging using `logging.basicConfig(level="DEBUG")` as suggested in these steps (`plt.set_loglevel("debug")` was not possible because the process crashes without error as soon as I try to `import matplotlib.pyplot as plt`), and I don't get any error in the output.

Here is the output from a Python environment that has the issue:
```
DEBUG:matplotlib:$HOME=...
DEBUG:matplotlib:CONFIGDIR=...
DEBUG:matplotlib:matplotlib data path: ...
DEBUG:matplotlib:loaded rc file ...
DEBUG:matplotlib:matplotlib version 3.0.0
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
DEBUG:matplotlib:loaded modules: [...]
DEBUG:matplotlib:CACHEDIR=...
DEBUG:matplotlib.font_manager:Using fontManager instance from ...
DEBUG:matplotlib.pyplot:Loaded backend qt5agg version unknown.
```

And here is the output from a Python environment that doesn't have the issue:
```
DEBUG:matplotlib:$HOME=...
DEBUG:matplotlib:CONFIGDIR=...
DEBUG:matplotlib:matplotlib data path: ...
DEBUG:matplotlib:loaded rc file ...
DEBUG:matplotlib:matplotlib version 3.0.2
DEBUG:matplotlib:interactive is False
DEBUG:matplotlib:platform is win32
DEBUG:matplotlib:loaded modules: [...]
DEBUG:matplotlib:CACHEDIR=...
DEBUG:matplotlib.font_manager:Using fontManager instance from ...
DEBUG:matplotlib.pyplot:Loaded backend qt5agg version unknown.
DEBUG:matplotlib.pyplot:Loaded backend qt5agg version unknown.
DEBUG:matplotlib.pyplot:Loaded backend Qt5Agg version unknown.
```

Both cases show messages about "backend qt5agg version unknown", so this doesn't explain why it still works in one environment or the other.

A fix to this issue would require logging information before the crash, so that I can understand what's the issue. I don't want to randomly install/uninstall packages until both environments have the same versions of everything, I want to understand what is the cause of the issue so that I can directly apply the necessary changes. If I try to uninstall some stuff, then I'll also need to uninstall anything that depends on it, and then the environment will no longer work for its purpose until I reinstall everything.

**Comment by jklymak** [comment]
Just to be clear, you need to do 
```
import logging
logging.basicConfig(level="DEBUG")
import matplotlib.pyplot as plt
```

If matplotlib 3.0.2 works for you, would it make sense to upgrade to that first?  It is a bug-fix release, so perhaps you are tripping over a bug in 3.0.0

**Comment by tacaswell** [comment]
Can you please check the pyqt versions in both environments? 

If you do

```python
import matplotlib
matplotlib.use('agg')
import matplotlib.pyplot as plt
```

does it work in both environments?  My guess is that it is something in pyqt that is failing to import and taking down the interpreter.

**Comment by ckarras** [comment]
@jklymak I updated to version 3.0.2 and the update process broke numpy and pandas, which I then had to reinstall. It now works without issue, but for some reason it's using TkAgg instead of QtAgg (log says "Loaded backend TkAgg version unknown."). I suspect this broke other installed components too, which I'll find out when I try to use them. This is the situation I was hoping to avoid. Anyway thanks for trying to help, but it seems that PyQt is actually to blame (see comment below) so I'll look in this library's bugs and documentation next.

@tacaswell I tried checking the PyQt version using this: 
```
import logging
logging.basicConfig(level="DEBUG")
from PyQt5.QtCore import QT_VERSION_STR
QT_VERSION_STR
```
and this fails silently (python process exits), without logging anything, so it's possible that this is what was causing the same issue in matplotlib.

The code you suggested is also a workaround I was able to use successfully (before my changes caused matplotlib to use TkAgg instead of QtAgg)

**Comment by vertok** [comment]
when I use `matplotlib.use('agg')` I receive `DEBUG   : Loaded backend agg version unknown.` and after I use `matplotlib.use('tkagg')` I get `DEBUG   : Loaded backend tkagg version unknown.`. I'm sad:(
(as default I get  `DEBUG   : Loaded backend tkagg version unknown.` message)

**Comment by tacaswell** [comment]
@vertok Those are just debug-level logging messages.  If your code is not otherwise working please open a new issue with a reproducible example.
