### ISSUE TITLE
plt.table kwarg fontsize does not work

### ISSUE THREAD

**Issue by mtchem** [matplotlib/matplotlib#12828]
### Bug report
No way to change the fontsize of tables (matplotlib.pyplot.table )
**Bug summary**

The kwarg fontsize for matplotlib.pyplot.table does not set the fontsize, nor does looping through each cell and setting cell's fontsize.

**Code for reproduction**

```python
#import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

data = [[ 66386, 174296,  75131, 577908,  32015],
        [ 58230, 381139,  78045,  99308, 160454],
        [ 89135,  80552, 152558, 497981, 603535],
        [ 78415,  81858, 150656, 193263,  69638],
        [139361, 331509, 343164, 781380,  52269]]

columns = ('Freeze', 'Wind', 'Flood', 'Quake', 'Hail')
rows = ['%d year' % x for x in (100, 50, 20, 10, 5)]

values = np.arange(0, 2500, 500)
value_increment = 1000

# Get some pastel shades for the colors
colors = plt.cm.BuPu(np.linspace(0, 0.5, len(rows)))
n_rows = len(data)

index = np.arange(len(columns)) + 0.3
bar_width = 0.4

# Initialize the vertical-offset for the stacked bar chart.
y_offset = np.zeros(len(columns))

# Plot bars and create text labels for the table
cell_text = []
for row in range(n_rows):
    plt.bar(index, data[row], bar_width, bottom=y_offset, color=colors[row])
    y_offset = y_offset + data[row]
    cell_text.append(['%1.1f' % (x / 1000.0) for x in y_offset])


# Add a table at the bottom of the axes
the_table = plt.table(cellText=cell_text,
                      rowLabels=rows,
                      rowColours=colors,
                      colLabels=columns,
                      loc='bottom',
                      **fontsize = 30)**

# Adjust layout to make room for the table:
plt.subplots_adjust(left=0.2, bottom=.1)



plt.show()
<img width="518" alt="screen shot 2018-11-18 at 4 40 09 am" src="https://user-images.githubusercontent.com/10767779/48671898-10cf4280-eaec-11e8-94ba-19ef31681855.png">

```

**Actual outcome**

<img width="518" alt="screen shot 2018-11-18 at 4 40 09 am" src="https://user-images.githubusercontent.com/10767779/48671941-905d1180-eaec-11e8-84cc-62c5395812f7.png">

```

```

**Expected outcome**

 The font in the table should be much bigger

**Matplotlib version**

  * Operating system: OSX 10.13.6
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6x
  * Jupyter version (if applicable):
  * Other libraries: 

 conda

**Comment by ImportanceOfBeingErnest** [comment]
You can set the fontsize of the table via

    the_table.set_fontsize(30)

The [documentation](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.table.html) indeed lists `fontsize` as a possible `kwarg`. I don't see why though, because `Table` subclasses `Artist`, but `Artist` has no `fontsize` property.

Letting `Table` use the `fontsize` argument seems perfectly possible as well and not too hard to implement.

**Comment by timhoffm** [comment]
There's more to consider:

`set_fontsize` silently limits the fontsize to a value so that the text still fits into the cell (see `auto_set_font_size`). You could do:

~~~
the_table.auto_set_font_size(False)
the_table.set_fontsize(20)
~~~

however the cell height does do not scale properly:

![grafik](https://user-images.githubusercontent.com/2836374/48674345-5b33dc00-eb4b-11e8-99dc-6ecc9efe1bc7.png)

Also there's some hard-coded sizing involved (`Table.FONTSIZE`).

**Comment by mtchem** [comment]
Thanks timhoffm, turning off the font size and set_fontsize worked. I will still have to change cell size, but there are examples for that. It still would be nice if fontsize worked as a parameter.

**Comment by timhoffm** [comment]
Fontsize documentation is improved as part of #12880.
