### ISSUE TITLE
boxplot not showing symbols with seaborn style sheet

### ISSUE THREAD

**Issue by RinaldoB** [matplotlib/matplotlib#13022]
### Bug report

**Bug summary**
When the `seaborn` style sheet is used, outlier points in plots generated with `boxplot` are not displayed. 

**Code for reproduction**

```python
%matplotlib notebook
import matplotlib.pyplot as plt
plt.style.use('seaborn')
plt.figure()
plt.boxplot([0,0,0,1])
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/5071882/50228860-409e8e00-03a9-11e9-93d5-1e44a82826a9.png)

**Expected outcome**
![image](https://user-images.githubusercontent.com/5071882/50228879-4eecaa00-03a9-11e9-81c5-3e8d19ccfef7.png)

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 3.0.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
This is actually due to an unfortunate default value for `lines.markeredgewidth = 0` rcParam.

For now, a possible workaround is using the `flierprops` parameter:

~~~
plt.boxplot([0,0,0,1], flierprops={'markeredgewidth': 1})
~~~

**Comment by mwaskom** [comment]
> This is actually due to an unfortunate default value for lines.markeredgewidth = 0 in seaborn.mplstyle.

It's also due to the fact that matplotlib's style sheets are out of sync with actual parameters seaborn sets:

```python
import seaborn as sns
import matplotlib.pyplot as plt

sns.set()
plt.boxplot([0, 1, 2] * 50 + [10])
print(sns.__version__)
```

```
0.9.0
```

![image](https://user-images.githubusercontent.com/315810/54072399-48532d80-4248-11e9-9286-6d1671b4cde4.png)

(By the way, the original example surprises me for other reasons. In Tukey's definition, box plots should only represents values that exist in the data set. How is 0.2 getting in there?)
