### ISSUE TITLE
eps and useTex: tick labels drawn over legend box

### ISSUE THREAD

**Issue by leejjoon** [matplotlib/matplotlib#131]
This is an issue originally reported in the mailing list by Brannon (giltirn@gmail.com).

http://old.nabble.com/eps-and-useTex%3A-tick-labels-drawn-over-legend-box-td31744864.html

Hi,

I am having trouble with matplotlib 1.0.1 drawing the axis tick labels over
the legend box in the eps output when useTex is set to true. The plot shown
after calling plt.show() looks fine, as does the output in pdf, png, svg
etc. Only the postscript appears to be affected.

The following simple example produces the png and eps files given at the
bottom of this post:

```
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import rc

rc('text', usetex=True)

g1, = plt.plot([1,2,3,4],[500,600,700,800])
g2, = plt.plot([1,2,3,4],[700,300,700,200])
g3, = plt.plot([1,2,3,4],[800,600,900,800])

plt.figlegend([g1,g2,g3],['test1','test2','test3'],'upper left')

plt.savefig('image.png')
plt.savefig('image.eps')

plt.show()
```

http://old.nabble.com/file/p31744864/image.eps image.eps
http://old.nabble.com/file/p31744864/image.png image.png

I would very much appreciate some help resolving this issue.

Thanks

**Comment by efiring** [comment]
@jkseppan, I suspect this bug is very hard to fix, and is not going to get fixed, in which case it would be nice to close it with a "won't fix".  I presume a reasonable workaround is to use the pdf backend instead and then use convert or gs to generate the ps or eps file.  Maybe a note to that effect could go in the docs.

**Comment by jkseppan** [comment]
Perhaps I can give some background on why the backend works this way. When you create EPS files in something like Matlab, you cannot usually typeset math inside the files. If you include a Matlab EPS file in your TeX document, the text and equations in it are going to look different from the rest of the document. That's why [psfrag](https://en.wikipedia.org/wiki/PSfrag) was created: you'd enter just some placeholder text in Matlab, and use the psfrag macros to generate some magic PostScript code to change the placeholders to equations rendered by TeX, and when this code is included in the output of dvips it would modify the included EPS file accordingly. Now the matplotlib PostScript backend adds one more layer by creating a LaTeX file that uses psfrag to modify the intermediate matplotlib output to render equations in TeX, and calling latex and dvips on it. I don't think there is any deep technical reason that z-order could not be made to work, but even figuring out which part of the Python/TeX/dvips/PostScript polyglot stack is doing it wrong is going to be a challenge. Certainly in the original use case of psfrag you'd want the equations to be typeset on top of any Matlab plots.

When I implemented usetex for the pdf backend, I couldn't do the same, since psfrag is implemented with PostScript tricks and depends on dvips. Thus we have dviread, which takes a different approach and has different bugs, so going via the pdf backend and using some pdf&rarr;ps converter can give different results.

**Comment by dstansby** [comment]
Just tried the code above and it seems fine to me now - I guess it was fixed at some point between 2016 and now, so going to close!
