### ISSUE TITLE
Examples that use private APIs

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#13199]
The following examples rely on at least one private API.  They should be changed to not use the private API, or, if that's not possible, we should discuss how to make that API public.

Fixed in #13202:
- <s>https://github.com/matplotlib/matplotlib/blob/master/examples/axes_grid1/demo_axes_grid2.py</s>
- <s>https://github.com/matplotlib/matplotlib/blob/master/examples/axisartist/demo_curvelinear_grid2.py</s>
- <s>https://github.com/matplotlib/matplotlib/blob/master/examples/axisartist/demo_floating_axes.py</s>
- <s>https://github.com/matplotlib/matplotlib/blob/master/examples/axisartist/demo_parasite_axes.py</s>

Still need fixing:
- <s>https://github.com/matplotlib/matplotlib/blob/master/examples/userdemo/custom_boxstyle02.py</s>
  is now the second example of https://matplotlib.org/devdocs/gallery/userdemo/custom_boxstyle01.html

**Comment by jklymak** [comment]
For axes_grid I think we should consider how to make that a core functionality.

**Comment by QuLogic** [comment]
The last example seems to exist solely to derive from that private API, so I don't know what to do about it.

**Comment by timhoffm** [comment]
As written elsewhere, I have doubts that private base classes are a reasonable approach. Their code leaks into the child classes, which is intended, but OTOH confusing because you're not seeing the base class. This also messes up sphinx because the inherited methods are not documented and cannot be linked.

Generally, I cannot remember to have seen private base classes anywhere else. I feel it's better to make the base class public, but some of it's members private or abstract.

**Comment by QuLogic** [comment]
Note, as part of #16615, the last example was merged into https://github.com/matplotlib/matplotlib/blob/master/examples/userdemo/custom_boxstyle01.py though the private API is still used.

**Comment by anntzer** [comment]
I have an idea of how to get rid of that private base class (essentially, move the mutation aspect handling out of `__call__` and into the (only) call site, but as usual this will require ginormous amounts of deprecation machinery.  I'll work on it at some point...
