### ISSUE TITLE
Suggestion: add pyplot.barplot order option

### ISSUE THREAD

**Issue by mdastro** [matplotlib/matplotlib#13261]
### Suggestion: new feature

Dear developers, 

I have stumbled with the following issue: I would like to create a barplot in which I could set the order of x axis label. The seaborn package has this option (`x_order`) in several of their plots (e.g. violinplot, boxplot, etc.) and I have found this very useful.

I would like to be able to set the order of my classes/groups either by index or by key.
I have seen in stackoverflow several questions such as mine, but the solutions are somewhat handful, which did not need to be.

Do you think this is feasible? It would be super helpful!

Thank you!!

Malu

PS.: just for the sake of being really clear, the accepted parameters of barplot are:
```
plt.bar(x, height, width=0.8, bottom=None, *, align='center', data=None, **kwargs)
```

The order option is not available. The `plt.xticks` command allows me to rename the bars, but not to change their places.

**Comment by dstansby** [comment]
I think what you want is possible to do by changing the order of the items in `x` before calling `plt.bar()`. Does that help?

**Comment by mdastro** [comment]
Hi @dstansby , thank you for your answer.
Well, it helps, of course!
I would just thinking on how to avoid this pre-processing of the data, specially when you want to do things faster, just to have a look at them.

This is my dataframe (which I simply generated by the .count() method from pandas -- the order appears to be alphabetical and case-sensitive):
![screenshot from 2019-01-22 14-03-16](https://user-images.githubusercontent.com/10452764/51552025-8211d580-1e4e-11e9-9d8d-a38f26e1183b.png)

This is what I get just doing the barplot with the data above. The order in the x axis is not what I would like, but it's done with respect of the order generated by pandas
![screenshot from 2019-01-22 14-02-55](https://user-images.githubusercontent.com/10452764/51552027-82aa6c00-1e4e-11e9-99b2-190f5906ae47.png)

This is what I want, but I need to do it manually. :/
![screenshot from 2019-01-22 14-02-38](https://user-images.githubusercontent.com/10452764/51552029-82aa6c00-1e4e-11e9-97f7-03a0b541ab85.png)

**Comment by ImportanceOfBeingErnest** [comment]
Consider that a matplotlib axis is an ordered "number line". Hence, an ordinate of 1 is necessarily between 0 and 2. What seaborn or pandas bar plots do is that they plot the first bar at position 0, the second at 1 etc. and then manipulate the labels shown at those positions. 

This essentially looks like

```
x = ["Zebra", "Cow", "Pig"]
y = [3,2,1]

plt.bar(range(len(x)), y)
plt.xticks(range(len(x)), x)
```

In matplotlib 2.1, the concept of "units" has been introduced, which allows categorical plots. The same as the above would then look like

```
x = ["Zebra", "Cow", "Pig"]
y = [3,2,1]

plt.bar(x, y)
```

This works because strings are considered to be categories. Of course the concept can be used for numbers as well, in case they are converted to strings first

```
x = [2,3,1]
y = [3,2,1]
plt.bar(numpy.array(x).astype(str), y)
```

Hence I don't see the necessity to introduce any "order" parameter for bars specifically. 

However, there is a more general, unsolved problem with categories, namely that it is currently not possible to predetermine the category order of an axis. A usecase may be

```
desired_order = ["Zebra", "Cow", "Pig", "Frog"]

x1 = ["Zebra", "Cow", "Frog"]
x2 = ["Zebra", "Pig", "Frog"]
y1 = [3,2,1]; y2 = [1,2,3]

plt.scatter(x1, y1)
plt.scatter(x2, y2)
```


*Actual outcome*

![image](https://user-images.githubusercontent.com/23121882/51552633-53f1bd00-1e71-11e9-9b50-beefc573c36e.png)

The order is Zebra, Cow, Frog, Pig. I.e. Pig is the last item, because it does not appear in the first plot.

*Desired outcome*

The desired order can be achieved by first plotting something unrelated to the axes, but in the desired order, and later remove it.

```
desired_order = ["Zebra", "Cow", "Pig", "Frog"]

x1 = ["Zebra", "Cow", "Frog"]
x2 = ["Zebra", "Pig", "Frog"]
y1 = [3,2,1]; y2 = [1,2,3]

cy = np.concatenate((y1,y2))
sentinel = plt.scatter(desired_order, np.linspace(cy.min(), cy.max(), len(desired_order)))
plt.scatter(x1, y1)
plt.scatter(x2, y2)

sentinel.remove()
```

![image](https://user-images.githubusercontent.com/23121882/51553089-51439780-1e72-11e9-86b6-618ea556f52b.png)
 This is pretty cumbersome and by far not obvious for users.

**Comment by mdastro** [comment]
Thank you @ImportanceOfBeingErnest for your answer.

The fact that matplotlib accepts categorical data is, for sure, very very useful.

I understand your point, however, as I described in my example above, the order came as a result of a previous output, so in order to set my _desired order_, I would need recreate my dataframe manually. :( 
Anyway, thank you for your attention!

**Comment by jklymak** [comment]
`x = x[new_order]` will re-order a numpy array x however you want it to be ordered.  i.e. 

`x =np.array( [2, 4, 6, 8]); new_order = [1, 0, 3, 2]; x[new_order]`  will yield `[4, 2, 8, 6]`.

**Comment by jklymak** [comment]
Also, since you have data frames: https://stackoverflow.com/questions/13148429/how-to-change-the-order-of-dataframe-columns

**Comment by mdastro** [comment]
Hi @jklymak, thank you.

Your suggestion is for sure the simplest one. It works fine, thanks.
By the way, about the the stackoverflow suggestion,  I have read this issue, but I'm not actually dealing with column order, but row order (I know I can transpose it, etc., etc.). 

Thanks for your suggestion, it works well. I had tried before with the order of the keys (i.e. row names/ index in the print I sent previously), but it did not work.

Cheers,
Malu

**Comment by mdastro** [comment]
PS.: just posting a screenshot of the code with your suggestion. Perhaps it may be useful to someone else.
![screenshot from 2019-01-22 15-03-34](https://user-images.githubusercontent.com/10452764/51555712-00727580-1e57-11e9-8589-f26343ffa484.png)

**Comment by QuLogic** [comment]
`data_count.iloc[order, :]` can be used to re-order a `DataFrame` in the order you specify (`data_count.loc[order, :]` if `order` is a list of row names instead of indices), in a similar way to NumPy.

(I think `.loc`/`.iloc` are better than plain `[]` indexing.)
