### ISSUE TITLE
Matplotlib keymap stop working after pressing tab

### ISSUE THREAD

**Issue by dallas74** [matplotlib/matplotlib#13484]
### Bug report

Using the example in the link below, keymap (eg h for home etc) works fine but if I press the tab none of the keymaps works. Clicking in the figure/plot dont help. I can use either alt+tab to get it working again or pressing tab for a few times.

https://matplotlib.org/gallery/user_interfaces/embedding_in_tk_sgskip.html#sphx-glr-gallery-user-interfaces-embedding-in-tk-sgskip-py

I would expect that clicking on the figure would make the keymap work again.

Im using Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32 and matplotlib v 3.0.2

Kind regards, Daniel

**Comment by tacaswell** [comment]
The mpl side callbacks (see https://matplotlib.org/users/event_handling.html) rely on the native GUI layer (and then the OS windowing layer) to deliver the user events and then dispatch those internally.

The issue here is that 'tab' is also changing the focus of what widget in the tk application is getting the key call backs.  Compare

![image](https://user-images.githubusercontent.com/199813/53303118-a5a4b300-3834-11e9-97b6-b7f3dce20f1d.png)


vs

![image](https://user-images.githubusercontent.com/199813/53303121-ad645780-3834-11e9-81aa-9a33dec84977.png)


Notice the box around the 'home' icon?  That means all of the key input is going to the home button (which is ignoring it).  As you hit tab you can see that box move around and when it gets back to the plot widget, the callback works again.  Focusing / defocusing the window does not help because tk keeps "which of my children is focused" separate from the WM's idea of which window is focused.

I don' think this is a bug, would merge a PR to that example showing how to set up Tk to change it's focus to the plot if you click on that widget.

**Comment by dallas74** [comment]
Hi, thanks a lot. Im new here so just to be sure, will you do the "PR" or
should I do anything?

I tried to use

self.d2 = fig.canvas.mpl_connect('axes_enter_event', self.on_click)

and

self.d2 = self.fig.canvas.mpl_connect('figure_enter_event', self.on_click)

but in def on_click I could get the widget instance passed as on
"normal" tk where you can use event.widget. Is there any documentation
showing how to get the widget instance using mpl_connect?

Best regards, Daniel


Den sön 24 feb. 2019 kl 19:07 skrev Thomas A Caswell <
notifications@github.com>:

**Comment by tacaswell** [comment]
Can you open the pull request (aka PR, sorry for the jargon!).

`mpl_connect` is working at the Matplotlib callback level (which passes around classes from Matplotlib and is mostly independent from the underlying GUI framework so the same code should work on any backend.

See https://matplotlib.org/users/event_handling.html?highlight=event#event-attributes for the attributes on the `Event` so you _should_ be able to dig out the underlying Tk event via `ev.guiEvent`.  However, I suspect that there is a tk-level way to solve this problem.

**Comment by dallas74** [comment]
Hi, I found a solution, should I post a code snippet of the solution i
found?

Best regards, Daniel

Den mån 25 feb. 2019 kl 03:26 skrev Thomas A Caswell <
notifications@github.com>:

**Comment by tacaswell** [comment]
Can you open a pull-request (see https://matplotlib.org/devel/contributing.html#contributing-code) updating the example?

Depending on what the change is we may want to put it in the backend code too.

**Comment by timhoffm** [comment]
The reason for this behavior is that shortcuts are bound to the canvas and pressing `<Tab>` moves the focus away from the canvas.

An alternative solution might be to bind the shortcuts to the window and not to the canvas. - Not sure if this is possible with Tk (with Qt it is) and if that's manageable in the current framework (essentially all actions are bound to the canvas and matplotlib does not know about the window).

Demilestoning and removing "Good first issue" because this is not trivial and I'm unclear if this can be solved at all.
