### ISSUE TITLE
Apply the same bbox_inches='tight' transformation on multiple plots

### ISSUE THREAD

**Issue by hamzamerzic** [matplotlib/matplotlib#13483]
Hi, I'm using matplotlib to record videos and I'm would like to apply the `bbox_inches='tight'` transformation on each frame of the video (not tight_layout - the output seems to be different). Ideally I would like to be able to obtain the transform that achieves that without using `savefig`, but after an extensive search I wasn't able to find that feature.

So currently I'm using `savefig` to store the image in a String buffer and read from there, the problem is that `savefig` performs the saving two times, once to determine the layout and second time to restore it [[ref](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py#L1996)] which in my case means that it effectively almost triples the recording time of the videos. 

Thus I'm wondering if there's a convenient way to store the same transformation as done by `bbox_inches='tight'` and apply it to all of the frames in the video?

Thank you!

**Comment by jklymak** [comment]
It doesn’t do any transformations per se.  It resizes the figure to include all the artists in the figure to not be clipped.

**Comment by hamzamerzic** [comment]
Thanks for the reply. So clearly it does something to the image (and definitely something different to `tight_layout`), and whatever it does I'm hoping to be able to cache it and then apply to all the subsequent frames.

**Comment by ImportanceOfBeingErnest** [comment]
`bbox_inches='tight'` finds the bounding box that includes all elements of the figure. Then this bounding box is used as the extent of the saved image. This is done *after* all transformations have been applied. There hence cannot be any transformation that does the same thing as `bbox_inches='tight'`. 

Concerning the problem at hand,  `Animation.save()` has an argument `savefig_kwargs`. You can supply the `bbox_inches` argument to it. To avoid letting it save the figure twice, you can instead of `bbox_inches="tight"`, supply your custom bounding box directly. This would leave you with the task of finding the same (or similar) bounding box as the one that is calculated by the `tight` option. With 2 to 3 iteration of trial and error that would already be quite usable. If the aim is to find the exact same bounding box, you can essentially just apply the code from https://github.com/matplotlib/matplotlib/blob/b9045cdfee9937ee2e47bc3170e3c496aaf46825/lib/matplotlib/backend_bases.py#L1995-L2015

once and store the resulting bbox for future use in the  animation's `savefig_kwargs`.

**Comment by jklymak** [comment]
Closing as I think @ImportanceOfBeingErnest has fully covered this.  If not, feel free to re-open and/or comment further.
