### ISSUE TITLE
matplotlib scatter plot with xyz axis lines through origin (0,0,0) and axis project lines to each point

### ISSUE THREAD

**Issue by wm2015email** [matplotlib/matplotlib#13575]
**Suggestion:**

Its my opinion, that matplotlib should be improved to make it less code to make simple algebra 1 level scatter plot of points for say, a high school algebra classs?   shouldn't take more than 3 lines of code to draw a scatter plot like listed below:

See stackoverflow.

https://stackoverflow.com/questions/54970401/matplotlib-scatter-plot-with-xyz-axis-lines-through-origin-0-0-0-and-axis-proj/54971037#54971037

Why can't we have a built-in function that's part of matplotlib call **add_standard_axis()** that does the following:

    Added X,Y,Z axis arrows through origin with arrow pointing towards positive direction and labeled X,Y,Z 
   Also would be nice to have a built-in function for adding points to scatterplot with X,Y,Z line projections, see function make_dashedLines():

See The following code:
```python
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np

def make_dashedLines(x,y,z,ax):
    for i in range(0, len(x)):
        x_val, y_val, z_val = x[i],y[i],z[i]
        ax.plot([0,x_val],[y_val,y_val],zs=[0,0], linestyle="dashed",color="black")
        ax.plot([x_val,x_val],[0,y_val],zs=[0,0], linestyle="dashed",color="black")
        ax.plot([x_val,x_val],[y_val,y_val],zs=[0,z_val], linestyle="dashed",color="black")

fig = plt.figure()

ax = fig.add_subplot(111, projection='3d')
x = [1,1,-1]
y = [1,-1,1]
z = [1,1,-1]

ax.scatter( x,y,z, c='r', marker='o')
make_dashedLines(x,y,z,ax)

# Make a 3D quiver plot
x, y, z = np.array([[-2,0,0],[0,-2,0],[0,0,-2]])
u, v, w = np.array([[4,0,0],[0,4,0],[0,0,4]])
ax.quiver(x,y,z,u,v,w,arrow_length_ratio=0.1, color="black")
ax.grid(False)
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')

ax.set_xlim(-2,2)
ax.set_ylim(-2,2)
ax.set_zlim(-2,2)

plt.show()
```

**Comment by tacaswell** [comment]
Given the broad use of Matplotlib, the notion of "the simple obvious plot" is very broad and in general contradictory among our user base.  We prefer to provide foundational APIs that you can use to build whet you need rather than complex specialized APIs that you have to workout how to deconstruct to get what you want.

An extension of top of Matplotlib that is targeted at high school level algebra, I think that would make an extremely interesting third party package.  I suspect that the choices you would want to make for that API (e.g. assume the axes are always labeled X, Y, Z) and the amount of details you want to hide from students would be very different that the choices we want to make in the core library. 

We would likely entertain a PR to add a method to `Axes3D` to add a coordinate system representation (the case demoed here of big arrows at the origin is one way, the little red/green/blue triplet in the corner is another common way), but I do not think we need to keep this issue open to track that.
