### ISSUE TITLE
zoomed_inset_axes flipping the image displayed inside

### ISSUE THREAD

**Issue by nitinnat** [matplotlib/matplotlib#13649]
### Bug report

**Bug summary**
When I use zoomed_inset_axes to plot a zoomed image, the image inside the inset axes is flipped. I tried the following:
1. using origin="lower" inside the imshow method
2. flipping "img" before displaying it in the inset axes by using np.flipud(img)

**Code for reproduction**

```python
img = imageio.imread("lena.jpg")
x1, y1, x2, y2 = [100, 100, 150, 150]
fig, ax = plt.subplots() # create a new figure with a default 111 subplot
ax.imshow(img)
from mpl_toolkits.axes_grid1.inset_locator import zoomed_inset_axes
axins = zoomed_inset_axes(ax, 2.5, loc=2) # zoom-factor: 2.5, location: upper-left
axins.imshow(img)
axins.set_xlim(x1, x2) # apply the x-limits
axins.set_ylim(y1, y2) # apply the y-limits
plt.yticks(visible=False)
plt.xticks(visible=False)
from mpl_toolkits.axes_grid1.inset_locator import mark_inset
mark_inset(ax, axins, loc1=2, loc2=4, fc="none", ec="red")
```

**Actual outcome**

![Capture](https://user-images.githubusercontent.com/32604203/54108036-448eea80-43b1-11e9-9429-9fad8555d4b6.PNG)

**Expected outcome**

The image inside the inset_axes must be displayed without being flipped.
**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version:  '2.2.3'
  * Matplotlib backend module://ipykernel.pylab.backend_inline
  * Python version: 3.6.6
  * Jupyter version (if applicable): 1.0.0

Installed using pip inside the Anaconda framework

**Comment by ImportanceOfBeingErnest** [comment]
This is due to the (default) `origin="upper"` setting of imshow. I think you would want to flip the y coordinates, `axins.set_ylim(y2, y1)`. This should give the correct image orientation. The look and feel of images is always a big source of confusion, but we have a [imshow extent](https://matplotlib.org/tutorials/intermediate/imshow_extent.html) tutorial, which tries to explain the interplay between the different arguments. 

You would then probably run into trouble with the connection lines. This is unfortunately not well documented; but see issues #10227 and #10738 on workarounds.

**Comment by nitinnat** [comment]
Yes, from what I saw it seems to be because of the confusion with images and their flipped coordinate systems. This works like a charm. Thank you!
The workarounds for mark_inset are useful too.
