### ISSUE TITLE
Add better error message to plt.axis()

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#13668]
I picked this up when looking at #13667 - currently giving 4 limits as separate args gives

```python
>>> plt.axis(0, 1, 0, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/pyplot.py", line 2397, in axis
    return gca().axis(*args, **kwargs)
  File "/Users/dstansby/github/matplotlib/lib/matplotlib/axes/_base.py", line 1725, in axis
    if len(v) != 4:
TypeError: object of type 'int' has no len()
```

which is a very cryptic error message. Changing to say something like `All four axis limits must be given in a list` would make more sense I think.

**Comment by anntzer** [comment]
TBH I'd consider deprecating this functionality:
- there's a trivial and more readable synonym available (`plt.xlim(xmin, xmax); ylim(ymin, ymax)` or `ax.set(xlim=(xmin, xmax), ylim=(ymin, ymax))`);
- it's difficult to explain properly in the docstring what are the valid calls (basically, one can pass all four values as a single list but only positionally, or one can pass them separately but only as keyword arguments);
- this functionality is somewhat orthogonal to what's provided by the "string" options that can be passed to axis().  Really, I'd say it's more the functionality that's cryptic, rather than the error message...

The main argument against is that this has been around for a long time, but we can leave a long deprecation period.
