### ISSUE TITLE
DOC: matplotlib.patches.Arc

### ISSUE THREAD

**Issue by keithbriggs** [matplotlib/matplotlib#13759]
1. It is said that "angle" is measured anti-clockwise, but it it is not stated whether the arc drawn is the one anti-clockwise from theta1 to theta2, or the other way.

2. Typo: ".e.g.".

3. Later the term "counterclockwise" is used.  It would be better to be consistent (always "anti-clockwise", or always "counterclockwise").

**Comment by NicolasCourtemancheAtMcGill** [comment]
Hello,
All those points are valid to me. I will adjust the doc and make a pull request.

**Comment by keithbriggs** [comment]
Thanks!  A further comment - the docs not say what happens if a negative angle is passed as theta1 or theta2, or what happens if an angle is greater the 360.

**Comment by NicolasCourtemancheAtMcGill** [comment]
To roughly answer those comments (I think with basic knowledge of degrees on the circle --or ellipse in this case, a user can understand):

1- A negative angle works, negative angles go in the clockwise direction, instead of the usual counterclockwise way of representing angles
2- An angle greater than 360 deg or smaller than -360 deg is still on the ellipse, and such a *theta* will be represented as ***theta* mod 360** if it is greater than 360, or **-( -*theta* mod 360 )** if it is lesser than -360.

I think we could use these bits:
```
Negative angles are valid, and increase negatively in the clockwise direction.

Angles greater than 360 or smaller than -360 are represented by an equivalent 
angle in the range (-360, 360).
```

**Comment by keithbriggs** [comment]
I think it should be just:

> Angles greater than or equal to 360, or smaller than 0, are represented by an equivalent 
angle in the range [0, 360), by taking the input value mod 360.

**Comment by keithbriggs** [comment]
Still open.

**Comment by NicolasCourtemancheAtMcGill** [comment]
Seeing the source code, your description is indeed more accurate as to what is done, and I have added it to the PR. I think it is good to go for review, unless anything else is found as to inaccurate doc.
