### ISSUE TITLE
tick labels overlay curve

### ISSUE THREAD

**Issue by aborzunov** [matplotlib/matplotlib#13863]
I found a guide with code examples that produces a different result if i copy-past it.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
X = np.linspace(-2 * np.pi, 2 * np.pi, 170, endpoint=True)
F1 = np.sin(X**3 / 2)
ax = plt.gca()
ax.spines['top'].set_color('none')
ax.spines['right'].set_color('none')
ax.xaxis.set_ticks_position('bottom')
ax.spines['bottom'].set_position(('data',0))
ax.yaxis.set_ticks_position('left')
ax.spines['left'].set_position(('data',0))
plt.xticks( [-6.28, -3.14, 3.14, 6.28],
        [r'$-2\pi$', r'$-\pi$', r'$+\pi$', r'$+2\pi$'])
plt.yticks([-3, -1, 0, +1, 3])
for xtick in ax.get_xticklabels():
    xtick.set_fontsize(18)
    xtick.set_bbox(dict(facecolor='white', edgecolor='None', alpha=0.7 ))
for ytick in ax.get_yticklabels():
    ytick.set_fontsize(14)
    ytick.set_bbox(dict(facecolor='white', edgecolor='None', alpha=0.7 ))
    
plt.plot(X, F1, label="$sin(x)$")
plt.legend(loc='lower left')
plt.show()
```

**Actual outcome**
![Figure_1](https://user-images.githubusercontent.com/2773341/55475155-cf16e280-561b-11e9-92d4-12c01fbe4c8f.png)

**Expected outcome**
![image](https://user-images.githubusercontent.com/2773341/55475176-db02a480-561b-11e9-8814-5d0b803158cc.png)

How to move tick labels on top of curve?

<details>
  <summary>Versions</summary>

```bash
uname -av     
Darwin AndreyBorzunovMain.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

python -c "import matplotlib; print matplotlib.__version__"
2.2.4

python -c "import matplotlib; print matplotlib.get_backend()"
MacOSX
```

</details>

**Comment by timhoffm** [comment]
Something is going wrong with the zorder during rendering. `xtick.zorder` is 3; the line zorder is 2. So in theory, the xticks should be on top of the line already.

**Observations:**
- changing `xtick.zorder` does not have any effect.
- changing the line zorder to <=1.5 brings the line behind the labels.

@aborzunov 
Temporary workaround for your example:
~~~
line, = plt.plot(X, F1, label="$sin(x)$")
line.zorder = 1
~~~

**Comment by ksunden** [comment]
Okay, so even though `xtick` has a zorder of 3, the _`xaxis`_ has a zorder of 1.5, and is drawn together at zorder of 1.5, which describes the behavior exactly.

perhaps the more proper fix to this problem is to do (rather than changing the zorder of the line)

```python
ax.xaxis.zorder=3
ax.yaxis.zorder=3
```

But as far as I can tell, this is not actually a bug.

Further investigation reveals that this is controlled by the `axes.axisbelow`, which defaults to `"line"`, which equates to a zorder of 1.5. This was part of the matplotlib 2.0 style overhaul.

Thus another solution would be to change that rc param to `False`, which equates to a zorder of 2.5, or to call

```python
ax.set_axisbelow(False)
```

If this is still considered a bug, then I guess the solution would be to recursively expand the artist list prior to sorting by zorder, but that seems quite likely to cause other problems.

I guess an alternative would be to change the default zorder of the `[xy]axis`, which would be a more minimal change, but that would be a style change.

Thus I'm going to close this, unless other maintainers have opinions to the contrary, as this seems like intended behavior that the axis gets drawn below a line by default.
