### ISSUE TITLE
Accessing default `norm` of a Collection removes its colors.

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#13887]
*This gave me some headaches to even isolate. Very weird bug!*

### Bug report

**Bug summary**

Accessing the default `norm` of a `Collection` removes its colors.

**Code for reproduction**

Create a `LineCollection` and access its `norm`.

```
import numpy as np; np.random.seed(42)
import matplotlib.pyplot as plt
from matplotlib.collections import LineCollection

lines = LineCollection(np.random.rand(4,3,2), array=np.arange(4))  
plt.gca().add_collection(lines)

print(lines.norm(2))

plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/23121882/55594708-eef3f680-5740-11e9-99e7-560e12b3a89b.png)

    >>> 0.0

Same bug is present if you replace `LineCollection` by `PolyCollection`. Possibly other collections are equally affected.

**Expected outcome**

Expected outcome is the same as when removing the `print` statement.

```
lines = LineCollection(np.random.rand(4,3,2), array=np.arange(4))  
plt.gca().add_collection(lines)

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/55594794-44300800-5741-11e9-8570-46c53d265e99.png)

Fun Fact:

If adding a colorbar first, the whole thing runs fine.

```
lines = LineCollection(np.random.rand(4,3,2), array=np.arange(4))  
plt.gca().add_collection(lines)

plt.colorbar(lines)
print(lines.norm(2))

plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/55595142-cb31b000-5742-11e9-8d1c-3efd721449de.png)

    >>> 0.6666666666666666

**Matplotlib version**

  * Operating system: Win 8.1
  * Matplotlib version:  1.5.3 (!!!) to current master
  * Matplotlib backend (`print(matplotlib.get_backend())`):  TkAgg (1.5.3), Qt5Agg (master)
  * Python version: 3.6

**Comment by anntzer** [comment]
This happens because the norm bounds (min/max) are only computed at draw time, but when you call `norm(2)` you trigger a first calculation of bounds using `2` as sole input and then the Normalize instance stays stuck with vmin=vmax=2.

One could change it to have the min/max be computed when the LineCollection is instantiated instead, but I'm sure someone out there relies on being able to change the Collection's mapped values after instantiation but before drawing and then expects the min/max to pick it up.  Having thought approximately 15s about it, I do think that normalizing at artist instantiation (specifically, in set_norm) does look better than at first draw, though (and the above-mentioned disgruntled users can always call set_norm() with a new Normalize instance after updating the mapped values -- which will work *even after the first draw*.

**Comment by ImportanceOfBeingErnest** [comment]
I understand that any fix to this might be an API change. My expectation simply comes from the fact that 

```
im = plt.imshow(np.random.normal(size=(100,100)))
print(im.norm(2))
```

or 

```
sc = plt.scatter([1,2,3],[3,4,5], c=[0,4,1])
print(sc.norm(2))
```

work as expected.
My thinking is that this should be a matter of keeping track of whether the norm has been `None` or user-specified.

**Comment by jklymak** [comment]
I didn't check if this was still an issue but if so seems worth fixing.

**Comment by ksunden** [comment]
Can confirm that the behavior still exists.
