### ISSUE TITLE
Unnecessary drawing with NbAgg

### ISSUE THREAD

**Issue by astrofrog** [matplotlib/matplotlib#13971]
I am running into performance issues when using the NbAgg backend, some of which I think is avoidable. Essentially, when clicking on an NbAgg plot, with no tool active, the backend re-draws the data, which can cause the kernel to hang if the plot is complex. Here is a demonstration - note the kernel activity in the circle in the top right. Every time I click on the plot, it is redrawn:

![Screen-Recording-2019-04-16-at-11 13 08](https://user-images.githubusercontent.com/314716/56201666-3af44480-6039-11e9-9b11-dfc0d612f1a5.gif)

Just to be clear, I totally expect plotting to be slow the first time the plot is shown, and if e.g. panning/zooming, but drawing when no tool is active doesn't seem right. This is causing issues for me because I am developing tools that respond to a click event in the plot and try and be nice by doing ``draw_idle`` to keep the UI responsive, but every mouse action also results in a full ``draw`` which slows things down a lot.

**Matplotlib version**

  * Operating system: MacOS X 10.14.2
  * Matplotlib version: latest dev (557cdfaef1836a7e39d93e41c93810876c715016)
  * Matplotlib backend (`print(matplotlib.get_backend())`): NbAgg
  * Python version: 3.7.1
  * Jupyter version (if applicable): 4.4.0

**Comment by thomasaarholt** [comment]
I just did some testing:
MWE:
```python
import numpy as np
import matplotlib.pyplot as plt

i = 1000000
y = np.random.random(i)
x = np.random.random(i)
plt.figure()
plt.scatter(x,y)
```

- This is also present with the widget backend
- It is not present in the qt5 backend

@SylvainCorlay I see you're doing a lot of updates to ipympl these days (super job, btw). Have you seen anything that might affect this?

**Comment by timhoffm** [comment]
Given #14596 

> Going forward we should [...] deprecate the nbagg backend

is it still worth looking into performance issues of nbagg?

**Comment by SylvainCorlay** [comment]
@astrofrog it would be interesting if you could try out the master version of ipympl and let us know if this improves your experience. We are funding @martinRenou to put some cycles into `ipympl`, which now makes use of ipywidgets' binary messages, so that no base64 encoding is required. This should make things a bit smother hopefully.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay I see you're doing a lot of updates to ipympl these days (super job, btw). Have you seen anything that might affect this?

Yes, I don't think the current logic in ipympl / nbagg is right. At the moment, @martinRenou is mostly doing a cleanup work / removing dead code / removing dependency to jquery. Goals of the pass by martin are:
 - a general cleanup and modernization of the code
 - making ipympl use more of the underlying ipywidgets tools rather than redoing so much manually

Hopefully, a lot of the current glitches should be solved with this pass, and then the code base should be easier to move forward.

Another goal is to have the ipympl front-end to be a bit more stateful, which would help for some of the embedding contexts.

> Going forward we should [...] deprecate the nbagg backend

Yes, I think so too.

**Comment by martinRenou** [comment]
Concerning this "redraw on mouse move" issue, from what I understand I feel like matplotlib itself is requesting a redraw, so either we are sure that nothing changed and we don't redraw or we always redraw on request...

The thing is that sometimes it really needs a redraw on mouse move (e.g. displaying a label on mouse hover).

**Comment by tacaswell** [comment]
how are we shipping the cursor location text to the front end?  I wonder if that is accidentally causing the re-draw?

**Comment by martinRenou** [comment]
> how are we shipping the cursor location text to the front end?

If I understand correctly, the cursor location text is sent from here: https://github.com/matplotlib/matplotlib/blob/e39b334786b6a6ba6f3d9efccda6e355282f5766/lib/matplotlib/backend_tools.py#L337
And this code is triggered when the front-end sends a `motion_notify` event.

Actually, I tried with `ipympl` and moving the mouse around does not seem to trigger a redraw. As `ipympl` does not change that much on the back-end I would be tempted to say that it's due to the NbAgg front-end implementation.

**Comment by QuLogic** [comment]
I don't see any indication that there's any drawing happening in your screencast, other than the "busy" indicator.

I ran latest `master` and looked at Dev Tools, and the websocket only has a mouse_move event and a corresponding status message update. This is translating your mouse position into the "x=0.12345 y=6.7890" message in the toolbar.

There are also some messages flipping the execution status from idle to busy and back. I think that Jupyter is just flipping execution status any time it has to run Python code that's not itself. Maybe with the binary protocol, this can use a different channel, or be flagged to not do that.

**Comment by QuLogic** [comment]
Sorry, for some reason, I totally spaced out on the *clicking* part of the reproducer, which I can confirm. And I _can_ reproduce that on latest master, though not yet sure what is triggering it.

**Comment by QuLogic** [comment]
So the draw is only an empty blit because nothing's changed, but since transferring as base64 is not too efficient, it's a bit slow, though not as much as a full draw. Probably ipympl using binary transfer means this is less perceptible, but it may still be getting the extra draw.

After a while of digging, the cause of the draw seems to come from the IPython post execute hook:
https://github.com/matplotlib/matplotlib/blob/da8789b56f58aff98520279b3a464d7548d252a9/lib/matplotlib/pyplot.py#L136-L139
I don't think that hook is necessary in the notebook, so you could deregister it by calling `plt.uninstall_repl_displayhook`.

While that may be a suitable workaround for you, it's not the real cause because `draw_all` is supposed to only redraw figures that are stale:
https://github.com/matplotlib/matplotlib/blob/da8789b56f58aff98520279b3a464d7548d252a9/lib/matplotlib/_pylab_helpers.py#L133-L136

**Comment by QuLogic** [comment]
Annnnd the reason it's stale is in a round about way related to #6664:
```pytb
  File "matplotlib/lib/matplotlib/backend_bases.py", line 1754, in button_press_event
    self.callbacks.process(s, mouseevent)
  File "matplotlib/lib/matplotlib/cbook/__init__.py", line 225, in process
    func(*args, **kwargs)
  File "matplotlib/lib/matplotlib/backend_bases.py", line 1647, in pick
    self.figure.pick(mouseevent)
  File "matplotlib/lib/matplotlib/artist.py", line 513, in pick
    a.pick(mouseevent)
  File "matplotlib/lib/matplotlib/artist.py", line 513, in pick
    a.pick(mouseevent)
  File "matplotlib/lib/matplotlib/artist.py", line 502, in pick
    for a in self.get_children():
  File "matplotlib/lib/matplotlib/axis.py", line 751, in get_children
    *self.get_major_ticks(), *self.get_minor_ticks()]
  File "matplotlib/lib/matplotlib/axis.py", line 1325, in get_major_ticks
    numticks = len(self.get_minorticklocs())
  File "matplotlib/lib/matplotlib/axis.py", line 1243, in get_majorticklocs
    major_locs = self.major.locator()
  File "matplotlib/lib/matplotlib/ticker.py", line 2123, in __call__
    return self.tick_values(vmin, vmax)
  File "matplotlib/lib/matplotlib/ticker.py", line 2131, in tick_values
    locs = self._raw_ticks(vmin, vmax)
  File "matplotlib/lib/matplotlib/ticker.py", line 2070, in _raw_ticks
    nbins = np.clip(self.axis.get_tick_space(),
  File "matplotlib/lib/matplotlib/axis.py", line 2092, in get_tick_space
    tick = self._get_tick(True)
  File "matplotlib/lib/matplotlib/axis.py", line 1860, in _get_tick
    return XTick(self.axes, 0, major=major, **tick_kw)
  File "matplotlib/lib/matplotlib/axis.py", line 401, in __init__
    super().__init__(*args, **kwargs)
  File "matplotlib/lib/matplotlib/cbook/deprecation.py", line 387, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "matplotlib/lib/matplotlib/axis.py", line 146, in __init__
    self.apply_tickdir(tickdir)
  File "matplotlib/lib/matplotlib/axis.py", line 449, in apply_tickdir
    self.stale = True
  File "matplotlib/lib/matplotlib/artist.py", line 226, in stale
    self.stale_callback(self, val)
  File "matplotlib/lib/matplotlib/artist.py", line 54, in _stale_axes_callback
    self.axes.stale = val
  File "matplotlib/lib/matplotlib/artist.py", line 226, in stale
    self.stale_callback(self, val)
  File "matplotlib/lib/matplotlib/figure.py", line 43, in _stale_figure_callback
    self.figure.stale = val
  File "matplotlib/lib/matplotlib/figure.py", line 246, in stale
```
Button press starts picking -> `Figure.pick` -> `Axes.pick` -> `Axis.pick` -> `Axis.get_children` -> `Axis.get_major_ticks` -> stuff -> new `XTick`, which updates its position and this marks the `Axis` as stale (propogating up to the `Figure`.)

**Comment by tacaswell** [comment]
Do we need a more general way to suppress the stale processing or is the problem that we are getting a new xtick?

**Comment by anntzer** [comment]
I guess https://github.com/matplotlib/matplotlib/pull/11027 is related.

**Comment by QuLogic** [comment]
I don't think #11027 would have any effect on this. Current options seem to be:
* Don't use `Axis._get_tick`, but just find the font size from the stored kwargs and default rcParams. This mostly works, though it is slightly problematic for `Axis` subclasses (such as polar ones), because they don't have their own rcParams. See https://github.com/QuLogic/matplotlib/commit/afbb048cb487e028fae3425944478fe749bfff0b
* Override stale processing when calling `Axis._get_tick`. See https://github.com/QuLogic/matplotlib/commit/9411bbd1552df414daa7867cae5a248b70701ebe

Both of these fix the extra stale-ness, so if there's any preference, I can open a PR from either branch. I'm somewhat partial to the first method, but the possible effect on `Axis` subclasses is a bit of an unknown.

One approach I haven't tried is to check `Axis.majorTicks` for a `Tick` first.

**Comment by tacaswell** [comment]
I'm also partial to the first as it is simpler at run time.

**Comment by anntzer** [comment]
First option would also "fail" if the user manually changed the fontsize of the tick and expects that to be taken into account in ticknumber selection.  Carefully checking Axis.majorTicks for an already existing tick (without triggering unlazification!), i.e. the last suggestion, may work, though.

**Comment by QuLogic** [comment]
If they changed the fontsize of a single tick, than that wouldn't have been taken into account in the current code either? But anyway, the `Tick` properties are not canonical (which is probably annoying, but a different issue), the kwargs dictionary on the `Axis` are.

And yes, the unlazification is the tricky part.

**Comment by QuLogic** [comment]
I've put together the third option here: https://github.com/matplotlib/matplotlib/commit/d0b23344f543ad92f11d2fca72bfcc016d27aa50

Opinions on which one?

**Comment by tacaswell** [comment]
I think I like the first one best.  The second and third feel like they are spending too much effort to work around our selves which is sign we should reconsider what we are doing.

It is a bit annoying that the `Tick` object attaching itself to the Axes enough to participate in the stale tree even though it will never be shown on screen, however fixing that looks like a much bigger effort...

**Comment by QuLogic** [comment]
Took me a little bit to figure out the test, as this is only triggered with mpl20 style, not classic, but I've opened #17348 with the first option.
