### ISSUE TITLE
TypeError on plt.subplot(figure=plt.figure())

### ISSUE THREAD

**Issue by qmeeus** [matplotlib/matplotlib#14011]
### Bug report

**Bug summary**
When calling `plt.subplot` with a `figure` argument, we get:
```
TypeError: process_projection_requirements() got multiple values for argument 'figure'
```
The argument 'figure' is specified in the [doc](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplot.html)

The function `plt.subplot` uses `plt.gcf()` to get the current figure. It should check whether a figure was provided, eg. `fig = kwargs.pop('figure') if kwargs.get('figure') else plt.gcf()`

**Code for reproduction**

```python
plt.subplot(figure=plt.figure())
# OR EVEN
plt.subplot(figure=None)
```

**Actual outcome**
```                              
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-30-bdfa817205a7> in <module>
----> 1 plt.subplot(figure=None)

~/bin/anaconda3/lib/python3.7/site-packages/matplotlib/pyplot.py in subplot(*args, **kwargs)
   1082 
   1083     fig = gcf()
-> 1084     a = fig.add_subplot(*args, **kwargs)
   1085     bbox = a.bbox
   1086     byebye = []

~/bin/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py in add_subplot(self, *args, **kwargs)
   1347         else:
   1348             projection_class, kwargs, key = process_projection_requirements(
-> 1349                 self, *args, **kwargs)
   1350 
   1351             # try to find the axes with this key in the stack

TypeError: process_projection_requirements() got multiple values for argument 'figure'
```

**Matplotlib version**
  * Operating system: Linux
  * Matplotlib version: 3.0.2 (with conda and with pip)
  * Matplotlib backend: Qt5Agg
  * Python version: tested on 3.7.2 and 3.5

**Comment by anntzer** [comment]
This is fixed as of master (well, not the `subplot(figure=None)` case, but that's not document to work and I wouldn't bother with supporting that).

**Comment by timhoffm** [comment]
Only the special case `plt.subplot(figure=plt.figure())` works as the passed figure is the already the current figure.

~~~
fig1 = plt.figure()
fig2 = plt.figure()
plt.subplot(figure=fig1)
~~~
raises with `RuntimeError: Can not put single artist in more than one figure`.

`plt.subplot` explicitly documents itself as  "Add a subplot to the current figure." There is no `figure` keyword argument documented and I see it as an implementation flaw that it is accepted at all.

Also, I don't see the need to support it since pyplot is explicitly a state-based interface. Other pyplot functions generally also do not accept `figure` or `axes` parameters.
