### ISSUE TITLE
quiver(C=...) argument is not reasonably validated

### ISSUE THREAD

**Issue by sharun-s** [matplotlib/matplotlib#14060]
**Bug summary**

Quiver plot issue matching key label color with arrow color

**Code for reproduction**

```python
q=plt.quiver([1, 2,], [1, 1], [[49],[49]], [0],
   [[(0.6, 0.8, 0.5, 1.0 )],
    [(0.3, 0.1, 0.2, 1.0 )]],
       angles=[[45],[90]],
       )
plt.quiverkey(q, .5, .5, 7, r'vector2', labelcolor=(0.3, 0.1, .2, 1), labelpos='S', coordinates = 'figure')
```

**Actual outcome**

![Figure_1](https://user-images.githubusercontent.com/18413274/56828417-e5146d80-687e-11e9-84be-0054b4385e2f.png)

**Expected outcome**

The key label color and a vector are both set to (0.3, 0.1, .2, 1) but their colors are different.  

**Matplotlib version**
  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.0.3
  * Matplotlib backend: TkAgg
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: 

pip3 install matplotlib

**Comment by timhoffm** [comment]
This is actually not an issue with `quiverkey(labelcolor=...)`, as can be checked by setting the label color to 'red'. `(0.3, 0.1, .2, 1)` is a dark violet, and that's what the label color is.

The problem is that the `C` argument is not doing, what one might expect:

In `[[(0.6, 0.8, 0.5, 1.0 )], [(0.3, 0.1, 0.2, 1.0 )]]` the first two numbers 0.6, 0.8 are used to lookup the colors of the two arrows from the colormap (whose norm is in some way determined by all the numbers - didn't check exactly).

This is not a reasonable behavior - either we should raise an error with these inputs or support explicit colors in `C`. Either way the documentation must be improved as well.

**Comment by ImportanceOfBeingErnest** [comment]
xref https://stackoverflow.com/questions/55871552/matplotlib-quiver-plot-matching-key-label-color-with-arrow-color/

I think this is above all a documentation issue. It currently says for `C`

> C : 1D or 2D array, sequence, optional
       The arrow colors

and for `color`

> color : [ color | color sequence ], optional
       This is a synonym for the PolyCollection facecolor kwarg. If C has been set, color has no effect.

**Comment by anntzer** [comment]
Looks like a duplicate/variant of https://github.com/matplotlib/matplotlib/issues/13423, perhaps?
