### ISSUE TITLE
Reminder: PySide decref patch

### ISSUE THREAD

**Issue by dmcdougall** [matplotlib/matplotlib#1413]
PR #1323 monkey-patched a memory leak for windows. The exact line is [here](https://github.com/matplotlib/matplotlib/blob/v1.2.x/lib/matplotlib/backends/backend_qt4agg.py#L117).

We should check this periodically to see if it ever gets fixed upstream.

**Comment by anntzer** [comment]
FWIW this issue is still present as of pyside 1.2.4 (the latest version).  If we want to drop the "hack", one can switch instead to the solution proposed at https://bugreports.qt.io/browse/PYSIDE-140, i.e. create the QImage first and fill its buffer using the inner `_backend_agg.RendererAgg` (which is fortunately private, so everything is fair game :-))

**Comment by ctismer** [comment]
I stumbled today on this decref patch, which crashed when Python is compiled with debug.
We should re-open the issue and fix it in PySide2.
