### ISSUE TITLE
shift + w does not close all figures (has no effect)

### ISSUE THREAD

**Issue by paulbrodersen** [matplotlib/matplotlib#14208]
### Bug report

**Bug summary**

`shift + w` should close all open figures, as outlined in the [docs](https://matplotlib.org/users/navigation_toolbar.html). However, the shortcut does not seem to have any effect. Furthermore, none of the other equivalent -- albeit undocumented -- keybindings as defined in `plt.rcParams` (`'keymap.quit_all': ['W', 'cmd+W', 'Q'],`) have any effect either.  
This is in contrast to `ctrl + w`, which is supposed to close a single figure, and does that just fine. 

**Code for reproduction**

```python
fig1 = plt.figure()
fig2 = plt.figure()
# press shift + w
```

**Actual outcome**
Nothing happens.

**Expected outcome**

All figures are closed. 

**Matplotlib version**

  * Operating system: Ubuntu, Windows
  * Matplotlib version: 2.2.3, 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: python 2.7.13, python 3.7.3
  * Jupyter version (if applicable):
  * Other libraries: 

Ubuntu 17.03 / python 2.7.13 / matplotlib version 2.2.3 from source; 
Windows 10 / python 3.7.3 / matplotlib version 3.0.3 via Anaconda (default channel)

**Comment by nitrofortin** [comment]
CMD+q on macOS closed all showed figures, so maybe CTRL+q on Windows and Ubuntu would be worth trying.

**Comment by tacaswell** [comment]
Per the discussion in https://github.com/matplotlib/matplotlib/pull/4921 we never released a version that had the "Close all" turned on by default (but it is in toolmanager version of the toolbar).  We reverted the code change, but not the doc change.

I am inclined to make the docs consistent with the code as I am still worried about giving user a surprise way to fat-finger close all of the figures they spent the last hour getting just right (or I maybe projecting both my inability to type and exploratory workflow onto others ;) ).

**Comment by timhoffm** [comment]
@tacaswell I'm not particularly happy with just documenting this because of the different behavior between toolmanager/classic events. 

AFAICS there were two arguments:

- Adding this for classic event would further increases dependencies between pyplot and backends.
- Closing all windows is too dangerous.

To the first I'd answer that it's just another use of `Gcf` on the subsequent line to handling single-figure closing. It's not making it particularly worse.
To the second: If it's too dangerous there should also not be activated in toolmanger.

Alternative solution:
- Implement this also for classic events. Optionally do not set default shortcuts.

**Comment by anntzer** [comment]
I would suggest we implement quit_all for the classic toolbar and *also* simultaneously set the default value of keymap.quit_all to the empty list (we "can" do that because this only changes observable behavior on toolmanager, which is explicitly listed as "experimental").  This way people who want to use it can, well, use it :), and things stay consistent.
