### ISSUE TITLE
Feature request: add option to shrink pdfs via gs distillation

### ISSUE THREAD

**Issue by bastibe** [matplotlib/matplotlib#14206]
### Bug report

**Bug summary**

When saving a `pcolormesh` plot as PDF, file size does not change if the plot is cropped. Saving as PNG, or using a different plotting function such as `imshow` do not exhibit this issue.

**Code for reproduction**

```python
import numpy
from matplotlib.pyplot import subplots

# create a matrix with a diagonal gradient for plotting:
data = numpy.linspace(0, 1, 100)[None, :] * numpy.linspace(0, 1, 100)[:, None]

# plot entire data:
fig, ax = subplots()
ax.pcolormesh(data, clim=[0, 1])
fig.savefig("test1.pdf")

# plot lower-left quadrant:
fig, ax = subplots()
ax.pcolormesh(data, clim=[0, 1])
ax.set(xlim=[0, 50], ylim=[0, 50])
fig.savefig("test2.pdf")
```

**Actual outcome**

The above code creates two PDF files, which are almost equal in size.

**Expected outcome**

Since the second PDF file contains only a quarter of the image of the first PDF file, it should be smaller. 

Indeed, any one of the following strategies would show the second file much smaller than the first:
- saving as PNG instead of PDF
- using a different plotting function such as `imshow` instead of `pcolormesh`
- cropping the data to the plot-area before plotting

**Matplotlib version**
  * Operating system: Linux (OpenSuse Tumbleed)
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.6.6

Python installed through PyEnv, Matplotlib installed from wheel via `pip`.

**Comment by jklymak** [comment]
The whole pcolor object is still there to allow panning (for instance). I don’t think it’s worth the complexity to remove all the elements during a savefig versus just visually clipping them. If the user really needs a smaller PDF they can clip the data.  

You might also check rasterized=True though this will not likely lead to smaller files because the pcolor raster will be the same size.

**Comment by efiring** [comment]
There is a way to make *both* files smaller.  I made a little utility script for this, originally not for mpl pdfs but for various document pdfs, some of which are unreadable in their original form with readers like preview:
```python
#!/usr/bin/env python

# https://gist.github.com/firstdoit/6390547
# TODO: proper script interface, include options for different
#       pdf settings, output name

import os, sys

fname = sys.argv[1]
outname = os.path.splitext(fname)[0] + '_shrink.pdf'

cmd = ('gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer'
      ' -dNOPAUSE -dQUIET -dBATCH -sOutputFile="%s" "%s"' % (outname, fname))

print(cmd)
os.system(cmd)
```

Here is the result:
```
(py36) ~/temp $ ll test*.pdf
-rw-rw-r--  1 efiring  efiring  164045 May 25 09:38 test1.pdf
-rw-rw-r--  1 efiring  efiring   74079 May 25 09:39 test1_shrink.pdf
-rw-rw-r--  1 efiring  efiring  164827 May 25 09:38 test2.pdf
-rw-rw-r--  1 efiring  efiring   34733 May 25 09:39 test2_shrink.pdf
```
Notice that it cut even the first file size nearly in half, and then cut that in half again for the second file with the smaller area.

We have an option to use a distillation step like this with ps files.  Maybe we should add a similar option for pdf.

**Comment by efiring** [comment]
@bastibe I hope you don't mind my renaming your issue.

**Comment by bastibe** [comment]
@efiring that's cool, thank you!

To add to the original issue, my particular use case produced a PDF that was a couple hundred megabytes in size, and took *minutes* to generate. While your trick would help with the size issue, it does not help with the time part.

**Comment by efiring** [comment]
@bastibe For your original use case I think you are going to have to solve the problem yourself, using one or more of the following methods:
- If your grid is Cartesian with uniform spacing in x and y, then `pcolorfast` can use the image machinery.
- Call `pc.set_rasterized(True)` to rasterize the pcolormesh drawing in the pdf file.
- Subset your data before plotting instead of relying entirely on setting the view limits.

In general, using both rasterization and subsetting will probably be the most satisfactory if you are working with large arrays.

The decision to rasterize elements in a vector file format must be left with the user.
In the case of a Cartesian grid (with uniform or non-uniform spacing), I think it would be possible for us to automatically crop the data before rendering.  If it can be done without adding too much complexity it would be a nice optimization.

**Comment by bastibe** [comment]
@efiring thank you for your last response! I didn't know about the rasterization. This will solve my issue entirely. As far as I am concerned, you can close the issue.

**Comment by timhoffm** [comment]
IMHO not worth the effort.
