### ISSUE TITLE
Check if point is in path or not by contains_point

### ISSUE THREAD

**Issue by archman** [matplotlib/matplotlib#14207]
I tried to use `contains_point` method of `Patch` to check if some point is inside the closed path, e.g.
I defined an ellipse with the center, width, height and angle parameters:
```Python
>>> from matplotlib.patches import Ellipse
>>> e1 = Ellipse((3,5), 10, 8, 20)
>>> e1.contains_point((3,5))
True
```
The last line prints out `True`, which means the center is in the defined ellipse. But after I added the `e1` to an axes, the same line just print out `False`, e.g.
```Python
>>> import matplotlib.pyplot as plt
>>> from matplotlib.patches import Ellipse
>>> fig, ax = plt.subplots()
>>> e1 = Ellipse((3,5), 10, 8, 20)
>>> e1.contains_point((3,5))
True
>>> ax.add_patch(e1)
>>> e1.contains_point((3,5))
False
```
I'm testing the above with matplotlib of version 3.0.3. Is this a bug? Or something I did was not correct? Thanks!

**Comment by timhoffm** [comment]
This is a bug. Probably caused by `add_patch` changing the transform, which is not correctly accounted for by `contains_point`.

**Comment by tacaswell** [comment]
I am not sure this is a bug per-say, but confusion over what coordinate system the incoming point is in.  When it is first created, the artist has no transform which means it is implicitly the unit transfrom and all of your center, and radii are in the same coordinate frame.  Once you add the patch to the axes we set the transform to be the data trasfrom (data space -> screen space) (see https://matplotlib.org/3.1.1/tutorials/advanced/transforms_tutorial.html).  This means internal to `contains_point` we convert the path to screen units before asking if your point is in it but we do not transform the input point.  In the screen coordinate frame (3, 5) is way down at the bottom corner of the figure.  If you transfrom the input point to screen space via

```python
>>> e1.contains_point(ax.transData.transform((3, 5)))                                                                                       
True
```

it works again.  I suspect the reason it behaves this way is that almost always when we are checking if a point falls in a path it is because we are seeing if a mouse event was over a given artist and there the "natural" input is screen units (as that is (more or less) what the GUI toolkits give us).
