### ISSUE TITLE
[Feature request] Add a way to update the position of the Arrow patch.

### ISSUE THREAD

**Issue by davidmurray** [matplotlib/matplotlib#14217]
Hi,

Currently, the `arrow` class doesn't let you update the coordinates after creating the patch. That is, one **must** remove the old patch and create a new one just to move the arrows. This seems fairly inefficient.

Would it be possible to add some setter methods to let one change the arrow position and size without recreating a new one?

The motivation for this is that removing and adding a new patch requires a full re-draw (afaik) which is slow.

Thanks!

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): qt5agg
  * Python version: 3.7

**Comment by timhoffm** [comment]
### What needs  to be done:

- The `_path` of the `Arrow` itself is stored in normalized coordinates and not modified.
- Positioning is performed by the `_patch_transform`. This has to be recreated when chaning the position.
- It's probably best to store `x, y, dx, dy, width` in private variables so that they can be reused for recreating the transform.

This can be used as an example to start with:

~~~
import matplotlib.pyplot as plt
from matplotlib.patches import Arrow

fig, ax = plt.subplots()
ax.plot([0, 4], [10, 0])

a = Arrow(2, 0, 0, 10)
ax.add_patch(a)

# code for modifing the arrow goes here.

plt.show()
~~~

**Comment by ImportanceOfBeingErnest** [comment]
Given that the transform needs to be recreated, I would not expect updating to be any faster than removing and recreating the arrow.  
Possibly, making the `FancyArrowPatch` more user-friendly could be of higher priority.

**Comment by timhoffm** [comment]
It seems indeed, that the use of `Arrow` should be discouraged or even deprecated, because it suffers from the transform distorting it. This is essentially never desired.

**Comment by davidmurray** [comment]
Probably still relevant
