### ISSUE TITLE
Secondary axis called with [0, 1] might produce exceptions in case these are invalid data

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#14270]
### Bug report

Transform functions for the new feature `secondary_xaxis`  are always called with 0 and 1 at
instantiation, which might be invalid input for transformations.

**Code for reproduction**

E.g. trying to get a secondary axis showing mjd for a date axis

```python
import matplotlib.pyplot as plt
from matplotlib.dates import date2num, num2date
from datetime import datetime, timedelta
import numpy as np


MJDREF = datetime(1858, 11, 17, 0)


def trans(mpl_date):
    print(mpl_date)
    return (num2date(mpl_date) - MJDREF).total_seconds() / 86400


def inv(mjd):
    return date2num(MJDREF + timedelta(days=mjd))


t = np.array(['2018-01-01', '2018-03-03', '2018-04-10'], dtype='datetime64[s]')


fig, ax = plt.subplots()
ax.plot(t, [1, 2, 1])

t_ax = ax.secondary_xaxis('top', functions=(trans, inv))
```

Results in:

```
ValueError: Cannot convert 0 to a date.  This often happens if non-datetime values are passed to an axis that expects datetime objects.
```

**Matplotlib version**

  * Operating system: linux, but should be indepenent
  * Matplotlib version:  3.1
  * Matplotlib backend: all
  * Python version: 3.7

**Comment by anntzer** [comment]
I think the 0-1 invalid values problem is mostly fixed by https://github.com/matplotlib/matplotlib/pull/13593 (already merged), although there are some subsequent problems:
1) num2date returns a list, so subtracting MJDREF results in `TypeError: unsupported operand type(s) for -: 'list' and 'datetime.datetime'`.
2) even casting the result to an array
```
def trans(mpl_date):
    return (np.asarray(num2date(mpl_date)) - MJDREF).total_seconds() / 86400
```
results in `TypeError: can't subtract offset-naive and offset-aware datetimes`.

So I think at that point (in master) it's more a datetime handling problem (well, I don't know enough about datetime handling to really judge) rather than a secondary_axis problem.  Perhaps(??) it would be nice to have a `num2datearray` that returns a numpy array rather than a list of datetimes?

**Comment by jklymak** [comment]
Sorry secondary_axis has some issues.  Thanks for trying it out!   I’m away from computer until next weekend so I can’t look at this right away.

**Comment by MaxNoe** [comment]
Btw. I found an easy solution, see: https://gist.github.com/MaxNoe/3deef353cf377245f28a04f32dee6ee8

Still, I think it's a bit surprising that functions get called with hard-coded 0, 1

**Comment by MaxNoe** [comment]
> results in TypeError: can't subtract offset-naive and offset-aware datetimes.

Works if you specify `tzinfo=timezone.utc` for the MJDREF.

**Comment by jklymak** [comment]
I guess new axes have to be instantiated with some limits.  But in this case I guess secondary axes should check the parent axes at least before it tries to get ticks etc.

**Comment by MaxNoe** [comment]
The [0, 1] thingy is gone on master, so I'll close this. Thx for the help.

**Comment by jklymak** [comment]
Ok but does it need to be backported to 3.1.x?

**Comment by dstansby** [comment]
I think #13593 is probably too big to backport to master, but maybe if there's not an easier fix to this problem we could?

**Comment by tacaswell** [comment]
Given the scale of the backport that would be required, and that 3.2 is coming out soon, marking this as 3.2 and closing.
