### ISSUE TITLE
Different behaviour for savefig pdf and png at the axis

### ISSUE THREAD

**Issue by tzipperle** [matplotlib/matplotlib#14431]
### Bug report

**Bug summary**
Different behaviour for savefig pdf and png at the axis

**Code for reproduction**
Please make sure to minimize the number of dependencies required, and provide
any necessary plotted data.

```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
    
plt.style.use('fivethirtyeight')
COLOR = 'black'
mpl.rcParams['text.color'] = COLOR
mpl.rcParams['axes.labelcolor'] = COLOR
mpl.rcParams['xtick.color'] = COLOR
mpl.rcParams['ytick.color'] = COLOR

df = pd.DataFrame(np.random.rand(10, 4), columns=['a', 'b', 'c', 'd'])
df.loc[9,:] = 0

fig, ax = plt.subplots(figsize=(7, 5))
df.plot(ax=ax, kind='bar', stacked=True)
ax.set_ylim(-0.1, max(df.sum()) * 1.05)
ax.set_facecolor('white')
plt.savefig('test.pdf', bbox_inches='tight', edgecolor='none')
plt.savefig('test.png', bbox_inches='tight', edgecolor='none')
```
**Actual outcome**
If I save the figure to a pdf than there is a overlap at the x axis. This is not happening if I save the figure to a png format. 

```
plt.savefig('test.png', bbox_inches='tight', edgecolor='none')
```
![test](https://user-images.githubusercontent.com/6015123/58787548-51a32a80-85ea-11e9-821d-8cc0fa58a5f0.png)

```
plt.savefig('test.pdf', bbox_inches='tight', edgecolor='none')
```
[test.pdf](https://github.com/matplotlib/matplotlib/files/3246514/test.pdf)
![test-pdf-save-fig](https://user-images.githubusercontent.com/6015123/58787497-36d0b600-85ea-11e9-81a7-09993160bd3f.png)

**Expected outcome**
```
plt.savefig('test.pdf', bbox_inches='tight', edgecolor='none')
```
![test](https://user-images.githubusercontent.com/6015123/58787548-51a32a80-85ea-11e9-821d-8cc0fa58a5f0.png)

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.0.2
  * Matplotlib backend: module://ipykernel.pylab.backend_inline

  * Python version: 3.7.1
  * Jupyter version (if applicable):
  * Other libraries: 

conda -c conda-forge install matplotlib

**Comment by ImportanceOfBeingErnest** [comment]
If you zoom into the pdf you see that the bar starts at the middle of the line,

![image](https://user-images.githubusercontent.com/23121882/58795838-fe39d800-85fb-11e9-9a2b-cb8ff14a39ca.png)

This would be the expected output in all cases, due to the bar starting at y=0 and the line at y=0 extending in both directions.

For the pdf case, it is the pdf viewer (Acrobat, or whatever you use) that eventually determines how to render the vector file on screen.
In the png image, the bar, as well as the line, need to match with the available pixels. So it will happen that they overlap or not. Of course the larger the dpi (e.g `plt.subplots(dpi=400)`) the more likely you get exactly the true output, which would be the bar positionned at half the line width.

If you need a line overlapping the bar in all cases, you need to draw that line yourself. E.g. via `ax.axhline(y=0)`.

**Comment by tzipperle** [comment]
@ImportanceOfBeingErnest thanks for the quick and good explanation.
