### ISSUE TITLE
to_jshtml does not appear to respect retina configuration

### ISSUE THREAD

**Issue by jni** [matplotlib/matplotlib#14722]
## Bug report

**Bug summary**

I use `%config InlineBackend.figure_format = 'retina'` for sharp images in matplotlib inline mode. However, animations produced with `to_jshtml` are still using default dpi.

**Code for reproduction**

Thanks to @story645 for providing the template for this!

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation
from IPython.display import HTML


signal = np.random.random((100,))
smoothed = np.convolve(signal, np.full((3,), 1/3), mode='valid')

fig, ax = plt.subplots(figsize=(6,3))
ax.plot(signal, label='signal')
line, = ax.plot(0, smoothed[0], linewidth=3,
                color='C1', label='convolved')
ax.set_xticks(np.arange(0, 100, window_size))
ax.legend()

def animate(i):
    line.set_data(np.arange(i), smoothed[:i])
    return [line]

ani = animation.FuncAnimation(fig, animate, frames=98)

HTML(ani.to_jshtml())
```

![plt-retina-anim](https://user-images.githubusercontent.com/492549/60844059-df4fd800-a19d-11e9-82fd-1cc149bce4d2.png)

**Expected outcome**

The animation plot should be as sharp as the image plot.

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): 'module://ipykernel.pylab.backend_inline'
  * Python version: 3.6
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: 

mpl installed from pip, *I think*. ;)

**Comment by dopplershift** [comment]
So it looks like we use the `savefig.dpi` rcParam if no DPI is passed to `save()` on the animations, and `to_jshtml()` does not let you set it. The thing is, though, that `InlineBackend.figure_format = 'retina'` is an IPython thing, not a matplotlib thing, so that's probably why the setting isn't making its way to some place we get. I'm not sure what to do about that.

**Comment by jni** [comment]
Fascinating! Thanks for looking into it, @dopplershift! I presumed that the figure format stuff was secretly updating some rcParams.

... Isn't it??? :thinking: 

At any rate, I'd be happy with a way to get .js_html to look sharp, IPython or no IPython. :relaxed:

**Comment by dopplershift** [comment]
What happens if you set `rcParams['savefig.dpi']` to a higher value?

**Comment by dstansby** [comment]
It looks like IPython do the 'retina' dpi conversion at https://github.com/ipython/ipython/blob/7c93853733a806293d2fb0a51a3dc23f63d30900/IPython/core/pylabtools.py#L112-L114 , which is in a block of code to directly print figures to screen.

I guess this means that to get the animation stuff to work with 'retina', IPython would also need to have a similar helper function for animations. I think this issue is worth reporting upstream at https://github.com/ipython/ipython

**Comment by mjbaldwin** [comment]
Just leaving a comment that this is still an issue.

I can do something like `plt.rcParams['figure.dpi'] = 200` (instead of the default 100) to render at a twice the pixels, but then the animation just gets output twice as large. It isn't shrunken to appear more detailed the way Retina should be.

**Comment by jni** [comment]
https://nostalebots.xyz/ 🙏 (I don't want to tell anyone how to run their projects, just want to spread this idea around. 🙏 As always, thank you to all the maintainers! 🙏)
