### ISSUE TITLE
Rotated ytick labels are not centered

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#14865]
### Bug report

Rotated ytick labels are not centered.

Example:

~~~
import matplotlib.pyplot as plt

fig, (ax1, ax2) = plt.subplots(1, 2)

ax1.plot([0, 2, 1])
ax1.set_xticks([0, 1, 2])
ax1.set_xticklabels(['Label1', 'Label2', 'Label3'])
ax1.set_yticks([0, 1, 2])
ax1.set_yticklabels(['Label1', 'Label2', 'Label3'])

ax2.plot([0, 2, 1])
ax2.set_xticks([0, 1, 2])
ax2.set_xticklabels(['Label1', 'Label2', 'Label3'], rotation=90)
ax2.set_yticks([0, 1, 2])
ax2.set_yticklabels(['Label1', 'Label2', 'Label3'], rotation=90)

plt.show()
~~~

![grafik](https://user-images.githubusercontent.com/2836374/61594488-d541c680-abec-11e9-9ccf-ae22e48de95a.png)

**Actual outcome**
The rotated yticklabels in the right-side plot are right-aligned to the ticks.

**Expected outcome**
The rotated yticklabels in the right-side plot should be centered on their ticks.

As opposed to claims in https://github.com/matplotlib/matplotlib/issues/6288#issuecomment-220880416 this is not backend-dependent (Checked qtagg and wxagg. Both yield the same plot).

**Comment by ImportanceOfBeingErnest** [comment]
Setting the vertical alignment to `center` would of course solve this, 

    ax2.set_yticklabels(['Label1', 'Label2', 'Label3'], rotation=90, va="center")

Now the question is if one wants to couple the vertical aligment property to the rotation? I would oppose this, simply because those are independent parameters and its surely confusing to see a 90 degrees rotated text suddenly change its aligment compared to an 89 degrees rotated text.

**Comment by timhoffm** [comment]
But a 0 degree text is already center aligned.

Need to check the in between values and also what happens on x, but I‘m quite sure, we‘re not consistent currently.

**Comment by ImportanceOfBeingErnest** [comment]
vertical alignment is `"center_baseline"`, horizontalalignment is `"right"`. If you rotate such text, it seems perfectly consistent to me.

![image](https://user-images.githubusercontent.com/23121882/61628807-9f9bec80-ac83-11e9-829e-3904be38eb0c.png)

**Comment by jklymak** [comment]
Yeah I dont see how we can change alignment based on angle/rotation.

**Comment by QuLogic** [comment]
One could change rotation mode, but this would break the common case of 45 degree rotations. It is really only 90 degree rotation that seems 'wrong', but I don't think there's anything we can do about that.

**Comment by anntzer** [comment]
Perhaps a better solution may be to use rotation_mode="anchor"? (https://matplotlib.org/devdocs/gallery/text_labels_and_annotations/demo_text_rotation_mode.html)  Well really what we'd need is "anchor" in y and "default" in x I think?

**Comment by QuLogic** [comment]
The rotation mode is _already_ set to "anchor", but only on the y-axis. I'm not sure why they're different though. Perhaps to ensure correct baseline anchoring?

**Comment by anntzer** [comment]
I have admittedly not looked too much into it, but the idea was basically "rotate the text, then center it vertically and right-align it horizontally".

**Comment by timhoffm** [comment]
Having thought about this, I believe that all non-90° rotations are fine. The labels point to the tick:
![grafik](https://user-images.githubusercontent.com/2836374/61745670-54c0c880-ad9a-11e9-97e1-401d5795de3c.png)

Well, for more than 60° it gets less clear, but roughly ok.

The situation really changes discontinuously for 90° rotations. The visual direction does not work here. Instead the visual association is between the rectangular bounding box and the tick. Therefore, ticks should be centered.

![grafik](https://user-images.githubusercontent.com/2836374/61746547-38be2680-ad9c-11e9-8f2a-1b8b0c5e18df.png)

This can be achieved by overriding `YAxis.set_ticklabels`:

~~~
def set_ticklabels(self, ticklabels, *args, minor=False, **kwargs):
    if kwargs.get('rotation') in [-90, 90] and 'verticalalignment' not in kwargs:
        kwargs['verticalalignment'] = 'center'
    super().set_ticklabels(self, ticklabels, *args, minor, **kwargs)
~~~

**Comment by ImportanceOfBeingErnest** [comment]
A "fix" would need to be much more complicated than the above, because ticklabels could also be rotated via `set_rotation` of the labels. So it would need to be a subclassed `Text` that is aware of changes at runtime...

Anyways, as [commented earlier](https://github.com/matplotlib/matplotlib/issues/14865#issuecomment-513597868), I am -1 on such such coupling between independent parameters.

**Comment by timhoffm** [comment]
I don't think it's necessary to go that complicated. There needn't be a permanent coupling between rotation and alignment. Only the default verticalalign of  `set_ticklabels` depends on rotation.

I argue that
1. the positioning showed in https://github.com/matplotlib/matplotlib/issues/14865#issuecomment-514379344 is the desireable layout of tick labels (independent on how to get there)
2.  if the user uses `set_ticklabels` she should get a plot with a reasonable alignment by default.

This improved user experience can be achieved with little effort and I don't see any real disadvatages in doing so.

**Comment by ImportanceOfBeingErnest** [comment]
To reinterate, my argument is that you should not get a different output whether you use the usual way of rotating ticks, like `plt.setp(ax.get_yticklabels(), rotation=90)` or `ax.tick_params(axis="y", labelrotation=90)`, or whether you use `ax.set_yticklabels(list_of_labels, rotation=90)`. The latter is in general undesired, because it changes the formatter to a `FixedFormatter` and hence only useful in certain cases, where also a `FixedLocator` (e.g. via `set_yticks()`) is being used. "Fixing" this for only one of the code paths introduces inconsistent behaviour, which is not desireable at all.

So to get a consisten behaviour, it is not enough to change `set_ticklabels`, but you need to either subclass `Text`  and provide the linkage via property setters or use callbacks on changed attributes.

**Comment by timhoffm** [comment]
I do not agree. IMHO, `ax.set_yticklabels(list_of_labels, rotation=90)` is a more high-level API than `plt.setp(ax.get_yticklabels(), rotation=90)` and `ax.tick_params(axis="y", labelrotation=90)`. While the latter two only modify a property of existing labels, the former creates these labels. Therefore, it hat the right to also influence aligment.

From a usability perspective, it's not intuitive that one should do `ax.set_xticklabels(['Label1', 'Label2', 'Label3'], rotation=90, verticalalign='center')` to get reasonable rotated labels. The straight forward `ax.set_xticklabels(['Label1', 'Label2', 'Label3'], rotation=90)` just results in a bad plot that I don't anybody would want.

**Comment by ImportanceOfBeingErnest** [comment]
It simply doesn't make sense. People who use a `FixedFormatter` should see a different plot than people who use the default one or any other formatter?

**Comment by jklymak** [comment]
I think I agree that `ax.tick_params` and `ax.set_yticklabels` should have the same behaviour, and that it doesn't make sense to change the FixedFormatter case to be different than the automatic cases.  Can this change be applied to both?  

Not convinced that has to extend to `plt.setp`, which is just a helper function in my opinion, and assume the user knows the state of the objects they are applying `setp` to

**Comment by timhoffm** [comment]
One could patch `ax.tick_params`. But thinking again, one should actually patch `YAxis.set_ticklabels` and `YAxis.set_tickparams`. Otherwise `ax.yaxis.set_ticklabels` would behave differently again. And the special-alignment is acually related to the yaxis geometry, so it naturally belongs there.
