### ISSUE TITLE
plt.ioff() not supressing figure generation

### ISSUE THREAD

**Issue by Yoshi2112** [matplotlib/matplotlib#14950]
### Bug report

**Bug summary**
Usual behaviour for supressing plots (by enabling plt.ioff()) no longer working since update to latest version of conda.

**Code for reproduction**
```python
import numpy as np
import matplotlib.pyplot as plt

x = np.random.rand(10)
y = np.random.rand(10)

plt.ioff()
plt.plot(x, y)
```

**Actual outcome**
In Spyder IDE, still generates figure window. 

**Expected outcome**
Figure window should not appear. plt.ioff() should disable interactive mode, and require a plt.show() call to generate figure window.

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt5Agg
  * Python version: 3.7.3
  * Jupyter version (if applicable):
  * Other libraries: numpy 1.16.4

conda

Default channel (via https://www.anaconda.com/distribution/ )

**Comment by WeatherGod** [comment]
If I remember correctly, Spyder has its own backend, right? I wonder if
they aren't properly recognizing `ioff()`? Does the same issue happen when
running the code from a vanilla python interface?

**Comment by ImportanceOfBeingErnest** [comment]
Spyder does not have its own backend (PyCharm has, though).  
However, spyder has a "Support for grahics (Matplotlib)" mode, which is probably turned on by default. 

![image](https://user-images.githubusercontent.com/23121882/62313274-a3ecb480-b490-11e9-9db7-80ebfc4cf2ea.png)

Many people like this mode, because it allows to choose a backend on a by-file- or by-project basis etc., but support for consequences of using this should probably directed towards Spyder.

**Comment by Yoshi2112** [comment]
@ImportanceOfBeingErnest 

If I force inline plots by disabling Matplotlib support in Spyder, the interactive mode works correctly. Inline also works correctly when manually selected as the graphics backend.

The other modes don't work as I'd expect. I'd always used the "Automatic" setting, which would probably be Qt5. Manually selecting Qt5 had the behaviour described in the OP - plt.ioff() failed to suppress the generation of a figure window.

Of the other two modes, Qt4 failed to run because Qt5 was running (?), and Tkinter was successfully suppressed, but failed to display a plot when interactive mode was selected. A figure window was generated, but frozen. This might be an issue with missing modules or something though? I'm not exactly a dev.

Is this a problem with matplotlib? Or perhaps an issue with the Spyder IDE failing to adhere to the interactive mode settings?

**Comment by ccordoba12** [comment]
Chiming in in behalf of Spyder. We set the Matplotlib backend using the `%,matploitlib` IPython magic, so if there's a problem is with that magic.

**Comment by ImportanceOfBeingErnest** [comment]
Indeed it doesn't look like a Spyder issue. I was able to reproduce solemnly on the Ipython QtConsole, running 

![image](https://user-images.githubusercontent.com/23121882/62389173-61de7400-b55f-11e9-85fb-aad5f1c42351.png)

Now it turns out this is indeed a matplotlib issue. 
It bisects to https://github.com/matplotlib/matplotlib/pull/13664 ("Backport PR #12637 on branch v3.1.x (Tell IPython the correct GUI event loop to use for all backends.)"), and hence originates from

#12637 ("Tell IPython the correct GUI event loop to use for all backends.")

**Comment by tacaswell** [comment]
Suspect that https://github.com/ipython/ipython/issues/11837 is also related.

**Comment by tacaswell** [comment]
I suspect that if you call `plt.ioff()` after you have created the first figure it will work as expected.

**Comment by ImportanceOfBeingErnest** [comment]
Yes, but that's not really an option if you want to run your whole code in one cell, like e.g. spyder does.

**Comment by Carreau** [comment]
See #14979 for the fix of the IPython side issue; and thomas is right that the piece of code that is responsible for the IPython-side-issue seem to also enable matplotlib gui integration and switch back to interactive. 

It seem to be triggered as a side effect of `import matplotlib.pyplot as plt` So we should likely detect that the `%matplotlib` magic has been called and not trigger the `ip.enable_maplotlib()`
