### ISSUE TITLE
Adopting uarray as a backend system

### ISSUE THREAD

**Issue by hameerabbasi** [matplotlib/matplotlib#15057]
As far as I can tell, Matplotlib has a custom-rolled backend solution. We've built a solution that we hope is general enough for Matplotlib and other projects while also being a one-stop-shop for backend-dispatch.

The project is called [`uarray`](https://uarray.readthedocs.io/en/latest/), and it's meant to be a general multiple-dispatch and backend-dispatch solution.

This is meant to be a discussion about whether Matplotlib maintainers are willing to have this discussion and what it would take for Matplotlib to adopt `uarray` as its preferred backend system.

**Comment by anntzer** [comment]
I have only skimmed through the uarray docs, but it is not clear to me what it could offer to matplotlib's backends.  Specifically (I may well be mistaken), it looks like one of uarray's goals is to be able to write (multi)methods taking arguments of various types (provided by various backends), but in matplotlib's case, the APIs provided by all backends essentially all take arguments of the same type (mostly simple scalar types -- integers, floats, strings).
Also note that because many of matplotlib's backends (the interactive ones) are tied to a specific GUI event loop, there are specific rules regarding the cohabitation between backends (specifically, once a window has been created, it is (usually) impossible to switch from an interactive backend to another one because of the way GUI toolkits are implemented).
If there is anything specific that you believe uarray could offer to matplotlib I would be happy to hear more about it.

**Comment by story645** [comment]
In Matplotlib, backends are basically what render the pixels to screen. Uarray looks like it could potentially slot into a new proposed data model for Matplotlib, but what would be the advantage of using uarray over natively writing ufuncs similar to how dask handles it's dispatch system?

**Comment by tacaswell** [comment]
To build on what @anntzer is saying is that Maplotlib has _mostly_ solved the dispatch / backend to the level we need to.  The place where we need the dispatch the most is the rendering backends and we currently implement that with a visitor pattern so directly adopting `uarray` for the rendering backends would be a pretty major re-factoring.

We also relay on taking in basically what ever the user wants to hand us (and then duck type them as best as we can (modulo units) to numpy arrays and scalars).  

As @story645 says, we are looking at doing some major refactors to the internal data-model and this may be useful there, but I suspect that we would benefit more from {numpy, xarray, pandas} adopting uarray rather than using it our selves.

**Comment by hameerabbasi** [comment]
>  The place where we need the dispatch the most is the rendering backends and we currently implement that with a visitor pattern so directly adopting uarray for the rendering backends would be a pretty major re-factoring.

Could you point me to code where this is done?

> We also relay on taking in basically what ever the user wants to hand us (and then duck type them as best as we can (modulo units) to numpy arrays and scalars).

The point of `unumpy` is to do these operations/duck-typing for you. 😄 

> As @story645 says, we are looking at doing some major refactors to the internal data-model and this may be useful there, but I suspect that we would benefit more from {numpy, xarray, pandas} adopting uarray rather than using it our selves.

We do have backends for NumPy in `unumpy`, and anyone is welcome to make a `uxarray`/`upandas`, but the plan is for the backends to move, at some point, into the packages themselves.

**Comment by WeatherGod** [comment]
I think what is being misunderstood here is that matplotlib's backends
aren't doing math on data. Our backends are GUI backends for event handling
and window management, not for computation. I also don't see how uarray can
be used. We don't have any defined ufuncs. All data passed into our
plotting functions are either assumed to be numpy array-like or are
explicitly converted to them via `np.asanyarray()`. We don't do math on
data without first having done that.

**Comment by hameerabbasi** [comment]
> I think what is being misunderstood here is that matplotlib's backends
aren't doing math on data.

`uarray` is a general backend-dispatch system independent of array math, `unumpy` builds on top of `uarray` to build multimethods and backends for array math.

**Comment by tacaswell** [comment]
The base classes are in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py and then each of the "backends" implement the required methods.

To see how it is used trace through starting from `Figure.savefig` -> `canvas.print_figure` -> `Figure.draw`.

**Comment by hameerabbasi** [comment]
I see. You say "mostly", @tacaswell... Are there some features it doesn't have?

**Comment by tacaswell** [comment]
I was hedging a bit.  The double layered dependency injection is a bit awkward and in can be confusing to work through, but it is serving our needs.  There is an on-going campaign to simplify and reduce the code in the backends (spearheaded by @anntzer ) 

Now that you have looked at what exactly we mean by "backend" in the Matplotlib context, do you still think `uarray` is a good fit?   

In the documentation it says that uarray could be used to style Matplotlib, how do you envision that working?

**Comment by hameerabbasi** [comment]
cc @anntzer 

With `uarray`, you would define "trivial multimethods" that don't rely on any types, and then do something like the following to switch backends:

[Here are docs on writing multimethods.](https://uarray.readthedocs.io/en/latest/multimethod_docs.html)

```python
with ua.set_backend(mpl_backend_of_choice):
    # your plotting code here
```

OR

```python
ua.set_global_backend(mpl_backend_of_choice)
# your plotting code here
```

You would need to define a `__ua_function__` method for each backend. And that would be all you need to do, more or less. [Here are docs on writing backends.](https://uarray.readthedocs.io/en/latest/libauthor_docs.html)

**Comment by anntzer** [comment]
I am open to trying new techniques, but with all due respect, I really do not understand what part of the Matplotlib codebase you are concretely proposing to replace with uarray.

**Comment by hameerabbasi** [comment]
@tacaswell mentioned that you were trying to get rid of dependency injection and simplify the current code in Matplotlib backends. The code he pointed to in https://github.com/matplotlib/matplotlib/issues/15057#issuecomment-523673277 is one example of what would need to be replaced with `uarray`-dependent code.

The backend mechanism in general would need to be re-written.

> In the documentation it says that uarray could be used to style Matplotlib, how do you envision that working?

That comment was written when I didn't understand the internals of Matplotlib, and in fairness, I still don't. But what I do hope is that `uarray` can help simplify things in the parts of Matplotlib where dispatch is needed.

**Comment by anntzer** [comment]
Perhaps @tacaswell can provide a concrete example then... :)

**Comment by anntzer** [comment]
Thanks for the pointer to uarray, but I'm going to close this as non-actionable given that nothing concrete has been suggested so far.  Feel free to request a reopen with more ideas.
