### ISSUE TITLE
Aggregate several AxesSubplot after multiprocessing to draw a matplotlib figure

### ISSUE THREAD

**Issue by jbtruffault** [matplotlib/matplotlib#15081]
I create this post to bring attention to this thread where I explain my problem: https://stackoverflow.com/questions/57269797/aggregate-several-axessubplot-after-multiprocessing-to-draw-a-matplotlib-figure It provides details and reproducible code, so I prefer to not duplicate.

Can someone tell me if it's a bug or if I missed something in my code ?

Thanks in advance !

**Comment by ImportanceOfBeingErnest** [comment]
It's not a bug in matplotlib. Also, there is nothing wrong with the code itself. The problem is that multiple processes cannot work on the same object in python. So multiprocessing is great if one wants to e.g. save several different versions of a figure to disk, but not for creating a single figure through several processes.
