### ISSUE TITLE
set_size_inches doesn't resize window on macosx backend

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#15131]
Using `set_size_inches()` correct resizes the figure canvas, but doesn't resize the window with the `macosx` backend:

```python
import matplotlib
matplotlib.use('macosx')
import matplotlib.pyplot as plt

fig1, ax = plt.subplots()
fig1.set_size_inches(2, 2)
plt.show()
```
 results in 
<img width="639" alt="Screenshot 2019-08-26 at 18 06 29" src="https://user-images.githubusercontent.com/6197628/63708398-4009a180-c82c-11e9-884e-bd92bbe57afe.png">

**Comment by lukelbd** [comment]
Hopefully this can be fixed soon. This issue prevents me from performing [automatic figure resizing](https://proplot.readthedocs.io/en/latest/subplots.html#Automatic-layout) in proplot when the MacOSX backend is enabled (on macOS Catalina).

**Comment by jklymak** [comment]
Is this a reversion, or did it always do this?

**Comment by lukelbd** [comment]
Not sure. Looks like the MacOSX backend dates back [very far](https://matplotlib.org/3.0.0/users/prev_whats_new/whats_new_1.2.html#python-3-x-support) but I don't see any other issues. I wouldn't be surprised if this is restricted to the latest macOS versions (Catalina, and IIRC this was also an issue for me on Mojave). Or perhaps very few people resize their figures in-place :)

**Comment by jklymak** [comment]
.. I have it behaving this way back to at least 2.1.0 on Catalina.  Someone who needs this to work will need to dig into it to see what the problem is.  Given that most of the devs use Qt5 or webAgg, and this has been around for a few years, I wouldn't count on this to be fixed "soon".

**Comment by lukelbd** [comment]
Sorry if that came off wrong, just wanted to generate some discussion. I'll definitely dig around if I get the chance (I also use Qt5 but have been trying to make my auto-figure resizing algorithm more robust).

**Comment by lukelbd** [comment]
... wow I significantly overestimated the complexity of this problem. Fixed it in two lines in `backend_macosx.py`. Submitting a PR soon.

**Comment by lukelbd** [comment]
The culprit is that `Figure.set_size_inches` calls the figure manager `resize` method to "push" the resize to the backend, but `FigureManagerMac` does not implement a `resize` method:

https://github.com/matplotlib/matplotlib/blob/c18549489d77d1dfe03710e66a8edf3fbf1bb743/lib/matplotlib/backends/backend_macosx.py#L107-L129

So just the empty `FigureManagerBase.resize` gets called. It also seems that `_macos.FigureManagerMac` (inherited by `FigureManagerMac`) does not have a resize method:

https://github.com/matplotlib/matplotlib/blob/3a2589bee0d7e9abfa6d1acbefb668b2fad5f71c/src/_macosx.m#L671-L869

I tried to implement my own resize method by accessing the "window" like in `backend_qt5.py`

https://github.com/matplotlib/matplotlib/blob/c18549489d77d1dfe03710e66a8edf3fbf1bb743/lib/matplotlib/backends/backend_qt5.py#L629-L635

but there does not seem to be any sort of "window" object on `FigureManagerMac` (its `dir` just contains `['button_press', 'button_press_handler_id', 'canvas', 'close', 'destroy', 'full_screen_toggle', 'get_window_title', 'key_press', 'key_press_handler_id', 'num', 'resize', 'set_window_title', 'show', 'toolbar', 'toolmanager']`). Not sure where to go from here; hopefully this helps someone else.

**Comment by dopplershift** [comment]
I'm making some headway on this, along with a variety of other clean-ups for the macosx backend. It's complicated by the fact that the Figure windows on the Mac backend aren't using any kind of layout--it's hand-coded widget placement.

**Comment by dstansby** [comment]
Thanks for the PR/fix @dopplershift !
