### ISSUE TITLE
Line2D object is printed over an Arc object, even when the arc is added after the line

### ISSUE THREAD

**Issue by johannfaouzi** [matplotlib/matplotlib#15173]
### Bug report

**Bug summary**

A `Line2D` object is printed over an `Arc` object, even when the `Arc` object is added after the `Line2D` object with `add_artist`.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
from matplotlib.patches import Arc
from matplotlib.lines import Line2D


fig, ax = plt.subplots(figsize=(6, 6), frameon=False)

green_line = Line2D([0.2, 0.8], [0.5, 0.5], color='green', lw=6)
black_line = Line2D([0.5, 0.5], [0.2, 0.8], color='black', lw=6)
red_arc = Arc((0.5, 0.5), 0.4, 0.4, theta1=-90, theta2=180, color='red', lw=6)
blue_arc = Arc((0.5, 0.5), 0.4, 0.4, theta1=180, theta2=360, color='orange', lw=6)
ax.add_artist(black_line)
ax.add_artist(green_line)
ax.add_artist(red_arc)
ax.add_artist(blue_arc)
```

**Actual outcome**

![Capture d’écran 2019-09-02 à 14 04 46](https://user-images.githubusercontent.com/17053934/64113460-aa6d9500-cd8a-11e9-93b3-3f65aa220cc9.png)

**Expected outcome**

I expected both arcs to be printed 'over' the lines, since they are added after.

**Matplotlib version**
Original Anaconda distribution:
  * Operating system: MacOS
  * Matplotlib version: 3.0.2
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.7

**Comment by ImportanceOfBeingErnest** [comment]
Lines have by default a higher `zorder` than patches. The reason is that patches mostly take a larger area in the plot and should not hide any finer grained plots, independent on the order they are created. Prominent example would be a bar plot and a line plot where you always want to have the lines in front of the bars.

This means for other custom plotting orders, `zorder` must be set manually.

```
line = Line2D(..., zorder=1)
arc = Arc(..., zorder=2)
```

or 

```
line.set_zorder(1)
arc.set_zorder(2)
```

<hr>

Unrelated, but maybe helpful in other cases: Mind that we have `ax.add_line` and  `ax.add_patch` methods. If using those instead of `ax.add_artist`, autoscaling will work better.

**Comment by johannfaouzi** [comment]
Thank you very much for the answer and the tips. Sorry for opening an issue for something that is documented (but not that easy to find).
