### ISSUE TITLE
`matplotlib.pyplot.hist` is plotting different width for different bins, when width is less than or equal to 0.1

### ISSUE THREAD

**Issue by mhnlp** [matplotlib/matplotlib#15344]
### Bug report

**Bug summary**

`matplotlib.pyplot.hist` is plotting different width for different bins, when width is less than or equal to 0.1

**Code for reproduction**

```python
rng = np.random.RandomState(10)
a = rng.normal(size=10000)
# try different widths {0.01, 0.02, 0.05, 0.1, 0.2}
_ = plt.hist(a, bins=30, width = 0.03)
```

**Actual outcome**

The width of some bins are not equal to others

![](https://i.stack.imgur.com/x1w2Q.png)

**Expected outcome**

The width of each bins should be equal.

**Matplotlib version**

  * Operating system: Ubuntu 18.04.2 LTS
  * Matplotlib version: 3.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.3
  * Jupyter version (if applicable): 4.4.0
  * Other libraries: 

conda install matplotlib

pypi

**Comment by timhoffm** [comment]
I assume the image is actually taken with `width=0.01`.  This is a rasterization effect.

Roughly, you have am x-range of 8 spread about maybe 600 pixels; i.e. 0.013 per pixel. Since you can't draw at fractional pixels, the lines are snapped to the nearest possible pixel. Most of the times distances of 0.01 result in one pixel difference, but sometimes it's two. This one-pixel jitter is a fundamental property of all rasterization output. The only way to reduce this effect is to increase the figure size so that your smallest features are significantly larger than 1px.

**Comment by jklymak** [comment]
Or change the dpi.
