### ISSUE TITLE
ticks or labels of the first heatmap are not being removed during an animation

### ISSUE THREAD

**Issue by nbro** [matplotlib/matplotlib#15428]
### Bug report

**Bug summary**

The ticks or labels on the axes of a figure that shows a seaborn.heatmap are not removed, even though `ax.set_xticks([])` is being called. In the code below, I create a heat map both before the creation of `anim` and in `init`, but even without calling `init` (you can comment it) the problem persists.

**Code for reproduction**

```python
import matplotlib.animation as animation
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns


def animate_heat_map():
    fig = plt.figure()

    nx = ny = 20

    data = np.random.rand(nx, ny)

    ax = sns.heatmap(data, vmin=0, vmax=1)
    ax.set_xticks([])
    ax.set_yticks([])

    def init():
        plt.clf()
        ax = sns.heatmap(data, vmin=0, vmax=1)
        ax.set_xticks([])
        ax.set_yticks([])

    def animate(i):
        pass

    anim = animation.FuncAnimation(fig, animate, init_func=init, interval=1000)

    plt.show()


if __name__ == "__main__":
    animate_heat_map()
```

**Expected outcome**

No ticks or labels on the axes are shown.

**Matplotlib version**

  * Operating system: Mac OS X Catalina
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.4
  * Other libraries: seaborn

I installed Matplotlib with `pip` and Python with Homebrew.

**Comment by jklymak** [comment]
Since seaborn is making the original object, it seems reasonable to bring the issue up with them?  https://github.com/mwaskom/seaborn  Or have you already isolated this to a matplotlib bug?  If so, can you reproduce w/o seaborn?

**Comment by jklymak** [comment]
I mean you get the `ax` object from seaborn, so they would be best equipped to tell you how to change the x/y ticks.  I'm going to close for now, but feel free to post again if you think you have a matplotlib bug isolated.

**Comment by nbro** [comment]
@jklymak But the `ax` used is of the figure created with `fig = plt.figure()`. You should leave this issue opened until it is solved.

**Comment by jklymak** [comment]
@nbro, please provide a self-contained example that does not include seaborn.  Maybe you can reproduce the error using `imshow` instead of `heatmap`?  Also please check that your animation code is doing what you think it does.  `plt.figure()` does not create an axes object, so perhaps that is your problem.

**Comment by ImportanceOfBeingErnest** [comment]
The problem is this line in seaborn's heatmap plotting routine: https://github.com/mwaskom/seaborn/blob/222d54467685b96ec9fabb32a9b382e35c745b1f/seaborn/matrix.py#L318

    ax.figure.draw(ax.figure.canvas.get_renderer())

Meaning, inside the animation's `init` function, the figure will be drawn first (no draw_idle here), so the first animation frame is shown on screen until the next frame starts.

I guess from matplotlib's design point of view it's simply wrong to `draw` anything inside the functions that compose the animation and instead let the `Animation` class do the drawing. Hence, I doubt anything should be done here; if people want to animate heatmaps, they can do it without using seaborn.

**Comment by nbro** [comment]
@ImportanceOfBeingErnest The interesting thing is that, if you attempt to save the animation to a file, it works as expected, that is, you will not see the labels on the first frame.

**Comment by ImportanceOfBeingErnest** [comment]
Sure, because what is saved is drawn anyways *after* you set the ticks to an empty list.

**Comment by nbro** [comment]
@ImportanceOfBeingErnest Thanks for your help!
