### ISSUE TITLE
matplotlib cannot be installed properly in Python 3.8

### ISSUE THREAD

**Issue by timeneverdie** [matplotlib/matplotlib#15568]
See this post: 

https://stackoverflow.com/questions/58597399/pip-install-command-error-out-with-exit-status-1-when-installing-matplotlib

I met the same problem and got the same error code. 

The solution is to change back to Python 3.7.

**Comment by tacaswell** [comment]
That stack overflow question is because you are missing freetype (which is an external c dependency) (see https://matplotlib.org/users/installing.html#installing-from-source).  The easiest way to fix this is to follow the instruction for how to build a local freetype installation at https://matplotlib.org/devel/contributing.html#retrieving-and-installing-the-latest-version-of-the-code

If you need more help, please move this conversation to https://discourse.matplotlib.org/c/community/install .

**Comment by timeneverdie** [comment]
> That stack overflow question is because you are missing freetype (which is an external c dependency) (see https://matplotlib.org/users/installing.html#installing-from-source). The easiest way to fix this is to follow the instruction for how to build a local freetype installation at https://matplotlib.org/devel/contributing.html#retrieving-and-installing-the-latest-version-of-the-code
> 
> If you need more help, please move this conversation to https://discourse.matplotlib.org/c/community/install .

I found you replied on stackoverflow. 

You said, "You are missing freetype which is a required external dependency to build python from source which you need to do because we have not posted py38 wheels for Matplotlib (we are working on it)."

Would you mind telling me the exact date for that works in Python 3.8? Thanks anyway.

**Comment by tacaswell** [comment]
Matplotlib works correctly with py38 (the tests are passing on osx and linux on CI) and to my knowledge has no problem compiling on windows.  The issue you are having is that you are missing a required dependency.  If you need more help fixing your local compilation / installation issues, please open a topic on  https://discourse.matplotlib.org/c/community/install .
