### ISSUE TITLE
Inconsistent plot with and without colorbar

### ISSUE THREAD

**Issue by martinfleis** [matplotlib/matplotlib#15566]
### Bug report

**Bug summary**

Plotting without colorbar gives different colors than plotting with one if all plotted values are equal. While this might be expected behaviour, I find it a bit strange. Plotting colorbar alongside the plot should only show the legend to what is plotted, not change the plot itself, I would say. We ran into this recently with geopandas https://github.com/geopandas/geopandas/pull/1163 . Is this the intended behaviour of matplotlib or is it something which should be changed? 

**Code for reproduction**

```python
Without:
sc = plt.scatter(range(3), range(3), c=[1, 1, 1], cmap='viridis')
```
With:
```python
sc = plt.scatter(range(3), range(3), c=[1, 1, 1], cmap='viridis')
plt.colorbar(sc)
```

**Actual outcome**

![67638048-9a7cb800-f8d8-11e9-9584-c15ba7e78c20](https://user-images.githubusercontent.com/36797143/67753070-0ae81e00-fa2c-11e9-9757-6bb36f16f3c6.png)
![67638210-f3008500-f8d9-11e9-9164-da640b7180fc](https://user-images.githubusercontent.com/36797143/67753076-0d4a7800-fa2c-11e9-9e30-cb6a4e1b4296.png)

**Expected outcome**

I would expect colors to be the same in both plots above.

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: 3.1.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.3
  * Jupyter version (if applicable): 1.0.0
  * Other libraries:

**Comment by anntzer** [comment]
looks like a proper bug to me.

**Comment by jklymak** [comment]
Guess this is an issue w scatter. What happens with imagesc or pcolormesh?

**Comment by martinfleis** [comment]
@jklymak It is not. pcolormesh does exactly the same thing.

```py
sc = plt.pcolormesh([[2, 2], [2, 2]], cmap='viridis')
plt.colorbar(sc)
```

![Unknown-1](https://user-images.githubusercontent.com/36797143/67774369-1d2a8200-fa55-11e9-8bde-ec65b80052e9.png)

```py
sc = plt.pcolormesh([[2, 2], [2, 2]], cmap='viridis')
```
![Unknown](https://user-images.githubusercontent.com/36797143/67774370-1f8cdc00-fa55-11e9-8109-568b87aa507a.png)

**Comment by jorisvandenbossche** [comment]
Although it is inconsistent/surprising behaviour, it's a consequence of how the colorbar deals with constant values:

https://github.com/matplotlib/matplotlib/blob/fadc7fce0b8cfeb2600c1e988e9ca23aaaf9ed71/lib/matplotlib/colorbar.py#L979-L982

So here +/- 10% is added to the range, to have an actual colorbar to show. So given that this is also useful, not sure there is a clear fix / better option. You could only add 10% (and not subtract), so the actual value is not in the middle of the colorbar range but at the beginning. That would ensure the color does not change, but on the other hand also gives an odd look I think (although it's a corner case anyway ..)

**Comment by jklymak** [comment]
Ok so the question is whether we should do that non singular expansion regardless of the presence of a colorbar.

**Comment by jorisvandenbossche** [comment]
Ah, yes, that's also a way to get it consistent.

**Comment by jklymak** [comment]
Anything we do will not be backwards compatible so this needs discussion.  
 
1. leaves as is
2. apply non-singular expansion before a norm is used and either:
  a. keep centered as it is now
  b. offset so its just x and x*1.1.

**Comment by anntzer** [comment]
As always, it would be nice to reuse the nonsingular expansion of scales here.

**Comment by jklymak** [comment]
You mean a norm/scale refactor?

**Comment by anntzer** [comment]
Yes.

**Comment by tacaswell** [comment]
We let https://github.com/matplotlib/matplotlib/issues/5467 which is the same issue close due to inactivity recently.

Repeating the discussion a bit:

 - if you want a colorbar, the norm must be non-singular (or the transform to make the colorbar don't work as it must be finite size)
 - in every other case there is no reason that a norm has to be non-singular and we map all singular values to 0 (acd19a10b38e6af081dbe8b5ac5c3be8d75e1fa1 picked up a comment that maybe degenerate norms should give 0.5, but chasing this all the way back, the behavior of giving 0 goes back to e34a333d00814124d3e19d462b9d78ac35e7a49a which is the first reliable commit we have for most of the library from 2004)
 - the norm of the mappable and the colorbar is shared (so they stay in sync!)

Taken together this means if you create a colorbar with a singular norm then we have the options of:

   1. expand the norm as we do now
   2. raise


I do not think any of the 3 things above are really changeable and given the options of expanding or raising, I think expanding is the better choice. 
 

Even if we were to push the non-singular expansion down to the auto-scaling (like suggested https://github.com/matplotlib/matplotlib/issues/5467#issuecomment-156156799 ) I don't think it would actually solve this problem.  The exact case of the OP would be solved, but users could still manually set the limits to be singular and would have even more reason to report a bug ("I asked for a singular norm and the colorbar 'fixed' it!").

I am also going to close this as "can't-fix" as we are in a jam.  If in early 2000's the choice had been made to map singular norms to 0.5 we would not have this problem, but I do not think the up-side of fixing this issue is worth the cost of changing the singular behavior.

**Comment by anntzer** [comment]
I did not think much about this recently but is it clear that mapping singular norms to 0.5 (or perhaps even more generically, using the already existing scale expansion behavior for scale-derived norms) is really too disruptive a change? (Seems like something for which we can have a normal deprecation period.)

**Comment by timhoffm** [comment]
The associated PR https://github.com/matplotlib/matplotlib/pull/26307 has been re-milestoned. Applying the same here.
