### ISSUE TITLE
Legend changes position when saving figure with DPI value different from display when loc set to best

### ISSUE THREAD

**Issue by tboothr** [matplotlib/matplotlib#15585]
### Bug report

**Bug summary**

I think that this is an issue related to the bug #10458 which was already solved, in which the legend position in a saved figure (savefig) is not the same as in the display, when saving the figure with a different DPI value. 

The current issue is that if I specify the legend location with loc='best', and save the figure with a different DPI value to that of the display figure, the legend might change positions to any of the predefined ('upper left', 'upper right', etc), depending on the data that is being plotted.

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.1.1
  * Python version: 3.7.1
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by PrateekArya** [comment]
This bug is still present in matplotlib 3.2.1.

**Comment by tacaswell** [comment]
I'm not actually sure that this is a bug.  The goal of 'best' is to place the legend so that it overlaps with the data as little as possible.  It is plausible, particularly if you are using tight or constrained layout, that the "best" location changes as a function of the DPI.

 @PrateekArya  and @tboothr do either of you have a minimal example that exhibits this behavior?

**Comment by PrateekArya** [comment]
@tacaswell I also thought for a moment that this should be categorized as a bug but here is an example which does not make sense to me:

> Plot created with default loc (I guess its "best"):
![Original plot](https://user-images.githubusercontent.com/1255663/86480322-18d60780-bd4e-11ea-8944-d73657f62257.png)

> Same plot when I save it with following command:  plt.savefig(fileName, dpi=300)
![Plot on savefig with 300 DPI](https://user-images.githubusercontent.com/1255663/86480406-3c00b700-bd4e-11ea-85ce-0d3d435eb8ed.png)

I m not sure how matplotlib decides "best" location but I would assume that it would first check the 4 corners of plot area for "best" location (which should be as in the first plot). 
So may be the only thing needed here is that after changing the DPI, the function should recheck for "best" location. :)

Unfortunately, I do not have a minimal example to share with you.

**Comment by tacaswell** [comment]
I think the "problem" is that we _are_ re running it and coming to different conclusions based on the DPI.  Without a minimal example it is very hard to debug this.

Are those grid lines actually grids or many `axvline` and `axhline` s?

**Comment by PrateekArya** [comment]
Yes u have guessed it right those are not grid lines but several axvlines and axhlines. 😉 I cannot unfortunately share my data but I'll see if I can cook up another example for you. :) :D

**Comment by PrateekArya** [comment]
@tacaswell U r right its gonna be difficult to fix this problem as it seems to be difficult to recreate it in the first place. 😅
I tried with some dummy data which was arranged in a similar fashion as my original data but it didn't show this problem. But I noticed the following when I maximize the plot window to full screen:

Original data:
![image](https://user-images.githubusercontent.com/1255663/86530288-d16b8a80-beb7-11ea-99c5-6df4d9016afe.png)

Dummy data:
![image](https://user-images.githubusercontent.com/1255663/86530320-1bed0700-beb8-11ea-8524-787c35d3df87.png)

I am not sure if this gonna be helpful but this bug is not that important to resolve at this point anyways. 😉

**Comment by tacaswell** [comment]
> Yes u have guessed it right those are not grid lines but several axvlines and axhlines

I suspect that this is the key to thins bug.  There no "good" location for the legend because it always collides with the faked grid lines.  Because we don't let the legend go _anywhere_, only at the pre-defined locations I suspect that there is an instability when the legend hits a different number of the vertical lines (in the original image it looks like there is a grid line _just_ at the edge).  My bet is if you resize the window you'll see the same jumping around behavior.

**Comment by PrateekArya** [comment]
@tacaswell Yes u r very right!! The legend box jumps erratically between format 1 and 2 when I resize it by dragging the corner. Moreover, It works normally if I remove the fake grid lines! So its a problem with fake gridlines then. 😅 

Format 1:
>   ![Original plot](https://user-images.githubusercontent.com/1255663/86480322-18d60780-bd4e-11ea-8944-d73657f62257.png)

Format 2:
>   ![Plot on savefig with 300 DPI](https://user-images.githubusercontent.com/1255663/86480406-3c00b700-bd4e-11ea-85ce-0d3d435eb8ed.png)

**Comment by jklymak** [comment]
Right.  "best" is DPI dependent, in general.  I don't think there is really an action item here, so I'm going to close. If users need the legend to stay in one spot, then they can set the location manually.
