### ISSUE TITLE
[SPRINT] Update Named Colors Example

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#15609]
The named colors example is missing a couple of the matplotlib color tables. It should be updated with XKCD and the others.

https://matplotlib.org/gallery/color/named_colors.html#sphx-glr-gallery-color-named-colors-py

**Comment by ImportanceOfBeingErnest** [comment]
I put a comment there which says

> `# Optionally plot the XKCD colors (Caution: will produce large figure)`

So in that example, you can uncomment those lines and get all XKCD colors, but the figure will be utterly large, so I think it's not a good idea to have them uncommented by default. 

What are "the others"?

**Comment by overenthused** [comment]
When that line in uncommented, several of the xkcd color names run over onto the colors of the next column. The column width would need to be increased, which might require having three columns instead of four columns. Should this only happen when XKCD lines are uncommented? Or should there be three columns be default?

**Comment by ImportanceOfBeingErnest** [comment]
Would reducing fontsize help? Or maybe mentionning the `xkcd:` prefix in the title and removing it from each colorname?

**Comment by overenthused** [comment]
Since the intent of this page is the help users identify strings that map to colornames, the `'xkcd:'` prefix seems necessary, especially since they conflict with several of the CSS colors. Decreasing the font size to 12 does fix the issue. If that's a large enough font, that might be the best solution.

**Comment by overenthused** [comment]
Also, this is my first sprint. How do I edit a gallery page? Do I need to fork the repo? Where do the gallery pages live?

**Comment by ImportanceOfBeingErnest** [comment]
Yes, you can fork the repo and then create a pull request. Details should be in https://matplotlib.org/devel/contributing.html#contributing-code and https://matplotlib.org/devel/documenting_mpl.html#getting-started

In this specific case, the file is in https://github.com/matplotlib/matplotlib/blob/master/examples/color/named_colors.py

**Comment by overenthused** [comment]
Thank you! Is there any reason why you have an option to save the xkcd colors as a png? None of the other colors have that option.

**Comment by ImportanceOfBeingErnest** [comment]
Of course you can save the others as png as well if you want. The reason why this is made explicit for the xkcd colors in that code is that the figure will be too large to be displayed on usual screens via `plt.show()`, so one would need to save it as image.

**Comment by story645** [comment]
Closed by #18672
