### ISSUE TITLE
named color examples need borders

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#15614]
Jumping off of #15609, the [Named Color Example](https://matplotlib.org/gallery/color/named_colors.html#sphx-glr-gallery-color-named-colors-py) is using hlines to do the color patches and some of the lighter colors are hard to distinguish from the background.  If these lines were changed to patches, then they could be edged in light gray.

**Comment by timhoffm** [comment]
I think a border would significantly reduce the color impression. Recognizing the difference between a light color and white is harder if there is a separating line in between. The positions of the color blocks is quite clear from the layout, so a border is also not needed to indicate the position.

Some of the light colors are inherently hard to distinguish from white. We cannot do much about that.

**Comment by anntzer** [comment]
I agree no borders is likely better.

**Comment by joybhallaa** [comment]
Can I work on this ?

**Comment by timhoffm** [comment]
From the thumbs, I think we'd rather not introduce borders.

**Comment by timhoffm** [comment]
@story645 closing based on the thumbs vote. Feel free to reopen if you think we should revisit this.

@joybhallaa sorry for the red herring, for now this is not actionable.

**Comment by story645** [comment]
Backgrounds always mess with perception, including the choice of a white background. For example this optical illusion where the gray swatch is all the same color:
![optical illustion where gray swatch looks different depending on background](https://www.moillusions.com/wp-content/uploads/2015/06/Is-this-gray-bar-the-same-color.png)
 I think the benefit of a slight very light (like two points darker than white or than the color swatch itself) edges benefit on readability/distinguishing colors outweighs color skewing effects that are already inherently in place because of having a background.

**Comment by ImportanceOfBeingErnest** [comment]
In case there is another opinion needed here, I did actually think about adding a border when updating this example in #12209 and I decided against. The reason is precisely that color perception is dependent on the color of border and background; however, since matplotlib by default has a white background, showing those colors directly on top of the white background should give the perceptually closest result to how they would look when used in a default figure.

Arguably you sometimes have a different background or other requirements, so adding a commented-out line (or an argument to the function) in the example allowing anyone running it to easily change the background color would make sense to me.

Or, if adding more complexity is not an issue, one could make it such that right clicking any color swatch would change the background of the figure to that clicked color.

**Comment by timhoffm** [comment]
The gradient background example is a bit on the extreme end :wink:. In the end, every context will influence the perception of the color, whether it's background color, pattern, border, shape or size. We only need to decide which influence we want; and here I follow @ImportanceOfBeingErnest with the argument that we usually draw on white.

Nevertheless, I gave it a chance and copied the code to see how borders would look like. But turns out, adding borders is not trivial, because the color swatches are thick lines, not rectangles. One would have to rewrite the whole example to add borders. At least for me, that's too much effort given that I think it's not looking better.

I wouldn't bother with any interactivity in the example. Not because of code complexity, but because I assume that most people will only look at the rendered html version anyway. Also we shouldn't overdo it. This is "just" (sorry for the word, I know you've scolded me for that before) a reference card of the color names with some basic visualization.

All that said, I'm just one voice. As usual if there's a majority for adding a border, I won't stop that.

**Comment by story645** [comment]
>One would have to rewrite the whole example to add borders. 
I think the example should be patches rather than hspan anyway since they are patches. I'm not terribly concerned about the amount of effort given this is an issue aimed at new contributors and I don't think learning the patch API to do it is a huge ask. 

>"just" (sorry for the word, I know you've scolded me for that before) 
Eh, I don't think that word belongs in docs (usually), but like it's fine to use it in language. And sorry that I came off scoldy.

**Comment by timhoffm** [comment]
> I think the example should be patches rather than hspan anyway since they are patches.

Agreed. Rewriting to using Rectangles would be good anyway. @joybhallaa would you be interested in picking that up?

We can later compare if Rectangles look better with or without border.

> And sorry that I came off scoldy.

No, no, you were not. I just :roll_eyes: get more conscious about my language. :smile:

**Comment by asongtoruin** [comment]
Hiya - there didn't seem to be any further developments on this, so I thought I'd pick it up. The commit referenced above applies the basic change to convert to use `Rectangle`, assuming the same widths as before. As @timhoffm suggested, this makes it much easier to test the black borders - assuming `edgecolor='k', linewidth=1` we get:

![Base Colors](https://user-images.githubusercontent.com/20771863/73697025-80235900-46d5-11ea-9496-684df441cf18.png)
![CSS Colors](https://user-images.githubusercontent.com/20771863/73697026-80bbef80-46d5-11ea-9278-ac4596e36b3b.png)
![Tableau Palette](https://user-images.githubusercontent.com/20771863/73697028-80bbef80-46d5-11ea-86c5-b4c8ae44f5b3.png)

I'd be happy to submit a PR as it stands (without the border) if that's suitable, or add further tweaks if needs be.

Thanks!

**Comment by story645** [comment]
Awesome @asongtoruin! A PR would be much appreciated, and if it's not too much work would you mind also trying a very light gray background?

**Comment by asongtoruin** [comment]
@story645 as in, a grey background to the whole page? With/without the black borders?

**Comment by story645** [comment]
Sorry, meant light gray borders!

**Comment by timhoffm** [comment]
Looking at the above light borders might not be too bad after all :smile:. I'm looking forward to see a picture of there.

**Comment by asongtoruin** [comment]
Splitting the difference - with `edgecolor='0.5'`:

![Base Colors](https://user-images.githubusercontent.com/20771863/73798236-23de3900-47aa-11ea-905e-7bf805941ea5.png)
![CSS Colors](https://user-images.githubusercontent.com/20771863/73798239-250f6600-47aa-11ea-815d-cddb2ae361f7.png)
![Tableau Palette](https://user-images.githubusercontent.com/20771863/73798241-25a7fc80-47aa-11ea-8c97-ffaa2416d7e3.png)

**Comment by asongtoruin** [comment]
@timhoffm are you in support of the light grey borders then? I'll put in a PR if so

**Comment by ImportanceOfBeingErnest** [comment]
My vote would be to stick to a borderless visual per my [comment](https://github.com/matplotlib/matplotlib/issues/15614#issuecomment-567972677) above.

**Comment by jklymak** [comment]
Agree w @ImportanceOfBeingErnest   colours should be shown in the context they are most likely to be used and for us that is against a white background.

**Comment by story645** [comment]
but I then I think it should be with a black border since axis are black 90% of the time and they provide a visual border.

**Comment by jklymak** [comment]
I think coloured lines are typically drawn on a white canvas.

**Comment by story645** [comment]
I think the pale colors are more often used as backgrounds or fills, or at least that's how I use 'em.  But I also think that the impact of the border on the perception of the color is a lot smaller than the clarity gained by having it.

**Comment by timhoffm** [comment]
Perception depends a lot on background and on the size of the colored area. If we care about that, we'd need at least:

- blocks without border on white background (as we have currently) - repesenting filled Artists, which by default have no border.
- thin lines on white background - representing Line2D.

But I wouldn't care to go down that road. This is just" an illustration for the color names, so I'd keep it simple with one representation of the colors.


Coming back to the basics, we would like to have this rewritten using patches instead of hspan.  (https://github.com/matplotlib/matplotlib/issues/15614#issuecomment-568002387). This can ce done indepentently on whether we add a border later or not.

**Comment by WeatherGod** [comment]
fwiw, I personally like the outline. I have difficulty seeing contrasts,
and so having the outline as a point of reference helps me. But, you are
right, it is just meant to be an illustration.

**Comment by asongtoruin** [comment]
@timhoffm PR above for the basic rewrite.

Personally, I find the colours easier to perceive with the border, but I can see the idea behind keeping the comparison directly against white.

**Comment by anntzer** [comment]
fwiw I personally like the thin outlines; it is true that our colors are typically used without outlines but they're also most often points or lines, nor rectangles, so heh.
