### ISSUE TITLE
Depthshade not working when using multiple scatter plots

### ISSUE THREAD

**Issue by giacomomarchioro** [matplotlib/matplotlib#15657]
### Bug report

**Bug summary**

When I am using many scatter plot in a single 3D plot, the depth shade is not working.

**Code for reproduction**

```python
from mpl_toolkits.mplot3d import Axes3D  t
import matplotlib.pyplot as plt
import numpy as np
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
xs = np.random.randn(100)
for i in range(100):
    ax.scatter(xs[i], ys[i], zs[i])
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/7785549/68547526-c91f8600-03e2-11ea-892a-484b27d0cced.png)

**Expected outcome**
The point should have alpha levels in relation to the depth.
**Matplotlib version**

  * Operating system: GoogleCloud
  * Matplotlib version:  3.3.1
  * Matplotlib backend:module://ipykernel.pylab.backend_inline
  * Python version: 3.6
  * Jupyter version (if applicable):
  * Other libraries: 

You can test it in this colab:
https://colab.research.google.com/drive/1XQv3aK44-_lebbgfWDYv-0genBe4QKR1

**Comment by timhoffm** [comment]
Depthshading does only work within the dataset provided to `scatter()`. You passed 1-sized datasets, therefore they do not get any shading. Additionally, `scatter()` uses the color cycle for the base color, so that each of your points gets a new color.

If you do two calls on the half dataset depthshading works:

~~~
# This import registers the 3D projection, but is otherwise unused.
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 unused import
import matplotlib
import matplotlib.pyplot as plt
import numpy as np
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(xs[:50], ys[:50], zs[:50])
ax.scatter(xs[50:], ys[50:], zs[50:])
plt.show()
~~~

![grafik](https://user-images.githubusercontent.com/2836374/68548236-d476af80-03ea-11ea-8916-37442bf6f5d4.png)

**Comment by giacomomarchioro** [comment]
Thanks, unfortunately, I've to pass one data set at a time because I've to change colour and marker depending on the class, and I can't pass list of markers.

At the moment I've solved the problem creating a custom depthshade that I use also for a kind of perspective effect on the size, this is the pseudo code:
```
# alpha depending only on x-y coordinates not z
cxalpha = 0.4*((coord[0]-xmin)/x_range)
cyalpha = 0.4 - 0.4*((coord[1]-ymin)/y_range)
alpha = cxalpha+cyalpha+0.2 # minimum alpha 0.2
marker,color= labels_dict[label]
for i in range(samples):           
 axc.scatter(coord[0],coord[1],coord[2],marker=marker,color=color,depthshade=True,s=200*alpha,alpha=alpha)
```
