### ISSUE TITLE
Publish 3.8 wheels

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#15714]
Currently there are no python 3.8 builds available.

**Comment by cgohlke** [comment]
Try `pip install matplotlib==3.2.0rc1`

**Comment by MaxNoe** [comment]
Are there no plans to publisch 3.1 wheels? Also I'm more concerned with linux than Windows :wink:

**Comment by matthew-brett** [comment]
Is there a reason not to build Python 3.8 wheels for the current release, rather than waiting until the next release?

**Comment by tacaswell** [comment]
Where we are currenty stuck on 3.1.1 wheels is that due to changes in CPython we now have some spurious warnings (see https://travis-ci.org/MacPython/matplotlib-wheels/jobs/602597261 ) which makes the test fail on the CI we use to build the mac/linux wheels.

@MaxNoe could you push on adding a patch to https://github.com/MacPython/matplotlib-wheels/tree/build-3.1.x to not fail the tests on producing warnings?

**Comment by MaxNoe** [comment]
I'm not really sure what you mean. The log you provided seems to indicate the build is missing `tornado` as a dependency of the `webagg` backend.

**Comment by timhoffm** [comment]
Can this be closed since 3.1.2 is out?=

**Comment by anntzer** [comment]
I think so.
