### ISSUE TITLE
PDF problem with fill_between and a lot of zoom

### ISSUE THREAD

**Issue by ezalorpro** [matplotlib/matplotlib#15817]
When i use fill_between and a lot of zoom the saved pdf do not show correctly, it looks different depending of the pdf viewer, if the plot is saved as png there is not problem

**Code for reproduction**

```python
from matplotlib import pyplot as plt
import numpy as np

x = np.linspace(0, 4*np.pi, 1000)
y = np.sin(x)
z = y + 1e-14

plt.plot(x, y)
plt.plot(x, z)
plt.fill_between(x,y,z)
plt.show()
```

**Actual outcome**
in the next image i show:

1) the plot
2) the plot after zooming a lot
3) the plot as png looking correctly
4) the plot as pdf looking wrong

![testWrong](https://user-images.githubusercontent.com/37134637/70017443-7ce6e200-1559-11ea-86f1-df8cca9f153b.png)

And the reason why I need to zoom in so much is to make a graphic comparison between two signals as seen in the following image, in the first one the plot is shown correctly, while the other shows that it simply does not save well as pdf

![sample](https://user-images.githubusercontent.com/37134637/70017742-478ec400-155a-11ea-8dc2-10be742ed0ff.png)

**Matplotlib version**
  * Operating system: Windows 10
  * Matplotlib version: 3.1.2
  * Matplotlib backend: TkAgg
  * Python version: 3.7.3
  * Matplotlib installed with pip

**Comment by QuLogic** [comment]
How are you making the inset Axes?

**Comment by ezalorpro** [comment]
@QuLogic for the inset Axes:

```python
axins = ax.inset_axes([0.54, 0.2, 0.41, 0.37])
axins.plot(T2, Y2, color="#001C7F", label='MATLAB', linewidth=2)
axins.plot([T2[indice]]*2, [Y1[indice], Y2[indice]], color='k', linewidth=3, label='Diferencia maxima')
axins.plot(T2, Y1, 'r', dashes=[1, 2], label='Laboratorio Virtual', linewidth=3)
axins.fill_between(T2, Y1, Y2, alpha=0.4, color="#001C7F", label='Area de diferencia')
x1, x2 = T2[indice] - np.abs(Y1[indice] - Y2[indice])*20, T2[indice] + np.abs(Y1[indice] - Y2[indice])*20

if Y2[indice] >= Y1[indice]:
    y1, y2 = Y1[indice] - np.abs(Y1[indice] - Y2[indice]), Y2[indice] + np.abs(Y1[indice] - Y2[indice])
else:
    y1, y2 = Y2[indice] - np.abs(Y1[indice] - Y2[indice]), Y1[indice] + np.abs(Y1[indice] - Y2[indice])

axins.set_xlim(x1, x2)
axins.set_ylim(y1, y2)
ax.indicate_inset_zoom(axins)
axins.grid()
```

But I don't think it's an inset axes problem, since the MWE above doesn't have any, besides, if I delete the fill_between, the graph is saved well in PDF.

Note: if I save the graph in .svg, everything looks correctly, but the fill area disappears, an example of both cases:

![svgexample](https://user-images.githubusercontent.com/37134637/70021118-ebca3800-1565-11ea-8885-c167511c74e1.png)

**Comment by QuLogic** [comment]
Well, this would be easier to reproduce with an explicit zoom, just "zoom a lot" until it breaks is not necessarily possible.

**Comment by ezalorpro** [comment]
@QuLogic The following code contains a limit for x and y that produce the zoom level required to reproduce the prolema, but, I am not sure what the amount of zoom that causes it will not work, but for my particular case I need to be able to see things at 1e-14

```python
from matplotlib import pyplot as plt
import matplotlib
import numpy as np

x = np.linspace(0, 2*np.pi, 10000)
y = np.sin(x)
z = y + 1e-14

plt.plot(x, y)
plt.plot(x, z)
plt.fill_between(x,y,z)
plt.axis([1.5709534220463992, 1.5709534222199248, 0.999999987660502, 0.9999999876605615])
plt.show()
```
Cheers

**Comment by anntzer** [comment]
1e-14 is close to the limit of floating point resolution so I'm almost certain this is just running into inaccuracies in the pdf rendering engine and can't be fixed on our side.

**Comment by ImportanceOfBeingErnest** [comment]
It looks like the underlying problem concerning matplotlib is that it's not easily possible to use a custom formatter with offset/multiplicator (and mathtext). Else it would be possible to just plot in some other unit system (e.g. nanometers instead of lightyears) and plug the offset into the formatter.

**Comment by tacaswell** [comment]
I can still reproduce this.

```python
from matplotlib import pyplot as plt
import numpy as np

x = np.linspace(0, 4*np.pi, 1000)
y = np.sin(x)
z = y + 1e-14
fig, ax = plt.subplots()
ax.plot(x, y)
ax.plot(x, z)
ax.fill_between(x,y,z)
ax.set_xlim((7.849264527884863, 7.84926452789317))
ax.set_ylim((0.9999888744756801, 0.99998887447573))
plt.show()

```

What is going on here is that when we draw the path for the line (and the fill between) the points are like 10-12 orders of magnitude farther apart than the view limits.  Apparently Agg can cope with this but after being run through one of the vector formats the loss in precision is enough that the points look "flat" or "the same" and we get weird rendering in the vector backends.

This is obviously a synthetic case, but sampling more with in the view limit (e.g. `x = np.linspace(7.849264527884863, 7.84926452789317, 1000)`) produces a pdf that matches the output of Agg (and notably it looks different because at this zoom level linearly connecting the points is introducing significant error from the actual value of `sin`)

We do have some ability to re-sample paths just before we draw them (we use this in polar axes) so it may be possible to fix this, but this seems like a very extreme edge case (looking at a single point with the adjacent points being far enough away that numerical error matters and we get a version of `big + small == big` issue).

I am comfortable leaving this closed, but if someone has a compelling use case or wants to dig into this would be happy to re-open.
