### ISSUE TITLE
Axis label alignment defaults

### ISSUE THREAD

**Issue by andrzejnovak** [matplotlib/matplotlib#15839]
**Feature Request**

Would there be opposition to adding `x, y, ha, va` as `rcparams`? I would like aligning labels to the end of axes to be a style option.
Or really a shortcut for `set_label()`, i.e. align `"left"` : `<x/y>=0, ha='left'` and `"left" : <x/y>=1, ha='right'` and align could be a new rcparam?

**Comment by jklymak** [comment]
Can you clarify your proposed API?  I'm not even clear what method you want these to apply to...

**Comment by andrzejnovak** [comment]
Sure, `set_xlabel()` currently takes `ha='right', x=1` which effectively aligns label to the right. I would like this to be an optional default i.e. rcparam, though that could quickly get bloated ha/x/y for xaxis/yaxis. So alternatively `set_xlabel()` could take a new kwarg `align={"right"|"center"|"left"}` which would be a shortcut for setting the right 'ha/x/y` and then `align` could be a singular new rcparam.

**Comment by timhoffm** [comment]
The idea is to align the axis label left/center/right with respect to the axis.

`(horizontal/vertical)align` unfortunately has a fixed notion to align the text relative to a reference point. Therefore adding a parameter `align` may be a source of confusion.

The desired effect is a bit analogous to the parameter `loc` in [Axes.set_title](https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.set_title.html). However, the difference is, that there are actually 3 titles which may be used simultaneously, and `loc` selects which title to use. OTOH `legend()` actually uses `loc` to move the legend, so `set_xlabel('the label', loc='left')` may actually be the way to go even if we just have one `Text` object for the label.

**Comment by andrzejnovak** [comment]
I don't have an issue with loc instead of align such that `set_xlabel('the label', loc='left')` where 'left' means `set_xlabel('the label', ha='right', x=1)` and similarly with 'right'. I'm happy to take a crack at a PR if we can get a consensus on the API.

**Comment by jklymak** [comment]
If x=1 is already the way to do this maybe we capture x and allow special string values for it. Ie x=“left”. It would also allow us to document that you can just pass x to set_xlabel, whivc I hadn’t realized before now.

**Comment by andrzejnovak** [comment]
@jklymak Unfortunately for `set_ylabel()` it's y not x. The goal here is to have a setup that will allow for an rcParam like axis.label.loc = 'right' that will align all x-label, y-label, cbar-label to the right.

**Comment by timhoffm** [comment]
Technically `x`/`y` is documented via the Text properties in kwargs (https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.set_xlabel.html).

I'm in favor of a new `loc='left'` instead of `x='left'`. On the downside, we have another parameter that interacts with `x` and `horizontalalignment`. But also `x='left'` would still interact with `horizontalalignment`. We cannot get around that completely. Then IMHO it is clearer to introduce a separate `loc` parameter as a high-level interface that manipulates the low-level interface (`x`/`horizontalalignment`).

There's also some layouting happening in the non-axis direction, which overrides any `y` parameter given to `xlabel`:
~~~
l = plt.xlabel('test')
print(l)  # Text(0.5, 0, 'test')
plt.draw()
print(l)  # Text(0.5, 15.0, 'test')
~~~
If we pull `x` to top level in `xlabel`, people will get aware of `y`, but that does not work for setting the vertical position, which we would have to doc as well. Also for that reason, I don't think we should use or advertise `x`.

**Comment by andrzejnovak** [comment]
Could also babyproof it, i.e throw error if both `x/ha` and `loc` get used

**Comment by anntzer** [comment]
I think @timhoffm's point is a good one in favor of `loc="left"` and against `x="left"`.

**Comment by QuLogic** [comment]
This was added in #15974.
