### ISSUE TITLE
DOC: Error in colormap manipulation tutorial

### ISSUE THREAD

**Issue by 1313e** [matplotlib/matplotlib#15884]
So, I was reading the online documentation of MPL on colormaps, and noticed that there is an error in it.
In the section of ["Creating listed colormaps"](https://matplotlib.org/3.1.1/tutorials/colors/colormap-manipulation.html#creating-listed-colormaps), it mentions that the dynamic range of a colormap can be reduced by using:
```python
viridisBig = cm.get_cmap('viridis', 512)
newcmp = ListedColormap(viridisBig(np.linspace(0.25, 0.75, 256)))
plot_examples([viridis, newcmp])
```
It also specifically mentions that this must be done in order to make sure that the new colormap does not have repeated values.

However, as `viridis` is a `ListedColormap` and `ListedColormap` objects do not allow for interpolation between values, both `viridisBig` and `newcmp` will have repeated values, despite the documentation specifically mentioning they do not.

This could be fixed by either changing the tutorial into:
```python
viridisRGB = viridis(np.linspace(0, 1, viridis.N))
viridisBig = LinearSegmentedColormap.from_list('viridisBig', viridisRGB, 512)
newcmp = ListedColormap(viridisBig(np.linspace(0.25, 0.75, 256)))
plot_examples([viridis, newcmp])
```
as `LinearSegmentedColormap` objects do allow for interpolation when creating them, or obviously by making `ListedColormap` objects be able to perform interpolation.

I have however noticed that the interpolation messes up sometimes, especially at the ends of the colormap.
It might therefore be better to simply take the required part of the colormap when reducing the dynamic range, with something like:
```python
newcmp = ListedColormap(viridis(np.linspace(0.25, 0.75, viridis.N*(0.75-0.25))))
plot_examples([viridis, newcmp])
```
This obviously also reduces the resolution of the colormap, so it is not a good solution, but works well enough on colormaps with 256 segments and a not too big reduction in dynamic range.

**Comment by ImportanceOfBeingErnest** [comment]
I think it might be a good idea to first show the simple upsampling where resolution is lost; then state the problem of lost dynamic range; then show how to interpolate linearly. This is because for many applications the 128 colors might be enough and we may not want to confuse beginners too much.

I do not see how the third solution is different from the first on first sight. Just less codelines, or is there more to it?

In general, one could introduce a `linear_upsample` method, which would fall back to `_resample` in case of a segmented map, and interpolate linearly in case of listed map; though one has do be aware that linear interpolation is not really happening in the perceptual colorspace.

**Comment by 1313e** [comment]
@ImportanceOfBeingErnest I assume you mean the third code snippet I posted with 'the third solution', and compare it to the code snippet currently found in the MPL docs?
If so, they are different as the MPL example will take 128 segments and duplicate all of them to create 256 of them, while mine simply keeps the 128 segments.
This will give a slight difference when plotting both colormaps, as the center value associated with a specific segment is slightly shifted (either in between the duplicated values or the value itself).
