### ISSUE TITLE
matplotlib DLL load failed - after conda update of jupyter

### ISSUE THREAD

**Issue by dwervin** [matplotlib/matplotlib#15893]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-8-ffe729860a8a> in <module>
      2 #%matplotlib inline
      3 
----> 4 import matplotlib.pyplot as plt
      5 import numpy as np
      6 import pandas as pd

C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\matplotlib\__init__.py in <module>
    203 
    204 
--> 205 _check_versions()
    206 
    207 

C:\ProgramData\Anaconda3\envs\py37\lib\site-packages\matplotlib\__init__.py in _check_versions()
    188     # Quickfix to ensure Microsoft Visual C++ redistributable
    189     # DLLs are loaded before importing kiwisolver
--> 190     from . import ft2font
    191 
    192     for modname, minver in [

ImportError: DLL load failed: The specified module could not be found.

**Comment by tacaswell** [comment]
Looks similar to https://github.com/matplotlib/jupyter-matplotlib/issues/155

I suspect that this is a local installation issue, please move this discussion to https://discourse.matplotlib.org/t/issues-with-my-installation-of-matplotlib/20746/2

**Comment by kylefoley76** [comment]
I had this problem as well.  I did the following to fix it
pip uninstall matplotlib
pip install matplotlib
I then got the error 'kiwisolver' module not found.   I then did
pip install kiwisolver
That did not work since it said that that requirement was already satisfied.  I manually deleted any files beginning with kiwisolver from my library, then ran
pip install kiwisolver
That fixed it.
