### ISSUE TITLE
Constrained_layout creates extra axes when used with subgridspec

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#16173]
### Bug report

**Bug summary**

Constrained_layout creates extra axes when used with subgridspec. This is specific to using a subgridspec and axes added to positions from the gridspec, *as well as* the subgridspec.

The extra axes shadows the underlying axes, such that e.g. mouse-events are ignored. Is is the underlying issue of this question: https://stackoverflow.com/questions/59663421/matplotlib-button-not-working-when-in-nested-gridspec

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig = plt.figure(constrained_layout=True)

gs = fig.add_gridspec(2, 1)

ax1 = fig.add_subplot(gs[0, 0])

gs2 = gs[1, 0].subgridspec(1, 2)
ax2 = fig.add_subplot(gs2[0, 0])
ax3 = fig.add_subplot(gs2[0, 1])

print(len(fig.axes))  # prints 3 (as expected)   
fig.canvas.draw()
print(len(fig.axes))  # prints 4

for ax, color in zip(fig.axes, plt.cm.tab10.colors):
    pos = ax.get_position()
    rect = plt.Rectangle((pos.x0, pos.y0), width=pos.width, height=pos.height,
                         color=color, alpha=0.4, transform=fig.transFigure)
    fig.add_artist(rect)

plt.show()
```

**Actual outcome**

![c1](https://user-images.githubusercontent.com/23121882/72084195-59a31580-3303-11ea-81cb-9c9690ffb33c.png)

There are four axes in the figure, the one in red is undesired.

**Expected outcome**

Three axes.

**Note**

If `ax1 = fig.add_subplot(gs[0, 0])` is replaced by 

```
gs1 = gs[0, 0].subgridspec(1, 1)
ax1 = fig.add_subplot(gs1[0, 0])
```
no extra axes is present. Also, without constrained_layout, the issue is not present. 

**Matplotlib version**

  * Operating system: Windows 8.1
  * Matplotlib version: 3.1.0, also master branch from before Christmas
  * Matplotlib backend (`print(matplotlib.get_backend())`): PyQt5
  * Python version: 3.7

**Comment by jklymak** [comment]
OK, if a subplotspec is empty `constrained_layout` fills it with a dummy axes that is not visible.  Thats a bit of a hack, but we need something to constrain the upper plot with, otherwise it would fill the whole figure, which the user does not want. So the behaviour is "expected", if a bit of a hack (See https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html#empty-gridspec-slots)

The undesirable side effect is that mouse events are not being passed down to the axes below the ghost axes.  

I can see a few solutions:

1. Somehow get rid of the hack in constrained_layout.  But of course I don't think thats trivial or I wouldn't have put the hack there in the first place.
2. Find a mechanism to turn off the mouse event capture for the ghost axes.  Is there an easy one?  
3. Generally always pass mouse events down as far as possible.  I'm not actually following why the event doesn't get to the axes below.  

Any suggestions welcome.

**Comment by anntzer** [comment]
cbook._topmost_artist could be modified to first filter-out non_visible() artists?
IIRC propagation of events to artists "under" others has been discussed elsewhere a while ago.

**Comment by jklymak** [comment]
Or Artists could get a flag that says they don't want to be picked?  That would be more flexible?

**Comment by anntzer** [comment]
That's called set_picker(False), but that's not checked on the parent axes, just on the artist itself.

**Comment by jklymak** [comment]
OK, but it could be checked in _topmost_artist?  i.e. you could readily imagine someone having buttons in an axes that is not visible (the buttons will still show up, right?)

**Comment by anntzer** [comment]
I think if the axes is not visible draw() doesn't even recurse down into the children (you probably meant if the spines are not visible and there are no ticks...).

**Comment by jklymak** [comment]
Right,  if its not visible, nothing on the axes will draw.  So can we safely assume nothing should be pickable if its not drawn?

**Comment by anntzer** [comment]
I guess so?
