### ISSUE TITLE
Is `repeat_delay` property valid in `matplotlib.animation.Animation.save`?

### ISSUE THREAD

**Issue by Cartman0** [matplotlib/matplotlib#16216]
### Bug report
`repeat_delay` property is invalid in ArtistAnimation.

**Bug summary**

trying writer:
- "pillow"
- "imagemagick"

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import scipy as sp
import matplotlib.animation as animation

ims = []
fig = plt.figure()
for i in sp.arange(10):
    fr_i = plt.text(0, 0, "i={:}".format(i), color="k", fontsize=16,  ha='left')
    ims.append([fr_i])

ani = animation.ArtistAnimation(fig, ims, interval=200, repeat=True, repeat_delay=5000)
ani.save("test.gif", writer="imagemagick")
```

**Actual outcome**

![test](https://user-images.githubusercontent.com/10578703/72327216-001c5b80-36f4-11ea-977c-848d7e435f9f.gif)

**Expected outcome**

after waiting 5s, should repeat.

**Matplotlib version**

  * Operating system: Windows10 64bit
  * Matplotlib version: 3.1.2 
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.4
  * Jupyter version (if applicable): jupyter1.0.0, notebook6.0.2
  * Other libraries: 
    - imagemagick: 7.0.8Q16
    - Pillow: 7.0.0

**Comment by anntzer** [comment]
repeat_delay currently only works for the animation displayed on interactively.  It may be useful to make it work on the saved gif as well.

**Comment by Cartman0** [comment]
@anntzer 
if not using `animation.save`, are there any way to display , magick code?

**Comment by anntzer** [comment]
Replace `ani.save()` by `plt.show()`.

**Comment by Cartman0** [comment]
@anntzer thx. then adding `%matplotlib notebook`, could preview animation.

**Comment by Cartman0** [comment]
In `animation.save`, `repeat_delay` is invalid but `interval` is valid ?

**Comment by Cartman0** [comment]
I tried `interval=150, 300`.

interval=150:
![test150](https://user-images.githubusercontent.com/10578703/72423610-ea786600-37c7-11ea-8009-f4be72d97b20.gif)

interval=300:
![test300](https://user-images.githubusercontent.com/10578703/72423618-ee0bed00-37c7-11ea-97a1-b04e1d5991b4.gif)

**Comment by drnancy** [comment]
Instead of using animation.ArtistAnimation use animation.FuncAnimation function

 
import matplotlib.pyplot as plt 
import matplotlib.animation as animation 
import scipy as sp

#second to hold the repeating operation after each cycle
INTERVAL = 200 #millisecond interval between the index number
HOLD_MS = 5000 #millisecond interval between each cycle
HOLD_COUNT = HOLD_MS // INTERVAL

#Create generator when to stop at particular frame 
def frame_generator():
    for frame in sp.arange(11):

        # Yield the frame first
        yield frame

        # If we should "sleep" here, yield None HOLD_COUNT times
        if frame == 10:
            for _ in range(HOLD_COUNT):
                yield frame

#create figure and axis
fig, ax = plt.subplots()
ims=[]

#text to plot in graph
fr_i = ax.text(0, 0, "i={:}".format(0), color="k", fontsize=16,  ha='left')

#update function as parameter to FuncAnimation method
def update(i):
    fr_i.set_text("i={:}".format(str(i)))

#Animation   
ani = animation.FuncAnimation(fig, update, frames=frame_generator(), interval=200)
#save as gif
ani.save("testE.gif", writer="imagemagick")
 

Output:


![Output](https://user-images.githubusercontent.com/58162442/72605104-26373b00-3942-11ea-83ff-b35b189cd546.gif)
