### ISSUE TITLE
errorbar 'c' parameter ValueError

### ISSUE THREAD

**Issue by RobertArbon** [matplotlib/matplotlib#16317]
### Bug report

**Bug summary**

trying to colour individual data points using the parameter `c` results in a value error when using `errorbar`.  Equivalent code when using `scatter` works fine. 

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

n = 10
x = np.random.random(n)
y = np.random.random(n)
c = np.random.random((n, 4))
# This works
plt.scatter(x, y, c=c)
# This doesn't work
plt.errorbar(x, y, c=c)
```

```
...
./Research/optimize_fs_peptide/opt_fs_pep/lib/python3.7/site-packages/matplotlib/colors.py in _to_rgba_no_colorcycle(c, alpha)
    238         # float)` and `np.array(...).astype(float)` all convert "0.5" to 0.5.
    239         # Test dimensionality to reject single floats.
--> 240         raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
    241     # Return a tuple to prevent the cached value from being modified.
    242     c = tuple(c.astype(float))

ValueError: Invalid RGBA argument: array([[0.85981682, 0.76878602, 0.90930044, 0.22403945],
       [0.73117369, 0.82011925, 0.17867098, 0.49324954],
       [0.53221114, 0.95889687, 0.39141199, 0.99857525],
       [0.74226572, 0.85605136, 0.11591957, 0.96316758],
       [0.57368284, 0.58597761, 0.19907932, 0.34996845],
       [0.70578752, 0.18786991, 0.01388688, 0.1197096 ],
       [0.13273994, 0.31122034, 0.12788089, 0.02427832],
       [0.05403387, 0.0243305 , 0.04028422, 0.72135796],
       [0.73654379, 0.10406606, 0.92445699, 0.32987775],
       [0.18072718, 0.34832409, 0.71184788, 0.78884535]])

<Figure size 432x288 with 1 Axes>
```

**Expected outcome**

The `scatter` and `errorbar` function should work the same. 

**Matplotlib version**

  * Operating system: macOs 10.15.1
  * Matplotlib version: 3.1.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: Python 3.7.3
  * Jupyter version (if applicable): 1.0.0
  * Other libraries: numpy 1.17.4

Everything installed using `pip` and `virtualenv`

**Comment by ImportanceOfBeingErnest** [comment]
Correct, `errorbar` only takes a single color as input. Because, as the documentation states: 
> All other keyword arguments are passed on to the `plot` command for the markers.

and `plot` also only takes a single color in.

While from a user's perspective one might expect all those functions to work exactly the same, this is not the case on the technical level. `plot` and `errorbar` create `Line2D` objects (which have a single color), while `scatter` creates a `PathCollection`, whose purpose it is to allow for different properties. 

I'm not sure about usecases for differently colored errorbars. If you can enlighten us about your usecase or possible user groups for such feature, it might help identify how urgent that is needed.

**Comment by RobertArbon** [comment]
Thanks for your reply, I see I didn't twig the connection to `plot`.  The docs are a little confusing as it says: 

Valid kwargs for the marker properties are Lines2D properties:
Property | Description
-- | --
color or c | color

which I took to mean `c` is fine. 


As to my use case - I've been plotting values, `y` with errors, while I'm coloring them according to and explanatory variable. So if `y = y(x, z)`, then I'm plotting `y` vs `x` and coloring according to `z`. It's equivalent to using `hue` in `seaborn.FacetGrid` with one facet. 

Thanks for your help. If you think it's worth a new feature that would certainly be useful.

**Comment by jklymak** [comment]
This is achievable by looping through your values and changing the color for each errorbar.  My guess is that it would be a tough ask to add that ability natively to the `c` argument, if only for back compatibility concerns.  But if someone had a proposal, it might be possible.  I've not looked at the details of how errorbar is implemented; for all I know all it does is a loop and its just as easy to take a variable `c`.  

As for the docs, the `c` argument is fine, but its just a single value, not an array.

**Comment by RobertArbon** [comment]
OK thanks.  I have an easy workaround.

**Comment by jklymak** [comment]
Please ask to re-open if you think performance issues would merit a more integrated solution....

**Comment by kaarelmand** [comment]
Is it possible to reopen this issue? In my field (geochemistry),  scatter plots of data with error bars are very commonly used and colorization by a continuous variable is often needed.

For example, I'm using matplotlib for a paper which reports chromium isotopic compositions in rock samples (see panel b in the figure below). These types of measurements are commonly reported with a mean and error but since I wanted to color-code the rock sample measurements by the age of the rock, I could not use `plt.errorbar` and had to rely on `plt.scatter`. My reviewer, quite correctly, has pointed out that the data should display error bars, which means I will have to remove the age visualisation. Looping over unique values is not efficient in this case as the variable is continuous.

![Figure 6](https://user-images.githubusercontent.com/16322491/153717917-fbf9a811-452d-48f1-b0a4-b2a2972cb808.png)
