### ISSUE TITLE
“Size” ignored if placed before fontproperties 

### ISSUE THREAD

**Issue by ShawnChen1996** [matplotlib/matplotlib#16389]
### Bug report

**Bug summary**

In `as.text`, `ax.set_title` and all the functions realated to displaying characters on the figure,
the arguement `size` is ignored if it is placed before fontproperties.

**Code for reproduction**
```python
data = np.random.randn(10000)
plt.hist(data, bins=40, facecolor="blue", edgecolor="black", alpha=0.5)
plt.xlabel("value", fontproperties='SimHei',size=20  ) # this will work
plt.ylabel("counts",size=20, fontproperties='SimHei')  # this doesn't
plt.show()
```
This issue is replicated with ipython (%pylab) and jupyter-notebook
####

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system: win10  1909
  * Matplotlib version:  Version :3.1.2 ,   Build : py36_1 ,    conda-forge
  * Matplotlib backend (`print(matplotlib.get_backend())`):  module://ipykernel.pylab.backend_inline
  * Python version:  3.6.10
  * Jupyter version (if applicable): version  1.0.0           
  * Other libraries: 

`conda install -c conda-forge matplotlib`

**Comment by timhoffm** [comment]
Somehow `update()` gets called with both values even though `Text()` holds `fontproperties` as explicit parameter but `size` is  handled via `**kwargs`. Since the passed arguments of `update()` are processed sequentially, order matters here.

If `fontproperties` is used with a string, a FontProperties instance with non-given defaults (including size) is created. That will overwrite the explicit `size` in the second example.

IMHO expicit font-related keywords like `size` should have precedence over `fontproperties`.

This is a good first issue to dig into. Please include a test based on the above example to validate the fix.

**Comment by tacaswell** [comment]
However, if we get passed an actual `FontProperties` objects (not a string we implicitly up-convert) the precedence is not completely clear.    I can see an argument for in that case the order of the kwargs mattering and the last one winning, however in the case of a string input (like this example) it is pretty clear that the `size` kwarg should have higher priority.   Given that is is better to not have behavior like that depend on the exact types, `size` should always win.

Which is a very long way of saying "I agree with @timhoffm".

**Comment by asongtoruin** [comment]
I'd be happy to take a look at this if you wouldn't mind?

From a quick dig around (and @timhoffm's comment) I think it's coming from `Artist.update()`

https://github.com/matplotlib/matplotlib/blob/c91d7ef888577e14a73405f8504e44d7a8113bc9/lib/matplotlib/artist.py#L968-L993

The simplest solution I can think of would be to pop `fontproperties` from the `props` dict to ensure `set_fontproperties` is run before any of the other functions. It's not particularly elegant, but it would ensure that values given by the other kwargs would always take precedence.

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/pull/16328 where I'm basically trying to get rid of this kind of kwargs reordering...

I think the proper solution would be for FontProperties to properly keep unset properties as being, well, unset, and not overwriting already existing properties on the text object.

(Note that in the base case here, passing `family="SimHei"` should work just fine, and will in fact work better if the font family contains a dash...)

**Comment by RiazCharania** [comment]
Is anyone else currently working on this? If not I'll give it a try.

**Comment by timhoffm** [comment]
@RiazCharania go for it. The first step is to clarify the expected behavior. See https://github.com/matplotlib/matplotlib/issues/16389#issuecomment-582181302 and https://github.com/matplotlib/matplotlib/issues/16389#issuecomment-585110776. I that you provide a short summary defining the behavior for all cases before implementing.

**Comment by HarrisonFok** [comment]
We'll give it a try too
