### ISSUE TITLE
xpdf distiller seems broken

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#16538]
### Bug report

**Bug summary**

What the title says

**Code for reproduction**

```python
rcParams["ps.usedistiller"] = "xpdf"; plot(); savefig("/tmp/test.ps")
```

**Actual outcome**

```
<elided>
  File ".../matplotlib/backends/backend_ps.py", line 1247, in xpdf_distill
    cbook._check_and_log_subprocess(
  File ".../matplotlib/cbook/__init__.py", line 2129, in _check_and_log_subprocess
    raise RuntimeError(
RuntimeError: The command
    ps2pdf '-dAutoFilterColorImages#false' '-dAutoFilterGrayImages#false' '-dAutoRotatePages#false' '-sGrayImageFilter#FlateEncode' '-sColorImageFilter#FlateEncode' '-sPAPERSIZE#letter' /tmp/tmpddvwd66_/tmp.ps /tmp/tmpddvwd66_/tmp.ps.pdf
failed and generated the following output:

and the following error:
Unrecoverable error: typecheck in .putdeviceprops
```

**Expected outcome**

Success.

**Matplotlib version**

  * Operating system: arch linux / fedora
  * Matplotlib version: master, but present as far back as mpl3.0 at least.
  * Matplotlib backend (`print(matplotlib.get_backend())`): ps
  * Python version: 38
  * Jupyter version (if applicable): no
  * Other libraries: ghostscript 9.50 on arch; 9.27 on fedora

**Comment by QuLogic** [comment]
Bisect points to 4ba9be12d240cdeee27354bd37fce098b6d99ce0, i.e., #10295, but the problem is not changing `=` to `#`, but rather that that PR incorporates #10294 which adds `-dAutoRotatePages#false` (on a side note, this is why you shouldn't mix different behavioural changes in a single commit.)

But maybe since it doesn't fail on CI, but does locally, it's a regression in Ghostscript too.
