### ISSUE TITLE
Let legend get the handles from the provided objects if not specified explicitly.

### ISSUE THREAD

**Issue by Wrzlprmft** [matplotlib/matplotlib#16567]
Consider the following example:

``` Python 3
import matplotlib.pyplot as plt
import numpy as np

fig,axes = plt.subplots()
line_A = axes.plot( np.random.random(10), label="foo" )[0]
line_B = axes.plot( np.random.random(10), label="bar" )[0]
line_C = axes.plot( np.random.random(10), label="quz" )[0]
lines = [line_A,line_B]

axes.legend( lines, [line.get_label() for line in lines] )
```

The last line needs to be this complicated since I get unwanted internal information if I just use `axes.legend(lines)`. However, this seems like something `legend` could do automatically: If I do not specify the handles for the legend, it extracts them from whatever I give it automatically.

This may be a duplicate of [this request](https://github.com/matplotlib/matplotlib/issues/8389), but I am not sure.

**Comment by ImportanceOfBeingErnest** [comment]
If only one argument is given to `legend`, it is assumed to be the labels of existing artists, see [docs](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.axes.Axes.legend.html). 
If you want to specify the handles, without the labels (which is possible if the handles have labels set already), it would be

    axes.legend(handles=lines)

**Comment by Wrzlprmft** [comment]
Ah, I see. Thanks.

I would suggest documenting this more clearly as a fourth case in the documentation.

**Comment by tacaswell** [comment]
@Wrzlprmft Could you open a pull request making the change that would have made this usage clear to you?

**Comment by timhoffm** [comment]
Currently, all elements in `labels` are implicitly casted to `str`, which results in unexpected output if you pass a list of arbitrary objects.. We should limit `labels` to be a list of strings and error out otherwise. IMHO this would help more than trying to improve the docs. The docs already tell that a single argument is interpreted as `labels` and that `labels` should be a list of strings.

This is one of the "funny" signatures and we may consider cleaning it up via a depreacation, so that we can make the parameters explicit in the signature.
