### ISSUE TITLE
Can't unpickle figure objects made with v 2.1.0 using latest 3.1.3

### ISSUE THREAD

**Issue by goracle** [matplotlib/matplotlib#16562]
I get attribute errors when attempting to unpickle 2.1.0 figures.

**Comment by ImportanceOfBeingErnest** [comment]
Unfortunately, this is an inherent consequence of pickling. It is only guaranteed to work within the exact same version. (Though one might be lucky to have it still working across different minor versions.)

If you need to open the old files again, it is nowadays quite easy to install a new environment with the respective matplotlib version, e.g. via miniconda, and continue working from there.

**Comment by goracle** [comment]
Yes, but you could've made them compatible.  I created these plots a few weeks ago, but my version was apparently slightly out of date.  Now, I have to have people downgrade to look at them.  I don't see why the task of backwards compatibility is now my problem to solve, as a user.  This is traditionally the task of the developers.  If you're going to offer a save format, you should make it backwards compatible.  This is some weird hack/use of language that offloads that traditional work onto me.  Thanks /s

**Comment by jklymak** [comment]
I think its a general rule that pickle is not suitable as an archive format, but is for temporary storage only.  Given how easy it is to maintain environments these days, you should be able to set up an environment with the old version of Matplotlib that will still work.

**Comment by tacaswell** [comment]
I agree that if we offered a serialization format it should be stable across versions of both Matplotlib and Python.  However, we do not "offer a save format", we support pickle so that we play nicely with Python tools (such as multi process) that require objects to be pickable to serialize between processes.  If there is anyplace in our documentation that suggests otherwise?  

I do not consider the contents of a pickle file to be part of our stable API.  They will necessarily encode the private parts our objects which we need to be able to change. 

The official position on how to serialize figures is save the function or script that generates the Figure.
