### ISSUE TITLE
Animations & Object Persistence

### ISSUE THREAD

**Issue by jakevdp** [matplotlib/matplotlib#1656]
Unlike other plotting operations, if you create an animation and do not store it in a persistent variable, it will fail.

So, for example,

``` python
import matplotlib.pyplot as plt
from matplotlib import animation

fig = plt.figure()

def animate(i):
   # ... do something here

anim = animation.FuncAnimation(fig, animate)
plt.show()
```

will work, but changing the final lines to

``` python
animation.FuncAnimation(fig, animate)
plt.show()
```

(i.e. not creating a variable to store the animation) leads to a quiet failure.

I think the problem is because the figure does not store a reference to the animation object, python's garbage collection removes it if it is not explicitly stored.
Probably the best way to address this would be to add an `animation` attribute to the `Figure` class, such that any animation will store a pointer to itself in its associated figure.

I think this is a pretty easy fix, but I'm just wondering if there are any other details to be aware of when adding something like this.

**Comment by petehuang** [comment]
What's the latest on this?

**Comment by dopplershift** [comment]
Looking at it with really fresh eyes (2 years later), I think @jakevdp 's last suggestion, of just adding to a `fig.animations` list within the constructor (*should* just be able to go in the `Animation` base class) is probably the way to go to eliminate a common gotcha for animations.

My only minor concern here is that we're taking a one-way coupling (`Animation` knows about `Figure`), and turning it into a two-way coupling (now also `Figure` knows about `Animation`). It's only one small list--but statements like that are how we ended up with the highly coupled, somewhat cohesive, ungodly mess that is much of matplotlib's (highly functional) codebase. 

(For the record, I still don't consider this a problem, since `FuncAnimation` and co. are classes; nowhere in Python do we create an instance of a class and expect it to go on living if we don't assign a name to it.)

I'm not volunteering to do it, but adding the `animations` list to the `Figure` constructor and calling `append` in the `Animation` constructor seems straightforward enough to be beginner ready.

**Comment by t-makaro** [comment]
So, I noticed an interesting use case for this in writing tests.

Currently, when doing image comparison tests. A test function is written to make a plot, and a decorator grabs that figure and saves it as an image before comparing it. This figures are grabbed [by these lines](https://github.com/matplotlib/matplotlib/blob/4d1d12c39f4de38f6068ff118364e199b02efdcb/lib/matplotlib/testing/decorators.py#L212). If the figure had knowledge of the animation, then it would be easy to grab the animation and save it for comparison. Alternatively, the test function could return the animation so that the decorator could pick it up. #11839

**Comment by SamuelQZQ** [comment]
From the perspective of language, I agreed with @dopplershift. This is not a problem. Nowhere in Python do we create an instance of a class and expect it to go on living if we don't assign a name to it.

But From the perspective of creating animations, it's weird. Is that necessary for users to consider that much about the language detail when he just wants to simply use the animation API? And must someone will be confused why his animation disappear just because he hasn't created a variable (never apparently used) to store the animation. Even if he has passed the Figure argument to Animation. 

I'm not sure if it makes sense or not. I'm new and try to figure out my first PR here.

[**PR link**](https://github.com/matplotlib/matplotlib/pull/15026)

**Comment by anntzer** [comment]
Untagged "good first issue", given that it's really a design problem now (and we already rejected two PRs implementing the "obvious" solution).

**Comment by jklymak** [comment]
I think we've had this conversation a few times in favour of asking people to keep their animations persistent.  Yes, people are still sometimes confused about this, but the docs have a lot of pointers that explain the right way to do this, so I think it's OK to close this.
