### ISSUE TITLE
Incosistent keyword arguments

### ISSUE THREAD

**Issue by Prukutu** [matplotlib/matplotlib#16747]
### Bug report

**Bug summary**

There is some very frustrating inconsistencies in keyword arguments names across the library. One notable (to me) example is "ncol" and "ncols" as found in matplotlib.gridspec.GridSpec and matplotlib.axes.Axes.legend, respectively. 

Not a big issue, but I'm sure I'm not the only one consistently getting mixed up!

**Matplotlib version**

  * Operating system: Ubuntu
  * Matplotlib version:  3.03
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.3

Installed matplotlib and python via a pip virtualenv

**Comment by timhoffm** [comment]
Thanks for the feedback. We know that matplotlib unfortunately has some inconsistencies in its API. Matplotlib has been developed by different people over a very long time, and API consistency and design has not always been watched for as strongly as we do nowadays.
Today we have to make a trade off between improving the existing API and breaking changes we would introduce with that. Given that there are millions of users, we have to be very conservative with breaking changes.

**Comment by TAdeJong** [comment]
Just weighing in here with my opinion (Instead of opening a new issue: https://twitter.com/sjvrijn/status/1395746154223181828 ) The `ncol` in `legend()` versus by now pretty consistently used  `ncols` elsewhere is, I feel, an example that might be worth changing by now, or at least start accepting `ncols` as well... 
Maybe as a "good first issue"? 
Or is it worthwhile to start collecting a list of such minor inconsistencies to target for a next release (more explicitly than [the label](https://github.com/matplotlib/matplotlib/labels/API%3A%20consistency) does)?

**Comment by anntzer** [comment]
For the specific case of here I would agree with making `ncols` a synonym for `ncol` (or rather having `ncols` be the canonical name).  This can be done using `_api.rename_parameter` with a small modification to allow having just the renaming effect, but never emitting a deprecation.

**Comment by oscargus** [comment]
This was fixed in 3.6: https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.6.0.html#ncol-keyword-argument-to-legend-renamed-to-ncols 

PR: https://github.com/matplotlib/matplotlib/pull/23198
