### ISSUE TITLE
eventhough i compiled freetype and fontconfig, ,,cairo doesnot recognizing ....what i need to do can any help me out

### ISSUE THREAD

**Issue by ravitejaambati97** [matplotlib/matplotlib#16785]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by ImportanceOfBeingErnest** [comment]
Hello. This is the matplotlib bug tracker. If you think you have found a problem with matplotlib, you are invited to **completely** fill out the bug report template.  
If instead you need help with installing or using matplotlib you are invited to join https://discourse.matplotlib.org and post any question you have there.

Closing this for now, because the information given does not allow to understand the problem.
