### ISSUE TITLE
hist() with density=True and logarithm scale is not usable

### ISSUE THREAD

**Issue by donggu-prestolabs** [matplotlib/matplotlib#16860]
### Bug report

**Bug summary**

`hist([arr1,arr2], density=True, bins=np.geomspace(..)) && ax.xscale="log"` only shows arr1 or arr2 if they have different scales.

The problem is `density=True` normalizes using `bins[i+1]-bins[i]`.

For example, when `bins=[0.1, 1, 10, 100, 1000]`, and `ax.xscale="log"`, the bin [0.1,1] and [1,10] have the same visual width but scales differently. Due to this, if `arr1` ranges over small values and `arr2` ranges over large values, `arr1` has much larger `y` hence `arr2` is not visible.

This may be not a bug, but counter-intuitive. I suggest to add `visually_normed=True` which normalizes using visual bin widths.

**Example**

```
import matplotlib.pyplot as plt
import numpy as np


x1 = np.random.normal(0,1,[1000])
x2 = np.random.normal(3,1,[1000])x1 = 10**x1x2 = 10**x2
plt.subplot(311)plt.xscale('log')plt.hist(x1, bins=np.geomspace(1,10**5,100), density=True)
plt.subplot(312)plt.xscale('log')plt.hist(x2, bins=np.geomspace(1,10**5,100), density=True)
plt.subplot(313)plt.xscale('log')plt.hist([x1,x2], bins=np.geomspace(1,10**5,100), density=True, label=['x1','x2'])plt.legend()plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/52903912/77219964-26d89180-6b7e-11ea-9931-e9637a623194.png)

**Expected outcome**

The orange bar in the third plot should be visible.

**Matplotlib version**
  * Matplotlib version: 3.2

**Comment by mwaskom** [comment]
> The problem is density=True normalizes using bins[i+1]-bins[i].

I don't think this is an accurate statement. matplotlib [uses numpy](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L6583) to calculate the histogram and that is [not what numpy does](https://github.com/numpy/numpy/blob/v1.17.0/numpy/lib/histograms.py#L896...L898).

**Comment by donggu-prestolabs** [comment]
`np.diff(bin_edges)`
This looks like `bin_edges[i+1]-bin_edges[i]`.

**Comment by jklymak** [comment]
There is no way we can normalize visually, because the user can choose whatever x-scale they want and we don't know what choice they will use, and they can change it after the histogram is calculated.  Right now, `density=True` does what we say and makes the area under the curve 1.  If you need to normalize visually, you redo the norm as you see fit, perhaps using the `weights` kwarg.

**Comment by donggu-prestolabs** [comment]
Yeah, `density=True` does what it should do. It just does not fit the use case. Using `weights` requires to know each point's bin in advance.
> they can change it after the histogram is calculated
This sounds like a dead end.

**Comment by genialnylala** [comment]
Hi,
it is in fact true that numpy.histogram does not normalize correctly when using logarithmic bins and integer value arrays a. The reason is that the width of bins can be smaller than 1 which leads to higher density than it should be. If my bin_edges are eg.

[1.        ,   1.13945444,   1.29835642,   1.47941798,
         1.68572938,   1.92081183,   2.18867756,   2.49389836,
         2.84168356,   3.23796894,   3.68951808,   4.20403775]

and array a= [1,1,1,1,2,3],  then numpy.histogram(density=True) will return the histogram [3.184 , 0 , 0 , 0 , 0 , 0.829 , 0 , 0 , 0.84175 , 0 , 0 ]. One can clearly see the normalization has not worked correctly because the values do no add up to 1.

If the array a passed into numpy.histogram consists of integers only, minimum bin size should be 1.
