### ISSUE TITLE
tk window immediately resizes down to zero-height upon showing up.

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#16926]
### Bug report

**Bug summary**

tk window (whether tkagg or mplcairo.tk) immediately resizes down to zero-height upon showing up.

**Code for reproduction**

```
$ MPLBACKEND=tkagg python -c "from pylab import *; plot(); show()"
```

**Actual outcome**

As described above.

**Expected outcome**

Window stays at original size.

**Matplotlib version**

  * Operating system: arch linux
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`): tkany
  * Python version: 38
  * Jupyter version (if applicable):
  * Other libraries: 

This bisects to https://github.com/matplotlib/matplotlib/pull/16828 (attn @QuLogic), even though it's not clear how that's related... perhaps the dynamic changes to figure dpi confuse tk, but it's not clear why this is different from before?

**Comment by QuLogic** [comment]
I'm guessing this is related to the flaky test on AppVeyor. The only thing that's hit by that test is the fix to `Text.get_window_extent`: https://github.com/matplotlib/matplotlib/pull/16828/files#diff-15e8fbe2a4d40deb738e8627eba02318L894

My best guess is that `figure.dpi` has _never_ been correctly set, and it's been relying on this accidental change to do so.

**Comment by QuLogic** [comment]
So it seems that's not it, as I can never trigger a case where `dpi is not None`, but `self.figure.dpi is None` (or something other than `dpi`). The strange thing is that if I print out all the properties that would be changed in `Figure._set_dpi`, _nothing_ changes. So neither the forward call to `Figure.set_size_inches` (which might hit the canvas/toolbar size), nor the callbacks for the `dpi_changed` event do this. Yet somehow on a later call, the size is smaller...

There's definitely something else weird going on; if you add an extra dpi changed on the old code:
```
MPLBACKEND=tkagg python -c "from pylab import *; plot(); gcf().dpi=100; show()"
```
then there will be one call to `Figure.set_size_inches` with `[6.4  4.46]`, but it magically fixes itself. I'm guessing what happens is that since the dpi change in the `Text.get_window_extent` is part of the draw/stale mechanism, it is enough to propagate that height change.

**Comment by 15100288536** [comment]
a question about how to use Chinese,when I want to show Chinese,it always shows me errors,thanks

**Comment by tacaswell** [comment]
was  #16828  backported to the v3.2.x branch?

**Comment by tacaswell** [comment]
Ah, I understand now, not a regression on 3.2.x, but was backported there because it fixed some other bugs.

**Comment by QuLogic** [comment]
You're right though; this bug was never in 3.2, so this issue shouldn't be tagged on it.
