### ISSUE TITLE
Unable to append to array.array after using it in a plot

### ISSUE THREAD

**Issue by MichaelClerx** [matplotlib/matplotlib#16935]
I'm running simulations and logging the output to `array.array` objects. After I use one of these to plot results, the array's `append()` method stops working.

It seems something in matplotlib's plotting code causes the array to "export a buffer"

**Code for reproduction**
```python
#!/usr/bin/env python3
import array
import matplotlib.pyplot as plt

x = array.array('d')
y = array.array('d')

# Appending to array works as expectecd
for i in range(10):
    x.append(i)
    y.append(i**2)

# Now using x and y in a plot
plt.figure()
plt.plot(x, y)

# Side effect has occurred: no longer able to append to array
x.append(11)
```

**Actual outcome**

```
Traceback (most recent call last):
  File "./log_append.py", line 15, in <module>
    x.append(11)
BufferError: cannot resize an array that is exporting buffers
```

**Expected outcome**

No errors

**Matplotlib version**

  * Operating system: Fedora linux
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): template, Agg
  * Python version: 3.7.6
  * Other libraries: Myokit (pip installable)

Matplotlib installed via dnf (package manager)

**Comment by jklymak** [comment]
Can you make a self-contained example that doesn't require `myokit` or whatever is in `example`?  That error doesn't come from matplotlib, so its pretty hard for us to debug or even know that matplotlib is the source of the problem.

**Comment by MichaelClerx** [comment]
Fair enough:

```
#!/usr/bin/env python3
import array
import matplotlib.pyplot as plt

x = array.array('d')
y = array.array('d')

for i in range(10):
    x.append(i)
    y.append(i**2)

plt.figure()
plt.plot(x, y)
plt.close()

x.append(11)
```

The error does not originate in matplotlib, the error is that matplotlib somehow changes the state of the `array.array` that was passed into `.plot()`. It's a side effect. Doesn't happen on Python 2.7 with matplotlib 2.2.5, but happens on Python 3.7.6 with matplotlib 3.0.3

**Comment by ImportanceOfBeingErnest** [comment]
I suspect that this has to do with the python version in use, rather than matplotlib. As far as I know there is no special support for python's inbuilt `array`. 

Note that you can easily copy your data to one of the supported formates, e.g. a python list

    plt.plot(list(x), list(y))

or a numpy array

    plt.plot(np.array(x), np.array(y))

**Comment by anntzer** [comment]
Actually, this is yet another subtle bug arising from (guess what) the unit system.  This can be triggered without using `array.array`:
```
from matplotlib import pyplot as plt
import numpy as np

t = np.array([1., 2.])
fig, ax = plt.subplots()
l, = ax.plot(t, t)
t[0] = 1.5
l.set_drawstyle("steps")
print(l._yorig)
plt.show()
```
![test](https://user-images.githubusercontent.com/1322974/77792236-4c770680-7068-11ea-82ec-2f8df816ca59.png)

Note how the x axis uses the "new" x values ([1.5, 2]) but the y axis the initial ones ([1, 2]).
Essentially, this is because Line2D keeps a reference to the "original" data (_xorig, _yorig) to be able to handle unit changes (and this is also triggered by drawstyle changes, as in the demo here), but of course this means that changes to the original data are sometimes subtly brought in sync with the "copy" used by Line2D.

**Comment by ImportanceOfBeingErnest** [comment]
The input for `scatter` should go through the same unit conversion than for `plot`; yet, for `scatter` the problem does not occur.  
Would there be a reason to keep input mutable?

So a quick test shows that 

```
diff --git a/lib/matplotlib/axes/_base.py b/lib/matplotlib/axes/_base.py
index 109e2a5b1..00d9a4001 100644
--- a/lib/matplotlib/axes/_base.py
+++ b/lib/matplotlib/axes/_base.py
@@ -333,6 +333,9 @@ class _process_plot_var_args:
         else:
             x, y = index_of(tup[-1])

+        x = np.array(x)
+        y = np.array(y)
+
         if self.axes.xaxis is not None:
             self.axes.xaxis.update_units(x)
         if self.axes.yaxis is not None:

```

would fix this. But this might cause performance decrease?!

**Comment by anntzer** [comment]
That's because scatter is a PolyCollection, which does *not* support unit reconversion (i.e., in theory, you can plot "meters" (in mpl's unit system sense) and then later convert them to "feet") -- only Line2D does, at it does so at the cost of an extremely complicated system.
By adding calls to np.array, you'd drop the "original" units and lose the ability to change them.
I'm not convinced this feature is really worth the complexity -- especially given that it *only* works for Line2Ds -- but this has already been discussed to death elsewhere.

**Comment by jklymak** [comment]
... ooops was just typing what @anntzer was typing, plus or minus.  

I agree that we should get rid of unit *re*-conversion and simply resolve units when the `plot` method gets called.  But perhaps @story645  and @tacaswell have other plans.

**Comment by MichaelClerx** [comment]
Not an option to just copy any data you want to keep a hold of?

**Comment by ImportanceOfBeingErnest** [comment]
`x = np.array(x)` would indeed do a copy. But apparently this is explicitely not done as others have commented. 
What this means for now, is that the user is responsible for doing the copy - which, after all, is not too hard; you just need to know about that fact, which is completely undocumented.

**Comment by tacaswell** [comment]
We also keep a reference to the original data because there is some performance tuning in `Line2D` to detect monotonic data and only passing a slice of the full data down to the renderers based based on the view.

**Comment by tacaswell** [comment]
I think we _intend_ to create copy and are running into an edge case where numpy has a well justified optomization.

**Comment by MichaelClerx** [comment]
Seems to happen when you create a numpy array with `copy=False`
https://github.com/numpy/numpy/issues/15860

Is that what's happening in the matplotlib code?

**Comment by ImportanceOfBeingErnest** [comment]
What matplotlib's `plot` does is to call `numpy.atleast_1d`, which has the same effect of creating a pointer instead of a copy.

https://github.com/matplotlib/matplotlib/blob/381bc485a862fe81876a6ac98834d0f1a92e6704/lib/matplotlib/cbook/__init__.py#L1292

<hr>

Fun fact: If `plt.plot` is replaced by 
```
l = plt.Line2D(x,y)
plt.gca().add_line(l)
```
the original example works fine, because `type(l._xorig)` stays an `array.array`.

**Comment by tacaswell** [comment]
I don't think this is related to units, we just need to be better about making sure we make a copy when we need to?

**Comment by anntzer** [comment]
How do you propose to perform a copy *without* calling np.asarray (which would strip out units)?  Note that array-likes (e.g. the stdlib's `array;array`) may not have a copy() method.

Actually, a quick look suggests that the stdlib's `copy.copy()` may work?  but untested...

**Comment by jklymak** [comment]
I think with plot we hang onto the original object until draw time in order to allow the units to change on the axis.  The simplest solution would be to not try and do that anymore and to call convert when plot is called like we do for other artists.  The idea that the user will want to change the axis units after things are added to it is a great idea in theory but we haven’t managed to do it right.

**Comment by MichaelClerx** [comment]
```
#!/usr/bin/env python3
import array
import matplotlib
import matplotlib.pyplot as plt

print(matplotlib.__version__)

x = array.array('d')
y = array.array('d')

# Appending to array works as expectecd
for i in range(10):
    x.append(i)
    y.append(i**2)

# Now using x and y in a plot
plt.figure()
plt.plot(x, y)

# Side effect has occurred: no longer able to append to array
x.append(11)

plt.show()
```
This now seems to run without errors

**Comment by jklymak** [comment]
Thanks for checking.  We will close.
