### ISSUE TITLE
Different colors for legends across all axes in a figure.

### ISSUE THREAD

**Issue by greatsharma** [matplotlib/matplotlib#16977]
I generated this plot but get different colors for different axes in the same figure. I want the color to be same for the same label.

![CV_10](https://user-images.githubusercontent.com/32649388/78020980-02479b00-7370-11ea-8534-7f85b36b1208.png)

I used the below code to generate this figure.

```
    fig = pyplot.figure(1, (10,8))

    for i,to_plot in enumerate(['metric', 'loss']):
        ax = pyplot.subplot(2,1,i+1)

        for f in os.listdir(MODEL_PATH):
            if f.startswith(to_plot) and f'CV{fold}' in f:
                label = '_'.join(f.split('_')[1:-2])
                metric = joblib.load(MODEL_PATH + f)
                sns.lineplot(x=range(1,fold+1), y=metric,
                                    label=label, markers=True, dashes=True)

        ax.set_xlabel('CV FOLD')

        if to_plot == 'metric':
            ax.set_ylabel(global_var.METRIC + f'  {to_plot}')
        else:
            ax.set_ylabel(global_var.LOSS + f'   {to_plot}')

        ax.legend()
        pyplot.tight_layout()

    pyplot.savefig(IMG_PATH + f'CV_{fold}.png')
    del fig
```

Please help.

**Comment by ImportanceOfBeingErnest** [comment]
Labels are defined by the `label` argument - whatever you pass in is correctly shown in the legend. Colors are applied sequentially in the order of plot creation. You can hence either make sure to loop in the order you desire, or use a mapping that maps the label to a predefined color. An alternative is to use seaborn's `FacetGrid`. 

Since there is no bug or undesired behaviour in matplotlib identified here, I will close this. For further help, we generally recommend bringing usage questions up at discourse.matplotlib.org or stackoverflow.com

**Comment by QuLogic** [comment]
>         for f in os.listdir(MODEL_PATH):

And to be clear here, because this came up in someone's broken (and published!) analysis before, `os.listdir` does not guarantee the order of its output.
