### ISSUE TITLE
Documentation not updated

### ISSUE THREAD

**Issue by tommydino93** [matplotlib/matplotlib#16994]
### Bug report

**The documentation is not in sync with the github page**

I was following the tutorial at [this link](https://matplotlib.org/examples/axes_grid/demo_parasite_axes2.html) and I noticed that it is not in sync with its corresponding [github page](https://github.com/matplotlib/matplotlib/blob/master/examples/axisartist/demo_parasite_axes2.py).

In fact, the line below is missing in the documentation while it's present on the github page:

`par1.axis["right"].toggle(all=True)`

Without it, one of the y axis is not visible

------------------------------------------------------------------------------------------------------------------------------------

  * Operating system: Ubuntu Xenial 16.04
  * Matplotlib version: 3.0.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.5
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by timhoffm** [comment]
The reason for the difference is twofold:

- Older versions of the docs had another file structure and currently linger in between the current website files. This problem is discussed in #12374. The current version of the example is https://matplotlib.org/gallery/axisartist/demo_parasite_axes2.html
- The example has recently been updated in #16877. Therefore the latest released version above is is different from the master branch.
