### ISSUE TITLE
Computer Modern Glyph Error

### ISSUE THREAD

**Issue by roussel-ryan** [matplotlib/matplotlib#17007]
### Bug report

Trying to use computer modern roman (cmr10) font in plot. Getting an error which prevents minus sign rendering in plot.

```
import matplotlib as mpl
import matplotlib.pyplot as plt

mpl.rc('font',family = 'serif', serif = 'cmr10')
fig, ax = plt.subplots()

ax.set_title('This is a special font:')
ax.set_xlabel(r'This is the default font $\alpha\beta\gamma$')
ax.set_yticks([-1,0,1])
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/24279776/78292576-7d31c280-74e4-11ea-9657-81d602684acf.png)

Output:

```
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:214: RuntimeWarning: Glyph 8722 missing from current font.
  font.set_text(s, 0.0, flags=flags)
C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\backends\backend_agg.py:183: RuntimeWarning: Glyph 8722 missing from current font.
  font.set_text(s, 0, flags=flags)
```

**Expected outcome**
Correct rendering of symbols

**Matplotlib version**

  * Operating system: Cygwin / Windows10 Enterprise 64 Bit
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 3.7.7
  * Jupyter version (if applicable): N/A
  * Other libraries: 

Installed matplotlib via anaconda on default channel

**Comment by anntzer** [comment]
Likely due to https://github.com/matplotlib/matplotlib/pull/14567?  Seems reasonable to special case unicode minus to map to normal minus given that we already special case it for other purposes and also https://github.com/matplotlib/matplotlib/pull/16366, just needs to figure out what are the fonts that need that and can also do it correctly (not mapping to a dash).

**Comment by anntzer** [comment]
Ah, actually that's not a regression, the unicode minus comes from https://github.com/matplotlib/matplotlib/blob/bb75f737a28f620fe023742f59dc6ed4f53b094f/lib/matplotlib/mathtext.py#L63 (of course we can still fix it...).

**Comment by scawsome** [comment]
Ok thank you for the effort! I'm not sure if I can do anything to help, but please let me know if there is

**Comment by casperdcl** [comment]
Same issue here.

Setting font as Computer Modern Roman (`matplotlib.rcParams.update({'font.family': 'cmr10'})`) results in negative signs in ticklabels not rendering. Oddly, negative signs in titles & labels render fine.

![image](https://user-images.githubusercontent.com/10780059/86539114-19a79e80-bef2-11ea-964a-76f4ef80e04f.png)

**Code for reproduction**

<details>

```python
import matplotlib
matplotlib.rcParams.update({
    #'mathtext.fontset': 'cm',
    'font.family': 'cmr10'
})
import matplotlib.pyplot as plt

plt.figure()
plt.plot(range(-1, 1), range(-1, 1))
plt.title(r"dash (-) $mathtext:negative (-)\bf{mathtext.bf:negative (-)}$")
plt.xlabel(r"dash (-) $mathtext:negative (-)\bf{mathtext.bf:negative (-)}$")
```

</details>

**Comment by casperdcl** [comment]
unfortunately the only workaround I could come up with is:

```python
plt.gca().set_xticklabels([i.get_text().replace('−', '$-$') for i in ax.get_xticklabels()])
plt.gca().set_yticklabels([i.get_text().replace('−', '$-$') for i in ax.get_yticklabels()])
```

**Comment by anntzer** [comment]
I looked a bit more into this.  Fundamentally, the problem is that we are relying on the old computer modern fonts, where symbols (e.g. minus) and letters/digits are in different font files (cmr10/cmsy10); moreover the "standard" (non-mathtext) Text object is only able to use a single font file at a time (and it would be quite a big surgery to change that limitation).

Fortunately, when using *mathtext*, you can use multiple fonts at the same time; so one needs to force the ticks to use mathtext `rcParams["axes.formatter.use_mathtext"] = True`, and then we're not done yet, because the ticker uses `\mathdefault` to wrap ticks, i.e. use the "non-mathtext" font... so then we need to add a special-case to mathtext, when using cmr10 as the non-mathtext font, to look up the minus sign in cmsy10 instead:
```patch
diff --git i/lib/matplotlib/mathtext.py w/lib/matplotlib/mathtext.py
index 8b9df7e19..8fdc29cad 100644
--- i/lib/matplotlib/mathtext.py
+++ w/lib/matplotlib/mathtext.py
@@ -842,6 +842,10 @@ class UnicodeFonts(TruetypeFonts):
             found_symbol = False
             font = self._get_font(new_fontname)
             if font is not None:
+                if font.family_name == "cmr10" and uniindex == 0x2212:
+                    font = get_font(
+                        cbook._get_data_path("fonts/ttf/cmsy10.ttf"))
+                    uniindex = 0xa1
                 glyphindex = font.get_char_index(uniindex)
                 if glyphindex != 0:
                     found_symbol = True
```
(probably a real patch would need to add a comment there).  Together with `rcParams["axes.formatter.use_mathtext"] = True`, I think this is the only reasonable short-term fix.  Brownie points for whoever makes a PR out of this.

Long term I would like to get rid of the numerous cmXX10 fonts and replace them by the monolithic Latin Modern Math font, which should avoid all these problems.

**Comment by ehremington** [comment]
This also happens with the xkcd plotting style using the "Humor Sans" font.

`x = np.linspace(0,10,20)
y = 2*x-3

with plt.xkcd():
    fig = plt.figure()
    ax = fig.add_subplot()
    ax.plot(x,y)`

**Comment by adiazmont** [comment]
I was able to get rid of the RuntimeWarning by declaring the font usage with:

`plt.rcParams["font.serif"] = "cmr10"`

Hence:

```
import matplotlib.pyplot as plt
plt.rcParams["font.serif"] = "cmr10"
fig, ax = plt.subplots()

ax.set_title('This is a special font:')
ax.set_xlabel(r'This is the default font $\alpha\beta\gamma$')
ax.set_yticks([-1, 0, 1])
plt.show()
```

![tmp1](https://user-images.githubusercontent.com/25737272/93820322-feb01500-fc2a-11ea-84b4-73c1a3a4ae7b.png)

And, it continues to work despite the declaration of the yticks, as in:

```
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams["font.serif"] = "cmr10"
fig, ax = plt.subplots()

ax.set_title('This is a special font:')
ax.set_xlabel(r'This is the default font $\alpha\beta\gamma$')
ax.set_yticks(np.arange(-1, 1.25, 0.25))
plt.show()
```
![tmp2](https://user-images.githubusercontent.com/25737272/93820429-27380f00-fc2b-11ea-91b9-2e4932ee7b7c.png)

Hope this helps!

**Comment by mayou36** [comment]
Are there any news on this?

**Comment by casperdcl** [comment]
just rebased #18397

**Comment by mayou36** [comment]
I find the same behavior with "Times New Roman".
