### ISSUE TITLE
Bug in 3D histogram documentation

### ISSUE THREAD

**Issue by TormodLandet** [matplotlib/matplotlib#1702]
The documentation on http://matplotlib.org/examples/mplot3d/hist3d_demo.html contains use of numpy.meshgrid, numpy.histogram2d and flatten. Meshgrid returns arrays of shape (ny, nx) while histogram2d returns arrays of shape (nx, ny). Thus, one or the other has to be transposed in order to use them all together after flatten (or flatten must be run with order='F' on one of the results)

**Comment by souravsingh** [comment]
I would like to work on the issue.How do I proceed?

**Comment by tacaswell** [comment]
@souravsingh Glad to hear you are interested in helping!  There is pretty extensive documentation at http://matplotlib.org/devel/index.html or more generally (with better pictures!) https://guides.github.com/introduction/flow/

the TL;DR is:

 - fork mpl on github
 - clone to your computer and add both _your_ remote and canonical upstream as remotes 
 - create a new branch on your computer
 - hack; commit; repeat
 - push your feature branch to _your_ gh fork of mpl
 - open Pull Request

You can then expect to have your code reviewed where we may ask you to make changes, then you

 - make and commit changes on your feature branch
 - push changes up to you gh fork of mpl

and there may be several cycles of this.  

Please feel free to ask any questions, we are a friendly project!
which will automaticaly attach them to the pull request

**Comment by discardthree** [comment]
Hi, I'm working on this one`1ttttttttttttttt

**Comment by discardthree** [comment]
Hi all,

I want to get a second opinion before I make a pull request that fixes this issue and also revises the example a bit.

This example bugs me because the bars have absolute size 0.5x0.5 and absolute positioning (offset (0.25, 0.25) from the bin's lower right corner) even though the bin size depends on the random data and will be smaller than 1x1.  This means bar placement will be a bit to the upper-right of the bin's center.  The difference isn't much to the naked eye, but if the goal is to help users understand how to use the histogram2d function then I think the current absolute positioning could lead people to misunderstand and think that bins have size 1 and we're placing bars in their centers.

There are two reasonable options in my opinion:
1. Make everything absolute: like [this](https://github.com/matplotlib/matplotlib/blob/9b9ed321ba4af06ea2fdcaaa9cbbf1026cacbba8/examples/mplot3d/hist3d_demo.py), but adding range=[[0, 4], [0, 4]] to the np.histogram2d call to give the bins fixed size 1.
2. Make everything relative: like [this](https://github.com/matplotlib/matplotlib/blob/c7945adca311f3cec8e04704aa6b1255f3cbd27c/examples/mplot3d/hist3d_demo.py), show how to scale bar sizes relative to bin sizes and center the bars in their bins.

Any opinions?

**Comment by tacaswell** [comment]
I lean towards option 1 because comparing between runs of the same code is
easier if bins are always the same size.

**Comment by discardthree** [comment]
Okay, I'll submit a pull request like that for now.
