### ISSUE TITLE
MaxNLocator(integer=True) doesn't treat percentages as integers with PercentFormatter(xmax=1)

### ISSUE THREAD

**Issue by MaxGhenis** [matplotlib/matplotlib#17113]
### Bug report

**Bug summary**

When plotting percentage data where 1 = 100% -- and denoting this by using `mpl.ticker.PercentFormatter(xmax=1)` -- `mpl.ticker.MaxNLocator(integer=True)` does not treat integer percentages (e.g. 10% i.e. 0.1) as integer. The y-axis is either left without integer axes or with unexpected integer axes like only labeling 0% and 100%. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import matplotlib as mpl

def plot(data, xmax):
    plt.plot(data)
    ax = plt.gca()
    ax.yaxis.set_major_formatter(mpl.ticker.PercentFormatter(xmax=xmax))
    ax.yaxis.set_major_locator(mpl.ticker.MaxNLocator(integer=True))
    plt.show()

plot([0.1, -0.1], xmax=1)  # Example 1: noninteger percent ticks
plot([1.1, -0.1], xmax=1)  # Example 2: ticks only at 0% and 100%
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/6076111/79089277-708a4700-7cfa-11ea-93ae-44f7538a92a8.png)
![image](https://user-images.githubusercontent.com/6076111/79089280-73853780-7cfa-11ea-8b75-e0cd5a467316.png)

**Expected outcome**

Expected results can be produced by multiplying the input by 100 and using `xmax=100`:
```
plot([10, -10], xmax=100)  # Example 1
```
![image](https://user-images.githubusercontent.com/6076111/79089266-66684880-7cfa-11ea-957a-8c0b4546d629.png)
```
plot([110, -10], xmax=100)
```
![image](https://user-images.githubusercontent.com/6076111/79089274-6cf6c000-7cfa-11ea-80ff-c0ca91a139f8.png)

**Matplotlib version**

  * Operating system: Linux
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.6.9
  * Jupyter version (if applicable): 5.2.2
  * Other libraries: 

Installed/loaded matplotlib from Google Colab ([here's my notebook](https://colab.research.google.com/drive/1aLWWWKn1x43hEjpbPiae6J2EzH3UcDvL)).

**Comment by jklymak** [comment]
The locator doesn’t know anything about the formatter so it has no idea you want to plot integer percentages.

**Comment by MaxGhenis** [comment]
OK, if that's impossible, would an `xmax` arg to the locator be possible/worthwhile?

**Comment by dstansby** [comment]
I think this is all expected behaviour; if you want integer percentages, then I think you need to use `MutlipleLocator(base=0.01)`, since 0.01 = 1%. I hope that helps - since the behaviour seems to be as documented - if I've missed something, or my proposed solution doesn't work, feel free to leave a comment or re-open the issue.

**Comment by tacaswell** [comment]
The formatter does not change / rescale your data it only determines how the tick labels are formatted.  

To Matplolib in the first case your data is still `[0.1, -0.1]` and in the second `[1.1, -0.1]`. This is the context in which the locator is picking ticks.  A further complication is that the `MaxNLocator` will ignore the `integer=True` flag if it can not find at least 2 ticks (this number is configurable)  (see https://matplotlib.org/api/ticker_api.html?highlight=maxnlocator#matplotlib.ticker.MaxNLocator) because it would be much worse to give you _no_ ticks in the first case (because the total ylimit does not span an integer).  In the second case it can put ticks at 0 and 1 so it goes with that (which in turn get formatted as 0% and 100%).


If you use

```python
ax.yaxis.set_major_locator(mpl.ticker.MaxNLocator(steps=[1, 5, 10]))
``` 

You will (so long as you don't zoom in too far) you will get only integer percentages.

**Comment by MaxGhenis** [comment]
Thanks, `MaxNLocator(steps=[1, 2, 5, 10])` gave good results for both:
```
def plot_steps(data, xmax):
    plt.plot(data)
    ax = plt.gca()
    ax.yaxis.set_major_formatter(mpl.ticker.PercentFormatter(
        xmax=xmax, decimals=0))
    ax.yaxis.set_major_locator(mpl.ticker.MaxNLocator(steps=[1, 2, 5, 10]))
    plt.show()

plot_steps([1.1, -0.1], xmax=1)
```
![image](https://user-images.githubusercontent.com/6076111/87269345-c7322900-c481-11ea-930f-b1596cbbcdf3.png)
```
plot_steps([0.1, -0.1], xmax=1)
```
![image](https://user-images.githubusercontent.com/6076111/87269354-cbf6dd00-c481-11ea-88a5-894bf5ba0162.png)
