### ISSUE TITLE
ipython autocomplete does not work for plt.figure()

### ISSUE THREAD

**Issue by mxposed** [matplotlib/matplotlib#17190]
### Bug report

With the default setup for IPython or jupyter notebook, autocomplete for `plt.figure()`, `plt.subplots()` and probably other methods shows nothing.

```python
# In IPython
import matplotlib.pyplot as plt
plt.figure().<press tab>
```

**Code for reproduction**

Programmatic way to get completion items:
```python
import matplotlib.pyplot as plt
import jedi
print(jedi.Interpreter('plt.figure().', [globals()]).completions()[:5])
```

**Actual outcome**

```python
[]
```

**Expected outcome**

```
[<Completion: add_artist>, <Completion: add_axes>, <Completion: add_axobserver>, <Completion: add_callback>, <Completion: add_gridspec>]
```

**Get it working with current version**
```python
import matplotlib.pyplot as plt
import jedi
fig = plt.figure()
print(jedi.Interpreter('fig.', [globals()]).completions()[:5])
```

In this [issue](https://github.com/jupyter/notebook/issues/2435#issuecomment-615995740) @davidhalter figured out that `jedi` cannot interpret the current return type of `plt.figure()` from its docstring.

**Matplotlib version**

  * Operating system: MacOS 10.13.6
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.1
  * Jupyter version (if applicable):
  * Other libraries: ipython=7.13.0 jedi=0.17.0

This is anaconda python installation with packages upgraded with pip

**Comment by timhoffm** [comment]
The notation is standard Sphinx with the [default role](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-default_role) set to `py:obj`. I therefore claim that this is rather an issue on the Jedi side and the format should be supported there. We‘ve intentionally chosen that default role because it leads to better readability of the plain text docstrings.

**Comment by davidhalter** [comment]
@timhoffm I kind of understand.

However I intentionally opted out of "parsing" more of those strange docstring formats. People should be using annotations for specifying types IMO, because that makes it possible to interact with the types easily for everyone. 

It's hard to reason about `figure()` and how it behaves if you only read the code. IMO annotations help a lot with these kind of cases. Docstrings are then just for descriptions and not types.

And no, I'm not advocating to use annotations everywhere. I think that's usually pretty annoying. But if you specify the types anyway - especially return types, annotations are great!

**Comment by timhoffm** [comment]
@davidhalter Thanks for the response. I have to consider what that means for us. As it seems you support at least some from of return format. Do you know from the top of your head what the problem is with 

~~~
    Returns
    -------
    `~matplotlib.figure.Figure`
~~~

Is it the default role, the `~`, the missing parameter name or using a formatted value at all?

**Comment by davidhalter** [comment]
It might be all of it :) I'm pretty sure though that `matplotlib.figure.Figure` would work and `Figure` (which you used a few versions ago) would also work.

Is it not an option to use annotations for this?

**Comment by timhoffm** [comment]
Well have Annotations in the upcoming matplotlib 3.8 release.
