### ISSUE TITLE
How to report bugs in the documentation?

### ISSUE THREAD

**Issue by myRandomFiles** [matplotlib/matplotlib#17320]
I tried to report a bug in the documentation, but the report was called "off topic" and was [closed](https://github.com/matplotlib/matplotlib/issues/17317). Why should documentation be a second class entity in open source software? It isn't second class in emacs.

**Comment by jklymak** [comment]
You did not specify a bug or make a specific documentation suggestion.   You asked for guidance that was more appropriate to other forums.  If as part of that process you decide there is a specific issue that would be suitable for the bug tracker.

**Comment by myRandomFiles** [comment]
I'm not asking for help here. I understand you don't want to do that here. Still, my original thread describes my difficulty figuring out how to control sizes in matplotlib from the documentation. Here's a blog from someone I don't know, and he's also calling it "difficult" to learn how to control sizes in matplotlib. This other person independently arrived at the conclusion that the matplotlib documentation is lacking:

> The example above is full, working, code, and should honestly probably be part of matplotlib: generally speaking, when I set the size of a figure, I intend to set the actual size of the figure, not the size of the plot with some minimal padding around it. In any case, hopefully this code is helpful to you!

**Comment by jklymak** [comment]
The counterpoint is as someone wrote in the comments of that blog post (not me):

> You say "Setting the actual size of figures in matplotlib.pyplot is difficult." That's simply plain wrong. The size of figures is easily set with `figsize` and `dpi` arguments. E.g. with figsize=(5,4), dpi=100 you get a 500x400 pixel figure out. You can use `fig.tight_layout` or `contrained_layout` to distribute the space *within* the figure better. 
What you should by no means do is to use the `bbox_inches="tight"` option, because that will change the figure size. It's hence the inverse of what you want. 
So what this article here does is working around a problem that doesn't actually exist. I would propose to detele it, because it's utterly confusing for people.

On Stackoverflow, I told you how to precisely set the size of an axes using `figure.add_axes` (https://matplotlib.org/3.2.1/api/_as_gen/matplotlib.figure.Figure.html#matplotlib.figure.Figure.add_axes).  If you don't want an axes, you can easily make the axes the size of the figure with `add_axes([0, 0, 1, 1])`.  If your confusion is coming in because you are using the inline backend in Jupyter, thats because it uses `bbox_inches='tight'`   Use `%matplotlib notebook` backend instead and you won't have this behaviour.

**Comment by myRandomFiles** [comment]
Where is "backend" documented? Not here:

https://jupyterlab.readthedocs.io/en/stable/search.html?q=backend&check_keywords=yes&area=default

**Comment by jklymak** [comment]
I was referring to this:  https://stackoverflow.com/questions/61553855/python-plotting-module-allowing-control-over-plot-area/61554607#61554607   

If you don’t know what a backend is, then you should start here:  https://matplotlib.org/3.2.1/tutorials/introductory/usage.html

Or more likely you want something more low level than Matplotlib.

**Comment by story645** [comment]
>Still, my original thread describes my difficulty figuring out how to control sizes in matplotlib from the documentation. 
Hi, reading through your original post, it sounds like the trouble is that our [TOC](https://matplotlib.org/3.2.1/contents.html) is pretty unfriendly and I totally agree that it could be better. Like @jklymak mentioned, the [tutorials](https://matplotlib.org/3.2.1/tutorials/index.html) are a much better place to start to understand the features of the library. Do you have suggestions on how we can make that clearer to users like yourself? And maybe on how we can improve our TOC? 

For an interactive jupyterlab application, you're going to want to use [jupyter-matplotlib](https://github.com/matplotlib/ipympl) rather than notebook. It's an external backend so you will have to install it separately - instructions are on their site, but it is far more responsive. 

If you want a very primitive but still Jupyter based plotting library, https://ipycanvas.readthedocs.io/en/latest/ might do the trick.

**Comment by myRandomFiles** [comment]
Thank you for the ipycanvas recommendation. Primitive sounds ideal for my current needs.

I'd found your Usage Guide when I first used matplotlib for plotting graphs, but I skipped the Backend section because it looked unnecessary for regular graph-plotting. Now that I needed that info, I didn't find it until @jklymak jklymak linked above (thank you).

When I look under Documentation : User's Guide, the Credits, License, History, What's New, and Github Stats get the most real estate, but is that what most users are looking for most of the time?

Since the tutorials are so important, maybe a textual TOC for the tutorials that takes less time to scroll through?

![TOC](https://user-images.githubusercontent.com/60956662/80938328-8df88100-8d8d-11ea-9a5e-1948541572e5.png)

Tutorials are a better place to start, but the tab to them follows the tab for Examples.

Hyperlinked cross-references, from the Usage Guide into the Tutorials and from the Tutorials back to the Usage Guide, so the documentation is friendly to people who don't read documentation from beginning to end and retain it all photographically. Matplotlib is extensive, so the docs should work efficiently for people who need just some features not all. Make it easy for beginners and occasional users to find the parts they need without having to memorize it all.

I was just on a page titled "Gallery", and I'm wondering how I got there, and then I say that the Gallery tab is called Examples. Two different words why not use the same word in both places?

Those suggestions I just blurted out, after I was about to say I'm too tired to answer your question. Off the top of my head.

**Comment by tacaswell** [comment]
This is the correct to report bugs, however your original issue was correctly closed.  I understand you meant it to be a bug report, but it reads as a request for help implementing a specific application (with some generalized expression of frustration -- which is a valid feeling! Learning new languages and libraries can be hard) which is better handled through SO or https://discourse.matplotlib.org .

Thank you for your critique of the documentation.  We are well aware of the limitation of the documentation and have discussed all of the things you have suggested previously.  However, the gap between acknowledging that we need to better organize the documentation and actually re-organizing it is substantial amount of work.

I am going to close this issue as there is nothing actionable here.  @myRandomFiles If you have concrete suggestions about the organization please open a new issue or PR.

----

@myRandomFiles as you seem to be new to the open source world, please keep in mind that almost everyone who works on these projects is a volunteer.  Just like [jupyter](https://github.com/jupyterlab/jupyterlab/issues/8337) we expect you to engage with us in a constructive non-abusive manner.

**Comment by myRandomFiles** [comment]
"Learning new languages and libraries can be hard"

Thanks for the condescending lecture, but [you have nothing to teach me about learning new languages or libraries](https://www.dropbox.com/s/uep199c73diec2z/Stanford%20Transcript.pdf?dl=0).

I'm someone who keeps documentation bug-reports open until the document bugs are fixes. You're someone who closes bug reports before the bugs are fixed. You have nothing to teach me about software.
