### ISSUE TITLE
svg output not accurate

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#17421]
When plotting two circles that _touch_, `plt.show()` does the right thing, but saving the scene as SVG makes the two circles overlap. It's more or less visible, and crucial for my application
```python
import matplotlib.pyplot as plt

circ = plt.Circle((-1, 0), 1, color="C0", alpha=0.5)
plt.gca().add_artist(circ)
circ = plt.Circle((+1, 0), 1, color="C0", alpha=0.5)
plt.gca().add_artist(circ)

plt.xlim(-2, 2)
plt.ylim(-1, 1)
plt.gca().set_aspect("equal")

# plt.show()
plt.savefig("out.svg")
```
Good (`show`):
![zoom1](https://user-images.githubusercontent.com/181628/82067330-e1919580-96d0-11ea-91bd-e2dba12f8394.png)

Bad (`savefig`):
![zoom2](https://user-images.githubusercontent.com/181628/82067285-cb83d500-96d0-11ea-8fe1-b95a8ea21c98.png)

**Comment by ImportanceOfBeingErnest** [comment]
Patches by default have a linewidth of 1 pt (determined by the `rcParams['patch.linewidth']`; hence the patch will be 0.5 pt larger on either side.
Options are:
* remove the edgecolor,  `facecolor="C0", edgecolor="none"`
* set the linewidth to 0, `color="C0", linewidth=0`

You can help us here by identifying where in the documentation you would have expected to learn about this.

**Comment by nschloe** [comment]
At first glance, there seems to be a discrepancy between the interactive window and the svg. Do I see it correctly that:
   * in the interactive window, `0.5pt` means 0.5pt on the screen, no matter the zoom level (and hence the overlap is never actually visible)
   * in the SVG, the overlap is 0.5 in the current view, and when zooming in, it naturally increases?

It'll be hard to find one single point where to put this information I think.

**Comment by tacaswell** [comment]
Every time you zoom in on an interactive figure we re-render and make the line width 0.5pt (which more-or-less means a fixed width in pixels).   Because we re-draw on zoom the ratio between the size of the figure on the screen and the size of the figure in it's own internal scales is (tautologically) fixed (to the effective dpi which is either `figure.dpi` or `figure.dpi * 2` depending on your monitor.  If you set the dpi to match your screens physical dpi you should be able to set the size of the figure and then hold up a ruler to the screen and have it be correct, but I digress).

In the case of an svg viewer the Figure has a fixed size so when you zoom in the ratio between the size of the figure on the screen and figures internal scale is changing so as you zoom in lines look "wider".

Another way to think of this is that when you zoom in on a SVG you are changing the dpi not the dimensions.  It looks bigger to you, but everything is scaled.
