### ISSUE TITLE
plt.imshow() doesn't show proper image for numpy masked array for matplotlib 3.2.1 version

### ISSUE THREAD

**Issue by awsaf49** [matplotlib/matplotlib#17430]
I am facing this problem for matplotlib version 3.2.1 in python 3.7. Installing older version is solving the problem but latest still has this problem. please have a look in this link
https://stackoverflow.com/questions/61816602/plt-imshow-doesnt-show-proper-masked-arraynp-ma-masked-where/61834826#61834826

**Comment by jklymak** [comment]
That srackoveeflow question is too short on detail for us to definitively help.  However my guess would be that you need to set interpolation=“none” in your call to imshow.  We changed the default in 3.2

**Comment by awsaf49** [comment]
It's working now. Thank you very much

**Comment by tacaswell** [comment]
This is likely due to switching to the improved anti-aliasing interpolation.  I suspect that the features are actually quite small and we were artificially expanding them with "nearest".

@awsaf49 In the future please always paste the code as text (rather than as screen shots) and if possible please make the code a minimally runable example which will reproduce the problem.

**Comment by awsaf49** [comment]
You were right, the features were very small and for a large image, it was
working just fine. I could've pasted the code but without the data,
the audience won't be able to reproduce the result that's why I gave the
screenshot.

**Comment by tacaswell** [comment]
It is best if you can also provide representative data.  This issue is likely not dependent on the data being of an eye, but could be reproduced by a sparse numpy array.

There is never a case where I would rather see a screen shot than the code as text (even if you can not provide code to generate synthetic data) and I strongly suspect that is the consensus view of the people who are likely to be able to help you.
