### ISSUE TITLE
AttributeError: module 'dateutil' has no attribute '__version__' when importing Matplotlib

### ISSUE THREAD

**Issue by khmira** [matplotlib/matplotlib#17433]
### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
import matplotlib.pyplot as plt
```

**Actual outcome**

```
# If applicable, paste the console output here
runfile('C:/Users/Khmira/Desktop/Projet_S2/ML database/data csv/projet.py', wdir='C:/Users/Khmira/Desktop/Projet_S2/ML database/data csv')
Traceback (most recent call last):

  File "C:\Users\Khmira\Desktop\Projet_S2\ML database\data csv\projet.py", line 11, in <module>
    import matplotlib.pyplot as plt

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 205, in <module>
    _check_versions()

  File "C:\ProgramData\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 200, in _check_versions
    if LooseVersion(module.__version__) < minver:

AttributeError: module 'dateutil' has no attribute '__version__'
```

**Expected outcome**

**Matplotlib version**

  * Operating system:
  * Matplotlib version: 
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by tacaswell** [comment]
This appears to be an installation issue (as dateutil is a third-party package that should have `__version__` if it is installed correctly).

I am going to close this as I do not think there is anything we can do on the Matplotlib side, if you can can not resolve your installation issues on your own, please create a post at https://discourse.matplotlib.org/c/community/install/13.  Make sure to include the same information we asked for here about your system and how you installed Python / Matplotlib so that we can give you advise that is relevant to your system.

**Comment by Master-Pr0grammer** [comment]
For anyone else with this problem, I was able to 'hack' it by going to the source of the raised exception, and commenting it out.

It worked for me, but this also might not work for everyone because this section of the code is what checks for compatibility issues, and its not an ideal solution anyways.
