### ISSUE TITLE
Jupyterlab dark theme compatibility problem

### ISSUE THREAD

**Issue by abcam** [matplotlib/matplotlib#17549]
### Bug report

When using twinx and adjusting the label colours on the y scales in jupyterlab with dark theme the labels and ticks disappear.

**Code for reproduction**

```python

import numpy as np
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

x = np.linspace(0, 10, 10)

y1 = np.linspace(0, 10, 5)

y2 = np.linspace(80, 100, 5)

ax.plot(x[:5], y1, '^-', color = 'C1')

ax1 = ax.twinx()
ax1.plot(x[5:], y2, 'o--', color = 'C0')

ax.minorticks_on()
ax1.minorticks_on()

ax1.set_ylabel('Label')
ax.set_ylabel('Label')

ax.tick_params(axis = 'y', labelcolor = 'C1')
ax1.tick_params(axis = 'y', labelcolor = 'C0')

plt.show()
```

**Actual outcome**
![image](https://user-images.githubusercontent.com/64583949/83417012-6b539980-a419-11ea-980f-ea6c844e493b.png)

**Expected outcome**

![image](https://user-images.githubusercontent.com/64583949/83417568-2d0aaa00-a41a-11ea-8137-1bbe9361cdc7.png)
With the axis tick labels coloured as in the above.

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 3.2.1
  * Matplotlib backend: module://ipykernel.pylab.backend_inline
  * Python version: 3.7.7
  * Jupyter version (if applicable): jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.3
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.1.3
jupyter lab      : 2.1.1
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
  * Other libraries:

**Comment by timhoffm** [comment]
This was discussed in https://github.com/jupyterlab/jupyterlab/issues/4172 marked resolved via https://github.com/jupyterlab/jupyterlab/pull/5232. However, I don't think that's a good solution because it shares rendering responsibility between matplotlib and jupyterlab. The figure has a transparent background and jupyterlab draws as theme-matching background behind that. This can lead to badly readable or vanishing plot elements as described in this issue.

IMHO the image should not have any transparencies (https://github.com/jupyterlab/jupyterlab/issues/4172#issuecomment-372307454) - This would be a responsibility of the inline backend, which belongs to ipython, not matplotlib itself.

As a workaround, you can set a figure background; for an individual figure:
~~~
fig.patch.set_facecolor('white')
~~~
or for all figures, using configuration settings:
~~~
plt.rcParams['figure.facecolor'] = 'white'
~~~

**Comment by jklymak** [comment]
Thanks @timhoffm 

@abcam I don't think there is anything we can do from our end, so I'll close.  But feel free to request a re-open if you really think this is a matplotlib actionable issue.

**Comment by abcam** [comment]
Thank you both

**Comment by Psp29onetwo** [comment]
I found one solution for expanding the plot canvas a bit so that x and y ticks will get visible.

You need to add one line `plt.style.use('default')` after importing the matplot lib module in notebook.


<img src="https://i.stack.imgur.com/eIc32.png">

See my ticks are outside the canvas before.

<img src="https://i.stack.imgur.com/Yd7LZ.png">

After adding the line the tick got added to the canvas itself no further modification was needed.

<img src="https://i.stack.imgur.com/jNeEg.png">

As you can see in the above image this will pull the x and y ticks in the canvas to make it visible without changing or modifying ticks or plot color, it will make it easier to collaborate your work with others.


  [1]: https://i.stack.imgur.com/eIc32.png
  [2]: https://i.stack.imgur.com/Yd7LZ.png

**Comment by timhoffm** [comment]
`plt.style.use('default')` is essentially `plt.rcParams['figure.facecolor'] = 'white'`. As discussed above jupyterlab sets the background color to transparent. Both of the above set it back to white (the style does more though).
