### ISSUE TITLE
Inconsistent argument handling for plot_date()

### ISSUE THREAD

**Issue by grap3-fru1t** [matplotlib/matplotlib#17548]
**Pyplot doesn't use a lineplot by default**

Pyplot is using a scatterplot by default when no arguments are applied. 

```python
import pandas as pd
import matplotlib.pyplot as plt

d = {'dates': ["2019-05-16", "2019-05-19", "2019-05-23"], 'value': [8281, 8193, 7998]}

df = pd.DataFrame(data=d)

x_value = df['dates']
y_value = df['value']

plt.plot_date(x_value, y_value)
plt.gcf().autofmt_xdate()
plt.show()
```

The code above produces the following output:
![grafik](https://user-images.githubusercontent.com/52132296/83413327-ec139500-a41b-11ea-8516-39576beda109.png)

**Scatterplot changes to lineplot when color changes**
When changing one of the arguments, e.g. the color, the scatterplot changes to lineplot automatically.
When using ``` plt.plot_date(x_value, y_value, 'r') ``` instead, the output produces a lineplot, although the line style '-' was not used as an argument:
![grafik](https://user-images.githubusercontent.com/52132296/83413256-d7cf9800-a41b-11ea-8468-936c9f997d54.png)

**Matplotlib version**

  * Operating system: Windows 10
  * Matplotlib version: 3.0.2
  * Python version:3.7.2

Matplotlib installed from pip.

**Comment by timhoffm** [comment]
This is a special quirk of the `plot_date()` function, which defines it's own format default.

Essentially, that function is obsolete because regular matplotlib plotting functions (in particular also `plot()`) natively support dates. And I advise to use these instead.

**Comment by mwaskom** [comment]
I think it's useful to be clear about what the actual issue is here ... the third parameter in `plot_date` isn't `color`, it's `fmt`. The inconsistency is in the default value (`"-"` for `plot` and `"o"` for `plot_date`), but `plt.plot(x, y, "r")` does the same thing as `plt.plot_date(x, y, "r")`, and `plt.plot(x, y, "ro")` likewise matches `plt.plot_date(x, y, "ro")`.

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/pull/14614 re whether these foo_date functions should be deprecated (I still think they should, but I don't really want to relitigate the discussion here).

It wouldn't be "too hard" to emit a warning if people call plot_date without a third argument, telling them that the default fmt will change, and later change the default fmt to "-" to match plot()... just some boring code churn.

**Comment by timhoffm** [comment]
@anntzer AFAICS #14614 is about ?axis_date not about plot_date.

**Comment by anntzer** [comment]
I know, but I would say most arguments are similarly applicable.

**Comment by timhoffm** [comment]
IMHO the hesitation to accept #14614 is based on usecases for ?axis_date outside of plot.

> The usecase of `ax.xaxis_date()` is clearly not a usual line `plot`, but rather one of the cases where matplotlib does not automatically convert dates, e.g. a `LineCollection`, box plots, a `PolyCollection`s, or candlestick diagrams etc. 

I don‘t see a case where plot_date has any real benefit. In contrast, it has some downsides:

- the above API inconsistency
- it does not work for 3D
- The paradigm of having a special function for a datatype is different from all our other plot API. We define functions for different kind of plots, not different kinds of data.

**Comment by jklymak** [comment]
The benefit was outlined in @efiring posts: many folks carry dates around as floating point and having a way to easily add date locators and formatters to floating point is what plot_date does.  It also does other things like rotate the labels etc. I’m not sure I like it, but asking folks to do the whole locator formatter dance is a bit harsh.

**Comment by timhoffm** [comment]
(@jklymak I took the liberty to add the link to the post.)

I acknowledge the case of plain float dates (even though I ask myself how common that really is). In the end
~~~
ax.plot_date(x, y)
~~~
is equivalent to
~~~
ax.plot(x, y)
ax.xaxis_date()
~~~

I'd much rather use the latter because of its clarity. If we had just the latter (I hope) we would never add the former as a convenience shortcut. IMHO the only reason `plot_date()` could stay is for backward compatibility. But even then I'd recommend to add a note and discourage its use in favor of the latter.

**Comment by jklymak** [comment]
Closing as won't fix...
