### ISSUE TITLE
Interactive mode not working inside ipdb

### ISSUE THREAD

**Issue by onnoeberhard** [matplotlib/matplotlib#17577]
### Bug report

Hi, I am trying to use the interactive mode for plotting from an ipython debugger session. When I execute a `plot` command, I expect a window with the plot to pop up. However, even though something happens, nothing is plotted: on Windows, I just get a "Not responding" window and on Mac OS an icon appears in the dock but no window shows up.

**Code for reproduction**
```python
In [1]: %pdb
Automatic pdb calling has been turned ON

In [2]: raise Exception()
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-32c500991385> in <module>
----> 1 raise Exception()

Exception:
> <ipython-input-2-32c500991385>(1)<module>()
----> 1 raise Exception()

ipdb> import matplotlib.pyplot as plt
ipdb> plt.ion()
ipdb> plt.plot(1)
[<matplotlib.lines.Line2D object at 0x113505110>]
ipdb> # Did not work (even if I call plt.show() now)
```
 
The followling works no problem:
```python
In [3]: import matplotlib.pyplot as plt

In [4]: plt.ion()

In [5]: plt.plot(1)
Out[5]: [<matplotlib.lines.Line2D at 0x11ac2a750>]

In [6]: # This worked
```

**Matplotlib version**

  * Operating system: Mac OS 10.15.4
  * Matplotlib version: 3.1.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.7.6
  * Jupyter version (if applicable): IPython 7.13.0
  * Other libraries: -

**Comment by timhoffm** [comment]
On linux, a window is shown, but without content being generated.

Without looking into the details: The interactive mode needs a running event loop, and I assume that pdb holds up program execution so that the event loop does not spin.

**Comment by tacaswell** [comment]
This is expected because in the debugger the input hook is not active and nothing is spinning the event loop.  See https://matplotlib.org/devdocs/users/interactive.html and https://matplotlib.org/devdocs/users/interactive_guide.html for details of what is going on here.

See the discussion at https://github.com/ipython/ipykernel/pull/438 for work on fixing this.

**Comment by tacaswell** [comment]
I'm going to close this because it is properly fixed on the IPython side of things.

**Comment by felipeespic** [comment]
This issue still persists. I miss those days when Matplotlib and IPython were flawlessly working integrated. It lasted until IPython 7.7.

**Comment by tacaswell** [comment]
I just verified that at least with IPython in the terminal and tkagg, doing `plt.show(block=True)` in ipdb works as expected (figures are live, but the prompt is blocked until all the windows are closed) as does `plt.pause(N)` (which blocks the prompt and gives you live figures for `N` seconds).

The integration that is failing is not Matplotlib/IPython, it is the integration between the text prompt and the GUI toolkits.  I have not checked, but I suspect that this is a result of the change from IPython using `readline` to prompttool kit.  In the case of readline the same intput hooks are used for both the "normal" and "debug" prompts so that there was always something spinning the GUI event loop while waiting for human input.   The linked pr is for ipykernel which is a bit more complicated because there is a network connection involved.  I _suspect_ that there is an easy way to turn on the inputhook for the terminal debugger, but am not sure.  If this is a critical functionality for you @felipeespic and the blocking solutions above are not enough that is where I suggest you investigate.

**Comment by felipeespic** [comment]
Actually I just realised that it works without issues if using **pdb** instead of **ipdb**. So, there is something wrong only in **ipdb**. I would have expected that the way they handle input hooks was similar, but it seems it's not the case.

**Comment by palbarede** [comment]
> Actually I just realised that it works without issues if using **pdb** instead of **ipdb**. So, there is something wrong only in **ipdb**. I would have expected that the way they handle input hooks was similar, but it seems it's not the case.

There seems to be some confusion between pdb and ipdb.   If you found a solution to exposed bug, thank you for explaining.
