### ISSUE TITLE
Plot directive may be confused by ..include::

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#17860]
### Bug report

In our docs, we have `users/whats_new.rst` that does `.. include:: prev_whats_new/whats_new_3.3.0.rst`.

For any `plot` directives, this latter file creates files like `build/plot_directive/users/prev_whats_new/whats_new_3-3-0-*.*`. Somehow this also gets copied to `build/plot_directive/users/whats_new-*.*`. Then in the final docs (in `build/html`), this ends up in coming from `_images/whats_new-*.*`. I don't really understand why that third copy is made, since the other two still exist in `build/html`, but whatever.

The problem occurs when you update plots in `whats_new_3.3.0.rst`. Only the first image is updated, and nothing is copied to the second or third locations.

**Matplotlib version**

  * Operating system: Fedora 31
  * Matplotlib version: master (actually, head of #17858)
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.7.6
  * Other libraries: Sphinx 3.1.2

**Comment by QuLogic** [comment]
I think this pretty self-contained to the sphinx extension code only, so should be a good first issue. However, since it requires understanding sphinx it's at least medium difficulty.

**Comment by yongrenjie** [comment]
I had a brief go at this and made a PR. The basic strategy is to check modification times of included files as well as the original source files. There are a couple of ways to get the included files:

**Method 1**

Since docutils 0.17, there is an attribute `state.document.include_log` which is a list of tuples containing the names of any files that were included, which is exactly what we want.

```
[('index.rst', (None, None, None, None), 4.611686018427388e+18),
 ('included.rst', (None, None, None, None), 21)]
```

**Method 2**

Directly inspect `state_machine.input_lines.items`, which is a list of tuples `(source, offset)`. If a RST file is included, then we can get its filename (relative to the top-level Sphinx directory) in `source`. For example, this is what `plot_directive` can when I place `.. include:: included.rst` inside the file `~/test/plot_dir/index.rst`:

```
[('included.rst', 2),
 ('included.rst', 3),
 ('included.rst', 4),
 ('included.rst', 5),
 ('included.rst', 6),
 ('included.rst', 7), 
 ('included.rst', 8),
 ('included.rst', 9),
 ('included.rst', 10),
 ('included.rst', 11),
 ('included.rst', 12),
 ('internal padding after included.rst', 13),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 7),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 8),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 9),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 10),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 11),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 12),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 13),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 14),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 15),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 16),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 17),
 ('/Users/yongrenjie/test/plot_dir/index.rst', 18)
]
```

The issue with this is that there's the 'internal padding after...' line which we would have to filter out, and I'm not sure what other directives (if any) might also add some junk to this list. I got around this by first removing duplicates and then checking which of the entries were valid files.

I feel like Method 2 is a bit fragile, so I made it as a fallback:

```
try:
    # method 1...
except AttributeError:    # indicates docutils <=0.16
    # method 2...
```

I've tested this all the way back to docutils 0.14 and it seems to be pretty reliable.
