### ISSUE TITLE
Set mathtext.fontset per element

### ISSUE THREAD

**Issue by isentropic** [matplotlib/matplotlib#17906]
How can we set [mathtext font](https://matplotlib.org/3.2.1/tutorials/text/mathtext.html) without manipulating RC per [Text](https://matplotlib.org/3.2.2/api/text_api.html#matplotlib.text.Text) element. Text objects cannot take in this parameter, as apparently the only way to set `"mathtext.fontset"="Serif"` is to make it global (not per some Text element).

**Comment by isentropic** [comment]
The only way is to set it globally according to [docs](https://matplotlib.org/3.1.1/tutorials/text/text_props.html#default-font)

**Comment by isentropic** [comment]
[This](https://matplotlib.org/3.1.1/tutorials/text/mathtext.html#mathtext-fonts) does not help a lot too

**Comment by timhoffm** [comment]
AFAICS this is a global setting that cannot be modified per `Text` element. ping @anntzer

**Comment by isentropic** [comment]
This would be a very useful feature for packages using matplotlib as a backend. For example at JuliaPlots/Plots.jl we have user settable fonts per every plot element, hence mathfont should also change per each element.

**Comment by anntzer** [comment]
I don't think it should be "particularly" hard to add a per-Text property to set this (I guess we can't really reuse FontProperties for that because they are not precise enough for mathtext); as usual someone needs to give it a try :)

**Comment by timhoffm** [comment]
**👉 Things to do:**

- Find the (only) usage of `rcParams['mathtext.fontset']` in `MathTextParser.parse()`.
- Trace the call hirachy back to find out how a `Text` rendering finally calls `parse()`.
- Add a parameter to define the font for Text objects.
- Pass this parameter down the call hirachy so that is can be used in `parse()`
- Check that the parameter can be passed from relevant functions such as `Axes.title()` and `Axes.text()` (This is likely the case because keyword arguments are passed).

**Comment by timhoffm** [comment]
Related: #6518.

**Comment by diegoleal** [comment]
While trying to solve this I realised that the fontset passed to rcParams is validated and the methods to make this validation are all private to the rcsetup.py and the __init__ from matplotlib.
I think the fontset used in a Text should have the same validations as if it were an rcParam, but I see no easy way of doing that.

If someone has a suggestion or want to discuss any change I made, feel free to contact me.
I am working on the problem here:
https://github.com/diegoleal/matplotlib/tree/issue%2317906

**Comment by timhoffm** [comment]
The topic of validator availability is still an open issue. Historically, validators were only used by the rcParams parser. But I agree that they can be useful in other parts of the library as well. We should solve this on a fundamental level from the library side. This needs careful consideration regarding import order. For now, you may import `_validators`. As long as the import of `_validators` is only within the library, it's ok-ish. The important aspect is that it's not public API for users of Matplotlib.
