### ISSUE TITLE
Confusing error message when home config directory not writable

### ISSUE THREAD

**Issue by trampgeek** [matplotlib/matplotlib#18011]
### Bug report

**Bug summary**

If matplotlib is run in an environment without a writable home directory, a very confusing error message is printed in which the configdir and the tempdir are interchanged. 

**Code for reproduction**

1. In Linux, create a user `someone` with no home directory. 
2. Run Python with a command like

    sudo -u someone python3

3. In the Python shell, type `import matplotlib`

**Actual outcome**

```
Matplotlib created a temporary config/cache directory at /root/.config/matplotlib because the default path (/tmp/matplotlib-9yoi7m8l) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
```

**Expected outcome**

```
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9yoi7m8l because the default path (/root/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
```

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): agg
  * Python version: 3.9.0b4
  * Jupyter version (if applicable): N/A
  * Other libraries: N/A

Matplotlib was compiled from source. The error is at line 482 in `__init__.py` at the root level in the source tree. The parameters are the wrong way round.

**Comment by YuantianGao** [comment]
I have the same issue, did you solve it?

**Comment by tacaswell** [comment]
@YuantianGao Yes, we fixed the order of the paths in #18014 and this should be fixed in all versions after 3.3.1.

**Comment by ttarabula** [comment]
Does anyone know if this warning message can be suppressed? If not, any chance there's interest in adding an environment variable to optionally suppress the warning?

something _like_ (but better named ;):
`diff --git a/lib/matplotlib/__init__.py b/lib/matplotlib/__init__.py
index 71afd3928d..01f8d15fab 100644
--- a/lib/matplotlib/__init__.py
+++ b/lib/matplotlib/__init__.py
@@ -481,13 +481,14 @@ def _get_config_or_cache_dir(xdg_base_getter):
     tmpdir = os.environ["MPLCONFIGDIR"] = \
         tempfile.mkdtemp(prefix="matplotlib-")
     atexit.register(shutil.rmtree, tmpdir)
-    _log.warning(
-        "Matplotlib created a temporary config/cache directory at %s because "
-        "the default path (%s) is not a writable directory; it is highly "
-        "recommended to set the MPLCONFIGDIR environment variable to a "
-        "writable directory, in particular to speed up the import of "
-        "Matplotlib and to better support multiprocessing.",
-        tmpdir, configdir)
+    if not os.environ.get("MPLNOCACHEWARN"):
+        _log.warning(
+            "Matplotlib created a temporary config/cache directory at %s because "
+            "the default path (%s) is not a writable directory; it is highly "
+            "recommended to set the MPLCONFIGDIR environment variable to a "
+            "writable directory, in particular to speed up the import of "
+            "Matplotlib and to better support multiprocessing.",
+            tmpdir, configdir)`

**Comment by jklymak** [comment]
You can filter logging module warnings as well: https://docs.python.org/3/library/logging.html
