### ISSUE TITLE
Document minimum supported OSX version for macos backend

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#18066]
See https://github.com/matplotlib/matplotlib/pull/17956 for discussion; we should document what the minimum version of OSX we support is, and communicate any changes to this in release notes as and when it is bumped.

**Comment by timhoffm** [comment]
Version info is currently held in theses two places. This should probably go somewhere there.

https://matplotlib.org/devdocs/users/installing.html#dependencies
https://matplotlib.org/devdocs/devel/min_dep_policy.html#list-of-dependency-min-versions

**Comment by QuLogic** [comment]
This would be good to know, so I can delete some code.

**Comment by dopplershift** [comment]
(Bringing this up because of #18128, but figured the discussion should be here.)

I'd say at this point we should document what's done in practice: currently to get full functionality, one needs to be running on >= macOS 10.11 ([~5 years old](https://en.wikipedia.org/wiki/OS_X_El_Capitan)). We also, by virtue of [using `@available`](https://stackoverflow.com/questions/46965347/objective-c-available-guard-anded-with-more-conditions) to check for availability of APIs, require XCode >= 9 ([~3 years old](https://en.wikipedia.org/wiki/Xcode#9.x_series)).

Looks like the closest we can get to that [on travis](https://docs.travis-ci.com/user/reference/osx/#macos-version) is using the `xcode9` image (`osx_image` key), which unfortunately uses macOS 10.12. That *should* be ok, since by virtue of #17956 we should at least error out if we unwittingly use newer APIs.

**Comment by jkseppan** [comment]
I would argue that we can only claim to support releases that we can run tests on. It seems that Travis CI has an XCode 9 environment running on macOS 10.12, and so does CircleCI (albeit only available on paid plans). Do we have other ways to run our tests? Perhaps even an occasional manual test run would suffice, since I think the MacOSX backend changes quite infrequently.

**Comment by jkseppan** [comment]
I'll just mention some anecdotes about macOS versions. When building in the Travis xcode9 environment, Homebrew prints the following warning:

> Warning: You are using macOS 10.12.
> We (and Apple) do not provide support for this old version.
> You will encounter build failures with some formulae.
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC. You are responsible for resolving any issues you
> experience while you are running this old version.

I had a laptop running 10.13, but recently iTerm2 dropped support so I had to upgrade to 10.14. It seems that I was subscribed to their beta release channel, as they still ship a stable version with support for 10.12 but the next version will drop that support.

AFAIK Apple doesn't really announce EOL for their OS versions, but looking at their security updates gives some clues: https://support.apple.com/en-us/HT201222. The last Safari version was released for 10.13 (High Sierra) and newer systems, and there were 15 July security updates for 10.13 and up. The last time there was an update for 10.12 (Sierra) was in September 2019, and the last time there was an update for 10.11 (El Capitan) was in July 2018.

**Comment by tacaswell** [comment]
We have a hosted mac-mini (and funding from NF to pay for it for 3 years).  Currently it is a 10.15, but it looks like we can have it re-imaged as far back to 10.7 (and by "re-image" the path may be to cancel it and order a new one with what ever version we want).  Poking at the interface I discovered the "manage team" settings and adding @jkseppan , @dopplershift , and @QuLogic as admins.

Through the same service we also have access to one of the Apple Silicon development kit.

**Comment by tacaswell** [comment]
And if anyone else wants access I think there are now 4 people who can add team members (but I guess I should only really volunteer my self to do support;) ) please ask.

If you make any changes please log them at  https://discourse.matplotlib.org/t/managing-macstadium-account-log/21437

**Comment by jkseppan** [comment]
I'm experimenting with building on 10.12/XCode 9 in #18134.

**Comment by jkseppan** [comment]
#18134 was merged, so now I think we could honestly claim that we support the MacOSX backend on MacOS 10.12 and XCode 9. The Travis builds are currently actually quite fast, but if we enable svg and pdf tests (#18140) they become slow again. Perhaps running those would be a good use for the MacStadium host.

As an aside: do we have high-level documentation on the CI setup? There are jobs being run on at least Travis CI, CircleCI, Appveyor and Azure Devops, probably with different parameters. I assume the point is to get wide coverage of different features on different platforms, but is there an overarching plan? If there is, I would like to update it to mention the recent change on Travis.

**Comment by dstansby** [comment]
I have opened a PR to document this and set the min requirement at 10.12: https://github.com/matplotlib/matplotlib/pull/22240. As far as I can tell we're not actually running travis tests any more, so we don't test on 10.12 now?

It seems like on:
- github actions the furthest we can go back is 10.15: https://github.com/actions/virtual-environments#readme
- azure pipelines the furthest we can go back is 10.15: https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software
- circleCI we might be able to go back further?: https://circleci.com/docs/2.0/xcode-policy/#macos-versions
