### ISSUE TITLE
3.3.0 regression in png backend with colorbar()

### ISSUE THREAD

**Issue by yuyichao** [matplotlib/matplotlib#18061]
### Bug report

**Bug summary**

With multiple subplots with one of them being a color plot with `colorbar()`, png backends emits significantly different image from everything else (qt5, pdf, svg). This was not the case in 3.2.2.

**Code for reproduction**

```python
import matplotlib
from matplotlib.pyplot import *
import numpy as np

matplotlib.rcParams['font.size'] = 20
matplotlib.rc('xtick', labelsize=15)
matplotlib.rc('ytick', labelsize=15)

figure(figsize=[12.6, 11.2])

subplot(2, 2, 1)
xlabel("XXX XXX")
ylabel("YYY YYY")
title("Title Title")

subplot(2, 2, 2)
xlabel("XXX XXX")
ylabel("YYY YYY")
title("Title Title")

subplot(2, 2, 3)
xlabel("XXX XXX")
ylabel("YYY YYY")
title("Title Title")

subplot(2, 2, 4)
def func3(x, y):
    return (1 - x / 2 + x**5 + y**3) * np.exp(-(x**2 + y**2))
dx, dy = 0.05, 0.05
x = np.arange(-3.0, 3.0, dx)
y = np.arange(-3.0, 3.0, dy)
X, Y = np.meshgrid(x, y)
Z2 = func3(X, Y)
imshow(Z2)
xlabel("XXX XXX")
ylabel("YYY YYY")
title("Title Title")
colorbar() # <-- This is the main trigger of the bug

tight_layout(pad=0.6)

savefig("b.pdf", bbox_inches="tight", transparent=True,
        metadata={'Creator': None, 'Producer': None, "CreationData": None})
savefig("b.png", bbox_inches="tight", transparent=True)
```

**Actual outcome**

The issue manefest itself different if the setting of `font.size`, x/ytick size, or the `tight_layout` was removed but in all cases the png backends produces different results than other backend. With the code as posted, which is the most similar to what I actually have in my real code that worked on 3.2.2, the png output was.

![b](https://user-images.githubusercontent.com/712232/88459308-5ec05000-ce62-11ea-9f05-2104de071a6c.png)

whereas the pdf output (converted to png) and everything else was,

![b-pdf](https://user-images.githubusercontent.com/712232/88459411-63d1cf00-ce63-11ea-9e4e-1e7ac83042d4.png)

The difference in this case is the overlapping of the title/labels and this should have been fixed by the `tight_layout`. With other options (e.g. if some of the font size settings are commented out) the png image will come out clipped.

**Expected outcome**

The png output should be the same as the pdf output as it was on 3.2.2.

**Matplotlib version**
  * Operating system: ArchLinux
  * Matplotlib version: 3.3.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): `Qt5Agg`
  * Python version: 3.8.3

matplotlib installed from ArchLinux repo.

**Comment by yuyichao** [comment]
Oh, forgot to mention. As said in the title, this seems to be caused by `colorbar()`. Without it, the output png looks identical with the pdf (and everything else). Given that this used to work and removing `colorbar()` causes a minimum change in the output pdf but a huge change in the output png I believe this is a png bug..

**Comment by jklymak** [comment]
If you call `plt.savefig` with `bbox_inches='tight'` you resize the figure, and that makes the second save different than the first. If you change the order of these two calls, the problem is not apparent.  If you remove `bbox_inches='tight'` is it also not happening.  Given that you are calling `tight_layout` I don't think you are accomplishing anything with `bbox_inches='tight'`.  

That said, the behaviour *did* change, and bisects to 602be075297ae9b  https://github.com/matplotlib/matplotlib/pull/17607 which changed the behaviour of `adjust_bbox`.  I don't understand that PR, or what it was meant to fix, but it is causing the hysteresis of response here.  Ping @QuLogic

**Comment by yuyichao** [comment]
> If you call plt.savefig with bbox_inches='tight' you resize the figure, and that makes the second save different than the first.

Hmmm, I have to say it is not obvious from the [doc](https://matplotlib.org/3.3.0/api/_as_gen/matplotlib.pyplot.savefig.html) that this option affects the plot more than the saved copy from it...

> Bounding box in inches: only the given portion of the figure is saved. If 'tight', try to figure out the tight bbox of the figure.

I always assume it was a "read-only" option on the plot itself....

> If you remove bbox_inches='tight' is it also not happening. Given that you are calling tight_layout I don't think you are accomplishing anything with bbox_inches='tight'.

I can believe that although both a bit magical to me in general....
In the real code, the `bbox_inches` was there to make sure the saving code always saves the correct size and I generally only "need" the tight_layout when I make a plot with subplots. Most of the plots I make are single plot and without the `bbox_inches` the saved figure usually have the "wrong size" (I added that option in my code probably at least 4 years ago and I can certainly do some tests to see which combination of options works the best for me now....)

**Comment by yuyichao** [comment]
> resize the figure, and that makes the second save different than the first.

BTW, if it is just resizing, and since I included the same option in the second savefig call as well, shouldn't that resize have no effect (on the content at least)? Or does the resize do more than just cropping the image to the correct size?

Also note that in my real code I actually save 3 images in the order of `pdf`, `png` and `svg` and I omitted the `svg` here since it happens after the `png` and obviously didn't have a retroaction on the `png` file. I just had a look and it seems that the `svg` file is also fine, the `png` in between is the only one messed up = = ........

**Comment by yuyichao** [comment]
> and bisects to 602be07 #17607 which changed the behaviour of adjust_bbox.

Hmm, reverting that locally doesn't seem to help. I'll try to do some bisect as well...

**Comment by yuyichao** [comment]
> Hmm, reverting that locally doesn't seem to help.

Sorry, wrong test..... It works, thx. I'll just revert it locally for now before a fix is released. =)

**Comment by QuLogic** [comment]
So that PR was intended to simplify `adjust_bbox`, using an `ExitStack` and our own attribute context manager. But I misunderstood how `process_figure_for_rasterizing` was used though, and this no longer works properly.

With the new code, it's expected that everything is called in pairs, i.e., `adjust_bbox` followed by `restore_bbox`. When saving, `BackendBases.print_figure` calls `adjust_bbox` before and `restore_bbox` after the renderer-specific method. In raster renderers, that's all that happens.

However, in mixed mode renderers, this is not the case. When it needs to rasterize (`MixedModeRendering.start_rasterizing`), it will change the DPI, restore the bbox, and re-adjust again. Internally, it hangs on to the new `restore_bbox`, but `print_figure` still has the original, which was cleared at the first `start_rasterizing` call, so when it calls `restore_bbox`, it does nothing because the stack is empty.

So as much as I like the cleanup, I guess we will have to revert this. There are some additional changes on master that will have to be handled as well.
