### ISSUE TITLE
3D scatterplots do not generate legend correctly

### ISSUE THREAD

**Issue by OGordon100** [matplotlib/matplotlib#18096]
### Bug report

**Bug summary**

Creating a 3d scatterplot with ax.scatter() and the "c" argument for colour only produces 1 legend entry

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
x = np.random.rand(20)
y = np.random.rand(20)
z = np.random.rand(20)
c = np.random.randint(low=0, high=4, size=20)
ax.scatter(x,y,z,c=c)
leg = [1,2,3, 4]
ax.legend(leg)
```

**Actual outcome**

![Output Image](https://i.snipboard.io/qMYz1f.jpg)

**Expected outcome**

The legend should have separate entries for "1", "2", "3", "4"

**Matplotlib version**

  * Operating system: Ubuntu 18.04
  * Matplotlib version: 3.3.0 (also exists at least as far back as 3.2.2)
  * Matplotlib backend (`TkAgg`):
  * Python version: 3.6.3
  * Jupyter version (if applicable): N/A
  * Other libraries: Numpy 

 pip

**Comment by OGordon100** [comment]
Also maybe of interest, I find a workaround with 

    # Get enough legend entries
    for _ in range(len(leg)-1):
        ax.scatter([0], [0])
    leg = ax.legend(leg)

    # Cycle through the colourmap to get colours correct
    color = plt.cm.viridis(np.linspace(0, 1, len(leg)))
    for i, leg_handle in enumerate(leg.legendHandles):
        leg_handle.set_color(color[i, :])

**Comment by timhoffm** [comment]
This is not how you create a legend with categories. Use
~~~
sc = ax.scatter(x, y, c=c)
ax.legend(*sc.legend_elements())
~~~
or, if you want custom labels
~~~
sc = ax.scatter(x, y, c=c)
labels = ['foo', 'bar', 'baz', 'spam']
ax.legend(sc.legend_elements()[0], labels)
~~~

**Comment by OGordon100** [comment]
@timhoffm Thanks, but this seems like quite a hacky workaround.

Normally, legends are just ax.legend(labels) or plt.legend(labels). Why should it be different for 3D, what suggests to the user that it's any different besides a tutorial you have to know exists to know exists, and what suggests to the user they should write plot.legend_elements()[0]?

**Comment by timhoffm** [comment]
There is no difference between 2D and 3D. You example equally does not work for 2D.

`plt.legend(labels)` is discouraged (https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.legend.html#matplotlib.pyplot.legend):

> Note: This way of using is discouraged, because the relation between plot elements and labels is only implicit by their order and can easily be mixed up.

The problem with `scatter()` is, that you have one `Artist` representing all data (a `PathCollection`) and you want to generate multiple handles (i.e. the marker part in the legend) and associate them with multiple labels. In general, this set of handles is ambiguous, because you could have colors and sizes. This needs configurability, which is why `PathCollection.get_legend_elements()` exists.

**Comment by OGordon100** [comment]
But to an end user, you not being able to do plt.legend() is not consistent. Worse, it displays the wrong output.

Ideally, plt.legend() should be consistent as when called with other artists. i.e. the function should in the background call plt.legend(*sc.legend_elements())

If it isn't possible to do so, then it should be ackowledged that the plot produced is wrong. The code should instead error and say you should instead call plt.legend(*sc.legend_elements()). (Or, better yet, be consistent)

**Comment by jklymak** [comment]
@OGordon100 I think the best way to think about it is that each artist only gets one legend entry, by default.  So, if you want to have multiple legend entries you either need to make multiple artists, or do something hacky.  

> If it isn't possible to do so, then it should be ackowledged that the plot produced is wrong.

I don't think its "wrong".  `scatter` has no way to know that you have 4 distinct categories, thats just a feature of your particular data set.  legend gives you an entry for your scatter call.  Its up to the user to make the scatter calls distinct.

**Comment by tacaswell** [comment]
The legend is not "wrong" it is "not what @OGordon100 wanted" which are different things. 

For example with non-categorical data:

```

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import Normalize

norm = Normalize(0, 1)
fig, ax = plt.subplots()

sc1 = ax.scatter(np.random.rand(20),
                 np.random.rand(20),
                 c=np.random.rand(20),
                 norm=norm,
                 label='A')
sc2 = ax.scatter(np.random.rand(20),
                 np.random.rand(20),
                 c=np.random.rand(20),
                 norm=norm, marker='s', label='B')

ax.legend()
fig.colorbar(sc1)
```

![image](https://user-images.githubusercontent.com/199813/88700118-3f315d80-d0d6-11ea-97a3-c184cd6cc08f.png)

is perfectly correct and what you are proposing would break that use case.  Given the breadth of users that Matplotlib has we have to accept that some things will be less-terse than some people would wish so that everyone's uses can actually be covered.
