### ISSUE TITLE
Error reading png image from URL with imread in matplotlib 3.3

### ISSUE THREAD

**Issue by tdpetrou** [matplotlib/matplotlib#18129]
### Bug report

**Bug summary**

After upgrading to matplotlib 3.3, `imread` errors when reading in a png from a URL. This was working in 3.2.

```python
from matplotlib import image
url = 'https://github.com/hjnilsson/country-flags/raw/master/png250px/us.png'
image.imread(url)
```

Results in `UnsupportedOperation: seek`

Traceback indicates error is from pillow. [Related Issue](https://github.com/imageio/imageio/issues/202)

**Full Traceback**

```
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-28-3cc23b6666a9> in <module>
----> 1 image.imread(url)

~/miniconda3/envs/mpl/lib/python3.8/site-packages/matplotlib/image.py in imread(fname, format)
   1473             from urllib import request
   1474             with urllib.request.urlopen(fname) as response:
-> 1475                 return imread(response, format=ext)
   1476     with img_open(fname) as image:
   1477         return (_pil_png_to_float_array(image)

~/miniconda3/envs/mpl/lib/python3.8/site-packages/matplotlib/image.py in imread(fname, format)
   1474             with urllib.request.urlopen(fname) as response:
   1475                 return imread(response, format=ext)
-> 1476     with img_open(fname) as image:
   1477         return (_pil_png_to_float_array(image)
   1478                 if isinstance(image, PIL.PngImagePlugin.PngImageFile) else

~/miniconda3/envs/mpl/lib/python3.8/site-packages/PIL/ImageFile.py in __init__(self, fp, filename)
    115         try:
    116             try:
--> 117                 self._open()
    118             except (
    119                 IndexError,  # end of data

~/miniconda3/envs/mpl/lib/python3.8/site-packages/PIL/PngImagePlugin.py in _open(self)
    651             # get next chunk
    652 
--> 653             cid, pos, length = self.png.read()
    654 
    655             try:

~/miniconda3/envs/mpl/lib/python3.8/site-packages/PIL/PngImagePlugin.py in read(self)
    126             s = self.fp.read(8)
    127             cid = s[4:]
--> 128             pos = self.fp.tell()
    129             length = i32(s)
    130 

UnsupportedOperation: seek
```

**Matplotlib version**

  * Operating system: macOS
  * Matplotlib version: 3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.8

**Comment by jklymak** [comment]
We switched to pillow handling the image i/o and it seems pillow can't handle urls?  https://github.com/matplotlib/matplotlib/pull/15193

**Comment by tdpetrou** [comment]
Would a simple approach using the standard library's `urllib.request` module to read the contents as bytes not work?

**Comment by tdpetrou** [comment]
Just looked at the source. `urllib.request` is used and passes the response to `PIL.PngImagePlugin.PngImageFile`, but if it passes it to `PIL.Image.open`, it would work.

**Comment by tdpetrou** [comment]
`PIL.Image.open` supports `urllib.request.urlopen` objects (https://github.com/python-pillow/Pillow/pull/1151) so I don't see why we can't just always pass it there instead of `PngImagePlugin.PngImageFile`

**Comment by jklymak** [comment]
This was discussed - https://github.com/matplotlib/matplotlib/pull/15193#discussion_r329832767  Not clear to me what @anntzer was trying to do with that, so perhaps he can explain.

**Comment by anntzer** [comment]
The point was to force reading the file as a png (if `ext == "png"`) rather than relying on pillow's autodetection.  This only matters if someone is nasty enough to have e.g. a jpeg file in a png extension, or pass a jpeg file to `imread(..., ext="png")`.
My guess is that wrapping in a BytesIO() is fine, you already made a web request anyways and we're about to convert the whole thing to float32, so I wouldn't worry too much about speed or memory usage.

**Comment by tacaswell** [comment]
Labeling this as a good first issue because there is a very clear regression and 2 suggested fixes in this thread.  This should get a test (so we don't accidentally break it again).  I think we have a test of getting a stylesheet from a URL, the new test should get the same markup so it can be skipped in no-network environments (ex debian builds) .

**Comment by andrewkoo** [comment]
Hi! I am new to open source and am interested in helping out if I can. If this is still open, can I start working on this?

**Comment by tacaswell** [comment]
@andrewkoo Interesting, it is probably worth investigating why that test did not catch this issue!

**Comment by timhoffm** [comment]
Without checking, I'd guess file:/// vs. https:///.

**Comment by dopplershift** [comment]
With checking: `open()` doesn't seem to recognize `file:///`, but it's possible I did something wrong.

**Comment by linchiwei123** [comment]
need to test http(s) as well.
```python
>>> file_r = urllib.request.urlopen(file_url)
>>> file_r.tell()
0
>>> https_r = urllib.request.urlopen(https_url)
>>> https_r.tell()
Traceback (most recent call last):
  File "<pyshell#20>", line 1, in <module>
    https_r.tell()
io.UnsupportedOperation: seek
```

**Comment by tacaswell** [comment]
Do we expect that type instability from `urlopen`?  If not, does this need to be reported as a bug to cpython?

**Comment by linchiwei123** [comment]
https://docs.python.org/3.8/library/urllib.request.html#urllib.request.urlopen
For HTTP and HTTPS URLs, this function returns a http.client.HTTPResponse object slightly modified. In addition to the three new methods above, the msg attribute contains the same information as the reason attribute — the reason phrase returned by server — instead of the response headers as it is specified in the documentation for HTTPResponse.

For FTP, file, and data URLs and requests explicitly handled by legacy URLopener and FancyURLopener classes, this function returns a urllib.response.addinfourl object.

**Comment by timhoffm** [comment]
> Do we expect that type instability from `urlopen`?  If not, does this need to be reported as a bug to cpython?

[HTTPResponse](https://docs.python.org/3.8/library/http.client.html#httpresponse-objects) is documented to implement [BufferedIOBase](https://docs.python.org/3.8/library/io.html#io.BufferedIOBase), which does not include `seek()`. IMHO that's all we can expect. That file:// returns another object with more functionality can be misleading but is not strictly a bug and I don't think cpython could/would change this.

Like Pillow ((https://github.com/python-pillow/Pillow/pull/1151) we cannot assume that `seek()` exists. The fix is to either pass the response straight through (which we apparently do not want to do - did not follow the details), or apply the same fix with wrapping if neccesary as Pillow does.

**Comment by tacaswell** [comment]
@linchiwei123 @andrewkoo I went ahead and opened the PR to take care of this.  Sorry to steal the work out from under you but as this was the last issue for 3.3.1 we wanted to expedite the process.

**Comment by andrewkoo** [comment]
All good! This is all just a learning process for me so would hate to delay anything..

**Comment by linchiwei123** [comment]
It's OK.

**Comment by anntzer** [comment]
Note that with Pillow 8.0 the dance at https://github.com/matplotlib/matplotlib/issues/18129#issuecomment-666675572 would not be necessary anymore per https://pillow.readthedocs.io/en/stable/releasenotes/8.0.0.html#image-open-add-formats-parameter.
