### ISSUE TITLE
document deprecated artist methods instead of writing unknown

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#18289]
### Problem
The `contains` kwarg in `.plot` and derived methods has description that says  `unknown`
![image](https://user-images.githubusercontent.com/1300499/90569701-56ff7d00-e17c-11ea-9b99-5990fbcf6b88.png)

clicking through, it's also unclear if this keyword argument is deprecated or if the [Artist.set_contains](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.artist.Artist.set_contains.html#matplotlib.artist.Artist.set_contains) method is deprecated. 

### Suggested Improvement
Either it should explicitly say that the keyword is deprecated or is a callable that overwrites the contains method of the artist.

**Comment by QuLogic** [comment]
Passing `contains` would call `.set_contains`, so I think both ways are deprecated.

**Comment by timhoffm** [comment]
Formally, you are right. In practice, the issue will resolve itself when the deprecation expires and I wouldn't put extra effort in.

- The value "unknown" is printed because the `Artist.set_contains` docstring does not formally define supported values (either via `ACCEPTS:` or via numpydoc `Parameter`). The docstring could be changed, but personally I wouldn't bother for this deprecated method.
- One could add *[deprecated]* in front of the values. That would have to be done in `ArtistInspector.pprint_setters_rest` and maybe  `ArtistInspector.pprint_setters`. Given that I don't expect us to massively deprecate Artist properties, I don't think this would be worth the effort and added complexity. Note that you still get the runtime deprecation warning.

**Comment by story645** [comment]
> One could add [deprecated] in front of the values. That would have to be done in ArtistInspector.pprint_setters_rest and maybe ArtistInspector.pprint_setters. Given that I don't expect us to massively deprecate Artist properties, I don't think this would be worth the effort and added complexity. Note that you still get the runtime deprecation warning.

I support this approach if it is regularized 'cause I ran across it on a different argument and having to click through to learn unknown usually means deprecated in Matplotlib docs is a convention I don't think we want to nurture. 
![image](https://user-images.githubusercontent.com/1300499/91229590-211c4480-e6f8-11ea-80dc-ee8472f6c6b8.png)

**Comment by oscargus** [comment]
These two examples are now removed, but I think that the deprecation issue is not solved, so not sure if this can be closed.

**Comment by story645** [comment]
Thanks for the update! I think the solution to the broader issue is a decorator/addition to deprecation deprecator that adds deprecated to the docs when the properties are deprecated?

**Comment by timhoffm** [comment]
Technically, amending pprint is the correct solution. However, the mentioned cases are resolved through the expired deprecation.  As written above, deprecating artist properties is extremely rare. I don't think amending pprint is worth the effort and therefore propose to close. - Unless somebody feels strongly now and steps up to implement this. But IMHO we should not leave his open indefinitely without action.

**Comment by story645** [comment]
can I add an if statement where unknown is added saying [deprecated] if condition instead of messing w/ the pre/post print
https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/artist.py#L1452

**Comment by timhoffm** [comment]
It's perfectly viable to add such an if statement. But note that basically all return statements (except for return None) should get a "[deprecated]" prefix.

(You need that early exit if docstring is None, because the following code requires docstring to be a string.)
