### ISSUE TITLE
2-D array RGB and RGBA values not understood in plt.plot()

### ISSUE THREAD

**Issue by danuo** [matplotlib/matplotlib#18411]
### Bug report

**Bug summary**

2-D array color does not work in plt.plot() while working as intended in plt.scatter(). A 2-D array is recommended by matplotlib itself by this warning:
"'c' argument looks like a single numeric RGB or RGBA sequence, which should be avoided as value-mapping will have precedence in case its length matches with 'x' & 'y'.  Please use a 2-D array with a single row if you really want to specify the same RGB or RGBA value for all points."

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

color_rgb = np.array([[0.1,0.2,0.3]])
color_rgba = np.array([[0.1,0.2,0.3,0.4]])

plt.scatter([1,2],[1,2],c=color_rgb)  # working
plt.plot([1,2],[1,2],c=color_rgb)     # not working

plt.scatter([1,2],[1,2],c=color_rgba) # works fine
plt.plot([1,2],[1,2],c=color_rgba)    # NOT working

plt.show()
```

**Actual outcome**

```
Invalid RGBA argument: array([[0.1, 0.2, 0.3, 0.4]])
```

**Matplotlib version**

  * Operating system: Win 10 1909
  * Matplotlib version: 3.1.3 (from anaconda, pkgs/main)
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.8.1

**Comment by jklymak** [comment]
Plot only ever accepts one color so that warning is not applicable to plot.  OTOH color can be a list for scatter.  I actually agree though that we should be able got take a single color and the warning for scatter should only pop up if there is some ambiguity as to whether a single color is wanted or three colors.

**Comment by danuo** [comment]
I fully agree on your reasoning, however one should be able to define a single rgb color in a way so that it can be used universally. I think the warning should be there, as color=(a,b,c) is indeed dangerous. Instead plot() should accept 2d-array (3*1 or 4*1) color input as that format is suggested by scatter().

**Comment by tacaswell** [comment]
I think that we should always warn it the scatter case (as there is a chance of ambiguity and the case that people test on may not have the n=3/4 issues, but when they start using their code it pops up and surprises them (think of the case where people are running lots of datasets in a loop/automated job and may not be watching the warnings like a hawk).  It is better that the warning is unconditional.

That then means in  `_process_plot_var_args` we should do the down-broadcasting of a single element array of color variables so that you can pass the same color to both `plot` and `scatter` as @danuo points out.


----

I'm labeling as good first issue because I think that the changes can be very localized to the argument parsing logic of `plot`, but medium because you will have to understand the logic of the plot input parsing (which because it is so forgiving to the user is a bit gnarly).

**Comment by danuo** [comment]
I looked into the route you suggested, by looking into the `_process_plot_var_args` and I did not really like the approach because at that stage, the 'color' keyword could either be in the kw OR the kwargs variable and could have any format, if not undefined.

The solution I found working and to be more elegant looks as follows. In Matplotlib 1.3.1 the error I described gets produced in `colors.py` by this line of code:
`    if not np.can_cast(c.dtype, float, "same_kind") or c.ndim != 1:
        raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))`

Changing that to 
`    if c.ndim == 2 and c.shape[0] == 1:
        c = c.reshape((-1))
    
    if not np.can_cast(c.dtype, float, "same_kind") or c.ndim != 1:
        raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))`

does fix the error in my modified installed Matplotlib. However, I do not know how I can test this in master. I did clone the master repo locally but I am unable to import that not-installed/cloned version of Matplotlib without error.

Can you please elaborate on my suggested fix and maybe point me in the right direction of where I can learn about importing a cloned Matplotlib? Thanks

**Comment by jklymak** [comment]
There are developer docs that should help with installing and "editable installation".  Usually it's pip -e . In the Toole be matplotlib directory

**Comment by danuo** [comment]
I did make a pull request here:
https://github.com/matplotlib/matplotlib/pull/18423

Thank you @jklymak for pointing a rookie into the right direction, the internet is filled with bad advice and sometimes it can be hard to know where to start looking.
