### ISSUE TITLE
imshow doesn't support vmin/vmax parameters (data range that colormap covers) for multichannel data.

### ISSUE THREAD

**Issue by mkcor** [matplotlib/matplotlib#18627]
Hello,

I have searched open issues and PRs for 'imshow' and 'vmin' and none seemed to correspond to the current issue.
@emmanuelle I'm opening this issue to follow up on https://github.com/scikit-image/scikit-image/pull/4946#issuecomment-702301758. 

### Problem

I'm using `imshow` to view a multichannel image.

@tacaswell in this case, it's actually not an RGB(A) image! It's a (2D) slice of 3D data imaged with confocal fluorescence microscopy, where the three 3 colour channels correspond to emission wavelengths 450nm, 515nm, and 605nm, respectively.

Whatever the colour channels are and however many they are, I would like to be able to change the contrast by passing `vmin/vmax` values, possibly as lists (of which length would be the number of colour channels).

### Proposed Solution

The `vmin/vmax` parameter of `imshow` could support the multichannel case, the way Plotly Express's `imshow` does:
https://plotly.com/python/imshow/#defining-the-data-range-covered-by-the-color-range-with-zmin-and-zmax

### Additional context and prior art

The tiny PR I just submitted is related to this issue: https://github.com/matplotlib/matplotlib/pull/18626

**Comment by jklymak** [comment]
Matplotlib `imshow` accepts *either* MxNx3, MxNx4, or MxN.  If its the first two, each element in the array is RGB(A), and `vmin` and `vmax` are completely ignored because we are assuming you have passed actual colors in.  

If you want to re-normalize one of the three (four) channels, you can do that yourself before passing to `imshow`, but I don't think we want to be in the business of renormalizing specific colors for the user.

If you pass MxN, then vmin and vmax are used to normalize the data in the array, and then those numbers are passed to a colormap for mapping to RGBA values.  

We don't support passing arbitrary numbers of colors to `imshow`. Again, you'd have to composite outside of matplotlib and pass us the final product.  

I hope that is clear, but perhaps I've misunderstood your request. If I have it correct, I would strongly argue this is a "won't fix".

**Comment by timhoffm** [comment]
This would require some semantic and internal changes. For us, every (M, N, 3) array *is* a RGB image stating explicit colors. Even though the data origin may not RGB, plotting it with imshow interprets it as RGB.

In contrast, the `vmin`/`vmax` conecpt maps scalar data to the colorbar scale.

One can take the standpoint that 3-tuple vmin/vmax map arbitrary values to the R, G, B channel scales. This is not completely off, but would be a new way of framing the topic and would need really good documentation. From an implementation side, 3-tuple vmin/vmax would need to be handled completely separate. Scalar vmin/vmax just instantiate a `LinearNorm(vmin, vmax)` and use the scalar->norm->colormap pipeline. Adding a general multi-dimensional mapping seems not like a viable idea - at least not within the current ScalarMappable / Colormap concept. 3-tuple vmin/vmax would be a standalone ad-hoc addition to imshow. 

@mkcor I see where you're coming from but it's not as straight forward to add to Matplotlib in a consistent way. Would this really be much simpler than having your own rescaling function `imshow(rescale(X, vmin=(0, 0, 0), vmax=(0.4, 0.5, 0.6)))`? In your own function, you could group by channel `rescale(X, r=(0, 0.4), g=(0, 0.5), b=(0, 0.6))`, which seems more intuitive, but for sure we is not option on the matplotlib side.

**Comment by mkcor** [comment]
@jklymak @timhoffm thank you both for the detailed replies! I get the philosophy. I'll close this issue then.

PS: @timhoffm I'm not sure where the `(0.4, 0.5, 0.6)` values come from, but I think I get your general point: With the right custom-made rescaling function, I could convert whatever multichannel image into an RGB image. In the short-term, I'll stick with Plotly's `imshow`.

**Comment by tacaswell** [comment]
@mkcor Thank you for being understanding.  Hope to hear from you again!
