### ISSUE TITLE
Errorbar lines are not present in the Qt NavToolBar --> curves tab

### ISSUE THREAD

**Issue by andyfaff** [matplotlib/matplotlib#18631]
I would like to be able to interactively change various aspects of an error bar plot (in a Qt window), such as line width/colour/marker size.
This is possible for a normal Qt `plot`, you can do this with the NavToolBar button that opens a Figure options GUI. There is a curves tab that displays these options for each of the `plot`s on the graph.

However, `errorbar` plots don't show in the curves tab, so it's not possible to interactively set their properties. Why don't those plots show in the curves tab?

**Comment by tacaswell** [comment]
Because the code that populates that part of the UI https://github.com/matplotlib/matplotlib/blob/fcb629602fd71085b5e48f73cadc9acb910be5a2/lib/matplotlib/backends/qt_editor/figureoptions.py#L68-L74 only looks at lines but the errorbar objects are (internally) stored differently.

The details of the internal storage is being changed (see 
https://github.com/matplotlib/matplotlib/pull/18216) but there is stable public API to get the "containers" and add them to this list.
