### ISSUE TITLE
i use contourf method to fill three blocks with value 1,2,3 but between 1 and 3 filled by 2

### ISSUE THREAD

**Issue by diversoft** [matplotlib/matplotlib#18720]
### Bug report

** i use contourf method to fill three blocks with value 1,2,3 but between 1 and 3 filled by 2**

**Code for reproduction**

```python
import matplotlib
import numpy as np
import matplotlib.pyplot as plt

origin = 'lower'

delta = 0.025

x = y = np.arange(-3.0, 3.01, delta)
X, Y = np.meshgrid(x, y)
# create grid with 1
Z = np.ones((len(x), len(y)), dtype=float)
# set 0-100 value=2
Z[0:100] = 2

# set 3
Z[100:, 0:100] = 3

# the left is 1


fig1, ax2 = plt.subplots(constrained_layout=True)
CS = ax2.contourf(X, Y, Z, levels=[0, 1, 2, 3], colors=[
                  '#ff0', '#0ff', '#f00', '#000'],  origin=origin)
plt.show()
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/2303685/95866143-1eee7200-0d9a-11eb-8132-331ea6e9da4b.png)

**Expected outcome**
![image](https://user-images.githubusercontent.com/2303685/95865422-4133c000-0d99-11eb-8eed-b0b6bb32a06c.png)

**Matplotlib version**

  * Operating system:windows 10 bit64
  * Matplotlib version: 3.2.1
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version:python 3.7.2 bit64
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by jklymak** [comment]
In general, that "2" contour exists between those two data  values, so I think the algorithm is working properly and showing a contour between your two specified data points.  You can make that region thinner or thicker by changing the distance between the data points but otherwise this is working as expected.  I'm going to close as won't fix.
