### ISSUE TITLE
<< c >> and << color >> keyword argument inconsistency

### ISSUE THREAD

**Issue by jeromefv** [matplotlib/matplotlib#18776]
### Describe the issue

**Summary**
Request from [Matplotlib Survey](https://docs.google.com/spreadsheets/d/1z_bAu7hG-IgtFkM5uPezkUHQvi6gsWKxoDnh0Hz1K5U/edit?usp=sharing) user with Interactive Shell/Batch Script Non-production background.

> Please fix the « c » and « color » keyword argument inconsistency in the API or put some warnings in the documentation

**Comment by story645** [comment]
So it's not an inconsistency, it's that c/s are for when you can pass in a list of data values to set those parameters (vectorization).

**Comment by timhoffm** [comment]
I assume this concerns `scatter()`?

I don't see an inconsistency there, and the original request is too vague. Il propose to close as non-actionable.

**Comment by jklymak** [comment]
I think its a general complaint that we sometimes use `c` and sometimes `color`.  I have a similar compliant about `location` and `loc` in `title` and `legend`.   I can never remember off the top of my head which gets which....

**Comment by timhoffm** [comment]
Where exactly? We have `c` (or `C`) in false-color-type plots and in `scatter()`. All other "simple" artists have `color`. IMHO that's justifyable because the color is a primary element-wise feature of those plots (Signature `X, Y, C`, where C is often not even usable keyword). `scatter()` is a bit debatable, but there it's at least also an element-wise property. And I don't think we should change the `c` in `scatter()` for compatibility reasons. I still do not see what to change.

**Comment by story645** [comment]
I don't think the plan of action necessarily has to be changing anything; what's worked every single time I've run into the complaint is to explain when folks should use 'c' versus and when they should use 'color' and that the consistency is that c/s is for vectorized parameters (though not in those exact words). Basically, I think this issue can be resolved in clearer docs rather than API changes.

**Comment by timhoffm** [comment]
I was only weighing in on the issue because the problem description is vague and I'm not clear how a solution could look like. Therefore I've proposed to close this as non-actionable.

I'd like to see a clarification of the problem and a proposed solution. Otherwise this issue will most likely just live forever as non-actionable, and that does more harm than just closing it.

**Comment by jeromefv** [comment]
I don't think the person who answered that way in the Matplotlib survey ever talked about this in the community. It's likely best to close this issue in the meantime.

**Comment by andrzejnovak** [comment]
I am not the OP, but I also found this a bit irksome. I understand the vectorization argument somehow, but it's still confusing because some function will also understand iterable in addition to the default like `color` or `label` in `hist` or `bar`.

My preference would be either to remove `c` as an option or rather just treat it as an alias for `color` in all function

**Comment by timhoffm** [comment]
There are different cases:

1. 'c' is an alias for 'color' in `Line2D` (and thus all functions that accept `Line2D` properties)
2. 'c' is an explicit parameter in `scatter()`
3. 'C' is an explicit parameter `hexbin()`
(4. There's additionally some C in other color-mapping functions such as `pcolormesh()` but these are mostly documentation as the parameters are parsed through `*args` and thus `C` cannot be used as a keyword. On exception is `Quiver.set_UVC(U, V, C)`.)

These are all very public APIs and I don't see that we can change anything without massively affecting existing user code. Thus, I consider this as non-viable.

That said, If somebody has concrete suggestions for changes, I'm happy to discuss that. But please make it very specific. "Remove `c` as an option is too broad as we have the different cases above.
