### ISSUE TITLE
Function from R^3 to R documentation

### ISSUE THREAD

**Issue by jeromefv** [matplotlib/matplotlib#18777]
### Problem

Request from [Matplotlib Survey](https://docs.google.com/spreadsheets/d/1z_bAu7hG-IgtFkM5uPezkUHQvi6gsWKxoDnh0Hz1K5U/edit?usp=sharing) user with Production usage from Interactive Shell/Jupyter/GUI.

> Please give more documentation on function from R^3 to R it’s extremely difficult to understand how to plot such functions

**Comment by jklymak** [comment]
@jeromefv   This is too vague to be actionable.

**Comment by jeromefv** [comment]
Ah, I'm not too sure what else this user had in mind. Survey had little other data to aid in more detail for the issue. Happy to take direction on continuing steps or other action.

**Comment by timhoffm** [comment]
Plotting R^3 -> R is difficult because you have 4 dimensions. One solution could be a 3D plot with color coding. But since you cannot fill the whole R^3, you have to choose representative data points. How that should be done depends on your data e.g. via [scatter](https://matplotlib.org/gallery/mplot3d/scatter3d.html) or via [voxels](https://matplotlib.org/gallery/mplot3d/voxels_rgb.html).

This is more a question of defining a reasonable visual representation for a certain problem. It's less about showing how to achive a given visual representation. In that sense I suggest that this is out of scope for our examples. We cannot in general discuss how to best visualize complex data sets. That's a field much to broad.
