### ISSUE TITLE
Bug: mpl doesn't handle values correctly from `pandas.Timestamp.isocalendar`

### ISSUE THREAD

**Issue by vedal** [matplotlib/matplotlib#18788]
### Bug report

**Bug summary**

The following example produces unexpected behavior. The reason seems to be that matplotlib currently doesn't handle the pandas Uint32 type (in column week) as grouping variable.

**Code for reproduction**

```python

import pandas as pd
import matplotlib as mpl
df = (
    pd.DataFrame(
        {"date": pd.date_range("20200101", "20200120"), "value": range(20)}
    )
    .eval(
        """
        week=date.dt.isocalendar().week
        hour=date.dt.hour
        """
    )
)

mpl.colors.Normalize()(np.asarray(df["week"]))
```

**Actual outcome**

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-5-2195a79da9a9> in <module>
     13 )
     14
---> 15 mpl.colors.Normalize()(np.asarray(df["week"]))

~/.pyenv/versions/3.6.5/envs/dda-product/lib/python3.6/site-packages/matplotlib/colors.py in __call__(self, value, clip)
   1044         result, is_scalar = self.process_value(value)
   1045
-> 1046         self.autoscale_None(result)
   1047         # Convert at least to float, without losing precision.
   1048         (vmin,), _ = self.process_value(self.vmin)

~/.pyenv/versions/3.6.5/envs/dda-product/lib/python3.6/site-packages/matplotlib/colors.py in autoscale_None(self, A)
   1088         A = np.asanyarray(A)
   1089         if self.vmin is None and A.size:
-> 1090             self.vmin = A.min()
   1091         if self.vmax is None and A.size:
   1092             self.vmax = A.max()

~/.pyenv/versions/3.6.5/envs/dda-product/lib/python3.6/site-packages/numpy/ma/core.py in min(self, axis, out, fill_value, keepdims)
   5699         if out is None:
   5700             result = self.filled(fill_value).min(
-> 5701                 axis=axis, out=out, **kwargs).view(type(self))
   5702             if result.ndim:
   5703                 # Set the mask

AttributeError: 'int' object has no attribute 'view'
---------------------------------------------------------------------------
```

**Matplotlib version**

  * Operating system: `macOS 10.13.6`
  * Matplotlib version: `'3.3.2'` 
  * Matplotlib backend: `TkAgg`
  * Python version: `3.6.5`

Installed using pip

**Comment by vedal** [comment]
Simpler reproducible example suggested by @mwaskom :
```
import matplotlib as mpl, pandas as pd

mpl.colors.Normalize()(pd.Series([1, 2, 3], dtype="UInt8"))
```

**Comment by mwaskom** [comment]
Simpler reproducer:

```python
import matplotlib as mpl, pandas as pd
s = pd.Series([1, 2, 3], dtype="UInt32")
mpl.colors.Normalize()(s)
```

The problem arises in `Normalize.process_value` because the way matplotlib uses `numpy.min_scalar_type` and `numpy.promote_types` causes the series to be converted to object type, which eventually breaks numeric operations.

I'm not exactly sure what the objective for doing the type conversion is in this function.

Then the downstream problem is that that while numpy can find the `min` of an object array when all of the objects are numbers, matplotlib uses a masked array internally which does not have the same flexibility.

**Comment by tacaswell** [comment]
The best thing to do for now is pre-convert the pandas array to either a `np.array` of float + nan or to a `np.ma.array`.

It looks like this is https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.arrays.IntegerArray.html which the docs mark as experimental.  I think that the minimal example (`np.ma.array(np.asarray(s))`) should be reported to pandas as on a very quick reading it looks like `pandas.arrays.IntegerArray` is a 1D special case of `np.ma.array` I would expect to be able to go between them without trouble.

**Comment by mwaskom** [comment]
Who owns the logic of what `np.asarray(s)` does? It returns as object type, but IMO a nullable integer should be represented as a float type.

The inconsistency between regular array and masked array in failing on `.min()` seems like a numpy-specific problem however.

**Comment by mwaskom** [comment]
```python
s.__array__()
```
```
array([1, 2, 3], dtype=object)
```

ok, does seem like pandas isn't doing the apparently correct here (but perhaps with a good reason).

**Comment by tacaswell** [comment]
I think the underlying problem here is that they have defined extension types on the ints that include missing values.  It is strictly correct that the values in one of these things can not be represented in any dtype available to numpy (real ints do not have missing value sentinels, floats may lose precision) so `object` is the "right" choice.

While we have users running into this at the seaborn/mpl level, this needs to be sorted out at the pandas/numpy level.   Hopefully they can sort this out upstream, but if they can not I guess we will have to add more epi-cycles to the input normalization code.

**Comment by mwaskom** [comment]
I reported the narrow issue that could make this work upstream to numpy.
