### ISSUE TITLE
pcolormesh has been broken

### ISSUE THREAD

**Issue by 2sn** [matplotlib/matplotlib#18853]
### Bug report

**Bug summary**

pcolormesh used to work with subpressing plot NaN values in regular (not masked) array, now broken.

**Code for reproduction**

in `axes/_axes.py` please comment (back) out the lines

```
                if np.ma.is_masked(X) or np.ma.is_masked(Y):
                    raise ValueError(
                        'x and y arguments to pcolormesh cannot have '
                        'non-finite values or be of type '
                        'numpy.ma.core.MaskedArray with masked values')
```
then all is fine.  These lines, whereas they may have been well-intended, do seem to serve no desirable purpose.

**Comment by timhoffm** [comment]
This was intentionally introduced in #9723. By design, `pcolormesh()` cannot work reliably with masked x/y arguments. If you really need that, consider using `pcolor()` instead. See also [differences between pcolor() and pcolormesh()](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.pcolormesh.html#differences-pcolor-pcolormesh).

**Comment by 2sn** [comment]
`pcolor()` is way too slow for any reasonable application.  The problem is that the code above does not only filter our masked arrays, chich U do not use, but also arrays that just contain `nan`s.  For my case it was just working fine and it is only your test code that breaks things arbitrarily.  It is better to let things work for cases where is no problem.  The matplotlib code base is poor enough even without such _additions_.

**Comment by jklymak** [comment]
That change was made a long time ago, and you are the first user to complain about it, so your use case seems rare.  It would be helpful if you provided an example and an argument why including nan in x or y is good API.  

In particular, given that x and y define a quadrilateral corner, what do you expect to happen if one corner of four quadrilaterals is missing?  Should all four adjacent data points be poisoned?  Hard for us to guess what the user meant and perhaps better for them to put the NaNs in their data (the c array) rather than trying to guess. 

Sorry this broke your code, but it's pretty easy for the user to remove nan from numpy arrays in a way that is consistent with their data. 

With respect to the codebase, matplotlib is a volunteer project and we always welcome improvement PRs.

**Comment by kthyng** [comment]
Wow! I can't believe people write such rude comments! And @jklymak being kind in response.

I have also run across this issue, using matplotlib wrapped in xarray and pcolor is not wrapped, but indeed I was able to `.dropna()` before the plot call and it worked out ok. 

Also I love matplotlib and I really appreciate your work on it!!
