### ISSUE TITLE
Add a built-in style for publication quality scientific plots

### ISSUE THREAD

**Issue by aeturrell** [matplotlib/matplotlib#19028]
### Problem

None of the built-in styles are suitable for publication quality scientific plots. (Seaborn-paper comes closest of the current styles.) It would be good to make it as easy as possible for newcomers from the scientific (and social science) community to tweak their plots to fit the style of scientific papers by having a built-in style that they can use out of the box. It's a small change to the code base but anything that lowers the barriers to entry to making high quality plots is very valuable to the casual or new user.

### Proposed Solution

It would be fantastic to have an in-built style that was suited for scientific papers and could be called via `plt.style.use('paper')`. Notably this would entail:

- white backgrounds.

- ticks.

- fonts that are the closest to the ones used by default in the Latex typesetting language, which is used for writing papers across many disciplines.

- math and text fonts that are consistent.

- plot font sizes that are relatively large compared to the size of plot features, for readability when output as part of a PDF.

- figure proportions that are sympathetic to paper layout, i.e. quite a bit wider than they are long.

### Additional context and prior art

The best I have been able to get to a publication quality plot is by using the following style. It's imperfect but could be a starting point for a scientific paper style. (I'm also not sure whether the sizes of elements can be specified in relative, rather than absolute, terms--but relative would be better.)

```python
plot_settings = {'ytick.labelsize': 16,
                        'xtick.labelsize': 16,
                        'font.size': 22,
                        'figure.figsize': (10, 5),
                        'axes.titlesize': 22,
                        'axes.labelsize': 18,
                        'lines.linewidth': 2,
                        'lines.markersize': 3,
                        'legend.fontsize': 11,
                        'mathtext.fontset': 'stix',
                        'font.family': 'STIXGeneral'}
plt.style.use(plot_settings)
```

**Comment by jklymak** [comment]
This is pretty subjective and people publish with our default style all the time.  

I think we were planning a separate repository for user-contributed styles.  @story645 was that a project you were going to do?   A suggestion like this would be appropriate in that repository to start and if it gained large popularity could be moved as a library default.

**Comment by story645** [comment]
@jklymak I didn't get buy in to make it part of the matplotlib org and right now don't have the bandwidth to push it forward. @petermckeeverPerform started a repo to collect styles but he also built on API to make them:
https://github.com/petermckeeverPerform/themepy

We've gotten the suggestion before for a paper style since seaborn has one, and I think giving a basic template is good  but I also think Jody makes a good point that papers tends a bit too discpline specific in their specifications.

I'm not sure how to approach this in the docs though since the tutorial works through a presentation style that styles are composable: https://matplotlib.org/tutorials/introductory/customizing.html#composing-styles

**Comment by jklymak** [comment]
@tacaswell was going to write a "how to" for making your own startup script.  I still think that would be super helpful for many naive users.   Actually it would be helpful to me.  I find scope issues and when something is run on import somewhat befuddling.

**Comment by mwaskom** [comment]
To be clear, the fact that the different components of the seaborn themes are split into different stylesheets when bundled with matplotlib makes this a little confusing, but the `seaborn-paper` theme changes *only* the scaling of the plot elements, so it's not a general purpose "publication quality" (whatever that means) style. And it makes fonts *smaller* than the matplotlib defaults, not larger as proposed here.

FWIW I agree that what makes a figure "publication quality" is both subjective and field-specific; it's common in physics journals to use latex fonts in figures, but that is very unusual in biomedicine, where few papers are drafted in latex and many journals request Helvetica/Arial fonts. And a 10 inch wide figure default seems not to make much sense in a paper context, given that print-formatted documents are have only ~8 in of available width...

**Comment by jklymak** [comment]
In my field I'd say most people do draft in latex but very few people make the fonts match. Aesthetically, I think it looks terrible to use the same fonts in a graphic as in the text. I think the physics and math community does this because 30 years ago you *had* to use latex if you wanted scientific notation etc in your tick labels.  Pretty sure folks went in with Illustrator or Corel Draw and added them after creation.  But all modern plotting packages provide that functionality now, and I really think the aesthetic is still followed just to seem "serious".

**Comment by aeturrell** [comment]
@mwaskom To be honest, I'm not sure how best to execute what I was thinking of, I just thought I'd make the suggestion with some bullets and get the ball rolling with an (imperfect) example in case that was helpful.

My personal view is that if there are multiple built-in styles at all, and there are at least some fields (physics, economics, computer science) that might benefit from a Latex-oriented (or perhaps publication-oriented, given what @jklymak has said) built-in, then the marginal cost of having one more style that's aimed at reducing effort for users is low. 

But I can see that there is less agreement on what fonts/styles 'publication quality' entails than I had anticipated. Even so, I wonder if having built-in styles suited for papers (perhaps different styles for different disciplines) could be useful for users?

**Comment by jklymak** [comment]
Closing as not directly actionable.
