### ISSUE TITLE
event loop and event handling docs are hard to find

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19037]
### Problem

In the user's guide section (https://matplotlib.org/users/index.html), the event loop (https://matplotlib.org/devdocs/users/interactive_guide.html) and event handling (https://matplotlib.org/users/event_handling.html) docs are under the "Interactive figures" section.  That is in itself fine, but note that if you click on the "Interactive figures" section, you end up at https://matplotlib.org/users/interactive.html which is a full page of docs in itself (which contains all other entries of the "Interactive figures" section, and only contains a hard-to-notice link to the event loop and event handling sub-pages.

(As a side point, I also don't like the leading sentence of the "interactive figures" page, "When working with data, interactivity can be invaluable.": that's also true when working with simulations, or plotting mathematical equations, or whatnot...)

**Comment by Joe-Sin7h** [comment]
Hello! This is my first time contributing to an open source project , I would like to work on this issue .
can i get assigned ?

**Comment by timhoffm** [comment]
Go for it. We do not have a formal assignment (but it's good to announce that you are gonna be working on it).

**Comment by rajpratyush** [comment]
@timhoffm what are your suggestions for tackling the issue ?

**Comment by timhoffm** [comment]
I haven't looked into the details of the issue. I you can come up with a good solution yourself, go for it, otherwise please find something else to work on. I don't have time to mentor.

**Comment by rajpratyush** [comment]
@timhoffm A solution as per my mind could be as both event loop and event handling should have short description about each of them and make them as sub topics of the pages rather than mere hyperlinks. One more fault that I discovered was there there was very less gap in between the lines of the topic like you can see in the screenshot attached.
![Screenshot (706)](https://user-images.githubusercontent.com/53184883/111273016-4e5f1e80-8659-11eb-8580-a043a447a07a.png)
