### ISSUE TITLE
PyQt Toolbar Issue

### ISSUE THREAD

**Issue by Mastiff37** [matplotlib/matplotlib#19064]
Not sure if I have a bug or just a question.  I'm using PyQt4 and matplotlib 2.1.0.  I embed a figure in the GUI in a way that worked fine for matplotlib 1.2.0.  The issue is that while zoom and pan work properly in the toolbar, clicking the home button always changes the axis range to (0 to 1) in both dimensions.  It appears that the code behind the home button has no idea what the data range is or what the range history was at all and just reverts to default.  Is this a compatibility issue with PyQt4, or something else?

**Comment by jklymak** [comment]
2.1 is outside our support window.   There were indeed issues with the axes history, but they were addressed quite a while ago.  Can you try with a more modern matplotlib?

**Comment by Mastiff37** [comment]
Thanks for the reply.  Unfortunately, I'm on a sequestered network and 2.1 is actually the newest available.  My fallback is to revert back to 1.4, slightly newer than the 1.2 I was using.  If there's a workaround for 2.1, I can give it a shot, but I understand these versions are a bit old.

**Comment by jklymak** [comment]
I doubt there is a work around, unless you want to write a whole bunch of infrastructure to wrap what those buttons do and keep proper track of the limits yourself.  I'll close this because I don't think there is anything we can do to help from our end.  But if you do need further guidance, you can post at discourse.matplotlib.org.
