### ISSUE TITLE
How to remove the window title of a matplotlib figure by tkagg

### ISSUE THREAD

**Issue by azuryl** [matplotlib/matplotlib#19072]
I need  figure header can be set invisible, since I  just draw one picture include  lines and points and display with another large picture . figure header blocking the previous picture. I need the function  fig.canvas.header_visible = False
like https://github.com/matplotlib/ipympl/issues/134
![sample](https://user-images.githubusercontent.com/23340671/101274389-a4bfe580-376b-11eb-8a45-bb37ad738b4c.png)
I need the small picture effect like the sample which  figure header in invisible but can draw

How to remove the window title of a matplotlib figure by tkagg

**Comment by jklymak** [comment]
You can embed your matplotlib figure in a tk app that you write.  However, I'm not sure if tk will allow you to remove the title bar or not.  Most window managers do not because how would you manipulate the window at that point?  

In the above, if the other image is also a figure, suggest you just make the white axes an inset axes, or a manually placed axes on the parent figure, not a separate figure?

**Comment by eleminer** [comment]
Do you find any solution for this?

**Comment by tacaswell** [comment]
See the examples in https://matplotlib.org/stable/gallery/index.html#embedding-matplotlib-in-graphical-user-interfaces and https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_tk_sgskip.html#sphx-glr-gallery-user-interfaces-embedding-in-tk-sgskip-py in particular.  

I'm going to close this because in the context of a GUI toolkit we are at the mercy of the window manager etc.   We maybe able to add enough API to control this in limited cases, but ensuring it is consistent across the GUI backends would be a fair amount of work and less-featureful than pointing users to go back to the underlying toolkit.
