### ISSUE TITLE
deprecation of validCap, validJoin makes pydoc spam out many, many warnings

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19080]
### Bug report

**Bug summary**

`pydoc matplotlib.patches` emits many warnings about the deprecation of `validJoin` and `validCap`.  attn @brunobeltran, I guess.

**Code for reproduction**
**Actual outcome**

Per the above.

**Expected outcome**

No warning

**Matplotlib version**

  * Operating system:
  * Matplotlib version: master
  * Matplotlib backend (`print(matplotlib.get_backend())`):
  * Python version: 39
  * Jupyter version (if applicable):
  * Other libraries: 

-----

I guess a solution would be to add a check in `_deprecated_property.__get__` to silence the warning if `sys.argv[0] == pydoc.__file__`.

**Comment by brunobeltran** [comment]
Interesting. I don't see a way around the fact that if we're going to emit a UserWarning on class attribute access, then modules that systematically import/inspect class attributes are going to trigger a computer-generated amount of copies of this warning. 

Even when building our docs, in order to prevent this, there is a special filter ignoring any MatplotlibDeprecationWarnings coming from `sphinx.util.inspect` directly. 

That said, to me this is clearly a case of deprecation warnings causing more annoyance than they do good, since people inspecting the class using standard tools should not be spammed by us.

This issue may be the first concrete argument for why we should make MatplotlibDeprecationWarning an actual DeprecationWarning instead of a UserWarning. The filter that was added in Python ~3.2 (and amended most recently in https://www.python.org/dev/peps/pep-0565/, I think?) prevents this issue if MatplotlibDeprecationWarning is a subclass of DeprecationWarning, as the point of those changes was exactly to hide deprecation warnings from "end users" like someone running `pydoc`.

**Comment by brunobeltran** [comment]
I see three reasonable paths for resolution:

1. Undeprecate validJoin/validCap, assuming that the annoyance of having any inspection of the **many** Patch subclasses for now until 3.6(?) emit unnecessary warnings outweighs the extremely marginal benefit of getting rid of the small code cruft.
2. Document exactly who we intend to see our DeprecationWarnings in the first place, and consider whether or not moving towards MatplotlibDeprecationWarning subclassing DeprecationWarning (which effectively would just change what default warning filters are applied to it, since DeprecationWarning is a UserWarning) might actually be a good idea.
3. Replicate the relevant warnings filter that we *would* be getting from subclassing deprecation warning, but make it specific to matplotlib and to the class attribute access deprecation machinery. While I know the opinion of @tacaswell is that a library shouldn't modify "global state" like the warnings filter list, I think the fact of the matter is that is the only tool that Python provides library writers for dealing with exactly these issues, so it would make sense to use it (like other packages already do).

**Comment by QuLogic** [comment]
Avoiding the larger point, can we deprecate on at least write only?

**Comment by timhoffm** [comment]
Technically, it is sufficient to document the deprecation in API changes. We don't have to issue runtime warnings.  Sure, a runtime warning is more discoverable, but if it's doing more harm than good we can go without it.

**Comment by brunobeltran** [comment]
> Avoiding the larger point, can we deprecate on at least write only?

I can definitely push this, although I'm not sure it's worth the effort, since in this particular case I'm....frankly not sure who we're targeting with that message.

> Technically, it is sufficient to document the deprecation in API changes. We don't have to issue runtime warnings. Sure, a runtime warning is more discoverable, but if it's doing more harm than good we can go without it.

I'll bring this up as a quick point in today's call, that might be the way to go.

**Comment by jklymak** [comment]
Cross ref https://github.com/matplotlib/matplotlib/pull/18817

**Comment by jklymak** [comment]
- suggested during the call that maybe instead of deprecating, `Line2D.valid_JoinStyle` could just call through to `JoinStyle.valid_strings` or whatever top-level class holds that info....

**Comment by QuLogic** [comment]
These deprecations were removed in 3.6, so I guess there's nothing to worry about here any more.
