### ISSUE TITLE
Arrow coordinates slightly off when used with annotation text

### ISSUE THREAD

**Issue by MarinManuel** [matplotlib/matplotlib#19084]
### Bug report

**Bug summary**

When using `annotation()` with an arrow, the position of the arrowhead is slightly off when the annotation text is not empty

**Code for reproduction**

```python
fig, ax = plt.subplots()
xy0 = (0,0.5)
xy1 = (0.5,0.5)
ax.annotate('A', xy0, xy1, arrowprops=dict(arrowstyle='<-', color='k', shrinkA=0, shrinkB=0))
ax.annotate('', xy0, xy1, arrowprops=dict(color='r',arrowstyle='<-', ls='--', shrinkA=0, shrinkB=0))
```

**Actual outcome**

![index](https://user-images.githubusercontent.com/65401298/101681517-86efca80-3a62-11eb-8615-c06cb11721f2.png)

**Expected outcome**
arrows should overlap

**Matplotlib version**

  * Operating system: osx
  * Matplotlib version:  3.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.7.4
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by jklymak** [comment]
Yes, the text end of the arrow is centred on the text, by design.  I can see why that is a little unexpected, but most people put the text at the other end of the arrow (`"->"`) and want the arrow to line up that way. If you just want to draw an arrow there are other ways.  

I don't see a path or reason for us to change this.  Feel free to continue discussion here if you disagree, but I'm going to close. Thanks!

**Comment by MarinManuel** [comment]
Thanks, makes sense. I wasn't sure whether this was a bug or by design. Maybe it would be worth putting a little sentence in the documentation to make this behavior explicit

**Comment by 1nF0rmed** [comment]
Hey, I would like to work on this. Can you point to the specific file?

**Comment by timhoffm** [comment]
The relevant docstring is at

https://github.com/matplotlib/matplotlib/blob/92eccf1d03b439485186bd08920b98e1262f8b31/lib/matplotlib/text.py#L1588
