### ISSUE TITLE
Unexpected error after using Figure.canvas.draw on macosx backend

### ISSUE THREAD

**Issue by mwaskom** [matplotlib/matplotlib#19197]
### Bug report

**Bug summary**

It has [been claimed](https://github.com/matplotlib/matplotlib/issues/18407#issuecomment-687223797) that "fig.canvas.draw() is the canonical way to trigger a draw", replacing `fig.draw(fig.canvas.get_renderer())`. But on the macosx backend, this seems not to work.

**Code for reproduction**

```python
import matplotlib.pyplot as plt
f, ax = plt.subplots()
lines = ax.plot([0, 1])
legend = ax.legend(lines, ["a line"])
f.canvas.draw()
# f.draw(f.canvas.get_renderer())
print(legend.get_window_extent())
```

**Actual outcome**

```python-traceback
Traceback (most recent call last):
  File "mpl_issue.py", line 7, in <module>
    print(legend.get_window_extent())
  File "/Users/mwaskom/miniconda3/lib/python3.7/site-packages/matplotlib/legend.py", line 897, in get_window_extent
    return self._legend_box.get_window_extent(renderer=renderer)
  File "/Users/mwaskom/miniconda3/lib/python3.7/site-packages/matplotlib/offsetbox.py", line 346, in get_window_extent
    w, h, xd, yd, offsets = self.get_extent_offsets(renderer)
  File "/Users/mwaskom/miniconda3/lib/python3.7/site-packages/matplotlib/offsetbox.py", line 462, in get_extent_offsets
    dpicor = renderer.points_to_pixels(1.)
AttributeError: 'NoneType' object has no attribute 'points_to_pixels'
```

**Expected outcome**

On the `qt5agg` backend, or when uncommenting the (deprecated?) `f.draw(f.canvas.get_renderer())` line, the code runs and prints the extent of the legend.

**Matplotlib version**

  * Operating system: Macos
  * Matplotlib version: 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): macosx
  * Python version: 3.8
  * Jupyter version (if applicable): na
  * Other libraries: 

xref https://github.com/matplotlib/matplotlib/issues/18407, https://github.com/mwaskom/seaborn/pull/2399

**Comment by tacaswell** [comment]
The issues appears to be that `draw` defers to `draw_idle` with the OSX backend 
https://github.com/matplotlib/matplotlib/blob/f2c5b37264a48eb7ecf7cc4924bdac7b85acd46f/lib/matplotlib/backends/backend_macosx.py#L48-L51 .  I think the fix is to add a call to `self._draw()` before the `self.draw_idle()` in L50.


I suspect some of this complexity is left from the previous version of the OSX backend which did the rendering via osx-native methods (rather than pushing Agg output into the GUI like it does now (and like the rest of the GUI backends do)) which meant we could not get access to the renderer _except_ when we were handed it by the OSX event loop.

**Comment by mwaskom** [comment]
Is there a good way to programmatically check that the draw actually happened?  i.e so something

```python
fig.canvas.draw()
if not fig.canvas.has_been_drawn():
    fig.draw(fig.canvas.get_renderer())
```

**Comment by tacaswell** [comment]
If you look at `fig.stale` (which comes from `Artist` so every object in the tree has this state).  That state tracks if the artist (or any of its children) have changed from the last time it has rendered.  It get initialized to `False` should should _mostly_ solve the problem you are having.
