### ISSUE TITLE
qhull leaking into matplotlib build

### ISSUE THREAD

**Issue by zlscherr** [matplotlib/matplotlib#19211]
### Bug report

**Bug summary**

I have octave installed via homebrew, and qhull is one of its dependencies.  It would appear that this 2020.1 version of qhull leaks into matplotlib build and causes some methods to crash.  This is on Mac Big Sur 11.1.

**Code for reproduction**

With qhull installed through homebrew and after building matplotlib from source, the following code produces problems.

```python
from matplotlib import tri
tri.Triangulation([1,2,3],[1,2,3])
```

**Actual outcome**

Running that code produces:

```
QH6249 qh_lib_check: Incorrect qhull library called.  Size of qhT for caller is 2896, but for library is 2792.
QH6256 qh_lib_check: Cannot continue.  Library 'qhull 7.2.0 (2015.2 2016/01/18)' uses a static qhT (e.g., libqhull.so)
```

**Expected outcome**

**Matplotlib version**

This occurs in version 3.3.3 installed via

```
pip install matplotlib --no-binary :all:
```

with homebrew qhull installed.  The wheel for matplotlib works fine, but I've been using matplotlib via SageMath where it is built from source, and so I've encountered this issue.

Thanks!

**Comment by tacaswell** [comment]
If you are installing from source and have an externally provided qhull the best option is to set the `system_qhull = True` in `setup.cfg` , see https://github.com/matplotlib/matplotlib/blob/a8f52d977b30965dc3b7d71f73feeb9f96a2721b/setup.cfg.template#L8-L16  in the template which will make the source install of Matplotlib find and use the homebrew version of qhull (rather than using our vendor ed version).

**Comment by zlscherr** [comment]
Thank you!
