### ISSUE TITLE
Bbox.frozen() does not copy minposx/minposy

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#19296]
### Bug report

**Bug summary**

All's in the title.

One use case which showcases this is to prevent an artist from participating in autoscaling (in effect, a slightly hackish way to implement something like https://github.com/matplotlib/matplotlib/pull/15595):
```python
ax = ...
dl = ax.dataLim.frozen()
ax.plot(...)
# restore old datalim, so that plot() does not participate in autoscale
ax.dataLim = dl
```
which works... except for log-scale, as that needs also copying minposx/minposy.

**Code for reproduction**

```python
from pylab import *
plot([1, 2]); print(gca().dataLim.minposx, gca().dataLim.frozen().minposx)
```

**Actual outcome**

```
1.0 inf
```

**Expected outcome**

```
1.0 1.0
```

**Matplotlib version**

  * Operating system: linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): master (3.3.x)
  * Matplotlib backend (`print(matplotlib.get_backend())`): any
  * Python version: 3.9
  * Jupyter version (if applicable):
  * Other libraries:

**Comment by Monishver** [comment]
Hello @anntzer , I'm new to open source, and would like to contribute to this issue, could you explain this issue more and navigate me a little bit.

**Comment by story645** [comment]
hi @Monishver! check out our development guide at https://matplotlib.org/devdocs/

The issue is that the method `frozen` on BBoxes parent (https://github.com/matplotlib/matplotlib/blob/6530db191bab108ff6400dc174db54fae9c4002d/lib/matplotlib/transforms.py#L259) does not include the minposx/minposy properties of the BBox child class. 

One possible solution is for `Bbox` to implement its own frozen method but there are probably others.

**Comment by Monishver** [comment]
Thanks for giving a detailed overview, I have started looking into it and will try to implement it in few days.

**Comment by viditostwal** [comment]
I am new to open source and I trying to know about this issue, can you @story645 please tell how adding frozen in the Bbox class would help to resolve this issue

**Comment by story645** [comment]
If you overload 'frozen' inside by implementing it inside BBox, than you can add whichever of BBox's attributes (such as miniposx and minposy) to the attributes returned in the frozen version. 

Another option is extending BBox.get_points but I don't like that approach since miniposx and miniposy aren't points.

**Comment by jklymak** [comment]
I've reclassified this - I don't think anything that touches the `minpos` machinery is a "Good first issue".  Maybe its "Easy" if you know what `minpos` is and understand its use in the library, but given that it is almost undocumented, that requires digging through the code.  Thats not to preclude this being a "first issue", but first time contributors should expect to do said digging.
