### ISSUE TITLE
Packrat caching in _mathtext.py is enabled globally for pyparsing

### ISSUE THREAD

**Issue by arekfu** [matplotlib/matplotlib#19391]
### Bug report

**Bug summary**

Enabling packrat caching for the mathtext pyparsing parser ([here](https://github.com/matplotlib/matplotlib/blob/dd249744270f6abe3f540f81b7a77c0cb728ddbb/lib/matplotlib/_mathtext.py#L29)) does so globally, for any other pyparsing parser. In my application packrat caching slows parsing down by a factor of 2, and so does importing `matplotlib`.

**Code for reproduction**

```python
import pyparsing as pp
import timeit

parser = pp.OneOrMore(pp.Word(pp.printables))

text = '''Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim
veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat.'''

print('before importing matplotlib: {}'
      .format(timeit.timeit(lambda: parser.parseString(text), number=1000)))

import matplotlib.pyplot

print('after importing matplotlib: {}'
      .format(timeit.timeit(lambda: parser.parseString(text), number=1000)))
```

**Actual outcome**

```shell
$ python3 pp.py
before importing matplotlib: 0.2993983749765903
after importing matplotlib: 0.5376854920759797
```

**Expected outcome**

The timing should be comparable between the two code versions. I would appreciate if matplotlib provided a configuration option to turn on/off packrat caching for the mathtext parser.

**Matplotlib version**

  * Operating system: CentOS 7 and Ubuntu 16
  * Matplotlib version: 3.3.4
  * Matplotlib backend: agg
  * Python version: 3.6.8
  * Other libraries: obviously `pyparsing`

I installed matplotlib using `pip install matplotlib`.

**Comment by arekfu** [comment]
Incidentally, I haven't checked if there are other parsers in `matplotlib` that use `pyparsing` and turn on packrat caching.

**Comment by anntzer** [comment]
I think your best bet is to require pyparsing>=3 which provides `ParserElement.disable_memoization()`, and call that whereever you need.  Unfortunately, I don't think a configuration option really makes sense, because you can (usually) not be sure that no one imported matplotlib even before you set the config option (and if we were to provide a callable such as `mpl.mathtext.disable_packrat()`, you may just as well directly call the corresponding pyparsing API).

Perhaps pyparsing should provide per-parser memoization states, but that's tracked at https://github.com/pyparsing/pyparsing/issues/267.

We *could* add a doc entry somewhere -- any suggestions? but other than that I'd suggest closing this as non-actionable.

**Comment by anntzer** [comment]
Closing per the above (the switch is provided by pyparsing now).
