### ISSUE TITLE
.whl import libpng = 1.6.21

### ISSUE THREAD

**Issue by lh-yw** [matplotlib/matplotlib#19442]
matplotlib == 3.2.0 ,libpng = 1.6.21

libpng has some unclear pointer arithmetic problems.

- CVE-2018-13785
- CVE-2018-14550
- CVE-2016-10087
- CVE-2017-12652
- CVE-2019-7317

**Comment by jklymak** [comment]
Can you clarify what the issue is?

**Comment by lh-yw** [comment]
matplotlib-3.2.0-cp38-cp38-manylinux1_x86_64.whl
matplotlib-3.2.1-cp38-cp38-manylinux1_x86_64.whl
matplotlib-3.2.2-cp38-cp38-manylinux1_x86_64.whl
contains libpng.so(=1.6.21) file, libpng has serial CVEs

**Comment by QuLogic** [comment]
In the future, if you want to report security issues, you should disclose responsibly and follow the procedures lined out by projects. The security process was outlined in an option in the New issue template selection, and it was not to open a public bug report.

I have looked through said security issues, and do not see any reason to issue any new releases:

> * CVE-2018-13785

This bug is an issue in 1.6.34, which is newer than the version in Matplotlib wheels.

> * CVE-2018-14550

This bug is an issue in PNM decoding in the `pnm2png` executable, not used by Matplotlib.

> * CVE-2016-10087

This bug is an issue in `png_set_text_2`, not used by Matplotlib.

> * CVE-2017-12652

This bug is that libpng does not check chunk sizes against user limits set by `png_set_user_limits`, but Matplotlib does not set a user limit and relies on the default.

> * CVE-2019-7317

This bug is an issue in `png_image_free`, not used by Matplotlib.
