### ISSUE TITLE
Unexpected Tricontour behaviour in polar projection

### ISSUE THREAD

**Issue by skogsvik** [matplotlib/matplotlib#19492]
### Bug report

**Bug summary**

When using tricontour and tricontourf in polar projection, some levels will jump across the plot rather than cross over the periodic border at 0/360 degrees.

**Code for reproduction**

```python
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import tri


def function_z(x, y):
    # Example data taken from https://matplotlib.org/3.3.4/gallery/images_contours_and_fields/tricontour_smooth_user.html#sphx-glr-gallery-images-contours-and-fields-tricontour-smooth-user-py
    r1 = np.sqrt((0.5 - x)**2 + (0.5 - y)**2)
    theta1 = np.arctan2(0.5 - x, 0.5 - y)
    r2 = np.sqrt((-x - 0.2)**2 + (-y - 0.2)**2)
    theta2 = np.arctan2(-x - 0.2, -y - 0.2)
    z = -(2 * (np.exp((r1 / 10)**2) - 1) * 30. * np.cos(7. * theta1) +
          (np.exp((r2 / 10)**2) - 1) * 30. * np.cos(11. * theta2) +
          0.7 * (x**2 + y**2))
    return (np.max(z) - z) / (np.max(z) - np.min(z))


# Generate random unordered grid of polar coordinates
np.random.seed(2685)
radius, azimuth = np.meshgrid(np.pi*np.random.random(14), 2*np.pi*np.random.random(35), indexing='ij')

radius = radius.ravel()
azimuth = azimuth.ravel()

# Perform triangulation in cartesian coordinates to account for periodicity in azimuth
x = radius*np.cos(azimuth)
y = radius*np.sin(azimuth)
triangles = tri.Triangulation(x, y).get_masked_triangles()

z = function_z(x, y)

# Polar tricontour with triangulation from cartesian
ax = plt.figure().add_subplot(111, polar=True)
ax.tricontour(azimuth, radius, triangles, z)
# ax.scatter(azimuth, radius, 1, 'r')

# Cartesian tricontour with triangulation from cartesian
fig = plt.figure()
ax_polar = fig.add_subplot(111, polar=True, frameon=True)
ax_cart = fig.add_subplot(111, polar=False, frameon=False)
ax_cart.tricontour(x, y, triangles, z)
# ax_cart.scatter(x, y, 1, 'r')
ax_cart.axis('equal')
ax_cart.get_xaxis().set_visible(False)
ax_cart.get_yaxis().set_visible(False)
plt.show()

```

**Actual outcome**
![actual](https://user-images.githubusercontent.com/21970817/107508679-b1185280-6ba1-11eb-9c8d-499f219dc6d6.png)

**Expected outcome**
![expected](https://user-images.githubusercontent.com/21970817/107509902-80d1b380-6ba3-11eb-8991-a3134c3af660.png)

**Matplotlib version**

  * Operating system: Microsoft Windows 10 Pro (10.0.19042 Build 19042)
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.8.1 64 bit
  * Jupyter version (if applicable): N/A
  * Other libraries: numpy: 1.16.1
 
Note that this same behavior seems to exist in older versions of Python and matplotlib as well as with the Qt5Agg backend.

All packages installed via pip

**Comment by ianthomas23** [comment]
Hi @skogsvik, thanks for the high quality report.

Your problem is the combination of these two lines:

```python
triangles = tri.Triangulation(x, y).get_masked_triangles()
ax.tricontour(azimuth, radius, triangles, z)
```
You are calculating the triangulation in x-y coordinates, but then displaying the results in radius-azimuth coordinates.  Points that are near to each other in x-y coordinates are not necessarily near to each other in radius-azimuth coords and so the result is a mess.  You need to both calculate and display in radius-azimuth coordinates.

As you have identified, you cannot naively triangulate in radius-azimuth coords as there is a discontinuity at `0` and `2*pi` radians and this will result in a gap.  The standard approach to deal with this is to add an extra 2 pairs of points to the triangulation at azimuth = `0`, `2*pi` and the min and max of the radius.  This will ensure that the triangulation, and hence the contours, will extend to the join at `0` and `2*pi` from both directions so that when these are wrapped around to display they meet neatly.

Under some circumstances you need to add more than 2 pairs of points along the `0`, `2*pi` boundary and may have to do some interpolation/extrapolation to obtain reasonable z-values for these points.

Example image and script (modified from yours) below.  Note that this is not strictly a polar coordinates problem as it also occurs in the cartesian radius-azimuth plot as well.

Ian

![response](https://user-images.githubusercontent.com/580326/107627197-de730800-6c56-11eb-9d95-a4dfb57f3a67.png)

```python
import numpy as np
from matplotlib import pyplot as plt
from matplotlib import tri

def function_z(x, y):
    r1 = np.sqrt((0.5 - x)**2 + (0.5 - y)**2)
    theta1 = np.arctan2(0.5 - x, 0.5 - y)
    r2 = np.sqrt((-x - 0.2)**2 + (-y - 0.2)**2)
    theta2 = np.arctan2(-x - 0.2, -y - 0.2)
    z = -(2 * (np.exp((r1 / 10)**2) - 1) * 30. * np.cos(7. * theta1) +
          (np.exp((r2 / 10)**2) - 1) * 30. * np.cos(11. * theta2) +
          0.7 * (x**2 + y**2))
    return (np.max(z) - z) / (np.max(z) - np.min(z))

radius, azimuth = np.meshgrid(np.pi*np.random.random(14), 2*np.pi*np.random.random(35), indexing='ij')
radius = radius.ravel()
azimuth = azimuth.ravel()

# Add 4 extra points to triangulation.
rmin, rmax = radius.min(), radius.max()
radius = np.append(radius, [rmin, rmax, rmin, rmax])
azimuth = np.append(azimuth, [0.0, 0.0, 2*np.pi, 2*np.pi])

x = radius*np.cos(azimuth)
y = radius*np.sin(azimuth)
# Triangulations in cartesian (x, y) and polar (radius, azimuth) coordinates.
triangles_xy = tri.Triangulation(x, y).get_masked_triangles()
triangles_ra = tri.Triangulation(radius, azimuth).get_masked_triangles()

z = function_z(x, y)

fig = plt.figure()

ax = fig.add_subplot(221)
ax.tricontour(azimuth, radius, triangles_xy, z)
ax.set_title('Calculate in xy-space, display in ra-space')
ax.set_ylabel('radius')

ax = fig.add_subplot(222, polar=True)
ax.tricontour(azimuth, radius, triangles_xy, z)
ax.set_title('Calculate in xy-space, display in ra-space')

ax = fig.add_subplot(223)
ax.tricontour(azimuth, radius, triangles_ra, z)
ax.set_title('Calculate and display in ra-space')
ax.set_xlabel('azimuth')
ax.set_ylabel('radius')

ax = fig.add_subplot(224, polar=True)
ax.tricontour(azimuth, radius, triangles_ra, z)
ax.set_title('Calculate and display in ra-space')

plt.show()
```

**Comment by skogsvik** [comment]
Thank you @ianthomas23 for the prompt and thorough answer.
I am happy to hear that this is a user error rather than a bug! It makes it much easier to fix.

I should've realized that the polar projection is just that, a projection, and does not necessarily account for the periodicity at 2 pi.
In my debugging I saw the same issues in the cartesian projection but assumed it to be due to the lack of periodicity.

I will have to think if there is a consequence of copying the closest azimuth points to the 0 / 2pi border along a straight line or if I need to interpolate them.
