### ISSUE TITLE
Allow saving PDF files without a page group

### ISSUE THREAD

**Issue by bersbersbers** [matplotlib/matplotlib#19506]
### Problem

My problem is shown with this code, creating `bug.pdf` with `matplotlib` and then reusing that figure in `pdflatex`:

```
echo "import matplotlib.pyplot as plt;plt.figure();plt.savefig('bug.pdf')" | python3 -
cp bug.pdf bug2.pdf
echo "\documentclass{article}\usepackage{graphicx}\begin{document}
\includegraphics[height=1in]{bug}\includegraphics[height=1in]{bug2}
\end{document}" | pdflatex | grep -A 1 warning
```

What's the problem?
> pdfTeX warning: pdflatex (file ./bug2.pdf): PDF inclusion: multiple pdfs with page group included in a single page

Find a lot of information on this problem at https://tex.stackexchange.com/a/78020/30810

What solves the problem in my case is deleting the page group (by replacing with spaces to maintain file size):

```
grep -a Group bug.pdf
sed -i 's-/Group << /CS /DeviceRGB /S /Transparency /Type /Group >>-                                                         -' bug.pdf
cp bug.pdf bug2.pdf
echo "\documentclass{article}\usepackage{graphicx}\begin{document}
\includegraphics[height=1in]{bug}\includegraphics[height=1in]{bug2}
\end{document}" | pdflatex | grep -A 1 warning
```

No warning!

### Proposed Solution

1. Allow skipping the (optional!) `Group` element in this code block to increase compatibility with `pdflatex`:

https://github.com/matplotlib/matplotlib/blob/7e3cef3ba8c62d79491a94db26c5b06904d9944e/lib/matplotlib/backends/backend_pdf.py#L730-L741

2. Ideally, determine if transparency is needed and skip the element only if not.

**Comment by anntzer** [comment]
I had a quick look at the pdf spec.  Can we just get rid of the page group and instead set the colorspace using /CS and /cs? (See the description of these operators at the end of section 8.6.3.)

**Comment by jkseppan** [comment]
I don't know any immediate reason not to use @anntzer's solution, but I do know that pdf files get used in various different environments, some of which don't follow the spec. But I suspect that pdftex is the most important way to embed our pdf files into other documents, so if that patch fixes a problem with pdftex, we might as well apply it and wait for any bug reports from people using other software. Ideally we'd test with other software as well, but I don't have access to the full Adobe Acrobat so that test would have to be done by someone else.
