### ISSUE TITLE
Adding lightsource when plotting Poly3DCollection

### ISSUE THREAD

**Issue by n2d7** [matplotlib/matplotlib#19509]
I am trying to visualize a .stl file using the libraries numpy-stl and mplot3D. 
```

new_mesh = mesh.Mesh.from_file('result.stl')
figure = plt.Figure(figsize=(6.4,5.4), dpi=100) 
ax = mplot3d.Axes3D(figure)
ax.add_collection3d(mplot3d.art3d.Poly3DCollection(new_mesh.vectors))
```

But in the plot we can barely see any features and its quite flat. Is it possible to add a `lightsource `option for Poly3DCollections.
![mplot3d plot](https://user-images.githubusercontent.com/71412585/107866345-dec40b00-6ec3-11eb-8b45-347ef01d2fef.PNG)

**Comment by oscargus** [comment]
This is more or less implemented in `Axes3D.plot_surface`:

https://github.com/matplotlib/matplotlib/blob/cf38c3464ebdbc66eee97222445f9b861ac1a395/lib/mpl_toolkits/mplot3d/axes3d.py#L1467-L1490

I guess an option is to add a method, `shade_polygon` to `Poly3DCollection`, or something, that basically does relevant parts of the above code.

I mark is as a good first issue since there is template code, but probably medium as it requires a bit of thinking. For example, which parameters to use.

**Comment by oscargus** [comment]
Another option, if someone bumps into this, is to provide `edgecolors`, which they at least will result in the edges being articulated.
