### ISSUE TITLE
ax.get_tightbbox chops of right axis

### ISSUE THREAD

**Issue by randolf-scholz** [matplotlib/matplotlib#19557]
### Bug report

**Bug summary**

I was trying to save a subplot using the suggestion of using [`ax.get_tightbbox`](https://matplotlib.org/3.3.4/api/_as_gen/matplotlib.axes.Axes.get_tightbbox.html) given here https://stackoverflow.com/a/26432947/9318372. However, the tightbbox chops of the right axis. Also, `ax.get_tightbbox` doesn't seem to play nice with `tight_layout`.

**Code for reproduction**

```python
import matplotlib.pyplot as plt

fig, axes = plt.subplots(ncols=2, figsize=(6, 2), tight_layout=None)
fig.set_facecolor('xkcd:mint green')
axes[0].plot(range(10), 'b-')
axes[0].set_title("blue line")
axes[1].plot(range(10), 'r^')
axes[1].set_title("red triangles")

fig.savefig(F"full_image.png")
renderer = fig.canvas.get_renderer()
transform = fig.dpi_scale_trans.inverted()

for k, ax in enumerate(axes):
    ax_extent = ax.get_tightbbox(renderer)
    fig.savefig(F"ax{k}.png", bbox_inches=ax_extent.transformed(transform), pad_inches=0)

    bbox_extra_artists = ax.get_default_bbox_extra_artists()
    bbox_extra_artists += ax.get_xticklabels()
    bbox_extra_artists += ax.get_yticklabels()

    ax_extent = ax.get_tightbbox(renderer, bbox_extra_artists=bbox_extra_artists)
    fig.savefig(F"ax{k}_with_extra_artists.png", bbox_inches=ax_extent.transformed(transform), pad_inches=0)
```

**Actual outcome**

The right axis gets chopped off

Original:
![full_image](https://user-images.githubusercontent.com/39696536/108707354-2a079a80-7510-11eb-8a5b-b336754d754c.png)

`tightbbox`: Using ` ax.get_tightbbox(fig.canvas.get_renderer()).transformed(fig.dpi_scale_trans.inverted())` - the right axis gets chopped off
![ax0](https://user-images.githubusercontent.com/39696536/108707342-25db7d00-7510-11eb-80a4-ad15a46f2335.png) ![ax1](https://user-images.githubusercontent.com/39696536/108707360-2d9b2180-7510-11eb-9326-98faac5f4203.png)
`tightbbox` + `bbox_extra_artists`: Manually adding `xticklabels` and `yticklabels` as extra artists - too much space added, for the second ax even some parts of the first plot get captured
![ax0_with_extra_artists](https://user-images.githubusercontent.com/39696536/108707287-13614380-7510-11eb-81e9-f93122858caa.png) ![ax1_with_extra_artists](https://user-images.githubusercontent.com/39696536/108707373-2ffd7b80-7510-11eb-8b37-970f2ba5eaf8.png)

-----

If we construct the figure via `plt.subplots(..., tight_layout=True)` all hell breaks loose:

Original + `tight_layout`
![full_image](https://user-images.githubusercontent.com/39696536/108707681-aef2b400-7510-11eb-96f7-60000ab93071.png)

`tightbbox` + `tight_layout`
![ax0](https://user-images.githubusercontent.com/39696536/108707685-b0bc7780-7510-11eb-88cf-aa5019fb5dd4.png) ![ax1](https://user-images.githubusercontent.com/39696536/108707689-b31ed180-7510-11eb-984d-6fe41a36525d.png)

`tightbbox` + `bbox_extra_artists` + `tight_layout`
![ax0_with_extra_artists](https://user-images.githubusercontent.com/39696536/108707705-b87c1c00-7510-11eb-8b99-8c1158c8dde3.png) ![ax1_with_extra_artists](https://user-images.githubusercontent.com/39696536/108707711-bade7600-7510-11eb-9eea-6956f64c4857.png)

**Expected outcome**

**Matplotlib version**

  * Operating system: Ubuntu 20.04.2 LTS
  * Matplotlib version (`3.3.4`): 
  * Matplotlib backend (`agg`): 
  * Python version: 3.9.2 | packaged by conda-forge | (default, Feb 21 2021, 05:02:46) 

-----

**PS:** Another potential issue  I noticed in the [source code of get_tightbbox](https://github.com/matplotlib/matplotlib/blob/9a242b26eaa16f07d41e5c2ba1ba8f8f609c841c/lib/matplotlib/axes/_base.py#L4383): at line 4472 we have 

```python
bbox_artists = bbox_extra_artists
if bbox_artists is None:
    bbox_artists = self.get_default_bbox_extra_artists()

for a in bbox_artists:
    ....
```

But one probably wants that if the user specifies some `bbox_extra_artists`, that the `default_bbox_extra_artists` get added anyway!, i.e.

```python
bbox_artists = self.get_default_bbox_extra_artists()
if bbox_extra_artists is not None:
    bbox_artists += bbox_extra_artists

for a in bbox_artists:
    ....
```

**Comment by jklymak** [comment]
`tight_layout` tries to resize the axes to fit, so you are facing an uphill climb if you are resizing, and then trimming them due to the extent before they were resized.  You can do it, but better to turn tight layout off before grabbing the extent.

As to your first problem, I'd say everything is working as expected, it is just that the "extent" doesn't know about the line thickness and thus the line doesn't draw.  You can fix this by simply adding a bit of a margin:

```python
for k, ax in enumerate(axes):
    ax_extent = ax.get_tightbbox(renderer)
    bbox = ax_extent.transformed(transform).padded(2/72) # add 2 pts of padding
    fig.savefig(F"ax{k}.png", bbox_inches=bbox)
```
Note `pad_inches` is only used when `bbox_inches='tight'` so playing with that will not help your handmade bbox.  

I'm not sure why you have added the tick labels in the extra artists.  `ax.get_tightbbox` always includes the tick labels *after* their position has been properly adjusted.  Doing so like this will lead to errors.  

I think everything is working as expected.  You could argue that the extent could detect the width of line, or that the line should not be clipped, but that is impossible to do in general, so you should simply add a bit of padding.   I'll close, but feel free to continue the conversation, or discuss more at discourse.matplotlib.org.

> But one probably wants that if the user specifies some bbox_extra_artists, that the default_bbox_extra_artists get added anyway!, 

Then we have no way for the user to leave an artist out of the calculation.  (well they can set `artist.in_layout(False)`)
