### ISSUE TITLE
code of conduct link 404s

### ISSUE THREAD

**Issue by pseyfert** [matplotlib/matplotlib#19594]
The link to the code of conduct at the top of https://matplotlib.org/devdocs/devel/contributing.html leads to https://matplotlib.org/CODE_OF_CONDUCT.md, which gives me a 404 error.

**Comment by jklymak** [comment]
I *guess* that is supposed to be: https://github.com/matplotlib/matplotlib/blob/master/CODE_OF_CONDUCT.md but I'm not sure what the plan was there...  @story645 ?

**Comment by story645** [comment]
Yeah I think the plan had been to find a way to just render the MD page in sphinx but yes for now the link should be to the GitHub page

**Comment by Aadi71** [comment]
It is supposed to be: https://www.python.org/psf/conduct/ as a python software foundation code of conduct.

**Comment by jklymak** [comment]
> It is supposed to be: https://www.python.org/psf/conduct/ as a python software foundation code of conduct.

No that's the existing page, but we changed it for 3.4.

**Comment by Aadi71** [comment]
Hello sir, I hope this mail finds you in pink of health.
Sir, I am Aadi Jain a first-year B.TECH CSE undergrad from India.
I want to start and learn about open source contributions to ameliorate my
knowledge and to solve real-world problems. .
That's why maybe I made a mistake and I apologize for that and I can assure
you sir I want to nourish my skills by these mistakes.
Considering the fact I am facing a little bit of problem as I had never
contributed to these big projects. So, I request you to guide me on the
veracious pathway to contribute to such projects.

Thanking you in anticipation.
