### ISSUE TITLE
Promote _Backend to public api

### ISSUE THREAD

**Issue by ianhi** [matplotlib/matplotlib#19605]
### Problem
Discussed on gitter here: https://gitter.im/matplotlib/matplotlib?at=603c83fc44f5a454a447c6e9

The `_Backend` class added in matplotlib/matplotlib#8773 would be useful for external backends such as ipympl, and is already used by mplcairo. But it is currently marked as a private.

### Proposed Solution
1. Make `_Backend` public
2. Document `_Backend` as stable.

**Comment by anntzer** [comment]
The reason it's already used by mplcairo is because I essentially designed and implemented _Backend for that purpose :-)

I actually think making _Backend public is not best (because `@_Backend.export` is pretty weird); I have a better solution in mind (starting from something along the lines of https://github.com/matplotlib/matplotlib/pull/18854, please review :-)).  I'll try to post a longer writeup later.

**Comment by anntzer** [comment]
@ianhi Actually, I just realized that there's (I think, probably... but see PS below) a much simpler solution (that should get documented) available for you (because you don't "inherit" from another _Backend).  Taking https://github.com/matplotlib/ipympl/pull/305/ as a starting point, you can just get rid of `_Backend_ipympl`, moving FigureCanvas, FigureManager, new_figure_manager_given_figure(), and show() to be toplevel definitions, and that should be all that's needed.  (Then your module will not define its own new_figure_manager, which *could* be considered an API break if you consider that that's public API, but at least Matplotlib will be fine with it because it internally generates a shim to replace it, see https://github.com/matplotlib/matplotlib/blob/0a4a10c5a19a0a08dac53202c3cb091fed99d4c2/lib/matplotlib/pyplot.py#L245-L253.)  In fact, you could perhaps even consider making the additional (transparency handling) code in new_figure_manager_given_figure() to either `Canvas.__init__` or `FigureManager.__init__` (whichever makes more sense), and then you could then get rid of the definition of new_figure_manager_given_figure as well, again relying on the Matplotlib-generated shim.

(PS: I remembered this point while working on a toy backend; I tried to check whether this works specifically for ipympl but once again I couldn't make Matplotlib work in Jupyter notebooks and I have limited patience in fiddling with that :-))

**Comment by anntzer** [comment]
Superseded by https://github.com/matplotlib/matplotlib/pull/22925, I would say
