### ISSUE TITLE
Avoid showing a black background before the plot is ready with Qt5agg backend 

### ISSUE THREAD

**Issue by hppi-johnsson** [matplotlib/matplotlib#19755]
When I open a window to show a plot, the background of the canvas is first black for some time until the plot is ready. This can be up to several seconds for large datasets.
This is just a cosmetic annoyance, since the user experiences a "flickering" of the window.

I am using using Matplotlib 3.3.4 with Qt5 on Windows 10.
In an older release I used before (1.4.2 with Qt4) the window is not shown until the plot is ready, so the issue is never seen.

I suggest that the background color of the widget is shown before the plot is drawn.

**Comment by tacaswell** [comment]
This is somelpace in the Qt widget start up code.  It is a good first issue as there is no API design discussion required and I suspect very little understanding of Matplotlib internals required, but medium difficulty as it will requires knowing how the Qt APIs work and reading through our GUI setup code.

It is possible that the black coloring is coming from Qt and is drawn before we have any chance to influence it, but I would be surprised.

**Comment by QuLogic** [comment]
I experimented with this, and there is unfortunately nothing we can do without a fix occurring in Qt.

According to Qt docs, Windows are filled with the `QPalette::Window` colour unless the `WA_OpaquePaintEvent` attribute is set. This attribute is set on the canvas, but not on the window. You can also set `QWidget::autoFillBackground` to do the same.

Using `QPalette` or `setStyleSheet`, you can see that it's effective by the toolbar changing backgrounds (but not the canvas, since we draw that all ourselves). However, when things are slow, _even the toolbar_ is initially drawn in black, disregarding the stylesheet or palette.

So we can't really do anything about this without a change in Qt.
