### ISSUE TITLE
Add support for 3d plots to align the y axis vertically instead of the z axis

### ISSUE THREAD

**Issue by Illviljan** [matplotlib/matplotlib#19791]
### Problem
I have a hard time grasping what happens when jumping between 2d and 3d scatters because the y changes from the vertical direction to the depth direction.

![image](https://user-images.githubusercontent.com/14371165/112721976-30ba7080-8f07-11eb-972b-dea2a3f16128.png)

### Proposed Solution
A simple way to tell matplotlib to put the y axis vertically instead of the z axis. Either by improving `zdir` or adding a new parameter.
This will make it easier to visualize what happens since we are rotating this block of data as little as possible and it makes it easy to continue working with the plot as all x,y,z-methods continues to make sense.

The hack of interchanging the data and labels works if all you want is to get the plot working. But it gets rather unintuitive for downstream users if they want to further process the plot with for example `set_ylim` or `set_zlim`.

Rotating with ax.view_init() is very difficult or impossible to get good as it's difficult to get the same init angles and in interactive mode it feels completely opposite to rotate compared to the normal settings.

### Example code

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.array([0, 1, 2, 4])
y = np.array([5, 10])
z = np.array([100, 150, 200])
X, Y, Z = np.meshgrid(*[x, y, z], indexing="ij")
c = np.arange(0, X.size)


ax = plt.subplot(1, 3, 1)
ax.scatter(X, Y, c=c)
ax.set_title("x, y-plot, difficult to tell what's going on.")
ax.set_xlabel("x")
ax.set_ylabel("y")

ax = plt.subplot(1, 3, 2, projection="3d")
ax.scatter(X, Y, Z, c=c)
ax.set_title(
    "3d plot, but now y is going in the depthwise direction.\nHave to relearn the plot."
)
ax.set_xlabel("x")
ax.set_ylabel("y")
ax.set_zlabel("z")

ax = plt.subplot(1, 3, 3, projection="3d")
ax.scatter(X, Z, Y, c=c)
ax.set_title(
    (
        "Interchange y and z, intuitive and builds on top of 2dplot\n"
        "But now set_*labels doesn't make sense."
    )
)
ax.set_xlabel("x")
ax.set_ylabel("z")
ax.set_zlabel("y")
```

**Comment by timhoffm** [comment]
Neither `zdir` nor juggling the data is suitable for this.

As far as I understand the request, this is *only* about rotating the view so that some axis is pointing up. The problem is that the current rotation is only based on two values (*azimuth* and *elevation*) which still has a preferred axis and cannot express all view angles. I don't think we can or want to switch to a more general rotation because that also would need different controls. However, i could imagine extending the API to `view_init(elev, azim, vertical_axis='y')`. The `vertical_axis` would have to be processed in `get_proj()`.
