### ISSUE TITLE
Deprecation warning when building API doc for Polygon subclass

### ISSUE THREAD

**Issue by pllim** [matplotlib/matplotlib#19850]
We started seeing deprecation warning while building doc and unfortunately we have set ReadTheDocs build to fail on warnings. After some investigation, it turned out that this is the perfect storm of the following conditions:

1. We have a class inheriting from `matplotlib.patches.Polygon`.
2. Sphinx automatically inherits docstrings for subclasses, which is desirable for this case.
3. We use a Sphinx extension calling [getattr(obj, attr, *defargs)](https://github.com/astropy/sphinx-automodapi/blob/f66e58254e58220f49a30b6c66280d8e2d940c9e/sphinx_automodapi/autodoc_enhancements.py#L71).
4. You have deprecated `validCap` and `validJoin` here:

https://github.com/matplotlib/matplotlib/blob/7f9d84a0603424917a521df03cb96a23696ae001/lib/matplotlib/patches.py#L42-L52

I am not sure what is the best fix. I can maybe overwrite the docstring of those two methods in subclasses but it is not elegant. Advise is appreciated. Thanks!

xref astropy/astropy#11458 and astropy/sphinx-automodapi#125

**Comment by jklymak** [comment]
Please see #19839

**Comment by timhoffm** [comment]
This is a different issue than #19839.

**Comment by timhoffm** [comment]
I think there is nothing we can do about this on the Matplotlib side. With the `@_api.deprecated` decorator we intentionally warn if somebody uses these attributes. Your sphinx extension accesses these attributes, so you get the warning.

If you are sure that nobody accesses these attributes in your subclass, you can overwrite them

```
class SpecialPolygon(Polygon):
    validCap = None
```

**Comment by pllim** [comment]
Thanks for the response. I did try to not inherit the docstring but to no avail. I'll try your suggestion when you get the chance, though right now RTD isn't complaining, but maybe it will again when the monkeypatch in #19839 is reverted. 🤷

**Comment by timhoffm** [comment]
This does not directly have to do with docstrings. The warning will occur if you access the property. - Whether your sphinx extension does that or not somewhat depending on the docstring I cannot tell. The monkey-patch should not affect the deprecation warning.

I'll leave this closed as I don't think it's actionable from our side. But you are welcome to report back if the issue comes back again.

**Comment by pllim** [comment]
That makes sense, I am okay with closing this issue.

To wrap things up, unfortunately https://github.com/matplotlib/matplotlib/issues/19850#issuecomment-816227976 does not work for us.

I guess there is no reason for `sphinx-automodapi` to access all the attributes but it is not a rabbit hole I want to jump in currently.

**Comment by brunobeltran** [comment]
@pllim Sorry I'm late to the party, but it may make sense to silence specifically DeprecationWarning's coming specifically from whatever extension module is throwing these errors. 

> I guess there is no reason for `sphinx-automodapi` to access all the attributes but it is not a rabbit hole I want to jump in currently.

Matplotlib's conf.py solves this problem by simply filtering out DeprecationWarnings for class-level attributes (and module level deprecations). For example, for sphinx-autodoc, the following filter works:

```python
# make sure to ignore warnings that stem from simply inspecting deprecated
# class-level attributes
warnings.filterwarnings('ignore', category=DeprecationWarning,
                        module='sphinx.util.inspect')
```

This is basically a perfect storm in terms of Python warning semantics. There really is no reasonable way for sphinx (or any other "autodoc" style code) to parse the docstrings of all attributes of a class without a `getattr(cls, attr)` call, but there's also no reasonable way for us to trigger a DeprecationWarning without doing so on `getattr(cls, attr)`.

That said, since sphinx-automodapi is internal to you guys, if I were you I would just silence the warnings at the `getattr` site. In fact, I should probably open a PR that does exactly that for sphinx-autodoc.
