### ISSUE TITLE
Causes error when log is zero, can be fixed by adding a very small value like 1e-9 to spec. 

### ISSUE THREAD

**Issue by jacobmcasey** [matplotlib/matplotlib#19914]
https://github.com/matplotlib/matplotlib/blob/c7a01db84b57f0e8774c3052a255cc02d2cf699f/lib/matplotlib/axes/_axes.py#L7706

**Comment by tacaswell** [comment]
Can you be a bit clearer what you mean by "error"?  

Adding small constant offsets to floats is something that has historically is Matplotlib ended up causing more problems than it solved....

**Comment by jklymak** [comment]
Well, `np.log10(0)` will of course error, but since `spec` is positive definite unless x is all zeros, I think the user should catch this before calling `specgram`

I would strongly recommend using https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.spectrogram.html, and plotting using pcolormesh or imshow.

**Comment by tacaswell** [comment]
numpy spits out a warning, but does not error out

```
In [13]: np.log10(np.array([1, 2.56, 0, 3]))
<ipython-input-13-96102dee3f4b>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(np.array([1, 2.56, 0, 3]))
Out[13]: array([0.        , 0.40823997,       -inf, 0.47712125])

In [14]: np.log10(0)
<ipython-input-14-fb8478a94c6a>:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(0)
Out[14]: -inf

```

**Comment by jklymak** [comment]
I'm going to close, but feel free to request a reopen or to continue discussion!
