### ISSUE TITLE
outline attribute of colorbar not documented

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#19946]
Was trying to change the color of the outline of my colorbar:
![image](https://user-images.githubusercontent.com/1300499/114332788-e6470f80-9b14-11eb-92ff-5c7bb346b99e.png)

and wasn't clear in the docs how to do it, but found on stackoverflow that there's an `outline` attribute that is the collection of spines:
```python
 self.outline = ax.spines['outline'] = _ColorbarSpine(ax)
```
 around the colorbar (and is not the same spines as the axes containing the colorbar since I tried that and it didn't work.)

**Comment by jklymak** [comment]
Note #18900 will likely change this behaviour to be exactly the same as any other axes...

**Comment by QuLogic** [comment]
With the new [`Axes.spines` shortcut](https://matplotlib.org/stable/users/whats_new.html#axes-spines-access-shortcuts), you can use `ax.spines[:].set_color('red')` on any `Axes` without worrying about the names.

**Comment by anushkrishnav** [comment]
I would like to work on this issue

**Comment by timhoffm** [comment]
AFAICS there is no clear action:

- we don't want to start advertizing a special `ax.spines['outline']` for colorbars if that will change to standard behavior in #18900.
- `ax.spines[:]` works on any axis. It's documented on `Spines` and it doesn't make sense to add documentation on a general feature specifically to colorbars.

@story645 do you see any specific documentation that we should add that would have helped you? Otherwise I propose to close this.

@anushkrishnav Sorry that the action status is not clear/up-to-date.

**Comment by story645** [comment]
Haven't closed it because I think it could be useful as a backport only doc (since ax.spines doesn't work on earlier versions) but I don't know quote how far back it'd be backported

**Comment by jklymak** [comment]
I don't think we rebuild old docs...

**Comment by timhoffm** [comment]
`ax.spines[:]` is new in 3.4. https://matplotlib.org/stable/api/spines_api.html?highlight=spines#matplotlib.spines.Spines

We don't update docs for previous releases. So I'm closing this as nothing to do.

@story645 Maybe you want to twitter about this some day? This is not as glorious as `subplot_mosaic`, but a nice API to share.
