### ISSUE TITLE
A funtion can put text and data legend together in a freedom way.

### ISSUE THREAD

**Issue by xczics** [matplotlib/matplotlib#20045]
### Problem
I want to create a table-like legend looks like:
![image](https://user-images.githubusercontent.com/40168035/115752725-f7bdd080-a3cc-11eb-8d73-2fa56da069f4.png)
To complete this, we may need a new feature that can put text and legend together by pharsing text.
If we can write "10℃\t20℃\t30℃\t\n\<line1\>\t\<line2\>\t\<line3\>\tPhlo..." to complete this, we may create more wonderful lengends!
Here is a sample image of what I am asking for:
![image](https://user-images.githubusercontent.com/40168035/115753910-4455db80-a3ce-11eb-9331-c3c0e1314b3e.png)

### Proposed Solution
We can get a legend handle for most Artists and we can layout text relative to other artists. We just need a function put those two features together!

**Comment by anntzer** [comment]
I am almost certain there was a request some time ago to be able to have e.g. ylabels of the form `<the line> label` (basically, moving the legend for an axes with a single artist to the ylabel).  Likely the discussions should be linked...

**Comment by timhoffm** [comment]
Semi-related: Markers on axis (#16005), but this uses dedicated methods `set_xlabel_legend()`.

I see the appeal of embedding markers in Text via placeholders.

Implementation-wise this needs a bit more thought:

- Can we embed that into existing `Text` objects cleanly? Probably not because i) API-wise we have to pass the markers, ii) implementation-wise the rendering/layout algorithm would become much more complex.
- Can we make a proxy Artist, that takes the string and markers and breaks it in howmany `Text` objects we need and lays them out all together? This does not quite feel how we usually operate, OTOH we have some "collection" Artists.
- Can we make a dedicated `Text` subclass that has the additional features? Maybe

**Comment by anntzer** [comment]
This is indeed what I was thinking about above.

**Comment by jklymak** [comment]
`legend` has already solved all this with a hierarchy of hbox and vbox packers, similar to the TeX basic objects.  i.e. https://matplotlib.org/stable/api/offsetbox_api.html#matplotlib.offsetbox.HPacker  I think if you want a custom 4-column legend, its just a matter of laterally laying out 3 lines instead of just one.  I would *not* be in favour of expanding the legend API to make that happen, but the tools are all there to write your own `legend_4col`.
