### ISSUE TITLE
Zoom in NavigationToolbar2Tk stops working after updating the canvas figure.

### ISSUE THREAD

**Issue by kopytjuk** [matplotlib/matplotlib#20159]
### Bug report

**Bug summary**

After updating `canvas.figure` with a new figure (and successive `canvas.draw()` call zoom does not work in `3.4.1` release. The same code works for `3.3.4`.

**Code for reproduction**

```python
# adapted from
# https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_tk_sgskip.html
import tkinter

from matplotlib.backends.backend_tkagg import (
    FigureCanvasTkAgg, NavigationToolbar2Tk)
# Implement the default Matplotlib key bindings.
from matplotlib.backend_bases import key_press_handler
from matplotlib.figure import Figure
from matplotlib import __version__

import numpy as np

print("matplotlib", __version__)

root = tkinter.Tk()
root.wm_title("Embedding in Tk")

fig = Figure(figsize=(5, 4), dpi=100)
t = np.arange(0, 3, .01)
fig.add_subplot().plot(t, 2 * np.sin(2 * np.pi * t))

canvas = FigureCanvasTkAgg(fig, master=root)  # A tk.DrawingArea.
canvas.draw()

# pack_toolbar=False will make it easier to use a layout manager later on.
toolbar = NavigationToolbar2Tk(canvas, root, pack_toolbar=False)
toolbar.update()

##### Change !!!
# second figure
second_fig = Figure(figsize=(5, 4), dpi=100)
t = np.arange(0, 4, .01)
second_fig.add_subplot().plot(t, 2 * np.sin(2 * np.pi * t))
canvas.figure = second_fig

toolbar.update()
canvas.draw()
##### !!!

canvas.mpl_connect(
    "key_press_event", lambda event: print(f"you pressed {event.key}"))
canvas.mpl_connect("key_press_event", key_press_handler)

button = tkinter.Button(master=root, text="Quit", command=root.quit)

# Packing order is important. Widgets are processed sequentially and if there
# is no space left, because the window is too small, they are not displayed.
# The canvas is rather flexible in its size, so we pack it last which makes
# sure the UI controls are displayed as long as possible.
button.pack(side=tkinter.BOTTOM)
toolbar.pack(side=tkinter.BOTTOM, fill=tkinter.X)
canvas.get_tk_widget().pack(side=tkinter.TOP, fill=tkinter.BOTH, expand=1)

tkinter.mainloop()
```

**Matplotlib version**

  * Operating system: ubuntu 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.8.5
  * Jupyter version (if applicable): 
  * Other libraries: 

Installed from pip.

**Comment by tacaswell** [comment]
This is a consequence of an intentional change (https://matplotlib.org/stable/api/api_changes.html#canvas-s-callback-registry-now-stored-on-figure ) to fix restoring the interactions on pickled 3D axes (https://github.com/matplotlib/matplotlib/pull/16220).  It looks like the callbacks, some of which are registered in the toolbar `__init__`, are being split across the two figures.  I have not fully traced through the exact details of what is going wrong, but am very confident that this is the root explanation. 

What are you trying to do with two figures like this?  From context I assume that you are switching between them via some other part of the UI?  The best path forward will depend on why you are doing this.  If you are indeed doing a switcher I could see making a case for the switcher toggling the visibility of the Axes rather than swapping the Figure or a case for getting a sub-class of the toolbar that knows how to move around its callbacks as part of the swap.

**Comment by kopytjuk** [comment]
Thanks for your quick feedback!

The idea of this approach that I have a function in my codebase which returns an instance of `Figure` which I attach to the canvas (to update a plot). Is the workaround to create a `Figure` once and update the `Axes` only?

**Comment by jklymak** [comment]
Its usually a good idea to create the figure, and often the axes, at a higher level and pass them to functions to draw in.  Not always (like you could imagine different numbers of figures or subplots based on the data state), but often.

**Comment by tacaswell** [comment]
I think you have the right idea, but need to tie the `Figure` and `canvas` creation more tightly together at the moment.  It used to work because the canvas own the callbacks so the toolbar call backs would be auto-magically transferred to the new figure.  In 3.4+ the callbacks live on the Figure so they get auto-magically transferred to a new canvas (because we expected there to be more changing of canvases under Figures, than Figures on top of canvases).  

I think there is still some more (careful) work to be done to shift around some internal boundaries between Figure and Canvas (as one is more-or-less useless without the other the edge can be a bit fuzzy).

Figure is the top of the draw tree and should be the only Artist without a parent.  It is aware of it's canvas so `fig.savefig(...)` will work, its size (in inches), and its dpi.  Like all `Artist`s it has a `draw` method which takes in a renderer.  

The Canvas in responsible for creating and managing the `Renderer` instances and owns the `print_XYZ` methods that know how to output to a given file type.  They are also where we, via multiple inheritance, hook into the GUI systems.  They are aware of what figure they are attached to so `canvas.draw()` works.

That circular knowledge of each other is the source of much of the confusion.

**Comment by kopytjuk** [comment]
Would you like me to extend the _Embedding in Tk_ example with a small showcase how to update existing plot in the GUI? I think it is a common use case where you preselect/prefilter the data with some other widget and update current plot.

In any case we can close this issue from my side. Thanks for your explanation!

**Comment by QuLogic** [comment]
Does this need to remain open?
