### ISSUE TITLE
alpha='auto' : set a good alpha value based on density of points

### ISSUE THREAD

**Issue by bagrow** [matplotlib/matplotlib#20175]
### Problem

Occlusion makes it difficult to estimate the joint density in scatter plots with many points. One fix is to use a 2d binning instead of a scatter plot, but another simple solution is to lower the alpha of plot markers. 

For translucent points, I often find myself iterating back and forth to find alpha. Is `alpha=0.5` good? No, still too dense. How about `alpha=0.1`? No, now I can't see anything. `alpha=0.33`? Just right.

### Proposed Solution

What about an `alpha="auto"` option? This follows the lead of `bins="auto"` in `hist`.

What heuristic to set alpha? You need to estimate how many markers overlap, but it should be simple and cheap to compute as it will typically be used when N, the number of points, is large. It may be best to avoid an O(N^2) calculation, such as looking at the distance between all pairs of points.

Some ideas for choosing alpha:

1. Run the data through `np.histogram2d` with bins around the size of the plot marker (transformed to data coords) and get n, the max or mean number of points in non-empty bins. Then let alpha be a slowly decreasing (logarithmic?) function of n.
2. If `histogram2d` is too much, something simpler could be to just look at the typical distance between points on one axis, (max(x)-min(x))/N and compare that to the width of a plot marker. Of course, looking at only one dimension will miss information, but it might still be a workable heuristic.

There should be a clever solution here.

(Searching the issues, I couldn't find if this had been proposed previously. Apologies if this is redundant.)

**Comment by tacaswell** [comment]
This is an interesting suggestion, but I am skeptical of getting merged in to main-line Matplotlib in the near future.  I think this would be better suited to start as a stand alone package to work through the exact questions you bring up that the exact algorithm to use being unclear!  

Being a stand-alone package means you can release on what ever time scale you want (rather than the ~2x per year we do feature releases) and are not bound by our API constraints (once things go into mpl they are hard to get out or change in major ways!).  

If you are interested in pushing on this https://github.com/matplotlib/matplotlib-extension-cookiecutter may be of use to get started and once you have published a version of this, please add it to https://github.com/matplotlib/matplotlib-extension-cookiecutter !

You may be interested in https://github.com/astrofrog/mpl-scatter-density or datashader (which now includes a mpl artist, see  https://github.com/astrofrog/mpl-scatter-density) both of which dynamically adjusts the 2D binning based on the current axes view.

**Comment by jklymak** [comment]
> once you have published a version of this, please add it to

https://matplotlib.org/mpl-third-party/

**Comment by bagrow** [comment]
If I pursue this, I'll probably start with just a basic function to work out the details:

```python
plt.plot(x,y, 'o', alpha=auto_alpha(x,y))
```
then try to bring it into the matplotlib package ecosystem proper.

Thanks for the feedback.

**Comment by mwaskom** [comment]
This question has been studied, so I might look at this paper before inventing your own solution *de novo* thttps://www.autodesk.com/research/publications/dynamic-opacity-optimization-for

BTW I doubt an `auto_alpha(x, y)` function will be sufficient because you also need to know, at least, the size of the points that you're drawing, and the limits of the axes you're plotting onto may exceed the limits implied by the (sub)set of data you're passing into the function.

**Comment by bagrow** [comment]
The research paper from Autodesk, Matejka _et al._, really underscores that:

1. There is a demonstrated need for this solution.
2. There is no need for experimentation, the problem is solved. Their method is cheap to compute and validated with user studies on real data in a peer-reviewed venue. Their user studies also rebut potential complaints of subjectivity.

So the feature I now request is simply to put Matejka _et al._ behind `alpha="auto"`.

> then someone will say we did it wrong, and want "auto2", or "auto3" etc.

The same argument holds for `bins='auto'` in hist. Even though automatic binning is inherited from numpy, if that is the concern then it should be removed from matplotlib. Histograms are a general tool too. I don't agree that this justifies not including an `alpha="auto"` feature.

With all that said, it seems most folks are lukewarm at best on this idea. Fair enough---matplotlib is a big package and there are lots of users wanting lots of things and everything takes time to build and maintain. Thanks for taking the time to consider the proposal.

**Comment by mwaskom** [comment]
Also `bins` actually does support a number of additional automatic rules with specific names, and then `bins="auto"` takes the max of the answer from two of them.

**Comment by bagrow** [comment]
Yes, people have been proposing histogram binning heuristics for, what 40 years? That's why you should really use the ECDF.

**Comment by mwaskom** [comment]
That seems unrelated to scatterplot opacity.

Anyway just because I'm thinking about possible implementation issues here, one problem is that matplotlib figures are interactive and you can zoom in/out, or resize the window. (Or, for that matter, programatticaly change the axis limits after the scatterplot is created either explicitly or by adding data with a larger range). So for the final product to actually have an "optimal" opacity, you would need to run the algorithm at draw time, not at the time the artist is added to the axes.
