### ISSUE TITLE
Consider adding GitHub topics

### ISSUE THREAD

**Issue by imba-tjd** [matplotlib/matplotlib#20246]
For example https://github.com/topics/data-visualization

**Comment by tacaswell** [comment]
We should also turn the crank to curate the matplotlib topic (see https://github.com/github/explore/blob/main/CONTRIBUTING.md for instructions).

I'm going to throw "matplotlib data-visualization python data-science qt wx gtk" in there for now because it is a web UI to change it (it is hidden in the gear wheel on the "about" in the right column of the repo page, not sure what the access control to edit it is).

**Comment by anntzer** [comment]
probably add tk as well?  (fwiw I don't have access to the gear wheel on the mpl repo)
