### ISSUE TITLE
Incorrect subscript typesetting in f strings

### ISSUE THREAD

**Issue by K20shores** [matplotlib/matplotlib#20280]
### Bug report

**Bug summary**

A latex subscript of the form `$_{decimal number}$` in an f string is not typeset correctly. Only the number before the decimal is subscripted. This only seems to happen when f strings are used. 

**Code for reproduction**

```python
plt.rc('text', usetex=True)

fig, ax = plt.subplots(dpi=300)

ax.plot(np.arange(10))

thing = 1

ax.set_title(f"Thing$_{2.5}$ {thing}")
```

**Actual outcome**

![image](https://user-images.githubusercontent.com/13836216/119150096-bcd2ab00-ba13-11eb-959a-7065b5880ee3.png)

**Expected outcome**

The number `2.5` should fully be a subscript. However, a workaround would be changing the title from `f"Thing$_{2.5}$ {thing}")` to `"Thing$_{2.5}$" + f" {thing}")`

**Matplotlib version**

  * Operating system: mac
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): module://ipykernel.pylab.backend_inline
  * Python version: 3.9.4
  * Jupyter version (if applicable): jupyter core 4.7.0, jupyter-notebook 6.2.0
  * Other libraries:

**Comment by tacaswell** [comment]
This is due to how fstrings work.  `'f"{2.5}'` is interpreted by Python to be "please replace the whole curly branch expression with the result of evaluating the Python inside the curly braces against the local namespace and then convert that result to a string".  In this case, the Python is a string literal, which comes back as "2.5".  If you want the curly braces to survive the fstring, you need to escape them as `f'{{2.5}}'`

```python
In [1]: thing = 1

In [2]: f"Thing$_{2.5}$ {thing}"
Out[2]: 'Thing$_2.5$ 1'

In [3]: f"Thing$_{{2.5}}$ {thing}"
Out[3]: 'Thing$_{2.5}$ 1'

In [4]: 
```

I'm going to close this because there is nothing that we can do on the Matplotlib side as the curly braces for the subscript are gone before we see the string!

**Comment by tacaswell** [comment]
Also see https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals and  https://docs.python.org/3/library/string.html#format-string-syntax
