### ISSUE TITLE
Memory not freed up correctly

### ISSUE THREAD

**Issue by P-Takenaka** [matplotlib/matplotlib#20300]
### Bug report

**Bug summary**

When creating multiple plots (e.g. in a loop), the allocated memory for the process increases in each iteration even though the figure is cleared each time.

**Code for reproduction**

```python
import gc
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
for i in range(5000):
    fig.clf()
    plt.cla()
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
    plt.close('all')
    plt.close(fig)

    gc.collect()
```

**Expected outcome**

The allocated memory should not increase in each iteration.

**Matplotlib version**

  * Operating system: Arch Linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.4.2
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: 3.9.5
  * Jupyter version (if applicable): 
  * Other libraries: 

Matplotlib was installed via pip.

**Comment by timhoffm** [comment]
This indeed slowly increases memory usage (checked with memory_profiler and 500 samples):

![grafik](https://user-images.githubusercontent.com/2836374/119515388-16b9d480-bd76-11eb-82a9-5f6dbf7ba50d.png)


However, the code is not reasonable in itself. It seems you are trying wildly delete everything. But though that, `fig.clf()` cleans the figure, including it's axes, `plt.cla()` does nothing then, and the `ax` object continues to live detached from any figure so that the data from `ax.plot` will not show up in any figure.

While that doesn't explain the memory leak, let's try and start from a realistic example: What are you trying to do exactly? Do you only want to replace data inside the Axes? If so, the only cleanup command necessary should be `ax.clear()` (or historically synonym `ax.cla()`). If you need to wipe the whole figure, `fig.clf()` is the way to go (But I expect `fig.close(); fig = plt.figure()` should be similarly efficient).

**Comment by P-Takenaka** [comment]
I am aware that the example code contains redundant clear commands, I wanted to emphasize that I tried all the commands that solved past issues of a similar kind. However, after your remarks regarding a floating axis object I noticed that only the following combination of clear commands in each iteration results in the memory growth problem:
```python
plt.cla()
plt.close()
```

In my use case I only need to clear the axis data, therefore for me the issue would be solved by only using `plt.cla()` as you said.  I unnecessarily went the way to rebuild the whole figure in each iteration at first, resulting in me having this issue. Though I am still wondering why the above code results in the memory leak. Unfortunately I am not familiar enough with the inner workings of matplotlib.

**Comment by timhoffm** [comment]
Regular usage with clearing the Axes or figure does not have a memory leak. It seems that `plt.close()` doesn't completely get rid of the data.

### Axes clearing
```
fig = plt.figure()
ax = fig.add_subplot(111)
for i in range(500):
    ax.clear()
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
```
![grafik](https://user-images.githubusercontent.com/2836374/119551900-6b6f4680-bd9a-11eb-8199-fe0ff3fc0eb0.png)

### Figure clearing
```
fig = plt.figure()
for i in range(500):
    fig.clf()
    ax = fig.add_subplot(111)
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
```
![grafik](https://user-images.githubusercontent.com/2836374/119552385-e0428080-bd9a-11eb-83ce-87b530c981e9.png)

### Figure closing

#### Simple figure closing

```
for i in range(500):
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
    plt.close(fig)
```

![grafik](https://user-images.githubusercontent.com/2836374/119552818-40392700-bd9b-11eb-8991-1344f98f76d7.png)

#### Closing with garbage collection

Strips of some memory, but doesn't help with the leak. All this does is that the gc slows down execution:

```
for i in range(500):
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
    plt.close(fig)
    gc.collect()
```

![grafik](https://user-images.githubusercontent.com/2836374/119553020-7a0a2d80-bd9b-11eb-9869-96f6e9ec2cce.png)

**Comment by jklymak** [comment]
I'm relatively sure tK leaking has been documented before.  Does this happen for other backends?

**Comment by timhoffm** [comment]
As proposed in #5795, this has to do with created but not-shown GUI windows.

#### It works if you show the windows and close them afterwards

```
for i in range(500):
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
    plt.show(block=False)
    plt.pause(0.2)
    plt.close(fig)
```

![grafik](https://user-images.githubusercontent.com/2836374/119555484-336a0280-bd9e-11eb-979f-bf05682b7a5e.png)

The edges are probably due to garbage collection.

#### It works if you use a non-GUI backend

```
import matplotlib as mpl
mpl.use('agg')
import matplotlib.pyplot as plt

for i in range(500):
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.plot([0,1,2,3,4,5], [0,1,2,3,4,5])
    plt.savefig(f'test{i:03d}.png')
    plt.close(fig)
```

![grafik](https://user-images.githubusercontent.com/2836374/119555906-ad9a8700-bd9e-11eb-897b-aa0ad701c59b.png)

## Summary
This only happens if you work in a GUI backend, create new figures, but don't show them. This way of usage is not reasonable. There are working usage patterns for all relevant scenarios.

I'm closing this as "won't fix" because the memory leak doesn't happen for proper usage, and I assume that debugging the GUI framework memory management would be quite hard.

**Comment by tacaswell** [comment]
> The edges are probably due to garbage collection.

gc + circular references is the source of the jagged edges, Python only does the more expensive sweeps every so often and we have a lot of circular references!
