### ISSUE TITLE
Add ']->' , '<-[' arrowstyles

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#20385]
I frequently want an arrow with a bracket on one end and point on the other to show that a region or set of values is the input into a point. 
![image](https://user-images.githubusercontent.com/1300499/121121912-83a98180-c7ee-11eb-98ec-5f27c7ff5887.png)

Skimming [Arrowstyle](https://github.com/matplotlib/matplotlib/blob/ca6e9dcb892181a81863c3474829a363e3115d5b/lib/matplotlib/patches.py#L3106), I'm not sure if this is impossible or just not implemented 'cause of API creep. If it's the latter, what about an API change that allows for separately defined A and B styles? 

Usually I implement this by overlaying two arrows:
```python
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches

fig, ax = plt.subplots()

q1 = mpatches.ConnectionPatch(xyA=(.2, .5), coordsA=ax.transAxes, 
                                  xyB=(.7, .5), coordsB=ax.transAxes, 
                                  arrowstyle=']-', lw=5)      
fig.add_artist(q1)

q2 = mpatches.ConnectionPatch(xyA=(.2, .5), coordsA=ax.transAxes, 
                                  xyB=(.9, .5), coordsB=ax.transAxes, 
                                  arrowstyle='->', lw=5)      
fig.add_artist(q2)
```

**Comment by anntzer** [comment]
It seems it would make sense to allow that.

**Comment by story645** [comment]
xref #3624 which is also asking for separate styling of body and head.

**Comment by anntzer** [comment]
OK, it's not actually *that* simple because some of the arrow styles *need* to be drawn as single patches, such as the default "Simple" (ahem) arrowstyle, which fattens a single line into an arrow with a nonzero width (I don't think the head and the body can be drawn separately while keeping the edgecolor from being drawn at the interface between the two of them):
```python
gca().add_artist(FancyArrowPatch((.1, .1), (.9, .1), mutation_scale=100))
```
is
![test](https://user-images.githubusercontent.com/1322974/121790926-c13e4e00-cbe4-11eb-91d4-00c126203ab1.png)
(at least this explains the choice of the "mutate-the-path" API, I guess.)

**Comment by Carloscerq** [comment]
It's possible that instead we just substitute the `_Bracket` and `_Curve` classes with a “bigger” one? Then it would be possible to do something like `beginarrow_curve = True` and `endarrow_bracket = True` for `“<-[”`, and so on. This, maybe, would make the changes proposed here easier, since it wouldn’t be necessary to change the `Simple`, `Fancy` or `Wedge` ones. The only downside I could think is that it wouldn’t solve the #17284
