### ISSUE TITLE
Imshow changes position of its inset-axes

### ISSUE THREAD

**Issue by CakeUser321** [matplotlib/matplotlib#20412]
### Bug report

Inset axes moves its position relative to parent axes when showing an image. 

**Code for reproduction**

```python
import matplotlib.pyplot as plt

img = plt.imread("https://upload.wikimedia.org/wikipedia/commons/6/64/Gnu_meditate_levitate.png")
bShowImg = False # Change for see coordinate shift


fig, ax = plt.subplots()
ax.plot(range(10))
ax.grid()
axin = ax.inset_axes([2, 2, 1.280, 1.112], transform=ax.transData)
if bShowImg:
    axin.imshow(img)

plt.show()
```

**Actual outcome**

Outcome with no Image:
![right](https://user-images.githubusercontent.com/23025940/121686114-0d906d80-cac1-11eb-9a62-3f7748aab7a5.png)

Outcome with Image:
![wrong](https://user-images.githubusercontent.com/23025940/121686242-357fd100-cac1-11eb-8d06-85b17b5f1fcd.png)

**Expected outcome**

The origin of the image should be at the point (2|2).

**Matplotlib version**
  * Operating system: Linux machinex539 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 3.3.4
  * Matplotlib backend (`print(matplotlib.get_backend())`): Backend TkAgg is interactive backend. Turning interactive mode on.
TkAgg
  * Python version: Python 3.6.9
  * Other libraries:

**Comment by jklymak** [comment]
imshow sets the aspect ratio of the data in the axes to 'equal', and in this case that means the axes shrinks in the vertical to do that.  This is expected behaviour.  If you dont' want the axes to move, change the aspect='auto', or make the inset have the same aspect as the data.  I'll close this, but if you have more questions, feel free to ask at discourse.matplotlib.org.
