### ISSUE TITLE
show plot_surface and plot3D simutaneously

### ISSUE THREAD

**Issue by Korbinhu** [matplotlib/matplotlib#20429]
When I use the example code as below to plot surface and 3D lines simultaneously, it always appears to make the surface image in front of the 3D line. Is there any method or functional setting to avoid this and show the figure correctly?

##Code
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator
import numpy as np

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
X = np.arange(-5, 5, 0.25)
Y = np.arange(-5, 5, 0.25)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)
surf = ax.plot_surface(X, Y, Z, cmap=cm.coolwarm,linewidth=0, antialiased=False)
ax.plot3D(X[0,:],Y[:,0],np.diag(Z))
ax.set_zlim(-1.01, 1.01)
ax.zaxis.set_major_locator(LinearLocator(10))
ax.zaxis.set_major_formatter('{x:.02f}')
plt.show()

the result is below:
![屏幕截图 2021-06-13 204202](https://user-images.githubusercontent.com/37903338/121807757-1a12f280-cc88-11eb-938c-df16f1831c96.png)

but what I want is like this:
![2](https://user-images.githubusercontent.com/37903338/121807764-2434f100-cc88-11eb-94f9-55a337e0b6d5.png)
how to make the 3d Line in front of the image?
Thanks very much!!!

**Comment by timhoffm** [comment]
This is not possible, due to fundamental limitations of the way 3D is implemented: Different plot objects cannot mutually overlap each other. It's always either the surface or the line in front. See also [My 3D plot doesn't look right at certain viewing angles](https://matplotlib.org/devdocs/api/toolkits/mplot3d/faq.html#my-3d-plot-doesn-t-look-right-at-certain-viewing-angles).

The best you can do is raise the line to the top by increasing its `zorder`: ` ax.plot3D(X[0,:],Y[:,0],np.diag(Z), zorder=4)`

![grafik](https://user-images.githubusercontent.com/2836374/121809026-74e22500-cc5b-11eb-88de-38601360a4cb.png)
