### ISSUE TITLE
Contour behaviour changed with NaN coordinates

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#20443]
### Bug report
The behaviour when creating a contour where some of the input coordinates of the data are `NaN` has changed between the latest stable release (3.4.2) and the current master branch. Before the contour path was 'skipped' at the points where coordinates were `NaN`, but now the contour path is completed between the first finite coordinate and final finite coordinate.

We've noticed this upstream in sunpy (at https://github.com/sunpy/sunpy/pull/5398 - sorry, it doesn't have the right images to demonstrate this bug at the moment), where we would like to transform a set of coordinates such that some of them are `NaN`, but still be able to draw a contour with the `NaN` bits missing.

The change bisects to https://github.com/matplotlib/matplotlib/commit/04f4bb6d1206d283a572f108e95ecec1a47123ca from https://github.com/matplotlib/matplotlib/pull/19623 by @ianthomas23 

**Code for reproduction**

```python
import matplotlib.pyplot as plt
import numpy as np

x, y = np.meshgrid(np.arange(-10, 10.), np.arange(-10, 10.))
data = np.sqrt(x**2 + y**2 < 5)

fig, axs = plt.subplots(ncols=2)
axs[0].contour(x, y, data, levels=[0.5])

x[x < 0] = np.nan
axs[1].contour(x, y, data, levels=[0.5])
axs[1].set_xlim(-10, 10)
axs[1].set_ylim(-10, 10)
plt.show()
```

**Actual outcome**
With current master branch:
![after](https://user-images.githubusercontent.com/6197628/122101085-d3e69c00-ce0b-11eb-899a-09e67109a35b.png)

**Expected outcome**

With 3.4.2:
![before](https://user-images.githubusercontent.com/6197628/122100994-bca7ae80-ce0b-11eb-99fa-d53c6d49fd85.png)

**Matplotlib version**

  * Operating system: 
  * Matplotlib version (`import matplotlib; print(matplotlib.__version__)`): 
  * Matplotlib backend (`print(matplotlib.get_backend())`): 
  * Python version: 
  * Jupyter version (if applicable): 
  * Other libraries:

**Comment by ianthomas23** [comment]
@dstansby Interesting problem!  Prepare yourself for one of my long-winded explanations.

Ideally don't use non-finite coordinates.  If you must, you also need to mask out the corresponding `z` values (`data` in the reproducing code).  So instead of
```python
x[x < 0] = np.nan
```
you should use
```python
data[x < 0] = np.nan
x[x < 0] = np.nan
```
or indeed just
```python
data[x < 0] = np.nan
```
will give you what you want.

### Explanation
`contour(x, y, z)` (and contourf and the tricontour equivalents) accept a masked array for `z` and will automatically convert non-finite values like `np.nan` to a mask. The contour calculation algorithm will ignore grid points for which `z` is masked, so it doesn't matter what the corresponding `x` and `y` values are.  But it expects `x` and `y` to be unmasked arrays and will treat non-finite values (`-np.nan`, `-np.inf`, `np.nan`, `np.inf`) as their double-precision values which are essentially very large negative and positive numbers. So a non-finite `x` or `y` that isn't masked out by the corresponding `z` will be processed by the contour algorithm in the normal way.

In your example just under half of your domain is at `x = np.nan`, which is effectively a very long distance off the screen to the right.  The contouring algorithm marches through all of this in the normal way. The left-hand half of the contoured diamond is calculated at `x = np.nan` and hence never displayed.

The PR that you bisected to fixes a very long standing problem in that contours that are correctly identified as closed line loops (first and last points are identical) were rendered as open line strips, because the `LineCollection`s that were used didn't support any form of closed-ness flag.  By changing them to `PathCollection`s the closed-ness is rendered correctly.  There is not much of a difference between `LineCollection` and `PathCollection` as `Line`s are ultimately converted to `Path`s for rendering anyway, but it seems that there was a side-effect of `LineCollection` that you were relying on and shouldn't have been.  I'm not an expert on the `Collection` code, but evidently `LineCollection` doesn't render line segments if one or both ends have a `np.nan` coordinate, whereas `PathCollection` just ignores the points with `np.nan` coords and so closes the line loop.

Anyway, all of this `Collection` stuff is really a distraction. You don't want the contouring algorithm to trawl through regions of your grid that have non-finite coordinates as it is unnecessary computation.  So set the `z` mask appropriately.

I thought the `contour` documentation explained about the possibility of masked `z`, Evidently not!

**Comment by dstansby** [comment]
Thanks a lot for the clear explanation! Masking the data array seems like a reasonable thing for the (Matplotlib) user to do, so we can do that in sunpy. I think it might be worth adding a quick changelog entry to mention this behaviour change just in case - I didn't spot one added in https://github.com/matplotlib/matplotlib/pull/19623, but I guess that might be because this is an odd way to be using contour.

**Comment by dstansby** [comment]
Probably a bit late to amend/add a changelog entry for this now, so I'll close.
