### ISSUE TITLE
interactively pop out one graph from a set of subplots

### ISSUE THREAD

**Issue by aardvarkkrill** [matplotlib/matplotlib#20482]
### Problem

I often group together graphs in subplots.  But when I want to explore a subplot in detail I'm limited by the size of the window.  
Conversely if I have a figure with a single axis I can make it fill the whole screen, but then it's hard to manage if there are a lot of them.
It's annoying to have to code for both possibilities, since I don't know which graphs I will need enlarged when.

### Proposed Solution

So it would be great to have a way to point at a subplot interactively and have it pop out into its own new figure window.
(Perhaps this could be built on top of a "graph clone" primitive?)

thanks!

**Comment by tacaswell** [comment]
Doing things like this is one of the things that https://github.com/matplotlib/interactive_tutorial highlights in the 03-temperature section (that code adds lines to different Axes in the same Figure, but the principle is the same).

If you write you plotting tools to look something like

```python

def my_plotter(ax, data, **style):
    ...
    return some_artists

```

it is possible to make reusable and composable helpers (see the discussion in the second half of https://matplotlib.org/stable/tutorials/introductory/usage.html#the-object-oriented-interface-and-the-pyplot-interface and https://github.com/tacaswell/2021-03_APS/tree/main/code/harmonic_oscilator for more details).

If you want to have a further discussion about how to implement this for your use case I suggest starting a discussion at https://discourse.matplotlib.org ! 

I'm going to close this because I think all of the tools you need from the library already exist!

**Comment by aardvarkkrill** [comment]
@tacaswell, thanks for the link, I do understand your point, and I can see how this works, and I see that I could implement it but...
In this use case I'm using python+matplotlib interactively, usually inside a debugger.  I generate lots of temporary and fleeting figures for exploring and debugging code (I'm signal processing messy data -- this is a search for solutions, not a solid piece of code.)  Most figures get closed.  Some get examined.  If I had to carefully keep track of every Axes and its data my job would take 10 times as long, and this for code that I will throw away in half an hour (or 5 hours if it takes 10 times as long ;-).  I believe Matplotlib is named after MATLAB, and I'm trying to use it (pyplot) in a similar spirit (at least some of the time -- at other times I write properly structured code!)  So please forgive me for saying that although the tools exist, I think they are not the right tools for this level of interaction.  Maybe I'm just spoilt, because the built-in viewer can already do zooming and panning without me coding anything...
