### ISSUE TITLE
Consider making default verticalalignment `baseline`

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#2051]
Continuing from #1734

**Comment by anntzer** [comment]
I have no idea how difficult this would be to include in 2.0? (if it's a straight default change we may perhaps as well bundle it in?)

Milestoning it to 2.0 so that this doesn't get lost in case it's easy but feel free to push it back to 2.1.

(As a side note, did the "1.5.x" issue get renamed to "2.1" at some point?)

**Comment by dopplershift** [comment]
The original problem shown in #1734 doesn't seem to be a problem any more; out of the box, the x and y labels look to be aligned fine on current v2.x and 1.5.3. AFAICT, no changes necessary.
