### ISSUE TITLE
set_segments(get_segments()) makes lines coarse

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#20551]
After plotting with `contourf`, I would like to retrieve the lines and manipulate them. Unfortunately, I noticed that the result is much coarser than without manipulation. In fact, a simple `lc.set_segments(lc.get_segments())` has this effect. I would have expected this does nothing at all.

MWE:
```python
import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-1.1, 1.1, 100)
y = np.linspace(-1.1, 1.1, 100)

X, Y = np.meshgrid(x, y)
Z = X ** 2 + Y ** 2

c = plt.contour(X, Y, Z, levels=[1.0], colors="k")

# reset segments
lc = c.collections[0]
segments = lc.get_segments()
lc.set_segments(segments)

plt.gca().set_aspect("equal")
plt.show()
```

|  ![sc1](https://user-images.githubusercontent.com/181628/123953915-11206180-d9a8-11eb-9661-ce4363d19437.png) | ![sc2](https://user-images.githubusercontent.com/181628/123953934-17aed900-d9a8-11eb-8a50-88c6168def93.png) |
| ------- | ------- |
| default | with reset segments |

This is with mpl 3.4.2.

**Comment by nschloe** [comment]
Aha: There is
```
c.allsegs
```
which can be manipulated instead.

**Comment by dmatos2012** [comment]
Hi @nschloe, has your problem been resolved?

**Comment by tacaswell** [comment]
Interesting between 3.4.2 and the default branch this has changed from a `LineCollection` to a `PathCollection` which notable does not even _have_ a `get_segments`.

**Comment by nschloe** [comment]
`get_segments()` was wrong apparently, so problem solved for me.

**Comment by tacaswell** [comment]
@nschloe You identified a _different_ bug which is why does `lc.get_segments()` aggressively simplify the curve ?!

Internally all `Collection` flavors boil down to calling `renderer.draw_path_collection` and all of the sub-classes primarily provide nicer user-facing APIs to fabricate the paths that will be passed down to the renderer.  In `LineCollection` rather than tracking both the user supplied data and the internal `Path` objects, we just keep the `Path` objects and re-extract segments on demand.  To do this we use `Path.iter_segments` with defaults to asking the path if it should simplify the path (that is drop points that do not matter which is in turn defined by if the deflection away from "straight" is greater than some threshold).  The `Path` objects we are holding have values in data-space, but the default value of "should simplify" and "what is the threshold for 'not mattering'" are both set so that they make sense once the path has been converted to pixel space (`True` and `1/9`).  In `LineCollection.get_segments` we are not passing anything special so we are cleaning the path to only include points that make the path deviate by ~0.1111 (which eye-balling looks about right).  I think the fix here is to pass `simplify=False` in `LineColleciton.get_segments()`.

**Comment by tacaswell** [comment]
And the change from LineCollection -> PathCollection was 04f4bb6d1206d283a572f108e95ecec1a47123ca and is justified.
