### ISSUE TITLE
Bug in matplotlib.pyplot.imshow(., cmap = 'gray')

### ISSUE THREAD

**Issue by mortezadmh** [matplotlib/matplotlib#20556]
Hello,

It seems like there is a bug in 'matplotlib.pyplot.imshow' with the 'gray' colormap. A matrix of all float 1.0 values shows similar to that of 0.0.

matplotlib version: 3.4.2
Python version: 3.9.5

`import matplotlib.pyplot as plt`

`import numpy as np`

`fig = plt.figure()`

`tmp = np.ones((10,10), dtype=np.float)`

`#tmp[0,0]=0.`

`plt.imshow(tmp, cmap = 'gray')`

`plt.show()`

![bugCmap1](https://user-images.githubusercontent.com/4101291/124021057-189c3680-d9b9-11eb-8b95-6e959c3a1a2c.png)

`import matplotlib.pyplot as plt`

`import numpy as np`

`fig = plt.figure()`

`tmp = np.ones((10,10), dtype=np.float)`

`tmp[0,0]=0.`

`plt.imshow(tmp, cmap = 'gray')`

`plt.show()`
![bugCmap2](https://user-images.githubusercontent.com/4101291/124021130-2ea9f700-d9b9-11eb-9024-949cb3b62e38.png)

**Comment by tacaswell** [comment]
This is the expected behavior, if you do not provide `vmin` and `vmax` we infer them from the data provided.  We then map your data, between vmin and vmax, to the colormap.  If all of the values are equal and `vmin == vmax` there is an ambiguity in what we should do.  In this case we map all the values to the bottom color of the color map (really any color would be defendable so long as it is uniform!) hence

```python
fig, (ax0, ax1) = plt.subplots(2)

ax0.imshow(np.zero((5, 5)))
ax1.imshow(np.ones((5, 5)))

```

will look the same.  If you know ahead of time that the meaningful range of your data is [0, 1] do

```python
fig, (ax0, ax1) = plt.subplots(2)

ax0.imshow(np.zero((5, 5)), vmin=0, vmax=1)
ax1.imshow(np.ones((5, 5)), vmin=0, vmax=1)

```

See https://matplotlib.org/stable/tutorials/colors/colormapnorms.html for more details.

I am going to close this as this is the expected behavior, if you want to continue this discussion please open a new topic at https://discourse.matplotlib.org !
