### ISSUE TITLE
[Bug]: X11 failtue crashes IPython

### ISSUE THREAD

**Issue by 2sn** [matplotlib/matplotlib#20789]
### Bug summary

When making plots, I get an X11 error and IPython crashes.  Not necessarily firt plot, but after 2-3 plots.

### Code for reproduction

```python
(various plot script)
Crashes when making matplotlib plot.

This happens repeatedly, about a dozens time for me already today.
```

### Actual outcome

```
The X11 connection broke: No error (code 0)
XIO:  fatal IO error 0 (Success) on X server ":0"
      after 3847 requests (3847 known processed) with 0 events remaining.
```
IPython terminates.

### Expected outcome

(a plot)

### Operating system

 5.13.4-200.fc34.x86_64

### Matplotlib Version

3.4.1

### Matplotlib Backend

Qt5Agg

### Python version

3.9.6

### Jupyter version

IPython 7.26.0

### Installation

pip

**Comment by jklymak** [comment]
That really seems to be at least one level lower than Matplotlib.  I am skeptical we can directly help.

**Comment by jklymak** [comment]
You shouldn't need to install from source.  Matplotlib does not do anything at the X11 level, so maybe your pyQt5 is no longer compatible with your X11?  You could test pyqt5 w/o matplotlib: 

```python
from PyQt5.QtWidgets import *
app = QApplication([])
label = QLabel('Hello World!')
label.show()
app.exec_()
```

**Comment by tacaswell** [comment]
Is this local or over ssh?

**Comment by 2sn** [comment]
I now went to try the most besic, just using `tkagg`, after restarting the computer, to make sure all libraries are current and no old versions persist.  But even with that, e.g., the file dialog does not work, drop-down box on file type is just grey, and interactive file saving is not possible.  Sometimes when windows are deleted, the background task seems to get stuck and windows are no longer re-drawn.  Maybe it is some of the libraries matplotlib uses to manage background jobs, threads or asyncio have been updated and their new cousins interact poorly together with ipython?

**Comment by tacaswell** [comment]
Are you using readline or prompttoolkit for IPython's input? And have you tried manually running `%gui tk` or `%matplotlib tk`?

**Comment by 2sn** [comment]
in IPython I use %pylab by default (called in ipython config file).
It seems to used prompt_toolkit, when I run
```python
import sys
   ...: for x in sys.modules.keys():
   ...:     if x.startswith('prompt'):
   ...:         print(x)
   ```
it lists some 100 (sub-)packages.
Also, using `tkagg` (set in matplotlib config file), when I make a simple plot in bare python,
```python
>>> from matplotlib.pylab import *
>>> plot([0,1])
>>> show()
```
the plot seems to work.
Is there settings in matplotlib or IPython that influence the use of prompt toolkit and its interaction with matplotlib?

Disabling  all setup / config files, I can reproduce the problem using current (just updated) pip packages (python-3.9.6, matplotlib-3.4.3, ipykernel-6.1.0, prompt-toolkit-3.0.19, ipython-7.26.0) I can reproduce the error (e.g., just gray box in file type selection on plot save box) using
```python
import matplotlib as mpl
mpl.use('tkagg')
from matplotlib.pylab import *
plot([0,1])
show()
```

**Comment by 2sn** [comment]
Reproducibility seems not solid:

I ran another test of the same machine but over ssh, and there it seemed to work at first, then trying again on the original machine, it caused no problems.  I have to admit I am at a loss and see that is may be hard, if not impossible, to debug remotely. @tacaswell - I very much appreciate your help and suggestions, though.

(Original problem why I switched to tk in the first place over using default was not because I prefer it but because ipython would get stuck after closing windows when using gtk3 or qt5.)

Further test, using matplotibrc to set tkagg (which does not seem to cause the issue) I can now reproduce the problem (locally and remotely) using
```python
Python 3.9.6 (default, Jul 11 2021, 12:00:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.26.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %pylab
Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib

In [2]: plot([0,1])
Out[2]: [<matplotlib.lines.Line2D at 0x7f7379d434f0>]
```
So the problems seems to be related to `%pylab` integration with IPython.  At least, this is where is seems to become reproducibly apparent.

My apologies for the confusion and th many messages.

**Comment by jklymak** [comment]
Can I suggest you close this and open a new issue?  The problem with tkAgg is completely different than your initial problem with qt5agg. 

It would also be helpful if you could test your graphic frameworks directly rather than through a confusing chain of pylab, ipython, matplotlib.  Does all this happen in a script with no ipython or pylab?  If so, that makes debugging much simpler.  If you _need_ pylab to see the problem that would be helpful to confirm.

**Comment by 2sn** [comment]
@jklymak I think the issues are related and may be tied to `%pylab`.  I thought I first saw it happen even w/o `%pylab` but current tests I did could not confirm this.  I see the issue with tkAgg just on the command line input as in the last example I posted.

I did not see it in MacOS/M1, but dialog boxes use different system dialogs than on my very basic X11 Linux desktop (fvwm2).

**Comment by jklymak** [comment]
Hopefully you can narrow it down more than that.  However we do not provide %pylab so it would eb helpful to figure out what it is doing that is breaking your dialogs.  

Again however, your current issue is completely different than the description or title of the issue you are posting to. That is confusing and I'd still suggest closing this and opening a new issue or editing the issue description.

**Comment by tacaswell** [comment]
This sounds like something is very wrong with the input hook integration. See https://matplotlib.org/stable/users/interactive_guide.html for lots of details, but the short version is that to have the figure be "alive", we need to let the GUI event loop run from time-to-time and manage the alternation between the GUI event loop running and the IPython repl loop running (there are 2 infinite loops who both think they should be in charge of the main thread).   This getting out-of-whack can show many of the symptoms you describe.  If the windows are unresponsive it is because we have not given control back to GUI to process the UI events and if IPython hangs when you close the window we have somehow failed to give control back to the IPython event loop from the GUI.

I assume you have not changed your desktop manager recently?  I could _imagine_ that a very basic window manager would fail to provide some key event the toolkits are relying on to know a window closed, but given what I remember about the prompttoolkit inputhook functions that should not matter.  Have you changed virtual terminals recently?

**Comment by 2sn** [comment]
It does seem to run w/o issues on MacOS 11.5.1/M1.  Very different pop-up boxes provided by it graphical interface, and can;t be run over ssh (as far as I have be able to do).

**Comment by jklymak** [comment]
I am going to close, as I don't see a next-action here...

**Comment by 2sn** [comment]
I used different interface and did not have issues recently.  
My apologies, time did not allow to follow up further.
I will re-open when running into these issues again, could have been overcome with various updates to X11 and matplotlib and re-installing from source after 3.9.7 update.
