### ISSUE TITLE
`macosx` cursors break with images

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#20797]
@QuLogic, I just tested the `macosx` cursors a bit. It didn't have anything to do with this PR. Master is the same behavior as 3.4.2.

Somehow it has to do with the plotted mappable on the axes...
```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

ax.contourf([[0, 1], [2, 3]])  # cursor changes to the grab/zoom image
# ax.imshow([[0, 1], [2, 3]])  # cursor does not change

plt.show()
```

It works properly for contourf, but not for imshow/pcolormesh. The cursor works as expected for all mappables with `qt5agg`.

_Originally posted by @greglucas in https://github.com/matplotlib/matplotlib/issues/20620#issuecomment-893786577_

**Comment by greglucas** [comment]
This works on v3.2.2, but not 3.3.0 and later. I'm not able to build 3.2.2 locally, so can't do a bisect to figure it out exactly. A quick diff of the `_macosx.m` file between those versions didn't yield anything immediately obvious to me either... Hopefully that helps someone else narrow down the issue.

**Comment by QuLogic** [comment]
Could it be related to the mouse tracking changes in #16992?

**Comment by dstansby** [comment]
This bisects to https://github.com/matplotlib/matplotlib/commit/1857fcafd9cc9e4438e4f1942779c891276784be from https://github.com/matplotlib/matplotlib/pull/17092 by @anntzer

**Comment by anntzer** [comment]
I guess trying to display a 2-line status message may make macosx unhappy?  No other idea for now...

**Comment by greglucas** [comment]
I'm not exactly clear what the issue is here...
If I pass in a string I format that matches what the format_data is sending myself, everything seems to work fine...
`message = 'x=\N{MINUS SIGN}0.1234 y=1.234\n[1.234]'`
However, as far as I can tell that same message when coming from that section of code, causes the cursor to be lost. I thought perhaps it had something to do with the MINUS SIGN unicode character, but that seems to be rendered fine in that string as well.

The quick fix is to send in `message = message.replace('\n', \t')`, which still looks pretty good and you get the cursor back. But, it is a bit of a mystery to me why there is a difference even though the byte-codes seem to be identical to me.

**Comment by anntzer** [comment]
Probably(?) doesn't help, but
```patch
diff --git i/lib/matplotlib/backends/backend_macosx.py w/lib/matplotlib/backends/backend_macosx.py
index f9fb8713f4..2a12f1ca91 100644
--- i/lib/matplotlib/backends/backend_macosx.py
+++ w/lib/matplotlib/backends/backend_macosx.py
@@ -116,9 +116,6 @@ class NavigationToolbar2Mac(_macosx.NavigationToolbar2, NavigationToolbar2):
         _tool = SubplotTool(self.canvas.figure, toolfig)
         return canvas
 
-    def set_message(self, message):
-        _macosx.NavigationToolbar2.set_message(self, message.encode('utf-8'))
-
 
 @_Backend.export
 class _BackendMac(_Backend):
diff --git i/src/_macosx.m w/src/_macosx.m
index 366b786cf6..a547115175 100755
--- i/src/_macosx.m
+++ w/src/_macosx.m
@@ -1130,7 +1130,7 @@ NavigationToolbar2_set_message(NavigationToolbar2 *self, PyObject* args)
 {
     const char* message;
 
-    if (!PyArg_ParseTuple(args, "y", &message)) { return NULL; }
+    if (!PyArg_ParseTuple(args, "s", &message)) { return NULL; }
 
     NSTextView* messagebox = self->messagebox;
```
seems like a reasonable patch in any case?
