### ISSUE TITLE
[MNT]: Deprecate GTK3Cairo backend

### ISSUE THREAD

**Issue by rivanfebrian123** [matplotlib/matplotlib#20838]
### Summary

GTK3Cairo 3D plotting runs so slow and heavy, and seems to be unstable

### Proposed fix

Pleace deprecate this backend to make development much easier

**Comment by tacaswell** [comment]
Thank you for the suggestion, however I do not think we will deprecate this until we at least have  gtk4 merged and it does not absorb very much maintenance work (we only touch it a few times a year).

If you find the gtk3cairo unfit for your needs, but still want to use gtk3 + cairo you may be interested in https://github.com/matplotlib/mplcairo which has better performance (by directly binding to cairo rather than going through another Python layer) 

I'm going to close this, but hope to hear from you again @rivanfebrian123 !
