### ISSUE TITLE
[ENH]: Gantt chart request 

### ISSUE THREAD

**Issue by Asteliks** [matplotlib/matplotlib#20865]
### Problem

I would like to create an advanced aggregated Gantt chart I wish it could look sth like this:
![Gantt example](https://user-images.githubusercontent.com/62251475/130223305-d0a3513b-be40-4863-8a39-eff79ecf5874.png)

The colors are depicting the different stages of sub tasks, for example green in done, red is in backlog etc.

**Comment by tacaswell** [comment]
Thank you for your suggestion @Asteliks , however this is sufficiently specialized that I think it is a better fit for a third-party extension library rather than core Matplotilb.  In particular, I can see there being many ways to encode the state of the gnatt chart (what are the tasks, their state, ...) and several ways to map each of those structures to Matplotlib's Artists. 

If you are interested in writing such an extension I suggest starting with https://github.com/matplotlib/matplotlib-extension-cookiecutter

----

From looking at your sketch I think you either want to use `imshow` + a `Rectangle` for the outline or `Axes.broken_barh` https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.broken_barh.html .

If you want to continue the discussion about how to implement the charts, can we please move the discussion to https://discourse.matplotlib.org ?
