### ISSUE TITLE
[Bug]: Exported SVG files are no longer imported Affinity Designer correctly

### ISSUE THREAD

**Issue by tobywise** [matplotlib/matplotlib#20910]
### Bug summary

When importing SVG files created by Matplotlib into Affinity Designer, text characters are imported on top of one another. There are no issues importing into Inkscape, and I have not tried any other software.

### Code for reproduction

```python
# Exporting .SVG using the following code
plt.savefig('filename.svg')
```

### Actual outcome

![matplotlib_affinity_text](https://user-images.githubusercontent.com/10914118/130940603-39cc3b92-c033-47fb-8031-e747c4231549.png)

### Expected outcome

Matplotlib SVGs were imported into Affinity Designer correctly prior to #17669 - specifically this commit https://github.com/matplotlib/matplotlib/pull/17669/commits/7480805c2dfb934e7c62eb437d75902e2666d987 

### Operating system

Windows

### Matplotlib Version

3.4.3

### Installation

pip

**Comment by tacaswell** [comment]
@tobywise Do you have an xref to the issue with AD?

**Comment by tobywise** [comment]
Here's my report on their bug reporting forum https://forum.affinity.serif.com/index.php?/topic/148539-bug-in-svg-imports/&tab=comments#comment-830429

**Comment by LorenzoPeri17** [comment]
This seems to be still an issue in latest versions of matplotlib and Affinity Designer. 
Generating SVGs and tweaking them in Designer is a key part of my workflow.
I've collected a couple of tricks I found in a [small module](https://pypi.org/project/AffinitySvgPatcher/1.0.0/).
The two main workarounds seem to be:
* in `text` elements, replace `font` attributes with `font-size` and `font-family` (`font` is [apparently ignored](https://forum.affinity.serif.com/index.php?/topic/173734-font-sizes-in-imported-svg-documents-are-sometimes-interpreted-incorrectly/) by AD),
* in `xlink:href` replace `x` and `y` attributes with `transform=translate(x y)` (AD seems to ignore `x` or `y` attributes in `href`s).
Patching those two attributes seems to usually fix the problems.

I'd be happy to contribute a PR (it should be a matter of changing no more than 10 lines in `matplotlib/backends/backend_svg.py`) if it is welcome :)

**Comment by timhoffm** [comment]
Thanks for the suggestion.

Do you have any documentation / specification links which prove that the suggested changes are equally valid (or ideally even preferred)? We should tailor our output to a specification not to what some individual program has implemented. Otherwise there's a risk of breaking the use in other programs.

**Comment by LorenzoPeri17** [comment]
Thanks for the prompt reply! I agree that it is best to follow the spec rather than chase down bugs of individual editors. However, I think there might be an argument for both changes. I have done some digging in the docs and the mpl code, and here are my findings.

### Font

While [both ways are supported in CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/font), the [mozilla svg docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/font-size) seem to separate `font` into its separate constituent properties. The [w3 docs](https://www.w3.org/TR/SVG11/text.html#FontPropertiesUsedBySVG) defines `font` as 

> Shorthand property for setting [‘font-style’](https://www.w3.org/TR/SVG11/text.html#FontStyleProperty), [‘font-variant’](https://www.w3.org/TR/SVG11/text.html#FontVariantProperty), [‘font-weight’](https://www.w3.org/TR/SVG11/text.html#FontWeightProperty), [‘font-size’](https://www.w3.org/TR/SVG11/text.html#FontSizeProperty), ‘line-height’ and [‘font-family’](https://www.w3.org/TR/SVG11/text.html#FontFamilyProperty).

Since setting `font` rather than the separate properties is just a shorthand that may cause compatibility issues, I can see an argument for matplotlib doing the _most correct_ thing and setting style attributes indvidually

### xlink:href

Similar case for `xlink:href`, with the notable difference that [it has been deprecated in favour of `href` without the `xlink` namespace in SVG2](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href). Looking at the [w3 docs for the layout of the `use` tag (5.6.2)](https://www.w3.org/TR/SVG/struct.html#UseLayout), there seems to be a lot of historical baggage on how it's handled, but `x` and `y` attributes get transofmed into a `translate(x y)` in the end. There seems to be even more subtleties when `x` and `y` are used within a `g` tag.

To me this issue seems more of an Affinity shortcoming (it seems to work fine on inkscape and most browsers). However, this is the behaviour people are most likely to run into because it is the default way in which the svg backend currently renders axes lables and ticklables. 

More specifically, current the svg backend in `RendererSVG._draw_text_as_path` defines layouts using `x` and `y` if it does not contain any latex (`ismath = False`)
> ```python
># if not ismath:
>     attrib = {'xlink:href': f'#{glyph_id}'}
>     if xposition != 0.0:
>         attrib['x'] = _short_float_fmt(xposition)
>      if yposition != 0.0:
>         attrib['y'] = _short_float_fmt(yposition)
>     writer.element('use', attrib=attrib)
>```
while it uses `tranfsorm=translate(x y)` if `ismath` is `True`
> ```python
># else:
>     writer.element(
>    'use',
>    transform=_generate_transform([
>    ('translate', (xposition, yposition)),
>    ('scale', (scale,)),
>    ]),
>     attrib={'xlink:href': f'#{char_id}'})
>```

Since both behaviours are equivalent according to the docs and present in the current matplotlib implementation, I could see an argument to have `translate` in both for the sake of compatibility.

Let me know your thoughs! :)

**Comment by timhoffm** [comment]
Thanks for the reseach work. This sounds reasonable to me and I'll support a change. However, I'd like to have a second opinion from another core dev.

**Comment by tacaswell** [comment]
I think there are 3 proposed changes:

 - `xlink:href` -> `href`.  It looks like it was deprecated in svg2, but svg2 is still a draft.  My read is we should hold off on that for now?
 - using `transform=` in both branches seems reasonable to me
 - splitting font parameters back up seems reasonable (I think we somewhat recently merged them together)

**Comment by LorenzoPeri17** [comment]
Sounds good to me! I'm happy to hold off on `xlink:href`, also because that does not seem to cause issues with any SVG app. I'll get working on a PR for the other two changes since you both seem happy with them :)

**Comment by QuLogic** [comment]
> splitting font parameters back up seems reasonable (I think we somewhat recently merged them together)

They were merged in 3.5: #19253

**Comment by tacaswell** [comment]
I have a slight worry that there is a bug the other way where some program does not like the many-entry.  I have a vague memory of some svg tests where the weight was wrong when generating the baseline on some platforms that we fixed by re-generating to get the single-string version of the font.

**Comment by QuLogic** [comment]
That was a special-casing in our converter, not the external program: https://github.com/matplotlib/matplotlib/pull/27723/commits/effefafcb95d9140ab1c692b938ba09fdab4719d

**Comment by tacaswell** [comment]
ah, I am glad I miss-remember there!

**Comment by LorenzoPeri17** [comment]
I found some time to work on the [PR](https://github.com/matplotlib/matplotlib/pull/28504) and update the check in the converter higlighted before. Some tests failed on azure because of a timeout on the interactive backend (which I don't think should be affected by the changes?), but all the svg-related tests seem to be passing, and now all the test images open correctly in the latest version of Affinity Designer 2.

**Comment by tobywise** [comment]
@LorenzoPeri17 just wanted to say thank you for figuring out a fix for this - I've been using awkward workarounds for the past 3 years!
