### ISSUE TITLE
[Bug]: label strings that start with "_" are excluded from legends

### ISSUE THREAD

**Issue by rowlesmr** [matplotlib/matplotlib#21295]
### Bug summary

in (at least) pyplot.plot, labels that begin with an underscore are not included in legend entries

### Code for reproduction

```python
import matplotlib.pyplot as plt

x=[1,2,3,4]
y1=[1,2,4,8]
y2=[0,1,3,9]

plt.plot(x, y1, label="_label")  # this label is not included in the legend
plt.plot(x, y2, label="label")
plt.legend()
plt.show()
```

### Actual outcome

![Figure_1](https://user-images.githubusercontent.com/14921460/136145921-796a29da-e4ec-473b-8fab-de39dcf8e4b6.png)

### Expected outcome

![Figure_2](https://user-images.githubusercontent.com/14921460/136145983-f2775b8d-07aa-4c83-81b0-85e461d2f985.png)
I created this by labelling each plot with a leading space (" _label"), so the alignment is a little off, but it shows the idea

### Operating system

Windows 10

### Matplotlib Version

3.4.3

### Matplotlib Backend

Qt5Agg

### Python version

3.9.4

### Installation

pip

**Comment by jklymak** [comment]
This is expected behaviour: https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.legend.html "Specific lines can be excluded from the automatic legend element selection by defining a label starting with an underscore."  This has been long-standing behaviour and I dont' think there is any appetite to change it.  Thanks!

**Comment by AleksandarLukic96** [comment]
Hi,
A workaround that somewhat worked for me, was to add a whitespace at the front of the label:
label = "_label"
label_new = ' ' + label

This could also be thrown into a loop to update all the labels which start with a '_' to ' _'.

You can still slightly see the whitespace in the legend, but at least the label is displayed :) 
Hope that helps!

**Comment by skjerns** [comment]
In the newest version of matplotlib this behaviour has been removed.

i.e. legend labels are now also printed when they start with an underscore

**Comment by jklymak** [comment]
@skjerns that would be very surprising - if that is actually the case, please open a new issue with a reproducible example

**Comment by skjerns** [comment]
> MatplotlibDeprecationWarning: An artist whose label starts with an underscore was passed to legend(); **such artists will no longer be ignored in the future**. To suppress this warning, explicitly filter out such artists, e.g. with [art for art in artists if not art.get_label().startswith('_')].

I guess this future has arrived?  

I could not find any PR that introduces this change, but it's mentioned in the changelog for 3.10. 

Quite a shame, that was a useful feature!

<img width="750" height="240" alt="Image" src="https://github.com/user-attachments/assets/bf1fd984-6136-4418-834c-10b41ec8c5e5" />

reproducible example

```python
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.DataFrame({'timepoint': np.random.randint(0, 10, 1000),
      'class': np.random.choice(['cat', 'dog', 'duck', 'hare'], 1000),
      'probability': np.random.rand(1000)
})
sns.lineplot(df, x='timepoint', y='probability', hue='class')

# previously, providing underscores as names was hiding the label
# this has unfortunately been deprecated
plt.legend(['cat', *['_']*5, 'hare'])
```

**Comment by tacaswell** [comment]
The filtering still happens when we discover both the artists and the labels, but does not happen if the user explicitly passes them to us.  This makes sense (if the user did not want the artist in the legend, they could have not passed it it) and solves the bug reports we got of "I asked for this to be in the legend and it got silently dropped!".

This use case is a hybrid where mpl is discovering what to label and the user is providing a replacement set of labels (which is very brittle...if sns decides to re-order the creation of the lines this code will still run without error but the labels will be scrambled).  I think that this behavior was exploiting a quirk and dropping it is the right path as if you want to filter there are other explicit ways, but if you wanted to have a label start with `_` there was no way to do it.

This will get you the same effect that will work with all versions of mpl and is robust to changes to the details of how mpl's artists-for-legend discovery works, the details of how seaborn, and the addition or removal of categories in the data:

```python
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.DataFrame({'timepoint': np.random.randint(0, 10, 1000),
      'class': np.random.choice(['cat', 'dog', 'duck', 'hare'], 1000),
      'probability': np.random.rand(1000)
})
# it would be better if sns returned the artists rather than the Axes
ax = sns.lineplot(df, x='timepoint', y='probability', hue='class')

plt.legend(handles=[ln for ln in ax.lines if ln.get_label() in ('cat', 'hare')])
plt.show()
```

**Comment by skjerns** [comment]
Would it be an option to implement a specific keyword? Oftentimes it is much easier to simply filter/rename out legend entries you don't want posthoc with `plt.legend(['_', 'second'])`. 

Especially for adhoc-REPL renaming of legends this is significantly faster than replotting the entire figure. Often I need to do miniscule changes to specific label names, and it has become so much more cumbersome now.

e.g. enabling `_nolegend_` to also act here to suppress a specific legend entry?

**Comment by rcomer** [comment]
@skjerns note that we do not encourage passing only labels to `legend` in general. See point 4 here https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.legend.html#matplotlib.axes.Axes.legend

You can filter out legend labels with

```python
ax = plt.gca()
handles, labels = ax.get_legend_handles_labels()
ax.legend(handles[1], 'second')
```

Or keep hold of the artists and set the labels directly on them.

```python
line1, = plt.plot([0, 1], label='first')
line2, = plt.plot([0, 2], label='second')

plt.legend()  # Legend shows 2 entries

line1.set_label('_')
plt.legend()  # Legend shows 1 entry

```

**Comment by timhoffm** [comment]
I can see the case for interactive sessions, e.g. You've plotted two lines and post-hoc want to add a legend only for the second line:
```
plt.plot(x, y)
plt.plot(x, y2)
plt.legend(["_", "second"])
```
`"_nolegend_"` could be made possible and is logically consistent. But I wonder wether that's too cumbersome for interactive sessions. We may alternatively support `"_"` (may be less good to remember) or `None`.
