### ISSUE TITLE
[Doc]: Mix of `.. notes::` and numpydoc Notes

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#21538]
### Problem

We currently have a mix of `.. notes::` and numpydoc Notes in the docstrings, and they render differently (compare e.g. https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.grid and https://matplotlib.org/devdocs/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html#mpl_toolkits.mplot3d.axes3d.Axes3D.zaxis_date).  Admittedly I'm not sure we can be always consistent, because (I think?) there can be only one Notes numpydoc section whereas there can be as many `.. notes::` as needed with any nesting.  Perhaps we should try to improve partial consistency, or perhaps not...  Just pointing this out :)

### Matplotlib Version

3.5.0.dev2456+g2c3f14ed28

### Matplotlib documentation version

3.5.0.dev2456+g2c3f14ed28

**Comment by timhoffm** [comment]
Although both are called „notes“ the serve a different purpose. The numpy section is for general notes on the complete function. These should be used for additional information that is not quite important (because it’s rendered at the bottom of the docstring). The rst notes admonitions are notes to the local context (or sometimes to highlight some important remark close to the top of the docstring, as in your example. See also https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.plot.html?highlight=plot#matplotlib.axes.Axes.plot for a docstring that uses both.

I think we‘re mostly using them correct.

**Comment by oscargus** [comment]
I add the sentences starting with `Note:` (and `NB:` and `Remark:` and ...).

**Comment by timhoffm** [comment]
I'm closing this as "won't fix". The usage is generally correct. While I stated above that `zaxis_data` would better be an admonition, it would be cumbersome to insert that into the existing docstring:

https://github.com/matplotlib/matplotlib/blob/69f9ebf6f84dc0b3618cf6ef74e074f2e6f3fed8/lib/mpl_toolkits/mplot3d/axes3d.py#L1075-L1083

The Notes section is not ideal but simple and good enough.
