### ISSUE TITLE
[Bug]: get_tight_layout() returns False after setting tight_layout()

### ISSUE THREAD

**Issue by mdecleir** [matplotlib/matplotlib#21682]
### Bug summary

I am not sure if this is a bug, but I don't know where else to ask/report this.
I was trying to undo/reset the `tight_layout()` of a figure after the fact, using `fig.set_tight_layout(False)`.
However, that does not seem to work.
I noticed that `fig.get_tight_layout()` returns False even when `tight_layout()` has been applied.

### Code for reproduction

```python
from matplotlib import pyplot as plt
fig, ax = plt.subplots()
ax.scatter([1,2],[3,4])
fig.tight_layout()

print(fig.get_tight_layout())
```

### Actual outcome

`fig.get_tight_layout()` returns False

### Expected outcome

I would expect `fig.get_tight_layout()` would return True after doing `fig.tight_layout()`

### Operating system

OS/X

### Matplotlib Version

3.4.2

### Matplotlib Backend

MacOSX

### Python version

3.7.10

### Installation

conda

**Comment by tacaswell** [comment]
`fig.tight_layout()` is "compute the tight layout now" https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.tight_layout and `fig.set_tight_layout()` is "turn tight layout on so it gets run at save time" https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.set_tight_layout.

While confusing, I think that this is the actually the expected behavior.

**Comment by jklymak** [comment]
This is being discussed on discourse.  Please don't double post!  I'll close here.    Thanks for your understanding.
