### ISSUE TITLE
[ENH]: Native waterfall chart

### ISSUE THREAD

**Issue by jnsspam** [matplotlib/matplotlib#21828]
### Problem

I'm trying to create a waterfall plot.  There are separate libraries that I could import to create one (e.g., https://www.machinelearningplus.com/waterfall-plot-in-python/), but I these libraries limit customization in ways that a matplotlib user like me finds disappointing.   It would be great if there were a built-in way to create these via matplotlib.

**Comment by jklymak** [comment]
This is just a bunch of bars with colors and positions depending on change.  I think this would make a great example, but I don't think would be a good candidate for a new basic plot type. I believe this chart type also that this chart type already exists in mpl-finance: https://github.com/matplotlib/mplfinance though they call it a "renko" plot (which is good, because in my field a "waterfall plot" is very different than this - in fact I'm not sure why this would be called a waterfall plot - perhaps it was invented during a stock market crash).

**Comment by tacaswell** [comment]
That was not at all what I was expecting when I clicked the link (I was expecting either a khymograph or a bunch of Line2Ds with vertical offsets (which are the two very different tings that people I work with assert are called "waterfall plots")).



It looks like `waterfall_chart` return the Figure and Axes it creates (https://github.com/chrispaulca/waterfall/blob/76aca3543b39a79a82bd82137928d2b023078701/waterfall_chart.py#L163).  The best coures of action may be to reach out to @chrispaulca to get the customization knobs you need in that package (and maybe get it listed on https://matplotlib.org/mpl-third-party/).  If that does not work out, given the reference to finance in the write up this would be better proposed to mplfinance. 

----

Thank you for the suggestion @jnsspam , however I think that there is too much variation between domains to be a good candidate for a core plotting method, so I am going to close this as "wont fix".   I think that by having this functionality live in an external package you will get a much better outcome as a smaller domain specific package will be able to make more assumptions about the domain (so it will be easier to use), be able to have different dependencies that core Matplotlib (we can not depend on pandas!), not be tied to our strict back-compatibility policies, and release at what ever cadence makes sense (so you can make mistakes and iterate fast!).

I hope you are not discouraged and we hear from you again!
