### ISSUE TITLE
[Bug]: Matplotlib leading to Spyder kernel restarting and PyCharm error exit code

### ISSUE THREAD

**Issue by BOZHENG001** [matplotlib/matplotlib#21842]
### Bug summary

After updating `matplotlib version 3.5.0` through `conda update`, there seem to be some issues using matplotlib in both Spyder and PyCharm, but they show different phenomena. I try to run a simple script using matplotlib (Please check the code in the `Code for reproduction`), what I see is described below:

In Spyder, the phenomena depend on the `preferences` (settings):
If the `Inline Backend` is used, the script can be run without any issues. But if the `plt.show()` is commented, I will not see the figure showing (Normally in Spyder, even without the code `plt.show()`, the figure should be shown.), and after a while, I see `Restarting kernel...` in the console.
If the `Automatic Backend` is used no matter the code `plt.show()` is commented or not, after the script is run, I can see the figure window popping up, but no figure is shown and the figure window is disappeared after one second around. After that, the `Restarting kernel...` is shown in the console.

In PyCharm:
After the script is run, again I can see the figure window popping up but no figure shown in the window. After around one second, the figure window disappears and the exit code is shown as `Process finished with exit code -1073741819 (0xC0000005)`. If the code `plt.show()` is commented, the figure is not shown anymore which is normal while using PyCharm, and the exit code is shown as `Process finished with exit code 0`.

I consider there can be something wrong or bugs within the newest version of matplotlib, or maybe my setting issues. Could anyone help me with this issue?

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

x=np.arange(0,10)
y=np.arange(0,10)

plt.plot(x, y)
plt.show()
```

### Actual outcome

Spyder:
`Restarting kernel...`

PyCharm:
`Process finished with exit code -1073741819 (0xC0000005)`

### Expected outcome

A figure window with the expected figure shown on it

### Operating system

Windows 10

### Matplotlib Version

3.5.0

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.8.12

### Installation

conda

**Comment by jklymak** [comment]
Sorry this is a problem for you,  however, we don't maintain either the PyCharm or the Spyder backends.  If you report it to them, and there is an action item for us, please feel free to re-report, but this should be taken up with those projects.  Its possible you may also get help from https://discourse.matplotlib.org, or on stack overflow.  Thanks for your understanding.

**Comment by tacaswell** [comment]
Can you try down-grading freetype away from 2.11.0?

Searching for "Process finished with exit code -1073741819 (0xC0000005)" gets a bunch of hints suggesting that your installations are crossed (meaning you have incompatible dlls).   I also noted in spyder-ide/spyder#16841 you have mixed versions of Matplotlib installed from both pip and conda.  It being freetype as the problem is consistent with what you are reporting about pycharm (because if you never show the window, then we never render the figure, which means we never try to draw text, which means we never make any calls into freetype so it "works" only because you did not to the thing that breaks).  I expect it to fail if you tried to save the figure as well.

**Comment by BOZHENG001** [comment]
@tacaswell Thanks for your suggestion. I have already downgraded `freetype` from `2.11.0` to `2.10.4`, and plotting seems to work properly now.
