### ISSUE TITLE
[Bug]: Colormap + NoNorm only plots one color under `matplotlib` 3.5.0

### ISSUE THREAD

**Issue by dominiquesydow** [matplotlib/matplotlib#21870]
### Bug summary

My aim is to plot a colormap with e.g. 5 discrete colors (with 5 ticks centered per color).

Under `matplotlib` 3.4.3, I got this working with the code snippet below using `NoNorm`; under 3.5.0, only one color is plotted.

Is this a bug - or is my setup incorrect/unidiomatic and worked only by chance before?

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib import cm, colors

data = [1, 2, 3, 4, 5]

fig, ax = plt.subplots(figsize=(6, 1))
fig.subplots_adjust(bottom=0.5)

norm = colors.NoNorm(vmin=min(data), vmax=max(data))
cmap = cm.get_cmap("viridis", len(data))
cbar = fig.colorbar(cm.ScalarMappable(norm=norm, cmap=cmap), cax=ax, orientation="horizontal")
print(cbar.get_ticks())
```

### Actual outcome

![image](https://user-images.githubusercontent.com/7207093/144764565-fdd2108a-4b81-434e-8de4-a56f7cc93436.png)

This _is_ the output under `matplotlib` 3.5.0.

### Expected outcome

![image](https://user-images.githubusercontent.com/7207093/144764559-9b4bb901-98d9-4574-b80f-ba6401867106.png)

This _was_ the output under `matplotlib` 3.4.3.

### Operating system

Ubuntu

### Matplotlib Version

3.5.0

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.9.7

### Jupyter version

3.2.4

### Installation

conda

**Comment by tacaswell** [comment]
This definitely is a regression, sorry about that.

This bisects back to  146856b03e85aa4b1becdd89fe1628f98fed2a05 /  https://github.com/matplotlib/matplotlib/pull/20054which is part of an on going effort to make the colorbar code "less special" and hence easier to maintain and work with, unfortunately it looks like then special path for handling `NoNorm` (which is when compared to our other norms quite special as its output domain is what ever you put in rather than [0, 1]) did not make it across quite right.

I'll see if I can make any progress on sorting this out, but this may need attention from @jklymak.

**Comment by jklymak** [comment]
Yes, sorry we broke this.  Some of colorbars' features were completely untested, so we are finding lots of things dropped in 3.5.0.  We will try and have all  reported ones squashed by 3.5.1....
