### ISSUE TITLE
[Bug]: pcolormesh sometimes respects autolimit_mode and sometimes doesn't

### ISSUE THREAD

**Issue by bmcfee** [matplotlib/matplotlib#21888]
### Bug summary

When `axes.autolimit_mode='round_numbers'`, the behavior of pcolormesh seems inconsistent.  Depending on whether coordinates are implicit or explicit, the axes limits may or may not stick to the mesh.

I'm labeling this as a bug, but I'm not sure which behavior should be considered "correct".  However, it does seem strange that it differs in this way.

### Code for reproduction

```python
import matplotlib as mpl
import numpy as np
import matplotlib.pyplot as plt

mpl.style.use('classic')  # to force autolimit_mode='round_numbers'

fig, ax = plt.subplots(nrows=3)
C = np.random.randn(12, 200)


# First with explicit coordinates
ax[0].pcolormesh(np.arange(C.shape[1]), np.arange(C.shape[0]), C, cmap='gray_r')

# Second with implicit coordinates
ax[1].pcolormesh(C, cmap='gray_r')

# And imshow for comparison
ax[2].imshow(C, origin='lower', aspect='auto', cmap='gray_r')
```

### Actual outcome

![image](https://user-images.githubusercontent.com/1190540/145312135-a1b962de-34e5-42c3-82d2-e0f3639e510f.png)

### Expected outcome

I would expect either all three methods to override autolimit mode here (ie be sticky?), or none of them to.

### Additional information

Using a different style where `axes.autolimit_mode = 'data'`, all three examples behave equivalently.

### Operating system

ubuntu

### Matplotlib Version

3.5.0

### Matplotlib Backend

'module://ipympl.backend_nbagg'

### Python version

3.9.7

### Jupyter version

3.2.4

### Installation

conda

**Comment by greglucas** [comment]
The implicit coordinates are not the same as the explicit coordinates in your first two cases. See https://matplotlib.org/devdocs/gallery/images_contours_and_fields/pcolormesh_grids.html for a description of the shading options for pcolormesh.
You can get the coordinates of each mesh to verify:
```python
mesh = ax[1].pcolormesh(C, cmap='gray_r')
print(mesh.get_coordinates()
```
and to explicitly set the coordinates the same would be adding one to your dimensions to specify the edges rather than the centers, which will produce the same result in ax0 and ax1
```python
ax[0].pcolormesh(np.arange(C.shape[1] + 1), np.arange(C.shape[0] + 1), C, cmap='gray_r')
```

**Comment by bmcfee** [comment]
> The implicit coordinates are not the same as the explicit coordinates in your first two cases.

Yes, you're right, the example uses centered coordinates rather than corners.  But I think the issue is still valid: why should corner coordinates stick the axes while centered coordinates don't?

**Comment by greglucas** [comment]
In the first case the corners are created for you and go past 0 out to -0.5, which then applies "round numbers" to round down to -50 on the axis limits it seems. Another "fix" for this is to ignore the final dimension of your data array, which is what was done in previous versions of MPL: `C[:-1, :-1]`. The basic point here is that a quadmesh is defined by the 4 edges surrounding the data, not the centers, so the data dimensions cannot be the same shape as the coordinate dimensions. If there is more that could be added to that page to describe this issue better a PR would be very welcome!

**Comment by jklymak** [comment]
I think this is behaving as intended, and the confusion here is just what the data limits actually are under the hood of pcolormesh.  If concerned about ambiguity, users should simply provide co-ordinates rather than depend on arbitrary defaults.  I'll close because I don't think there is an action item, but feel free to continue the discussion if you feel there is something we should do differently that will still be backwards compatible.  Thanks!

**Comment by bmcfee** [comment]
Ok, I understand what's going on now, thanks for the clarification.
