### ISSUE TITLE
[Bug]: Matplotlib is unable to apply the boundaries in the colorbar after updating to 3.5.0

### ISSUE THREAD

**Issue by krysros** [matplotlib/matplotlib#21909]
### Bug summary

Matplotlib is unable to apply the boundaries in the colorbar after updating to 3.5.0. Please compare the results in the screenshots between version 3.5.0 and the previous version 3.4.3. 

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm

n_radii = 8
n_angles = 36

# Make radii and angles spaces (radius r=0 omitted to eliminate duplication).
radii = np.linspace(0.125, 1.0, n_radii)
angles = np.linspace(0, 2*np.pi, n_angles, endpoint=False)[..., np.newaxis]

# Convert polar (radii, angles) coords to cartesian (x, y) coords.
# (0, 0) is manually added at this stage,  so there will be no duplicate
# points in the (x, y) plane.
x = np.append(0, (radii*np.cos(angles)).flatten())
y = np.append(0, (radii*np.sin(angles)).flatten())

# Compute z to make the pringle surface.
z = np.sin(-x*y)

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})

surf = ax.plot_trisurf(x, y, z, linewidth=0.2, antialiased=True, cmap=cm.coolwarm)

boundaries = np.linspace(np.min(z), np.max(z), 10, endpoint=True)
fig.colorbar(surf, shrink=0.5, boundaries=boundaries, pad=0.1)

plt.show()
```

### Actual outcome

![Figure_matplotlib==3 5 0](https://user-images.githubusercontent.com/5299999/145533380-64fb0801-c30f-413e-8709-3bfe8ff202f5.png)

### Expected outcome

![Figure_matplotlib==3 4 3](https://user-images.githubusercontent.com/5299999/145533365-2c0b8053-9789-46e8-a014-3da2d8ff3ddd.png)

### Operating system

Windows

### Matplotlib Version

3.5.0

### Matplotlib Backend

TkAgg

### Python version

Python 3.9.9, Python 3.10.1

### Installation

pip

**Comment by jklymak** [comment]
Colorbars got a pretty substantial rewrite in 3.5, so sorry we broke this.  

OTOH, I'm not sure I understand your use of this kwarg here, and why you would use boundaries in the colorbar when the associated object is using a continuous norm.   To make the colorbar correspond with the data, you could make the data representation also have boundaries:

```python
from matplotlib.colors import BoundaryNorm
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import cm

n_radii = 8
n_angles = 36

# Make radii and angles spaces (radius r=0 omitted to eliminate duplication).
radii = np.linspace(0.125, 1.0, n_radii)
angles = np.linspace(0, 2*np.pi, n_angles, endpoint=False)[..., np.newaxis]

# Convert polar (radii, angles) coords to cartesian (x, y) coords.
# (0, 0) is manually added at this stage,  so there will be no duplicate
# points in the (x, y) plane.
x = np.append(0, (radii*np.cos(angles)).flatten())
y = np.append(0, (radii*np.sin(angles)).flatten())

# Compute z to make the pringle surface.
z = np.sin(-x*y)

fig, ax = plt.subplots(subplot_kw={"projection": "3d"})
cmap = cm.coolwarm
boundaries = np.linspace(np.min(z), np.max(z), 10, endpoint=True)
norm = BoundaryNorm(boundaries, cmap.N)

surf = ax.plot_trisurf(x, y, z, linewidth=0.2,
                       cmap=cmap, norm=norm)

fig.colorbar(surf, shrink=0.5, pad=0.1)

plt.show()
```


![boundaries](https://user-images.githubusercontent.com/1562854/145537681-814270fe-f3a0-4f81-b8d1-28632f74512a.png)

Note that the plot looks different!  I think it is confusing to specify the boundaries in the colorbar because users may think this will lead to the tri_surf gaining boundaries as well, whereas that is not the case.  Were you trying to make the colorbar different from the data?  

Note that the docs explicitly say that *boundaries* are only useful for `NoNorm` and "other unusual circumstances".  I'm not sure what the path forward is here.  We could probably get the old behaviour back, but I'm somewhat reticent.
