### ISSUE TITLE
[Bug]: twin axes doesn't apply(correctly) set_ylim 

### ISSUE THREAD

**Issue by AntSimi** [matplotlib/matplotlib#21973]
### Bug summary

I want to add a second axes with a shared axes (X) which are previously set with `aspect='equal'`, but set_ylim on first axes doesn't work.

### Code for reproduction

```python
import matplotlib
print(matplotlib.__version__)
from matplotlib import pyplot as plt
fig = plt.figure(figsize=(20,10))
ax = fig.add_subplot(111, aspect='equal')
ax2=ax.twinx()
ax.set_ylim(0,20)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/36040805/146359420-48154a4f-cc4b-4f55-b463-c230fe14945b.png)

### Expected outcome

Left axes must be set from 0 to 20

### Matplotlib Version

3.5.0

**Comment by jklymak** [comment]
```
import matplotlib
print(matplotlib.__version__)
from matplotlib import pyplot as plt
fig = plt.figure(figsize=(20,10))
ax = fig.add_subplot(111, aspect='equal')
ax2=ax.twinx()
ax.set_ylim(0,20)
print(ax.get_aspect(), ax.get_adjustable())
ax.set_adjustable('box')
plt.show()
```
yields `1.0 datalim`
and 
```
RuntimeError: Adjustable 'box' is not allowed in a twinned Axes; use 'datalim' instead
```

So what is happening is that you have twinned, so it is using datalim to enforce the aspect ratio, and you have an x axis that goes from 0-1 so it sets the ylimit to a narrowed field of view.  I suppose you could argue that the `set_ylim` should be respected, but Matplotlib has no way to know which is the preferred axes, is it looks like it is choosing the shared x axes.  

There may be a away around this depending on what you expect, but be aware that twinned axes and fixed aspect ratios obviously do not mix very well. I'm not sure if this is a bug or by design - I think @efiring worked on this last?

**Comment by efiring** [comment]
This is by design.  `apply_aspect` will not change a shared axis.

**Comment by AntSimi** [comment]
OK I understand
