### ISSUE TITLE
[Doc]: [source] link for deprecated functions leads to _api/deprecation.py

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#22039]
### Documentation Link

https://matplotlib.org/devdocs/api/dates_api.html#matplotlib.dates.MicrosecondLocator.set_data_interval

### Problem

see title, [[source]](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/_api/deprecation.py#L1693-L1696) links to  https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/_api/deprecation.py#L1693-L1696, i.e. the line numbers are correct but the file is wrong (`_api/deprecation.py` instead of `matplotlib/dates.py`)

### Suggested improvement

[source] link should lead to deprecated function, i.e. in the given example to https://github.com/matplotlib/matplotlib/blob/a35921c407aced5e65d39b29fd942676ee03679b/lib/matplotlib/dates.py#L1693-L1696

### Matplotlib Version

3.5.1

**Comment by tacaswell** [comment]
This will presumably would be a fix to https://github.com/matplotlib/matplotlib/blob/a35921c407aced5e65d39b29fd942676ee03679b/doc/conf.py#L580-L636

Labeled as good first issue because it involves no public API changes, but medium as you will need to work with the code linked above and do a bunch of code scraping to see if we can get back to the source of the decorated function!

**Comment by StefRe** [comment]
maybe it makes more sense to integrate this in https://github.com/sphinx-doc/sphinx/issues/1556  (if not already covered by https://github.com/sphinx-doc/sphinx/pull/9625) than to create an own version?

**Comment by StefRe** [comment]
Thanks @tacaswell for pointing me to the rigth file. With the help of https://bugs.python.org/issue34305 the fix was trivial.
