### ISSUE TITLE
bug:  when plotting in one color there is a default color 

### ISSUE THREAD

**Issue by IggyGIFBR** [matplotlib/matplotlib#22090]
When plotting in one color there is a default color and not the desired color.
If I add at least another point with a different color the colors are correct.
expected behavior if I have one color the plot will be in the same color for the same value as for two colors or more.

this example shows the problem and the expected when having more then one color.

import matplotlib.pyplot as plt 
import numpy as np

fig, ax = plt.subplots(1, 3)
size = 10
data = [ np.arange(size )] * size
DataArray = np.array(data)
x = DataArray.reshape((1,size * size))
y = np.arange(size * size)
colorBlue = [1.] * size * size
colorRed = [0.] * size * size

ax[0].set_title("all zero")
ax[0].scatter( x  , y ,c=colorRed )

ax[1].set_title("all ones")
ax[1].scatter( x  , y  ,c=colorBlue )

colorBlue[0] = 0.5
ax[2].set_title("all ones but one of them")
ax[2].scatter( x  , y  ,c=colorBlue )
plt.show()

![matplotlib color bug](https://user-images.githubusercontent.com/53514196/147924099-c1e56aa9-4170-4c06-bc39-35a36f9f9b96.PNG)

**Comment by jklymak** [comment]
`c` maps into the colormap given by the cmap command.  If you want to control the mapping you can set the *vmin* and *vmax* kwargs.  Please see https://matplotlib.org/stable/tutorials/introductory/usage.html#color-mapped-data and the documentation for `scatter`.  If you have any other questions, please ask at https://discourse.matplotlib.org - I am closing here because Matplotlib is working as expected.
