### ISSUE TITLE
[BUG]: The view of 3D plot and surface plot together does not work

### ISSUE THREAD

**Issue by skeshvar** [matplotlib/matplotlib#22165]
### Bug summary

Based on this code below, the line is exactly on top of the surface plot but by rotating along the z-axis, it's obvious that the perspective of the line with respect to the surface changes, as it should not. 

### Code for reproduction

```python
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
import math
pi = math.pi

x, y = np.meshgrid( np.linspace(-3, 7, 100) , np.linspace(-3, 7, 100))

V = np.linspace(-4, 4, 100)
U = np.linspace(-4, 4, 100) 

U, V = np.meshgrid(U, V)
X = U**2
Y = V**2

Z = U + 2*V

fig = plt.figure('1', figsize=(8,7))
ax = fig.add_subplot(111, projection='3d')
ax.plot_surface(X, Y, Z, cmap = plt.cm.coolwarm)

k=10
ax.plot(np.linspace(-2-k, 1+k, 10), np.linspace(-4-k, 1+k, 10), np.linspace(3-k, 4+k, 10), 'k' )

ax.set_xlabel('x')
ax.set_ylabel('y')
ax.set_zlabel('z')
plt.tight_layout()
```

### Actual outcome

The line seems to be plotted below the surface for some azimuthal angles.

### Expected outcome

The line should always be seen on top of the surface.

### Operating system

Windows 10

### Matplotlib Version

3.2.2

### Matplotlib Backend

Qt5Agg

### Installation

conda

**Comment by jklymak** [comment]
mplot3d does not have a proper ray tracing algorithm, so these artifacts from composing artists are always going to be a problem and not behave as you might expect.  I think you need to play with zorder depending on the view.  I think this is probably "Can't fix"

**Comment by skeshvar** [comment]
Thanks for the solution but it seems to me that "Can't fix" statement means that you guys are not planning to fix this issue ever?

**Comment by timhoffm** [comment]
The fundamental problem is that mplot3d is not using a 3D renderer but only draws artists on top of each other using some projections. This leads to the limitation you encounter here. This could only be fixed be rewriting the whole backend in OpenGL or similar. See here for more details https://matplotlib.org/devdocs/api/toolkits/mplot3d/faq.html#my-3d-plot-doesn-t-look-right-at-certain-viewing-angles.

While there is a rough idea that rewriting in OpenGL would be desirable, we currently neither have the capability nor the capacity to do this. Unless someone external shows up with either time or funding to do this, this will not move forward.

I'll close and mark as "won't or can't fix" because we have no plan to fix this. Sorry for the limitation.

**Comment by timhoffm** [comment]
Duplicate of #13580.
