### ISSUE TITLE
[Bug]: `IPython.utils.capture` does not capture plots in Jupyter

### ISSUE THREAD

**Issue by kolibril13** [matplotlib/matplotlib#22162]
### Bug summary

https://ipython.readthedocs.io/en/stable/api/generated/IPython.utils.capture.html does not capture plots in Jupyter

### Code for reproduction

```python
from IPython.utils.capture import capture_output
from IPython.display import display
import matplotlib.pyplot as plt

with capture_output(display=True) as result:
    plt.plot([1,2], [10,20])
print(result.outputs) # prints empty list
```
Fix: 
```py
with capture_output(display=True) as result:
    display(plt.plot([1,2], [10,20])) 
print(result.outputs) # works fine
```

### Actual outcome

![image](https://user-images.githubusercontent.com/44469195/148660484-7d5610e8-80ef-4123-87b4-7484f72b35c3.png)

### Expected outcome

The output should be captured with the line `plt.plot([1,2], [10,20])`

### Additional information

For my personal use, it is not necessary that this bug would be fixed, as there is a very easy workaround.
I just want to mention that this might be unintended behavior.

### Operating system

MacBook Air (M1, 2020) , macOS monterey

### Matplotlib Version

3.4.3

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

Python 3.9.5 

### Jupyter version

6.4.0

### Installation

pip

**Comment by QuLogic** [comment]
> module://ipykernel.pylab.backend_inline

That backend is here: https://github.com/ipython/matplotlib-inline/ and I think you need to report this issue to them.

**Comment by tacaswell** [comment]
I suspect that throwing `plt.show()` in the context would also work.  

Agree with @QuLogic , this is an interaction between the inline backend (which collects all of the figures and renders them to the display just after the cell executes) and the capture context manager.  `plt.plot` does not by itself create anything that is displayed so it is (correctly but not what you want) not captured (because there is nothing to capture because nothing has been put in the output (yet)).   When you call display you are explicitly pushing the rendered plot into the output of the cell and hence there is something to capture.

I'm going to close this because there is nothing that we can do about this on the Matplotlib side, this needs to be sorted out by matplotlib-inline / jupyter folks.

----

What would you expect:

```python
from IPython.utils.capture import capture_output
from IPython.display import display
import matplotlib.pyplot as plt

plt.plot(range(5))
with capture_output(display=True) as result:
    plt.plot([1,2], [10,20])
print(result.outputs) # prints empty list
```

to do?
