### ISSUE TITLE
[MNT]: Write a bot to post doc build issues

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#22176]
### Summary

When doc builds fail, most of the time it's due to ReST formatting or referencing issues.

Most issues have a form similar to 

> /home/circleci/project/doc/api/next_api_changes/behavior/22135-JSS3.rst:3: WARNING: py:obj reference target not found: Figure._localaxes

My standard way to find out the error is:
- Open CircleCI
- Download the build log
- Search for "WARNING"

This is cumbersome and not very discoverable for new contributors.

### Proposed fix

It would be great to have a bot post these warnings if CicleCI fails. I assume that would cover 95% of doc build failures and point contributors (new and experienced) to the problem so that they can solve it faster.

**Comment by ksunden** [comment]
As it turns out, the sections added in #23868 don't actually run on failed doc builds, rendering them ineffective. (They _do_ run on successful doc builds, not that it says anything other than "no errors or warnings")

See, for example [this run](https://app.circleci.com/pipelines/github/matplotlib/matplotlib/20467/workflows/006a23ca-5b59-4bfa-83dd-c587118854a7/jobs/72418) for which the doc build failed, but no such separate job for pulling out the errors/warnings.

I believe @QuLogic is planning on implementing a more full solution in the near term, including a bot-generated comment on the PR (correct me if I'm wrong/misremembering a conversation)

**Comment by QuLogic** [comment]
Yes, and thinking about it more, I think I have a simpler (in some ways) solution than we discussed, but I haven't fully tested it out yet.

**Comment by oscargus** [comment]
Agreed that they do not solve it. Not really clear why it is not executed though...

Just want to point out that it would also be good if a solution that writes back a GH comment also takes any deprecations into account. That part of the code actually seems to work as it should...

**Comment by oscargus** [comment]
I think I figured out the issue...
