### ISSUE TITLE
[ENH]: vector map 

### ISSUE THREAD

**Issue by sarge130** [matplotlib/matplotlib#22657]
### Problem

* I'm attempting to make a vector map using the quiver tool (to overlay vectors on a background plot), but implementation of the data I'm using has not been so intuitive.
* I have a 2D array with values indicating vector angle (additionally, another one indicating strengths). quiver requires converting the 2D arrays into a list of lists and the input parameters are not very intuitive (at least to me).
* Additionally, scaling the coordinate system is not a feature I've seen.

Minimum working example of how I'm able to achieve a "vector map"

```python
import matplotlib.pyplot as plt
import numpy as np
ones=np.ones((16,16)) # 2D numpy array containing coordinates
angles=ones*45 # 2D numpy array containing coordinate angles
olist=ones.tolist()
alist=angles.tolist()
ax=plt.subplot()
ax.quiver(olist,olist,angles=angles,headwidth=0,headlength=0,headaxislength=0,units='xy',width=0.1)
plt.show()
```

### Proposed solution

I would suggest a new plotting tool with the ability for direct input of 2D arrays for vector direction and magnitude with coordinate system transformations included as an option. A user with large plots may not want to include every single vector component, so an additional parameter could indicate the density of the plot where the plot only shows every fifth pixel in a row. (similar to a slice, though, this may be tricky with coordinate transforms). Additional options could include line thickness, color, arrowheads, etc.

Examples:
```python
ones=np.ones((16,16))
angles=ones*45
transform=ax.get_transform(WCS) # some coordinate system transformation object
ax.vectors(orientation=angles) # a plot of unit magnitude vectors with specificed orientations
ax.vectors(orientation=angles,density=slice(None,None,5)) # same as above with a reduced density
ax.vectors(magnitude=ones,orientation=angles) # input 2D arrays with magnitude and orientation
ax.vectors(magnitude=ones,orientation=angles,transform=transform) # transform coordinates similar to ax.contour
plt.show()
```

I'm not so well versed in the matplotlib coding structure but I would be happy to help to learn about how it works.

**Comment by timhoffm** [comment]
> the input parameters are not very intuitive (at least to me).

I agree that `quiver()` is quite complex and that the documentation could be improved.

> quiver requires converting the 2D arrays into a list of lists 

Arrays are perfectly fine.

Also, setting `headlength=0, headaxislength=0` should be sufficient to make the head disappear (`headwidth=0` can be left out).  This is the same as your plot:
```
import matplotlib.pyplot as plt
import numpy as np
ones = np.ones((16, 16))  # 2D numpy array containing coordinates
angles = ones * 45  # 2D numpy array containing coordinate angles
ax = plt.subplot()
ax.quiver(ones, ones, angles=angles, headlength=0, headaxislength=0, units='xy', width=0.1)
plt.show()
```

Concerning the remaining parameters: `units` applies to all arrow sizes apart from the length, i.e. `width`, `headwidth`, `headlength`, `headaxislength`. Since you made the head disappear, this only leaves `width`. i.e. this setting means that the line will be proportionally increased / decreased on scaling. Whether or not one wants that is rather a style choice since the line width does not carry information. Same for `width`.

Overall, `headlength=0, headaxislength=0, units='xy', width=0.1` are only styling parameters, that do not warrant a new function.

Your basic call is `ax.quiver(ones, ones, angles=angles)`. I agree that `U, V, angles` is a bit of a strange API and we'd probably better not added the possibility for angle values. It's rather confusing how that interacts with U, V and the resulting scaling. OTOH, I think having *angles* for vectors is rather rare compared to having the components *dx*, *dy*, and the API for that is fine. I suggest to convert to convert to components and essentially do:

```
angles = np.deg2rad(ones * 45)  # 2D numpy array containing coordinate angles
dx = np.cos(angles)
dy = np.sin(angles)
ax=plt.subplot()
ax.quiver(dx, dy, headlength=0, headaxislength=0)
```

**Comment by timhoffm** [comment]
@sarge130 thanks for the feedback. Could you give us a hint in what part of the admittedly long [quiver docstring](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.quiver.html#matplotlib.axes.Axes.quiver) information on magnitude+direction semantics would have helped you?

**Comment by timhoffm** [comment]
#22659 added more description to the quiver docs:
https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.quiver.html#matplotlib.axes.Axes.quiver

Hopefully this is now easier to understand.
