### ISSUE TITLE
[Bug]: figure and matshow

### ISSUE THREAD

**Issue by FredPaletou** [matplotlib/matplotlib#22833]
### Bug summary

it seems that doing, say figure(#) and a matshow doesn't work fine without adding a fignum=# into the matshow command

### Code for reproduction

```python
import numpy as np
import matplotlib.pyplot as plt

mat=np.random.rand(10,10)

plt.figure(1)
plt.matshow(mat)
#plt.matshow(mat, fignum=1)
plt.colorbar()
plt.show()
```

### Actual outcome

opens 2 windows (instead of one), with an empty figure(1) and the matrix in figure(2)

### Expected outcome

single window figure(1) with the matrix plot, which can be done right (only?) by adding fignum=1 into the matshow command

### Additional information

when doing multiple figures output, troubles with matshow

### Operating system

ubuntu

### Matplotlib Version

3.4.2

### Matplotlib Backend

Qt5Agg

### Python version

Python 3.8.10

### Installation

pip

**Comment by anntzer** [comment]
This has intentionally been the case basically since the beginning: https://github.com/matplotlib/matplotlib/blob/f2241b9510da5737a3bc46708895b5a04f081ca3/lib/matplotlib/pylab.py#L1401
and is therefore extremely unlikely to be ever changed.  Consider using the object-oriented interface (https://matplotlib.org/devdocs/tutorials/introductory/quick_start.html#coding-styles) for better control.
