### ISSUE TITLE
[ENH]: Cannot get colormaps registered by register_cmap() after restart python or IDE

### ISSUE THREAD

**Issue by 664787022** [matplotlib/matplotlib#22960]
### Problem

I used register_cmap() to register a new colormap, but i am not able to get that colormap by using get_cmap **after I turned off IDE and restarted.**
It seems that register_cmap() does not register a colormap permanently?  When i turn off python and restart, i  can't get that colormap i registered from matplotlib because the memory is released. 
**Is there any way to register a colormap permanently**, so that i don't need to register colormaps i create every time.

### Proposed solution

Allow register_cmap() to register colormaps permanently.

**Comment by tacaswell** [comment]
This is the expected behavior, `register_cmap` only makes changes to the running process.

I am very skeptical of this having a persistent effect.  While I do see why it would be useful it falls too much on the "application" side of the "application" vs "library" axis.   It would open up a huge amount of complexity to persist and automatically reload the colormaps on Matplotlib import.

That said, I strongly suggest you write up any specific customization you want (including registering colormaps) and put them in a `.py` file you can import at the top of your scripts / notebook.

I am inclined to close this as "won't implement", but would like a second dev to weigh in.

**Comment by anntzer** [comment]
Agreed with @tacaswell.

**Comment by timhoffm** [comment]
I agree that `register_cmap()` should not make any persistent changes.

I could imagine a way to add cmaps via config in a declarative way. However that needs design considerations  a format specification, and separate implementation paths. Such an extension seems reasonable but low priority.

**Comment by 664787022** [comment]
> This is the expected behavior, `register_cmap` only makes changes to the running process.
> 
> I am very skeptical of this having a persistent effect. While I do see why it would be useful it falls too much on the "application" side of the "application" vs "library" axis. It would open up a huge amount of complexity to persist and automatically reload the colormaps on Matplotlib import.
> 
> That said, I strongly suggest you write up any specific customization you want (including registering colormaps) and put them in a `.py` file you can import at the top of your scripts / notebook.
> 
> I am inclined to close this as "won't implement", but would like a second dev to weigh in.

Thanks for giving advice!

**Comment by 664787022** [comment]
> I agree that `register_cmap()` should not make any persistent changes.
> 
> I could imagine a way to add cmaps via config in a declarative way. However that needs design considerations a format specification, and separate implementation paths. Such an extension seems reasonable but low priority.

Thanks!
