### ISSUE TITLE
[Bug]: import failure when disk quota exceeded 

### ISSUE THREAD

**Issue by av9ash** [matplotlib/matplotlib#22986]
### Bug summary

When running a python script containing matplotlib module on a remote server machine, got the following errors:

### Code for reproduction

```python
import matplotlib.pyplot as plt
```

### Actual outcome

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/test-result-jenie/venv_trj/lib/python3.8/site-packages/matplotlib/pyplot.py", line 49, in <module>
    import matplotlib.colorbar
  File "/opt/test-result-jenie/venv_trj/lib/python3.8/site-packages/matplotlib/colorbar.py", line 21, in <module>
    from matplotlib import _api, collections, cm, colors, contour, ticker
  File "/opt/test-result-jenie/venv_trj/lib/python3.8/site-packages/matplotlib/contour.py", line 13, in <module>
    from matplotlib.backend_bases import MouseButton
  File "/opt/test-result-jenie/venv_trj/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 46, in <module>
    from matplotlib import (
  File "/opt/test-result-jenie/venv_trj/lib/python3.8/site-packages/matplotlib/textpath.py", line 8, in <module>
    from matplotlib import _text_helpers, dviread, font_manager
  File "/opt/test-result-jenie/venv_trj/lib/python3.8/site-packages/matplotlib/font_manager.py", line 1447, in <module>
    fontManager = _load_fontmanager()
  File "/opt/test-result-jenie/venv_trj/lib/python3.8/site-packages/matplotlib/font_manager.py", line 1442, in _load_fontmanager
    json_dump(fm, fm_path)
  File "/opt/test-result-jenie/venv_trj/lib/python3.8/site-packages/matplotlib/font_manager.py", line 1007, in json_dump
    _log.warning('Could not save font_manager cache {}'.format(e))
OSError: [Errno 122] Disk quota exceeded

### Expected outcome

no output, simpy return after import

### Additional information

similar to https://github.com/matplotlib/matplotlib/issues/9548/

### Operating system

Ubuntu

### Matplotlib Version

matplotlib-3.5.2

### Python version

Python 3.8.10

### Installation

pip

**Comment by tacaswell** [comment]
This is coming from this code:

https://github.com/matplotlib/matplotlib/blob/6997192263f39a1fc364350ae27ce427ca54e41b/lib/matplotlib/font_manager.py#L1044-L1049

I think what is happening here is that:
 - you have run out of quota space on your server
 - we are failing to write the font cache
 - we then put a warning into the log machinery
 - the log machinery _also_ fails to write because (I presume) you have a handler that writes logs to disk?

On one hand, we could also wrap the log call in an try-except and I guess just print if that also fails.  It makes sense that if disk writing fails for our use, it will also fail for the other, so we should try very hard to import.

On the other hand, if failing to log or not is fatal to the application should be between you and the logger you are using and we should not, as a library insert ourselves into that logic.

I also suspect that if you are out of disk, even if you get past this import lots of other things are going to go wrong.

**Comment by tacaswell** [comment]
@av9ash I took the liberty of setting the issue title to be something meaningful.

**Comment by timhoffm** [comment]
If I understand correctly: When there is no logger logging to disk, we should currently still be able to import.

If that's the case, we've done all we can do. Logging can happen in various places, not only within matplotlib. Logging to disk is an active user decision. It's your responsibility then to make sure logging does not conflict with your quota.

**Comment by oscargus** [comment]
I agree that it seems to be in the logging the error happens and that the Matplotlib part of the quota exceeded is handled as well as we can.

You can do something like:
```
import logging
import sys
logging.basicConfig(stream=sys.stderr, level=logging.DEBUG)
```
to set the logging to not use a file (or you can change the level to something higher, like `logging.ERROR` to not log any `warning`) . This will, as @timhoffm points out, probably be useful even later as Matplotlib (and many other libraries) do occasionally log stuff and a similar error will arise every time a library tries to do that.

**Comment by timhoffm** [comment]
Closing be cause this has to be handled by logging configuration on the user side.

**Comment by av9ash** [comment]
Hi,

Thanks for the comments and updates, I used the information given on this thread and softlinked the cache to a dir with more space to make it work.

Thanks
Avinash
