### ISSUE TITLE
[Bug]: with setuptools>=60, cannot find msbuild

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#23147]
In testing out #23146, I've been unable to fully update cibuildwheel because Windows builds fail. They cannot find `msbuild` with cibuildwheel >= 2.4.0. I originally filed this with cibuildwheel (https://github.com/pypa/cibuildwheel/issues/1118), but further investigation shows this is a problem outside of cibuildwheel.

I modified our GitHub Action to only install on Windows, and [it fails to build as well](https://github.com/QuLogic/matplotlib/actions/runs/2393780852). From bisecting cibuildwheel, I know that this came about from setuptools 60, which has the change:

> [#2896](https://github.com/pypa/setuptools/issues/2896): Setuptools once again makes its local copy of distutils the default. To override, set `SETUPTOOLS_USE_DISTUTILS=stdlib`.

Setting the override variable does fix the build, but I don't think that should be our preferred option.

I think this comes about from our hacky attempt to find a compiler search path:
https://github.com/matplotlib/matplotlib/blob/6296e500cfbf6c5a9247a016a059505b9330bc9f/setupext.py#L528-L548
https://github.com/matplotlib/matplotlib/blob/6296e500cfbf6c5a9247a016a059505b9330bc9f/setupext.py#L693-L705
but I don't know what we can do to fix it.

**Comment by QuLogic** [comment]
cc @anntzer if you have any ideas

**Comment by QuLogic** [comment]
I tried a [partial revert](https://github.com/QuLogic/matplotlib/commit/78f810b5d36e0d8ad0b71678c216f237c8bb9da9), but that [didn't seem to work](https://github.com/QuLogic/matplotlib/runs/6618773175?check_suite_focus=true).

**Comment by anntzer** [comment]
I think(?) you basically need https://github.com/matplotlib/mplcairo/commit/2991c725cd36b14a63f6353262e9a689b44769cd, which is a consequence of https://github.com/pypa/distutils/pull/6.
Previously, MSVCCompiler would run spawn after locally monkeypatching os.environ["PATH"], which both 1) changed the PATH seen by the subprocess, but also, and first, 2) changed the search path for the executable spawned by the subprocess.  After the distutils patch above, PATH is instead passed to `subprocess.Popen(..., env=...)`, which on Windows only affects 1) but not 2) (see warning at https://docs.python.org/3/library/subprocess.html#subprocess.Popen).

The hack I wrote for mplcairo (which I wrote before fully understanding the issue here...) was to use cc.spawn to run a python subprocess, which has PATH correctly set and can thus locate the full paths of the needed executables; perhaps slightly simpler would be to spawn `python -c "import os, sys; print(repr(os.environ["PATH"]))"`, ast.literal_eval that and in the parent process use `shutil.which(..., path=...)` to locate the full path to msbuild.exe.

It would also be nice if this could be reported (perhaps with a fix) to upstream (as that's really a change in behavior), if you have the bandwidth for that.
