### ISSUE TITLE
[ENH]: Rotation statistics graph

### ISSUE THREAD

**Issue by klosteraner** [matplotlib/matplotlib#23320]
### Problem

I would like a graph to intuitively read statistics on rotations (e.g. for camera pose estimation in computer vision).
There is a very useful, but simple graph I found in some papers, but I could not find it 1:1 in the examples and reproducing it in matplotlib required some in-depth skills to combine ideas.
The graph is mainly a 2D ellipse scatter plot, where the center corresponds to the mean of my data and the ellipse dimensions to its standard deviation. Those 2 dimensions can e.g. be intuitively used for camera pan/yaw and tilt/pitch. Optionally a 3rd dimension (rotation around viewing direction / roll) could be represented by a wedge looking in the mean direction and shape again representing its standard deviation. It could look like this when used in a comparison:
![Screenshot at 2022-06-22 09-32-59](https://user-images.githubusercontent.com/5983620/174971163-17aac495-8a99-4405-902e-5b89389ebba1.png)

### Proposed solution

Maybe others computer vision devs would benefit from example code, 
I would find it great if there would be a class/function that wraps the logic in an easy interface ( in particular get the label legend logic right while using individual ellipses)

**Comment by jklymak** [comment]
@klosteraner This sounds _very_ specialized, and ripe for a third-party, package rather than something we would entertain in core.  See https://github.com/matplotlib/matplotlib-extension-cookiecutter for a package template and https://github.com/matplotlib/mpl-third-party for a place to submit a package.  If you want help creating such a visualization, please see https://discourse.matplotlib.org  I'm going to close this here, as I am pretty certain this is out of our scope, but thanks for your interest in improving Matplotlib!

**Comment by klosteraner** [comment]
While my use case may be very specialized, I guess a ellipse scatterplot for 2D statistics can prove very useful in many areas.

Thanks for looking into the proposal!

**Comment by tacaswell** [comment]
I think you can also directly create an `EllipseCollection`  https://matplotlib.org/stable/api/collections_api.html#matplotlib.collections.EllipseCollection which takes an array of angles as an input instead of using the lines (
See https://matplotlib.org/stable/gallery/lines_bars_and_markers/multicolored_line.html as an example).

I agree with @jklymak , much of the complexity here is not in Matplotlib pre-say, but in how to map however your data is structured to Matplotlib's view of the world which makes it well suited for a third-party package that is tuned to the data structures you expect in your field!
