### ISSUE TITLE
[MNT]: 

### ISSUE THREAD

**Issue by galonpy** [matplotlib/matplotlib#23410]
### Summary

I won’t see any line overlay of the normal distribution on a histogram because earlier when i constructed the histogram density was not set to True — it would be clever if an error message was printed in this exact scenario ie: “density not set to true in histogram”, rather than having plt.plot(x, p, 'k', linewidth=2) run and do nothing silently. I lost 90 minutes searching for a reason why it wasn't plotting anything.

### Proposed fix

#Here I show a simple example that I googled, with a small change to reflect the lack of density=True so you can see 
#the exact kind of situation where this occurs and use it as a unit test. The fix should probably cause plt.plot(x, p, 'k', linewidth=2) to throw an error because it does nothing specifically because density=True is not earlier.

import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt
  
data = np.random.normal(170, 10, 250)
  
# Fit a normal distribution to the data mean and standard deviation
mu, std = norm.fit(data) 
  
# Plot the histogram.
#plt.hist(data, bins=25, density=True, alpha=0.6, color='b')
plt.hist(data, bins=25, alpha=0.6, color='b') #here we see what caused several lines of PDF code below to do nothing
 
# Plot the PDF.
xmin, xmax = plt.xlim()
x = np.linspace(xmin, xmax, 100)
p = norm.pdf(x, mu, std)
  
plt.plot(x, p, 'k', linewidth=2)
title = "Fit Values: {:.2f} and {:.2f}".format(mu, std)
plt.title(title)

**Comment by jklymak** [comment]
Unfortunately, we have no way to know what the user is trying to plot, either in the histogram, or the subsequent call to `plot`, so its really not possible for us to infer that you will not get what you expect and issue a warning that wouldn't _also_ annoy everyone who was trying to do something purposefully.  

It is unfortunate that there are different ways to interpret `hist`, as it is a perennial source of confusion.  We have made substantial efforts over the years to improve the documentation.  However, the default is not going to change, and we are not going to issue a warning if folks use the default.  I'm going to close because I do not feel there is an actionable way forward for Matplotlib.
