### ISSUE TITLE
[Bug]: Horizontal colorbars drawn incorrectly with hatches

### ISSUE THREAD

**Issue by hCraker** [matplotlib/matplotlib#23456]
### Bug summary

When specifying hatches for `contourf,` the colorbar is drawn correctly for vertical colorbars but not for horizontal ones. The Hatches and colorfill only fill the lower diagonal of the colorbar boxes.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

import matplotlib.pyplot as plt
import numpy as np

# invent some numbers, turning the x and y arrays into simple
# 2d arrays, which make combining them together easier.
x = np.linspace(-3, 5, 150).reshape(1, -1)
y = np.linspace(-3, 5, 120).reshape(-1, 1)
z = np.cos(x) + np.sin(y)

# we no longer need x and y to be 2 dimensional, so flatten them.
x, y = x.flatten(), y.flatten()

fig1, ax1 = plt.subplots()
cs = ax1.contourf(x, y, z, hatches=['-', '/', '\\', '//'],
                  cmap='gray', extend='both', alpha=0.5)

fig1.colorbar(cs, orientation='horizontal')
plt.show()
```

### Actual outcome

![actual_colobar](https://user-images.githubusercontent.com/42781301/180038311-1100fca9-bbaa-4baa-93fb-97ccc56d8260.png)

### Expected outcome

![expected_colorbar](https://user-images.githubusercontent.com/42781301/180038758-eb0177ff-52c8-49cf-9fd4-d927fc4170b6.png)

### Additional information

The bug occurs when the colorbar is horizontal and the `contourf` call uses hatches. Changing the kwargs `extend`, `cmap`, `colors`, `alpha`, etc when calling `contourf` does *not* resolve the bug. 

The bug does *not* occur when the colorbar is vertical with hatches nor when the colorbar is horizontal and no hatches are used.

*Potential Solution*:
In colorbar.py, change line 637 to the following:
`xy = np.array([[X[i, 0], Y[i, 1]],`

This doesn't cause issues when hatches are not used. It also doesn't cause problems with vertical colorbars.

### Operating system

macOS Big Sur Version 11.3.1 with Intel Silicon

### Matplotlib Version

3.5.2

### Matplotlib Backend

module://backend_interagg

### Python version

3.10.5

### Installation

conda

**Comment by jklymak** [comment]
Did this work before and we broke it, or did it never work?  There were some changes to colorbars, but I'm not sure why they would cause this to happen.  Thanks.

**Comment by hCraker** [comment]
I'm not sure but I can try running my code using older versions of matplotlib. What version do you think might be the culprit?

**Comment by jklymak** [comment]
Try 3.4.2.  But if you don't know if this ever worked it probably never did.  My guess would be there is a typo in the code that makes the hatch.  Maybe east to fix if you grep hatch in the colorbar.py

**Comment by oscargus** [comment]
I was about to implement this, but I found another issue as well. A slightly different setting gave this (after the patch above was introduced):

![image](https://user-images.githubusercontent.com/8114497/185750413-9087c107-8f6e-4c6d-ac70-3e2b5765d7e2.png)

Clearly the colors and hatches are off by one.

That seems to be a problem for vertical as well (and maybe easier to see there):
![image](https://user-images.githubusercontent.com/8114497/185750519-c54d8b96-4d69-45ef-8b2c-f21220122e44.png)

The same thing can be seen in the original picture although not as obvious there. Rather, there are eight different levels in both the contour and the colorbar, but the left extended level in the colorbar is not matching the darkest in the contour. However, of the three lightest/right-most three levels in the contour, only two of them are in the colorbar.

Not sure if it is worthwhile doing a patch to get the rectangle correct as it probably doesn't make sense to add a test image since the colorbar in itself doesn't match the contour-levels.

**Comment by oscargus** [comment]
The problem is related to `extend`. Without it, it is all good.

**Comment by oscargus** [comment]
So, `_add_solids_patches` duplicates the hatches:
https://github.com/matplotlib/matplotlib/blob/9b1fcf67c4228c4a2788af5bcaf0c6fde09a55bf/lib/matplotlib/colorbar.py#L610
and then picks one as a time starting from 0: 
https://github.com/matplotlib/matplotlib/blob/9b1fcf67c4228c4a2788af5bcaf0c6fde09a55bf/lib/matplotlib/colorbar.py#L619

The extend patches picks the first and last hatch pattern of the original list:
https://github.com/matplotlib/matplotlib/blob/9b1fcf67c4228c4a2788af5bcaf0c6fde09a55bf/lib/matplotlib/colorbar.py#L685

https://github.com/matplotlib/matplotlib/blob/9b1fcf67c4228c4a2788af5bcaf0c6fde09a55bf/lib/matplotlib/colorbar.py#L706
