### ISSUE TITLE
small change suggestion

### ISSUE THREAD

**Issue by Gatilsom** [matplotlib/matplotlib#23484]
https://github.com/matplotlib/matplotlib/blob/f3593aed059b0caad44a1a536e340ab18ba026b7/lib/matplotlib/backends/_backend_tk.py#L607

-> `self.label = tk.Label(master=self, font=self._label_font,`

![sugestao_matplotlib](https://user-images.githubusercontent.com/107775815/180626976-9d0c69db-8a14-490d-b3af-d5d5ed5cb35d.png)

**Comment by QuLogic** [comment]
None of that code in the screenshot is in Matplotlib, so I don't know what you are suggesting.

**Comment by anntzer** [comment]
I think this is asking to get a (public) handle to the spacer label widget so that they can configure its background to black, to match the rest of their custom styling.
I'd rather not provide such handles because I'd consider these widgets to be private implementation details.  It would be nice if there was a way to configure tk widgets to be fully transparent/zero-width, though a quick look didn't give anything.  However, you can still iterate over all children of the toolbar with e.g. `for c in toolbar.children.values(): c.configure(bg="black")` (actually it needs to be a bit more complex as you want to exclude buttons from the iteration, but you get the idea.
I'd suggest to close this as "not planned".

**Comment by tacaswell** [comment]
I agree with @anntzer (assuming that is the correct interpretation of the of the request).  On the other hand, it does take look like it would be easy for a down-stream library to re-implement the toolbar in a way that does give them full control.

However, given that in this case the OP is already doing a full tk embedding, iterating through the children seems like a reasonable path forward.

@Gatilsom Please ping to have this re-opened if we have misunderstood the issue!
