### ISSUE TITLE
[Bug]: svg backend does not use configured generic family lists

### ISSUE THREAD

**Issue by l-johnston** [matplotlib/matplotlib#23492]
### Bug summary

The FontProperties family parameter can be a generic family such as sans-serif and the actual font should be looked up in rcParams according to the documentation.

### Code for reproduction

```python
>>> import matplotlib as mpl
>>> import matplotlib.font_manager as fm
>>> mpl.rcParams["font.family"]
['sans-serif']
>>> mpl.rcParams["font.sans-serif"]
['DejaVu Sans',
 'Bitstream Vera Sans',
 'Computer Modern Sans Serif',
 'Lucida Grande',
 'Verdana',
 'Geneva',
 'Lucid',
 'Arial',
 'Helvetica',
 'Avant Garde',
 'sans-serif']
>>> fp = fm.FontProperties()
<matplotlib.font_manager.FontProperties at ...>
>>> fp.get_family()
['sans-serif']
```

### Actual outcome

```python
>>> fp.get_family()
['sans-serif']
```

### Expected outcome

```python
>>> fp.get_family()
['DejaVu Sans',
 'Bitstream Vera Sans',
 'Computer Modern Sans Serif',
 'Lucida Grande',
 'Verdana',
 'Geneva',
 'Lucid',
 'Arial',
 'Helvetica',
 'Avant Garde',
 'sans-serif']
```

### Operating system

Windows

### Matplotlib Version

3.5.2

### Matplotlib Backend

TkAgg

### Python version

3.9.13

### Jupyter version

N/A

### Installation

pip

**Comment by jklymak** [comment]
On the face of it, the result looks correct to me, so it seems the documentation is out of date?  https://matplotlib.org/stable/api/font_manager_api.html#matplotlib.font_manager.FontProperties.get_family

**Comment by l-johnston** [comment]
Why is the result correct? Where, other than the documentation is the public API specified? If it's just documentation that is out of date, then the [FontProperties docstring](https://matplotlib.org/stable/api/font_manager_api.html#matplotlib.font_manager.FontProperties.get_family:~:text=family%3A%20A%20list%20of%20font%20names%20in%20decreasing%20order%20of%20priority.%20The%20items%20may%20include%20a%20generic%20font%20family%20name%2C%20either%20%27sans%2Dserif%27%20(default)%2C%20%27serif%27%2C%20%27cursive%27%2C%20%27fantasy%27%2C%20or%20%27monospace%27.%20In%20that%20case%2C%20the%20actual%20font%20to%20be%20used%20will%20be%20looked%20up%20from%20the%20associated%20rcParam.) needs updating also.

**Comment by l-johnston** [comment]
but according to the docstring, get_family():
_Return a list of font names that comprise the font family._

meaning get all the family members, as opposed to simply the family name.

**Comment by story645** [comment]
> meaning get all the family members, as opposed to simply the family name

this seems more useful - do you have a guess of how hard it'd be to implement?

**Comment by l-johnston** [comment]
[here's another place in the documentation stating that a generic family name maps to a set of actual fonts](https://matplotlib.org/stable/tutorials/text/text_props.html?highlight=font#:~:text=If%20any%20of%20generic%20family%20names%20appear%20in%20%27font.family%27%2C%20we%20replace%20that%20entry%20by%20all%20the%20entries%20in%20the%20corresponding%20rcParam%20mapping.%20For%20example%3A)

**Comment by jklymak** [comment]
Yes, I appreciate what the docs say.   However, our usual pattern for setter/getters is for them to be reversible, so it would be unusual for `get_family` to return something other than what `set_family` was given.

**Comment by jklymak** [comment]
If this ever behaved differently, it was more than 8 years ago according to git blame.  I'll stand by my assertion that this is a documentation error.

**Comment by l-johnston** [comment]
For a documentation error, this is massive wide scale errors where all the errors are consistent. [set_family() accepts a list of real fonts](https://matplotlib.org/stable/api/font_manager_api.html#:~:text=set_family(family,is%20True.).

**Comment by story645** [comment]
>set_family() accepts a list of real fonts
 
that sounds like this is a bug in Matplotlib where the intended behavior is what's stated in the docs and somehow didn't get implemented or reverted. thanks for catching that

**Comment by l-johnston** [comment]
workaround is to set rcParams["font.family"] = <list of real fonts>

**Comment by tacaswell** [comment]
To start with, I want to note that fonts are confusing.  I do not think there are any major bugs or documentation errors here, however the documentation is ambiguous and should be clearer.

-----

First `FontProperties` are not actually fonts, they are the input to https://github.com/matplotlib/matplotlib/blob/cd66bfd3503830fc854d395968a92e9467c1c091/lib/matplotlib/font_manager.py#L1290-L1291 (which is a wrapper around `_findfont_cached` defined right below) that takes in the `props` and gives back the file path of the closest font to the one requested.  Internally we will eventually open what ever file that is and use it to render the text.

Because the "family" on the `FontProperties` is a list (rather than a single name) this means you can list several fonts in preference order and we will use the first one that is actually installed.   This behavior dates back to 2007-2008 and is consistent with css https://developer.mozilla.org/en-US/docs/Web/CSS/font-family .  The ambiguity of using "family" to refer to the list, the things in the list, and the generic things seems to be an ambiguity that we inherited.  I think the docstring on `get_family` should be clearer on which "family" it is referring too.

The other question is when do we resolve the generic font families ("sans", "serif", ...).   @l-johnston has the expectation that we resolve it eagerly when the family is set on the `FontProperties`, however we actually do it lazily when we are actually looking the font up at https://github.com/matplotlib/matplotlib/blob/cd66bfd3503830fc854d395968a92e9467c1c091/lib/matplotlib/font_manager.py#L1191-L1192 .  I think either behavior is defendable, however we have been doing it late from 2008.  

On net, I think doing it late is a preferable.  If the rcparam for the generic families changes between when the `FontProperties` object is created and when the Figure is saved it is ambiguous which state should be used.  "do what it says at draw time" seems easier to understand as if we resolved it early you could have N `FontProperties` than were created identically (but would at least not be equal) that all render differently!

If we did go to eager evaluation, I would not expect the generic family to survive in the list.

----

We do some light normalization in `set_family` to ensure that we always get a list back from `get_family` which wile it does not round trip, I think is reasonable behavior.

**Comment by l-johnston** [comment]
@tacaswell  the original error occurred when saving a figure as SVG file format with the following rcParams:

- svg.fonttype: none
- font.family: sans-serif
- font.sans-serif: [Source Sans Pro]

The resulting file has the font as 'sans-serif' instead of the expected 'Source Sans Pro'. What is the correct usage pattern to achieve the lookup?

**Comment by tacaswell** [comment]
That you are targeting SVG in this way is an important detail!  In this case we are letting the down-stream renderer actually do the font rendering.  I now understand why you want to keep the generic font family in the list rather than fully replace it as we do inside of `findfont`.    

For now, your workaround is the best we can do.  The bug fix is to adjust

https://github.com/matplotlib/matplotlib/blob/931a81f532ecf896cf9b78802d46f9d1f00bb167/lib/matplotlib/backends/backend_svg.py#L1131-L1134

to insert the rcParam specified preference list ahead of the generic names.  I think that this is going to change behavior a little bit (if you used to be happy with the renderer's generic fallback we might be putting other fonts ahead), but it is still the right thing to do. 

I think the steps here are:

 - adjust the line noted above with an analogy with what we do in `findfont`
 - add a test that we do indeed insert the fallback fonts
 - add a API change note in "behavior change"
 - bonus: check if we need a similar change to the other vector formats

**Comment by tacaswell** [comment]
I labeled this as a good first issue because it is a very isolated change, but medium difficulty because it involves fonts, it is a behavior change that while I think is non-controversial may require discussion, and is deep in a backend.  Who ever takes this should not be new-to-Python.

**Comment by tacaswell** [comment]
I also updated the issue title to reflect what I think the underlying bug is.

**Comment by tacaswell** [comment]
I now understand fonts and vector formats better than I did 2 weeks ago.  Per my bullet list:

 - more-or-less, but it had more complexity than I expected due to the quoting requirements
 - still need a test
 - I am now fully convinced that this is a bug not a behavior change.  I could be talked into needing an API change not, but I would not advocated for it
 - no, this only affects SVG.  The PDF/PS will either embed the fonts they need in the file (like path mode in the SVG backend) or rely on the "core fonts" which are assumed to be there so no generic families need apply
