### ISSUE TITLE
[ENH]: Suppress duplicate labels in legend

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#23664]
### Problem

As discussed in #23525, the legend treats every label as distinct and will therefore display them even when visually indistinguishable. 
![image](https://user-images.githubusercontent.com/1300499/185444858-4a539a36-7376-46ba-81be-6270ac235eca.png)
 

### Proposed solution

@timhoffm raised the good point that we don't want to break the artist-(label, handle) link in case the artist gets updated, so I think an alternative solution is maybe to have this logic in the legend. Something like a `duplicate` keyword argument to legend:

* ```duplicate=True```, default, current behavior
* ```duplicate=False``` - triggers a check of legend objects. If multiple legend handles have the same properties (class, color/edgecolor, hatch, size/width/edgewidth, etc) and the same label, then a new handle with those properties linked to all the artists is shown in place of the original handles. 

I'm not sure if this is even doable in the current architecture, but if possible this would be designed so that updates to properties that update handles/legends propagate back to create new entries on the legend as needed. The advantage of this approach is that it would facilitate explicitly linking legend labels & handles to multiple artists. 

I think currently duplicates are eliminated manually either by omitting the labels on some artists or creating a custom legend handle. Neither approach preserves a link between a legend entry and all the artists it is intended to describe.

**Comment by jklymak** [comment]
Can you repeat the code that would cause the above?  A legend is really only useful if there is information that can't be keyed some other way - so orange and blue bars each representing different distributions would each get one legend entry.  I don't understand why this example would get a legend at all, and hence am skeptical that we need new API to deal with it.

**Comment by story645** [comment]
That example is from the feature in #23525, but is also the default behavior. I think it'd be useful for some sort of meta grouping:

```python
fig, ax = plt.subplots()

x = ['JFK', 'LGA', 'Central Park']
y = [2, 1, 3]
l = ['airport', 'airport', 'park']
c = ['tab:orange', 'tab:orange', 'tab:blue']

for xi, yi, li, ci in zip(x,y,l,c):
  ax.bar(xi, yi, label=li, color=ci)

ax.legend();
```
![image](https://user-images.githubusercontent.com/1300499/185458698-5538e6bd-ec5c-4194-aaee-70b4f61420a8.png)

A more real world example of irregular group membership is plotting attributes of individual data points and then coloring by cluster membership as a way to see the variability of that feature in each group.

**Comment by jklymak** [comment]
I can see that, but its sophisticated enough I'd just ask people to save the handles they want in the legend and pass those to legend, rather than trying to devise an API and heuristic and do something magical:

```python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()

x = ['JFK', 'LGA', 'Central Park']
y = [2, 1, 3]
l = ['airport', 'airport', 'park']
c = ['tab:orange', 'tab:orange', 'tab:blue']

handles = []
colors = []
labels = []

for xi, yi, li, ci in zip(x,y,l,c):
    hl = ax.bar(xi, yi, label=li, color=ci)
    if not ((ci in colors) and (li in labels)):
        handles += [hl]
        colors += [ci]
        labels += [li]
ax.legend(handles=handles)
```

**Comment by jklymak** [comment]
.. and just to clarify the above; I think there are lots of other bar properties we would have to check (hatching, edgecolor, edge linestyle) to make sure bars aren't actually different.

**Comment by tacaswell** [comment]
I am very :-1: on implementing any de-duplicating logic in `ax.legend()` / `fig.legend()`.

In addition to the concerns Jody and Tim have, we use this same API when users explicitly pass us handles and/on labels.   In those cases we should do exactly what the user asked us to do (leaving any filtering to them) and having a kwarg that only has an effect sometimes is a major anti-pattern. 


-----

A variation on what @timhoffm suggested an as alternative should skip the label but be a bit more readable:

```python
fig, ax = plt.subplots()

x = ['JFK', 'LGA', 'Central Park']
y = [2, 1, 3]
l = ['airport', '_airport', 'park']
c = ['tab:orange', 'tab:orange', 'tab:blue']

for xi, yi, li, ci in zip(x,y,l,c):
  ax.bar(xi, yi, label=li, color=ci)

ax.legend();
```


-----

If the consensus is to do this, the keyword should be something like `filter_duplicates=False` and you which you set to `True` to opt-into the behavior.   Having keywords that have a negation in their name and than you need to set to False (double negation!) to get the behavior are more confusing than keywords which do not have "built in" negation and you set to True to get the behavior.

**Comment by story645** [comment]
>we should do exactly what the user asked us to do 
It'd be opt in de-duplication, so the user would be explicitly asking us to handle the filtering. Yes we would be implementing the deduplication algorithm, but as that would be documented I don't see how that's any more or less magic than for example the layout algorithms. 

I don't mind tabling the dedup discussion for now, but the [stack overflow question](https://stackoverflow.com/questions/19385639/duplicate-items-in-legend-in-matplotlib) has 47K views b/c this is not uncommon. 

That being said, I still think there are use cases for being able to explicitly associate multiple artists with one (label, handle) pair. I think one of the reasons @timhoffm rejected deduplication in the other PR was that it would break the (artist, label, handle) association, but we're in effect forcing users to break that association so that they do not have repeated entries.  One place where I think it would be really useful to associate multiple artists to the same (label, handle) is a modification of https://matplotlib.org/stable/gallery/event_handling/legend_picking.html where multiple lines are the same color and therefore inferred to belong to the same legend.

**Comment by tacaswell** [comment]
The consensus is against implementing the feature as described and it is tabled so I am going to close this issue.

------

In order to know to correctly do the layout you need to know things that are only knowable at draw time (the actually rendered size of text).  There is no way for the user, from the outside, to get the correct (fractional) size of the Axes so we have to do it.   On the other hand, knowing which artists should be grouped together as "the same" is something that the user (should) know and (absent an explicit API to tell us) we can only infer from heuristics.   I do not think the two cases are really comparable.

----

In  https://matplotlib.org/stable/gallery/event_handling/legend_picking.html  the mapping between the artist in the legend and the actual artist is set up by

```python
lines = [line1, line2]
lined = {}  # Will map legend lines to original lines.
for legline, origline in zip(leg.get_lines(), lines):
    legline.set_picker(True)  # Enable picking on the legend line.
    lined[legline] = origline
```
and is stored in user code not by Matplotlib (in fact I do not think we keep such a mapping, I spent a while looking and could not find it).  Tracking more than one line per legend element would be a small change to store a list as the value in `lined` rather than a single `Artist`.

-----

There is already a way to group multiple artists together, but is it more in the spirit of composition (see the second and third examples in https://matplotlib.org/stable/tutorials/intermediate/legend_guide.html#legend-handlers) and a document way to create proxy artists (https://matplotlib.org/stable/tutorials/intermediate/legend_guide.html#creating-artists-specifically-for-adding-to-the-legend-aka-proxy-artists) which is most useful for these cases where you have many more  artists on the Axes than you want to have in the legend.

**Comment by timhoffm** [comment]
> I still think there are use cases for being able to explicitly associate multiple artists with one (label, handle) pair.

I agree with that. Such a concept is desirable. However, getting this right is a major effort and OTOH the use cases are relatively niche and can also be achieved with more or less manual tweaking (all needed API is there so that a user could even implement this feature).
Looking at the trade off gain vs. effort, I think not following up in this for now is the correct choice.
