### ISSUE TITLE
[Bug]: contourf with alpha adds level lines

### ISSUE THREAD

**Issue by AlDanial** [matplotlib/matplotlib#23691]
### Bug summary

``contourf()`` by default does not draw borders between adjacent levels.  However, including the ``alpha`` keyword argument makes these borders visible.  Desired behavior is to not draw these lines even with ``alpha`` specified.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
x = np.linspace(-3, 5, 150).reshape(1, -1)
y = np.linspace(-3, 5, 120).reshape(-1, 1)
z = np.cos(x) + np.sin(y)
x, y = x.flatten(), y.flatten()
fig, ax = plt.subplots(nrows=2,ncols=1)
ax[0].set_title('Actual outcome')
ax[0].contourf(x, y, z, levels=15, vmin=0.5, vmax=1.0, cmap='cividis', alpha=0.9)
ax[1].set_title('Expected outcome')
ax[1].contourf(x, y, z, levels=15, vmin=0.5, vmax=1.0, cmap='cividis')
plt.show()
```

### Actual outcome

![actual](https://user-images.githubusercontent.com/1459933/185768358-a54285fc-8e9a-4d84-a1f3-d962888d31e2.png)

### Expected outcome

![expected](https://user-images.githubusercontent.com/1459933/185768363-521351d6-ecb4-4745-aee6-7d1afc06a94a.png)

### Operating system

Ubuntu 20.04

### Matplotlib Version

3.5.1

### Matplotlib Backend

QtAgg

### Python version

3.8.8

### Installation

conda

**Comment by tacaswell** [comment]
I am almost certain that the issue here is the patches used to draw the regions overlap by a pixel or so.  When the alpha is 1 the top layer is all that is visible, however if the alpha is less than 1 the overlaps show up as darker.   You can try setting `lw=0` to not stroke the edge of the patches, but that may lead to a worse situation of gaps between patches (not on a machine set up for dev right now so can not test).

**Comment by AlDanial** [comment]
Thanks for the quick response.  Sure, I tried the linewidth setting before submitting this issue--suppose I should have mentioned that under 'Additional information'.  Needless to say ``lw=0`` and ``lw=None`` have no effect, neither does ``linestyles=None``.
