### ISSUE TITLE
[Bug]: plt.figure(), plt.close() leaks memory

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#23701]
### Bug summary

MWE:

```python
import matplotlib.pyplot as plt

while True:
    plt.figure()
    plt.close()
```

Either run this code and monitor the mem consumption on top, or run
```
mprof run test.py
mprof plot
```
(with [memory-profiler](https://pypi.org/project/memory-profiler/)) to get

![screenshot](https://user-images.githubusercontent.com/181628/185868564-01a9752a-7535-4580-8e8e-5bd33c2bfab6.png)

Might be related to https://github.com/matplotlib/matplotlib/issues/22448.

### Operating system

Ubuntu 22.10

### Matplotlib Version

3.5.3

### Matplotlib Backend

GTK4Agg

### Python version

3.10.6

### Installation

pip

**Comment by nschloe** [comment]
The following is with

```python
matplotlib.use('GTK3Agg')
```

![screenshot](https://user-images.githubusercontent.com/181628/185873206-2870d105-ab5a-44d0-9618-8265c89f09c0.png)

**Comment by timhoffm** [comment]
Have you tried other backends? Is this GTK specific? Interesting would be "qtagg", "Tkagg", "agg" and "gtk4cairo".

**Comment by tacaswell** [comment]
The issue is that you are never letting the GUI event loop run so there are a growing number of GUI windows just hanging out in the background waiting for the event loop to run so they can finish their tear down cycle (because most UI frameworks have a way  to notify that things are being destroyed etc).

If you need to run tight loops like this either use a non-interactive backend (like `'agg'` or `'svg'`) which will never create the GUI objects or call `plt.pause(.1)` every so often to let the GUI clean up.

**Comment by nschloe** [comment]
I've tried the suggestion. Outcome: All backends have the problem, but `'agg'` and `'svg'` run a lot faster than the rest. When adding `plt.pause(1.0)` (a full second), no clean-up appears to happen. This is with `'agg'`; observe the plateaus:

![agg-pause-1-0](https://user-images.githubusercontent.com/181628/185995066-441b6652-3cac-457d-8e2e-83f6b333c901.png)

Code:

```python
import matplotlib
import matplotlib.pyplot as plt

matplotlib.use("GTK4Agg")

# [
#     "GTK3Agg",
#     "GTK3Cairo",
#     "GTK4Agg",
#     "GTK4Cairo",
#     "MacOSX",  # x
#     "nbAgg",  # x
#     "QtAgg",
#     "QtCairo",
#     "Qt5Agg",
#     "Qt5Cairo",
#     "TkAgg",
#     "TkCairo",
#     "WebAgg",
#     "WX",
#     "WXAgg",
#     "WXCairo",
#     "agg",
#     "cairo",
#     "pdf",
#     "pgf",
#     "ps",
#     "svg",
#     "template",
# ]

for k in range(4000):  # higher numbers for agg, svg
    plt.figure()
    plt.close()
    if k % 1000 == 0:
        plt.pause(1.0)
```

**Comment by tacaswell** [comment]
Can you please try adding `gc.collect()` (to clean up an reference cycles) and put the pause before the close (some of the backends do not actually run the event loop if the all of the managers are gone).

Can you also try with https://github.com/matplotlib/matplotlib/blob/main/tools/memleak.py on your system?


```python
import gc
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.use('agg')

while True:
    plt.figure()
    plt.close()
    gc.collect()
```

This stays under 90MB for me (where as with out the `gc.collect()` it did indeed start to run away).

**Comment by tacaswell** [comment]
```python
import matplotlib.figure as mfigure


while True:
    mfigure.Figure()

```

Also seems to work so likely something in the `Manager` class

**Comment by nschloe** [comment]
- agg without gc (100k iterations):
 
  ![agg](https://user-images.githubusercontent.com/181628/186019619-3c391e36-3655-4dd0-9095-0a62b91acfbb.png)

- agg with gc (100k iterations, gc after every 1000 its):
  
  ![agg-gc](https://user-images.githubusercontent.com/181628/186019666-b033f06f-e543-412a-8a41-53153926a5f4.png)

**Comment by nschloe** [comment]
```
python3 memleak.py agg 100 out.pdf
```

![screenshot](https://user-images.githubusercontent.com/181628/186020210-52e4d0d4-9563-48bd-bf6a-fc352df737c7.png)

**Comment by nschloe** [comment]
> `mfigure` Also seems to work so likely something in the Manager class

Indeed:

```python
import gc
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.figure as mfigure

mpl.use('agg')

for k in range(100000):
    mfigure.Figure()
    plt.close()
```

gives

![screenshot](https://user-images.githubusercontent.com/181628/186020608-e8ebb95f-4c9e-4176-8d1d-3dcf72713e9b.png)

-- no explicit gc.

**Comment by tacaswell** [comment]
That long delay at the end is probably GC finally running on the way out 

`plt.close()` is no effect in that second example because the `Figure` was never registered with 

-----

I understand the problem, TL;DR either use manual `gc.collect()` or set `gc.set_threshold(100)` because we internally use `gc.collect(1)` which breaks CPyhons garbage collection (I'll be opening up a PR soon).

1. https://devguide.python.org/internals/garbage-collector/index.html is the best write of the GC out there
2. a details that is not included is that the logic to sort out which generation to run is _only_ run if the threshold for the lowest generation is met ([cpython source](https://github.com/python/cpython/blob/129998bd7b133defa37c7529bfad9052c0022b5c/Modules/gcmodule.c#L2266))
3. we have a `gc.collect(1)` in https://github.com/matplotlib/matplotlib/blob/5773bf9a5ce11b7ba0c9bc1d6693ad99a39426cb/lib/matplotlib/_pylab_helpers.py#L69-L72 which is sweeping out lower generations
4. if we do not have a code path between the `plt.close()` that does not make 700 objects then we never pass that first test and CPython never tries to run its "what generation to run?" logic ([cpython source](https://github.com/python/cpython/blob/129998bd7b133defa37c7529bfad9052c0022b5c/Modules/gcmodule.c#L1409-L1463)) and we have this run-away "leak"

-----

You can reproduce this issue with:

```python
import gc
import matplotlib.figure as mfigure


print("about to start")
for j in range(100_000):
    fig = mfigure.Figure()
    gc.collect(1)
    print(gc.get_count())

```

A way to "fix" this is

```python
from itertools import count
import gc
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.use('agg')


class MyObject:
    ...
    
gc.collect()
print("about to start")
for j in range(100):
    print(gc.get_count())
    plt.figure()
    print(gc.get_count())
    plt.close()
    print(gc.get_count())
    c = [MyObject() for j in range(700)]

```

which will force enough generation 0 objects to be created that it will cause a full gc eventually.
