### ISSUE TITLE
[Bug]: get_xlim() not returning correct figure limits

### ISSUE THREAD

**Issue by abhijeet-pandey** [matplotlib/matplotlib#23743]
Wrote the following matplotlib based class to pan-right the figure using right arrow key. However, if I use the same class after zooming into the figure it does not produce the desired panning of the figure. I have figured out the root cause to be the get_xlim() function not returning the current or updated xlim of the figure. The right arrow key press event shows how get_xlim() seems to revert back to the old xlim values.
The issue remains even if I update the class variable- NavFigure.fig by a instance variable.

```
import numpy as np
import matplotlib.pyplot as plt 

class NavFigure:
    ax_tmp = plt.gca()
    fig = plt.gcf()    

    def __init__(self):
        NavFigure.fig.canvas.mpl_connect('key_press_event', self.pan_nav)    

    def pan_nav(self, event):    
        if event.key == 'right':
            print("initial limits:", NavFigure.ax_tmp.get_xlim())
            lims = NavFigure.ax_tmp.get_xlim()
            adjust = (lims[1] - lims[0]) * 0.9            
            NavFigure.ax_tmp.set_xlim((lims[0] + adjust, lims[1] + adjust))
            plt.draw()
            NavFigure.ax_tmp = plt.gca()
            print("updated limits:", NavFigure.ax_tmp.get_xlim())

plt.plot(np.random.rand(100))   
myfig = NavFigure()
```

**Comment by tacaswell** [comment]
I suspect the problem is either due to getting which Axes you are working on crossed (see the end of this repsonse) or because the standard keybindings are getting in the way.

When you pan/zoom we add the the view to a history stack and then bind the left/right key to back/forward in the stack https://matplotlib.org/stable/users/explain/interactive.html#navigation-keyboard-shortcuts .

Also see: https://stackoverflow.com/questions/35624183/disable-matplotlibs-default-arrow-key-bindings

Can you write a script that will drive the Axes to a state where `get_xlim()` is wrong?  It is very difficult to debug based on a workflow that requires specific interactive steps.

----

I would refactor this code to look something like:

```python
import numpy as np
import matplotlib.pyplot as plt

class NavFigure:

    def __init__(self, ax):
        self.ax = ax
        self.fig = ax.figure
        self.cid_ = self.fig.canvas.mpl_connect('key_press_event', self.pan_nav)

    def pan_nav(self, event):
        if event.key == 'right':
            print("initial limits:", self.ax.get_xlim())
            lims = self.ax.get_xlim()
            adjust = (lims[1] - lims[0]) * 0.9
            self.ax.set_xlim((lims[0] + adjust, lims[1] + adjust))
            self.fig.canvas.draw_idle()
            print("updated limits:", self.ax.get_xlim())

fig, ax = plt.subplots()
ax.plot(np.random.rand(100))
myfig = NavFigure(ax)
plt.show()

```

I strongly suspect that some of your problems are related to the way your are managing the state of which Axes you are working with.  Storing the state on the class means it is effectively global and shared between all instances of the class.  Further, you only attach the callback to the first Figure/Canvas, but if `plt.gca()` later returns an axes in a different Figure the callback will stop working (and change a different figure!).  If you want the callback to only apply when you are in one axes of a Figure you will need to do a bit more book keeping.

**Comment by abhijeet-pandey** [comment]
@tacaswell  - the refactored code suffers from the same issue. If I zoom-into the figure, the pan using right arrow still does not work.

**Comment by tacaswell** [comment]
Did you remove the default keybindings or try with different keys than the arrows?

**Comment by abhijeet-pandey** [comment]
Using a different key binding i.e. other than arrow works. Also, after removing default keybinding using `mpl.rcParams['keymap.forward'].remove('right')` resolved the issue with the right arrow key.
