### ISSUE TITLE
[ENH]: Zoomout Aliasing/Loss of Information

### ISSUE THREAD

**Issue by platise** [matplotlib/matplotlib#23758]
### Problem

On larger data-sets, i.e. from spice outputs, zoom-out (actually the default) view is incorrect due to loss of information when "compressing/reducting" data into a "smaller viewing" area.

For example, the blue signal in zoom out is represented incorrectly:

![ZO](https://user-images.githubusercontent.com/7982797/187024607-d61e07c7-4304-4b4e-9051-4ab919be7300.png)
![ZI](https://user-images.githubusercontent.com/7982797/187024610-ece2f5f5-5f29-45b4-b8ea-67ca6433e23a.png)

One problem is also that signals are overlapping, but this could be possibly improved as follows:

### Proposed solution

Assuming we have an array x = [x0, x1, ... xn] and view area v = [v0, v1, ... vm] for m < n, and assuming k points from v are merged into x. Then one option of compacting the x into v, would be:
- represent a distribution on Y axis of x, with color intensity/alpha/mixing (basically it is a histogram with color intensity representing the value) with overlapping signals,
- or could be simplified to a tuple (vi_max, vi_min, intensity) where max and min represent min(x_i .. x_i+k), max(), and intensity/alpha/mixing is inverse proportional to the spread
- definitely when compacting the signals intensity should change to notify visually that in "that segment" there is some spread, and it would be possible to see "spikes" from large data-sets in zoomed-out images.

In PCB CAD layouting there are some standard practices of "changing colors" of overlapped areas... maybe the same could be used here.

**Comment by timhoffm** [comment]
Thanks for the suggestion!

This is much more complicated than overlapped areas in CAD. The “area” impression is only given because we have a finite pixel resolution and every pixel is hit by a data point/line. So the overlap “area” coloring could only be determined on the rendered pixels. But the canvas is simply a drawing area on which the elements are drawn sequentially. The orange lines are drawn after the blue lines and thus cover them. You would need a fundamentally different architecture to support this.

When you have more data than the resolution, drawing individual data always looses information; e.g. even with the only one data set, you’d get a fully colored area and can’t see the step-like structure anymore (I don’t know your data but if you only have values at ~0.5 and ~5.5 and draw that with lines you’d still get the fully covered area even though you don’t have values in between). It’s usually better to choose a different visualization then. See  for a semi-related example.

One workaround you could do here is to introduce a transparency (e.g. alpha=0.7).

I’m closing this as a we can’t do anything about this.

**Comment by jklymak** [comment]
I think it's possible Matplotlibs screen backends could be a lot smarter about aliasing than they are.   If you save the above as a pdf, what does a pdf renderer show? 

OTOH the difference with a CAD drawing: our lines are specified as a width in page-space.  So a 2-pt line is 2/72 of an inch no matter how much of it is shown. You zoom in on a line, it is 2/72 of an inch.  You zoom out, it's the same.  A CAD program will keep the line width constant with respect to the object it is representing. As you zoom out the line thins, and as you zoom in the line thickens.  As @timhoffm says, that is a completely different model and your second line paints over your first.

**Comment by platise** [comment]
Thank you for prompt replies. Will try with alpha, or to emulate the proposed solution and print it as image, however it would have the same effect as zoom-in/out would not work equally. The histogram would show higher intensities on the top and bottom, so the chart should be much more illustrative.
I like the way Rhode & Schwarz is doing rendering on their scopes, you may catch every single "glitch" of the signal.

**Comment by jklymak** [comment]
As @timhoffm alludes above, you can pre-process your signal as needed and plot in the most appropriate method.   But Matplotlib is too general to do that pre processing for every different type of signal.  As an example, a more natural signal would probably be most appropriately low-passed, but in your case you would almost certainly not want that because you would lose all the peaks at large zoom outs.  If you want a scope like behaviour, I would make two 2d histograms and overlay them with transparency (or one histogram with the two signals as input).  Actually I think there are external packages that already do that.

**Comment by jklymak** [comment]
One final point: using a marker, by changing to `plot(x, y, '.')` makes it a lot clearer where the data populations live.

**Comment by ianthomas23** [comment]
`Datashader` is designed to deal with overplotting situations like this. Currently `Datashader` and `Matplotlib` don't work particularly well together, but developers of both libraries are keen to improve this situation so there should be improvements in the future.
