### ISSUE TITLE
[Bug]: fill_between crosses boundary

### ISSUE THREAD

**Issue by zwei-beiner** [matplotlib/matplotlib#23764]
### Bug summary

The code below fills the space between two curves. When saving the figure as a .pdf (or any other filetype), the filling shows two lines where the boundary would have been. 

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np
fig, ax = plt.subplots()
x = np.linspace(0, 4)
y = x ** 2
y2 = x ** 2.1
ax.fill_between(x, y, y2, alpha=0.25, color='red')
fig.save_fig('plot.pdf')
```

### Actual outcome

When zooming in into the plot, one sees the two darker lines:

<img width="724" alt="vANRL" src="https://user-images.githubusercontent.com/86890234/187081987-350da4a9-7ab2-4114-8e50-8d5995bef057.png">

### Expected outcome

This is the output when I call `plt.show()` instead of `save_fig`, which doesn't show the "color leak".

<img width="385" alt="image" src="https://user-images.githubusercontent.com/86890234/187082107-487ae0c1-82f4-4663-98ef-e9e2cce2e37a.png">

### Additional information

The bug doesn't happen when I remove `color='red'` from the above code.

### Operating system

OS/X

### Matplotlib Version

3.5.2

### Matplotlib Backend

MacOSX

### Python version

Python 3.9.13

### Installation

pip

**Comment by jklymak** [comment]
That is the line overlapping the polygon, and where they overlap the alphas add.   I think this is expected behaviour.  If you don't want the line set `linewidth=0`.  You will also see that you get the same effect with `plt.show` if you set the line width to be thick enough to see (`linewidth=10`).   I'll close here as I think this is working as expected.
