### ISSUE TITLE
[ENH] Interactive Zoom Rectangle Color Review for MACOSX backend

### ISSUE THREAD

**Issue by manu-b-s** [matplotlib/matplotlib#23777]
Interactive zoom rectangle is not visible on dark backgrounds for MACOSX backend.

Seems like this has been fixed when using QT backend (issue [#16798](https://github.com/matplotlib/matplotlib/pull/16798)), but can't find any solution / workaround for MACOSX backend.

<img alt="Light Background" src="https://i.stack.imgur.com/vTDEp.png">

<img alt="Dark Background" src="https://i.stack.imgur.com/udPJs.png">

**Comment by tacaswell** [comment]
This is a good first issue because there is no API design and does not require any understanding of Matplotlib internals.

Labeling this as medium difficulty because the implementation is likely to touch the objective C code and may require familiarity with both Python and objective C.  This may require research into the underlying toolkit's API.

**Comment by QuLogic** [comment]
In the Qt backend, we draw the rectangle twice, once in black, once in white with an offset. The same can be done in the macos backend.

**Comment by oscargus** [comment]
Just to clarify, that offset is in the "dash-space"? (I first read it as x and y offset.) I guess one can possibly even use the new striped line functionality for this?

**Comment by anntzer** [comment]
In all likelihood it will be much faster to do this with calls to native (dashed) path-drawing functions.

**Comment by QuLogic** [comment]
Yes, in dash space. Both Qt and GTK draw them with native calls.
