### ISSUE TITLE
[Bug]: crash due to backend issue in ipython session started explicitly with InteractiveShell 

### ISSUE THREAD

**Issue by zpincus** [matplotlib/matplotlib#23770]
### Bug summary

If an IPython session is started via `IPython.core.interactiveshell.InteractiveShell.instance()`, trying to create a matplotlib figure, or even query the backend, produces a crash (stack trace below) on OS X, and on Linux if there is an active X11 session.

Without an X session on Linux or if ipython is started via the command-line `ipython` command, everything works as expected.

### Code for reproduction

```python
import IPython.core.interactiveshell
IPython.core.interactiveshell.InteractiveShell.instance()

import matplotlib.pyplot
matplotlib.pyplot.figure()
# or the below crashes too
import matplotlib
matplotlib.get_backend()
```

### Actual outcome

```
In : matplotlib.pyplot.figure()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zpincus/miniconda/envs/mplcrash/lib/python3.10/site-packages/matplotlib/pyplot.py", line 806, in figure
    manager = new_figure_manager(
  File "/Users/zpincus/miniconda/envs/mplcrash/lib/python3.10/site-packages/matplotlib/pyplot.py", line 324, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/Users/zpincus/miniconda/envs/mplcrash/lib/python3.10/site-packages/matplotlib/pyplot.py", line 314, in _warn_if_gui_out_of_main_thread
    if (_get_required_interactive_framework(_get_backend_mod())
  File "/Users/zpincus/miniconda/envs/mplcrash/lib/python3.10/site-packages/matplotlib/pyplot.py", line 217, in _get_backend_mod
    switch_backend(dict.__getitem__(rcParams, "backend"))
  File "/Users/zpincus/miniconda/envs/mplcrash/lib/python3.10/site-packages/matplotlib/pyplot.py", line 262, in switch_backend
    switch_backend(candidate)
  File "/Users/zpincus/miniconda/envs/mplcrash/lib/python3.10/site-packages/matplotlib/pyplot.py", line 310, in switch_backend
    install_repl_displayhook()
  File "/Users/zpincus/miniconda/envs/mplcrash/lib/python3.10/site-packages/matplotlib/pyplot.py", line 150, in install_repl_displayhook
    ip.enable_gui(ipython_gui_name)
  File "/Users/zpincus/miniconda/envs/mplcrash/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3455, in enable_gui
    raise NotImplementedError('Implement enable_gui in a subclass')
NotImplementedError: Implement enable_gui in a subclass

```

### Expected outcome

```
In : matplotlib.pyplot.figure()
<Figure size 640x480 with 0 Axes>
```

### Additional information

The below is sufficient to reproduce the crash from a clean environment. 
```
conda create -n "mplcrash" -c conda-forge python=3.10 matplotlib ipython
conda activate mplcrash
python -c 'import IPython.core.interactiveshell as ipsh; ipsh.InteractiveShell.instance(); import matplotlib.pyplot as plt; plt.figure()'
```

It's a weird corner case to be creating an ipython session this way, and perhaps the problem is on my end, but I wasn't expecting a crash like this regardless...

### Operating system

macOS, Linux, maybe windows too?

### Matplotlib Version

3.5.3

### Matplotlib Backend

this crashes too with the same error when invoked after starting `InteractiveShell.instance()` 

### Python version

3.10.6 (but also occurs with various 3.9 versions)

### Installation

conda

**Comment by tacaswell** [comment]
The source of the problem is that we by default try to pick the "best" backend and use that.  If you have an active X session and a GUI framework installed we will select that.  In order for the GUI window to be responsive someone needs to take care of running the GUI event loop while waiting for the human to type into the terminal.  What `enable_gui` is doing is telling IPython to set up its inputhooks [1].  However because you are launching IPython from the base class to hook to install the hooks is not implemented, and hence the failure.

The immediate work around is to either force the backend to be non-interactive [2] via 
```
MPLBACKEND=agg python -c 'import IPython.core.interactiveshell as ipsh; ipsh.InteractiveShell.instance(); import matplotlib.pyplot as plt; plt.figure()'
```
(svg and pdf would also work, pick the one that matches the type you expect to save most often).  If you want to have GUI integration then you need to launch one of the sub-classes of `InteractiveShell` that has the GUI hooks implemented.

Medium term, we should catch errors in the call to `enable_gui` and continue down the fallback chain.

I am going to label this as good first issue and medium difficulty.  There is no API design involved here (we have a reproduction case that should not fail), but the backend selection code / fallback logic in `pyplot` is a bit complicated (it is a complicated thing and while we are working on simplifying it we are currently in the awkward state where both the old and new are around).  The exact steps here are:

 - adjust pyplot so in this case we will (eventually) fallback to a non-interactive backend (probably convert the `NotImplementedError` into an `ImportError` and undo a bunch of work we just did)
 - write a test that will reliably exercise this path (probably will require a subprocess?  We have some tools to make that easy)

The relevant code: https://github.com/matplotlib/matplotlib/blob/07af52236908e21677a59102177ab387f00838ab/lib/matplotlib/pyplot.py#L210-L329


[1] : more details than anyone wants about input hooks: https://matplotlib.org/stable/users/explain/interactive_guide.html
[2]: https://matplotlib.org/stable/users/explain/backends.html

**Comment by zpincus** [comment]
Thanks! This all makes sense.

For posterity / future googling: I actually discovered this issue because `bokeh.io.output_notebook()` actually (and unexpectedly to me at least) winds up invoking `IPython.core.interactiveshell.InteractiveShell.instance()` if no ipython is running already. So, for example, a stray `output_notebook()` in a script will summon this above exception.

**Comment by nithinivi** [comment]
I can try to take this issue! if you guys would guide me

**Comment by tacaswell** [comment]
@nithinivi Do you have specific questions about https://github.com/matplotlib/matplotlib/issues/23770#issuecomment-1230950650 ?

**Comment by nithinivi** [comment]
@tacaswell I'm working from a windows laptop, and I was able to reproduce the error, Is there something is should specifically consider while developing windows? so sorry for the late reply ! :)

**Comment by tacaswell** [comment]
No, I do not think that this issue is platform specific.

**Comment by turnipseason** [comment]
Hi! It seems that this issue is still around (tried and got it on windows, at least).
Is it free to work on? I'd like to give it a try.

**Comment by tacaswell** [comment]
> but after qtagg "fails", the next two backends are cairo-based.

we also have `*cairo` variant backends which are what depend on pycairo.  Please do not re-arrange the backend order. 

If you commit your changes it will work (we write the version Matpltolib used to generate the pickle into the file and then check if it matches the current version on the way out, the reported version of Matpltolib depends on the current state of git).

**Comment by turnipseason** [comment]
> we also have `*cairo` variant backends which are what depend on pycairo. Please do not re-arrange the backend order.
> 
> If you commit your changes it will work (we write the version Matpltolib used to generate the pickle into the file and then check if it matches the current version on the way out, the reported version of Matpltolib depends on the current state of git).

Thanks for replying and the clarification! I'll check everything once again and try submitting a PR in the morning then :)
