### ISSUE TITLE
[Bug]: comments being read in matplotlibrc?

### ISSUE THREAD

**Issue by jguzman-tech** [matplotlib/matplotlib#23798]
### Bug summary

When deleting some comments from matplotlibrc, I get errors because some parameters are not set. I tested this behavior by installing different matplotlib versions via conda (v3.5.3, v3.5.1, but not v.3.2.2) and then editing matplotlibrc. In my example I installed matplotlib v3.3.4 via pip.

This behavior can be reproduced by deleting 1 commented line in the packaged matplotlibrc file in any text editor:

`#backend_fallback: True`

You can also use sed:

`sed -i '/^#backend_fallback: True$/d' /path/to/my/matplotlibrc`

### Code for reproduction

```python
# note: must first delete specified comment line above from matplotlibrc, will throw KeyError
python3 -c "import matplotlib; print(matplotlib.__version__)"
```

### Actual outcome

Here's a full run. Even diff'd the matplotlibrc file with that of a fresh env, and used strace to prove that there's no other matplotlibrc being loaded from the CWD or ~/.config.
```
[0:jfg95@wind:~]-> python3 -m venv ./matplotlib-test-1
[0:jfg95@wind:~]-> . ./matplotlib-test-1/bin/activate
(matplotlib-test-1) [0:jfg95@wind:~]-> pip3 install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/a4/6d/6463d49a933f547439d6b5b98b46af8742cc03ae83543e4d7688c2420f8b/pip-21.3.1-py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 9.0.3
    Uninstalling pip-9.0.3:
      Successfully uninstalled pip-9.0.3
Successfully installed pip-21.3.1
You are using pip version 21.3.1, however version 22.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(matplotlib-test-1) [0:jfg95@wind:~]-> pip3 install matplotlib==3.3.4
Collecting matplotlib==3.3.4
  Using cached matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl (11.5 MB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-8.4.0-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp36-cp36m-manylinux1_x86_64.whl (1.1 MB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting numpy>=1.15
  Using cached numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, python-dateutil, pyparsing, pillow, numpy, kiwisolver, cycler, matplotlib
Successfully installed cycler-0.11.0 kiwisolver-1.3.1 matplotlib-3.3.4 numpy-1.19.5 pillow-8.4.0 pyparsing-3.0.9 python-dateutil-2.8.2 six-1.16.0
(matplotlib-test-1) [0:jfg95@wind:~]-> python3 -c "import matplotlib; print(matplotlib.__version__)"
3.3.4
(matplotlib-test-1) [0:jfg95@wind:~]-> sed -i '/^#backend_fallback: True$/d' ~/matplotlib-test-1/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc
(matplotlib-test-1) [0:jfg95@wind:~]-> diff ~/{matplotlib-test-1,matplotlib-untouched-rc}/lib/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc
98a99
> #backend_fallback: True
(matplotlib-test-1) [1:jfg95@wind:~]-> python3 -c "import matplotlib; print(matplotlib.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jfg95/matplotlib-test-1/lib64/python3.6/site-packages/matplotlib/__init__.py", line 931, in <module>
    for key, validator in rcsetup._validators.items()}
  File "/home/jfg95/matplotlib-test-1/lib64/python3.6/site-packages/matplotlib/__init__.py", line 931, in <dictcomp>
    for key, validator in rcsetup._validators.items()}
  File "/home/jfg95/matplotlib-test-1/lib64/python3.6/site-packages/matplotlib/__init__.py", line 708, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'backend_fallback'
(matplotlib-test-1) [1:jfg95@wind:~]-> strace -f -e openat python3 -c "import matplotlib; print(matplotlib.__version__)" |& grep matplotlibrc
openat(AT_FDCWD, "/home/jfg95/matplotlib-test-1/lib64/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc", O_RDONLY|O_CLOEXEC) = 3
openat(AT_FDCWD, "/home/jfg95/matplotlib-test-1/lib64/python3.6/site-packages/matplotlib/mpl-data/matplotlibrc", O_RDONLY|O_CLOEXEC) = 3
(matplotlib-test-1) [0:jfg95@wind:~]->
```

### Expected outcome

No `KeyError` after deleting a comment.

### Additional information

Unless this is expected behavior, comments are not being properly ignored. In at least one previous matplotlib release (v3.2.2) I did not get an error when deleting a comment, but I only tested a handful of matplotlib releases.

My team noticed this behavior after attempting to edit matplotlibrc to ensure that everyone would be using the `Agg` backend for an lmod package.

### Operating system

RHEL 8.6

### Matplotlib Version

3.3.4

### Matplotlib Backend

agg

### Python version

Python 3.6.8

### Jupyter version

N/A

### Installation

pip

**Comment by tacaswell** [comment]
Yes, this is now the expected behavior.  This file is part of our configuration use it to store the default values and do not expect end users to edit this file (any more than we expect the end user to edit one of the `.py` files that gets installed).  We do have a warning at the top:
https://github.com/matplotlib/matplotlib/blob/ddb891751d797517e28b9f74d1fffc98716f8c7d/lib/matplotlib/mpl-data/matplotlibrc#L1-L17

If you want to ensure that you always get the Agg backend you can 

1. if you are building Matplotlib your self set the mplsetup.cfg config to have us template the default backend [1]
2. set the `MPLBACKEND` env to 'agg'
3. drop a modified version of the matplotlibrc in one of the places specified
4. set the `MPLCONFIGDIR` directory to point to where you have dropped a modified matplotribrc https://matplotlib.org/stable/users/faq/environment_variables_faq.html?highlight=env#envvar-MPLCONFIGDIR 
5. if you are going to modify the packaged matplotlibrc (please do not) leave a leading `#` so that the code that extracts the defaults will still work


I'm sorry we broke what you had been doing, but there are a number of ways to achive the same thing that do not require effectively hot-patching the installed source.

[1] https://github.com/matplotlib/matplotlib/blob/ddb891751d797517e28b9f74d1fffc98716f8c7d/mplsetup.cfg.template#L28-L38

**Comment by jklymak** [comment]
I'll close because this happened a log time ago, and we can't go back now!

**Comment by jguzman-tech** [comment]
@tacaswell Thanks for the recommendations! We'll make use of the MPLBACKEND env variable for now.
