### ISSUE TITLE
[Doc]: Missing source files

### ISSUE THREAD

**Issue by StefRe** [matplotlib/matplotlib#23876]
### Documentation Link

https://matplotlib.org/devdocs/index.html

### Problem

Clicking on "Show Source" results in "Page Not Found" (pertains to any site in the docs, not just the example given above).
![grafik](https://user-images.githubusercontent.com/19879328/189614071-ddf6f4d0-b8fc-4e4d-b84f-6ed71577c7de.png)

### Suggested improvement

Add sources (or remove link).

**Comment by tacaswell** [comment]
This is because we intentionally remove `_source` directory in the circle config https://github.com/matplotlib/matplotlib/blob/main/.circleci/config.yml#L145 .  We did that because the `store_artifcats` uploads a file-at-a-time and we were spending an in ordinate amount of time in that.

Under the old theme I think we had already removed the "show source" link (which I think are of limited value as it is the rst which I have never personally actually wanted).  My preference here would be to remove the link in the template with a second choice option of moving the `_source` directory to hide it from the artifact upload (which leaves the PR build artifacts broken) and then moving it back for the commit.

**Comment by StefRe** [comment]
I don't need the sources online, I just clicked on the link out of curiosity and because I didn't see it before, so removing the "show source" link is fine with me.

**Comment by timhoffm** [comment]
While I agree that source links are of limited value and could be removed, there has been work to make these point to GitHub https://github.com/matplotlib/matplotlib/pull/20673. At least some user and reviewers saw value in the links. This should be considered before removing.

**Comment by tacaswell** [comment]
My understanding is that #20673 is the links back to the Python source in the refernce docs. e.g. https://matplotlib.org/stable/api/_as_gen/matplotlib.animation.AbstractMovieWriter.html#matplotlib.animation.AbstractMovieWriter 
![image](https://user-images.githubusercontent.com/199813/190714239-08de74e0-321b-4831-a840-b5f04813de6e.png)

whereas the source links here are to the `_source/blah.rst` that sphinx adds to the source of page you are looking at.

I think the first are very useful and the second are of limited use.

**Comment by timhoffm** [comment]
You're right. Me 🐑
