### ISSUE TITLE
[ENH]: scatter 3D numpy array using their (x,y,z) projectories

### ISSUE THREAD

**Issue by Firestar-Reimu** [matplotlib/matplotlib#24277]
### Problem

I often come across the situation where I have some 3d numpy array like: `data = np.random.rand(10, 10, 10)`.

Is there any way I can scatter data `using their (x,y,z) projectories`. for example: `data(1,1,4) = 514`, and make a 3D plot which plots `point(1,1,4)` as the color data `cdata` corresponding to the value 514.

What is the pythonic way to go from data to x, y, z and cdata?

**Comment by ksunden** [comment]
```python
>>> import numpy as np
>>> from matplotlib import pyplot as plt
>>> fig = plt.figure()
>>> ax = fig.add_subplot(projection="3d")
>>> x = np.arange(5)
>>> y = np.arange(8)
>>> z = np.arange(10)
>>> x,y,z = np.meshgrid(x,y,z)
>>> ax.scatter(x,y,z,c=np.random.rand(5,8,10))
<mpl_toolkits.mplot3d.art3d.Path3DCollection object at 0x7f2e4d6c5c50>
>>> plt.show()
```

I think this does what you want: 
![Figure_2](https://user-images.githubusercontent.com/2501846/198074466-9371668f-5e2c-4eec-a35d-eb5d0488514f.png)


(I changed shapes just to make it obvious that order does matter when the shapes are not equal)

**Comment by Firestar-Reimu** [comment]
Thanks! This solve my problem.

If we can plot them like boxes will be better.

for example, in the graph above, every plot is a 1x1x1 box with the same color?

**Comment by ksunden** [comment]
Ah, then this sounds like [voxels](https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.mplot3d.axes3d.Axes3D.html?highlight=voxels#mpl_toolkits.mplot3d.axes3d.Axes3D.voxels)

```python
norm = mpl.colors.Normalize(np.min(data), np.max(data))
ax.voxels(np.ones_like(data), facecolors=mpl.colormaps["viridis"](norm(data)))
```
(with the same setup for axes with 3d projection)

Now, you won't be able to see inside of the shape.

Note that voxels are more commonly used to show/exclude boxes rather than to show data as the color, so the `ones_like` is just saying "show every box" and the `facecolors` kwarg is calling the colormap directly to get color information in a format voxels can use.
Norm just normalizes the data to a range of 0 to 1, if you really only care about `np.random.rand` data, then that may be omitted, as that is already in that range.

Be aware that most of the boxes will not be visible, only those on the surface will be.

![Figure_1](https://user-images.githubusercontent.com/2501846/198241681-a12038d1-7c85-4062-b682-d8777c6f0ae8.png)

**Comment by scottshambaugh** [comment]
Closing since a pythonic solution was provided.
