### ISSUE TITLE
[Bug]: rcParams["interactive"] is overwritten if rc_context is used before anything else

### ISSUE THREAD

**Issue by timmysilv** [matplotlib/matplotlib#24351]
### Bug summary

`rcParams["interactive"]` is set based on environment upon the user's first call to plot some figure. However, if that call is wrapped with `@mpl.rc_context` (or does some sort of caching the original `rcParams`), it saves the default value of `interactive=False` and then restores it regardless of whether or not it has been updated to True.

### Code for reproduction

```python
### in an interactive environment such as a Jupyter notebook:

import matplotlib as mpl
from matplotlib import pyplot as plt
import numpy as np

y = np.linspace(1,100,100) ** 2

with mpl.rc_context({'lines.linestyle': '--'}):
    plt.plot(y)


### In another Jupyter cell:

plt.plot(y)
```

### Actual outcome

![image](https://user-images.githubusercontent.com/23283972/199745653-1e0946e6-0446-4b11-9342-29cf8b73fc97.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/23283972/199746000-40d85e2e-ba8d-4c23-a0f6-68ee6dc7bc74.png)

### Additional information

If the value of rcParams["interactive"] was fetched and added to `orig` in the `finally` block [here](https://github.com/matplotlib/matplotlib/blob/0b6d3703ff43ae87815dcc891c56e7a7c50ce5ff/lib/matplotlib/__init__.py#L1111), this should fix it. You'd have to ensure that the calling `rc` or `fname` didn't override `interactive` manually, so this change might require some additional care.

### Operating system

MacOS

### Matplotlib Version

3.5.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.13

### Jupyter version

6.4.12

### Installation

pip

**Comment by tacaswell** [comment]
Just to check if you make a plot in the first cell with out `rccontext` and then use `rccontext` in the second does it work as expected?

Additionally if you add `%matplotlib inline` to the top of your first cell does it work as expected?

I also expect putting `plt.ion()` in the first cell will also fix the problem.

We recently fixed a bug where we special cased the `'backend'` key in rcparams, which seems OK to do because it was ourselves changing it, however in this case I suspect that the inline backend changing it.  I do not think we can reliability tell if an rcparam as set be by the user in a way they want restored or was set by the import and selection of the inline backend and they probably do not want it restored.

Reading the docstring I see it is not clear, however the behavior of this context manager going back to when it was added in 2012 has been to reset all rcparams change in the context, not just the ones set in invoking the context manager so I do not think we can change that.

Unfortunately, I think we are stuck between a rock and a hard place on this.  We do not want to revert on deferring backend selection and loading until we actually need it (that prevents a bunch of other weird issues but makes some new ones), I do not think that matplotlib-inline should stop setting interactive on import (because in the case where the user does not use a context manager for their first plot it works out pretty well), we can not not revert the rcparams set in the body of the context manager, and I do not think we want to special case `'interactive'` the same way we did `'backend'`.  

Thus, the fix is to somehow in your notebook get interactive mode turned on before you use the context manager.   I'm not super stoked about that being the answer, but I do not see any other way out....

**Comment by timmysilv** [comment]
Thanks for getting back to me! All those workarounds within a notebook will certainly fix it. The thing that feels strange to me is, it seems that (without any rcParams changes) the `rcParams["interactive"]` value defaults to False on import, then gets set to True the first time it's used in any way. In the code snippet I provided, the dict was updated properly and the first plot was drawn, then restored. I think the part that subverts user expectations is: why doesn't the second call to `plt.plot` also check the backend to set `interactive=True` when appropriate? Is it too exhaustive to check that every time someone plots something? This isn't a critical bug, but it did take some poking around for me to realize what exactly was going on so I thought I'd raise it here. For direct use, the workarounds are no trouble at all. I am exercising caution because I'm working on a library that uses MPL and don't want users of the library to be unpleasantly surprised.

**Comment by tacaswell** [comment]
> the rcParams["interactive"] value defaults to False on import, then gets set to True the first time it's used in any way

I think this is _only_ true of the `matplotlib-inline` backend.

**Comment by timmysilv** [comment]
ok, thanks for all the info. All things considered, I'm satisfied with this - if you don't want to track this further, we can close this issue.

**Comment by tacaswell** [comment]
Thanks for being understanding @timmysilv , I really do not think there is anything we can do here (but I did update the documentation in #24354 to clarify it is expected to reset all rcparams).
