### ISSUE TITLE
[Bug]: Something about `plt.figure()` resets `rcParams['figure.facecolor']`

### ISSUE THREAD

**Issue by patricks1** [matplotlib/matplotlib#24393]
### Bug summary

On a fresh kernel, after setting `rcParams['fig.facecolor']`, the first instance of `plt.figure()` seems to reset `rcParams['figure.facecolor']` back to the default of transparent white. However, running the code a second time without resetting the kernel, the figure displays the correct color.

This did not happen in v3.5.1 but started in v3.5.2. It still occurs in v3.6.2.

### Code for reproduction

```python
from matplotlib import pyplot as plt, rcParams

rcParams['figure.facecolor'] = 'red'

fig = plt.figure()
ax = fig.add_subplot(111)
plt.show()

rcParams['figure.facecolor'] = 'red'

fig = plt.figure()
ax = fig.add_subplot(111)
plt.show()

fig = plt.figure()
ax = fig.add_subplot(111)
plt.show()
```

### Actual outcome

![image](https://user-images.githubusercontent.com/22312228/200390172-2c64925c-5bb6-4a66-b90c-d3b25df14201.png)

In the first plot creation, the `plt.figure()` instance seems to undo the `rcParams['figure.faceolor'] = 'red'` command. After setting `rcParams['figure.faceolor'] = 'red'` a second time and making subsequent `plt.figure()` instances, the red facecolor sticks and does not need to be reset after the second `plt.figure()` instance; the red color also sticks for the third plot.

### Expected outcome

All three plots should have a red facecolor.

### Additional information

This worked properly in v3.5.1. It started behaving incorrectly in v3.5.2 and still works incorrectly in v3.6.2.

### Operating system

CentOS Linux 7 (Core), MacOS 12.6

### Matplotlib Version

3.5.2, 3.6.2

### Matplotlib Backend

module://ipykernel.pylab.backend_inline

### Python version

3.10.2 on CentOS Linux, 3.10.1 on MacOS

### Jupyter version

6.3.0 on CentOS Linux, 6.4.6 on MacOS

### Installation

pip

**Comment by tacaswell** [comment]
I suspect this is another case of the inline backend setting rcparams on import now deferring the import until a late as possible.

I if you add

```
%matplotlib inline
```

or do

```python
plt.switch_backend('module://ipykernel.pylab.backend_inline')
# or
mpl.use('module://ipykernel.pylab.backend_inline')
```

before setting the rcparams is the problem resolved?

**Comment by ksunden** [comment]
Can confirm (with slightly outdated matplotlib_inline):

-set rcParam = `red`
-readback as `red`
-run `%matplotlib inline`
-readback rcParam as `(1,1,1,0)` (white)

So it comes down to:
matplotlib is intentionally lazy about actually loading backends, waiting until you do a call which relies on it (in this case, the first such call is `plt.figure()`, after you have set an rcParam)

But the backend which is selected (ipykernel inline) does a fair amount of rcParam manipulation when it is loaded, including, apparently, the figure facecolor.

Note that this does not appear to be the case with the most recent version of `matplotlib_inline` (documented as since 0.1.4, tested with 0.1.6)

Upgrading matplotlib_inline (`pip install --upgrade matplotlib_inline`) should resolve this issue I believe.

**Comment by patricks1** [comment]
Thank you @tacaswell and @ksunden! My MacOS environment was originally running `matplotlib_inline` v0.1.3. Upgrading to v0.1.6 fixed that environment. For some reason, my Linux enviro doesn't actually use `module://matplotlib_inline.backend_inline` but `module://ipykernel.pylab.backend_inline`. Checking my `ipykernel` version, I found that I was running v5.5.0 while the most recent version is v6.17.0. Upgrading to v6.17.0 fixed the issue. Also, in both enviros, @tacaswell's suggestion to put `%matplotlib inline` in the code before setting the `rcparams` also fixed the issue, even before upgrading `matplotlib_inline` and `ipykernel`.
