### ISSUE TITLE
[Doc]: add from file to font family example

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#24419]
### Documentation Link

https://matplotlib.org/devdocs/gallery/text_labels_and_annotations/font_family_rc.html

### Problem

The only documentation I could find of adding a font from file was [using a ttf file](https://matplotlib.org/devdocs/gallery/text_labels_and_annotations/font_file.html#sphx-glr-gallery-text-labels-and-annotations-font-file-py) which is about pointing to a specific file in text. We have the [FontManager API](https://matplotlib.org/devdocs/api/font_manager_api.html#matplotlib.font_manager.FontManager) but `addfont` is not used in any examples & we don't really document that to add a new font family you have to add all the .ttf/.afm files with that font, [indivdually](https://gitter.im/matplotlib/matplotlib?at=636c82ad25ca105c88ac3f8e).

### Suggested improvement

Amend the font family example to add a `font family from file` example. I don't guarantee this could works but it should be something like

Edit: working example  from @mikan3rd https://github.com/matplotlib/matplotlib/issues/17568#issuecomment-638714360
```python
from matplotlib import font_manager

font_dirs = ["/resources/fonts"]
font_files = font_manager.findSystemFonts(fontpaths=font_dirs)

for font_file in font_files:
    font_manager.fontManager.addfont(font_file)
```

and then use one of the font names of the new fonts in `ax.text(x,y, s, font=name)`to show how it works. Including maybe changing weights and the like to show the different family properties. 

I think it's a good first issue because it's fairly self contained.  I suggest using the font folder in source [lib/matolotlib/mpl-data/fonts](https://github.com/matplotlib/matplotlib/tree/main/lib/matplotlib/mpl-data/fonts) for the example  cause that one should build.

**Comment by Jeanne11on** [comment]
Hi is this still available? I'd like to be assigned to this issue.

**Comment by tacaswell** [comment]
xref: https://github.com/matplotlib/matplotlib/pull/24195 and https://github.com/matplotlib/matplotlib/issues/17568

I am tagging this is medium difficulty as it will require either knowing (or researching) the subtleties of font terminology and how we manage the singleton `FontManager` instance is used.  https://matplotlib.org/stable/users/explain/fonts.html is a good (but incomplete start).  This is not a good issue for someone new to programming.

As I commented in #24195, I'm not sure that we want to document and publicize this function.  The whole font manager machinery is for finding (and caching information about) the system or otherwise installed fonts on the computer.  I am very skeptical that having users add things to this structure is helpful (particularly given the confusion about when it gets persisted or not).  However, the reactions to https://github.com/matplotlib/matplotlib/issues/17568#issuecomment-638714360 suggests that there is a need for this sort of functionality.

On the other hand, registering with the font manager means your names can go into rcparams.

On the other other hand, of the places we search are user-writable spaces so we should better document there those are and tell people to drop their fonts there.

On the other other other hand, if you want to install fonts via Python package (which despite the fact that we do it I think is a bad idea in general) then you really need something like this.

I think the example, if we add it, would have to include a discussion of the trade offs of doing something like this.

**Comment by saranti** [comment]
I might take a crack at this @story645 @tacaswell. Can you point me to any good resources about the subtleties of font terminology etc?
