### ISSUE TITLE
[Doc]: change to install from conda forge 

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#24421]
### Documentation Link

https://matplotlib.org/devdocs/

### Problem

Our install instructions say to install from conda, but conda's version of matplotlib isn't always the latest. For example:
![image](https://user-images.githubusercontent.com/1300499/201185589-18cc82d6-0656-4b63-954b-be3563c1a044.png)

But this won't work because the latest version of matplotlib on conda is [3.5.3](https://anaconda.org/anaconda/matplotlib), which is not obvious unless you know to look at the page. 

### Suggested improvement

Maybe we should change it to `conda install -c conda-forge matplotlib` since we can ensure that will work?

**Comment by dopplershift** [comment]
That would make sense since we have control over what's available from `conda-forge`, whereas conda's `defaults` channel (and Anaconda) are outside our control.

**Comment by timhoffm** [comment]
I'm +0.5 on this.

The only downside is that users who don't know what channels are, are more likely to use the main channel because it's the default. Then, blindly copying the conda-forge install leads to a mixed environment. People who are on conda forge are more likely to know what a channel is and can adapt the call. OTOH there may be enough blind copy-pasting including `-c conda-forge` from other places that some people without channel-knowledge get the correct version by going to `conda-forge`.

### What are others doing:

- [numpy](https://numpy.org/install/) elegantly goes around this by creating a new environment. That's clean, but maybe also not what people want.
- [scipy](https://scipy.org/install/) only states `conda install scipy`
- pandas only states `conda install pandas` [here](https://pandas.pydata.org/docs/getting_started/index.html#getting-started) and has a very unhelpful additional [Download Anaconda](https://pandas.pydata.org/getting_started.html)

**Comment by ianthomas23** [comment]
> That would make sense since we have control over what's available from `conda-forge`, whereas conda's `defaults` channel (and Anaconda) are outside our control.

There is an internal Anaconda process for requesting a package build on `defaults` channel. I'll request a build of 3.6.2 and we can see how long it takes. In future someone could ping me when they want a new build.

**Comment by timhoffm** [comment]
Unfortunately, there is no universal recommendation that would match all users / use cases. anaconda and conda-forge are two distinct package sources with different boundary conditions.

Maybe the best way ist to turn this into three tabs: `pip | anaconda | conda-forge`

Each tab can get an additional sentence describing some context.

The downside is that only one is displayed at a time and we have to give one (pip) the priority of beeing initially shown. But that would be ok for me.

**Comment by ianthomas23** [comment]
I think my conda `defaults` investigations have held this up, and I don't want it to stall forever. So I would be inclined to opt for @story645's original suggestion of showing two options: `pip install matplotlib` and `conda install -c conda-forge matplotlib`.

I don't think we can justify giving equal billing to `conda install matplotlib`. We could reconsider this if/when there is a tried and tested process in place to update conda `defaults` on each new matplotlib release.

**Comment by exitflynn** [comment]
this seems pretty straightforward now, can i get to it? :cowboy_hat_face:

**Comment by QuLogic** [comment]
Fixed by #24888.
