### ISSUE TITLE
[Bug]: "import matplotlib.pyplot" gives ModuleNotFoundError

### ISSUE THREAD

**Issue by j1642** [matplotlib/matplotlib#24454]
### Bug summary

`import matplotlib.pyplot` returns `ModuleNotFoundError: No module named 'importlib_resources'` on Matplotlib version 8d2d4c26053f2c619e22f82b70c6abb6fc5cabcf. 

Can anyone reproduce this?

### Code for reproduction

```python
import matplotlib.pyplot as plt
```

### Actual outcome

```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [3], line 1
----> 1 import matplotlib.pyplot as plt

File ~/Python/mpl/matplotlib/lib/matplotlib/pyplot.py:55
     53 import matplotlib.image
     54 from matplotlib import _api
---> 55 from matplotlib import rcsetup, style
     56 from matplotlib import _pylab_helpers, interactive
     57 from matplotlib import cbook

File ~/Python/mpl/matplotlib/lib/matplotlib/style/__init__.py:1
----> 1 from .core import available, context, library, reload_library, use
      4 __all__ = ["available", "context", "library", "reload_library", "use"]

File ~/Python/mpl/matplotlib/lib/matplotlib/style/core.py:26
     22     import importlib.resources as importlib_resources
     23 else:
     24     # Even though Py3.9 has importlib.resources, it doesn't properly handle
     25     # modules added in sys.path.
---> 26     import importlib_resources
     28 import matplotlib as mpl
     29 from matplotlib import _api, _docstring, _rc_params_in_file, rcParamsDefault

ModuleNotFoundError: No module named 'importlib_resources'
```

### Expected outcome

Successful import.

### Additional information

The error is from [lib/matplotlib/style/core.py](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/style/core.py).

Locally on Python 3.9.7, I can fix the error by changing the operator on line 21 from `>=` to `<=`. I don't know if that will help other python versions.

### Operating system

Ubuntu

### Matplotlib Version

commit 8d2d4c26053f2c619e22f82b70c6abb6fc5cabcf

### Python version

3.9.7

**Comment by jklymak** [comment]
This is from https://github.com/matplotlib/matplotlib/pull/24257 (ping @anntzer) and is only on master....  Is importlib_resources a dependency we need to add for older pythons?  @j1642 if you do `pip install importlib_resources` (assuming you are using pip) does it work?

**Comment by ksunden** [comment]
#24257 is using an older, not particularly well documented method of adding the conditional dependencies by specifying as a particular `extras_require` section.

Since setuptools ~36.2, you can add the condition directly into main requirements section by adding: `"importlib_resources ; python_version<'3.10'",` into `install_requires`

While we do not explicitly set a minimum version of setuptools, setuptools_scm does set the minimum version to 45, so transitively we have a minimum version which supports the newer syntax.

In either case, this issue seems like a case of updating an existing install without rerunning `pip install -e .` as in a fresh environment the new dependency is correctly installed without specifying any `[extras]`. (which, if this is the case, would not be solved by moving to the newer specification style)

**Comment by j1642** [comment]
@ksunden is right, I did not update the dependencies after running `git pull`. My bad. Everything seems to work now. Thanks!
