### ISSUE TITLE
[Bug]: pyplot show function doesn't work if importing yolov7

### ISSUE THREAD

**Issue by NammaThalle** [matplotlib/matplotlib#24613]
### Bug summary

pyplot show function doesn't work if importing some function from yolov7

### Code for reproduction

```python
import matplotlib.pyplot as plt
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'yolov7'))
from yolov7_detect import load_model, detect_yolo

plt.plot(range(20), range(20))
plt.show(block=True)
```

### Actual outcome

no outcome

### Expected outcome

plot of graph

### Additional information

I have tested by adding "import matplotlib.pyplot as plt" line before and after the "from yolov7_detect..." line. it doesn't work.
Also when i comment "from yolov7_detect..." line I am getting the correct output. i.e the plot which i wanna show.

I have tried multiple backends including macosx, tkagg, agg, qt5agg, etc. but nothing seems to be working.

### Operating system

OS/X

### Matplotlib Version

3.6.2

### Matplotlib Backend

TkAgg

### Python version

3.9.0

### Installation

pip

**Comment by rcomer** [comment]
Thanks @NammaThalle for the report.  If the code snippet works without the yolov7 import then it’s plausible that the bug is actually in yolov7.  I would start by raising the issue over there, since it’s the higher level package.  If you and/or the yolov7 maintainers can make an example that demonstrates the problem without importing yolov7, then by all means raise it again here.

**Comment by QuLogic** [comment]
This sets the backend to Agg on import:
https://github.com/WongKinYiu/yolov7/blob/13594cf6d42bc3a49ff226570aa77b6bf7615f7f/utils/plots.py#L26

so you need to set the backend back to an interactive one after importing it. Or suggest to them that they not do that.

Going to close as this is not a Matplotlib bug.
