### ISSUE TITLE
[Bug]: Axes3D.set_frame_on not working as documented

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#24689]
### Bug summary

`Axes3D.set_frame_on` is documented as "Set whether the 3D axes panels are drawn.". However, this is really what `set_axis_on` and `set_axis_off` does (and `set_frame_on` doesn't do). (There is also `get_frame_on`.)

https://github.com/matplotlib/matplotlib/blob/4fda5fff98b58ff596ba6d0fbff2cc709c29025e/lib/mpl_toolkits/mplot3d/axes3d.py#L1337-L1350

https://github.com/matplotlib/matplotlib/blob/4fda5fff98b58ff596ba6d0fbff2cc709c29025e/lib/mpl_toolkits/mplot3d/axes3d.py#L176-L182

### Code for reproduction

```python
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import axes3d

X, Y, Z = axes3d.get_test_data(0.05)
ax1 = plt.subplot(1, 2, 1, projection="3d")
ax1.plot_wireframe(X, Y, Z)
ax2 = plt.subplot(1, 2, 2, projection="3d")
ax2.plot_wireframe(X, Y, Z)
ax2.set_frame_on(False)
```

### Actual outcome

Nothing is affected by `set_frame_on`.

![image](https://user-images.githubusercontent.com/8114497/206860270-51af8028-52b5-49c2-9075-3406a5f5fda4.png)

### Expected outcome

It should do as documented.

![image](https://user-images.githubusercontent.com/8114497/206860253-8ac74bc6-6c40-4aaa-998f-3e959af3f7e2.png)

### Additional information

`self._frameon` is set to `False` in `draw`. However removing this line does not change anything anyway.

https://github.com/matplotlib/matplotlib/blob/4fda5fff98b58ff596ba6d0fbff2cc709c29025e/lib/mpl_toolkits/mplot3d/axes3d.py#L445

I think that there are a few options:

1. Remove `Axes3D.set_frame_on` and `get_frame_on`. However, these will then be inherited from `Axes`, so not a good idea (although nothing is changed, documentation just more confusing).
2. Make `Axes3D.set_frame_on` call `set_axis_on/off`, keep both.
3. Make `Axes3D.set_frame_on` modify `self._axison` instead and deprecate `set_axis_on/off`.

The documentation for `*_frame_on` should be adapted to `set_axis_*` if kept and a `get_axis_on` method should probably be added.

### Matplotlib Version

main

### Installation

git checkout

**Comment by timhoffm** [comment]
There's a slight difference between `set_frame_on` and `set_axis_on/off`. the latter also removes ticks and tick labels. I think `frame_on` is more related to spines, though there is some intricate logic which I did not take the time to unravel.

More generally, I'd be happy to get rid of the `frame_on` concept. It seems not quite useful and is redundant. Also semantically, frame is a relatively poor concept for Axes (if anything I'd expect a frame to be outside around all ticks, titles and labels). spines and axis are much more appropriate.

Since I don't think we should follow up on the frame logic and it's not working anyway for 3D options 2 and 3 are out.

I think the cheap solution is 1. So far, nobody has complained it is not working, so by 1 we're effectively undocumenting it (and have the fallback to the still not working Axes method).
Alternatively, raise `NotImplementedError` and document that this is not supported and users should use axis/spine functionality instead.

**Comment by saranti** [comment]
@oscargus if you're happy with Tim's assessment, I can send in a PR that addresses solution 1?

**Comment by oscargus** [comment]
Please go ahead!

**Comment by saranti** [comment]
> Please go ahead!

No worries. 👍  Would any kind of test be necessary for this?

**Comment by oscargus** [comment]
Not sure. I do not remember the details fully, but I think that it is hard to test removed non-working stuff in general...
