### ISSUE TITLE
VS Code: Autocomplete and Syntax Highlighting do not work for matplotlib

### ISSUE THREAD

**Issue by CptK** [matplotlib/matplotlib#24701]
### Summary

I am using VS Code for coding python and I am having an issue regarding Matplotlib: Usually Autocomplete and Syntax Highlighting work fine but not with matplotlib. There everything is just white and I get no proposals. See this example:
![image](https://user-images.githubusercontent.com/52075921/207024707-12695f02-0a8f-4514-aeaa-e2c1e66c10c3.png)
I am using a virtual environment with python 3.10.8 and pylance as the python language server.

**Comment by oscargus** [comment]
I assume that you are (one way or the other) using https://github.com/microsoft/python-type-stubs ?

While we are discussing adding typing from the Matplotlib organization, improving those are the current way forward.

**Comment by oscargus** [comment]
For example, there is no typing annotation for `manager`of `FigureCanvasBase`:

https://github.com/microsoft/python-type-stubs/blob/116165aa23e718726dd5ec6e9481ceb16248d256/matplotlib/backend_bases.pyi#L267-L347

**Comment by oscargus** [comment]
I think that is a different issue related to `__init__.py` for Matplotlib. As figure is not imported there, it will not be accessible. Same with ipython.

**Comment by Avasam** [comment]
For a bit of context on what you are seeing:
- matplotlib does not currently ship with stubs are inline type hints. So any tool will see it as untyped. (there are stubs currently in the source code, added a few months ago, but they are not shipped, I assume because it's not ready)
- Some tools (like pyright and mypy) need to be told to use source code and infer types from there, when using untyped libraries.
- Pylance is a python language server for VSCode and a wrapper around pyright (essentially Pylance is pyright in VSCode extension form). It comes installed with the Python extension in VSCode. It is what's providing you with intellisense (token coloration, autocompletion, type hints in your editor, etc)
- Pylance specifically ships with https://github.com/microsoft/python-type-stubs (NOT pyright! so that causes a difference between cli and what you see). So any matplotlib type hint you may be seeing in VSCode only comes from there.
- Pycharm implements its own type checking.
- Pycharm and pyright/Pylance come bundled with https://github.com/python/typeshed. mypy requires manual `types-*` package installs
- `types-matplotlib` does not exist because matplotlib is not on typeshed, hence you're only seeing types with Pylance in VSCode that comes from https://github.com/microsoft/python-type-stubs/tree/main/matplotlib

---

- https://github.com/microsoft/python-type-stubs is a temporary location where hopefully everything either gets upstreamed to base library or added to typeshed.
- IMO it's not worth adding matplotlib to typeshed depending on how soon stubs are included with matplotlib releases
- The sooner matplotlib *does* release with type hints, the sooner this whole mess can be untangled and you won't need to correctly configure your type-checking tools

**Comment by oscargus** [comment]
Matplotlib 3.8 will ship with typing stubs.

**Comment by QuLogic** [comment]
Since the key problem here appears to be the lack of typing, and that is already mostly implemented for 3.8, I don't think this needs to remain open.
