### ISSUE TITLE
[Doc]: Delete examples made redundant by annotation tutorial rewrite (annotate_simple01, ...)

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#24723]
### Problem

#23606 moved a bunch of examples (annotate_simple01, ...) into the tutorial itself.  These examples are so short (and devoid of any explanatory text) that they can now be removed from the examples gallery and replaced by a redirect-from directive in the tutorial (to not break old links).

**Comment by rcomer** [comment]
Having recently been learning about annotations, I got a bit lost in the examples and api docs.  I eventually concluded that I should have started with the tutorial, so I am 👍 on anything that guides people there at the earliest opportunity.

**Comment by ayushanand308** [comment]
@anntzer I would like to work on this. Can you assign me this issue?

**Comment by rcomer** [comment]
Thanks @ayushanand308, please go ahead but we don't really assign issues.

**Comment by erg0dic** [comment]
Hi @anntzer, I noticed that there wasn't a pull request yet for this issue so I tried tackling it. Please have a look at my pull request. 

I noticed there were about 7 **obvious** examples in the user gallery that could easily be removed so I did just that and added a 
```
# .. redirect-from:: /gallery/userdemo/<gallery_example>
``` 
in the corresponding locations where the examples were used in the text of the `annotations.py` file. 

Not sure about the format for the redirect-from because I've never used sphinx? is that right? for autodoc generation. I saw the `redirect-from`s in a bunch of files in the header so just flagging that ...

**Comment by melissawm** [comment]
Is this closed by #25153?

**Comment by QuLogic** [comment]
It seems like `annotate_simple_coord02.py` was left behind; if that should stay, it should probably be renamed without the `02`. Otherwise, it could also be deleted and this issue closed.

**Comment by rcomer** [comment]
Closed by #26445
