### ISSUE TITLE
[ENH]: context manager to hijack down stream creation of new Figures

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#24898]
### Problem

Despite our advice (https://matplotlib.org/stable/tutorials/introductory/quick_start.html#making-a-helper-functions ) a large number of down stream libraries create Figures on behalf of users and do not provide a way for the user to pass in either the Figure or Axes that they would like to have their data plotted to.  A couple times a year we have requests like https://gitter.im/matplotlib/matplotlib?at=63b81c09c9591d20d38d6c5c where users are trapped by functions from down stream libraries that can not be composed the way they want.

In that thread I suggested the user (at their own risk) monkey patch `plt.subplots` as a pragmatic solution, but after a couple of iterations this turned into something that seemed reasonable for use to implement upstream.

### Proposed solution

The core problem here is that the user wants to inject some state through a call stack that does not provide a way to thread that state through (e.g. the plotting methods do not take `ax` or `fig`) so that leaves us with using global state to pass this through.  Fortunately in Python modules _are_ global state and the way pyplot is built we have exactly one entry point for fabricating new `Figure` objects so if we wanted to do something like say "the next 4 times I create a new Figure please _actually_ give me the SubFigures from a 2x2 grid" we can do that as:

```python
import matplotlib.pyplot as plt
from contextlib import contextmanager


@contextmanager
def monkey_patch_figure(nrows, ncols, fig_kargs=None, **subfig_kwargs):
    fig_kargs = fig_kargs or {}
    orig_figure = plt.figure

    outer_fig = orig_figure(**fig_kargs)
    fig_iter = iter(outer_fig.subfigures(nrows, ncols, **subfig_kwargs).ravel())

    def patch_figure(*args, **kwargs):
        print('called')
        if args or kwargs:
            # TODO make actual warning or raise?
            print(f"got non-empty {args=} or {kwargs=} which will be ignored")
        return next(fig_iter)

    plt.figure = patch_figure

    try:
        yield outer_fig
    finally:
        plt.figure = orig_figure

with monkey_patch_figure(2, 2) as fig:
    plt.subplots(1, 2)
    plt.plot(range(5))
    plt.subplots(3, 1)
    plt.plot(range(5))
    plt.subplot_mosaic('AA;BC')
    plt.plot(range(5))
    plt.subplots()
    plt.plot(range(5))    

```

If we were to pull this into Matplotlib we probably should have the context manager set some private state that `plt.figure` looks at to decide if it should mint a new Figure or pop one off the stack (to catch downstream libraries who have done `from matplotlib.pyplot import figure` or `from pylab import *`) 

This works for the minimal smoke testing in the example so I'm sure that there are a bunch of edge cases that do not work as expected.  I think there a couple of decision points here:

1. is this even a good idea? On one hand it appears to solve a long standing problem ..... by using more of that problem (global state and the application-ness / statefullness of pyplot).
2. is patching `plt.figure` the right place?  The first iteration of this thinking patched `subplots` (and should do `subplot_moasic` as well).  The pro of `figure` is that it is broader so will catch more uses, but the con is because it is broader it will get more uses which makes it more likely we will hit edge cases that break.
3. Should this go in core or get shuffled off to mpl-gui / some other third-party packaging (or just be documented (or is this issue enough)?

**Comment by jklymak** [comment]
I think it should be figure as subplots have the connotation of them being related both conceptually and in geometry (ie spines line up) whereas subfigures do not.  Presumably if a library is doing this they want to compose subplots, and that seems unlikely to be compatible with a general subplot grid. 

I do overall think this is a bad idea, however.  Libraries should at the very least take a (sub)figure as an optional argument.  I think before subfigure this made less sense if a library wanted to spawn more than one axes, but now should make sense.  I guess the holdout would be libraries that want to set the size of the figure, but libraries that insist on that seem a bad candidate for this anyways.

**Comment by timhoffm** [comment]
1. **good idea?**: I'm quite sceptical on the idea. I cannot judge whether this will work reasonably, which gives me a bad feeling. Some things to consider:

   - We have to distinguish reassigning Figures and Axes. Assume we only patch Figure. This works for cases in which the library creates one figure with one or multiple Axes, provided we pass in an empty figure (the downstream code effectively adds the new Axes to the patched-in figure). However, this does not cover the case that you want the plots in Axes of a preconfigured layout; say you have `plot_A()` and `plot_B()` each creating a figure and a single Axes and you want them in `subplot_mosaic('AB')`. - You can achieve something similar using subfigures, but there are differences in alignment, sharing etc. so it's not a substitute.
     The more general approach is patching Figure and Axes creation (but it's also harder to do and to describe).

   - Semi-related: Do you accept figures with existing Axes as replacement? Most likely this will break because the downstream code expects an empty figure to work with. If we only allow empty figures, the use of the replacement is quite limited to some figure properties like size, color etc., most of which can be configured via rcParams or afterwards using `set_*`. This again hints at the need to go for the more complicated Figure+Axes patching if we want to have useful functionality.

   - Before thinking about implementation: Can we come up with a concise user-facing description what the feature does and how it should be used? If we can't we should not even consider implementing it.

   - A conceptually simple partial solution would be supporting functions that create one Figure and one Axes. These do not have subplot layout semantics and are mainly concerned with plotting the data (Figure and Axes creation being only a convenince so that the user does not have to bother with it). - Not sure whether that makes implementation anyway easier (maybe even harder) than the general case.

   - For the more-than-one-Axes plotting functions, there will clearly be cases that will fail, e.g.: the plotting function does `subplots(1, 2, sharey)` and because the Axeses are side-by-side it removes y-tick labels on the second Axes. If we then reasign to Axes from a `subplots(2, 1)` layout, the second Axes does not have y-ticks and no adjacent other Axes to infer the scale/limits from.

   - OTOH: *If* we can make this work really well, we might even consider revising the policy for downstream libaries. The could just create stuff and not have to bother with explicitly passing optional figure and axes parameters through.

2. **where to patch**: `subplots` is definitively the wrong place to patch. The end user does not know whether a library uses `plt.subplots` or `plt.figure` to create a figure, so the cannot judge whether this well work. - One may even need to patch `Figure.__new__` 😨.

   > "the next 4 times I create a new Figure please actually give me the SubFigures from a 2x2 grid"

   Is this too complicated? No reasonable library I know of creates multiple figures with one function call. Therefore we could do

   "the next time a Figure is created, please reuse the following figure instead"

   ```
   with reuse_figure(fig):
       downstream_figure_creating_plot()
   ```

   one can always generalize that to multiple figures (`with reuse_figure([fig1, fig2])`) later if needed.

3. **where should this go?** I strongly suggest a third party library for experimental purposes.

**Comment by tacaswell** [comment]
I'm going to go ahead and close this.

Probably too clever for its own good, but the code is available if anyone wants to pick up a foot-cannon 😈 .
