### ISSUE TITLE
[Bug]: Clipping mask can shift in PDF and SVG file outputs when Bbox is adjusted

### ISSUE THREAD

**Issue by michaelmarty** [matplotlib/matplotlib#24890]
### Bug summary

I am trying to adjust the clipping box around markers, which work great for WxAgg and for PNG output. However, when I export in SVG or PDF, the clipping box has shifted up and to the right. 

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.transforms import Bbox
from copy import deepcopy

# Generic plot
plt.plot(range(6),range(6), marker='o')
plt.xlim(0, 5)
plt.ylim(0, 5)

ax = plt.gca()
# Original Code to expand the clipping box
# oldpts = ax.bbox.get_points()
# oldpts[1, 1] *= 1.05
# newbbox = Bbox(oldpts)
# Simple code to just copy the old bounding box
newbbox = deepcopy(ax.bbox)
for o in ax.lines:
    o.set_clip_box(newbbox)

# Save SVG
plt.savefig("test.svg")
# Show plot
plt.show()
```

### Actual outcome

See figure. The 0,0 point is clipped and the 5,5 point is not.

![test2](https://user-images.githubusercontent.com/15263033/210877723-44200595-1931-41c1-bf51-8202749aad19.svg)

### Expected outcome

See figure. Both should be clipped. This is what we see with PNG output and with the plt.show() rendering.

![test2](https://user-images.githubusercontent.com/15263033/210877864-525c0e4b-4373-4cd3-bb48-cf102185bebd.png)

### Additional information

When I copy the Bbox and set that as the clip box, it works fine. But, when I deepcopy it, it doesn't. 

I opened the SVG file in Illustrator, and there is a clipping box that is shifted up and to the right of the origin. It can be deleted in Illustrator to recover the content below.

I'm definitely open to workarounds. I'm not sure if I'm doing this right, but it seems to work for PNG files, which makes me think there is a glitch in the background somewhere.

### Operating system

Windows

### Matplotlib Version

3.6.2

### Matplotlib Backend

module://backend_interagg

### Python version

3.10.8

### Installation

pip

**Comment by tacaswell** [comment]
This is like because the axes clip box is not actually fixed, it depends on the figure size and resolution.  The default dpi is 100 (and the target screen units are 'pixels'), but for the vector output the effect dpi is 72 and the target units is pt.  When you make the copy (or otherwise get a static bounding box) it will come out wrong.

The hacky option is to create the figure at 72 DPI and then you will "get lucky", a more robust solution is to make a transformed box from `[-.05, 1.05, -0.5, 1.05]` in the transAxes coordinate system (75% chance I have spelled how to get that wrong), and the fanciest would be to use the transform chain to expand the bbox in a way that will follow the axes. 

https://matplotlib.org/stable/tutorials/advanced/transforms_tutorial.html is probably the reference you want.

**Comment by michaelmarty** [comment]
That makes sense. Any tips on how to do make a transformed box in the transAxes coordinate system? I've been searching and experimenting and can't get it, even with tips from the tutorial. I've also tried to modify the ax.bbox in place, but it won't allow that.

**Comment by jklymak** [comment]
I _think_ what you are trying to do is simply:

```
newbbox = TransformedBbox(Bbox([[0, 0], [1.05, 1.05]]),
                          ax.transAxes)
```
But, I could be misinterpreting.  I actually would agree that `set_clippath` could be a lot more clear about how to make these boxes.

**Comment by michaelmarty** [comment]
That's it! Thanks @jklymak and @tacaswell! Yeah, I can usually figure out how to get MPL to do what I'm looking for, but this one has stumped me for years. Finally thought I got it and then discovered this new issue. Thanks for your help!
