### ISSUE TITLE
[ENH]: Add (JPEG) encoded image to Axes without decode it first

### ISSUE THREAD

**Issue by huww98** [matplotlib/matplotlib#25130]
### Problem

I want to add some high-resolution but heavily compressed JPEG-encoded photos to my figure. Currently, I need to decode them to arrays then use `ax.imshow()`. The image will be re-encoded with PNG when saved to a PDF file, which is slow and makes the PDF file huge.

### Proposed solution

I would like a new API like
```python
with open('test.jpg', 'rb') as f:
    ax.add_encoded_image(f, format='jpg')
```
And when output to PDF, embed this image directly to stream with DCTDecode filter. If it is output to some else backend, decode and cache the image lazily and fall back to the old behavior.

**Comment by tacaswell** [comment]
I am very skeptical of this feature going into core as proposed, my current estimation of the complexity vs impact is very high complexity for relatively low impact.   


A feature that would still be a fair amount of work, but I think would have a high chance of being merged would be to extend https://github.com/matplotlib/matplotlib/blob/f3938be9f3be3446065e184b810ee0a8bcb54901/lib/matplotlib/backends/backend_pdf.py#L1747-L1804 and https://github.com/matplotlib/matplotlib/blob/f3938be9f3be3446065e184b810ee0a8bcb54901/lib/matplotlib/backends/backend_pdf.py#L1718-L1745 to make the format and compression options used for writing images to pdf files.  I would control this either via rcparams or extra kwargs to `savefig` (we have precedent for backend specific things being threaded through).


------


If you did want to push on an `Image` artist optimized for being fed pre-encoded data I would:

 - make a new `Artist` sub-class that takes the encoded blob at `__init__` time (usage would look like `ax.add_artist(MyCompressedImage(buffer, ...))`.  This is not too bad to do and quite in line with some of the thinking in https://github.com/matplotlib/data-prototype to pass data into artists that is not literal numpy arrays.  This will also provide you a bunch of simplification because the artist we make via `imshow` are really for color-mapped single-channel data but also happen to take RGB(A) arrays where we happen to skip 90% of the functionality.  With this artist you can be RGB(A) only and hence way simpler.
 - in the `draw` method sniff at the type of `renderer` and do something special when it is the pdf backend.  This is the part that I worry will be horrendously complicated as if you look at the `draw_image` implementation in the backend we are doing a bunch of work to stash all the images and write them out once at the end rather than inter-mixed in the stream.  I do not think it is impossible, but it would take some work and likely be very brittle.  Another option here would be to add an extra method to the renderer (but that likely has 0 chance of making it upstream).

I think that all of this can be developed in an external library (including implementing a backend that sub-classes from the built-in pdf backend if you want to go that route).  If I am wrong about how messy this will be, a straight forward implementation of these ideas is the best way to convince me 😄 .

**Comment by jklymak** [comment]
If you want to just merge PDFs I think [pypdf2](https://pypdf2.readthedocs.io/en/3.0.0/index.html) can overlay an image on top of a PDF, but I haven't looked into details.

**Comment by jklymak** [comment]
I'm going to close this for the reasons above, as I'm quite sure none of the regular devs will take this up.  However, if anyone else can come up with a good solution to this, they should open a PR.
