### ISSUE TITLE
[Doc]: cross link locator example with locator API

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#25172]
### Documentation Link

https://matplotlib.org/devdocs/gallery/ticks/tick-locators.html

### Problem

As demonstrated by @ksunden in today's new contributor meeting, there's no explicit link from [the locator example ](https://matplotlib.org/devdocs/gallery/ticks/tick-locators.html#tick-locators) to the [locator api](https://matplotlib.org/devdocs/api/ticker_api.html#matplotlib.ticker.Locator), it's just implicit in the intersphinx. 

### Suggested improvement

Add cross links as references in an admonition, like the [tick-formatter](https://matplotlib.org/devdocs/gallery/ticks/tick-formatters.html) example but fewer/more targeted references (locator only as a first pass?)

https://github.com/matplotlib/matplotlib/blob/472ebaa6a254b2e01d9c9ef0fb5e0c6318e02799/examples/ticks/tick-formatters.py#L112-L121

**Comment by nox1134** [comment]
Hey @story645, I'd like to take this issue. I am new to open source and this is my first time contributing, could you brief me more about this issue?

**Comment by melissawm** [comment]
Hi @nox1134 - you can take a look at the [contributing guide](https://matplotlib.org/devdocs/devel/index.html) for initial guidance. 

For this specific case, the Tick locators [example is autogenerated](https://matplotlib.org/stable/devel/documenting_mpl.html) from this python file: https://github.com/matplotlib/matplotlib/blob/main/examples/ticks/tick-locators.py

One suggestion to close this issue is to add a [reST link](https://matplotlib.org/stable/devel/documenting_mpl.html#referring-to-other-code) to the sentence below that points to the locator API. Something like:

> This example illustrates the usage and effect of the most common `matplotlib.ticker.Locator` instances.

**Comment by nox1134** [comment]
Thank you both for your suggestions and help! I have taken a look at the formatter example and I think I understand what is expected for the new section. I will start working on implementing the changes and will update you once the changes have been made.
