### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by jelber2** [matplotlib/matplotlib#25179]
### Bug summary

Not really a bug, but perhaps needs to be updated in 

https://github.com/matplotlib/matplotlib/blob/c9d7bff6705cf51a249cfb1f2bbbc7f9bef3bdf9/setupext.py#L764

Update 
`urls=["http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz"]`

to
`urls=["https://web.archive.org/web/20210427071050/http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz"]`

### Code for reproduction

```python
git clone https://github.com/matplotlib/matplotlib.git
git checkout c23ccdd
python install .
```

### Actual outcome

Fails because cannot access `http://www.qhull.org/download/qhull-2020-src-8.0.2.tgz`

### Expected outcome

Installs

### Matplotlib Version

c23ccdd

### Installation

None

**Comment by ksunden** [comment]
The current link works for me, may have been a temporary interruption or something specific to your network.

**Comment by jklymak** [comment]
link works for me as well.

**Comment by Fox214** [comment]
I also cannot work with the first link, I have to manually download qhull data and do a manual build, which also seems to report the wrong version number. The 2nd link above does work for me (tested both with wget) 

More specifically, I can install fine with pip on linux/x86 machines, but linux/power hosts I have this problem, I assume its something with the machine configuration (since this is 100% of the time and not random) but I do not control that. 

A simple env variable that overrides the default (if set) to change the link or use a local copy would probably satisfy the situation.

**Comment by tacaswell** [comment]
See https://matplotlib.org/stable/devel/dependencies.html#c-libraries for instructions on how to have it pick up the system versions.  I will open a PR adding text about where to download and unpack to.

Adding an ENV to reset the URLs or changing the link to point at archive.org are both non-starters.

@Fox214 I suggest you take this issue up with whoever does run your system/network.

**Comment by tacaswell** [comment]
You can also use `MPLSETPUPCFG` (https://matplotlib.org/devdocs/users/faq/environment_variables_faq.html#envvar-MPLSETUPCFG) to point a `pip install matplotlib` at a local cfg file to get it to build with system libraries.

**Comment by Fox214** [comment]
Well by default using the system qhull does not work because its not installed. But for anyone else that hits this you can work around this (linux/bourne shell) instructions:
download and gunzip/untar the file:
cd qhull-2020.2
outputDir=/path/to/myqhull
cmake -DCMAKE_INSTALL_PREFIX=${outputDir} CMakeLists.txt 
make 
make install 
(the above commands will build it in location of your choosing, after which, not sure if the LDFLAGS is needed in this case, I did not try without):
export CFLAGS="-I${outputDir}/include ${CFLAGS}"
export LDFLAGS="-L${outputDir}/lib ${LDFLAGS}"
pip install matplotlib
