### ISSUE TITLE
[Bug]: ylabel's x position equals yaxis's x position?

### ISSUE THREAD

**Issue by rraadd88** [matplotlib/matplotlib#25190]
### Bug summary

I am trying to get ylabel's x position for a subplot. With the two methods I used, as shown in the code below, I get yaxis's x position instead.

The ylabel's x position relative to the y-axis can vary depending on the objects in between i.e. ticks, ticklabels etc. Therefore the yaxis's x position is not readily convertible to ylabel's x position, therefore I guess it may not be quite useful in many contexts. Although please correct me if I got this wrong.

I would simply like to get the ylabel's x position instead.

In case there is any other method other than the two I used, please let me know. Also, in case this is supposed to be a feature(!), to allow users to deduce ylabel's x position by converting yaxis's x position, please let me know how that should be done. I would like to know how robust such conversion would be for a figure with multiple subplots having unequal widths.

### Code for reproduction

```python
import matplotlib.pyplot as plt
ax=plt.subplot()

## method #1
xy=ax.set_ylabel('ylabel').get_position()
print(f"ax.set_ylabel('ylabel').get_position()={xy}")
ax.text(s='<- here',x=xy[0],y=xy[1],ha='left')

## method #2
xy=ax.yaxis.get_label().get_position()
print(f"ax.yaxis.get_label().get_position()={xy}")
ax.text(s='<- here again',x=xy[0],y=xy[1],ha='left')
```

### Actual outcome

```
ax.set_ylabel('ylabel').get_position()=(0, 0.5)
ax.yaxis.get_label().get_position()=(0, 0.5)
```
![image](https://user-images.githubusercontent.com/9945034/218139061-9cc9b764-eeb1-43cd-bc28-fc139202f770.png)

### Expected outcome

![image](https://user-images.githubusercontent.com/9945034/218139281-f71e3e51-62c3-4649-9a0d-f0b8af707434.png)

### Additional information

**What are the conditions under which this bug happens? input parameters, edge cases, etc?**
Please see the code above.

**Has this worked in earlier versions?**
I haven't tested this on other matplotlib versions.

**Do you know why this bug is happening?**
NA.

**Do you maybe even know a fix?**
NA.

### Operating system

Ubuntu

### Matplotlib Version

3.5.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

 3.7.13

### Jupyter version

3.4.6

### Installation

pip

**Comment by jklymak** [comment]
This is expected behaviour.  If the x position is _exactly_ zero, then the ylabel is automatically moved to the left of the decorations.  This isn't decided until draw time, so to get the position, you need to call `figure.draw_without_rendering()`.  Or you can set the x position manually.  

Note that what you get from `get_position` after the call to draw_without_rendering is in a mixed co-ordinate system, and you will have to transform to axes co-ordinates.  

This isn't really a bug, so I'm going to close here.  However, if you want more guidance, please feel free to discuss at https://discourse.matplotlib.org

Thanks!
