### ISSUE TITLE
Possibility of using Matplotlib by importing Polars library in Python

### ISSUE THREAD

**Issue by Killpit** [matplotlib/matplotlib#25317]
### Problem

Polars is one of the recent Python library that has all the functionalities in Pandas while being much faster. However, as I looked at the documentation from both Polars library and matplotlib, I couldn't find anything. 

If polars library support is added to matplotlib, it becomes much easier and faster to create visualisations without losing time and the data frame becomes much tidier.

### Proposed solution

The solution should allow a support for Polars library where an extra line _polars to visualisation so that we can use Polars data frames

**Comment by jklymak** [comment]
We don't officially support pandas, so I doubt we are officially going to support polars.  However if polars data frames behave properly when using no.asarray then they should work the same as pandas data frames in our methods. Did you test to see if they work? 

If you mean df.plot type methods that is totally in pandas court, but if they go that route they should come talk to us.

**Comment by tacaswell** [comment]
This is the sort of integration that https://github.com/matplotlib/data-prototype is trying to make easier by pushing the integration point out a level from the core library.

In the current state of Matplotlib, we need things as numpy arrays (and will do that conversion internally via `np.asarray` as Jody said) because at the bottom we need to actually have all of the array data materialized in our code.  If polars supports this it should "just work" and if not, I think that the work needs to happen in polars to support that as it is very very unlikely that we are going to thread a polars dependency through the entire code base.

I am going to close this and track this work in https://github.com/matplotlib/matplotlib/issues/16402 and https://github.com/matplotlib/matplotlib/issues/22645 .

**Comment by jklymak** [comment]
Polars works fine so far as I can tell, at least for a simple dataframe.  Again, if you want `df.plot()` that is something to request of polars.  

```python
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import polars as pl

data = {"a": [1, 2, 3, 4], "b": [3, 4, 5, 6]}
df = pl.DataFrame(data)

plt.plot(df['a'], df['b'])
plt.show()
```
