### ISSUE TITLE
[Bug]: AttributeError: module 'matplotlib' has no attribute 'pyplot' on Mac

### ISSUE THREAD

**Issue by teslyuk** [matplotlib/matplotlib#25506]
### Bug summary

I'm getting a weird error locally on my Mac in Jupyter Notebook while trying to plot the graph with `matplotlib`. 
The error is: `AttributeError: module 'matplotlib' has no attribute 'pyplot'` even though everything is imported correctly and code works on Google Colab.

### Code for reproduction

```python
import librosa
import librosa.display
import matplotlib.pyplot as plt

def plot_mel_spectrogram(wav_file_path):
    y, sr = librosa.load(wav_file_path, sr=None)

    S = librosa.feature.melspectrogram(y=y, sr=sr, n_mels=128)

    log_S = librosa.power_to_db(S, ref=np.max)

    plt.figure(figsize=(10, 4))
    librosa.display.specshow(log_S, sr=sr, x_axis='time', y_axis='mel', cmap='coolwarm')
    plt.title('Mel spectrogram')
    plt.colorbar(format='%+02.0f dB')
    plt.tight_layout()
    plt.show()
```

### Actual outcome

```
File ~/envs/venv39/lib/python3.9/site-packages/matplotlib/_api/__init__.py:226, in caching_module_getattr.<locals>.__getattr__(name)
    224 if name in props:
    225     return props[name].__get__(instance)
--> 226 raise AttributeError(
    227     f"module {cls.__module__!r} has no attribute {name!r}")

AttributeError: module 'matplotlib' has no attribute 'axes'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/envs/venv39/lib/python3.9/site-packages/matplotlib_inline/backend_inline.py:99, in show(close, block)
     96 # only call close('all') if any to close
     97 # close triggers gc.collect, which can be slow
     98 if close and Gcf.get_all_fig_managers():
---> 99     matplotlib.pyplot.close('all')

File ~/envs/venv39/lib/python3.9/site-packages/matplotlib/_api/__init__.py:226, in caching_module_getattr.<locals>.__getattr__(name)
    224 if name in props:
    225     return props[name].__get__(instance)
--> 226 raise AttributeError(
    227     f"module {cls.__module__!r} has no attribute {name!r}")

AttributeError: module 'matplotlib' has no attribute 'pyplot'
```

### Expected outcome

Plotted graph of mel spectrogram.

### Additional information

I tried to reinstall it and import it in different ways, but it didn't help.

### Operating system

MacOS

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.9.16

### Jupyter version

6.5.3

### Installation

pip

**Comment by tacaswell** [comment]
Can you simplify this to not use librosa?

I am also confused by the traceback because there are two `AttributeErrors` in there.

I am still suspicious that this is an installation issue.

**Comment by teslyuk** [comment]
Yeah, I tried to use w/o **librosa** and got the same issue plotting a trivial graph.
Another weird thing, it only happens in Safari web browser Jupyter session, in Chrome everything runs fine without any issues, as well as in Google Colab.

**Comment by tacaswell** [comment]
There is no way that the browser should be able to affect anything about the Python run time.  If it is working in one browser and not another I suspect that this is due to using different kernels (and venvs) in each of those.

Can you please start with on entirely fresh venv reproduce this?  I think we would need to see both how you set up the env and the output of `pip list`.

**Comment by teslyuk** [comment]
But that browser stuff, that's what exactly happened to me, weird. 
I tried it with entirely fresh venv and the issue disappeared, maybe the problem was in a corrupted virtual environment, idk. 

Anyways, thanks for the assistance, resolved.

**Comment by tuantje** [comment]
Hi,

I had the exact same problem on Windows (very similar code to yours as I am also plotting spectograms. I tried so many things. It wouldn't even work in a new fresh venv, and the problem seemed to only occur in Jupyter Notebook and not in Spyder for example. 

I found out that it works if I do **not** import librosa.display. I think it messes up the import of matplotlib(.pyplot).

Just import librosa and use librosa.display.X in the code. 

Hope this helps if it occurs in the future!

**Comment by tacaswell** [comment]
@tuantje Can you please report this to librosa?

attn @bmcfee

**Comment by rohithnocoder** [comment]
Hi, I had this exact problem. I solved it by importing matplotlib.pyplot before importing librosa and it's sub components. Pretty easy fix but why I wonder 🤔

**Comment by erkara** [comment]
> Hi, I had this exact problem. I solved it by importing matplotlib.pyplot before importing librosa and it's sub components. Pretty easy fix but why I wonder thinking
> 
> matplotlib version 3.7.1

this worked for me as well.

**Comment by ankur-patil-88** [comment]
> Hi, I had this exact problem. I solved it by importing matplotlib.pyplot before importing librosa and it's sub components. Pretty easy fix but why I wonder 🤔
> 
> matplotlib version 3.7.1

**Comment by ankur-patil-88** [comment]
Worked for me as well...

**Comment by mattpitkin** [comment]
As far as I can tell, this seems to be caused by the lazy loading of matplotlib in librosa's [`display.py`](https://github.com/librosa/librosa/blob/main/librosa/display.py#L64). If I manually change:

```python
if TYPE_CHECKING:
    import matplotlib
    ...
```

to

```python
if True:
    import matplotlib
    ...
```

i.e., do the imports directly rather than with the lazy loader, then this problem doesn't seem to occur (for me at least).

**Comment by QuLogic** [comment]
This is a bug in matplotlib-inline: https://github.com/ipython/matplotlib-inline/issues/24. If you check their imports, they import `matplotlib` and various _other_ `matplotlib.foo`, but _not_ `matplotlib.pyplot`, so when they use it, it's up to whatever happened before it whether it exists.

**Comment by agucova** [comment]
This is not an issue in matplotlib-inline, but rather in librosa, caused by their lazy loading. See [here](https://github.com/librosa/librosa/issues/1721).

**Comment by stefanv** [comment]
It is true that the problem is triggered by the lazy loading mechanism, but the more pertinent question here is whether the [fancy footwork](https://github.com/matplotlib/matplotlib/blob/main/lib/matplotlib/_api/__init__.py#L190) in the matplotlib machinery is truly needed. If it is, then we should investigate more carefully whether there is anything we can do in `lazy_loader` to help address the problem.

**Comment by bmcfee** [comment]
FWIW, I've patched this particular issue from the librosa side after realizing that we didn't actually *need* to directly lazy-load mpl submodules.  (I don't think it's "wrong" to do so, but since we don't need to, I've reworked it.)  This will roll out in the next release (some time this summer), but has already merged to main: https://github.com/librosa/librosa/pull/1722
