### ISSUE TITLE
[Bug]: art3d.py set_data_3d;   "RuntimeError- must be a sequence"

### ISSUE THREAD

**Issue by Drozdman-1** [matplotlib/matplotlib#25544]
### Bug summary

Breaks single point drawing. 
**set_data_3d() changed to:**

```
 def set_data_3d(self, *args): 
        if len(args) == 1:
            args = args[0]
        for name, xyz in zip('xyz', args):
            if not np.iterable(xyz):
                raise RuntimeError(f'{name} must be a sequence')
        self._verts3d = args
        self.stale = True
```

**from previous version:**
```
    def set_data_3d(self, *args):
        if len(args) == 1:
            self._verts3d = args[0]
        else:
            self._verts3d = args
        self.stale = True
```

### Code for reproduction

```python
e.g.
set_data_3d(0.94, -0.26, 0.22)
```

### Actual outcome

 RuntimeError:  must be a sequence

### Expected outcome

setting new data using set_data_3d

### Matplotlib Version

3.7.1

### Python version

3.10

### Installation

None

**Comment by ksunden** [comment]
This was an intentional change introduced in #22329

The short version is that it was never truly intended behavior that worked by accident.
Setting to scalars was explicitly not allowed at init time, but no such check was done for the update versions of the calls.

A more full discussion can be seen at the above PR, which has a pretty well considered opinions on _why_ this change was made. It is unlikely to change back without a particularly compelling reason.

Recommendation is to do:

```python
set_data_3d([0.94], [-0.26], [0.22])
```

instead, which is compatible with both older and newer versions of mpl.
