### ISSUE TITLE
[Bug]: This code does work properly in windows

### ISSUE THREAD

**Issue by Vinay19742002** [matplotlib/matplotlib#25545]
### Bug summary

![Screenshot (1)](https://user-images.githubusercontent.com/128887255/227701971-c849b261-4ef5-4cd3-8cd7-f2f6c4073e88.png)
This is the output I am getting but in the linux system this code is working properly and also working in ipad .
So please fix it as soon as possible.

### Code for reproduction

```python
import matplotlib.pyplot as plt
from matplotlib.ticker import AutoMinorLocator
hours=[1,2,3,4,5,6,7,8,9,10]
temp=[14,13,12,15,16,17,18,24,29,32]
plt.plot(hours,temp,marker='o',markersize=5,color='r',
         linewidth='1',linestyle='dashed',markeredgecolor='black',markerfacecolor='yellow')
plt.xlabel("Hours")
plt.ylabel("Temp. in Celsius")
plt.title("Hours verses Temperature")
plt.xlim(0,12)
plt.ylim(0,35)
plt.grid(True)
yaxisminor=AutoMinorLocator(10)
plt.axes().yaxis.set_minor_locator(yaxisminor)
plt.axes().yaxis.set_tick_params(which='minor' , left='off' , size= 10)
plt.show()
```

### Actual outcome

![Screenshot (1)](https://user-images.githubusercontent.com/128887255/227702270-ceb7b885-5fa8-4b9e-82e5-37982b9a61d7.png)

### Expected outcome

![Figure_1](https://user-images.githubusercontent.com/128887255/227702404-568a255e-42f5-4ed3-a5e8-700110887c93.png)

### Operating system

Windows

### Matplotlib Version

3.6.3

### Python version

3.9.7

### Installation

pip

**Comment by ksunden** [comment]
I think your problem here is not a windows vs Linux problem (struggling to think of what would be platform specific here)

Looking at your code, you probably want `plt.gca` instead of `plt.axes`.

The former gets the current active Axes, the latter adds a new Axes to the current figure. This explains why there are two different scales (probably it's actually 3, but two of them are identical).

In general, we recommend using the more explicit object oriented api for exactly this kind of reason.

https://matplotlib.org/stable/users/explain/api_interfaces.html

**Comment by rcomer** [comment]
The behaviour that @ksunden describes changed at version 3.4, so my guess is that an older version is installed on the Linux machine.
https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.4.0.html#changes-to-behavior-of-axes-creation-methods-gca-add-axes-add-subplot

**Comment by rcomer** [comment]
I’m going to close this because I do not think it’s a bug in Matplotlib.  But @Vinay19742002 you are welcome to open a question over at https://discourse.matplotlib.org/ if you need more help.
