### ISSUE TITLE
[Doc]: backport strategy: inconsistency in guide

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#25649]
### Documentation Link

https://matplotlib.org/devdocs/devel/coding_guide.html

### Problem

The [milestones](https://matplotlib.org/devdocs/devel/coding_guide.html#milestones) section of the PR guidelines states

> Bugfixes, tests for released code, and docstring changes are milestoned for the next patch release v3.N.M.

which I had assumed means all bugfixes should go to a patch release.  However the [backport](https://matplotlib.org/devdocs/devel/coding_guide.html#backport-strategy) section states

> …(regressions against older releases, bugs/api inconsistencies the user can work around in their code) are on a case-by-case basis…

so not all bugfixes.

### Suggested improvement

The milestones section has been updated recently, which makes me suspect that the backports section is out-of-date and should be updated to match.

**Comment by Higgs32584** [comment]
So our policy on backporting patches is a lot less stringent than before, is that what I am hearing?

**Comment by ksunden** [comment]
The policy is indicating that bugs introduced by the current minor version (eg 3.7 at present) should generally be backported, especially when there is no good way to work around it as a user.

If the bug was introduced by an older release (eg 3.6 or 3.5) and thus has been present for an extended time, then it is not automatic that it should be backported. I think the note about api consistency applies to either long standing inconsistencies (which also fall under the older version provision) but also new APIs such that being inconsistent with other parts of the library is not desirable, but backporting over api changes is not automatic, to be considered case by case.

**Comment by Higgs32584** [comment]
So is this just a quick rewriting of that paragraph?

**Comment by ksunden** [comment]
The line between "bugfix" and "behavior inconsistency that should probably be made more consistent" can sometimes be a bit blurry. Even more so if it used to do what you consider consistent, but hasn't for several releases.

If something is erroring when it shouldn't (or vice versa) it is pretty easy to say "bug", but there are plenty of more subtle behavior changes that aren't quite as clear

**Comment by Higgs32584** [comment]
@ksunden ok so how do we fix this

**Comment by tacaswell** [comment]
One of my favorite XKCD: https://xkcd.com/1172/

As Kyle points out one person's "bug fix" is another's "breaking API change".  A goal of the patch releases should be to only take bugs out and to put no one's in (we do not always succeed, but that is the goal) so there is a judgement call on if the change is "clearly" a bug fix and if we are confident that there will be no other fallout from the change.   

The what

>  If multiple rules apply, choose the first matching from the above list.

is trying to get at.  I'll open a PR trying to clarify it.
