### ISSUE TITLE
[Doc]: Default value for nonpositive parameter is not as documented

### ISSUE THREAD

**Issue by pettza** [matplotlib/matplotlib#25758]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.loglog.html

### Problem

On the docs of the [`loglog`](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.loglog.html) function (probably on similar variants as well), the `nonpositive` parameter is said to have a default value of `'mask'`, however this does not seem to be the case. This is due to the parameter being given a default value of `'clip'` by the `LogScale` class.

### Suggested improvement

Well either the documentation should change to reflect the implementation or vice versa. In my opinion the first option is better since it would not affect existing code and it would match the documentation of the [`LogScale`](https://matplotlib.org/stable/api/scale_api.html#matplotlib.scale.LogScale) class which is correct.

**Comment by ksunden** [comment]
The incorrect value stems from here:

https://github.com/matplotlib/matplotlib/blob/b3bd929cf07ea35479fded8f739126ccc39edd6d/lib/matplotlib/axes/_axes.py#L1809

Documentation should probably change to match implementation, as that will not result in a behavior change.

Marking as Good First issue and Easy, because it is a matter of updating the docstring without any change in behavior
