### ISSUE TITLE
All values are on plot labels

### ISSUE THREAD

**Issue by mhd-fauzan** [matplotlib/matplotlib#25816]
### Bug summary

I created a plot from a csv file. In the csv file there are Frequency and dBSPL values whose total values are more than 1000 lines. When I run the code and the plot is displayed. But the plot is not as expected, the values of frequency and dBSPL are on the x and y axes. I want that value to be shown in the plot line.

### Code for reproduction

```python
import pandas as pd
import matplotlib.pyplot as plt


class csv2df():
    
    def __init__(self):
        self.df = pd.read_csv("RMS level.csv")
        self.sheet = self.df[3:]
        
    def plot(self):
        self.x = self.sheet["RMS Level"]
        self.y = self.sheet["Unnamed: 1"]
        plt.plot(self.x, self.y)
        plt.xlabel("Frequency (Hz)")
        plt.ylabel("dBSPL")
        
        plt.show()
        
data = csv2df()
data.plot()
```

### Actual outcome

![Figure 2023-05-05 100154](https://user-images.githubusercontent.com/126536526/236369363-d82bfd79-f2f6-45b5-b0f5-d9dd6b3faad3.png)

### Expected outcome

I want that value to be displayed in the plot line. more or less like the picture below. 
![image](https://user-images.githubusercontent.com/126536526/236369642-7fdc8ce4-486d-4e1d-aac5-bfa33be55aee.png)
NOTE : In the picture above there are 2 plot lines because there are 2 channels. It's different from my csv file which only has 1 channel

### Additional information

- I don't know why this bug occurs.
- I don't know how to fix it.

### Operating system

Windows

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.10.10

### Installation

conda

**Comment by ksunden** [comment]
This is most likely due to the values being interpreted as strings rather than numbers.

Probably, you need to tell pandas about the header of the csv: https://pandas.pydata.org/docs/user_guide/io.html#column-and-index-locations-and-names (in particular the `header` and `skiprows` arguments to `read_csv`)

It looks like you skip the first three lines of the csv, you may need to tell pandas to do that. That way pandas can properly interpret the data as numbers

I don't know what your csv actually looks like, but assuming there are two rows of not useful info followed by the actual header it would look something like:

```python
pd.read_csv("RMS level.csv", header=2)
```

Or if the header is the first line and the skipped lines are following:

```python
pd.read_csv("RMS level.csv", skip_rows=[1,2])
```

(to be clear, I don't have your data and do not _know_ that either of these are correct, but hopefully it sets you down the right track, at least)

More info on what is happening on our end (which I'm ~90% sure is a knock on effect of the way you read in your data to pandas): 

https://matplotlib.org/stable/users/faq/howto_faq.html#why-do-i-have-so-many-ticks-and-or-why-are-they-out-of-order

I'm going to close this issue because I'm pretty sure this is what is happening, and there is no action to take on our end if so.

**Comment by mhd-fauzan** [comment]
If I send my csv data can you help me to solve this problem? i am very difficult for this problem.

**Comment by rcomer** [comment]
@mhd-fauzan you are welcome to open a question over at https://discourse.matplotlib.org/ if you need more help.
