### ISSUE TITLE
[Bug]: Plot 3d vector 

### ISSUE THREAD

**Issue by Abner228** [matplotlib/matplotlib#25869]
### Bug summary

I plot a 3d vector [1,1,-1],  and set view_init(elev=-45, azim=45), why the vector don't look as a point in the view? 

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np


fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")
ax.view_init(elev=-45, azim=45)

point_2d_x = np.arange(0, 11, 1)
point_2d_y = np.arange(0, 11, 1)

point_2d_x, point_2d_y = np.meshgrid(point_2d_x, point_2d_y)
point_2d_z = - point_2d_x

point_2d_x = point_2d_x[np.eye(11) == 1]
point_2d_y = point_2d_y[np.eye(11) == 1]
point_2d_z = point_2d_z[np.eye(11) == 1]


ax.scatter(point_2d_x, point_2d_y, point_2d_z, c='g', marker='^')

ax.set_xlabel('X label')
ax.set_ylabel('Y label')
ax.set_zlabel('Z label')

plt.show()
```

### Actual outcome

![vet](https://github.com/matplotlib/matplotlib/assets/37471983/8ce54807-d372-4f5a-ac3c-9cbf25ac3ece)

### Expected outcome

look as a point in this angle

### Matplotlib Version

3.4.2

### Matplotlib Backend

module://backend_interagg

### Python version

Python 3.8.10

### Installation

pip

**Comment by tacaswell** [comment]
The angle that is "head on" should be ~35.2deg (`np.arctan(1/np.sqrt(2))`), The length of the perpendicular from the plane to the vector is 10 and the length of the projection of the vector onto the plane is `10*sqrt(2)`, thus the angle must be `tan(phi) = 1/sqrt(2)`.

However setting the angle correct is still not quite enough because the default aspect ratio is not 1:1:1 so the angles will be distorted.

```python
import matplotlib.pyplot as plt
import numpy as np


fig = plt.figure()
ax = fig.add_subplot(111, projection="3d")
ax.view_init(elev=-35.2, azim=45)

ax.scatter(np.arange(0, 11), np.arange(0, 11), -np.arange(0, 11), c='g', marker='^')

ax.set_xlabel('X label')
ax.set_ylabel('Y label')
ax.set_zlabel('Z label')
ax.set_aspect('equal')  # needs mpl 3.6
ax.set_proj_type('ortho')
plt.show()

```

![so](https://github.com/matplotlib/matplotlib/assets/199813/28916431-128f-4c71-9cb1-9d6ed9cf562e)


However the equal aspect ratio requires a newer version of Matplotlib than you are using.

**Comment by Abner228** [comment]
Thank you for your quick and detailed reply!
It helps a lot:)
