### ISSUE TITLE
Make `TexManager.texcache` private

### ISSUE THREAD

**Issue by oscargus** [matplotlib/matplotlib#25942]
(Original issue below the line)

As suggested below, it makes sense to make `texcache` private, which need to go through a deprecation cycle. See https://matplotlib.org/stable/devel/contributing.html#api-changes for a more detailed description of what is required in terms of deprecating something. Also, see the helper function `deprecate_privatize_attribute` and how it is used in the code base.

Marking as good first issue since there is a minor, well-defined, change. But it may require a bit of reading up to get it right.

---

### Documentation Link

https://matplotlib.org/stable/api/texmanager_api.html

### Problem

texcache = '/home/elliott/.cache/matplotlib/tex.cache'

### Suggested improvement

Not a big deal, but maybe one can at least add a doc-string stating that is points to `$HOME/.cache/matplotlib/tex.cache` or however it is actually determined.

**Comment by anntzer** [comment]
I would make texcache private and just document that things are cached in a subdirectory of get_cache_dir() (the caching uses an undocumented hash of the string contents so it's not "really" third-party readable anyways).

**Comment by timhoffm** [comment]
IMHO this could be improved a bit in formatting and wording (suggestion below). Not sure whether you can work around the wrapping issue. If nothing else works, you could read the content from a file using `body-path` (https://github.com/peter-evans/create-or-update-comment#action-inputs).

Suggested output:

---

### Good first issue - notes for new contibutors

This issue is well suited as a first contribution to Matplotlib. Please see [our Contributing guide](https://matplotlib.org/stable/devel/index) for how to get started.

**We do not formally assign issues**. If there is no open pull request (PR) for this issue (link would be in the timeline above), feel free to start working on this. If there is already a PR, please do not open concurrent ones to prevent duplicate work.

Do not hesitate to ask if something needs clarification - see also [our different communication channels](https://matplotlib.org/stable/devel/contributing.html#get-connected).

**Comment by timhoffm** [comment]
Sorry, my comment should have been in 
#25735.
