### ISSUE TITLE
[Doc]: Subfigures still marked as provisional

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#25947]
### Documentation Link

https://matplotlib.org/stable/gallery/subplots_axes_and_figures/subfigures.html#figure-subfigures

### Problem

![image](https://github.com/matplotlib/matplotlib/assets/2836374/9b75858c-cc13-40b7-9f4e-3f4bef2b777d)

### Suggested improvement

Have we made that API official yet?

- If not, let's do this. It's been out for 3 minor releases without complaint.
- If yes, simply delete the note.

**Comment by rcomer** [comment]
I think it might be good to resolve #25511 first.  As I note in my comment on the end of that issue, the expected behaviour according to the tests seems to be incompatible with the documented behaviour with respect to the _wspace_ and _hspace_ parameters.

Also we have a change to a default parameter coming without prior warning in v3.8 #25255

**Comment by timhoffm** [comment]
Should we make this stable in 3.10?
