### ISSUE TITLE
[ENH]: Add SOME way of making subplots without knowing their total number beforehand

### ISSUE THREAD

**Issue by User087** [matplotlib/matplotlib#26097]
### Problem

Is there any prospect of adding some high-level methods that would simply allow adding subplots to a figure without implicitly having to know the total number of subplots to be plotted and specify their exact layout in advance?
This issue is closely related to the request for a way to dynamically make new subplots on the fly, the lack of which has been another plight for some time. Methods of solving that, including the common hack using gridspec and set_subplotspec to reposition all the axes each time you add a new plot, would probably solve the issue at hand too as they obviously don’t require knowing the number of subplots beforehand.

This issue is more general though and I would expect it has a wider range of solutions, but currently the only workaround I can think of (but haven’t tried yet) would be to make a figure and then continuously add subplots using `ax = fig.add_subplot()` to the same default position (1, 1, 1), and then iterate through `fig.axes()` at the end, using gridspec and set_subplotspec to rearrange the plots, similar to the above hack for dynamic plotting.

If you want an example use case that would give rise to this issue, imagine you have multiple data sets which you are about to process.
1. The processing involves splitting and merging datasets, and plotting whatever datasets fulfil a bunch of nested if statements, the number of which you have no idea.
2. These datasets get plotted using various different types of plots (and hence using different matplotlib methods) depending on which if statements they fulfil, there being more possible types than you care to count.
3. The datasets are processed in a loop that reassigns the same variables in each iteration and you don’t want to retain much data in memory after each iteration.

(1) means that it’s not simply a case of calculating the size of your dataframe or whatever to know the number of plots (a common theme in examples) – the conditional logic means you really only know how many plots you’ve got after you go through it. (2) does away with any [idea of storing the parameters of each plot in a dictionary and all dictionaries in a list](https://stackoverflow.com/questions/58662494/matplotlibs-subplots-actual-number-of-subplots-unknown-in-advance#comment103628951_58662494) to go through after you've figured out exactly what your plotting, as you don’t even know which plotting method you’re going to use and it’s not feasible to make a custom map by which to identify them, besides the clunkiness involved when you’ve got a lot of axis options you want to configure. (3) makes it undesirable anyway to be retaining anything in memory beyond what’s necessary for the plot itself and any derived quantities etc you want to keep.

### Proposed solution

The problem might lie with axes being inseparably tied since their formation to figures, and there being no trivial way to adjust the size and layout of a figure after its formation. One possible solution might therefore lie in adding the ability to make axes independent of figures, configure all axes-specific options and then add them to figures using `fig.add_subplot()`. Another would be if new subplots can be added using knowledge of only the current number of axes, so something like `fig.add_subplot(len(fig.axes)+1, 1, len(fig.axes)+1)` to add a new subplot on the end of a single column of plots, upon running of which the size and other necessary components of the figure are automatically adjusted in the background without the user having to do that manually. The latter could also solve the dynamic plotting issue.

I’m guessing modifying the inner workings of matplotlib.figure would yield an optimal solution for this, but even a native wrapper around the gridspec and set_subplotspec technique could at least save beginners significant time and effort for what doesn’t appear to be a particularly advanced task worth getting stuck on: simply adding subplots without knowing their total number from the outset.

**Comment by tacaswell** [comment]
There is enough public API to do this currently, if a bit awkwardly.  There was some recent discussion in the gitter channel about this and in response I wrote up https://tacaswell.github.io/dynamic-axes-count.html which wraps the gridspec manipulation in a (maybe too) cute generator.  It would not be too hard to adapt that to be a class.

The source of the problem here is not that the internals of the Figure / Axes mechanism are too tightly coupled, it is that they are too loosely coupled.  The Figure is not responsible for laying out the Axes, the Axes are in charge of placing them selves where ever they want in the Figure (tight layout / constrained layout look like they are Figure level things, but they work by looking at (some) of the Axes in the Figure, working out where they ought to be, setting that state back into the Axes).  

You can currently add Axes at arbitrary fixed locations (https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.add_axes), if you use gridsec directly as in the second example in https://matplotlib.org/stable/gallery/userdemo/demo_gridspec03.html#gridspec-demo , you do anything with `subplot_mosaic`, or use the tools in mpl_toolkits.axis_grid (e.g. https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.axes_grid1.axes_divider.AxesDivider.html#mpl_toolkits.axes_grid1.axes_divider.AxesDivider) it becomes super unclear what any `Figure` level "add another Axes" should do.  Put another way, due to the flexibility with which you can already control the axes, putting something at the top level that "does the right thing" is best case super complex worst case we can not agree on what "the right thing" even is.

As with #25971 (which was focused on still a fixed number, but paraterizing the layout differently) I think the best path forward here is for someone who has a need for this functionality to start a new package that provides a manager class (or generator 😈 ) to provide this functionality.  If it gets traction then we can talk about moving it to the matplotlib org or merging it into the core library. We recently factored out draw-time layout into pluggable API (https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.6.0.html#new-layout-engine-module) to support exactly this sort of application.

-----

If you go with the class design I am thinking something like:

```python

fig = plt.figure()
#    or
# fig = other_fig.add_subfigure(...)
manager = ReflowManager(fig, ...)  
for j in count():
    ax = manager.add_axes(...)
    ...

fig.savefig(...)
# plt.show()

```

Design decisions to make:

 - how to you control the aspect ratio of the generated ?  Fixed at init-time, follow the shape of the figure, have a target (on screen) aspect ratio of the Axes?
 - even sized rows or staggered rows (e.g. grid-strategy)
 - should the manager be allow to resize the Figure? if yes, make bigger and smaller or only bigger?
 - how to manage shared x/y axes?
 - how do you manage automatically removing ticks and axis labels (if you want to support shared axis) 
 - how to thread through all of the Axes creation parameters?
 - can you remove an Axes?
 - can you only add a new Axes "at the end" or can you inject them into the middle / front?
 - which of these choices is set at `__init__` time and which are mutable?
 - What are good default values / settings?
 - if you go with grid, where should the empty spaces go (leave off of last row, leave off of last column, the corners, the middle (ok that might be a silly option), ...)?
 - do you want to use a layout manager (so the Axes may get moved automatically on every draw) or only update the layout when new Axes are added?

If pressed I could probably come up with snap answers for all these, but I think that an actual implementation is needed to validate all of them 🤣 and we need to get that implementation in front of a bunch of users who actually have this need (rather than our current regular contributor pool which judging by no one jumping on this in the past suggests don't regularly have this need in their work).


Doing this work in a new project has the advantages that because it is new you can clearly message that the API is unstable and be more aggressive about trying different things (our recent experimental / provisional APIs have been pretty thoroughly reviewed up front and marked as provisional just in case real-world usage found major design flaws) and then breaking it.  It also means releases can be done on your own schedule (I suspect this project would be pure-Python and hence perfect for all of the workflow automation push-to-pypi-from-gha tools) as rapidly as makes sense (where as mpl releases are best case every 6mo).


https://github.com/matplotlib/matplotlib-extension-cookiecutter may be useful to get started.

------


prior art to look it:

-  https://matplotlib.org/stable/api/_as_gen/mpl_toolkits.axes_grid1.axes_divider.html
- https://tacaswell.github.io/dynamic-axes-count.html 
- https://matplotlib.org/stable/api/layout_engine_api.html
- https://proplot.readthedocs.io/en/stable/
- https://github.com/matplotlib/grid-strategy

**Comment by tacaswell** [comment]
I am inclined to close this issue as this is not something I think we want to get PRs starting to implement in the core library until there is a good example of this in a third-party package.

**Comment by jklymak** [comment]
Strongly agree - I think there is adequate levers to make this a third party package, and I'm skeptical something like this should go in core.  If there are not adequate levels, happy to reconsider.
