### ISSUE TITLE
[Doc]: navigating to the User Guide

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#26156]
### Problem

This may already be in hand but...

The top level doc page currently looks like this:
https://matplotlib.org/devdocs/index.html

If I click "User Guide" in the top panel, I get this, whose panels have a very similar set of links to the top level page:
https://matplotlib.org/devdocs/users/index.html

To get to the actual User Guide, I have to click something in the top right panel of the above user guide page.  Then I get this:
https://matplotlib.org/devdocs/users/explain/index.html

### Suggested improvement

I think the four panels from the second link above could replace the four panels at the first link.  The "User Guide" link in the top panel could take you straight to the third link.

**Comment by jklymak** [comment]
The problem is that user/index is actually the top level index for the whole site according to sphinx.  It would be ideal to just restructure so the top level page is the index for the whole site, perhaps with hidden TOC if we don't like the current ones.  We could hide on the user/index as well, but if we are rearranging we should consider making it more standard. I don't remember the technical reason we don't do that.

**Comment by gracejiang16** [comment]
Hey, could I give this a try?

**Comment by jklymak** [comment]
@gracejiang16 thanks for being willing to help but this is probably better handled by someone who has been with the project for a while. Further we are not really sure we know how to proceed. I'd cJ pose something less likely to be controversial.

**Comment by AdityaSrivastava185** [comment]
I think that we can add a new link or button at the top right corner of the page and  should remove the other "user guide" link from the top as its navigating use to wrong user-guide page. We can also highlight the link for the attention of the user , so that user can easily navigate to the page
