### ISSUE TITLE
WebAgg for multiple clients

### ISSUE THREAD

**Issue by bmu** [matplotlib/matplotlib#2620]
I just integrated the webagg backend in a tornado application to visualize some data.

However the problem is, that a user on one client can manipulate the figures on another client. Maybe this is a problem of my application, but I think it would be awesome if you could really integrate the webagg backend in a multi client application.

I would like to implement something to separate this, e.g. creating a new figure for every request and using a separate websocket for every client, however I a not sure how to do this.

Do you have any ideas?

**Comment by raphaelquast** [comment]
Recently I wanted to create a multi-client webagg server and even though this issue is ~10 years old, it was the only helpful source of information I could find...

The good thing is that it was enough to get things started and now I have a working example for a multi-client setup!
(e.g. a server that spawns a new figure + websocket on each get request)

In case anyone is still interested, let me know!

**Comment by tacaswell** [comment]
@raphaelquast could you share a reference?

I also have a very rough prototype of serving mpl figures via fastAPI https://github.com/tacaswell/matplotlib-fastapi
