### ISSUE TITLE
[Bug]: return value of `plt.isinteractive()` changes after creating a figure in jupyter notebooks

### ISSUE THREAD

**Issue by raphaelquast** [matplotlib/matplotlib#26221]
### Bug summary

While trying to address issues with jupyter-notebook inline plotting in [eomaps](), I've realized that the return value of `plt.isinteractive()` somehow always changes to `True` after the first figure is created (even if `plt.ioff()` is explicitly called)...

### Code for reproduction

```python
# run the following lines in a cell of a jupyter notebook
import matplotlib.pyplot as plt
print("matplotlib is interactive:", plt.isinteractive())
# even explicitly calling plt.ioff() does not help here!
f, ax = plt.subplots()
print("matplotlib is interactive:", plt.isinteractive())
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/22773387/9f9fe091-40d7-49e6-926f-4dce96426b6e)

### Expected outcome

I expected `plt.isinteractive()` to return if the currently used backend is interactive on import (and that this value does not change after creating a figure)

### Additional information

If the backend is explicitly switched to the current backend, the interactivity is still changed to `True`, but afterwards all works as expected...
```python
import matplotlib.pyplot as plt
print("matplotlib is interactive:", plt.isinteractive())
plt.switch_backend(plt.get_backend())
print("matplotlib is interactive:", plt.isinteractive())
plt.ioff()
f, ax = plt.subplots()
print("matplotlib is interactive:", plt.isinteractive())
```

![image](https://github.com/matplotlib/matplotlib/assets/22773387/ffa93a9f-5b7f-480c-a17a-bed2993e2aa8)

### Operating system

Windows

### Matplotlib Version

3.7.1

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.11.3

### Jupyter version

4.0.2

### Installation

conda

**Comment by ksunden** [comment]
The inline backend is actually provided by IPython/maintained outside of matplotlib itself, so I don't think there is anything we can do here.

That said, here is some more info that may be useful:

The cause is is [this line](https://github.com/ipython/matplotlib-inline/blob/fbf0ab8f2d81993ff8e319a003f58896c77f2443/matplotlib_inline/backend_inline.py#L217) from matplotlib-inline, which then calls into IPython where [this line](https://github.com/ipython/ipython/blob/c3d7f161b19ddb3c16120487b0797539568c2c0f/IPython/core/pylabtools.py#L348) is what actually sets interactive to be True.

It's not clear to me immediately what the difference between interactive True and False _is_ for the inline backend (and to some extent any backend in Jupyter), though... there is no "wait for the figure to be closed to continue execution of python" which is one of the more prominent features of `interactive=False` in other backends. You also can't add to an existing plot from another cell with inline... it just outputs a png and is done, no updating later...

I guess the difference is whether plots show up automatically upon execution of the cell in which they are defined or if an explicit `plt.show()` must be called, which is fair.

I guess my suggestion short term would be to explicitly set the backend first _then_ call `plt.ioff()`. 

(The problem with the first call doing it is that the backend is loaded lazily, which kind of has to be the case for a variety of reasons, most notably that changing between gui backends is not possible, so if we fully loaded the backend before plotting, it would be impossible to change that.)

I'm going to close here as there is no action to be taken on our end, please report to IPython/matplotlib-inline.

**Comment by raphaelquast** [comment]
@ksunden thanks a lot for the detailed explanations!
I'll try to discuss this with the ipython team then. 

Just one quick question though... 

Is it OK to use the following line to make sure that the currently set backend is fully loaded or is there a better way?

```python
plt.switch_backend(plt.get_backend())
```

**Comment by tacaswell** [comment]
`plt.install_repl_displayhook()` is probably the most reliably way to fully load and lock in the backend.

**Comment by raphaelquast** [comment]
@tacaswell Thanks!
