### ISSUE TITLE
[ENH]:  Is it possible to add scientific colorbar 

### ISSUE THREAD

**Issue by mohseniaref** [matplotlib/matplotlib#26241]
### Problem

I have difficulty to add according https://www.nature.com/articles/s41467-020-19160-7 scientific colorbar in matplotlib and i hesitate to use package https://pypi.org/project/cmcrameri/ , is there any solution add it as part of Matplotlib

### Proposed solution

I think  here can be modified https://github.com/matplotlib/matplotlib/blob/f017315dd5e56c367e43fc7458fd0ed5fd9482a2/lib/matplotlib/_cm.py#L1416

**Comment by tacaswell** [comment]
I am not sure what you are proposing.  As noted in the linked paper we ship with viridis, plasma, inferno, and magma (which are continuous sequential and perceptually uniform) and the default colormap is viridis.  We now also ship cividis.  See https://matplotlib.org/stable/tutorials/colors/colormaps.html for lots of details about what we ship, including links to https://matplotlib.org/mpl-third-party/#colormaps-and-styles .  

We are unlikely to remove or change any existing color maps (due to our back-compatibility commitments), so if you are proposing to change or remove jet that is not really on the table.

We have a very high bar for adding new colourmaps.  It would rapidly become unwieldy if we took every proposed (and technically sound) colourmap. 
Past some base level of "should be uniform" (and there is more than one way to compute that) there is a degree of aesthetics and it is not a good use of time for Matplotlib to moderate the discussion over the naming and exact end points of N very similar but different colormaps.

That there is a package that provide the crameri colourmaps is in my view the best situation as they are readily available to anyone who prefers them over the colourmaps we ship (or are available in colorcet, cmasher, cmocean, ...).

**Comment by mohseniaref** [comment]
Thanks for the input, @tacaswell. I agree with your concerns, and at the same time, I also want to highlight @hannah's point about the importance of divergent colormaps.

These days, scientific colormaps like those provided by `cmcrameri` are gaining traction in the academic community. While adding an additional dependency is a consideration, we must weigh this against the benefits of a unified colormap dictionary.

Having both Matplotlib and `cmcrameri` colormaps in one dictionary could greatly simplify code for researchers, making it easier to switch between different colorbars. This would make the adoption of scientifically beneficial colormaps like those in `cmcrameri` smoother for Matplotlib users.

Let's think about how we could make this possible without overly complicating the user experience or creating unnecessary dependencies.

**Comment by mohseniaref** [comment]
Thanks for your prompt response, @story645!

I understand from the documentation that the `cmcrameri` colormaps should automatically register with `matplotlib` upon import, enabling their usage in the same way as built-in colormaps. For example, like so:

```python
plt.scatter(x, y, c=y, cmap='roma')

**Comment by mohseniaref** [comment]
I am surprised @story645  ! So the next question is why they didn't replace it instead of cmc.roma with simply 'roma' ?! Is there any way that we can fix it?
