### ISSUE TITLE
[ENH]: Array-like input for `plt.text` is needed

### ISSUE THREAD

**Issue by Social-Mean** [matplotlib/matplotlib#26296]
### Problem

I use `plt.text` to annotate tags of triangles and nodes like figure below:

![图片](https://github.com/matplotlib/matplotlib/assets/84260049/15d990ac-6ca3-4964-a2fd-db69aa8a1c67)

`plt.text` only takes one `x`, one `y` and one `text` at a time. This is:

1. inconvenient to use because a loop is needed for array-like data, 
2. and inefficient when numerous tags are needed to be tagged.

I use PyCharm to profile `plt.text` when facing numerous tags, and find `set_text` and `_get_layout` cost a long time.

![图片](https://github.com/matplotlib/matplotlib/assets/84260049/31a490be-81d3-44d3-8375-b418ed980bd4)

I suppose Matplotlib read-in current figure and almost re-draw a new figure at each time I call `plt.text`. This is obviously inefficient.

### Proposed solution

Array-like input is needed. The ideal call case is like:

```python
x_arr = [1, 2, 3, 4, 5]
y_arr = [1, 2, 3, 4, 5]
text_arr = ["a", "b", "c", "d", "e"]

plt.text(x_arr, y_arr, text_arr)
```

The expected result is:

![图片](https://github.com/matplotlib/matplotlib/assets/84260049/1faa7052-da07-46e1-aeb4-3fa5b27a9016)

This is easier to use and more efficient (maybe) in numerous data because only one time to read-in the old figure and re-draw a new figure.

Thanks! :smile

**Comment by jklymak** [comment]
```python
for x, y, t in zip(x_arr, y_arr, text_arr):
  text(x, y, t)
```
is not very inconvenient.  We are unlikely to write a C wrapper for something so niche, so there would likely be no speedup from us bringing the for-loop inside text, and considerable additional API burden.  The above is also more convenient as you can have other properties be different for each text call (rotation, color, fontsize).

**Comment by jklymak** [comment]
`annotate` is an arrow + text.  `text` is just the text.  

I don't think there is a practical need to put thousands of strings on an axes (versus thousands of markers), so I don't think there is a real need to vectorize `text`.

**Comment by jklymak** [comment]
Do any of those examples have "thousands of strings"?    From a practical point of view, a for-loop is going to be plenty fast for any of those examples.

**Comment by ksunden** [comment]
https://www.hockeyviz.com/xG/2223/

Here is another example (that does use mpl).

Yes, "thousands" is perhaps not quite right, but I would tend to say yes, things that are plotted  as data are perhaps appropriate. This example (and the site as a whole, actually) is one of the use cases I have in mind for some of the data-prototype work.

**Comment by jklymak** [comment]
I don't have _any_ objection to the original use case, or plotting strings as data - the examples are appreciated, but I am well-aware of the use case, and have even used it myself.  

I'm just pointing out that a) it is _easily_ achievable with the current API, and b) that there is unlikely to be much performance gain given the small number of strings a person viewing the visualization can parse.  

All the examples above re-inforce that, as they all have finite number of strings (<50).  

Shoehorning the `ax.text` API to make the examples above would be almost impossible.  You would need to start accepting lists for all the text properties (color, fontsize, fontfamily, fontstyle, fontweight, rotation, bbox color).  Further, the returned object would need to change to at least be a list of `Text` objects, rather than a single object.  I don't think either of those are reasonable proposals.  

If someone wanted to write `ax.textscatter` or `ax.scattertext` that did this, I wouldn't object.  But my expectation is that it would just be implemented as a for-loop.  So a bit of convenience for an API that would end up being very expansive, but I wouldn't expect a performance gain.

**Comment by anntzer** [comment]
FWIW I am rather dubious that there would be any real performance gain from vectorization here, but I'd be happy to be proven wrong.

**Comment by tacaswell** [comment]
I think that many of those examples need something more sophisticated than just "can pass an array of x, y, and text to `ax.text`".  In the plot from https://github.com/matplotlib/matplotlib/issues/26296#issue-1800525371 it looks like there is at least two different sets of text, a scatter, and a bunch of lines all of which need to placed at the same positions (with maybe offsets) so a helper function that creates artists for all of them is probably the right thing to do (e.g. like networkx's plotting methods).

Similarly, in almost all of the examples above there is more complex things going on than just putting text (styled) text at a location (arrows, interactions between the text etc) that would strongly suggest a user / domain specific helper function is needed anyway.



I agree with Antony, if we just do the for-loop for the user and still create `N` `Text` objects I would expect negligable speed ups.  If someone were to write a `TextCollection` (which I could have sworn we have talked about but could not find), we might see some speed ups as we could have a `for stuff in self._iterate_parts(): renderer.draw_text(*stuff)` and save the cost of creating many Python objects.   If we were going to consider that I would like to see a functioning prototype first.

I am going to close this issue for now as I do not think we want to attract any work on this at this time.  Making it easy to write this sort of broadcasting `Artist` is solidly in @ksunden 's remit, I will create an issue on data-prototype to track this use-case.

**Comment by jklymak** [comment]
> If someone were to write a TextCollection (which I could have sworn we have talked about but could not find), we might see some speed ups as we could have a for stuff in self._iterate_parts(): renderer.draw_text(*stuff) 

I think maybe in the context of Ticks?  https://github.com/matplotlib/matplotlib/issues/5665?

**Comment by jklymak** [comment]
>  but then I honestly really really question what's the purpose of text separate from annotation.

Annotation does labelled arrows.  Otherwise I agree that it would have no point.  

> does the function handle the bookkeeping or is the user handling the bookkeeping?

For all but the simplest case, the user has to do bookkeeping no matter what.  Making a big list of text properties to pass to this proposed function is going to require a for-loop _anyways_, and require extra memory to and time to create the lists.  I can imagine that in most cases this would be _less_ convenient than calling `text` N times.

**Comment by tacaswell** [comment]
A minimal "auto broadcaster" looks something like

```python
import matplotlib.pyplot as plt
from itertools import cycle
import cycler


def broadcast(func, *args, **kwargs):
    return [
        func(*largs, **lkwargs)
        for largs, lkwargs in zip(
            zip(*args) if args else cycle([()]),
            cycler.cycler(**kwargs) if kwargs else cycle([{}]),
        )
    ]


broadcast(
    plt.gca().text,
    [0.5, 0.1, 0.8],
    [0.3, 0.1, 0.5],
    s=["hi", "bob", "bill"],
    color=["r", "g", "b"],
)

```

This simplifies the problem a bit by not up-casting scalar values which if we were to put this is in the library we would probably want to do (I think it is tractable, just annoying and full of edge cases).   This might be worth finishing, documenting, testing, and putting in `cbook`?  On the other hand it is basically a (fancy) list comprehension and it is not obvious to me that using a simpler list comprehension would not be easier for the users. 


----
@Social-Mean 

> I suppose Matplotlib read-in current figure and almost re-draw a new figure at each time I call plt.text. This is obviously inefficient.


That is not quite the correct mental model of how Matplotlib works.  We should only be drawing when you actually ask for a rendering, otherwise we are mostly building up state in Python (`plt.XYZ` are a secondary API, the primary API is the `Axes` methods).  I am not sure exactly what you are profiling there, but it may be the case that pycharm's backend is rendering the figure too often or you just have a lot of text (and text is expensive to render).

-----

@story645 I think the best way to convince (at least) me that is is a good idea is for you to implement a `TextCollection` artist and a paired method on `Axes`.  Without a working prototype to drive the conversation we are just going to go in circles.

**Comment by Social-Mean** [comment]
@tacaswell 
> That is not quite the correct mental model of how Matplotlib works. We should only be drawing when you actually ask for a rendering, otherwise we are mostly building up state in Python (plt.XYZ are a secondary API, the primary API is the Axes methods).

You are right. I re-profile it and find the rendering is the most time-consuming. However, the time-consuming of `text` cannot be ignored. When `text` 1000 texts, `text` cost 20% of time while rendering cost 80%.

@jklymak 

> ```python
> for x, y, t in zip(x_arr, y_arr, text_arr):
>   text(x, y, t)
> ```

I don't really care about the convenience, because the code you give is convenient enough. My main concern is efficiency.

The source code of `axes.text` is:
```python
def text(self, x, y, s, fontdict=None, **kwargs):
    effective_kwargs = {
            'verticalalignment': 'baseline',
            'horizontalalignment': 'left',
            'transform': self.transData,
            'clip_on': False,
            **(fontdict if fontdict is not None else {}),
            **kwargs,
    }
    t = mtext.Text(x, y, text=s, **effective_kwargs)
        if t.get_clip_path() is None:
            t.set_clip_path(self.patch)
        self._add_text(t)
        return t
```

Each time I call `axes.text`, a `matplotlib.text.Text` instance will be created.

> Shoehorning the ax.text API to make the examples above would be almost impossible. You would need to start accepting lists for all the text properties (color, fontsize, fontfamily, fontstyle, fontweight, rotation, bbox color). Further, the returned object would need to change to at least be a list of Text objects, rather than a single object. I don't think either of those are reasonable proposals.

I agree with @jklymak. This new feature is really hard to implement.

**Comment by pauljurczak** [comment]
Here is my use case in image processing, where I need thousands of similar text labels:

<img width="1106" height="1124" alt="Image" src="https://github.com/user-attachments/assets/b9f75cac-50a6-41c8-b867-ef9f53a2c9db" />


Would use of TextCollection instead of many thousand calls to `ax.text()` have a potential to speed things up?

**Comment by story645** [comment]
> Would use of TextCollection instead of many thousand calls to ax.text() have a potential to speed things up?

TextCollection doesn't exist. The suggestion was implement a new `TextCollection` artist, and then use that under the hood of `ax.text` to make an ax.text that supports a list of inputs.

**Comment by pauljurczak** [comment]
Yes, I understand that. I added another reason to implement it in the future, if possible.
