### ISSUE TITLE
[Bug]: quiverkey shows multiple arrows under geographical projection and angle='xy'

### ISSUE THREAD

**Issue by xlucn** [matplotlib/matplotlib#26316]
### Bug summary

When I plot quiverkey with subplot option `projection='aitoff'` and quiver option `angle='xy'`, the quiverkey is then showing multiple arrows pointing at different directions.

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(-np.pi, np.pi, 11)
y = np.ones_like(x) * np.pi / 6
vx = np.zeros_like(x)
vy = np.ones_like(x)

fig = plt.figure()
ax = fig.add_subplot(projection='aitoff')
q = ax.quiver(x, y, vx, vy, angles='xy')
ax.quiverkey(q, 0, 0, 1, '1 units')
ax.grid()
plt.show()
```

### Actual outcome

![quiver_anglexy](https://github.com/matplotlib/matplotlib/assets/12032219/12a0c7dc-61f5-448b-a5f4-c5a6d9d8987f)

### Expected outcome

I naturally expect the quiverkey to be as in the image below, with the default `angle='uv'` option:

![quiver_angleuv](https://github.com/matplotlib/matplotlib/assets/12032219/ad52b270-5f0e-45f9-a033-1cacdf1895c6)

### Operating system

Arch Linux

### Matplotlib Version

3.7.1

### Matplotlib Backend

QtAgg

### Python version

Python 3.11.3

### Installation

Linux package manager

**Comment by stevezhang1999** [comment]
This can be reproduced when using mpl=3.7.2 and mpl=3.9.0dev

**Comment by stevezhang1999** [comment]
I think something is wrong in `QuiverKey._init()`, which will curate the wrong `QuiverKey.vector` to be `draw()`:
<img width="571" alt="image" src="https://github.com/matplotlib/matplotlib/assets/38875181/3aa0a668-7519-4b65-8134-15b06d312d9a">


The culprit may be in `_make_verts`
```
angle = (self.Q.angles if isinstance(self.Q.angles, str)
                         else 'uv')
self.verts = self.Q._make_verts(
    np.array([u]), np.array([v]), angle)
```

Script to reproduce the figure:
```
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl

x = np.linspace(-np.pi, np.pi, 11)
y = np.ones_like(x) * np.pi / 6
vx = np.zeros_like(x)
vy = np.ones_like(x)

fig = plt.figure()
ax = fig.add_subplot(projection='aitoff')
q = ax.quiver(x, y, vx, vy, angles='xy')
ax.quiverkey(q, 0, 0, 1, '1 units')

qk = ax.get_children()[1]
qk._init()

print(qk.vector._paths)
paths = qk.vector._paths

fig, ax = plt.subplots()

for path in paths: # 12 paths here!
    p = patches.PathPatch(path, facecolor='yellow',
                              edgecolor='red', alpha=0.5, lw=10) # make lw larger may see more things
    ax.add_patch(p)

ax.set_xlim(-2, 2)
ax.set_ylim(-2, 2)
plt.show()
```

**Comment by stevezhang1999** [comment]
Things break when we are calling
```
 angles, lengths = self._angles_lengths(U, V, eps=…)
```
We are only calling this when we are trying adding a quiver key to a quiver with angles=“xy”
The bug happens because`quiver._angles_lengths` assumes [U, V] is of the same shape of [X, Y] and it will use [X, Y] for processing. It’s designed for constructing the quiver - therefore it breaks when we want to reuse it to construct the quiver key. As a result, the return result is incorrectly broadcasted and its size become the same as `Quiver()`'s input size (We want only one arrow!).

More context:
We call `_angles_lengths` in `Quiver._make_verts(self, U, V, angles)`. We call `Quiver._make_verts(self, U, V, angles)` for constructing paths for both the quiver and the quiver key. `Quiver._make_verts(self, U, V, angles)` isn’t formally documented, so, from its name, it will constructs vertices from given U, V, and mapping of angles (“xy” vs “uv”). We want to use the same `_make_verts` for both the quiver and the quiver key, because we want the properties of the quiver key be consistent with the quiver. The conclusion is that, although it breaks, we may still want to reuse `_make_verts` rather than drawing the quiver key with a new method.

Solution: 
1. Easiest solution but with one small question to be clarified: 
    1. Solution: Make `Quiver._make_verts(self, U, V, angles)` in QuiverKey always use angles a default value (‘uv’ will be applied here) 
        1. In the doc: “QuiverKey.angle: The angle of the key arrow, in degrees anti-clockwise from the x-axis.”  Since we are not explicitly passing [U, V], but an angle, it doesn’t make sense that we can apply “xy” here.
    2. Question: I suggest change  “anti-clockwise from the x-axis” to “anti-clockwise from the horizontal line”. I believe here the “x-axis” refers to x-aixs a canonical x-y coordinates for a canvas (cuz we are printing the figure in a 2D canvas), rather than in coordinates that with a projection.
2. Modify `_angles_lengths` to deal with size unmatch - lot’s of work
