### ISSUE TITLE
[ENH]: Nightly Python 3.12 builds

### ISSUE THREAD

**Issue by effigies** [matplotlib/matplotlib#26557]
### Problem

Trying to get pre-release testing on 3.12 working across some repositories I work on. Matplotlib is currently a blocker for projects that have it as a mandatory dependency. With numpy 1.26.0b1 on PyPI, I suspect this is now doable?

Looking through the issue/PR list, this isn't obviously on the roadmap, so I'm hoping this is a nudge, not pestering.

### Proposed solution

If it's just a matter of duplicating the following with `cp312`, I'm happy to submit a PR:

https://github.com/matplotlib/matplotlib/blob/0b5940f544c5715220a9f3d57c971d3fc4073b64/.github/workflows/cibuildwheel.yml#L138-L145

**Comment by oscargus** [comment]
There are tests in https://github.com/matplotlib/matplotlib/pull/24711 and at the most recent attempt they did not pass.

**Comment by effigies** [comment]
Ah, I'm sorry. I saw the initial date on that PR and assumed it was non-active.

**Comment by oscargus** [comment]
I think your request still makes sense though. My comment was more to update you on the status.

**Comment by ianthomas23** [comment]
FYI there is now a ContourPy release candidate ([1.1.1rc1](https://github.com/contourpy/contourpy/releases/tag/v1.1.1rc1)) available on PyPI that includes wheels for Python 3.12.

I have also reinstated shipping win32 wheels as NumPy are intending to do so in the 1.26.0 release. I'll retroactively build them for the previous release (1.1.0) so that there isn't a gap without win32 wheels.
