### ISSUE TITLE
[Doc]: contourf demo use of origin keyword

### ISSUE THREAD

**Issue by rcomer** [matplotlib/matplotlib#26600]
### Documentation Link

https://matplotlib.org/devdocs/gallery/images_contours_and_fields/contourf_demo.html

### Problem

The [docstring for contourf](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.contourf.html) states that the _origin_ keyword "is only relevant, if X, Y are not given".  The contourf demo passes X, Y and _origin_  for most of its examples.

### Suggested improvement

The simplest thing would be to strip out _origin_ where it's not relevant, but it might be nice to show some examples where it does make a difference.

**Comment by gautamsagar99** [comment]
Hello,

I'm new to open source contribution, I want to solve this issue. I think no one created a PR for this issue can I start working on it?

Thanks

**Comment by rcomer** [comment]
Thanks @gautamsagar99, please go ahead and see our Contributors’ Guide here:
https://matplotlib.org/devdocs/devel/index.html

**Comment by gautamsagar99** [comment]
Hi @rcomer,

I found that origin attribute is useless for all the examples which are provided here https://matplotlib.org/devdocs/gallery/images_contours_and_fields/contourf_demo.html 

Should I add a new Example which demonstrate with origin attribute so that it can be differentiate between "lower" and "upper" values?
If so I can add this Example: 

    import matplotlib.pyplot as plt
    import numpy as np

    x = np.arange(1, 10)
    y = x.reshape(-1, 1)
    h = x * y
    
    cs = plt.contourf(h, levels=[10, 30, 50],
        colors=['#808080', '#A0A0A0', '#C0C0C0'], extend='both', origin="upper")
    cs.cmap.set_over('red')
    cs.cmap.set_under('blue')
    cs.changed()

This Example will be helpful for visualizing the plot when we include origin attribute.
