### ISSUE TITLE
[Bug]: cv2 causes subplots to fail

### ISSUE THREAD

**Issue by highghlow** [matplotlib/matplotlib#26613]
### Bug summary

Importing cv2 anywhere causes matplotlib.pyplot.subplots to fail

### Code for reproduction

```python
import matplotlib.pyplot as plt
import cv2 # Remove to test

plt.subplots(2, 2)
plt.show()
```

### Actual outcome

ERROR:
```
QObject::moveToThread: Current thread (0x56046eba6370) is not the object's thread (0x56046ebab0d0).
Cannot move to target thread (0x56046eba6370)

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/home/archer/.local/lib/python3.11/site-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb, eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx.

zsh: IOT instruction (core dumped)  /bin/python /<...>/mwe.py
```

### Expected outcome

A plot will show like it does with no cv2 imported

### Operating system

Arch

### Matplotlib Version

3.7.2

### Matplotlib Backend

QtAgg

### Python version

3.11.3

### Jupyter version

None

### Installation

pip

**Comment by oscargus** [comment]
Just installed opencv-python on my RHEL8 machine and the current main branch executes the code without any issues, both in a normal python prompt and in ipython.

More information is required, but even then I am a bit tempted to say that this is a opencv-python/cv2 problem rather than Matplotlib.

Just to be clear: did you try reinstalling opencv-python (and xcb?)  as suggested in the error message? Does importing cv2 work without this? Like importing cv2 and open up a minimal QT window? For example, https://www.pythonguis.com/tutorials/creating-your-first-pyqt-window/

Also, I just executed the code as stated. Hence, I do not know if the xcb plugin is actually loaded. Is there a way to make this happen or check which was loaded?

**Comment by ksunden** [comment]
See also: 

#24364

https://github.com/opencv/opencv/issues/22485

These reports had to do with GTK, rather than Qt, but could be related, though I somewhat suspect it is an installation of Qt dependencies that is to blame here.

Also:

#25619 which added a host machine dependency for libxcb-cursor0 with more recent versions of pyqt6, which could be the problem here.

**Comment by highghlow** [comment]
For some reason uninstalling matplotlib and opencv from pip and install from them from pacman solved the issue! (?)
