### ISSUE TITLE
[Bug]: QuadMesh.get_array change breaks seaborn heatmap annotation

### ISSUE THREAD

**Issue by WainingCeoi** [matplotlib/matplotlib#26822]
### Bug summary

When I using seaborn to create heatmap, and use "annot=Ture" to annotate each cells. However, when I use matplotlib 3.8.0 to do this, it only annotate the first row cells. And it can annotate all cells when I use matplotlib 3.7.3.

### Code for reproduction

```python
Fig_13a2 = plt.subplots(figsize=(8, 6))
sns.heatmap(df.corr().abs(), vmax=1, vmin=0, square=True, cmap="Blues", annot=True)
plt.xticks(rotation=45)
plt.tight_layout()
plt.savefig("Fig_13a2.pdf")
```

### Actual outcome

[Fig_13a2.pdf](https://github.com/matplotlib/matplotlib/files/12654104/Fig_13a2.pdf)
I got this using matplotlib 3.8.0, and seaborn 0.12.2

### Expected outcome

[Fig_13a2.pdf](https://github.com/matplotlib/matplotlib/files/12654102/Fig_13a2.pdf)
I got this using matplotlib 3.7.3, and seaborn 0.12.2

### Additional information

1. This worked well in the previous version (3.7.3), It happens when I use the 3.8.0 version. And of the other such as code, others packages, python version etc. remain the same.
2. My seaborn version is 0.12.2

Please feel free to reach me if you need additional info.

### Operating system

MacOS Ventura 13.5.2

### Matplotlib Version

3.8.0

### Matplotlib Backend

module://backend_interagg

### Python version

3.11.5

### Installation

pip

**Comment by tacaswell** [comment]
Is there a version of this that only uses Matplotlib?  Can you give us an example `df` that has this problem?

**Comment by ksunden** [comment]
This has been fixed in seaborn on git, at least (not sure about release) (see mwaskom/seaborn#3478, mwaskom/seaborn#3446)

**Comment by WainingCeoi** [comment]
> Is there a version of this that only uses Matplotlib? Can you give us an example `df` that has this problem?
[Weekly.csv](https://github.com/matplotlib/matplotlib/files/12654196/Weekly.csv)
This df is the one I used to plot this heatmap.

**Comment by thuiop** [comment]
> This has been fixed in seaborn on git, at least (not sure about release) (see [mwaskom/seaborn#3478](https://github.com/mwaskom/seaborn/issues/3478), [mwaskom/seaborn#3446](https://github.com/mwaskom/seaborn/pull/3446))

This is not yet released indeed, but the git version works fine.

Just to explain again the issue, the breaking change was [changing the output of `pcolormesh`](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.8.0.html#the-object-returned-by-pcolor-has-changed-to-a-polyquadmesh-class) ; the old one returned a flattened array when using `get_array`, while the new one returns a multi-dimensional one. The fix is easy enough (flattening it back) but not yet corrected in the seaborn release, so you should remain on matplotlib 3.7 until a new seaborn version is released (at least for the heatmaps).

**Comment by rcomer** [comment]
x-ref #25162
