### ISSUE TITLE
[Bug]: Matplotlib 3.8.0 is causing severe typing issues in dependent packages.

### ISSUE THREAD

**Issue by KelSolaar** [matplotlib/matplotlib#26837]
### Bug summary

Hello,

Matplotlib 3.8.0 is the first release where Matplotlib contains a `py.typed`, as a consequence and described by Eric [here](https://github.com/microsoft/pyright/discussions/5967), most of the objects are now considered private because of the way they are imported. The immediate consequence is that we now have [250+ errors on CI](https://github.com/colour-science/colour/actions/runs/6221153468/job/16882573741) following 3.8.0 release.

The guidelines to mark an object as public for a typed package are outlined here: https://github.com/python/typing/blob/master/docs/source/libraries.rst#library-interface-public-and-private-symbols

### Code for reproduction

```python
import matplotlib.pyplot as plt


def foo()-> tuple[plt.Axes, plt.Figure]:
    ...
```

Then running `pyright "scratch_104.py"`

### Actual outcome

```
 scratch_104.py:4:23 - error: "Axes" is not exported from module "matplotlib.pyplot" (reportPrivateImportUsage)
 scratch_104.py:4:33 - error: "Figure" is not exported from module "matplotlib.pyplot" (reportPrivateImportUsage)
```

### Expected outcome

```
0 errors, 0 warnings, 0 informations 
```

Which was verified by adding `__all__ = ["Axes", "Figure"]` to `matplotlib.pyplot`.

### Operating system

macOs

### Matplotlib Version

3.8.0

### Matplotlib Backend

MacOSX

### Python version

Python 3.11.4

### Installation

pip

**Comment by oscargus** [comment]
Please see https://github.com/matplotlib/matplotlib/issues/26812

**Comment by ksunden** [comment]
For `plt.Figure` and `plt.Axes`, as noted in #26812, these are not documented in that namespace and are considered a private implementation detail as such (in the same way that other imports are not considered public in python modules).

For those, which represent the majority of the errors, adjusting imports is expected.

A quick, non-exhaustive scroll through the CI shows a couple of other things, mostly we have some places that are type hinted as `tuple[float, float]`, such as `figsize`, because the fact that there are exactly two elements is _actually_ important for those use cases. I'd argue that it is the correct type hint, and that anything more general, such as NDArray, is actually missing quite important information there.

Also we have not done any type hinting for 3D axes, so those parts of the code may need either `typing.cast` calls or `# type: ignore` comments, as many calls do not differentiate out 3D (or indeed polar/etc) Axes from the return type of `Axes` (the return _is_ a subtype, and so if you are not using functionality that is added by the subtypes, it is fine, but we have not done the level of overloading needed there...). In fact _can't_ do all possible values for the `projection` argument, because it is a dynamically set list, that cannot be checked via static type checkers... (we may be able to do _better_, by including the built-ins, but it is fairly complicated, especially when the projection arg is sometimes burried inside of `**kwargs`, or there is also singular vs plural overloads, etc... At some point users may have to help the type checker out on this one, because building it into the methods is fragile or underspecified)

I may have missed a few (there were _a lot_ of non-error lines printed in that CI run, which made looking for the errors that much harder), but those were the main things I saw, none of them seemed actually incorrect as things for the type checker to find, though.

Type checking is new to this project, and a challenge to add to a codebase that was not written with static type checking in mind. I expect there are things that users don't _know_ are possible alternate returns (and if they want the type checker to be happy should account for) because they've never used them before, but if you pass `**kwargs`, it is absolutely possible to get. This came up with xarray, where a `hist` plot had been typed on their end using the most common return, but you could absolutely pass kwargs to change the return type to their function. In some ways, this is the _point_ of static type checkers: to find areas where you need to account for types being different than you expect, but possible.

Finally, I would encourage you to consider running your tests against pre-release matplotlib. This can help avert or at least mitigate surprises come release time. This can take a few forms, and I don't expect you to run it on every PR or anything. For instance we run a weekly test against nightly builds of numpy/pandas/etc. We provide [nightly wheels](https://anaconda.org/scientific-python-nightly-wheels/matplotlib) to make it so that installing is as easy as we can make it. Also keeping an eye out for release candidates can help us to catch any problems early enough to consider before final releases.

**Comment by KelSolaar** [comment]
> For plt.Figure and plt.Axes, as noted in https://github.com/matplotlib/matplotlib/issues/26812, these are not documented in that namespace and are considered a private implementation detail as such (in the same way that other imports are not considered public in python modules).

Certainly but this is where I found them back then, and looking at [Pandas](https://github.com/pandas-dev/pandas/pull/55192) and [Matplotlib](https://github.com/matplotlib/matplotlib/pull/26815) itself, this was not a crystal clear fact but it surely is now! I will update our imports accordingly.

All the other points are also fair or understandable, I will fix a few things and ignore some of the other ones. Closing this one and thanks for the discussion!
