### ISSUE TITLE
[ISSUE]: The iterator ''prop_cycler'' is removed from ax._get_lines after v3.8

### ISSUE THREAD

**Issue by JouleCai** [matplotlib/matplotlib#26831]
### Bug summary

I used to access the color cycle iterator for a given axes object (ax) through the _get_lines helper class instance.
However, it becomes an error after v3.8. Is there another way to get the state of the iterator? It was useful to set the line colors automatically for axis spines.

### Code for reproduction

```python
ax_in._get_lines.prop_cycler = ax._get_lines.prop_cycler
```

### Actual outcome

AttributeError: '_process_plot_var_args' object has no attribute 'prop_cycler'

### Expected outcome

Get the color cycler iterator and assign it to another axis spine

### Matplotlib Version

3.8

### Installation

None

**Comment by ksunden** [comment]
This was changed in #26341 in order to make it so that pickling works...

That said, this is private internal, undocumented behavior. AFAIK, there is currently no supported way to share property cycles like this.

See also:
- https://github.com/matplotlib/matplotlib/pull/26078 (Another PR from this cycle that affected `_get_lines`)
- https://github.com/matplotlib/matplotlib/pull/22789 (The PR that the above was based on, which has some direct discussion of sharing property cycles)
- https://github.com/matplotlib/matplotlib/pull/19484 (A (draft) proposal for explicitly shared cyclers, though I expect the implementation would clash with the changes from #26341)

I will tag @anntzer in on this one for further comment, as he is the author of several of the referenced PRs.

**Comment by oscargus** [comment]
Here is an issue about sharing 
https://github.com/matplotlib/matplotlib/issues/19479

I think it would be nice to have a public API to access the cycler for an axis. One obvious reason being easy plotting in twinned axes.

**Comment by anntzer** [comment]
There was no public API for sharing cyclers and there's still none, and I guess this issue is basically pointing in favor of having (some variant of) #19479.
In the meantime, if you want to copy the property cycler without copying the state (i.e. both cyclers advance independently of one another) you can get away with copying _idx, _cycler_items, and _prop_keys; if you want both cyclers to advance together you should just copy _get_lines / _get_patches_for_fill.  Like any usage private API this can break at any time with no advance notice.

**Comment by JouleCai** [comment]
Thanks. It would be nice to have a public API for sharing cyclers. Your hint is very helpful. My case of using multiple y-axis spines is solved by setting the cycler via ax.set_prop_cycle(). 

> There was no public API for sharing cyclers and there's still none, and I guess this issue is basically pointing in favor of having (some variant of) #19479. In the meantime, if you want to copy the property cycler without copying the state (i.e. both cyclers advance independently of one another) you can get away with copying _idx, _cycler_items, and _prop_keys; if you want both cyclers to advance together you should just copy _get_lines / _get_patches_for_fill. Like any usage private API this can break at any time with no advance notice.

**Comment by RoyiAvital** [comment]
What's the current and official way to extract the color cycler of a given axis since this was removed?

**Comment by tacaswell** [comment]
There is no public API for getting color cycle out of an Axes.

**Comment by drmcnelson** [comment]
P/S  Right now I need to generate a pile of twinned graphs for a large data analysis, and I am not sure what I am supposed to do that does not involving rewriting a dozen different graphics routines.   Suggestions?  please

What one lines can I drop in for this?

     ax2._get_lines.prop_cycler = ax1._get_lines.prop_cycler

**Comment by rcomer** [comment]
@drmcnelson did you read the above linked issue #19479?

**Comment by timhoffm** [comment]
> The first for twinx() should be implementable by simply using the same instance of the cycler. If that requires some code factoring, then, well... it should have been done a long time ago.
>
> I dont see how anything could be simpler than that, and I do not understand why it should be more complicated

Please keep in mind that we have much more feature requests than developer capacity and that most contributors work voluntarily on Matplotlib in their spare time. Not everything that is desireable will be implemented.

Also, outside judgements of the simpleness of a change are moot. As discussed in #19479, there are some things to consider, which obviously nobody has gone through thoroughly enough to have a concrete solution. If you are willing to dive in, a reviewable PR or concrete design suggestions (this has to be more detailed than "simply use the same instance" because that alone does not work) is always welcome.
