### ISSUE TITLE
[Bug]: Global legend weird behaviors

### ISSUE THREAD

**Issue by imxtx** [matplotlib/matplotlib#26841]
### Bug summary

The color of the global legend for all subplots does not match the label colors.

### Code for reproduction

```python
esbs = np.array(list(range(0,41)))
lines = [e for e in asrs]

colors = ['dodgerblue', 'tomato', 'yellowgreen', 'orange', 'dodgerblue', 'tomato', 'yellowgreen', 'orange']
labels = ['A', 'C', 'M','F','A+', 'C+', 'M+','F+',]
linestyles = ['-', '-','-', '-','--','--','--', '--']

fig, axs = plt.subplots(2, figsize=(6, 6), sharex=False)

handles = []
for i in range(8):
    print(i, colors[i], labels[i])
    if i == 3 or i == 7:
        h = axs[1].plot(esbs, lines[i], color=colors[i], linewidth=1.2, linestyle=linestyles[i], label=labels[i])
    else:
        h = axs[0].plot(esbs, lines[i], color=colors[i], linewidth=1.2, linestyle=linestyles[i], label=labels[i])
    handles.append(h)

fig.legend(handles, labels=labels, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper left')

plt.show()
```

### Actual outcome

<img width="440" alt="image" src="https://github.com/matplotlib/matplotlib/assets/93981430/704d3f9b-9f06-444c-bed6-bef88bae54b9">

### Expected outcome

The colors for legend F and legend F+ should be orange. But they are different.

### Matplotlib Version

3.7.1

### Installation

None

**Comment by tacaswell** [comment]
This looks like it is due to the signature on legend being _too_ forgiving.

https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.legend

It looks like we try to infer what the positional argument means (it can be a list of strings to go with the auto-discovered artists if it is the only positional argument or a list of handles if there are two positional arguments).   If you do not pass the labels as a keyword argument it will raise.  

What is going on here is we are going through a branch of https://github.com/matplotlib/matplotlib/blob/e6af5a339c7cea73fa0aaa587e258ecb742d4bef/lib/matplotlib/legend.py#L1336-L1374 that never looks at `*args` so the list of handles is being ignored (!!) so are zipping the labels passed in with the list of discovered handles which will be by axes hence the two lines on the second axes will be together at the end.

You should be getting a warning that looks like

```
<ipython-input-12-f89da0bd97bd>:19: UserWarning: You have mixed positional and keyword arguments, some input may be discarded.
  fig.legend(handles, labels=labels, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper left')
```

I think we should escalate that warning to an exception because we have been warning for at least 6 years (but without saying it would break in the future), it is really bad to drop user input on the floor, and this behavior is deeply miss leading.

-----

In the mean time

```python
fig.legend(handles, labels, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper left')
fig.legend(handles=handles, labels=labels, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper left')
```

both work correctly but he best invocation is probably

```python
fig.legend(handles=handles, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper lef
```

which lets the legend code extract the label from the Artist (which you set when you create the Artist so it can never gets out of sync).

**Comment by imxtx** [comment]
Thank you for your detailed analysis and explanation.  ---- Replied Message ----FromThomas A ***@***.***>Date09/20/2023 21:54 ***@***.***> CcT.X. ***@***.***>***@***.***>SubjectRe: [matplotlib/matplotlib] [Bug]: Global legend weird behaviors (Issue #26841)
This looks like it is due to the signature on legend being too forgiving.
https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.legend
It looks like we try to infer what the positional argument means (it can be a list of strings to go with the auto-discovered artists if it is the only positional argument or a list of handles if there are two positional arguments).   If you do not pass the labels as a keyword argument it will raise.
What is going on here is we are going through a branch of https://github.com/matplotlib/matplotlib/blob/e6af5a339c7cea73fa0aaa587e258ecb742d4bef/lib/matplotlib/legend.py#L1336-L1374 that never looks at *args so the list of handles is being ignored (!!) so are zipping the labels passed in with the list of discovered handles which will be by axes hence the two lines on the second axes will be together at the end.
You should be getting a warning that looks like
<ipython-input-12-f89da0bd97bd>:19: UserWarning: You have mixed positional and keyword arguments, some input may be discarded.
  fig.legend(handles, labels=labels, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper left')

I think we should escalate that warning to an exception because we have been warning for at least 6 years (but without saying it would break in the future), it is really bad to drop user input on the floor, and this behavior is deeply miss leading.

In the mean time
fig.legend(handles, labels, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper left')
fig.legend(handles=handles, labels=labels, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper left')
both work correctly but he best invocation is probably
fig.legend(handles=handles, ncol=2, bbox_to_anchor=(0.15, 1.06), loc='upper lef
which lets the legend code extract the label from the Artist (which you set when you create the Artist so it can never gets out of sync).

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/matplotlib/matplotlib/issues/26841#issuecomment-1727783846",
"url": "https://github.com/matplotlib/matplotlib/issues/26841#issuecomment-1727783846",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
