### ISSUE TITLE
[ENH]: Add `bar_plot` Function to Matplotlib

### ISSUE THREAD

**Issue by rajveer43** [matplotlib/matplotlib#26974]
### Issue Description:
I propose the addition of a new function, `bar_plot`, to the Matplotlib library. This function enables the creation of horizontal bar plots with various customization options, making it a valuable addition to Matplotlib's capabilities.

#### Function Description:
- `bar_plot` allows users to create horizontal bar plots with ease, including options for customizing labels, colors, and additional text.
- It enhances the current functionality of Matplotlib by providing a convenient way to visualize data in a horizontal bar format.

#### Benefits:
- This feature will simplify the creation of horizontal bar plots for Matplotlib users.
- It will enable users to customize their plots with labels, colors, and additional text, enhancing the visual representation of data.

#### Example Usage:
```python
# Example usage of the proposed `bar_plot` function
import matplotlib.pyplot as plt

data = [10, 20, 30, 40, 50]
labels = ['A', 'B', 'C', 'D', 'E']

plt.bar_plot(data, labels, per_label=True, label_rotate=0)
plt.show()
```

```python
function bar_plot(data: list, labels: list, per_label: bool, label_rotate: int, **kwargs) -> None:
    # Create a horizontal bar plot with optional customization

    # Initialize plot settings and parameters
    initialize_plot(**kwargs)

    # Calculate index positions for data points
    index = calculate_index(labels)

    # Loop through data, labels, and indices
    for x, y, z in zip(data, index, labels):
        # Display data points with values greater than 0
        if x > 0:
            add_data_point(x, y, z)
        else:
            # Store labels with zero values for optional display
            store_zero_value_labels(z)

    # Customize the plot appearance
    customize_plot(**kwargs)

    # Save or display the plot
    save_or_display_plot(**kwargs)
```

**Comment by jklymak** [comment]
How does this differ from https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.barh.html?  We are very unlikely to entertain very similar plotting using a different method.

**Comment by rcomer** [comment]
It’s great that you are interested in improving Matplotlib!  However I think that such a function would be out of scope for the library.  It looks like what it does is bring together some of Matplotlib’s functionality (bar plot, labelling, legends, updating tick properties, saving,….) into one convenient function.  I think Matplotlib’s job is to provide all the building blocks so that users can make functions such as this, but not to provide those functions directly.  There are simply too many possible combinations of functionality that users might want, so we would have an endless proliferation of new functions.
