### ISSUE TITLE
Passing arguments to called function with widgets

### ISSUE THREAD

**Issue by Cadair** [matplotlib/matplotlib#2706]
Hello,

I have a use case where I have many buttons and widgets that all have the same event function, just that function acts on the widget instance. I have written some code that allows arguments to be passed through to the function (I pass the widget instance). 

I was wondering if you would be interested in my wrapping it up in a PR and if so, if you had any comments on how I have done it. My subclasses of `Button` and `Slider` are here: http://goo.gl/08Y2Ol

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. @Cadair I know it's been a couple years but are you still interested in submitting a PR? If not, can you provide more detail on how you were thinking about / implementing it so others can pick up where you left off? Thank you!

**Comment by tacaswell** [comment]
This can also be addressed via https://docs.python.org/3/library/functools.html#functools.partial (which is maybe how this should be implemented and keep it restricted to kwargs).

I am going to disagree with my previous self and say `*args` are a bad idea (although upstream seems to disagree https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.AbstractEventLoop.call_later going with _only_ args)

I think there are 2 courses of work here here (which may not be mutually exclusive):

 1. add an essay to the top of the widigts api docs about how to use partial / lambdas / closures to bind values to functions
 2. add the proposed API to the `on_*` methods and do so my creating said closure (which is simpler than the OP's sub-classes as the rest of the call back machinery can remain as-is)

Tagged as medium as it may involve API choices and because it involves closures.

**Comment by Cadair** [comment]
I will try and swing around to this, I built some stuff off of it for sunpy (https://github.com/sunpy/sunpy/blob/master/sunpy/visualization/imageanimator.py) which might be worth pushing upstream with a bit of a refactor.

**Comment by anntzer** [comment]
I would strongly favor *not* adding `*args`, passing `functools.partial(func, **kwargs)` or a lambda, as mentioned by @tacaswell should be enough.

**Comment by anntzer** [comment]
Closing as all the maintainers who chimed in favor the partial/lambda approach.
