### ISSUE TITLE
[ENH]: increasing figure size with other elements scaling as well for vector graphics

### ISSUE THREAD

**Issue by cgadal** [matplotlib/matplotlib#27137]
### Problem

It seems to me there is no easy way to save a figure in vectorial formats n times (e.g. twice) bigger than the one created with other elements scaling up as well.

[One](https://stackoverflow.com/questions/77308083/how-to-change-figure-size-and-other-size-elements-for-a-svg-file/77311912#77311912) could suggest to scale up all elements in the rc file, but it seems really hard to do without forgetting any of it.

Another way to achieve this goal is to rely on external tools, such as `svgutils`:

```python
import svgutils.transform as sg
import matplotlib.pyplot as plt

figname = 'test.svg'
scale_factor = 2

fig = plt.figure()
fig.savefig(figname)

fig = sg.fromfile(figname)
newsize = ['{}pt'.format(scale_factor * float(i.replace('pt', ''))) for i in fig.get_size()]

fig.set_size(newsize)
fig.save(figname)
```

It would be great to have such a feature directly included in `matplotlib` ! Maybe as an argument of `savefig` ?

### Proposed solution

One solution would be to integrate `svgutils` directly as a required package when installing `matplotlib`, and use it. However, it is relatively new, and I do not know for how long it will be maintained.

Another solution would be to list all parameters of the rc file that should be scaled up, and work around this ?

**Comment by cgadal** [comment]
Short answer: if someone wants a figure twice bigger while maintaining the default matplotlib layout, in terms of axis linewidths, tick lengths, etc ...

Longer answer:

As for me, the motivation is mainly integrate those in presentations or webpages while painting consistency in terms of fontsizes, linewidths, and symbols sizes across the different figures and with the surrounding text.

To maintain consistency, one has to prepare the figures already at the size at which they will be integrated in the document, presentation, webpage, and not use scaling arguments often offered by the tool when integrating the figure (i.e if you want a figure half the width of your presentation or full width, you should not use something similar to `width=50%` as it will also shrink the fontsizes, linewidths etc...).

However, `matplotlib` default `rcparams` are very well designed to look good for a figure inside a document, i.e with a size around the default figsize. Consider now you want to include the matplotlib figure in a HTML presentation, or webpage. Typical screen resolution being 1920*1080, and considering a typical ppi of 96, you will need a figsize of about 20 inches for a full screen figure, which results in super small line widths for the axis:

```python
from matplotlib import rcParams

# document properties
revealjs_width = 1920  # [px]
revealjs_height = 1080  # [px]
revealjs_fontsize = 40  # [px]
revealjs_ppi = 96  # [px per inches]

# constants
golden_ratio = (1 + 5**0.5) / 2
ptpi = 72  # [pt per inches]

px_per_pt = (revealjs_ppi / ptpi)  # px per pt
scaling_factor = 1

# updating params
rcParams['font.size'] = int(revealjs_fontsize / px_per_pt / scaling_factor)

regular_fig_height = 0.75 * revealjs_height / revealjs_ppi / scaling_factor
regular_fig_width = regular_fig_height * golden_ratio
regular_fig_size = (regular_fig_width, regular_fig_height)
rcParams['figure.figsize'] = regular_fig_size

if __name__ == '__main__':
    import matplotlib.pyplot as plt

    fig = plt.figure(layout='constrained')
    plt.plot([0, 1], [0, 1])
    plt.gca().set_xlabel('Some label')
    plt.gca().set_ylabel('Some label')
    plt.savefig('test_scale_up.svg')
```
![test_scale_up](https://github.com/matplotlib/matplotlib/assets/48522112/85b45d57-8693-4e51-b1d9-ac043f444633)


However, you can consider building a 10 inches  figure with matplotlib default rcparams, and then scale it up by a factor two:

```python
import svgutils.transform as sg
from matplotlib import rcParams

# document properties
revealjs_width = 1920  # [px]
revealjs_height = 1080  # [px]
revealjs_fontsize = 40  # [px]
revealjs_ppi = 96  # [px per inches]

# constants
golden_ratio = (1 + 5**0.5) / 2
ptpi = 72  # [pt per inches]

px_per_pt = (revealjs_ppi / ptpi)  # px per pt
scaling_factor = 2

# updating params
rcParams['font.size'] = int(revealjs_fontsize / px_per_pt / scaling_factor)

regular_fig_height = 0.75 * revealjs_height / revealjs_ppi / scaling_factor
regular_fig_width = regular_fig_height * golden_ratio
regular_fig_size = (regular_fig_width, regular_fig_height)
rcParams['figure.figsize'] = regular_fig_size

if __name__ == '__main__':
    import matplotlib.pyplot as plt

    fig = plt.figure(layout='constrained')
    plt.plot([0, 1], [0, 1])
    plt.gca().set_xlabel('Some label')
    plt.gca().set_ylabel('Some label')
    plt.savefig('test_scale_up.svg')

    #
    fig = sg.fromfile('test_scale_up.svg')
    newsize = ['{}pt'.format(scaling_factor * float(i.replace('pt', ''))) for i in fig.get_size()]

    fig.set_size(newsize)
    fig.save('test_scale_up.svg')
```

![test_scale_up](https://github.com/matplotlib/matplotlib/assets/48522112/a002bf28-8bd1-4962-88f1-d30e77e2b270)

Hope that makes sense.

**Comment by tacaswell** [comment]
There is an rcparam for linewidth (and marker size) as well.

I suspect that this might be a good case for `mpl.style.use(make_for_size(20))` where `make_for_size` returns a dictionary of all of the rcparams you want to set for a given size figure (I can imagine you may also want to tune some of the layout values for spacing between subplots and the values of the automargin code).

I am very skeptical of adding this sort of post-processing into Matplotlib (as it can clearly some aspects of it can be done by external tools working only on the svg), however I think the root source of these issues is that we specify a number of sizes in absolute units (px, pts, etc).  I think what you really want is for the linewidth to be specified in relative size (looks like svg can technically do this: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stroke-width) but I have no guess off the top of my head how hard that would be to thread through Matplotlib.

**Comment by cgadal** [comment]
@tacaswell 

> I suspect that this might be a good case for mpl.style.use(make_for_size(20)) where make_for_size returns a dictionary of > all of the rcparams you want to set for a given size figure (I can imagine you may also want to tune some of the layout > > values for spacing between subplots and the values of the automargin code).

Maybe at first, having just a function, or an example in the doc, listing all the parameters that are not in relative units, and showing how to scale the with the `figsize` would be enough ?

I do agree that adding the post-processing of figures to `matplotlib` is surely not a good idea, and it's probably best to leave this to specific vector graphic tools, running in Python or not.

**Comment by cgadal** [comment]
@jklymak 

>  If you want to scale everything in the figure, scale it in your presentation or word-processing software.

Unfortunately, not every presentation or word-processing software offers this functionality. Working in LaTeX, I could change the macro inserting figures that that everything is inserted at a `scale = 2`. 

However, it is much more difficult for `.html` documents. For CSS < Version 3, it is not possible and requires using js queries. For the more recent versions, it requires `transform`, which does not go well with the flow of elements and usually breaks it or `zoom` which is not widely supported and non-standard, and thus not recommended.

**Comment by jklymak** [comment]
@cgadal I'm no html expert, and I don't know how you are trying to embed your images, but it would be shocking to me if _scalable_ vector graphics were not indeed scalable in most browsers since that is the whole point of them.  

On google and chrome just testing with no css:

```html
<div>
    <img src="boo.svg" style="width: 90%">
</div>
<div>
    <img src="boo.svg" style="width: 70%">
</div>
<div>
    <img src="boo.svg" style="width: 20%">
</div>
```
gives me scaled Matplotlib svgs that adapt as I make the viewport wider or narrower.  I can also use fixed sizes. 

<img width="1044" alt="SVG" src="https://github.com/matplotlib/matplotlib/assets/1562854/09be67ae-bc2d-477c-bdca-0aefcab7618e">

**Comment by cgadal** [comment]
I am sorry I am not clear enough on this. Doing this scales the object with respect to the parent container, not the object itself.

If I try to summarize my issue based on your example, I'd like to do the exact same thing but:

-  while conserving the font size, line widths, etc .. between the 3 figures
-  doing for a page that's typically in 1920px*1080px, with fontsize for labels of 40 px ~ 30 pt
- conserving the default matplotlib layout, i.e ratio between fontsize, linewidths etc ...

 if you try to do this, it seems to me you need to print your figures at the size you want them to be on your page.

**Comment by jklymak** [comment]
@cgadal These are all different things.  

> while conserving the font size, line widths, etc .. between the 3 figures

Then you change the fig size parameter:  `fig.set_size_inches(figsize)`

<img width="427" alt="Scale" src="https://github.com/matplotlib/matplotlib/assets/1562854/b9fdaa2d-92fe-4613-b373-f8baff482890">


> doing for a page that's typically in 1920px*1080px, with fontsize for labels of 40 px ~ 30 pt

Its not clear if you want to do this at the same time as the above; it is also not clear if you _just_ want the font size to increase, or if you want the lines to also thicken.  If you want both, then you make the figure smaller, and scale in your presenter:

<img width="427" alt="WidthsChange" src="https://github.com/matplotlib/matplotlib/assets/1562854/bf477928-0a5a-4233-be5b-6ce30cf48421">

If you just want the fonts to change size then you just do  `matplotlib.rc('font', size=30)`

<img width="427" alt="BigFont" src="https://github.com/matplotlib/matplotlib/assets/1562854/f4c476d6-7d96-4c8c-a0a7-a501e0ab0947">

> conserving the default matplotlib layout, i.e ratio between fontsize, linewidths etc ...

As above, you do that by making the figure smaller in Matplotlib, and scaling up in your viewer. 

> EDIT: Another constraint is that you often want to include your figures somewhere with an already defined layout, and it makes sense to me that you want to adapt the figure to the document layout, rather than modify the document layout (i.e the CSS file) to adapt it to the matplotlib layout.

Sure, let's say you want your figure to be 5 inches wide by 4 inches high, but fonts and lines scaled up to be larger so that a 12-pt font is 30 pts.  In Matplotlib you just do:

```
scale = 30/12
fig, ax = plt.subplots(layout='constrained', figsize=(5/scale, 4/scale))
```

and in your html you just do

```
    <img src="Scaled.svg" style="width: 5in">
```

your fonts will be 30 pts, and your lines will be thicker

<img width="713" alt="Scaling" src="https://github.com/matplotlib/matplotlib/assets/1562854/4f447e6a-efe0-4679-b02d-ae5b67da548a">

I agree that the resulting svg claims it is only 2 inches wide instead of 5 inches.  But that really doesn't matter at all - it's the relative size of the figure to its elements that matters.  After that, it is the job of the viewer to scale the graphic.   However, if you want to rescale it in SVG post processing, you can do that, but I don't think Matplotlib should be involved in that.

**Comment by jklymak** [comment]
Also note that if you _really_ want to not use `width=5in`, you can edit the svg yourself:

```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="144pt" height="115.2pt" viewBox="0 0 144 115.2" xmlns="http://www.w3.org/2000/svg" version="1.1">
```

to 

```
<svg xmlns:xlink="http://www.w3.org/1999/xlink" width="360pt" height="288pt" viewBox="0 0 144 115.2" xmlns="http://www.w3.org/2000/svg" version="1.1">
```

which reports the correct size and otherwise looks identical to the above. 

I guess all you are asking is that Matplotlib do this for you on `savefig`.    I think we would balk at adding something that can only be done for one backend.  It's possible/likely something similar exists for PDF and EPS so maybe a `scale_vector_output` is possible.  However, in my opinion, it's the wrong tool for the job.

**Comment by jklymak** [comment]
I'm going to take the liberty of closing this but feel free to ask for a re-open if there is a concise feature request that is in Matplotlib's wheelhouse.
