### ISSUE TITLE
[Doc]: Lack of "3d" as projection keyword argument in documentation of axes constructors such as pyplot.add_subplot, pyplot.subplot and pyplot.subplots.

### ISSUE THREAD

**Issue by p479h** [matplotlib/matplotlib#27166]
### Documentation Link

https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.add_subplot

### Problem

The [Axes3D documentation](https://matplotlib.org/stable/api/toolkits/mplot3d/axes3d.html#mpl-toolkits-mplot3d-axes3d-axes3dl) page instructs the user to visit [pyplot](https://matplotlib.org/stable/api/pyplot_summary.html#module-matplotlib.pyplot), [plt.gcf().add_axes](https://matplotlib.org/stable/api/figure_api.html#matplotlib.figure.Figure.add_axes), etc. to instantiate a 3D axes. All these options lead to the following description in the documentation:

Parameters:
...
projection{None, 'aitoff', 'hammer', 'lambert', 'mollweide', 'polar', 'rectilinear', str}, optional

Which is missing `projection='3d'` as a valid projection.

On a similar note, the [built-in projection](https://matplotlib.org/stable/api/projections_api.html#built-in-projections) documentation would also benefit from adding '3d' as an option.

### Suggested improvement

Include "3d" as one of the options in the `projection` keyword argument for `figure.add_subplot`, `figure.add_axes`, `pyplot.subplots` and `plt.subplot`.

**Comment by ksunden** [comment]
This falls into a slightly odd corner of what can be documented.

The list of projections is actually dynamic, and can be added to by calling [`register_projection`](https://matplotlib.org/stable/api/projections_api.html#matplotlib.projections.register_projection)

I do not think we are willing to update the docstring dynamically.

`"3d"` is at least arguably covered by the `str` and comment about "custom projections" in the docstring already.

3d support itself is in a little bit of an odd situation currently. It is actually implemented outside of the `matplotlib` namespace in `mpl_toolkits` (though it is installed into the `mpl_toolkits` namespace in a standard install of matplotlib).

That said, 3d is actually available by default because it is registered on import and imported [here](https://github.com/matplotlib/matplotlib/blob/e50154367059dd321f5a4aa33e08009351aaff91/lib/matplotlib/projections/__init__.py#L58). (Though I think we had decided in response to #26827 to at least wrap that import with a try/except the import... I'll actually go PR that now...)

I would personally argue in favor of moving 3D support into the `matplotlib` namespace and fully including it in these docstrings etc. without ambiguity of whether it "counts" or not (but that is a relatively large change). @scottshambaugh do you have opinions on such? (the idea has been raised at the community call, but no decision has been made)

**Comment by tacaswell** [comment]
We ship the 3D projection as part of the main library (even if it is in a funny namespace), we should document it as such.
