### ISSUE TITLE
[Bug]: Axis3D not displaying in figure

### ISSUE THREAD

**Issue by ethan-tau** [matplotlib/matplotlib#27193]
### Bug summary

When attempting to plot with an Axis3D object in a Jupyter QTConsole session in interactive mode, the axes and data do not show in the figure window

### Code for reproduction

```python
%matplotlib qt5
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
fig = plt.figure()
ax = Axes3D(fig=fig)
ax.plot3D(range(0, 60), range(0, 60), range(0,60))
```

### Actual outcome

![image](https://github.com/matplotlib/matplotlib/assets/61170911/59873f1f-2efa-4e15-b1c2-60ffa7cfeb82)

### Expected outcome

The figure window to display axes and plotted data:
![image](https://github.com/matplotlib/matplotlib/assets/61170911/112c35c7-251e-4c2c-aebd-af613f073d9a)

### Additional information

2D plots work fine

### Operating system

Windows 10

### Matplotlib Version

3.7.2

### Matplotlib Backend

Qt5Agg

### Python version

3.11.5

### Jupyter version

Jupyter QtConsole 5.4.2

### Installation

conda

**Comment by ksunden** [comment]
Initializing axes with the constuctor directly is not the usual way of creating Matplotlib axes. 

While it is true that you hand it the figure, it doesn't _actually_ add the Axes to the figure automatically.

To do so you need to add:

```python
fig.add_axes(ax)
```

However, the more idiomatic way/the way we demonstrate in examples is to thread through the `projection` argument with things like:

```python
fig, ax = plt.subplots(subplot_kw={"projection":"3d"})
```

rather than creating the Figure, Axes, and adding the axes to the figure in three separate steps.

There once was an argument to the Axes3D constructor called `auto_add_to_figure`, which defaulted to False. But that is no longer supported (plus `fig.add_axes(ax)` is actually _shorter_ anyway).

As this is known/expected behavior I will close this issue.

**Comment by ethan-tau** [comment]
@ksunden - thanks for the response. I thought something had broken in the dependency chain when even my prior code didn't render the 3D axis, but then I see the `Note` under Getting Started in https://matplotlib.org/2.0.2/mpl_toolkits/mplot3d/tutorial.html
