### ISSUE TITLE
[Bug]: AttributeError while trying to import matplotlib.pyplot

### ISSUE THREAD

**Issue by dhondta** [matplotlib/matplotlib#27289]
### Bug summary

`AttributeError` while trying to import `matplotlib.pyplot`.

### Code for reproduction

```python
import matplotlib.pyplot
``````

### Actual outcome

```
$ python3
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.11/site-packages/matplotlib/pyplot.py", line 66, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "/home/user/.local/lib/python3.11/site-packages/matplotlib/figure.py", line 43, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "/home/user/.local/lib/python3.11/site-packages/matplotlib/projections/__init__.py", line 60, in <module>
    from mpl_toolkits.mplot3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/__init__.py", line 1, in <module>
    from .axes3d import Axes3D
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 45, in <module>
    class Axes3D(Axes):
  File "/usr/lib/python3/dist-packages/mpl_toolkits/mplot3d/axes3d.py", line 723, in Axes3D
    set_zticklabels = _axis_method_wrapper(
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/matplotlib/axes/_base.py", line 56, in __init__
    doc = inspect.getdoc(getattr(maxis.Axis, method_name))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Axis' has no attribute '_set_ticklabels'. Did you mean: 'set_ticklabels'?
```

### Expected outcome

```
$ python3
Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot
>>> 
```

### Operating system

Ubuntu 22.04

### Matplotlib Version

3.8.1

### Python version

3.11.6

### Installation

pip

**Comment by ksunden** [comment]
This is an alternate presentation of #26827, just with mpl 3.6 installed rather than mpl 3.5 (and thus a different exception, which the initial band-aid fix doesn't catch).

The short version is that you have a state where two incompatible versions of mpl are installed and it is selecting the wrong one for 3D support. See the other thread for more details

I'm going to close this as a duplicate so that we keep the conversation in one place, but feel free to add some context over there.

**Comment by QuLogic** [comment]
This is also exacerbated by the fact that Debian's Python is completely busted. They have patched distro search paths to `/usr/lib/python3/dist-packages`, which _has no minor version_ in it. Your Python 3.11 is not the default Python for Ubuntu 22.04 (that is 3.10), but because of these faulty search paths, it _still sees_ the distribution files.
