### ISSUE TITLE
[Bug]: fill_between plots a line that should not exist when the color is modified

### ISSUE THREAD

**Issue by goodgoodcat** [matplotlib/matplotlib#27402]
### Bug summary

It appeared when I try to modify the color, I submitted this error two days ago, but GitHub shielded that account and it is *only accessible to me*

without color=color_elements[1], the plot is normal, once setting the desired color, the buggy plot is displayed.

```bash
# -*- coding: utf-8 -*-
'''
Created on Tue Nov 28 02:19:11 2023

@author: Nova
'''

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(-10, 10, 400)
y = np.abs(np.sin(x))

color_elements = ('#9ed900', '#f00056', '#4b5cc4')

fig, ax = plt.subplots()

plt.fill_between(y, x, color=color_elements[1], alpha=0.5)
# plt.fill_between(y ,x, alpha=0.5)

plt.show()
```

![图片](https://github.com/matplotlib/matplotlib/assets/126973075/453a586f-1de6-495e-b259-d52333669ec1)
![图片](https://github.com/matplotlib/matplotlib/assets/126973075/fbe03241-0ae2-4474-9415-d6c22005712f)

### Code for reproduction

```python
as provided above
```

### Actual outcome

as provided above

### Expected outcome

as provided above

### Operating system

Windows

### Matplotlib Version

3.8.2

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

3.12.0

### Jupyter version

no matter it's Jupyter or spyder

### Installation

pip

**Comment by ksunden** [comment]
Part of this is that setting `color` sets both the face- and edge-colors, the latter of which is not drawn by default, this is especially apparent with transparency as the regions overlap and become darker.


Setting `facecolor` instead should resolve this. 

The second point with this region is that fill_between takes x values (here set to the variable y) and 1-2 sets of y values. The second set of y values defaults to 0. Hence why a line is drawn along the 0, because it is drawing that particular edge.

Using fill_between for y-oriented functions like this can be a little odd. You likely want to use fill_betweenx instead.

**Comment by UjjawalkTjNw** [comment]
# Fill the area between y and the x-axis without drawing the line
plt.fill_between(y, x, color=color_elements[1], alpha=0.5, edgecolor='none')

Use edgecolor ='none'

Or if you want to fix without using this just swap the position of x and y:
plt.fill_between(x, y, color=color_elements[1], alpha=0.5)
