### ISSUE TITLE
[MNT]: svg font can not be selected and edited

### ISSUE THREAD

**Issue by Nikeguo** [matplotlib/matplotlib#27483]
### Summary

Why exported vector graphics svg exported to pdf font can not be selected and edited, but matlab is OK

**Comment by jklymak** [comment]
Can you give more details of what you mean here?  How do you make your Matplotlib svg and how do you export to pdf?

**Comment by Nikeguo** [comment]
Use this code is ok.
``` python
plt.rcParams['svg.fonttype'] = 'none'
```

**Comment by ksunden** [comment]
https://matplotlib.org/stable/users/explain/text/fonts.html#fonts-in-svg

By default, `svg` exports text as `paths` rather than embedded text fields so that the files will look the same regardless of installed fonts, etc.

This is however behavior that is selectable, by using the `svg.fonttype` rcparam.

Because this is intentional default behavior with a setting available to change it, I will close this issue.
