### ISSUE TITLE
Optional Dependencies Link not working on Installing user's page

### ISSUE THREAD

**Issue by echedey-ls** [matplotlib/matplotlib#27627]
See this reference: https://github.com/matplotlib/matplotlib/blob/6f635b41ff4941af640c75b4d9bf0e0955066114/doc/users/installing/index.rst?plain=1#L34C65-L34C65

In [current docs](https://matplotlib.org/stable/users/installing/index.html#install-an-official-release), it points to https://matplotlib.org/devdocs/devel/dependencies.html#optional-dependencies which is an invalid page.

I think it should link to this file/section: https://github.com/matplotlib/matplotlib/blob/main/doc/users/installing/dependencies.rst#optional

**Comment by dstansby** [comment]
Weird - I can confirm the Optional dependencies link on https://matplotlib.org/stable/users/installing/index.html#install-an-official-release is broken, but I have no idea how or why it's pointing to https://matplotlib.org/devdocs/devel/dependencies.html#optional-dependencies 😕

**Comment by rcomer** [comment]
I think this is a combination of two factors:

* `stable/devel` now redirects to `devdocs/devel` because we want contributors to find the most up-to-date information
* dependencies info was moved out of `devel` at #27395, but that change has not yet made it into a release (so stable is not benefitting).

So it should be fine once we update the stable docs at the next release.  A workaround in the meantime is to explicitly point to the v3.8.2 docs:
https://matplotlib.org/3.8.2/users/installing/index.html

**Comment by rcomer** [comment]
Now that v3.8.3 is out, the link is pointing to the correct location.
