### ISSUE TITLE
[Bug]: Savefig with invalid filename

### ISSUE THREAD

**Issue by hantangantan** [matplotlib/matplotlib#27748]
### Bug summary

savefig returns no error when using invalid filename

### Code for reproduction

```python
import matplotlib.pyplot as plt
import numpy as np

x = np.linspace(0, 10, 100)
y = np.sin(x)


plt.figure(figsize=(8, 6))
plt.plot(x, y, '-r', label='Sinewave')
plt.title('Example')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.legend(loc='best')

# creates empty file named test - no error thrown
plt.savefig('test : diagramm')
```

### Actual outcome

no error message - only empty file which is a little bit confusing as there is no error message created

### Expected outcome

Thrown Exception: Invalid Filename

### Operating system

Windows 10 Professional

### Matplotlib Version

3.8.2

### Python version

3.11.6

### Installation

pip

**Comment by timhoffm** [comment]
Might be a windows topic since `:` is not allowed there.

**Comment by tacaswell** [comment]
what does

```python
with open("test : broken", 'w') as fout:
   fout.write('test')
```

do?

**Comment by QuLogic** [comment]
`:` is not technically barred on Windows, since maybe NT? The above test code works fine.

_However_, the file is not usable in Explorer. It appears as `test `, so if you try to open or delete it, it doesn't work. It's also not accessible from PowerShell or the Command Prompt. That's not actually because of the colon, but because the filename ends with a space, which is not allowed. While `os.unlink('test ')` did seem to work, it seems to be stuck in the system somewhere and still shows up in `dir` or Explorer but can't be opened any more.

What the colon actually does is open an NTFS Alternate Data Stream, and [that is intentional](https://bugs.python.org/issue23463#msg235965). If you remove the space before the colon, then everything works a bit more reasonably:
```
PS > python
>>> with open('test:broken', 'w') as f:
...     f.write('test')
>>> exit()
PS > Get-Item test

    Directory: ...\matplotlib

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2024-02-05   6:23 PM              0 test
PS > Get-Item test | Get-Content  # Main stream is empty.
PS > Get-Item test | Get-Content -Stream broken  # But this alternate stream contains the data we wrote.
test
PS > del test  # Works fine here.
```

**Comment by timhoffm** [comment]
> because the filename ends with a space, which is not allowed.

Seems not exactly true. It's allowed but not fully supported 🙄 : https://stackoverflow.com/questions/67884051/how-do-i-delete-a-windows-file-with-a-trailing-space-or-period-character

Handling this is beyond our responsibility. This should be reported upstream and cpython itself should decide whether they act on it.

**Comment by timhoffm** [comment]
I'm closing this as we're not going to do any special casing on the Matplotlib side. This is up to cpython: https://github.com/python/cpython/issues/115104.
