### ISSUE TITLE
[Bug?]: mypy  error: Item "None" of "GridSpec | None" has no attribute "get_geometry"

### ISSUE THREAD

**Issue by ubaldot** [matplotlib/matplotlib#27914]
### Bug summary

I took back a project after few months and `mypy `suddenly reports a large number of errors all connected to `matplotlib`. 
Most of the errors are about type `None `not having attributes. 

I don't know if it is me or an actual bug, but to be sure I report a snippet below. 

### Code for reproduction

```Python
from matplotlib import pyplot as plt

nrows = 2
ncols = 2

fig = plt.figure()
grid = fig.add_gridspec(nrows, ncols)
axes = fig.add_subplot(grid[0])

nrows = fig.get_axes()[0].get_gridspec().get_geometry()[0]
ncols = fig.get_axes()[0].get_gridspec().get_geometry()[1]
```

### Actual outcome

error: Item "None" of "GridSpec | None" has no attribute "get_geometry"

### Expected outcome

No errors. 

### Matplotlib Version

3.8.3

### Python version

3.12.2

### Installation

conda

**Comment by ksunden** [comment]
In this case in particular, and looking through the source of your project (I found the similar lines) you actually already have the values you are looking up, so I don't think the lines that are erroring are doing much of anything. (In one method the two variables are named the same already, in the other you have the value as `q`, but you know what grid size you made in both cases.)

**Comment by ubaldot** [comment]
Many thanks for your reply and for the detailed explanation.

I see your points. I though that `mypy `was smart enough to understand that I added a `gridspec `but apparently it does not. 
A quick fix would be to use something like the following:

```
whatever = myFunction()
if whatever is None:
    return 1
```
after every function call (or to use some try exception) and handling each possible return type, but that would make the code to bloat very quickly. 

As usual, I think it is a matter of balance and good sense. Not having a checker at all is a bad idea IMO, but having it too aggressive may be not a good idea either. 

I also agree that returning `Any `is like not using at all the power of type checking, but again, I think it is a matter of balance and making conscious choices.

I think that I will disable mpl checks for now, and re-enable whenever `mypy `would become "smarter" :) 

Thanks for the support!

**Comment by ksunden** [comment]
The point of saying you have the info already is to say you don't actually need to make the calls that are erroring at all, you are querying for values you already have. This of course does not generalize to all uses, but it should work here.


The fact that mypy does not know what will be returned here is actually pretty fundamental and unlikely to change. It is not a simple matter of typing getting "smarter". It is a stateful property not a type based property. A valid `Axes` can return None here, and nothing about the type differs from one that will return a gridspec. Further even if we could differentiate them (eg by making a subclass, which there are no plans to do) level, the fact that this line goes through a collection (fig.get_axes) would mean that both options would still be valid to the type checker here. 

I think for the type system to know this, we would have to add many tags on Axes and make Figure generic over which kinds of axes it has, and users would have to specify all of that themselves. And all of those are probably more of a pain than it is worth.

Matplotlib's apis were of course largely made before type checking was available in python, and so some of the idiomatic things in type checked python were not considerations for this codebase. Perhaps different design choices would have been made, we will never truly know.

The spelling for pyproject.toml would be, I believe:

```toml
[[tool.mypy.overrides]]
module="matplotlib.*"
ignore_errors=true
```

**Comment by ksunden** [comment]
Even in the subplots case, `p` and `q` are exactly equal to `nrows` and `ncols`, respectively, so you do indeed have the information already.

The actual config (tested it out this time, not on your whole codebase, but on a test file containing this example, but using your pyproject.toml):

```toml
[[tool.mypy.overrides]]
module = "matplotlib.*"
follow_imports = "skip"
```

**Comment by ksunden** [comment]
> A quick fix would be to use something like the following:
> ```
> whatever = myFunction()
> if whatever is None:
>    return 1
> ```

This would work, and will in fact type narrow further down, I think in the case like this I may stylistically go with:

```python
gs = fig2.get_axes()[0].get_gridspec()
assert gs is not None, "We should always have a gridspec"
nrows, ncols = gs.get_geometry()
```

But any number of options would work, and if you were e.g. taking in a figure created elsewhere, you may need to either not do the size adjustment or assume there is only one plot (nrows = ncols = 1) etc.

The assert is nice because it does type narrow, but won't flag any lines as unrun for coverage checks, etc. and it shows the intent that a gridspec is there (while still providing a place to put a helpful error message).

This also does have the (admittedly likely negligible) advantage of not calling methods more than once.

**Comment by tacaswell** [comment]
```
if (gs := ax.get_gridspec()) is not None:
    gs.get_geometry()
```

should also work?

**Comment by ubaldot** [comment]
> ```
> if (gs := ax.get_gridspec()) is not None:
>     gs.get_geometry()
> ```
> 
> should also work?

Yes, but we are discussing a general approach not my specific (and to some extent questionable) example.

**Comment by tacaswell** [comment]
> What if a function returns a Union of 10 different types?

This is more of a general typing / API design philosophy question than a Matplotlib specific question.

I strongly suspect that the most common case like this is `Optional[Type]` / `Type | None` for things that do in-band signalling (one of the motivating cases for `:=` was the regex search API that either returns groups or `None`) which is well handled by these techniques.

If you have something that returns a union of 10 types that is a questionable API design (that said, it is unlikely that we are going to put in major API changes solely to make the typing nicer....terrible looking typing is just making more obvious what is already the case (I suspect that as more libraries are written with types from the start they will apply pressure for less-bad API choices)), but you would probably have to handle it the same way that we handle really flexible inputs with either a call of `if..elif...elif` or a match statement (https://docs.python.org/3/tutorial/controlflow.html#match-statements) both to help the static analyzer out and to make sure your code actually runs!  If something does return a union of 10 things I would also guess that there is likely some overlapping set of functionality they all have and it should be typed as a `Protocol` that has that sub-set.

---

I'm going to close this because (although possibly annoying) this is the typing and mypy working as expected.
