### ISSUE TITLE
redirect not working for updated contribute page

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#27911]
There should be a re-direct there: https://github.com/matplotlib/matplotlib/blob/478dc5aa62d90f9abeab62b94aefc1a1bfde3413/doc/devel/contribute.rst?plain=1#L1-L3

We should merge this to avoid the redirect in our links, but we should also sort out why the redirect is not working.

_Originally posted by @tacaswell in https://github.com/matplotlib/matplotlib/issues/27910#issuecomment-1992091204_

**Comment by AnsonTran** [comment]
The issue seems to be with this line of code here: https://github.com/matplotlib/matplotlib/blob/5a4bb71f640a3c4dd8aac1af8952fe336da428b8/doc/sphinxext/redirect_from.py#L110C1-L110C5.

```app.env.get_domain('redirect_from').redirects``` is an empty dictionary, so none of the redirect HTML pages get created. My guess is that it is being cleared somewhere?
