### ISSUE TITLE
[Bug]: ax.xaxis.set_label(...) doesn't set the x-axis label

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#27971]
### Bug summary

I'm used to using the Axis API like `ax.xaxis.set_major_formatter(...)` etc., so to be consistent it would be nice if one could do `ax.xaxis.set_label(...)` instead of `ax.set_xlabel(...)`. It seems like `ax.xaxis.set_label(...)` does not label the axis however.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.xaxis.set_label("x-label")
```

### Actual outcome

<img width="580" alt="Screenshot 2024-03-24 at 10 02 10" src="https://github.com/matplotlib/matplotlib/assets/6197628/1f11362e-c995-43b9-adeb-61b97009ce84">

### Expected outcome

<img width="602" alt="Screenshot 2024-03-24 at 10 02 26" src="https://github.com/matplotlib/matplotlib/assets/6197628/8f7c4c49-c1b1-4790-b392-0538805b2dea">

### Matplotlib Version

3.8.3

### Installation

conda

**Comment by ksunden** [comment]
The method you are looking for is [`set_label_text`](https://matplotlib.org/stable/api/_as_gen/matplotlib.axis.Axis.set_label_text.html#matplotlib.axis.Axis.set_label_text)

set_label is the inherited method from Artist which provides the text that would appear in a legend entry (odd to do for Axis, but is defined by Artist)

However, confusingly, get_label is actually overridden with a different meaning in Axis, where it returns the Text instance of the label. (And so I might expect the setter to error with a raw string, but expect a Text instance)

I will state that the "_text" postfix is itself confusing, because it is given a string and is opposed to the version which uses Text.

**Comment by dstansby** [comment]
Thanks - I thought something like that might be going on. Shall we close as won't fix then? Or we could keep open and as an action deprecate the overriden `get_text()` in favour of `get_label_text()` (if that would even be technically possible...)?

**Comment by timhoffm** [comment]
Please leave open. I will think about whether we can make this less confusing when I have a quiet minute.

**Comment by timhoffm** [comment]
The name label is very broad and used for different things in different contexts. It would have been better to either be more specific `set/get_legend_label` or distinguish data and decoration Artist categories, which could have individual interpretations of `label`. But we are not in a place to change either. To limit misuse and confusion I propose to:

- Override `set_label()` in `Axis` and `raise RuntimeError("A legend label cannot be assigned to an Axis")`. While this explicitly breaks Liskov's Substitution Principle, that principle was already implicitly broken by the design, i.e. deriving Axis as a class that cannot have legend entries from the Artist class that assumes it can have legend labels. IMHO it's better to make this explicit and fail loudly instead of silently accepting a value and not ever doing anything with it.
- Deprecate the overridden `get_label()`. We should not be overwriting this with different semantics than the base class. Instead, suggest to access the attribute `Axis.label` directly. Whether that's a good pattern is a differerent topic. It's already there as an interface, so it won't go away too easily. Alternatively, one could add `get_axislabel()` (consistent with the existing `Axis.get_ticklabels()`.
  When the deprecation expires, either fall back to the original behavior or, preferrably also raise a RuntimeError.
