### ISSUE TITLE
[MNT]: Misleading function name `Poly3DCollection.get_vector()`

### ISSUE THREAD

**Issue by AnsonTran** [matplotlib/matplotlib#28199]
### Summary

I came across this function `Poly3DCollection.get_vector()`, that just sets some internal variables. It's only called once in the codebase at `Poly3DCollection.set_vector()`, and isn't overriding anything from parent classes.

https://github.com/matplotlib/matplotlib/blob/d67f08e449a114a08c694c614ac847c565fbb372/lib/mpl_toolkits/mplot3d/art3d.py#L951-L962

### Proposed fix

`Poly3DCollection.get_vector()` should be renamed to something more appropriate, or deprecated and function code moved into `Poly3DCollection.set_vector()`

**Comment by tacaswell** [comment]
This should be made private and public access deprecated.  It is technically public so should go through the normal deprecation cycle.

I think renaming to `_get_vector` (or similar) is the first step as if we inline it we would have to carry two copies for the deprecation cycle (even though we are _sure_ no one is using it because we have been "sure" and wrong in the past).

It looks like this method came into the code base in edd492e866b0d43b497540f7c0fccc7fbba1021f in 2009 as part of the initial merged of mplot3d into the main codebase (!!).  It looks like this name makes sense when used in context of `set_verts`.
