### ISSUE TITLE
[Bug]: Interactive Mode Image Visualization

### ISSUE THREAD

**Issue by Xyhlon** [matplotlib/matplotlib#28200]
### Bug summary

I want to visualize the changes within an image and for some reason depending on the filling and initialization, the updating is working or not. 

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt

plt.ion()

fig, ax = plt.subplots()
data = np.random.rand(10, 10)
data.fill(0.0)
im = ax.imshow(data, cmap='viridis')

for _ in range(50):
    data = np.random.rand(10, 10)
    im.set_data(data)
    plt.draw()
    plt.pause(0.1)

plt.ioff()
plt.show()
```

### Actual outcome

run code from above

### Expected outcome

```python
import numpy as np
import matplotlib.pyplot as plt

plt.ion()

fig, ax = plt.subplots()
data = np.random.rand(10, 10)
im = ax.imshow(data, cmap='viridis')
data.fill(0.0)

for _ in range(50):
    data = np.random.rand(10, 10)
    im.set_data(data)
    plt.draw()
    plt.pause(0.1)

plt.ioff()
plt.show()
```

### Additional information

Initialization with np.zeros also doesn't work then

### Operating system

Arch

### Matplotlib Version

3.8.3

### Matplotlib Backend

QtAgg

### Python version

3.12.3

### Jupyter version

---

### Installation

Linux package manager

**Comment by tacaswell** [comment]
Setting the data does not automatically adjust the limits of the color normalization.  When you do the first draw with all 0 select the min/max of the data set as the vmin/vmax for the visualization.  As both are 0, you end up with a degenerate colormaping.

You can either explicitly set the vmin/vmax when you call `imshow` or use `im.set_clim` to adjust it everytime through the loop.

The following works for me (with stock Arch packages):

```python
import numpy as np
import matplotlib.pyplot as plt

plt.ion()

fig, ax = plt.subplots()
data = np.random.rand(10, 10)
data.fill(0.0)
im = ax.imshow(data, cmap='viridis', vmin=0, vmax=1)

for _ in range(50):
    data = np.random.rand(10, 10)
    im.set_data(data)
    ax.set_title(f'frame {_}')
    plt.draw()
    plt.pause(0.1)

plt.ioff()
plt.show()
%history
```

I am going to close this because I do not think there is a bug in Matplotlib and this is behaving as expected.
