### ISSUE TITLE
FFMpeg multi-threaded recording

### ISSUE THREAD

**Issue by ghost** [matplotlib/matplotlib#2820]
When using ffmpeg to record an .mp4 movie of a matplotlib animation with something like

```
anm.save('movie.mp4', writer='ffmpeg', extra_args=['-threads', 'n'])

```

where anm and n are the animation object and the number of threads, respectively, it seems that the global interpreter lock prevents from correctly distributing the task of encoding among available cpu cores. 

Of course, one can avoid this by first breaking the animation into n chunks and encoding each using ffmpeg with, for example, Python's multiprocessing library, and then stitching the resulting 'n' movies into a single one. 

Would the above be the best solution, or should perhaps matplotlib try to handle this internally?

**Comment by william-yessen** [comment]
If no one is currently working on this, I would like to take it over.

**Comment by WeatherGod** [comment]
No, no one is working on this. Looking over this thread (I missed it the
first time through), One thing to keep in mind is that there are stream
writers and file writers. The fundamental difference between them is that
the stream writers opens a pipe to the encoder at the beginning of the
animation, while the file writers opens the pipe at the end of the
animation. I can see how one can parallelize the file writers, but I think
it might be tricky to parallelize the stream writers.

In the stream encoding scenario, I can't imagine much gains happening
because you either end up with multiple movies that have every Nth frame
that has to be interleaved together, or you would restrict yourself to
situations where you know how many frames there will be (not all animations
know the number of frames at the onset). Even if you knew the number of
frames, denoted as M, you would send the first M//N frames to the first
worker, while the other N-1 workers are twiddling their thumbs.

I am unsure about how to configure this appropriately, especially given the
possible requirement of multiple tools. I would go the route of restricting
parallelism to only those encoders that can support the final stitching
step at the end.

**Comment by william-yessen** [comment]
Ah, thanks for the input! Right now I'm working on the file writer. I may or may not think about stream writer later, but in either case I'll keep this thread fresh with updates.

**Comment by william-yessen** [comment]
OK, the first (hopefully flying) version is done. I somehow cannot get ffmpeg and mencoder installed on Ubuntu 14.10. Could someone test the code please (see https://github.com/william-yessen/mpl_parsave) before I get to the machine that has all the requirements installed (which probably won't be until tomorrow).

**Comment by tacaswell** [comment]
@william-yessen Can you open a PR from that branch? That is the easiest way to get the code reviewed and get feed back.

I think we install ffmeg on travis so you should be able to write an automated test for this.
