### ISSUE TITLE
[Bug]: `set_text` does not work when accessed from `axis.get_xticklabels`

### ISSUE THREAD

**Issue by hoxbro** [matplotlib/matplotlib#28224]
### Bug summary

I want to update the x-ticks label in a for loop with `set_text`, but it does not update the text.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, axis = plt.subplots()
for t in axis.get_xticklabels():
    t.set_text('a')

plt.show()
```

### Actual outcome

Nothing happens with the xticklabels.

![Figure_1](https://github.com/matplotlib/matplotlib/assets/19758978/a2a739d2-55e8-48b7-8aa1-3343a33955a0)

### Expected outcome

I would expect all ticks on x-axis to be labeled 'a'. It works if I use `t.set_y` with the offset. 

### Matplotlib Version

3.8.4

### Installation

None

**Comment by tacaswell** [comment]
See https://matplotlib.org/devdocs/users/explain/axes/axes_ticks.html for details.

To get what you want use `ax.set_xticks(locs, labels=['a']*len(locs))`

The very short version is that the ticking system is made up of a locator (which decides where the tick should go) and the formatter (which decides what the tick label should be).  We do expose `Text` objects for the tick labels, however they are controlled by the ticking system so at draw time we will over-write the location and strings.  This is clearest when panning / zooming as the ticks must both move (on the screne) and get new labels.

It is an implementation details that `set_y` works because for efficiency reasons we re-use `Text` objects from a pool (rather than making new ones every time).

**Comment by hoxbro** [comment]
Thank you for the explanation.
