### ISSUE TITLE
[Bug]: Button causes window to hang

### ISSUE THREAD

**Issue by ohshitgorillas** [matplotlib/matplotlib#28319]
### Bug summary

I am designing mass spec data reduction software and, at one point, I am showing the user four subplots, and I give them a button to toggle one of the plots between two data sets.

This worked fine when I was using `matplotlib.pyplot`, however, switching to `matplotlib.figure` for tk compatibility has caused two errors to arise:
* `UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.`
* When toggling the plot rapidly, if one moves the mouse away from the button, then back over the button, it causes the program to hang.

### Code for reproduction

```Python
import random
import mplcursors
import customtkinter as ctk
from matplotlib.figure import Figure
from matplotlib.widgets import Button
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg

# create the window and frames
window       = ctk.CTk()
data_frame   = ctk.CTkFrame(window)
button_frame = ctk.CTkFrame(window)
data_frame.pack(side=ctk.TOP)
button_frame.pack(side=ctk.BOTTOM)

# lines to plot
lines = {}

# Create the figure and subplots
fig = Figure(figsize=(13, 9), tight_layout=True)
canvas = FigureCanvasTkAgg(fig, master=data_frame)
canvas.draw()
canvas.get_tk_widget().pack(side=ctk.TOP, fill=ctk.BOTH, expand=True)
axes = fig.subplots(2, 2)

# Create some sample data
x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y = {}
y_new = {}
for i in range(1, 101):
    y[i]     = [random.randint(1, 10) for _ in range(len(x))]
    y_new[i] = [random.randint(1, 10) for _ in range(len(x))]

# create a boolean var for toggling between y and y_new in 1,1
show_y_new = ctk.BooleanVar(False)

# Plot the normal data on each subplot
for i in range(2):
    for j in range(2):
        for k in range(1, 101):
            line, = axes[i, j].plot(x, y[k], label=f'Line {k}')
            lines[line] = line
                
# Create a cursor for hover indicators
cursor = mplcursors.cursor(lines, hover=True)
cursor.connect("add")
def on_hover(sel):
    x, y = sel.target
    sel.annotation.set_text(f"({x:.2f}, {y:.2f})")

# create a button to toggle the 1,1 subplot between y and y_new
def on_click(cursor):
    show_y_new.set(not show_y_new.get())
    if show_y_new.get():
        for line in lines:
            if line.axes == axes[1, 1]:
                line.set_ydata(y_new[int(line.get_label().split(' ')[1])])
    else:
        for line in lines:
            if line.axes == axes[1, 1]:
                line.set_ydata(y[int(line.get_label().split(' ')[1])])
            
    valid_lines = [line for line in lines.values() if line.figure is not None]
    canvas.draw()
    cursor.remove()
    cursor = mplcursors.cursor(valid_lines, hover=True)
    cursor.connect("add", on_hover)

# Create the toggle button
global button # do not remove-prevents garbage collection
button_axes = fig.add_axes([0.8885, 0.467, 0.1, 0.04])
button = Button(button_axes, label='Toggle 1,1 data')
button.on_clicked(lambda event: on_click(cursor))

# create the exit button
exit_button = ctk.CTkButton(window, text='Exit', command=window.destroy)
exit_button.pack(side='bottom')  # add the exit button to the window

# Show the plot
canvas.draw()
window.mainloop()
```

### Actual outcome

The new code with `matplotlib.figure` generates warning messages and can cause the program to hang when the button is toggled, then the mouse moves away from, and back over, the button.

### Expected outcome

The script behaves like before with `matplotlib.pyplot` with no warning message and doesn't hang.

### Operating system

Windows 11

### Matplotlib Version

5.3.5

### Matplotlib Backend

TkAgg

### Python version

3.7.9

### Installation

pip

**Comment by QuLogic** [comment]
Does the [Embedding in Tk example](https://matplotlib.org/stable/gallery/user_interfaces/embedding_in_tk_sgskip.html) work?

Sorry, your example is a bit too complicated. Do you really need `mplcursors`? What is `customtkinter`, and is it required to reproduce the problem?

**Comment by ksunden** [comment]
The warning about tight layout is because of the new Axes added for the button specifically, which is placed with exact numbers and therefore not compatible with layout managers.

Using `layout="constrained"` (instead of `tight_layout=True`) and calling  `button_axes.set_in_layout(False)` will get rid of the warning.

I'm 90% sure your "freezing" problem is that your lambda for you `button.on_clicked` is referring to your first cursor and then doesn't get updated.

I removed `mplcursors` (and switched to only standard TK) and everything seemed to work.

For me, adding back in the cursors, it does not freeze, but does not correctly remove the cursor, resulting in 2 (probably actually more, but overlapping) cursors. It then becomes slow to a degree. So having many cursors is the reason it is slow.

Using a `global cursor` rather than passing it in as a parameter _works_, but there may be more elegant solutions... but regardless, at that point is not really a matplotlib thing at that point.

**Comment by ohshitgorillas** [comment]
Unfortunately, not using tight layout isn't an option unless I want to manually define the location of every plot, which I really really don't. Constrained looks.... bad. Here's an example

constrained:
![image](https://github.com/matplotlib/matplotlib/assets/96808410/96e49266-0065-4bad-97a0-6b829fb7b395)

tight:
![image](https://github.com/matplotlib/matplotlib/assets/96808410/0e745f06-591c-45ae-8dcb-5f756f9a44f3)

Is my only option to avoid this warning to manually define and align ALL of my plots?

**Comment by ksunden** [comment]
https://matplotlib.org/stable/users/explain/axes/constrainedlayout_guide.html#padding-and-spacing

You may find that you can get what you want by changing from the default spacing parameters, or potentially by using `"compressed"` instead (compressed is a special case of constrained)

To be honest, in the context of the example script here, there isn't really much of any difference between the various layout managers, probably because they don't have axis labels and titles. (as well as if the additional things on the left are matplotlib drawn, can't fully tell from the image), so hard to judge from a distance.

lots of factors go into it, but in general constrained is pretty capable/generally more configurable than tight.

**Comment by rcomer** [comment]
Does tight layout not respect the _in_layout_ setting?  The [docstring](https://matplotlib.org/3.5.3/api/_as_gen/matplotlib.artist.Artist.set_in_layout.html) suggests it should.
