### ISSUE TITLE
[Bug]: ImportError: DLL Load Failed

### ISSUE THREAD

**Issue by sushimonk345** [matplotlib/matplotlib#28328]
### Bug summary

I installed the lib through PIP on terminal, tried running a sample matplotlib script from online, but it gave me the error, both on Python IDLE and also on VScode. I uninstalled both Python and VScode, but it didn't solve anything. The version I use for Matplotlib is 3.9.0 and the version of python is the latest 3.12.3. I also used numpy in the sample code.

### Code for reproduction

```Python
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(5, 4), dpi=72)
axes = fig.add_axes([0.01, 0.01, .98, 0.98])
X = np.linspace(0, 2, 200)
Y = np.sin(2*np.pi*X)
plt.plot(X, Y, lw=2)
plt.ylim(-1.1, 1.1)
plt.grid()

plt.show()
```

### Actual outcome

![Screenshot 2024-06-02 152529](https://github.com/matplotlib/matplotlib/assets/161652064/a0ffcdcd-c816-4d1b-88b0-cf871cd7bd43)

### Expected outcome

![Screenshot 2024-06-02 161521](https://github.com/matplotlib/matplotlib/assets/161652064/ff61ce38-7ba0-4325-844e-7cba8bdf0f8d)

### Additional information

I consulted on Discord first, where after trying multiple suggestions, nothing fixed it, even after uninstalling the dependencies that came with MTPLT and reinstalling them. As mentioned above, I uninstalled everything and tried again, just to see the same error.

### Operating system

Windows 11

### Matplotlib Version

3.9.0

### Matplotlib Backend

Doesn't work with this code either

### Python version

3.12.3

### Jupyter version

None

### Installation

pip

**Comment by tacaswell** [comment]
Can you import `kiwisolver` directly rather than implicitly via Matplotlib?

What version of kiwisolver do you have installed?  Can you try reinstalling kiwisolver (and be sure you are getting the wheel from pip not the sdist (which requires you to be able to compile it)).

You should also consider switching to one of the conda-based distributions ( https://conda-forge.org/download/ , https://www.anaconda.com/download , or https://prefix.dev) which will have fewer build/install edge cases than pip+wheels.


-----

In the future, please post error messages as copy-pasted text not images.  It is easier to read and to copy-paste from to work on.

**Comment by hjhzdbssmsbrj** [comment]
I understand you're facing an `ImportError: DLL Load Failed` issue with Matplotlib. Here are some potential solutions:

1. **Check and Reinstall `kiwisolver`**:

   - Sometimes, the issue might be with the `kiwisolver` dependency. Try importing `kiwisolver` directly to ensure it's working.

   - Reinstall `kiwisolver` using the following commands, and make sure to get the wheel package:

     ````
     pip uninstall kiwisolver
     pip install kiwisolver --prefer-binary
     ````

2. **Switch to Conda-based Distributions**:

   

   - Conda-based distributions (like Conda Forge or Anaconda) often have fewer build/install issues compared to pip + wheels.
   - You can download and install Conda from [Conda Forge](https://conda-forge.org/download/) or [Anaconda](https://www.anaconda.com/download).
   - After installing Conda, use the following command to install Matplotlib

   ````
   conda install matplotlib
   ````

3. **Ensure a Clean Environment**:

   - Make sure to completely uninstall any previous Python environment and related libraries before reinstalling to avoid conflicts and leftover issues.

4. **Check Dependency Versions**:

   - Verify that all installed dependencies are compatible with Matplotlib 3.9.0. You can use the following command to list installed packages:

     pip list

**Comment by sushimonk345** [comment]
> Can you import `kiwisolver` directly rather than implicitly via Matplotlib?
> 
> What version of kiwisolver do you have installed? Can you try reinstalling kiwisolver (and be sure you are getting the wheel from pip not the sdist (which requires you to be able to compile it)).
> 
> You should also consider switching to one of the conda-based distributions ( https://conda-forge.org/download/ , https://www.anaconda.com/download , or https://prefix.dev) which will have fewer build/install edge cases than pip+wheels.
> 
> In the future, please post error messages as copy-pasted text not images. It is easier to read and to copy-paste from to work on.

Thank you. The kiwisolver reinstall method didn't work, but after using the conda forge dist, it actually was able to run it with no problems. I'm a beginner so I had no idea what to do and how to post errors, but I will take your advice and actually copy paste the code. Thank you.

**Comment by sushimonk345** [comment]
> I understand you're facing an `ImportError: DLL Load Failed` issue with Matplotlib. Here are some potential solutions:
> 
> 1. **Check and Reinstall `kiwisolver`**:
>    
>    * Sometimes, the issue might be with the `kiwisolver` dependency. Try importing `kiwisolver` directly to ensure it's working.
>    * Reinstall `kiwisolver` using the following commands, and make sure to get the wheel package:
>      ```
>      pip uninstall kiwisolver
>      pip install kiwisolver --prefer-binary
>      ```
> 2. **Switch to Conda-based Distributions**:
>    
>    * Conda-based distributions (like Conda Forge or Anaconda) often have fewer build/install issues compared to pip + wheels.
>    * You can download and install Conda from [Conda Forge](https://conda-forge.org/download/) or [Anaconda](https://www.anaconda.com/download).
>    * After installing Conda, use the following command to install Matplotlib
>    
>    ```
>    conda install matplotlib
>    ```
> 3. **Ensure a Clean Environment**:
>    
>    * Make sure to completely uninstall any previous Python environment and related libraries before reinstalling to avoid conflicts and leftover issues.
> 4. **Check Dependency Versions**:
>    
>    * Verify that all installed dependencies are compatible with Matplotlib 3.9.0. You can use the following command to list installed packages:
>      pip list

Thank you very much. The conda forge dist worked and I realized that I wasn't even using a venv and I was trying to pip the library on the base interpreter, which was probably what led to the whole thing coming down. I also used PyCharm instead of VS Code, so I believe that also helped with its built-ins. Thank you.

**Comment by tacaswell** [comment]
@sushimonk345 Great, I'm glad you got this sorted!

On the positive side, there are a lot of different ways to get, install, and manage Python dependencies so that there is very likely one who's assumptions match your needs, and on the negative side, there are a lot of different ways to get, install, and manage Python dependencies so it can be very daunting to sort out which one you should use as a beginner (only made worse by finding short suggestions where it is unclear which of the systems the author is coming from).

If you are new to Python (and programming?) and want to work with scientific python / data science packages I strongly suggest you go with conda as the package manager + conda-forge as the channel and always use environments (that way if you break it, you "fix" it by delete it and trying again).  I would only reach for pip in the case where the package you want is not built and published on conda-forge.  By sticking with one source of your packages you will be able to avoid a lot of ... less than fun packaging issues (the biggest source of issues is when you try to use multiple package manager in the same environment at the same time and they fight).

**Comment by sushimonk345** [comment]
Very well! I'll keep the advice and carry on. Thank you!
