### ISSUE TITLE
[Bug]: Labels don't get wrapped when set_yticks() is used in subplots

### ISSUE THREAD

**Issue by soogui** [matplotlib/matplotlib#28358]
### Bug summary

When plotting bar charts in subplots with very long labels, the option of wrapping text only works on the first plotted subplot, despite passing `wrap=True` to `set_yticks()` in both cases.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np

long_text_label = 'very long category label i want to wrap'
labels = [f"{long_text_label}_{i}" for i in range(5)]
values = np.arange(1, 6)

fig, axes = plt.subplots(1, 2)

axes[0].barh(np.arange(len(labels)), values)
axes[0].set_yticks(np.arange(len(labels)), labels=labels, wrap=True)

axes[1].barh(np.arange(len(labels)), values)
axes[1].set_yticks(np.arange(len(labels)), labels=labels, wrap=True)
```

### Actual outcome

![output](https://github.com/matplotlib/matplotlib/assets/35564508/137c042d-a536-4a27-9991-e4e0a67ea527)

### Expected outcome

The label text on the y axis should appear wrapped on both subplots

### Operating system

macOS 14.4 (23E214)

### Matplotlib Version

3.8.3

### Matplotlib Backend

module://matplotlib_inline.backend_inline

### Python version

Python 3.11.8

### Jupyter version

4.2.0

### Installation

pip

**Comment by rcomer** [comment]
Thanks for the clear report @soogui.  I confirm that I have reproduced this with our `main` development branch.

**Comment by jklymak** [comment]
I'm not clear what the correct behaviour is here though.  Currently it's wrapping on the edge of the figure.  What would the inner axes wrap on?  The axes to the left presumably, but that isn't conceptually straight forward as an axes knows about its figure but not about its neighbours, and it knows its own spine position but doesn't try to reserve space for itself outside those spines.  Note we usually do the opposite and make the axes further apart to accommodate the ytick labels.

**Comment by timhoffm** [comment]
For the current architecture, this is the expected behavior. We should better document what `warp` can or can't do.

I see two possible ways to improve:
- hard: Assign each axes a bounding box. This should work well with subplots/subplot_mosaic, but I'm unclear how other axes creation methods would handle this. Up to now, the Axes is defined via the data area, ticks and labels just spill outside as far as they need.
- medium: Expand the `wrap` functionality to allow wrapping after N characters and/or specifying a maximal width.

**Comment by jklymak** [comment]
I think the conceptually simplest is to not allow auto wrap for tick labels.  Folks can manually wrap if they need to.

**Comment by timhoffm** [comment]
Well, the case of one subplot with long tick labels works. IMHO we should not break that.

**Comment by timhoffm** [comment]
@jklymak When #28177 is in, we could switch the wrapping box (in `Text._get_wrap_line_width`) to subfigure instead of figure. IMHO this boundary makes more sense. And it would at least allow to get what the OP wants using subfigures:

```
import matplotlib.pyplot as plt
import numpy as np

long_text_label = 'very long category label i want to wrap'
labels = [f"{long_text_label}_{i}" for i in range(5)]
values = np.arange(1, 6)

fig = plt.figure()
subfigs = fig.subfigures(1, 2)
ax0 = subfigs[0].subplots()
ax1 = subfigs[1].subplots()

ax0.barh(np.arange(len(labels)), values)
ax0.set_yticks(np.arange(len(labels)), labels=labels, wrap=True)

ax1.barh(np.arange(len(labels)), values)
ax1.set_yticks(np.arange(len(labels)), labels=labels, wrap=True)
```

**Comment by jklymak** [comment]
That's likely fine. However it should be noted that even in the single subplot situation the wrap is incompatible with layout management since that adjusts the size of the axes to account for the size of the labels versus wrapping the labels. 

As stated I am mildly opposed to us jumping through hoops to allow wrapping tick labels because I don't think it s a generally useful thing to do. However if the issues with wrapping tick labels also extends to other text boxes in subfigures, that might merit some effort to fix.

**Comment by timhoffm** [comment]
When #28401 is in, one can write the original plot using subfigures:

```
import matplotlib.pyplot as plt
import numpy as np

long_text_label = 'very long category label i want to wrap'
labels = [f"{long_text_label}_{i}" for i in range(5)]
values = np.arange(1, 6)

fig = plt.figure(layout="constrained")
fig1, fig2 = fig.subfigures(1, 2)
ax1 = fig1.add_subplot()
ax2 = fig2.add_subplot()


ax1.barh(np.arange(len(labels)), values)
ax1.set_yticks(np.arange(len(labels)), labels=labels, wrap=True)

ax2.barh(np.arange(len(labels)), values)
ax2.set_yticks(np.arange(len(labels)), labels=labels, wrap=True)
plt.show()
```
![grafik](https://github.com/matplotlib/matplotlib/assets/2836374/b679590e-c053-4c87-9b6e-10fd997ebc4d)
