### ISSUE TITLE
[MNT]: Last version unavailable in conda and/or pip

### ISSUE THREAD

**Issue by aebaci** [matplotlib/matplotlib#28466]
### Summary

Hi. I've been trying unsuccesfully to install the latest version in a conda environment. I tried using conda and pip. In Anaconda, the latest version is 3.8.4
I've been having an issue with another software (AttributeError: module 'matplotlib' has no attribute 'colormaps') which I hoped would be solved by the latest version. Thanks.

**Comment by tacaswell** [comment]
I'm sorry you are having issues, however I am not sure what we can do to help.

There is an sdist and wheels for mpl 3.9 on pypi (https://pypi.org/project/matplotlib/#history) .

There is some issue with building 3.9 on conda-forge (https://github.com/conda-forge/matplotlib-feedstock/pull/373) please follow that work there.

We have no control over the default anaconda channel, please report this through their support.

The `matplotlib.colormaps` was added in matplotlib 3.5 so based on this information I do not think that 3.9 will fix your problem in 3.8.4 does not work.  I suggest that you report that issue to the maintainers of the other software (they will appreciate if you give them the full traceback not just the last line).

I am going to close this because I do not think there is anything we can do to solve these problems on the Matplotlib side of things (and are being tracked else where).  For general questions about Matplotlib usage I suggest posting questions to https://discourse.matplotlib.org .
