### ISSUE TITLE
[Doc]: matplotlib.pyplot.specgram parameters vmin and vmax are not documented

### ISSUE THREAD

**Issue by johann-petrak** [matplotlib/matplotlib#28548]
### Documentation Link

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.specgram.html#matplotlib-pyplot-specgram

### Problem

Parameters vmin and vmax are shown as possible keyword args to the specgram function but unlike the other parameters, these two are not documented or mentioned at all. 
Unless somebody is already very familiar with the matplotlib package and its naming conventions and other functions, it is close to impossible to figure out what these parameters actually are here for. 
Especially since what is missing most from this function is a way to limit the frequency axis span, but instead these parameters appear to filter/rescale the actual spectrum values before they get shown. 

### Suggested improvement

Please just document what these parameters are here for like all others for that function.

**Comment by yuanx749** [comment]
vmin and vmax are passed on to `imshow` like other kwargs, but since they are in the signature of the function `specgram`, I agree it is better to document them.

**Comment by rcomer** [comment]
Another option would be to remove these from the signature so that they are included with "kwargs are passed to `imshow`", but I think that would require a deprecation period first to make them keyword-only.

So I agree just documenting them in this signature is the simplest option, and the only immediate fix.

**Comment by Alsosa** [comment]
Hi, I would like to work on this issue. It would be my first contribution so I'd like to make sure I'm doing this the right way.
I was reading the code and for what I understand, I could add the documentation of vmin and vmax parameters for 'specgram' the same way they are added in 'imshow', using the interpd decorator, is that correct?

**Comment by rcomer** [comment]
Thanks @Alsosa!  In this case I think it may make sense to write something more specific for `specgram`, as parts of the description used in `imshow` and elsewhere may not make sense here, e.g.

- "When using scalar data" - is this needed or would `specgram` always be using scalar data?
- "the colormap covers the complete value range of the supplied data" in `specgram`’s case the data that is plotted is not directly the data that the user supplied, so some re-wording here might make sense.

What do you think?

**Comment by Alsosa** [comment]
Thanks @rcomer! I'll do it that way!

**Comment by ian1203** [comment]
Hi, first time contributing here, I'm not sure if I'm too late, but I think there are a few things that could be added to improve your documentation:
`vmin` and `vmax` define the data range that the colormap covers, where `vmin` sets the lower limit and `vmax` sets the upper limit. By default, the colormap covers the complete value range of the data, but adjusting the values of `vmin` and `vmax` help to highlight features. It is an error to use `vmin`/`vmax` when a norm instance is given (but using a [str](https://docs.python.org/3/library/stdtypes.html#str) norm name together with `vmin/vmax` is acceptable). These parameters are ignored when plotting in RGB(A), since this data uses straight color values instead of a colormap. Furthermore, in cases like logarithmic normalization (`LogNorm`), the parameters must be positive due to the mathematical properties of logarithmic scaling. 

Slight changes and maybe a bit intuitive, but I find it better to see everything clear, hopefully it's useful.

**Comment by rcomer** [comment]
Closed by #28613.
