### ISSUE TITLE
[Doc]: Version switcher is broken

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#28639]
### Problem

- Start at: https://matplotlib.org/stable/ - the switcher shows "choose version" (?)
- In the switcher select "3.10 (dev)" - you are directed to the correct page but the switcher still shows "choose version"
- In the switcher select "3.9 (stabe)" - you are directed to the correct page but the switcher still shows "choose version"
- In the switcher select "3.8" - you are directed to the correct page but the switcher still shows "stable"
- In the switcher select "3.87 - you are directed to the correct page but the switcher again shows "stable" and is now broken (i.e. does not have a dropdown anymore)

### Suggested improvement

I'm not really sure what's going on. https://matplotlib.org/devdocs/_static/switcher.json is used, which is the correct file.

questions:
- is `version: "3.9.1"` in switcher.json correct or should this be `version: "stable"`?
- I don't really understand the config `switcher` / `version_match`. [pydata-sphinx-theme docs](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/version-dropdown.html#version-switcher-dropdowns) say

  > a string stating the version of the documentation that is currently being browsed.

  Is the change in #23175 ok to set this to "stable" or does this have to be a unique name across versions?

**Comment by QuLogic** [comment]
3.7 is probably broken because it used an older version of the theme, and the switcher json may have changed a bit since.

The rest are broken because our `version_match` setting is wrong; it currently picks either `'stable'` or `'devdocs'`, neither of which are used in the `switcher.json`. Prior to #28512, `'stable'` was a thing, but this broke the banner; but it makes no sense to use that; as you have noted, on older versions,

**Comment by QuLogic** [comment]
> * Start at: https://matplotlib.org/stable/ - the switcher shows "choose version" (?)

I pushed https://github.com/matplotlib/matplotlib.github.com/commit/4eabb2bb2ef9f0ba307a1a723143ccbf200f210e which applies the linked PR to the published docs, and fixed these pages.

> * In the switcher select "3.10 (dev)" - you are directed to the correct page but the switcher still shows "choose version"

This should be fixed by #28644.

> * In the switcher select "3.9 (stabe)" - you are directed to the correct page but the switcher still shows "choose version"

See first point.

> * In the switcher select "3.8" - you are directed to the correct page but the switcher still shows "stable"

I pushed https://github.com/matplotlib/matplotlib.github.com/commit/fd6b5d235d7042d8220df30bffce1f84b467e9c8 which backported the theme fixes and fixes these pages.

> * In the switcher select "3.7" - you are directed to the correct page but the switcher again shows "stable" and is now broken (i.e. does not have a dropdown anymore)

Here the JavaScript raises on missing `jQuery` before it can populate everything; possibly we updated Sphinx and not pydata-sphinx-theme, but I'm not sure exactly which versions were used for that build. I pushed https://github.com/matplotlib/matplotlib.github.com/commit/1fca7e7b69cdbcd1ff9af764de00634300aa34cd which restores jQuery on the files, and fixes populating the dropdown.

And then I also backported https://github.com/matplotlib/matplotlib.github.com/commit/691be21a439a34158af71eb05df0b164c9b4d8aa which fixed 3.6 and 3.7

**Comment by QuLogic** [comment]
> Here the JavaScript raises on missing `jQuery` before it can populate everything; possibly we updated Sphinx and not pydata-sphinx-theme, but I'm not sure exactly which versions were used for that build. I pushed matplotlib/matplotlib.github.com@1fca7e7b69cdbcd1ff9af764de00634300aa34cd which restores jQuery on the files, and fixes populating the dropdown.

One more followup here which fixes the `jQuery` references for files 3.7 that are in subdirectories: matplotlib/matplotlib.github.com@8fd7442188d3bcbc33df99ea0ffcbd749b700e22
