### ISSUE TITLE
[ENH]: AxLine xy1/xy2 setters should take xy as single parameters, (possibly) not separate ones

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#28800]
### Problem

Currently, AxLine.set_xy1 and set_xy2 take x and y as separate parameters.  They should also take them as a single `xy` parameter, which is consistent with most other setters and would in particular allow the idiom `line.set(xy1=..., xy2=...)` (or `line.set(xy1=..., slope=...`).

### Proposed solution

Given that the setters were only introduced only in Matplotlib 3.8, we could even consider just deprecating the split (x, y) form out and ultimately only supporting a single xy tuple (tagging this issue for 3.10 as we probably don't want to wait too long in that case); or we can support both forms with the standard dance present e.g. in Axes.set_xlim.

**Comment by timhoffm** [comment]
I see the need. I believe we're quite inconsistent with this throughout the library.

There's always a tradeoff between simplicity, consistency and usability. I'm not decided whether the slightly simpler code and documentation outweighs the need for users to write `set_xy1((x, y))` - it's easy to forget the additional braces, in particular also because we have that in other places.

Anyway, we need to start with supporting both for compatibility reasons. When we have that implementation, it's possibly easier to decide whether it's simple enough or whether we want to get rid of it.
