### ISSUE TITLE
PGF backend messes up fill

### ISSUE THREAD

**Issue by ibell** [matplotlib/matplotlib#2885]
I have a figure that I need to compile using PGF backend because the \Game symbol is incorrect (another issue will be opened for that problem).

But when I do, the curves bounding the fill seem to get cropped to the visible window, which breaks the fill, as seen here:

![ddlabeled](https://f.cloud.github.com/assets/1859947/2372461/caffe8b6-a83a-11e3-96a1-6fbc26fbdefb.jpg)

When using the other backends, this behavior is not seen, for instance, 
![ddlabeled](https://f.cloud.github.com/assets/1859947/2372475/e6b08f70-a83a-11e3-9eaf-8f13e9886077.png)

**Comment by pwuertz** [comment]
In reported duplicates and other related issues @mdboom mentioned that the clipping implementation matplotlib provides when iterating over path segments doesn't work for filled paths. I didn't know about this limitation when enabling path clipping in order to get rid of #1857. I'll prepare a fix for disabling clipping of filled paths - which is what other backends do as well if I understood correctly. Once a fill-aware clipping technique is implemented this restriction should be lifted again.

**Comment by pqrs6** [comment]
I don't know if this issue has been officially resolved yet, but I'm still having some problems with this. Using Matplotlib 1.4.3 I get the clipping, but in version 1.4.0 the fill stays the same, no problem.

Here's my example and the plot it generates:

        import matplotlib as mpl
        import numpy as np
        mpl.use('pgf')
        print(mpl.__version__)

        import matplotlib.pyplot as plt

        x = np.linspace(0,2*np.pi)
        y = np.sin(x)
        plt.subplot(221)
        plt.fill_between(x,0,0.5,color='0.7')
        plt.plot(x,y,'k')
        plt.xlim([0,2*np.pi])

        plt.subplot(222)
        plt.fill_between(x,0,0.5,color='0.7')
        plt.plot(x,y,'k')
        plt.xlim([1,5])

        plt.subplot(223)
        plt.fill_between(x,0,0.5,color='0.7')
        plt.plot(x,y,'k')
        plt.xlim([0,5])

        plt.subplot(224)
        plt.fill_between(x,0,0.5,color='0.7')
        plt.plot(x,y,'k')
        plt.xlim([1,2*np.pi])


        plt.savefig('filltest.png')


![filltest](https://cloud.githubusercontent.com/assets/6478137/8383897/2d77467a-1c0b-11e5-9442-a0bd878dce9f.png)

**Comment by pwuertz** [comment]
No, filled path clipping is still a known problem. The fills you are using however are not clipped and should work. I ran your example on my machine with the current matplotlib master and everything looks fine here, couldn't reproduce the error you posted.
Does this clipping error also appear in the PDF output? And you are saying that using matplotlib 1.4.0 instead of 1.4.3 fixes the problem for you?

**Comment by tacaswell** [comment]
This seems to be fixed on master 

![filltest](https://cloud.githubusercontent.com/assets/199813/8385228/ddfcd22c-1c14-11e5-9dd3-483e523d2d5b.png)

**Comment by pqrs6** [comment]
Hm, definitely a user error going on somewhere here...

So on one computer, with version 1.4.0., in all outputs with the pgf backend (.png, .pdf, .pgf in a TeX document) there's no clipping error, but these all show up on my other computer with version 1.4.3.

I'm using an Anaconda distribution, and have been trying to update with pip and conda. How do I update my distribution to match with master?

**Comment by pqrs6** [comment]
Hm, definitely a user error going on somewhere here...

So on one computer, with version 1.4.0., in all outputs with the pgf backend (.png, .pdf, .pgf in a TeX document) there's no clipping error, but these all show up on my other computer with version 1.4.3.

I'm using an Anaconda distribution, and have been trying to update with pip and conda. How do I update my distribution to match with master?

**Comment by tacaswell** [comment]
To get master you will have to install from source (which if you are on a linux or mac box is not too bad, `python setup.py install` works as expected).

What looks like happened is that it works with 1.4.0, we had a regression and we fixed it again on the master branch.

If you want to down-grade your conda installation to 1.4.0 do `conda install matplotlib==1.4.0`

**Comment by pwuertz** [comment]
The changes causing this problem got introduced in 9e1b7aee1224475c27f80a4200852176d90f71e4. The commit also broke the backend, which was restored at 73b7b7c3cf330c4d4f58f101496e9ccb164427ed. The commit in master that fixes the problem again is 3f80c7018cf5ce53d9b278c829d1d913cee0557d. My brain hurts by the way because apparently you cannot reverse the order of good and bad in git bisect, you have to force yourself to invert good/bad when you are looking for a fixing commit.

**Comment by pwuertz** [comment]
Oops, there are even references for this fix in this thread from earlier this year (19. Mar.). Incredible how fast I forgot about this..
