### ISSUE TITLE
[Bug]: hist()'s doc for edgecolors/facecolors does not match behavior (which is itself not very consistent)

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#28873]
### Bug summary

The docs for `hist` state
```
**kwargs
    `~matplotlib.patches.Patch` properties. The following properties
    additionally accept a sequence of values corresponding to the
    datasets in *x*:
    *edgecolors*, *facecolors*, *lines*, *linestyles*, *hatches*.
```
but this does not match actual behavior

### Code for reproduction

```Python
from pylab import *
hist(randn(100), facecolor="red")  # works
hist(randn(100), fc="red")  # silently does nothing
hist(randn(100), facecolors="red")  # crashes (Rectangle.set() got an unexpected keyword argument 'facecolors')

# and likewise for edgecolor(s)
```

### Actual outcome

See above.

### Expected outcome

At least the documentation and the behavior should match.  Bonus points if all three kwarg forms (facecolor/fc/facecolors) are supported.

### Operating system

any

### Matplotlib Version

3.10.0.dev645+gcb9cf3bbb1

### Matplotlib Backend

any

### Python version

3.12.2

### Jupyter version

no

### Installation

git checkout

**Comment by timhoffm** [comment]
The functionality was recently added in #28073.

The relevant code is:

https://github.com/matplotlib/matplotlib/blame/65878f3469da914e1399622ff5996c05ce0a4e73/lib/matplotlib/axes/_axes.py#L7212-L7234

To follow implementation, the documentation should read:
```
*edgecolor*, *facecolor*, *linewidth*, *linestyle*, *hatch*.
```
instead of
```
*edgecolors*, *facecolors*, *lines*, *linestyles*, *hatches*.
```

I believe this is the minimal API we must provide for consistency within the function. Before this PR, `color` and `label` accepted list inputs. Therefore, we should support the singular names. Plurals and abbreviations may come later. I suspect we should write helper functions to consolidate/normalize the different parameter names.

**Comment by anntzer** [comment]
At least the documentation issue should be release critical.

**Comment by timhoffm** [comment]
#28875 is a minimal fix for the documentation. That should solve the release-critical documentation aspect of this issue, but will not close it completely.

**Comment by timhoffm** [comment]
The documentation is fixed. To keep the remaining topic more focussed, I've created #28884, which covers the consistency aspect.
