### ISSUE TITLE
[Bug]: Lines between points are invisible when there are more than 7 subfigures per row

### ISSUE THREAD

**Issue by vealocia** [matplotlib/matplotlib#28893]
### Bug summary

When there are more than 7 sub figures per row, the line between points will be invisible for the last several subfigs.

### Code for reproduction

```Python
import matplotlib.pyplot as plt

subfig_size = (16, 9)

num_subfigs = 10
fig, axes = plt.subplots(1, num_subfigs, figsize=(num_subfigs * subfig_size[0], 1 * subfig_size[1]), dpi=300)
for j in range(num_subfigs):
    xs = list(range(10))
    ax = axes[j]
    
    ax.plot(xs, xs, marker='x', label=f"test", linewidth=3, markersize=10)

plt.savefig('test.jpg')
```

### Actual outcome

![test](https://github.com/user-attachments/assets/df25f853-214b-48b3-9892-610c600df665)

### Expected outcome

Line should be visible!

### Additional information

What are the conditions under which this bug happens? input parameters, edge cases, etc?
* matplotlib==3.9.2
Has this worked in earlier versions?
* Tried 3.5.0, but still not works

### Operating system

Ubuntu

### Matplotlib Version

3.9.2

### Matplotlib Backend

qtagg

### Python version

3.10.9

### Jupyter version

6.5.2

### Installation

pip

**Comment by ksunden** [comment]
This is likely not due to the number of subfigs, but rather the number of pixels. 

Agg (the renderer we most commonly use) has some fairly deep fundamental limitations when it comes to rendering on large canvases, which have some complicated relationships with how various elements are drawn (hence why markers and text still show up, but lines do not)

You are making a figure that is 160 inches wide at 300 dpi. I expect that if you lower the DPI, it will work for more figures, but regardless, we just simply cannot render it with Agg.

Agg has a limit of 2**15 = 32,768 pixels in each dimension. In your example, that is exceeded by the 7th subfigure (7*16*300 = 33,600), hence why it happens then.

Unfortunately it is unlikely to be changed any time soon, as it is pretty deeply ingrained and therefore hard to change.

Solutions may include, and which one is appropriate will vary based on specific usecases:
- smaller figures
- lower resolution (does it need to be 300 DPI)
- multiple figures (does it need to be one figure, can it be composed in an external image editor?)
- Using a cairo based backend?
  - I have not tried this recently, but know the specific limitation is in Agg, so other renderers may not be affected.
  - There are likely _some_ size limitation still, not sure if they are the same size though.
  
See also:

#26751

#26368

Probably more, these are just the more recent ones I found of effectively the same thing

**Comment by vealocia** [comment]
Thanks for your quickly reply! I will divide and draw each subfigure separately!
