### ISSUE TITLE
[Bug]: Enforce that Line data modifications are sequences

### ISSUE THREAD

**Issue by andyfaff** [matplotlib/matplotlib#28927]
### Bug summary

It used to be possible to use `Line2D.set_ydata` with a single scalar. From a quick search I think this behaviour was changed in #22329, and I guess it makes sense for a lot of cases. However, I don't think mandating a sequence really makes sense when `Line2D` was created by `ax.axhline`, or `ax.axvline`, because those two methods use scalars themselves, not sequences.

### Code for reproduction

```Python
fig, ax = plt.subplots()
l = ax.axvline(x=10)
l.set_xdata(15)
```

### Actual outcome

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[8], line 4
      2 fig, ax = plt.subplots()
      3 l = ax.axvline(x=10)
----> 4 l.set_xdata(15)

File [~/miniforge3/envs/dev3/lib/python3.12/site-packages/matplotlib/lines.py:1289](http://localhost:8888/lab/tree/data/reduce/~/miniforge3/envs/dev3/lib/python3.12/site-packages/matplotlib/lines.py#line=1288), in Line2D.set_xdata(self, x)
   1276 """
   1277 Set the data array for x.
   1278 
   (...)
   1286 set_ydata
   1287 """
   1288 if not np.iterable(x):
-> 1289     raise RuntimeError('x must be a sequence')
   1290 self._xorig = copy.copy(x)
   1291 self._invalidx = True

RuntimeError: x must be a sequence
```

### Expected outcome

A plot with horizontal/vertical line

### Matplotlib Version

3.9.2

### Installation

pip

**Comment by timhoffm** [comment]
There is no easy solution.

The created Line2D is a generic independent object, which doesn't know about the "single y-value" property of a horizontal line.
Not allowing scalar values makes sense there.

Options are:
1) Accept scalar values in Line2D - we decided explicitly against this in #22329.
2) Create a (sub?)class HorizontalLine2D - This would go into the direction of semantic Artists, which we are basically open for. But I'm not convinced it makes sense to have an individual Artist for every function.
3) Make the behavior of Line2D configurable, easiest through a simple `Line2D._allow_scalar_y` that `axvline` would overwrite. But this is either quite hacky because do is silently (i.e. also the set_ydata documentation would not reflect it), or we'd have to promote it to a regular feature, which does not really make sense for Line2D and adds complexity.
4) Do nothing and live with the surprise and inconvenience that you have to pass two values.

My preference is (4) > (2) > (1) > (3)

**Comment by andyfaff** [comment]
I came across this because I'd had code that was working for a long time (axvline + axhline), and suddenly set_ydata/set_xdata failed, without a visible deprecation warning. I fixed the code in my project, and because we make regular releases it'll limit the fallout. Perhaps a documentation fix will be enough?
