### ISSUE TITLE
[Bug]: calling title before making polar plot

### ISSUE THREAD

**Issue by qixdev** [matplotlib/matplotlib#28944]
### Bug summary

Hi, sorry to bother if it is not an issue at all.
Setting title first and then making polar plot messes up the plot and it makes the plot in usual cartesian plane

### Code for reproduction

```Python
import matplotlib.pyplot as plt

theta = [0, 1, 2, 3, 4, 5, 6]
r = [0, 1, 0.5, 1, 0.5, 1, 0]

plt.title("stuff")
plt.polar(theta, r)
plt.show()
```

### Actual outcome

It outputs a warning:
`<stdin>:1: UserWarning: Trying to create polar plot on an Axes that does not have a polar projection.`
And makes the plot:
<img width="571" alt="image" src="https://github.com/user-attachments/assets/7c0f6aae-1535-4cbe-8a2a-523483cfbb14">

### Expected outcome

Although the plot should have look like this:
<img width="558" alt="image" src="https://github.com/user-attachments/assets/cf28e56c-6bcd-4d2c-8b79-dcd4ac90e9b7">

### Operating system

OS/X

### Matplotlib Version

3.9.0

### Matplotlib Backend

macosx

### Python version

Python 3.12.0

### Installation

pip

**Comment by timhoffm** [comment]
This is basically expected behavior rooted in the implicit Axes creation of `pyplot`. All pyplot commands create an Axes if there is not one already, but if there is, they reuse an existing Axes. Thus, `plt.title()` creates a regular cartesian Axes and `polar()` tries to re-use it.

**Solution:** When making a polar plot with pyplot, the first call has to be `plt.polar()` because that ensures a polar Axes is created.

Though we may do better in communicating:

- the docs of `polar()` should mention that it must be the first command.
- we possibly should error out instead of issuing a warning.

**Comment by AbhinRustagi** [comment]
@timhoffm I'd be happy to work on this!
