### ISSUE TITLE
[Bug]: Incorrect Y limits

### ISSUE THREAD

**Issue by savitha-suresh** [matplotlib/matplotlib#28956]
### Bug summary

I am creating a dummy plot with 4 subplots. I set the y limits as -300 and 300 for each. But when the plot is drawn the y limits are always set to -200 and 200. Similarily, if i set to 150, it sets to 100. 
Is this expected behavior and is the reason mentioned in the doc or is this a bug?

### Code for reproduction

```Python
import matplotlib.pyplot as plt

fig, ax = plt.subplots(4, 1, sharex=True)

for i in range(4):
    ax[i].set_ylim((-300, 300))
    ax[i].set_ylabel(f"axis {i}")
fig.tight_layout()
plt.show()
```

### Actual outcome

<img width="635" alt="Screenshot 2024-10-09 at 2 40 54 PM" src="https://github.com/user-attachments/assets/2deae4a4-65fa-4c09-9ba0-d0a8cb53c8b0">

### Expected outcome

The limits should be -300 and 300 for each subplot. It never sets to 300 though.

### Matplotlib Version

3.9.2

### Installation

None

**Comment by timhoffm** [comment]
This is expected behavior. The limits are at -/+ 300. We just don't have ticks there, because by default ticks are placed by an [AutoLocator](https://matplotlib.org/stable/api/ticker_api.html#matplotlib.ticker.AutoLocator), which will never set ticks at 300.

It's a question of expectation what the ticks should be. More extreme examples: if the range was +/-299 or +/-301, where would you expect ticks to be?

You may use a `MaxNLocator` with appropriate settings, but if you fix the range manually and want three ticks, I'd explicitly set them:
```
ax[i].set_ylim((-300, 300))
ax[i].set_yticks([-300, 0, 300])
```

**Comment by WeatherGod** [comment]
To clarify a bit further, the limits are still actually -300 to 300, it is
just a question of what ticks to put down, and it choose -200, 0, and 200.
There is still space on the graph for data to go all the way down or up to
+/-300.

**Comment by savitha-suresh** [comment]
Got it thanks for your support.
