### ISSUE TITLE
[Bug]: Figure Number Gives Type Error

### ISSUE THREAD

**Issue by Murat65536** [matplotlib/matplotlib#28994]
### Bug summary

It looks like the `Figure` stub does not include the number variable, resulting in a type error.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
screen = plt.figure()
print(screen.number)
```

### Actual outcome

![Screenshot](https://github.com/user-attachments/assets/6cbdb071-b14e-4be3-a569-a60c889371e6)

### Expected outcome

![Screenshot](https://github.com/user-attachments/assets/b9911591-38bf-4c75-b9da-1bf8e3e85e2e)

### Additional information

I think that this bug is happening because the stub files do not include the number variable for Figure.

### Operating system

Windows 11

### Matplotlib Version

3.9.2

### Matplotlib Backend

tkagg

### Python version

3.12.5

### Installation

pip

**Comment by timhoffm** [comment]
The issue here is that `number` is not a native Figure attribute, but it is dynamically added by pyplot at

https://github.com/matplotlib/matplotlib/blob/9bfc330430b13753ba983549929e8c39ae5ee495/lib/matplotlib/_pylab_helpers.py#L111

This naturally does not work with static checkers.

IMHO we should get away from this dynamic way of working and instead make `number` a property, returning `self.canvas.manager.num` if that exists and `None` otherwise. AFAIK, the number is not meant to be changed and must stay in sync with the manager anyway.
