### ISSUE TITLE
[Bug]: Multiple 3D objects are not rendered correctly

### ISSUE THREAD

**Issue by insalt-glitch** [matplotlib/matplotlib#29060]
### Bug summary

When using multiple `plot_surface` calls in the same plot, where the surfaces intersect, they are not rendered correctly.

### Code for reproduction

```Python
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

X, Y = np.meshgrid([-1, 1], [-1, 1])
Z1 = np.zeros_like(X)
Z2 = np.array([[-1, -1,], [1, 1]])
ax.plot_surface(X, Y, Z1)
ax.plot_surface(X, Y, Z2)
plt.show()
```

### Actual outcome

One object always fully occludes the other.

### Expected outcome

Occlusion is handles based on whether a part of the part of the object is behind or in front of another one.

### Operating system

All

### Matplotlib Version

3.9.2

### Matplotlib Backend

tkagg

### Python version

3.12.7

### Installation

pip

**Comment by scottshambaugh** [comment]
Here's what your code generates:
![image](https://github.com/user-attachments/assets/0825301c-55da-48b7-91fe-08b3f12a3a68)

Unfortunately this is a limitation of the matplotlib 3D renderer. Matplotlib 3D is really a "2.5D" renderer, where each object is drawn all at once, so intersections do not properly render surfaces where they cross above and below each other.

Some more background, where the library [Mayavi](https://docs.enthought.com/mayavi/mayavi/) is recommended as an alternative tool: https://matplotlib.org/stable/api/toolkits/mplot3d/faq.html
A recent community question where [s3dlib](https://s3dlib.org/) is recommended as a matplotlib add-on that does proper rendering: https://discourse.matplotlib.org/t/plot-solid-3d-surface-on-top-of-another-one/24665

I'll close the ticket since this is a known issue that can't be fixed with the current renderer, but please feel free to ask follow-up questions if you have them!
