### ISSUE TITLE
[Bug]: plt.bar do not display histogram value

### ISSUE THREAD

**Issue by MoriDj** [matplotlib/matplotlib#29151]
### Bug summary

I would like to create a histogram from Skimage Dataset Brain image and display it with MatplotLib Bar.

Unfortunately this takes a long time and in the end it is not displayed. I use the whole thing in my Jupyter Notebook which is integrated via VSCode PlugIn.

### Code for reproduction

```Python
from skimage.exposure import histogram
import matplotlib.pyplot as plt
from skimage import data

plt.figure(figsize=(8,4)) # Create an empty figure with a specific screen size
pixel_counts, pixel_values = histogram(data.brain()[1,:,:]) # Calculate the image histogram
plt.bar(pixel_values, pixel_counts) # Plot the histogram
plt.show() # Show the plot
```

### Actual outcome

the outcome is empty bar plot (see the picture):

![image](https://github.com/user-attachments/assets/df5cfc9d-5d75-4378-8f24-deeb6bafa00e)

### Expected outcome

histogram value should be display as bar graph

### Additional information

if i change my code an reduce the size of the array than it work:

from skimage.exposure import histogram
import matplotlib.pyplot as plt
from skimage import data

plt.figure(figsize=(8,4)) # Create an empty figure with a specific screen size
pixel_counts, pixel_values = histogram(data.brain()[1,:,:]) # Calculate the image histogram
plt.bar(pixel_values[0:100], pixel_counts[0:100]) # Plot the histogram
plt.show() # Show the plot

![image](https://github.com/user-attachments/assets/b8001eed-4905-48d3-b2ac-8e6cf2e88232)

### Operating system

windows 11

### Matplotlib Version

3.8.4

### Matplotlib Backend

matplotlib_inline.backend_inline

### Python version

3.12.3

### Jupyter version

4.2.5

### Installation

conda

**Comment by jklymak** [comment]
Can you try converting whatever scikit is outputting to numpy arrays.

**Comment by rcomer** [comment]
`pixel_counts` and `pixel_values` each have 48401 elements so you are trying to plot that many bars.  The number of bars that can actually be visualised will be limited by the number of pixels in your plot window.  If I use `plt.plot` instead of `bar` I get this:

![image](https://github.com/user-attachments/assets/fd58bfe3-541a-4f3c-8aad-f08098de6e96)

**Comment by jklymak** [comment]
I'll close as "working as expected".

**Comment by djebemo** [comment]
> Can you try converting whatever scikit is outputting to numpy arrays.  

The output of skimage is a Numpy Array. You do not need any Addition conversion

**Comment by djebemo** [comment]
> `pixel_counts` and `pixel_values` each have 48401 elements so you are trying to plot that many bars.  The number of bars that can actually be visualised will be limited by the number of pixels in your plot window.  If I use `plt.plot` instead of `bar` I get this:
> 
> ![image](https://github.com/user-attachments/assets/fd58bfe3-541a-4f3c-8aad-f08098de6e96)
> 

You are right. I can display the Histogram values with plot, which Show that the code and data types are current. But i want to plot it with bar.

The question is whey it is not working? Is there any limitation? Or some Bug?

**Comment by timhoffm** [comment]
The underlying issue is that you have a lot more data points than pixel. The drawing mechanisms for lines and bars are different. When drawing a line, you visit all the data points and since you have more points than pixels, you draw on each pixel multiple times. Basically, the partial operation “draw a line from point i to i+1” will often be within the same pixel and just color that pixel. In contrast, `bar` creates unrelated rectangles. I don’t know the exact implementation of the renderer here, but if a rectangle is smaller than a pixel, there is no guarantee, it will be shown.
