### ISSUE TITLE
[Bug]: Introductory example on the pyplot API page does not show - missing plt.show()

### ISSUE THREAD

**Issue by sjlearmonth** [matplotlib/matplotlib#29227]
### Bug summary

https://matplotlib.org/3.9.3/api/pyplot_summary.html

The first example of Python code at the above URL does not work after adding the Matplotlib module in PyCharm CE 2024.2.5.

```
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 5, 0.1)
y = np.sin(x)
plt.plot(x, y)
```
unless it is edited to this...
```
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 5, 0.1)
y = np.sin(x)
fig = plt.figure(figsize=(10, 7))
plt.plot(x, y)
plt.show()
```

### Code for reproduction

```Python
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 5, 0.1)
y = np.sin(x)
plt.plot(x, y)
```

### Actual outcome

No figure was produced in the PyCharm CE 2024.2.5

### Expected outcome

<img width="1007" alt="Screenshot 2024-12-04 at 17 46 27" src="https://github.com/user-attachments/assets/0ed0ecda-a6c0-4e40-a6ec-3605bfc06394">

### Additional information

This is the "fix":

```
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0, 5, 0.1)
y = np.sin(x)
fig = plt.figure(figsize=(10, 7))
plt.plot(x, y)
plt.show()
```

### Operating system

MacOS 12.7.6

### Matplotlib Version

3.9.3

### Matplotlib Backend

Backend macosx is interactive backend. Turning interactive mode on. macosx

### Python version

```python --version``` crashes in PyCharm CE 2024.2.5 console.

### Installation

None

**Comment by sjlearmonth** [comment]
In MacOS Terminal ```python --version``` produces the output...
```
Python 2.7.10
```

**Comment by jklymak** [comment]
The use of `plt.show()` (or not) is discussed in the first few lines of the Quick Start Guide.  https://matplotlib.org/stable/users/explain/quick_start.html. This is also discussed in more detail at https://matplotlib.org/stable/users/explain/figure/figure_intro.html#introduction-to-figures

We are not going to litter `plt.show()` throughout the docs, I don't think

**Comment by sjlearmonth** [comment]
The example Python code I cited does not work as given on:

[https://matplotlib.org/3.5.3/api/_as_gen/matplotlib.pyplot.html](url)

It should be corrected for the benefit of anyone visiting that URL wishing to see how ```Matplotlib.plot``` works.

Your response is very disappointing and is not  encouraging for developes reporting a problem with Python code published at that URL.

I am not asking for any "litter". Just for the error to be corrected.

When you say "We are not going to litter plt.show() throughout the docs, I don't think", this means you are going to "litter". Please be clear and explicit in your response commentary.

**Comment by rcomer** [comment]
I do not think it is straightforward to say we should include `plt.show()` here to correct an error.  Sometimes calling `plt.show` is redundant, as noted in the page @jklymak linked.  Sometimes you do not want to display the figure but instead save it to a file, so would use `plt.savefig` rather than `plt.show`.

If we did decide to include it here, we should consider including it _all over the docs_, which is what I assume @jklymak meant by "littering".

FWIW, the comparison here does include it (although that example will not run because x and y are not defined...):
https://matplotlib.org/stable/api/index.html

**Comment by sjlearmonth** [comment]
I do not understand why it is not straight forward to include ```plot.shot(...)```.

It is a simple editing exercise of a website file.

**Comment by ksunden** [comment]
While it is easy to add in any single instance, it is a much larger project to try and be consistent across all examples. This particular example is not unique. Adding patchwork style only because somebody pointed it out actually quickly accumulates into either a lot of work, increasing the inconsistency of our docs, or worse flip-flopping because one person thinks it should be there and another thinks it should be gone (as @rcomer states, `show` is not always what you want to do after building out a figure...)

I won't claim we are 100% consistent to begin with (different people wrote different parts of the docs at different times), though I do think that the vast majority are likely _without_ an explicit `show`, and through a combination of "not always what you want", "more consistently lacking", and "not actually part of building the figure we are demonstrating" I would personally be more inclined towards _removing_ `show` calls rather than adding them, which appears to be an opinion shared by the other maintainers who have spoken up here.

**Comment by sjlearmonth** [comment]
It's not problem to solve.

**Comment by sjlearmonth** [comment]
It's not problem to solve.

**Comment by timhoffm** [comment]
I very much believe `plt.show()` should be added here:

- This is a first-point-of-contact example. We shouldn't expect that readers are fiamiliar with when `show()` is necessary or not.
- This is an otherwise complete and working example, including imports and data. As the OP noted it is surprising if this does not generate any output by default.
- The plotting workflow  is 1. create a figure 2. add contents 3. output the figure. We shouldn't leave out the third step. Since this is not the place to discuss all aspects of figure output (you could use `savefig()` instead of `show()`, jupyter has an auto-show, etc.) using `plt.show()` is a good default choise for output.

#### A note on consistency:

IMHO consistency is a secondary topic for `plt.show()`
- We have different kinds of "examples", at least: first-point-of-contact, gallery examples, tutorials. The different types may very well warrant different approaches to the usage of `plt.show()`.
- When we have identified the right approach, also gradual migration to that approach is beneficial, even if that means usage is more inconsistent thoughout the example category.

**Comment by sjlearmonth** [comment]
It is not a complete and working example as there is no evidence in the cited code that matplotlib.pyplot.plot is generating any output visually in a figure or to a file for the user to verify correct operation.

**Comment by sjlearmonth** [comment]
Thank you @timhoffm .

That will will help new users to understand the result of calling ```matlibplot.pyplot.plot(...)``` visually.
