### ISSUE TITLE
[Bug]: xkcd mode broken on RC/dev

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#29233]
### Bug summary

I think something with font fallback is going very wonky b/c instead of falling back cause of missing comic neue, it's producing abstract art. 

### Code for reproduction

```Python
import matplotlib.pyplot as plt
plt.xkcd()
plt.plot([1,2,3])
```

### Actual outcome

![Figure_1](https://github.com/user-attachments/assets/9c6a176d-0a13-4437-948a-cc1566220885)

### Expected outcome

![Untitled](https://github.com/user-attachments/assets/86260521-6e57-4bcb-9eb4-da3fbfc5f156)

### Operating system

windows

### Matplotlib Version

3.10rc & dev

### Matplotlib Backend

qtagg and inline

**Comment by QuLogic** [comment]
Which font is it actually using?

**Comment by oscargus** [comment]
There may for sure be a bug here, but I got similar results when I installed the "wrong" XKCD font.

**Comment by ksunden** [comment]
I do not see this on my machine, so I do suspect which installed fonts are present to be a factor... 

Gut reaction is that it has to do with 
- Font rendered as a path (rather than bitmap)
- with xkcd path modifications turned on

not sure, though

Experiments I'd like to see:
- Try simply setting the font to each font in the xkcd list, see if it can be triggered without full xkcd mode
- try doing just path effects with a standard font (in path mode if that needs to be specified)

**Comment by NGWi** [comment]
Script to rebuild font cache:
```
import matplotlib.font_manager as fm
import matplotlib as mpl

# Add fonts
fm.fontManager.addfont('~/Library/Fonts/xkcd.otf')
fm.fontManager.addfont('~/Library/Fonts/xkcd-script.ttf')

# Clear and rebuild the font cache
mpl.font_manager._load_fontmanager(try_read_cache=False)

# Optional: Print available fonts to verify
print("Available fonts:")
print([f.name for f in fm.fontManager.ttflist if
        'xkcd' in f.name.lower() or
        'humor' in f.name.lower() or
        'comic' in f.name.lower()])
 ```
