### ISSUE TITLE
Non-accurate placing of images from plt.imshow in PDF output

### ISSUE THREAD

**Issue by mojca** [matplotlib/matplotlib#2935]
I have some problems with non-accurate placing of images created by imshow. Output to PNG works fine, but the squares are rectangular and misaligned with the grid when plotting small squares to PDF (order of magnitude around 1-2 inches for the whole plot). I didn't inspect the contents of PDF, but I suspect that coordinates might be written with too low precision.

Here's a small example (maybe not the minimal possible, but hopefully short enough):

```
import numpy as np
import matplotlib.pyplot as plt

plt.gcf().set_size_inches([1,1])
a=np.random.rand(20,20)
im = plt.imshow(a, interpolation='nearest', origin='lower', extent=[-2,2,-2,2])
plt.gca().set_xticks(np.arange(-2,2,0.2))
plt.gca().set_yticks(np.arange(-2,2,0.2))
plt.gca().xaxis.set_ticklabels([])
plt.gca().yaxis.set_ticklabels([])
plt.grid(ls=':',lw=0.1,color='white')
plt.savefig('test.pdf')
```

![x](https://cloud.githubusercontent.com/assets/15606/2550376/6e526552-b682-11e3-820b-4c39a9ef6b1b.png)

I'm using python 3.3 and matplotlib 1.3.1.

**Comment by jklymak** [comment]
I think this is fixed in master by #9204 (or maybe other fixes since then).  There is still a 1-pixel offset, due to the rasterizing, but I think this is pretty accurate.  I'll take the liberty of closing, but feel free to re-open.

<img width="460" alt="banners_and_alerts_and_testimage_pdf__1_page_" src="https://user-images.githubusercontent.com/1562854/30791921-294aadfc-a16b-11e7-8e28-20668fac1c75.png">
