### ISSUE TITLE
contourf hatching and saving to pdf

### ISSUE THREAD

**Issue by wseviour** [matplotlib/matplotlib#3023]
`contourf` hatches do not appear when saving to pdf. This is apparent in the [`contourf_hatching.py`](http://matplotlib.org/examples/pylab_examples/contourf_hatching.html) example, here:

http://matplotlib.org/mpl_examples/pylab_examples/contourf_hatching_01.pdf

I think something similar was mentioned in #891 and #29, but I'm not sure it was resolved.

**Comment by lzkelley** [comment]
I think this is the same issue: PDF viewed in chrome also isn't showing the correct hatching with `fill_between` (for example, See Fig.8 or Fig.11 in http://arxiv.org/pdf/1606.01900v1.pdf --- they should be light grey instead of dark black shaded regions).  I can try to produce a MWE if that would be helpful.

**Comment by tacaswell** [comment]
This seems to be better, but still wrong on v2.0.0b1 

http://matplotlib.org/2.0.0b1/mpl_examples/pylab_examples/contourf_hatching_01.pdf

http://matplotlib.org/2.0.0b1/examples/pylab_examples/contourf_hatching.html

attn @jkseppan

**Comment by QuLogic** [comment]
Am I missing something, or is hatching working just fine in those examples?

**Comment by tacaswell** [comment]
@QuLogic The hatches in the pdf are wrong like in https://github.com/matplotlib/matplotlib/issues/6228

**Comment by NelleV** [comment]
Closed in #7421
