### ISSUE TITLE
pyplot.scatter() does not cycle colors

### ISSUE THREAD

**Issue by wavexx** [matplotlib/matplotlib#3041]
It looks like MPL is inconsistent in color cycling.
I would expect scatter() to cycle the current color as plot() does.

**Comment by tacaswell** [comment]
@JanSchulz I think https://github.com/matplotlib/matplotlib/pull/4258 + discussion at end of https://github.com/matplotlib/matplotlib/pull/3818 will get you towards what you want.

I am closing this issue as it has been quiet for over a year and what of this thread will be addressed is being is being addressed elsewhere.

**Comment by flipdazed** [comment]
This works, taken straight from my own code. 

```
from matplotlib import colours
clist = [i for i in colors.ColorConverter.colors if c != 'w']
colour = (i for i in random.sample(clist, len(clist)))
```

I randomise the `names` because life is too short to have the same colours also I filter out `w` which stands for `wheredmydatago`

```
import matplotlib.pyplot as plt
from matplotlib import colors
import numpy as np
import random

x = np.random.random(20)
test_list = [(x, x**i) for i in range(1,5)]

fig = plt.figure(figsize=(8, 8)) # make plot
ax =[]
ax.append(fig.add_subplot(111))
clist = [i for i in colors.ColorConverter.colors if c != 'w']
colour = (i for i in random.sample(clist, len(clist)))
for xy in test_list: 
    c = next(colour)
    ax[0].scatter(*xy, marker='o', color = c, label=c)
ax[0].legend(loc='best', shadow=True, fancybox=True)
plt.show()
```

Finally if you are feeling like a risk taker then replace as `clist = [c for c in colors.cnames if c not in ['white', 'snow']]` and you might just get a plot coloured by `u'palegoldenrod`

As a side comment it will break if you have more lines than colours. I leave that to someone else to figure out as I don't require it.

**Comment by tacaswell** [comment]
This actually went in to 2.0 via https://github.com/matplotlib/matplotlib/pull/6291 You should checkout the 2.0.0b1 release.
