### ISSUE TITLE
pcolormesh: hatch-parameter not appearing

### ISSUE THREAD

**Issue by oschoudhury** [matplotlib/matplotlib#3058]
There seems to be a problem with pcolormesh and the hatch-parameter. The hatch-symbol does not seem to appear, if you execute the basic example

``` python
x = np.arange(10)
y = np.arange(10)
z = np.arange(100).reshape((10, 10))
plt.pcolormesh(x, y, z, hatch = '*')
plt.show()
```

I only see the the image but not the *-symbol.

**Comment by petehuang** [comment]
Devs, what is the general consensus on implementing hatching in QuadMesh?

**Comment by efiring** [comment]
I don't know if there is a consensus, but I will continue to vote "no" until someone provides a nice, clean PR that adds hatch support with little extra code.  QuadMesh is a strange and complicated thing, so making it do more is not to be undertaken lightly.  It's strength is in making relatively dense image-like plots, but unlike imshow, it can handle non-Cartesian grids.  Neither pcolormesh *nor* imshow implements "hatch", although imshow chokes on it rather than silently ignoring it.

1) For situations where hatching is needed, use pcolor instead of pcolormesh.  Yes, it's slow, but this is problematic only if the grid is dense.  Do the applications where hatching is helpful include such dense grids?

2) The problem of silently ignoring an invalid kwarg should be addressed.

Side comment: pcolormesh and QuadMesh badly need some API and relatively high-level refactoring.  I would like to do it, but like so many things, it hasn't risen high enough in priority that I have been able to get to it.

**Comment by ozanmert** [comment]
Here is another workaround for this missing functionality:

https://stackoverflow.com/a/69059584/2952639
