### ISSUE TITLE
Visibility of short line depend on the direction

### ISSUE THREAD

**Issue by barpaum** [matplotlib/matplotlib#3114]
I have two series of lines plotted in one figure.
One series is plotted horizontally while the other is aslant. But they are exactly same in the x axis, while the horizontal line is rounded to year in y axis. They are both plotted with linewidth=5 and solid_capstyle="butt". 
The problem is that between August and Semptember, the five short aslant line can be seen ( not very clear ) while the corresponding horizontal lines can not be seen. For me, this is kind of inconsistance and introducing confusion. 
I don't known whether this is a bug. But is there a solution to make this consistent? Thanks!

![snapshot86](https://cloud.githubusercontent.com/assets/3433058/3174958/c6fab9f8-ebf6-11e3-89f6-4551a6bd420f.png)

**Comment by anntzer** [comment]
There is clearly some shift in visibility that is due to antialiasing, but we really can't do anything about it.
Simplified explanation: if your line is so thin that it falls "between" two physical pixel columns, the best that can be done is draw half-intensity lines on the two columns, but that line will look blurrier than a line that just falls straight on a physical pixel column.
