### ISSUE TITLE
Add imshow support to mplot3d

### ISSUE THREAD

**Issue by ddale** [matplotlib/matplotlib#315]
[Original report at SourceForge, opened Tue Sep 22 16:55:10 2009](https://sourceforge.net/tracker/?func=detail&aid=2864570&group_id=80706&atid=560723)

I need to create a plot that contains a textured surface in the x-y plane and on top of that several polygons. Unfortunately there does not seem to be a method for placing an image within the 3D axes provided by Axes3D. An interface for such functionality might be:

plt.imshow(my_img, normal_direction=[0,0,1], img_center_pos=[0,0,0])

which indicates that the image surface should be perpendicular to the direction 0,0,1, and the center of the image should lie at coordinate [0,0,0].

The meaning of the extent parameter may be interpreted as lying in the image plane and the x,y, and z axes may be calculated based on the projection of the image in those directions.

**Comment by petehuang** [comment]
Just commenting for an update - doesn't seem like there has been any movement here, but please post if otherwise

**Comment by WeatherGod** [comment]
We are closer to it than before, with @mdboom's refactor of the image
architecture to better handle transforms. The problem that remains is that
mplot3d doesn't utilize the transforms/projection framework that the rest
of matplotlib uses (predates it). I have made a couple of attempts at
fixing that a few years ago, but failed badly due to a lack of
understanding the framework and its interactions with the axes objects.

Perhaps my previous attempts at getting mplot3d refactored to use the
transform system has been too large of a job. Maybe some small first steps
would be to create some simple 3d projections and add them to the library
along with unit tests. Then we can look at how to integrate mplot3d with
that in a piecemeal fashion.

**Comment by thriveth** [comment]
Are there any updates on this, or is it not happening?

**Comment by scottshambaugh** [comment]
I agree this doesn't really make sense in 3D, and agree with pcolormesh as the way forward on this. While https://github.com/matplotlib/matplotlib/issues/4468 is being implemented, plot_surface can be used as a workaround right now, such as is done here: https://stackoverflow.com/questions/30269099/how-to-plot-a-rotating-3d-earth

Closing this one as won't-do since it seems like there is consensus, feel free to re-open the issue if there is more to consider here.
