### ISSUE TITLE
Why are numpoints and scatterpoints two different keywords?

### ISSUE THREAD

**Issue by Gabriel-p** [matplotlib/matplotlib#3212]
When plotting a legend the number of points displayed can be set with a keyword. If one is plotting a line, you have to use `numpoints`, if it is a scatter plot the keyword is `scatterpoints` instead.

Why is this? Why not simply use `numpoints` for both? It seems unnecessarily complicated.

**Comment by petehuang** [comment]
Hi,

This issue has been inactive for a while. Does this continue to represent a useful fix? If not, I recommend closing this issue. Wondering about the impact-disruption tradeoff for this one. Thanks!

**Comment by Gabriel-p** [comment]
Well, as the OP I still believe it is important. While it is true that this could be somewhat disruptive, the tradeoff is consistency.

**Comment by efiring** [comment]
@Gabriel-p, it looks like the reason is that the legend can display scatter symbols in a more complex way than symbols in a line.  It uses two parameters, scatterpoints and scatteryoffsets.  Not the greatest names, but their purpose is to allow the legend to clearly distinguish scatter markers from line markers.  When `rcParams['legend.scatterpoints'] > 1`, the points are vertically offset to suggest a scatterplot.  This (3 points) was the default in classic mode, but now the default is 1 point, so this mechanism is inactive by default.

I don't think we want to get rid of this offset scatter points mechanism--it can be used effectively to distinguish between elements in a plot--and it requires having both numpoints and scatterpoints.   Therefore I will close this issue.
