### ISSUE TITLE
re-paramterize quiver api

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#3305]
https://gist.github.com/tacaswell/a11a149d6b7557966f0c

Setting all of the arrow head properties independently can be a bit painful, the linked gist does some work to re-paraterize the head properties with a fixed head width, the ratio between the head and the shaft, the head aspect and the head 'pinch'.  Still very rough at the edges.

We probably should have a second function called 'quiver_something` for the new arguements to do the math and pass the call down to the current quiver.

This issue is mostly so it does not get lost.

**Comment by basharovV** [comment]
What would be an appropriate name for such a function? Should it be generated in pyplot.py too?

**Comment by tacaswell** [comment]
attn @efiring 

I am not sure if the best path is a new version of `quiver` or just a function that returns kwargs to pass to current `quiver`, ex

```python
q_kwargs = quiver_shape(head_size, ascale, pinch, aspect)
q = quiver(x, y, u, v, **q_kwargs)
```

or to have quiver take a bunch of kwargs and raise if it gets an incompatible mix of old/new.

**Comment by efiring** [comment]
I don't think this calls for a proliferation of new functions. I understand only part of your proposal.  What is `ascale` supposed to be?  If we are going to provide more kwargs to make it easier to specify arrow parameters, we need to be sure we are actually using names that will be easier to understand and remember.

There are many ways that that the head could be parameterized.  There are three degrees of freedom.  Probably the most natural way to think about them is that there is one overall size, and there are two angles.  Presently the overall size is `headwidth` which is a multiple of the shaft width. The rationale is that the default of 3, for example, means the back corners of the arrow stick out by one shaft width on either side; with a value of 1, the line is pointed, but there is really no arrow; nothing sticks out.  I don't see any point in changing this--I don't know a better way to specify overall head size for typical quiver applications.  

That leaves the angles, and here I originally chose an easy-to-implement specification via two lengths.  I would not mind seeing an alternative: instead of headlength and headaxislength, one could specify point_angle and pinch_angle.  The present default point_angle would then be 2 * arctan(1.5/5) or 33 degrees.  A simple pinch_angle definition would be the angle at the back of the head, so 180 for a straight line.  The present default is 143.

**Comment by tacaswell** [comment]
Given my naming patterns, I suspect that it stands for 'arrow scale', but I wrote that gist a long time ago.

**Comment by timhoffm** [comment]
Is there really a need for reparametrization? The current parameters are

![](https://matplotlib.org/devdocs/_images/quiver_sizes.svg)

as documented in the notes section at https://matplotlib.org/devdocs/api/_as_gen/matplotlib.axes.Axes.quiver.html#matplotlib.axes.Axes.quiver

Yes, you cannot easily scale the head while keeping its shape. OTOH tuning the arrow is basically a manual procedure anyway, which one won't do too often. IMHO the API hassle is not worth the effort.

If you really think this needs usability improvement, the suggested `arrow_shape()` function is a lightweight option.

**Comment by antara-gandhi** [comment]
hi there @tacaswell @timhoffm is this issue still open? i am new to contributing and would love to be able to try my hand at this! do you have any guidance?

**Comment by melissawm** [comment]
Hi @antara-gandhi, it looks like there are questions around the need for this change (see @timhoffm 's comment above). I'd recommend checking out other issues in the repo instead of this one, at least until we have a better understanding of the way forward here. Thanks!

**Comment by timhoffm** [comment]
@tacaswell are you still interested in this? I've proposed to close in https://github.com/matplotlib/matplotlib/issues/3305#issuecomment-1456944851.

**Comment by tacaswell** [comment]
I'm going to take @timhoffm 's suggestion and close this.
