### ISSUE TITLE
Unecessary arguement in GraphicsContextBase get_linestyle

### ISSUE THREAD

**Issue by JamesRamm** [matplotlib/matplotlib#3354]
There is an unnecessary arguement in `get_linestyle` of `GraphicsContextBase`. An unused arguement is required, which shouldn't be there.
It blocks any future 'propertification'...

I made the changes, but when trying to make a pull request against that commit, GitHub says there is nothing to compare?

Here is the commit:
https://github.com/JamesRamm/jplotlib/commit/0bab98249ee1b966eac96ac295e0e613a279b1cd

**Comment by petehuang** [comment]
This one should be _so_ easy :)

#3355 had stalled due to some bad commit pulling. The issue still stands, and the fix is as following:

1. Navigate to https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py#L915-L920
2. Remove the `style` keyword from the signature
3. Commit!

I'd mark as new-contributor-friendly and Difficulty: Easy
