### ISSUE TITLE
Does matplotlib have a utility for "normalizing" abbreviated kwargs?

### ISSUE THREAD

**Issue by danielballan** [matplotlib/matplotlib#3490]
Does matplotlib include an official utility for "normalizing" abbreviated keyword arguments? This is useful for functions that accept style arguments, apply defaults internally, and pass the result through to mpl.

One example of an implementation is [here](https://github.com/tritemio/FRETBursts/blob/fit_experim/fretbursts/burst_plot.py#L71). Does matplotlib have something like this in its API somewhere? If not, I think it would be nice to incorporate this in mpl.

cc @tritemio

**Comment by petehuang** [comment]
The referenced example in the OP is gone - for my understanding what does it look like?

Perhaps related: #1963

**Comment by tritemio** [comment]
The original function is this (permalink):

https://github.com/tritemio/FRETBursts/blob/0.5.9/fretbursts/burst_plot.py#L97


On Jan 2, 2017 12:54, "Pete Huang" <notifications@github.com> wrote:

The referenced example in the OP is gone - for my understanding what does
it look like?

Perhaps related: #1963
<https://github.com/matplotlib/matplotlib/issues/1963>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/matplotlib/matplotlib/issues/3490#issuecomment-270019285>,
or mute the thread

**Comment by tacaswell** [comment]
See https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook.py#L2510

**Comment by petehuang** [comment]
@tacaswell so, sounds like it exists but it's not used throughout. My search shows only `axes/_axes.py` as using it.

If we want to open up a new effort to start replacing the docstring scraping functionality, we should replace this issue with a fresh one

**Comment by tacaswell** [comment]
This is also tied to the traitlets work @rmorshea will be doing (so we can simply ask the artists what attributes they have).

**Comment by petehuang** [comment]
For visitor reference, traitlets work sits at #4762

**Comment by timhoffm** [comment]
For future reference: Aliases and normalizing are currently implemented via the decorator `@cbook._define_aliases` and the function `cbook.normalize_kwargs`.
