### ISSUE TITLE
3D figures cannot be created in 1.4.0: 'module' object has no attribute '_string_to_bool'

### ISSUE THREAD

**Issue by onesandzeroes** [matplotlib/matplotlib#3537]
Trying to run some of the 3d surface examples from the gallery, e.g. [this demo](http://matplotlib.org/examples/mplot3d/surface3d_demo.html), the creation of the axes is failing, saying that a module is missing a `_string_to_bool` attribute.

The full traceback I get is:

```
fig = plt.figure()
ax = fig.gca(projection='3d')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-acf5f628bd2d> in <module>()
      1 fig = plt.figure()
----> 2 ax = fig.gca(projection='3d')
      3 

/usr/local/lib/python2.7/dist-packages/matplotlib/figure.pyc in gca(self, **kwargs)
   1266 
   1267         # no axes found, so create one which spans the figure
-> 1268         return self.add_subplot(1, 1, 1, **kwargs)
   1269 
   1270     def sca(self, a):

/usr/local/lib/python2.7/dist-packages/matplotlib/figure.pyc in add_subplot(self, *args, **kwargs)
    956                     self._axstack.remove(ax)
    957 
--> 958             a = subplot_class_factory(projection_class)(self, *args, **kwargs)
    959 
    960         self._axstack.add(key, a)

/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_subplots.pyc in __init__(self, fig, *args, **kwargs)
     76 
     77         # _axes_class is set in the subplot_class_factory
---> 78         self._axes_class.__init__(self, fig, self.figbox, **kwargs)
     79 
     80     def __reduce__(self):

/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.pyc in __init__(self, fig, rect, *args, **kwargs)
     89         Axes.__init__(self, fig, rect,
     90                       frameon=True,
---> 91                       *args, **kwargs)
     92         # Disable drawing of axes by base class
     93         Axes.set_axis_off(self)

/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.pyc in __init__(self, fig, rect, axisbg, frameon, sharex, sharey, label, xscale, yscale, **kwargs)
    434         self._hold = rcParams['axes.hold']
    435         self._connected = {}  # a dict from events to (id, func)
--> 436         self.cla()
    437         # funcs used to format x and y - fall back on major formatters
    438         self.fmt_xdata = None

/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.pyc in cla(self)
   1043         self._zmargin = 0
   1044 
-> 1045         Axes.cla(self)
   1046 
   1047         self.grid(rcParams['axes3d.grid'])

/usr/local/lib/python2.7/dist-packages/matplotlib/axes/_base.pyc in cla(self)
    895         self.containers = []
    896 
--> 897         self.grid(self._gridOn, which=rcParams['axes.grid.which'])
    898         props = font_manager.FontProperties(size=rcParams['axes.titlesize'],
    899                                         weight=rcParams['axes.titleweight'])

/usr/lib/pymodules/python2.7/mpl_toolkits/mplot3d/axes3d.pyc in grid(self, b, **kwargs)
   1254         if len(kwargs) :
   1255             b = True
-> 1256         self._draw_grid = maxes._string_to_bool(b)
   1257 
   1258     def ticklabel_format(self, **kwargs) :

AttributeError: 'module' object has no attribute '_string_to_bool'
```

**Comment by valentas-kurauskas** [comment]
I have the same problem with ubuntu & python installed in virtualenv with --system-site-packages. The suggestion here http://stackoverflow.com/questions/25383698/error-string-to-bool-in-mplot3d-workaround-found does not work.

**Comment by valentas-kurauskas** [comment]
Actually I found that this bug can be fixed by importing pandas and mplot3d in a particular order. Here is a minimal code based on http://matplotlib.org/xkcd/examples/mplot3d/lines3d_demo.html.

# coding: utf-8
import matplotlib.pyplot as plt
import numpy as np
import pandas #comment this out or move one line down - and it works!
from mpl_toolkits.mplot3d import Axes3D

fig = plt.figure()
ax = fig.gca(projection='3d')
theta = np.linspace(-4 * np.pi, 4 * np.pi, 100)
z = np.linspace(-2, 2, 100)
r = z**2 + 1
x = r * np.sin(theta)
y = r * np.cos(theta)
ax.plot(x, y, z, label='parametric curve')
ax.legend()

plt.show()
~

**Comment by WeatherGod** [comment]
That is by no means a solution, or a work-around, really. It probably only
works because pandas might be importing a different mpl_toolkits package
than what would be imported normally. Such situations are endemic of a
broken python distribution. This would not work for someone else who is
suffering from a similar problem, but broken in a different way. The only
common thread I have seen with these broken installs is that it is all on
Ubuntu.

**Comment by basnijholt** [comment]
Why is this issue closed? The latest version on pip still has the problem.

**Comment by WeatherGod** [comment]
Because this particular problem was caused by user error. There were
multiple installs of mpl_toolkits on the system. There is nothing we can do
on our end to fix it.

**Comment by basnijholt** [comment]
Is there a suggested solution?

**Comment by tacaswell** [comment]
Make sure you have cleaned out any old installed versions of mpl.
