### ISSUE TITLE
Pick events broken in log axes

### ISSUE THREAD

**Issue by lpsinger** [matplotlib/matplotlib#3540]
Handling pick events does not work on logarithmic axes. See the example below. As long as the line statement `ax.set_xscale('log')` is commented out, clicking on the polygons created by `axvspan` xauses them to change from gray to red. Uncomment that line to make the x axis logarithmic, and clicking on the polygons has either no effect or is misdirected to the far-left polygon only.

``` python
    from matplotlib import pyplot as plt
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.set_xlim(1, 10)
    for i in range(1, 10, 3):
        ax.axvspan(i, i + 1, color='gray', picker=True)

    # uncomment this line to break the picker
    # ax.set_xscale('log')

    def onpick(event):
        event.artist.set_color('red')
        fig.canvas.draw()

    fig.canvas.mpl_connect('pick_event', onpick)
    plt.show()
```

Tested on version 1.4.0 and master as of 04496b056f1995e1c54e6a5feb5be9256e2d8e9b on Mac OS X Mavericks.

[TAC edited for formatting]

**Comment by tacaswell** [comment]
Punting on this again, I don't think this is a blocker as it is reportedly limited to the span objects.

**Comment by petehuang** [comment]
In 1.5.3 only the left bar showed red.

In 2.0 rc2 none showed red

**Comment by anntzer** [comment]
This is apparently due to `_point_in_path` not handling nonlinear transforms, and affects basically any path-containment-check in nonlinear axes.  The following patch fixes the issue:
```
diff --git a/lib/matplotlib/path.py b/lib/matplotlib/path.py
index 58e984d2c..e4c567898 100644
--- a/lib/matplotlib/path.py
+++ b/lib/matplotlib/path.py
@@ -492,10 +492,8 @@ class Path(object):
         smaller.
         """
         if transform is not None:
-            transform = transform.frozen()
-        result = _path.point_in_path(point[0], point[1], radius, self,
-                                     transform)
-        return result
+            self = transform.transform_path(self)
+        return _path.point_in_path(point[0], point[1], radius, self, None)
 
     def contains_points(self, points, transform=None, radius=0.0):
         """
```
but it probably needs a test, and I guess there is some memory cost to maintaining the entire transformed path in memory (but I guess that transformed path will have to be computed at draw time anyways so perhaps it should (is already?) be cached somewhere.

**Comment by anntzer** [comment]
I was thinking whether you could inverse-transform the point, rather than forward-transform the path (and then there's no memory cost anymore), but for really weird nonseparable transforms it may be not the same? (You can imagine a line that originally passes above a point curve below it after application of the transform... perhaps)
