### ISSUE TITLE
Feature Request: manually set colorbar without mappable

### ISSUE THREAD

**Issue by ahwillia** [matplotlib/matplotlib#3644]
There are some hacks for doing this: http://stackoverflow.com/questions/8342549/matplotlib-add-colorbar-to-a-sequence-of-line-plots

But it would be nice if this was just a single line of code:

```
plt.colorbar(cmap=cm.jet,min=0.0,max=1.0)
```

**Comment by pmfeldman** [comment]
I have not been able to find anything online that clearly explains what the term "mappable" means.

If one creates something like a filled contour plot, the colors on the colorbar must correspond to the colors appearing in the contour plot.  But, one might not want these colors to cover the limits of the data.

An important use case is the following: One creates a group of contour plots, and wants to then create a colorbar that is common to all of the plots.  It appears that there is currently no good mechanism for doing this.

Phillip M. Feldman

**Comment by efiring** [comment]
Here is a modification of http://matplotlib.org/examples/pylab_examples/multi_image.html.  Does this do what you want?

```python
#!/usr/bin/env python
'''
Make a set of contour plots with a single colormap and colorbar.
'''

import matplotlib.pyplot as plt
import numpy as np

from matplotlib.font_manager import FontProperties
from numpy.random import rand

cmap = plt.get_cmap('Blues')
clevs = np.arange(0, 4.001, 0.2)

Nr = 3
Nc = 2

fig = plt.figure()

figtitle = 'Multiple contour plots, same levels'
t = fig.text(0.5, 0.95, figtitle,
             horizontalalignment='center',
             fontproperties=FontProperties(size=16))

cax = fig.add_axes([0.2, 0.08, 0.6, 0.04])

w = 0.4
h = 0.22

contour_sets = []
for i in range(Nr):
    for j in range(Nc):
        pos = [0.075 + j*1.1*w, 0.18 + i*1.2*h, w, h]
        ax = fig.add_axes(pos)
        if i > 0:
            ax.set_xticklabels([])
        if j > 0:
            ax.set_yticklabels([])
        ax.locator_params(axis='y', nbins=5)
        # Make some fake data with a range that varies
        # somewhat from one plot to the next.
        data = i + j + rand(10, 20)
        cs = ax.contourf(data, levels=clevs, cmap=cmap)
        contour_sets.append(cs)

# The colorbar can be based on any of the mappables (the ContourSet
# objects) because they are all using the same levels and cmap.
fig.colorbar(contour_sets[0], cax, orientation='horizontal')

plt.show()
```

**Comment by pmfeldman** [comment]
Having a common colorbar for multiple axes is part of what I was looking for, but what I'd really like is the ability to explicitly set the limits of the colorbar via arguments to the colorbar method.

**Comment by pmfeldman** [comment]
I've been trying to find something that I can read that explains the concept of 'mappables'.  Any pointers will be appreciated.

**Comment by efiring** [comment]
Example of making a colorbar that is not tied to anything else:
http://matplotlib.org/examples/api/colorbar_only.html
"Mappable" refers to an Artist subclass that inherits from the ScalarMappable mixin:
http://matplotlib.org/api/cm_api.html

**Comment by pmfeldman** [comment]
Your example based on http://matplotlib.org/examples/pylab_examples/multi_image.html was closer to what I've been looking for.  Ideally, I'd like to be able to make a colorbar that shows the mapping between data values and colors appearing in one or more contour plots, but with the limits of the colorbar not tied to the limits of the data.

**Comment by efiring** [comment]
You can do that with the example I gave.  For a filled contour plot, the limits of the colorbar are take from the top and bottom values of the region boundaries, `clevs` in my example.  You can set those to anything you like, regardless of the actual data values being contoured.  In particular, you can set them to cover a smaller range, and use the `extend='both'` kwarg to `contourf` so that out-of-range values are colored with the "over" and "under" values of the colormap, and the colorbar has triangular ends to show these over and under regions.

**Comment by pmfeldman** [comment]
This sounds perfect.  I will experiment with this approach.  Thanks!

**Comment by efiring** [comment]
I'm inclined to close this; I don't support any of the suggestions made earlier in the discussion.  Am I missing something?  Is there an important use case that our present code can't handle adequately?

**Comment by ahwillia** [comment]
Close if you want to -- but just to clarify:

The point of the original issue was to request that the interface be simplified. Yes, there are ways to create a colorbar on e.g. line plots:

```python
sm = plt.cm.ScalarMappable(cmap=my_cmap, norm=plt.Normalize(vmin=0, vmax=1))
sm._A = []
plt.colorbar(sm)
```

But this isn't intuitive/easy for users -- you more or less need to go to stackoverflow or dig deep into the documentation/examples to figure this out. So **the proposal/feature request was to make this a one-liner** and have matplotlib execute something like the above code under the hood (without the user needing to know what a `ScalarMappable` is).

**Comment by efiring** [comment]
What is the use case for a colorbar with a line plot?  Is it something other than what one would do with a LineCollection, e.g., 
http://matplotlib.org/examples/pylab_examples/line_collection2.html
 or 
http://matplotlib.org/examples/pylab_examples/multicolored_line.html ?
How would the colorbar be connected to other plot elements in your use case?

**Comment by ahwillia** [comment]
Well my use case was an animation where the lines were changing color over time. For example, representing flow in a network, or electricity.

I wanted a colorbar on the side to show the range of the colormap I was using. So, for example, if the maximum flow allowable was `1.0`, it would be nice to just specify:

```python
plt.colorbar(cmap=cm.jet,min=0.0,max=1.0)
```

**Comment by pmfeldman** [comment]
My use case is in some respects similar.  I want to be able to produce a
sequence of filled contour plots with a colorbar that remains invariant
regardless of what the data is doing.  The attached script, which I created
with the assistance of Jim Corson at Enthought, demonstrates the creation
of a single filled contour plot with an overridden colorbar.  I have two
concerns: (1) It seems that the amount of code that is required to
accomplish this relatively simple job is excessive.  (2) What's going on is
rather non-intuitive.

Phillip

On Sun, Jan 17, 2016 at 1:25 PM, Alex Williams <notifications@github.com>
wrote:

> Well my use case was an animation where the lines were changing color over
> time. For example, representing flow in a network, or electricity.
>
> I wanted a colorbar on the side to show the range of the colormap I was
> using. So, for example, if the maximum flow allowable was 1.0, it would
> be nice to just specify:
>
> plt.colorbar(cmap=cm.jet,min=0.0,max=1.0)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/matplotlib/matplotlib/issues/3644#issuecomment-172384658>
> .
>

"""
contour_demo.py


OVERVIEW

matplotlib currently provides no good mechanism for creating a filled contour
plot with an accompanying colorbar whose limits are set independently of the
limits of the data.  The need for this functionality is particularly important
when one creates either a sequence of plots or an array of subplots with a
common colorbar.  It is hoped that matplotlib feature request #3644, 'manually
set colorbar without mappable', which was opened Oct 13, 2014, will eventually
lead to a clean solution.

In the meantime, this Python script demonstrates an ugly but effective solution
to the problem.  The script was created with the assistance of Jim Corson at
Enthought.


AUTHOR

Phillip M. Feldman
"""

from numpy import linspace, mgrid, sqrt
from matplotlib import colors, pyplot

# In following statement, we change the background color (`facecolor`) of the
# margin area of the figure from the default dark gray to white.  (Black text on
# a dark gray background gives poor contrast).
fig= pyplot.figure(figsize=(9, 7), facecolor=[1, 1, 1])

# The purpose of the following block of code is to create a "mappable object"
# and the associated colorbar range.  `N_bands` is the number of color bands
# desired.
cmin, cmax= (0, 4)
N_bands= 12
Z= [[0,0],[0,0]]

# `numpy.linspace` produces an array of `num` uniformly-spaced values.  Because
# linspace by default produces a sequence that includes both the initial
# (`cmin`) and final (`cmax`) points, the number the of values must be one
# greater than the number of bands:
levels= linspace(cmin, cmax, num=N_bands+1)
cbar_range= pyplot.contourf(Z, levels)

# The following statement clears the figure, but the mappable object still
# exists:
fig.clf()

# Create a single axes that (except for labels) fills the entire figure space:
axes= fig.add_subplot(111)

x, y= mgrid[0:4:100j, -3:3:200j]
z= sqrt(x**2 + y**2)
xvec= mgrid[-3:3:200j] # 200 values including -3 and 3
yvec= mgrid[0:4:100j] # 100 values including 0 and 2

axes.contourf(xvec, yvec, z, N_bands)
axes.set_xlabel('x', fontsize=14)
axes.set_ylabel('y', fontsize=14)

axes.grid()

cbar= fig.colorbar(cbar_range)
title= axes.set_title("matplotlib feature request #3644\n"
  "(manually set colorbar)", fontsize= 16, y=1.02)

cbar.set_label('power')
cbar.set_ticks([0, 1, 2, 3, 4])
pyplot.show()
fig.savefig("contour_demo.png")

**Comment by efiring** [comment]
On 2016/01/17 6:13 PM, Phillip M. Feldman wrote:
> I have two
> concerns: (1) It seems that the amount of code that is required to
> accomplish this relatively simple job is excessive. (2) What's going on is
> rather non-intuitive.

It's downright bizarre.  Either it is trying to do something I still 
don't understand, or it results from a misunderstanding of how contourf 
and colorbar work together.

**Comment by efiring** [comment]
On 2016/01/17 11:25 AM, Alex Williams wrote:
> Well my use case was an animation where the lines were changing color
> over time. For example, representing flow in a network, or electricity.
>
> I wanted a colorbar on the side to show the range of the colormap I was
> using. So, for example, if the maximum flow allowable was |1.0|, it
> would be nice to just specify:
>
> plt.colorbar(cmap=cm.jet,min=0.0,max=1.0)

OK, I can see how an animation of a line with changing color makes the 
need for a mappable inconvenient.  This is a rare case, but easily 
handled with two lines. You can make your own function using calls to 
`colorbar.make_axes()` or `colorbar.make_axes_gridspec()` to make the 
axes in which the colorbar will reside (stealing from the main plot 
axes, just like `colorbar()` does) and then pass that to 
`colorbar.ColorbarBase`.

**Comment by tacaswell** [comment]
copy-paste of the code to get highlighting (because us youngins can not deal otherwise).

```python
"""
contour_demo.py


OVERVIEW

matplotlib currently provides no good mechanism for creating a filled contour
plot with an accompanying colorbar whose limits are set independently of the
limits of the data.  The need for this functionality is particularly important
when one creates either a sequence of plots or an array of subplots with a
common colorbar.  It is hoped that matplotlib feature request #3644, 'manually
set colorbar without mappable', which was opened Oct 13, 2014, will eventually
lead to a clean solution.

In the meantime, this Python script demonstrates an ugly but effective solution
to the problem.  The script was created with the assistance of Jim Corson at
Enthought.


AUTHOR

Phillip M. Feldman
"""

from numpy import linspace, mgrid, sqrt
from matplotlib import colors, pyplot

# In following statement, we change the background color (`facecolor`) of the
# margin area of the figure from the default dark gray to white.  (Black text on
# a dark gray background gives poor contrast).
fig= pyplot.figure(figsize=(9, 7), facecolor=[1, 1, 1])

# The purpose of the following block of code is to create a "mappable object"
# and the associated colorbar range.  `N_bands` is the number of color bands
# desired.
cmin, cmax= (0, 4)
N_bands= 12
Z= [[0,0],[0,0]]

# `numpy.linspace` produces an array of `num` uniformly-spaced values.  Because
# linspace by default produces a sequence that includes both the initial
# (`cmin`) and final (`cmax`) points, the number the of values must be one
# greater than the number of bands:
levels= linspace(cmin, cmax, num=N_bands+1)
cbar_range= pyplot.contourf(Z, levels)

# The following statement clears the figure, but the mappable object still
# exists:
fig.clf()

# Create a single axes that (except for labels) fills the entire figure space:
axes= fig.add_subplot(111)

x, y= mgrid[0:4:100j, -3:3:200j]
z= sqrt(x**2 + y**2)
xvec= mgrid[-3:3:200j] # 200 values including -3 and 3
yvec= mgrid[0:4:100j] # 100 values including 0 and 2

axes.contourf(xvec, yvec, z, N_bands)
axes.set_xlabel('x', fontsize=14)
axes.set_ylabel('y', fontsize=14)

axes.grid()

cbar= fig.colorbar(cbar_range)
title= axes.set_title("matplotlib feature request #3644\n"
  "(manually set colorbar)", fontsize= 16, y=1.02)

cbar.set_label('power')
cbar.set_ticks([0, 1, 2, 3, 4])
pyplot.show()
fig.savefig("contour_demo.png")
```

**Comment by pmfeldman** [comment]
Hm.  You may have a point.  I've just realized that `z` takes values from 0
to 5, which means that this code is producing a colorbar that is
inconsistent with the contour plot.  My goal was to create a colorbar that
covers the range from 0 to 4, even though the data extends outside that
interval.

**Comment by tacaswell** [comment]
I _think_ you want to be doing something like:

```python
import matplotlib.pyplot as plt
import numpy as np

fig, ax = plt.subplots()

x, y = np.mgrid[0:4:100j, -3:3:200j]
z = 2 * np.sqrt(x**2 + y**2)
xvec = np.mgrid[-3:3:200j]  # 200 values including -3 and 3
yvec = np.mgrid[0:4:100j]   # 100 values including 0 and 2

bands = np.linspace(0, 4, 17, endpoint=True)
cf = ax.contourf(xvec, yvec, z, bands, extend='both', cmap='viridis')
ax.set_xlabel('x', fontsize=14)
ax.set_ylabel('y', fontsize=14)

ax.grid()

cbar = fig.colorbar(cf)

cbar.set_label('power')

plt.show()
fig.savefig("contour_demo.png")
```

![so](https://cloud.githubusercontent.com/assets/199813/12393517/304f4ab8-bdc4-11e5-96f0-9973858aef6a.png)

**Comment by pmfeldman** [comment]
After replacing `extend='both'` with `extend='neither'`, I did get exactly
what I was looking for.

In reading the documentation for contour/contourf, I missed the fact that
the behavior is different depending on whether the fourth argument is an
integer or a sequence (list or array). So, if there is a matplotlib issue
here, it involves either (a) the documentation for contour/contourf, or (b)
overuse of positional arguments as opposed to keyword arguments in the
definitions of these functions.

Thanks!

Phillip

**Comment by naught101** [comment]
See also [`plt.clim`](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.clim.html):

> Set the color limits of the current image.

**Comment by jimmyhmont** [comment]
Is there a way to use contour instead of contourf to create the colorbar this way?

Z= [[0,0],[0,0]]
cbar_range= pyplot.contour(Z, levels)
cbar= fig.colorbar(cbar_range)

I was using it to get a bar with line markers but it doesn't work in matplotlib 2.2.0 anymore.

**Comment by afvincent** [comment]
@jimmyhmont 
```python
import matplotlib.pyplot as plt
plt.ion()
fig, ax = plt.subplots()
Z = [[0, 1],[3, 0]]
cbar_range= ax.contour(Z, 10)
cbar= fig.colorbar(cbar_range, ax=ax)
```
seems to be working fine for me with Matplotlib 2.2.0 from pip. I guess that the *Z* array with only null values is somehow causing your issue. IIRC, some dev (maybe @efiring  or @jklymak) recently fixed an issue with those kind of all-null input in contour plots.

**Comment by story645** [comment]
While this was left in an unresolved state a few years ago, I'd support a PR for this because currently there's no great way to do a colorbar on a collection of filled polygons (like a choropleth)-the way the tutorial recommends (https://matplotlib.org/gallery/api/patch_collection.html#sphx-glr-gallery-api-patch-collection-py) doesn't work that great for geographic polygons so the usual suggested run around is to construct an empty scalermappable to pass into colorbar code. Being able to build it directly would be far more straightforward.

**Comment by jklymak** [comment]
I’d be against adding kwargs to colorbar to do this.   vmin and vmax as kwargs that act only on null colorbars would be quite confusing because you know folks would try to use them on normal colorbars as well.  On the other hand a new method (nullcorbar ?) makes sense to me.

**Comment by naught101** [comment]
What would be to problem with people using them on normal colourbars as well? I think it would be sensible to assume that if vmin/vmax are set, then they should override the detected values.

**Comment by jklymak** [comment]
Well, if someone wants to do this, I'd prefer #9903 is merged first, since adding vmin and vmax will be quite different in each case.

**Comment by jimmyhmont** [comment]
I tried with non null values but it's still not working.
I get the error message: index 2 is out of bounds for size 2.
It comes form colorbar.py line 485


2018-03-09 18:34 GMT+01:00 Adrien F. Vincent <notifications@github.com>:

**Comment by efiring** [comment]
I don't understand what the various posters are asking for here--the use cases are unclear to me, but I get the sense that different people might have quite different things in mind.
What is it that people want--and why--that is not illustrated in https://matplotlib.org/tutorials/colors/colorbar_only.html?highlight=colorbar?  (That tutorial needs better axes shapes for its sample colorbars, and also some reference to `matplotlib.colorbar.make_axes` and `matplotlib.colorbar.make_axes_gridspec`.)

**Comment by ahwillia** [comment]
That's exactly what I want. Except I want to be able to do it (a) in a single line, and (b) without creating a new axes object and fiddling with the sizing.

```python
plt.figure()
plt.plot(...) # could be anything
plt.colorbar(cmap='viridis', vmin=0, vmax=1)
```

Right now I accomplish this by making two figures and pasting them together post hoc in adobe illustrator. I wrote myself a helper function which is very similar to the tutorial you linked.

It works for me! I'm moderately happy with it. I still don't see why an easy one-liner like the suggestion above is problematic to incorporate. But I agree it can be done and figured out after googling around.

**Comment by story645** [comment]
@efiring , that tutorial/ColorbarBase works...but I thought it mostly wasn't supposed to be used directly? My use case is like @ahwillia , in that geopandas has a complicated relationship with colorbars and yeah, I know the real answer is make a PR on geopandas that fixes their issue with colorbars.

**Comment by efiring** [comment]
@hwillia, I'm sorry, but that's not enough information for me to understand.
1) Why do you want a colorbar that is not connected to anything, or at least is not connected in the normal way?
2) Do you want a quasi-continuous one, as opposed to one with discrete segments?  (I assume so.)
3) If so, how will plot elements in your main axes potentially generate any color within the range?
4) What are your vmin and vmax supposed to control? Selecting a segment of the full colormap? Or the numbers to which the full range of the colormap corresponds?  How do your proposed vmin and vmax relate to the vmin and vmax of the norm?  (Recall that the `ColorbarBase` *is* a `ScalarMappable`, and has its own cmap and norm.)

I'm not necessarily opposed to adding a convenience function, with a different name, for generating an independent colorbar that steals space from a given Axes containing the primary plot, but the purpose and design need to be clear.  The name and signature need to be chosen so as to reduce confusion, not increase it.

**Comment by story645** [comment]
@efiring so here's a really typical use case:

```
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib as mpl
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

cmap = mpl.cm.viridis_r
norm = mpl.colors.Normalize(vmin=0, vmax=1.25e9)

gs_kw = dict(width_ratios=[30,1], height_ratios=[1])
fig, (ax1, ax2) = plt.subplots(ncols=2, gridspec_kw=gs_kw)
world.plot(column='pop_est', cmap=cmap, norm=norm, ax=ax1)
mpl.colorbar.ColorbarBase(ax2, cmap=cmap, norm=norm)
ax1.set_aspect('equal')
```
Because ColorbarBase doesn't steal space, it's a ton of overhead to create a second axis that looks halfway respectable. As is, this one is too tall:
![index](https://user-images.githubusercontent.com/1300499/37580893-735155a0-2b1c-11e8-9256-48e8e2a72bec.png)

**Comment by efiring** [comment]
If I understand correctly, there are two problems:
1) `world.plot` is essentially making or using (or is) a `ScalarMappable`, but it is not giving you easy access to a `ScalarMappable` that you could use as input to `colorbar`.
2) As you say, getting the right size and shape of axes for the colorbar is a pain.

The second problem can be addressed by calling https://matplotlib.org/api/colorbar_api.html#matplotlib.colorbar.make_axes or https://matplotlib.org/api/colorbar_api.html#matplotlib.colorbar.make_axes_gridspec, which is what the `colorbar` function does to steal space and make its Axes.  Unfortunately, as with `colorbar`, it will still require some fiddling with the `shrink` kwarg because of the aspect-ratio setting of the main plot.  I think the solution for this is to use the new constraint-solver.

For the first problem, although I haven't looked at the geopandas code, it seems like it should not be hard to make `world.plot` return a ScalarMappable either directly or as an attribute of whatever it already returns.

**Comment by story645** [comment]
> For the first problem, although I haven't looked at the geopandas code, it seems like it should not be hard to make world.plot return a ScalarMappable either directly or as an attribute of whatever it already returns.

Geopandas implements choropleths as a collection of polygons, and it doesn't cleanly return those patch objects...and even if it did, it'd have to internally set the color array too going by [the patch collection colorbar](https://matplotlib.org/examples/api/patch_collection.html) tutorial. 

>The second problem can be addressed by calling https://matplotlib.org/api/colorbar_api.html#matplotlib.colorbar.make_axes or https://matplotlib.org/api/colorbar_api.html#matplotlib.colorbar.make_axes_gridspec, which is what the colorbar function does to steal space and make its Axes. 

The solution having this many fiddly steps is why I'm basically 👍 on a `plt.colorbar` type solution that has most of that baked in.

**Comment by jklymak** [comment]
i think all the basic colorbar needs is a colormap and a norm.  I think it’s not out of the question to implement passing None for the scalar mappable and then looking at new cmap and norm kwargs.  Or having a new fig.fakecolorbar that does this separately but otherwise just behaves like colorbar.  

OTOH I don’t see why geopandas can’t wrap their patches in a class that has cmap and norm in the returned object.

**Comment by ahwillia** [comment]
> Why do you want a colorbar that is not connected to anything, or at least is not connected in the normal way?

The original ask was for an animation involving line plots. See here, for example: 
 https://stackoverflow.com/questions/8342549/matplotlib-add-colorbar-to-a-sequence-of-line-plots

> Do you want a quasi-continuous one, as opposed to one with discrete segments? (I assume so.)

I guess discrete, with the ability to specify `nbins` or something so that I can make it quasi-continuous by setting it high enough.

> If so, how will plot elements in your main axes potentially generate any color within the range?

Because I will manually set the colors in the plot as well as the colorbar and make sure they match.

> What are your vmin and vmax supposed to control? Selecting a segment of the full colormap? Or the numbers to which the full range of the colormap corresponds? How do your proposed vmin and vmax relate to the vmin and vmax of the norm? (Recall that the ColorbarBase is a ScalarMappable, and has its own cmap and norm.)

Would it help for me to read up on these internals? I am coming from this as a naive outsider.

I ended up writing my own helper function that just takes a cmap and the ticks I want on the axis and then plots the thing. Does this help? https://github.com/ahwillia/jetpack/blob/master/jetpack/chart/plots.py#L328

Again, I'm fine to have this issue closed if it seems like an edge case (I'm not sure it is, given other posts here as well as on stack overflow). Matplotlib is awesome and I agree its possible to get around these issues when they do pop up.

**Comment by efiring** [comment]
@ahwillia A LineCollection is a ScalarMappable (and is also *much* faster than multiple plot calls), so I recommend that you use it with a normal colorbar call as in this example:
https://matplotlib.org/gallery/lines_bars_and_markers/multicolored_line.html?highlight=linecollection

**Comment by ahwillia** [comment]
Cool thanks! I did not know about that.

**Comment by story645** [comment]
so @phobson led me down to the solution to my problem, which is probably a general solution but also not a thing I love:

```python
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

cmap = mpl.cm.viridis_r
norm = mpl.colors.Normalize(vmin=0, vmax=1.25e9)

fig, ax = plt.subplots()
world.plot(column='pop_est', cmap=cmap, norm=norm, ax=ax)
plt.colorbar(ax.collections[0], shrink=.60)
ax.set_aspect('equal')
```

**Comment by ahwillia** [comment]
Is the philosophy of matplotlib that there should be one and only one way
to do something or are multiple solutions to the same problem ok?

Would adding something like "manual_colorbar" be feasible and not
confusing? If not I'm happy to see this closed.

**Comment by jklymak** [comment]
A new feature has to be in demand and well thought out.  Then someone has to see it through to a PR.  I think a well thought-out PR for this would be very seriously considered.

**Comment by efiring** [comment]
@ahwillia We certainly have multiple ways of doing things.  The most general example is using pyplot functions versus Axes methods.

The point of the conventional colorbar is to connect the primary plot to the colorbar, so that changing a cmap or norm in the former also changes it in the latter.  This is good for maintaining the integrity of the figure, so we want to encourage it whenever possible.  And in most cases it is possible.

**Comment by dopplershift** [comment]
@efiring What about the case of one colorbar for multiple subplots?

**Comment by jklymak** [comment]
... right now one colorbar for multiple subplots, is controlled by just one scalar mappable.  The "miultiple axes" is just a layout consideration.  Not sure how else it could work....

**Comment by ImportanceOfBeingErnest** [comment]
If I understand correctly what people want as `manual_colorbar` would be the following 3 line function:

```
def manual_colorbar(fig, norm, cmap, **kwargs):
    sm = plt.cm.ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    return fig.colorbar(sm, **kwargs)
```

While I agree that `sm.set_array([])` is pretty annoying in there (actually it has been introduced with matplotlib 1.2 or 1.3 or so, I remember it suddenly being needed for some unknown reason), it might be questionable if it's worth adding a completely new function as a shortcut. 

Couldn't this just be documented in a useful fashion?

**Comment by jklymak** [comment]
Yeah, or added to `figure` as `figure.manual_colorbar`.  I'd be fine w/ that addition.

**Comment by ahwillia** [comment]
> While I agree that sm.set_array([]) is pretty annoying in there

I think `plt.cm.ScalarMappable` is also a bit cumbersome for a new user. The idea of a colormap is very intuitive, especially when you can just pass it as a string, e.g. `plt.imshow(data, cmap='viridis')`.

> Couldn't this just be documented in a useful fashion?

I'd be happy with that as well.

**Comment by efiring** [comment]
@ImportanceOfBeingErnest That's not exactly what they want; they also want the automatic construction of the colorbar axes using space stolen from a primary axes. I don't think your version would run--it doesn't provide an axes or a way of making one.
@dopplershift, see https://matplotlib.org/gallery/images_contours_and_fields/multi_image.html#sphx-glr-gallery-images-contours-and-fields-multi-image-py.
Also see https://matplotlib.org/tutorials/intermediate/constrainedlayout_guide.html#sphx-glr-tutorials-intermediate-constrainedlayout-guide-py, but those examples need to be modified to be correct--they need to specify the same norm and cmap for each image, as in the multi-image gallery example.  As they stand, they will lead people astray. Attn @jklymak...

**Comment by ImportanceOfBeingErnest** [comment]
> they also want the automatic construction of the colorbar axes using space stolen from a primary axes.

@efiring This is precisely why one would use `fig.colorbar()` and not `mpl.colorbar.ColorbarBase()`. Because `fig.colorbar` provides the arguments `ax` and `cax` which can be used to have the colorbar either attached to an `ax` (steeling space as usual) or created inside a `cax`. 

```
ax = fig.add_subplot(332)
manual_colorbar(fig, norm, cmap, ax=ax)
```

or 

```
cax = fig.add_axes([....])
manual_colorbar(fig, norm, cmap, cax=cax)
```

The second case it pretty easily achieved with `mpl.colorbar.ColorbarBase()` as well, but for the first you would need to define your own gridspec or call the colorbar.make_axes method or use the axes_divider. 

@ahwillia I don't know what would be confusing about a ScalarMappable - except maybe the name. If you create a colorbar from an image you supply the image to the colorbar function. If you have no image you need to supply something else, and that is a ScalarMapple, i.e. the image without visual representation on screen. I remember that for me it was much more confusing to see `plt.colorbar()` actually producing something without any argument in many of the examples and I was then rather relieved reading about it taking an argument, namely the ScalarMappable.

At the end I think this can all be handled nicely in a tutorial about colormaps and colorbars.

**Comment by ahwillia** [comment]
> except maybe the name

Yes, this is what makes it confusing.

> At the end I think this can all be handled nicely in a tutorial about colormaps and colorbars.

Would be happy to see this as an addition! I just hope it ends up being easy for someone to find via google. The docs are pretty dense... Thanks for the continued interest in improving this!

**Comment by dopplershift** [comment]
@efiring I had no idea that you could give `colorbar()` an array of `Axes`. I feel like my knowledge about how to lay things out (e.g. constrained layout, grid spec) and all the things that work with it is out of date.

I think saying "Make a ScalarMappable" is an acceptable solution...provided we properly document that this as a straightforward solution. I myself, despite my experience, had no idea it was so easy to make one. This gap in my knowledge probably relates to the fact that none of our examples or tutorials actually ever show the manual instantiation of a `ScalarMappable` (they allude to it).

**Comment by jklymak** [comment]
@efiring I think I see what you mean about the norm and cmap.  But I think enforcing all that would just make the examples too complicated. I've made many many plots with shared colorbars and managed to keep my colormap and vmax/vmin the same between axes w/o invoking higher level machinery :wink:

**Comment by efiring** [comment]
@jklymak, I'm sure you have, but I strongly suspect that there will be users looking at your examples in that tutorial, using them as a model with too little modification, and getting the wrong result.  The key is that vmin and vmax *must* be explicitly set to the same values in all plots, either via the corresponding kwargs in the function or via vmin and vmax kwargs in a single norm instance used in all of the plots.  Otherwise, unless the image data in each panel happens to have the same range, the colorbar will be misleading for all but the plot to which it is directly connected.

**Comment by ImportanceOfBeingErnest** [comment]
Would someone be able to comment on why exactly a `ScalarMappable` is initialized with `self._A = None`?

https://github.com/matplotlib/matplotlib/blob/1d73e7338c0845486622238dca438cd17282efb0/lib/matplotlib/cm.py#L199

What would be the implication if that is changed to `self._A = []`?

**Comment by jklymak** [comment]
Do it and run the tests!

**Comment by ahwillia** [comment]
Just want to add a cross-reference to: https://github.com/matplotlib/matplotlib/issues/6040

Implementing support for multicolor lines (similar to `plt.scatter`) would make @efiring's suggestion to use LineCollections to circumvent the need for `manual_colorbar` much easier!
