### ISSUE TITLE
ensure removal of font cache on version upgrade

### ISSUE THREAD

**Issue by memecs** [matplotlib/matplotlib#3655]
I just re-installed matplotlib on Linux VERSION="14.04.1 LTS, Trusty Tahr". Importing matplotlib suddendly became really slow, ~3 seconds. Reason being afm.py. (details at: http://stackoverflow.com/questions/26421364/extremely-slow-import-of-matplotlib-afm). 

Matplotlib version is 1.4.0.

**Comment by naskomit** [comment]
I had the same problem. I figured out, that this happens when you upgrade matplotlib to a newer version. The cache file is not compatible with the new version, but apparently is not recreated. Instead font list is created each time on the fly. The solution is to delete the matplotlib cache directory (in my case ~/.cache/matplotlib

**Comment by Zaharid** [comment]
I can confirm this. I was able to resolve the problem by removing the matplotlib cache, as suggested here:

http://stackoverflow.com/questions/26421364/extremely-slow-import-of-matplotlib-afm

**Comment by wxgeo** [comment]
Same issue for me (matplotlib 1.4.2 on Ubuntu 15.10), and removing matplotlib cache works well too. Thanks for the tip, importing matplotlib was so painfully slow !
