### ISSUE TITLE
quiver does not consider direction of an axis

### ISSUE THREAD

**Issue by espdev** [matplotlib/matplotlib#3709]
I'm trying to plot imshow (**it inverts Y-axis**) and quiver on the same axes and I see the incorrect direction of vectors for Y-axis. In MATLAB the analogous code working correctly.

My code for example:
```python
import numpy as np
import scipy.ndimage as ndimage
import matplotlib.pyplot as plt

h = 100
w = 100

# test image (white square)
image = np.zeros((h, w))
image[20:79, 20:79] = 1

# compute X, Y gradients
gx = ndimage.convolve1d(image, [1, 0, -1], axis=1)
gy = ndimage.convolve1d(image, [1, 0, -1], axis=0)

# compute magnitude
mg = np.hypot(gx, gy)

# grid for quiver
x, y = np.meshgrid(np.arange(0, w), np.arange(0, h))

fig, ax = plt.subplots(2, 1)
ax1, ax2 = ax

ax1.set_title('Gradient mag image and Quiver')
ax1.imshow(mg, cmap=plt.cm.gray)
ax1.quiver(x, y, gx, gy, color='g')

ax2.set_title('Gradient Quiver')
ax2.set_xlim([0, w])
ax2.set_ylim([0, h])
ax2.set_aspect('equal')
ax2.quiver(x, y, gx, gy, color='g')

plt.show()
```

![image](http://habrastorage.org/files/492/dba/371/492dba371bc24f29bd45c569027d9ebf.PNG)

**Comment by tacaswell** [comment]
@efiring punting from 1.4.3 as I don't see this getting done in the next week and it has been like this apparently forever.

**Comment by efiring** [comment]
@tacaswell,  the fix is pretty simple, and I have included a test.  I have not yet made a changelog or api changes entry; I want to see whether people are comfortable with the kwarg name and values, or have a better idea.
This could be categorized as a "missing feature" rather than a "bug".  If it is more a bug than a missing feature, then the default should be changed to the newly added behavior; instead, in the present version of the PR, I kept the present behavior as the default.  At the moment, I'm having a hard time remembering why I thought the present behavior might be preferred for some applications. Ah, yes, it would be when plotting velocity arrows in an x-z plane with depth positive down but vertical velocity positive up.  That's pretty obscure, though, and easily handled by explicitly inverting the sign of the vertical velocity in the call to quiver.
