### ISSUE TITLE
possible race condition stops build with python3.4

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#3738]
Hello,
we noticed a problem in Debian buildd machines, where sometimes the build of mpl with python3.4 stuck at:

```
python3.4 ./setup.py build 
============================================================================
Edit setup.cfg to change the build options

BUILDING MATPLOTLIB
            matplotlib: yes [1.4.2]
                python: yes [3.4.2 (default, Oct  8 2014, 12:51:46)  [GCC
                        4.9.1]]
              platform: yes [gnukfreebsd9]

REQUIRED DEPENDENCIES AND EXTENSIONS
                 numpy: yes [version 1.8.2]
                   six: yes [using six version 1.8.0]
              dateutil: yes [using dateutil version 2.2]
                  pytz: yes [using pytz version 2012c]
               tornado: yes [using tornado version 3.2.2]
             pyparsing: yes [using pyparsing version 2.0.3]
                 pycxx: yes [Official versions of PyCXX are not compatible
                        with matplotlib on Python 3.x, since they lack
                        support for the buffer object.  Using local copy]
                libagg: yes [pkg-config information for 'libagg' could not
                        be found. Using local copy.]
              freetype: yes [version 2.5.2]
                   png: yes [version 1.2.50]
                 qhull: yes [pkg-config information for 'qhull' could not be
                        found. Using local copy.]

OPTIONAL SUBPACKAGES
           sample_data: yes [installing]
              toolkits: yes [installing]
                 tests: yes [using nose version 1.3.4 / using unittest.mock]
        toolkits_tests: yes [using nose version 1.3.4 / using unittest.mock]

OPTIONAL BACKEND EXTENSIONS
                macosx: no  [Mac OS-X only]
                qt5agg: yes [installing, Qt: 5.3.2, PyQt: 5.3.2]
E: Caught signal ‘Terminated’: terminating immediately
make: *** [build-3.4-stamp] Terminated
debian/rules:32: recipe for target 'build-3.4-stamp' failed
Build killed with signal TERM after 150 minutes of inactivity
```

(which got killed after 150 mins).

For now this has happened on kfreebsd-i386[1], s390x[2], i386[3] from early 1.4.1RC releases[4](the 'maybe-failed' entries)

[1] https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=kfreebsd-i386&ver=1.4.2-1&stamp=1414402804
[2] https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=s390x&ver=1.4.2-1&stamp=1414192251
[3] https://buildd.debian.org/status/fetch.php?pkg=matplotlib&arch=i386&ver=1.4.1~rc1-1&stamp=1413455146
[4] https://buildd.debian.org/status/logs.php?pkg=matplotlib

this is currently prevent matplotlib to be build on all Debian release architectures and thus reaching testing and Jessie for the freeze.

**Comment by sedimentation-fault** [comment]
Sorry for commenting on an old bug, but I am trying to install matplotlib-2.2.4 for Python 3.6 and 3.7 on a Gentoo system. It had worked previously, but I had to rebuild it because I wanted to remove Python 2.7 support.

So I had it installed for Python 2.7, 3.6 and 3.7. Then I decided to throw away 2.7. This time compilation for Python 3.6 went smooth, but for 3.7 it could not find gtk3agg due to 'Check timed out'. I thought it was a 3.7 problem, so I disabled 3.7 too. Now it cannot find gtk3agg for 3.6 due to the same timeout reason.

I decided to re-enable building for both Python 3.6 and 3.7 again - and again, gtk3agg is built for 3.6 but not for 3.7 due to timeout.

Now, a word about the load on the system while this is going on: the load is anywhere between 17 and 44(!). Yes, fortyfour. Who cares? There are 8 virtual CPUs at 3GHz each and 50 GB of RAM waiting to be used - so I use them. Since when has the load on a system any effect on the result of a test like 'do you have GTK3 for Python installed?'?

As you can see, just setting a 5 sec. timeout on a test will not cut it. The result is clearly dependent on the load - and you should not impose a maximum load on your users. What you can do is possibly inquire about the current load and set a timeout that depends on it. That is, if you would set a timeout of 5 sec. for a load of 0.2, then how high should it be for a load of 17 - or even 44?

You have to think more deeply about this...

**Comment by tacaswell** [comment]
We can not do the checks in-process due to conflicts of importing more than one GUI toolkit into the same process, if we do it in a sub-process.  If we do it without a timeout we run the risk of hanging the build forever if things go extremely sideways (as this issue reported).

This seems like a rather extreme edge case where you have loaded your system to the point where it is essentially non-responsive.  I am disinclined to pick up the complexity of a load-dependent timeout for this case, but if you open a PR we can discuss how what the complexity trade off actually looks like.

The fastest path forward for you is to inject a patch into the gentoo build process (https://wiki.gentoo.org/wiki//etc/portage/patches I think that this falls under the category of "site-specific patches") that removes the timeout.  It is between you and the gentoo packagers if they take that upstream.

In the future please open a new issue that refers to old ones rather than commenting on old ones.

-----

As a side-point, I strongly suspect that you are actually taking longer in wall time to get things done (due to the cost of context switching / cache misses etc) by over loading your system that way.
