### ISSUE TITLE
Update colormap examples.

### ISSUE THREAD

**Issue by chebee7i** [matplotlib/matplotlib#3791]
The colormap demos shown:

http://matplotlib.org/examples/color/colormaps_reference.html

and

http://matplotlib.org/users/colormaps.html

do not include all colormaps that are available in Matplotlib. They also are not consistent with each other in that they show different subsets of the Matplotlib colormaps (e.g. #2659 treated binary and gray as equivalent but #3301 did not. For the record, they are not equivalent.). I can tackle this issue soonish---I just wanted to create an issue as a reminder. I also think it would be helpful if these categorizations were part of Matplotlib and available programmatically. Also related: #889.

**Comment by alimuldal** [comment]
The [example plots](http://matplotlib.org/users/plotting/colormaps/lightness.py) for the new colormaps look wrong - the lightness axis seems to be inverted:

![Broken new  colormap examples](http://matplotlib.org/_images/lightness_00.png)

**Comment by mdboom** [comment]
@alimuldal: This is puzzling as these figures are all generated from the same code.  @njsmith, @kthyng: Any thoughts?

**Comment by kthyng** [comment]
Ah yes, this is just due to whether the colormap increases or decreases in lightness across the colormap. I did it in a kludge-y way originally, but I can do a better job. Also, I can use the CAM02-UCS colorspace from viscm to calculate the lightness instead of CIELAB, which will give slightly different results. That whole page could use a bit of an update, huh. I'll work on this in the next few weeks.

**Comment by kthyng** [comment]
I fixed the lightness plot code at pull request #5591.

**Comment by tacaswell** [comment]
fixed by #5591
