### ISSUE TITLE
bars plotted on polar axes still have visible boundaries when linewidth is 0

### ISSUE THREAD

**Issue by atpage** [matplotlib/matplotlib#3873]
For example, let me plot 20 blue bars around a circle:

```
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import ranf
ax = plt.subplot(111, polar=True)
for i in range(20):
    ax.bar(left=2*np.pi*i/20.0, height=ranf(), width=2*np.pi/20, color='blue', linewidth=0)
plt.show()
```

We see that there are faint lines/gaps along the boundaries between bars.  This does not occur in the cartesian version:

```
ax = plt.subplot(111)
for i in range(20):
    ax.bar(left=2*np.pi*i/20.0, height=ranf(), width=2*np.pi/20, color='blue', linewidth=0)
plt.show()
```

Going back to the polar version, if I add a small epsilon to the bar width:

```
ax = plt.subplot(111, polar=True)
eps = 0.01
for i in range(20):
    ax.bar(left=2*np.pi*i/20.0, height=ranf(), width=2*np.pi/20+eps, color='blue', linewidth=0)
plt.show()
```

The problem almost goes away (except at small r), indicating that there may be some floating-point/rounding errors along the radial lines.  So this may not be fixable, but thank you for taking a look.

**Comment by dabana** [comment]
Playing around with the code snippets provided above, I discovered a somewhat related issue with the cartesian version of the bar graph as well. 

If you add a NEGATIVE epsilon to this bar graph, it creates white spaces but in an inconsistent way. It skips some spaces (for example a white space every 4 bars instead of every bar as expected) or the width of the space seams to be different from one an other. When you re-scale to graph horizontally, the behavior of the white space changes.

```
import numpy as np
import matplotlib.pyplot as plt
from numpy.random import ranf
ax = plt.subplot(111)
eps = -0.005
for i in range(20):
    ax.bar(left=2*np.pi*i/20.0, height=ranf(), width=2*np.pi/20+eps, color='blue', linewidth=0)
plt.show()
```
Looks like an improper rounding error handling indeed.

Tested on matplotlib version 2.1.2 and 2.0.2

**Comment by dabana** [comment]
crossref #5694

**Comment by dstansby** [comment]
![Figure_1](https://user-images.githubusercontent.com/6197628/178807897-edae5040-a1e8-4f94-85a5-3e418d034dd4.png)

There don't seem to be any gaps/boundaries between bars on current `main` branch, so I'm going to close this; @atpage if this is still an issue for you, let us know be leaving a comment here and I can re-open the issue.
