### ISSUE TITLE
MacOSX backend: figure windows are shy [iTerm?]

### ISSUE THREAD

**Issue by kcarnold** [matplotlib/matplotlib#391]
Any newly created figure window is shown behind my active iTerm2 (beta) window. Neither Command-Tab nor Command-backtick gives the new window as an option. Even after selecting it in Exposé it falls behind the active app as soon as the animation completes.

The possible cause of all of this behavior is that the windows do not appear associated with any particular application. Though sub-optimal, it may be necessary to do that.

**Comment by nils-werner** [comment]
I am still seeing this issue, despite having `brew install python --framework` and trying several virtualenv fixes. Anybody else still seeing the same thing?

**Comment by ezietsman** [comment]
Yes, mine does this too.

**Comment by tacaswell** [comment]
@jenshnielsen mentioned writing documentation about how to deal with venv + framework issues.

**Comment by jenshnielsen** [comment]
Im working on the docs in https://github.com/jenshnielsen/matplotlib/blob/virtualenvdocs/doc/faq/virtualenv_faq.rst but progress has been to slow (Most of the basic contents should be there in the OSX section). I still hope to get it in to 1.5 

Basically even if your python version is a framework the virtualenv will not be. That is IMHO a bug in virutalenv. See the links to venv bug reports in that document. 

`brew install python --framework` does nothing as far as I know since brew python is always a framework build (That has changed since the time of writing of whatever suggests `--framework`) 

The script mentioned in that file works for me. It's based around using the system python and PYTHONHOME to relocate the import to use the virtualenv packages. 

Note that in 1.5 we have included a check to verify that Python is a framework build so you should at least get a clear error and not the strange shy behaviour.

**Comment by jenshnielsen** [comment]
@nils-werner or @ezietsman it would be great if you have the chance to test the script mentioned

**Comment by ezietsman** [comment]
Thanks, this works for me. I'm using matplotlib interactively inside a `venv` via `pyramid` so I need pshell too. I use the following command to make that happen:

    ./venv/bin/frameworkpython -m pyramid.scripts.pshell development.ini

**Comment by eas342** [comment]
I was experiencing this problem with my Anaconda installation. It seems to be fixed when I edited my `~/.matplotlib/matplotlibrc`:

    backend: MacOSX

**Comment by alexTnuts** [comment]
Want the one-line answer ? Just type:

plt.ion()

I know it's been quite a long time that the question was asked, but I had this problem today and looked for an answer for hours.
So it might be helpful for next people to know that straight answer.

Thanks to this guy https://www.youtube.com/watch?v=1zmV8lZsHF4 at 23:30 !

'plt' is used because of my import: import matplotlib.pyplot as plt

I'm using python2.7 on a mac with iTerm2.
