### ISSUE TITLE
setting up matplotlib for development

### ISSUE THREAD

**Issue by eyurtsev** [matplotlib/matplotlib#3959]
I read through the developer instructions (http://matplotlib.org/devel/index.html) and am still unsure as to the best workflow for matplotlib development. Specifically, I want to work on code that's under git control, but have the changes applied immediately (e.g., with %autoreload magic) if possible.

After these steps (from http://matplotlib.org/devel/gitwash/set_up_fork.html):

```bash
git clone git@github.com:your-user-name/matplotlib.git
cd matplotlib
git remote add upstream git://github.com/matplotlib/matplotlib.git
```
I would have loved to add matplotlib to the python path (i.e., "matplotlib/lib/matplotlib"). However, doing so doesn't work (probably because of stuff missing that's added during the build).

```python
---> 39 from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
     40     update_path_extents)
     41 from numpy.linalg import inv

ImportError: No module named _path
```

Any help for setting up for development will be appreciated!

**Comment by eyurtsev** [comment]
Worked like a charm! I didn't know about the develop option! :+1:

**Comment by tacaswell** [comment]
That really should be in the workflow documentation someplace.

Does it play nice with %autoreload?

**Comment by eyurtsev** [comment]
%autoreload doesn't seem to work for me either. I suspect that autoreload fails due to some issue with inheritance.

```python
TypeError: unbound method __init__() must be called with blah blah blah... 
```

Anyway, otherwise it's good! :)

**Comment by WeatherGod** [comment]
I used to be a fan of the "develop" mode, but not for a while now. Problems
occur when files are moved around (leaving the old .pyc around), and when
the C code gets modified. I am against recommending it on this page.

**Comment by eyurtsev** [comment]
sorry just saw the comment.. but already made a PR. @WeatherGod could you describe your set up?

**Comment by WeatherGod** [comment]
I just remember to do "python setup.py install" if I am doing a venv, or I tack on the "--user" option if I am not. Back when I was a big champion of the "develop" mode, there were older, more experienced members of the numpy/scipy community who cautioned against using it. But I ignored them, thinking that I knew better and was being more productive.

I was wrong... so very, very wrong.

**Comment by eyurtsev** [comment]
@WeatherGod  just to make sure I understand the workflow you suggest.

Say I have a copy of the matplotlib source code under git control in the following path:

```bash
~/development/matplotlib/
```

Then after making modifications to the source code, I'll need to test it out. To do that I should install the source code:

```bash
cd ~/development/matplotlib/
python setup.py install
```

This puts the new version in the site-packages; e.g., ```~/.virtualenvs/dev_matplotlib/local/lib/python2.7/site-packages```

So now it becomes importable in python. This process helps avoid issues arising from conflicts with old .pyc files and modifications of C code, but also means that I need to ``` run python setup.py install ``` each time?

Do you think it would be sufficient for me to run ```python setup.py develop``` every time after pulling from upstream to avoid these issues? (Assuming I'm not working on any C code myself?)

**Comment by WeatherGod** [comment]
Yes, you would need to rerun the setup.py install after each change. For
me, it is entirely muscle memory to make a change, run "python setup.py
install" and then "python setup.py nosetests", or whatever other program I
am working on. This is the same for any other project, which is why it is
muscle memory at this point for me.

As for the question of if it is sufficient, you are running through the
same thought processes that I had four years ago. In the ideal world, yes,
it is sufficient. Unfortunately, distutils is far from the ideal world.
Python packaging is far from ideal. It isn't a question of if, but *when*
something will go wrong. The terrible thing about it is that it usually
goes wrong in some subtle, strange and silent way. I didn't notice that
something was wrong with my devel environment until people started
complaining that I was checking in broken code. My tests were passing, but
the environment was in such a strange state that I had to nuke the whole
thing. To this day, I still don't know what I did wrong, but I haven't
gotten there since I stopped using the develop mode.

**Comment by tacaswell** [comment]
I use `git clean -xfd` quite liberally, but I jump between master branch
and 1.4.x frequently.

I have actually had similar problems to what Ben is describing even using
install (mostly, again, jumping between branch and issues with stale so/pyc
files getting installed) and it is easier to clean up the source tree than
get the figure out how to get the un-install to work correctly.

**Comment by efiring** [comment]
Sometimes even all that is not enough, and you actually have to blow away the installation before running `setup.py install` again. I think this was the case with the switch from axes.py to axes/, for example. 
In the appropriate site-packages or dist-packages directory, do `rm -rf` on each of the following:
```
 "matplotlib*", "pylab*",
 "mpl_toolkits/mplot3d",
 "mpl_toolkits/axes_grid",
 "mpl_toolkits/axes_grid1"
```

**Comment by madphysicist** [comment]
This is a very very useful thread. Bits of it should be enshrined in the documentation. Another option is to set it up so that `python texts.py ...` runs in the current directory. This is how it works for `numpy`/`scipy`. Part of the problem is the extra `lib` folder on the way to `matplotlib`.

**Comment by WeatherGod** [comment]
I can not begin to express my complete and utter disdain for numpy/scipy's
choice of putting a directory that is the same name as the package in the
root directory. If I am doing development while in the root directory, I
often want to check something using pydoc, but I can't do that for those
projects. And I can't just simply back out by one directory, because the
source tree is contained in a folder by the same name. I have to back up by
two directories. Argh!

**Comment by madphysicist** [comment]
@WeatherGod fair enough. That is probably not the way to go. However, I am sure that there is some other way to implement the ability to run tests directly in the root directory. Would something as simple as `cd lib; python ../tests.py` be effective?

**Comment by jniediek** [comment]
I'm about to write my first bug fix for matplotlib, but I'm having trouble getting started. I followed the developer's guide (http://matplotlib.org/devel/index.html). The guide suggests that it is possible to clone your fork of matplotlib and then run `python tests.py`. This neglects that one must first tell python which matplotlib to use (I did `PYTHONPATH=/path/to/my/clone/lib python tests.py`, but is this recommended?). Then, the guide does not mention that one has to compile some parts first. So I did `python setup.py build`. And here I'm stuck. `python setup.py develop` tries to create a whole new directory tree, which would be outside of the git repository. Is that intended?

I'm happy to contribute to matplotlib, but it would be great if the developer's guide could be more complete in this respect. Once I understand what to do, I'll be able to add this info to the developer's guide.
