### ISSUE TITLE
Axes fonts with text.usetex 'true' does not use set font

### ISSUE THREAD

**Issue by xkryptor** [matplotlib/matplotlib#3999]
I set the font style in the matplotlibrc param file to Helvetica (sans serif) and I set text.usetex to 'True' but the axes fonts use serif fonts. How do I get the axes fonts to use sans serif?

**Comment by tacaswell** [comment]
@xkryptor Why did you close this?  If you sorted out your problem could you post an update here? If you think the documentation should be improved can you put in a PR to improve them?

**Comment by xkryptor** [comment]
I am sorry, I think I accidently closed it.

**Comment by petehuang** [comment]
Recommend labeling as need confirmation

You'll need latex and the following lines to try to reproduce:

```python
from matplotlib import rcParams
rcParams['font.family'] = 'sans-serif'
rcParams['font.sans-serif'] = ['Helvetica']
rcParams['text.usetex'] = True
```

**Comment by Kojoley** [comment]
I am not sure what the original issue about because in my case the font changes (except the ticks).

```python
import matplotlib.pyplot as plt
from matplotlib import rc

rc('text', usetex=True)
for b in [False, True]:
    if b:
        rc('font', **{'family': 'sans-serif', 'sans-serif': ['Helvetica']})

    fig, ax = plt.subplots()
    ax.set_title('Title')
    ax.set_xlabel('X Axis')
    ax.set_ylabel('Y Axis')
    ax.plot([0, 1], [0, 1])

    fig.savefig('issue_3999_%d.png' % int(b))

from matplotlib.testing.compare import save_diff_image
save_diff_image('issue_3999_0.png', 'issue_3999_1.png', 'issue_3999-diff.png')
```

![issue_3999_0](https://cloud.githubusercontent.com/assets/2743474/21645179/103fa79c-d2a2-11e6-9194-74d93d43e45a.png)
![issue_3999_1](https://cloud.githubusercontent.com/assets/2743474/21645182/1394b496-d2a2-11e6-9456-e6e06648368f.png)
![issue_3999-diff](https://cloud.githubusercontent.com/assets/2743474/21645184/16ee38c4-d2a2-11e6-89cc-71375a9b6572.png)

**Comment by jklymak** [comment]
I'll close this as inactive
