### ISSUE TITLE
plt.plot fails if given `x` and `y` kwargs

### ISSUE THREAD

**Issue by Garrett-R** [matplotlib/matplotlib#4059]
When I execute the following command:

```
python3 -c "import matplotlib.pyplot as plt; plt.plot(x=[0,1], y=[0,1]); plt.show()"
```

it outputs: 

![Empty_Plot](https://cloud.githubusercontent.com/assets/6614695/5990571/691ad1e6-a96b-11e4-9430-1b890e56b2b7.png)

---

_Edit_: I see my error.  I was not supposed to provide the data as keyword arguments. Indeed `plt.plot([0,1], [0,1])` works fine.

I don't know anything about how matplotlib works, but perhaps `plot` should be able to handle this (similar to how `pandas.DataFrame.plot` can handle this):

```
import pandas as pd
df = pd.DataFrame([[0,0],[1,1]], columns=['A', 'B'])
df.plot('A', 'B')
df.plot(x='A', y='B')
```

If that's not desirable, then perhaps it could at least throw an error or give a warning that an unexpected keyword argument was given...

**Comment by blink1073** [comment]
@Garrett-R, `plot` does not take `x` and `y` as keyword arguments.  This works:

`python3 -c "import matplotlib.pyplot as plt; plt.plot([0,1], [0,1]); plt.show()"`

**Comment by Garrett-R** [comment]
@blink1073, thanks I must have realized it as the same time, because I just edited my original post.

**Comment by blink1073** [comment]
@Garrett-R, the problem with your suggestion is that `plot` can take multiple sets of arguments, for example:

`python3 -c "import matplotlib.pyplot as plt; plt.plot([0,1], [0,1], 'b', [0, .8], [0, 1], 'r'); plt.show()"`

**Comment by blink1073** [comment]
But perhaps the `x` and `y` kwargs could just be treated as if they were the first set of args...

**Comment by blink1073** [comment]
With this change your original example works:

```diff
diff --git a/lib/matplotlib/axes/_axes.py b/lib/matplotlib/axes/_axes.py
index 940ebdd..7db782f 100644
--- a/lib/matplotlib/axes/_axes.py
+++ b/lib/matplotlib/axes/_axes.py
@@ -1365,6 +1365,12 @@ class Axes(_AxesBase):
             self.cla()
         lines = []
 
+        if 'y' in kwargs:
+            args = (kwargs.pop('y'),) + args
+
+        if 'x' in kwargs:
+            args = (kwargs.pop('x'),) + args
+
         for line in self._get_lines(*args, **kwargs):
             self.add_line(line)
             lines.append(line)
```

**Comment by Garrett-R** [comment]
I like it!  :+1:  

I wonder if there's any downsides to that.  I know the upside.  I spent about an hour trying to debug my code, and had to read the the matplotlib source before realizing the `x` and `y` kwargs weren't being looked at.

**Comment by blink1073** [comment]
It could certainly be made more robust, but I agree it is a nice add.  I'll let one of the core devs chime in.

**Comment by tacaswell** [comment]
The `plot` api is modeled on the MATLAB api and far too magical, but changing it to simplify it is a non-starter (because it would break too much code) and I am not a huge fan of adding any _more_ magic to it.

One concern I have about @blink1073 's patch is that if there is a `x` kwarg, but no `y` it will erroneously convert the x -> y which would be bad. 

My knee jerk reaction is :-1: , but am open to being convinced other wise. 

Also, I don't think any of the docs say that you _can_ pass in the x/y values via kwargs (if there are, please point me to them so they can be removed).

**Comment by blink1073** [comment]
@tacaswell, that's why I said it needed more clean up. :smile:
I don't consider it magic if it is documented and intuitive, which I think this would be.  A simple change to check for the presence of `x'`before using `y` would cover your concern.

**Comment by blink1073** [comment]
The fact that I could not immediately look at @Garrett-R's example and see *why* it would fail is a good indicator...

**Comment by WeatherGod** [comment]
I share thomas's concern. I have repeatedly made attempts to refactor that
code, and failed. My failure to fix it is the main source for my imposter
syndrome in this project...

If changes are made here, then where else should it go? scatter()? bar()?
loglog()? What about polar() with kwargs of "r" and "theta"?

Nah, I think the real problem here is that there was no error reported. No
data was supplied! I know I am a huge fan of ensuring that the plotting
functions work with empty inputs, but I wouldn't go so far as working for
non-existent inputs!

-1

**Comment by blink1073** [comment]
Fair enough.  Then, there are two problems: there should be at least one `arg` given to these functions, or they should raise an error.  The other problem is that there is no handling of *invalid* kwargs (they're just ignored).

**Comment by tacaswell** [comment]
It is made extra bad in mpl due to the way that we pass things up (down) the stack so we _can not_ do validation at most levels.  I suspect the right place to blow up is in the `Artist` constructor.

@WeatherGod I recently dove into the `plot` arg parsing code a bit (69decec0297f5693303297800e5e05252b4663f9 which has an astoundingly high commit message length / number of lines changed ratio) and there is no shame in getting bogged down/confused by that code!

**Comment by petehuang** [comment]
Given the reactions from @tacaswell and @WeatherGod, should we close this with no intent to proceed?

**Comment by WeatherGod** [comment]
Well, we should probably still raise an error if `plot()` doesn't see any arguments.

**Comment by efiring** [comment]
It might even not be too difficult to handle the no-args case with x and/or y kwargs, bypassing all the logic required to handle the Matlab-style parsing.

**Comment by anntzer** [comment]
This now errors out with "TypeError: plot got an unexpected keyword argument 'x'".
It was argued in https://github.com/matplotlib/matplotlib/issues/11526 that we should not support keyword arguments in this case, so I'll just close this.
