### ISSUE TITLE
3D figures cannot be created in 1.4.2: 'module' object has no attribute '_string_to_bool'

### ISSUE THREAD

**Issue by chzhang** [matplotlib/matplotlib#4064]
I was trying to run some of the examples provided by http://matplotlib.org/examples/mplot3d/2dcollections3d_demo.html

The occur some error as follows:
<code>
Traceback (most recent call last):
  File "some.py", line 34, in <module>
    ax = p3.Axes3D(fig)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/mpl_toolkits/mplot3d/axes3d.py", line 91, in __init__
    *args, **kwargs)
  File "/Library/Python/2.7/site-packages/matplotlib/axes/_base.py", line 436, in __init__
    self.cla()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/mpl_toolkits/mplot3d/axes3d.py", line 1045, in cla
    Axes.cla(self)
  File "/Library/Python/2.7/site-packages/matplotlib/axes/_base.py", line 897, in cla
    self.grid(self._gridOn, which=rcParams['axes.grid.which'])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/mpl_toolkits/mplot3d/axes3d.py", line 1256, in grid
    self._draw_grid = maxes._string_to_bool(b)
AttributeError: 'module' object has no attribute '_string_to_bool'
</code>

OS : OS X Yosemit 10.10.2
Python version:  2.7.6
matplotlib : 1.4.2

Install matplotlib use by 'pip'

I solved the problem by used 
http://stackoverflow.com/questions/25383698/error-string-to-bool-in-mplot3d-workaround-found iamaziz's answer:

1) rename (or delete) the folder mplot3d (so matplotlib thinks it's not there):
<code>
/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/mpl_toolkits/mplot3d-old
</code>
2) update matplotlib with specifiying mplot3d:
<code>
pip install --upgrade 'matplotlib[mplot3d]'
</code>

**Comment by jenshnielsen** [comment]
I think this is caused by Apple installing an old version of Matplotlib with their system Python. ( 1.3.x I think). In older release the toolkits where stored in a seperat folder `mpl_toolkits` which have since been moved into the matplotlib folder. Thus this version is not overwritten when installing a new version of matplotlib and wrongly picked up when importing the toolkits. Does pip install into `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python` for your version of python? If that is the case you will need to get rid of the old Apple version of matplotlib from this directory before pip installing matplotlib since this version was not installed by pip and can't be safely upgraded. 
 
Personally I would recommend using an alternative python which does not use the apple packages. I have seen several issues like this one caused by the Apple packages. Personally I use homebrews python. But other alternatives are Anaconda/conda and Enthought canopy and official Python.org python.

**Comment by chzhang** [comment]
Thanks you for your advice.
I think I will use homebrew to install python
