### ISSUE TITLE
Colormap set_under and set_over have no effect on color bar for PolyCollection

### ISSUE THREAD

**Issue by durden** [matplotlib/matplotlib#4117]
I'm trying to control the over and under colors of a color bar with `set_under` and `set_over` on a `ListedColormap` object.  I do not see the colors change, but I do see the arrows added to the color bar.

For example, the following code mostly works but the calls to `set_under` and `set_over` seem to have no effect.  I'm trying to use [this color bar documentation](http://matplotlib.org/examples/api/colorbar_only.html) as a guide.  Maybe I'm doing something wrong or the example is slightly off?

I'm using matplotlib 1.4.0.

```python
import numpy
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.collections import PolyCollection

vertices = numpy.load('vertices.npy')
array = numpy.load('array.npy')

# Take 2d slice out of 3D array
slice_ = array[:, :, 0:1].flatten(order='F')

fig, ax = plt.subplots()

poly = PolyCollection(vertices, array=slice_, edgecolors='black', linewidth=.25)

cm = mpl.colors.ListedColormap([(1.0, 0.0, 0.0), (.2, .5, .2)])
cm.set_under('0.75')
cm.set_over('DarkViolet')
poly.set_cmap(cm)

bounds = [.1, .4, .6]
norm = mpl.colors.BoundaryNorm(bounds, cm.N)
bounds = [0.0] + bounds + [1.0]
fig.colorbar(poly, ax=ax, orientation='vertical', boundaries=bounds, norm=norm,
        extend='both')

ax.add_collection(poly, autolim=True)
ax.autoscale_view()

plt.show()
```
![plot_with_mask](https://cloud.githubusercontent.com/assets/58063/6237335/a9d01918-b6b7-11e4-9746-e41286b191f4.jpg)

**Comment by efiring** [comment]
(I would prefer that questions like this start out on the matplotlib-users list so that a wider audience would have a chance to respond, and would see the solution.  If the response on the list indicates that the problem really is a bug, then that's the time to open a github issue.  It's also best to provide a minimal self-contained example, so anyone can experiment with it.)

The following example uses an Image rather than a PolyCollection, but I think you will find that it illustrates what you want.  Notice that the `colorbar()` method gets the information it needs directly from the 'Mappable' object that is its first argument.

```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

z = np.linspace(0, 1, 100).reshape(10, 10)

fig, ax = plt.subplots()

cm = mpl.colors.ListedColormap([(1.0, 0.0, 0.0), (.2, .5, .2)])
cm.set_under('0.75')
cm.set_over('DarkViolet')

bounds = [.1, .4, .6]
norm = mpl.colors.BoundaryNorm(bounds, cm.N)

im = ax.imshow(z, interpolation='nearest', cmap=cm, norm=norm)

fig.colorbar(im, ax=ax, orientation='vertical',
        extend='both')

plt.show()
```

**Comment by durden** [comment]
No problem.  Sorry for the confusion, but thanks for the update.
