### ISSUE TITLE
Percent signs don't show up in labels with ps backend and usetex=True

### ISSUE THREAD

**Issue by moorepants** [matplotlib/matplotlib#4307]
With this code I see percentage signs in the labels:
```python
import matplotlib.pyplot as plt

fig, axes = plt.subplots(4)

axes[0].plot([1, 2, 3], [4, 5, 6])
axes[0].set_xlabel('100%')
axes[0].legend(['100%'])

axes[1].plot([1, 2, 3], [4, 5, 6])
axes[1].set_xlabel(r'100%')
axes[1].legend([r'100%'])

axes[2].plot([1, 2, 3], [4, 5, 6])
axes[2].set_xlabel('100/%')
axes[2].legend(['100/%'])

axes[3].plot([1, 2, 3], [4, 5, 6])
axes[3].set_xlabel(r'100%')
axes[3].legend([r'100/%'])

plt.tight_layout()

plt.show()
```
![percentage01](https://cloud.githubusercontent.com/assets/276007/6977019/f691eb90-d968-11e4-8e3c-c1e3a9f71f98.png)

But with this code I don't:
```python
import matplotlib.pyplot as plt

params = {'backend': 'ps',
          'text.usetex': True,
          }

plt.rcParams.update(params)

fig, axes = plt.subplots(4)

axes[0].plot([1, 2, 3], [4, 5, 6])
axes[0].set_xlabel('100%')
axes[0].legend(['100%'])

axes[1].plot([1, 2, 3], [4, 5, 6])
axes[1].set_xlabel(r'100%')
axes[1].legend([r'100%'])

axes[2].plot([1, 2, 3], [4, 5, 6])
axes[2].set_xlabel('100/%')
axes[2].legend(['100/%'])

axes[3].plot([1, 2, 3], [4, 5, 6])
axes[3].set_xlabel(r'100%')
axes[3].legend([r'100/%'])

plt.tight_layout()

plt.show()
```
![percentage02](https://cloud.githubusercontent.com/assets/276007/6977021/fab4e6f0-d968-11e4-807e-006598f548a6.png)
I haven't been able to figure out how to display percentage signs.

It is even trickier with things like:
```python
ax.legend(['{:1.1%}'.format(0.56)])
```

**Comment by tacaswell** [comment]
I think the escape slash is the other way:  http://tex.stackexchange.com/questions/34580/escape-character-in-latex.

**Comment by moorepants** [comment]
Thanks, you are correct.

And I guess there probably isn't a clean way to deal with this:

```python
ax.legend(['{:1.1%}'.format(0.56)])
```
besides:
```python
ax.legend(['{:1.1f}'.format(100.0 * 0.56)])
```

**Comment by mdboom** [comment]
@moorepants: Yeah -- unfortunately so.  Except perhaps the alternative:

```
ax.legend(['{:1.1%}'.format(0.56).replace('%', r'\%')])
```

(which I admit isn't much better).

In general, we just pass the string along to LaTeX verbatim, and of course there are various "special" characters in TeX that need to be escaped, such as `%`, which is the comment character.

http://www.giss.nasa.gov/tools/latex/ltx-164.html

You could *almost* make the case that a `%` should never mean comment character when it comes from matplotlib, and we should escape it on the user's behalf.  The same isn't really true of other special characters (except maybe `#`).  But I'm not sure if it's better to say "we escape some things" than "we escape nothing, the onus is on the user to escape things, and it's pretty obvious how everything flows along..."

**Comment by moorepants** [comment]
@mdboom Thanks for the comment. The behavior in matplotlib should probably stay the same. It just took a while to figure out why my plots were failing to show the percent.

**Comment by z-a-f** [comment]
Found this issue years after the fact :)

> But I'm not sure if it's better to say "we escape some things" than "we escape nothing, the onus is on the user to escape things, and it's pretty obvious how everything flows along..."

I don't think this is a fair argument. Here is my line of thinking:

1. Python has an [explicit contract](https://docs.python.org/3/tutorial/inputoutput.html#fancier-output-formatting) with users that '%' sign will be shown if formatting requests it.
2. TeX uses some special characters that need to be escaped. The list of those characters are [documented in MPL](https://matplotlib.org/stable/tutorials/text/usetex.html)
3. As a result of (2) users know that they cannot use '%' without escaping it.
4. However, due to (1) users have an option to "autogenerate" the strings using python's formatting mechanics.

What is the most confusing is that there ARE places in MPL that handle the TeX characters correctly. For example, [PercentFormatter](https://github.com/matplotlib/matplotlib/blob/862f85d37a0f0da270d93aa3a59157bb9f1553d3/lib/matplotlib/ticker.py#L1580-L1597) escapes all special characters. If that's an option for one part of the code, why is it ambiguous for other parts?

**Comment by tacaswell** [comment]
I do not quite understand what you mean in 1.  It is clear that any system that does string formatting and/or markup is going to have both special characters and a way to escape treating those characters as special, the core of the issue here is that every system does this slightly differently.    In general we can not look at a string and guess which of the special LaTeX symbols the user meant to be passed to LaTeX.  Mike's point is that we probably could say "right, putting comments in the text you pass to Matplotlib makes no sense, we will always escape `'%'`", however then we would be in the case were we are treating some tex symbols differently than others.  The idea is that it is easier to explain and for users to remember "you must do your own escaping when passing strings to latex" than "You must do your own escaping for everthing but `'%'`". 

As for `PercentFormatter` that seems to be to be a very special case as it is escaping something that we expect to be one or two symbols rather than arbitrary strings (yes, it _takes_ arbitrary strings but that is not its purpose).  It is also well documented and has as escape hatch to turn the auto-escaping off.

That said, it might be interesting to investigate adding a "please escape for latex" flag on the `Text` object (like the `use_tex` flag) that will do the escaping for the user as late as possible.  @z-a-f Please open a new issue if you want propose and advocate for this feature.
