### ISSUE TITLE
MatplotlibDeprecationWarning: Use `xyann` instead 

### ISSUE THREAD

**Issue by dashesy** [matplotlib/matplotlib#4440]
Version is 1.4.2 and I get deprecation warning so I would like to use the recommended way.
I use `a.xytext = (xpos, 0.8)` on response to user clicking on certain parts, if the functionality gets deprecated how can we dynamically `move` annotations? I am not talking about adding new annotations here. Of course one can delete the previous one and recreate a new annotation but that is not exactly same functionality.

**Comment by tacaswell** [comment]
`xytext` is an alias for `xyann`.  Just switch to using `a.xyann` instead of `a.xytext` .

Also see http://matplotlib.org/api/api_changes.html#changes-in-1-4-x

This was done in https://github.com/matplotlib/matplotlib/pull/2351

The aliases were removed from the master branch in 310cab1f50fa534c4adefbf174fa74b7eccc8bf9, but maybe that should be reverted for another release cycle or so.

**Comment by tacaswell** [comment]
Sorry, wrong button

**Comment by dashesy** [comment]
thanks, yes simply using `xyann` is working fine
