### ISSUE TITLE
Qt figure options widget can't undo step linestyle

### ISSUE THREAD

**Issue by rmccampbell** [matplotlib/matplotlib#4447]
If you set the "step" linestyle using the Qt Figure Options dialog, it can't be undone. This seems to be because step is actually a drawstyle, and is treated separately from the other options. The "default" drawstyle should be added to the combo box so it can be reset, or the default option could be appended to the other linestyles.

**Comment by tacaswell** [comment]
That is...odd..

**Comment by mfitzp** [comment]
This bug results (as @rmccampbell suspected) from the "steps" linestyle being handled differently to others - 'steps' is a `drawstyle` not a `linestyle`. You can reproduce the effect with this code:

    import matplotlib
    import matplotlib.pyplot as plt

    plt.plot([0,1,2,3,4])
    for line in plt.gca().get_lines():
        line.set_linestyle('--')
    plt.show()

    plt.plot([0,1,2,3,4])
    for line in plt.gca().get_lines():
        line.set_linestyle('steps')
    plt.show()

    plt.plot([0,1,2,3,4])
    for line in plt.gca().get_lines():
        line.set_linestyle('steps')
        line.set_linestyle('--')
    plt.show()

    plt.plot([0,1,2,3,4])
    for line in plt.gca().get_lines():
        line.set_linestyle('steps')
    plt.show()

As you can see 'steps' linestyle isn't overridden by the others: because it's a `drawstyle`. If we apply the `drawstyle` equivalent of normal, it reverts:

    import matplotlib
    import matplotlib.pyplot as plt

    plt.plot([0,1,2,3,4])
    for line in plt.gca().get_lines():
        line.set_linestyle('steps')
        line.set_linestyle('default')
    plt.show()

Either way the fix is fairly simple: add another drop down for drawstyle switching and apply that as a separate step from the linestyles. I'll work up a PR.
