### ISSUE TITLE
shared axes switch to log scale

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#4450]
Consider

```
fig, axs = plt.subplots(2, 2, sharex=True, sharey=True)
for i in range(2):
    for j in range(2):
        axs[i, j].hist(np.arange(10) + 10 ** (i + j)) # widely varying scales
for ax in axs.flat:
    ax.set_xscale("log")

plt.show()
```

The axes end up x-relim'd to the data limits of the last axes, hiding away the other histograms (that part seems vaguely related to #3481?).

Of course, one may think "just call `set_xscale("log")` on one of the axes and the others will follow, right?".  But switching to a single call `axs[0, 0].set_xscale("log")` end up as an even worse disaster; the scaling is not changed on the other axes but the tick markers are.

**Comment by tacaswell** [comment]
There are two indepnedent problems here

 1. the scale does not properly propagate.  This one is a bit upsetting, I suspect what is happening is that the `Axis` locator and formatter is getting updated (as they are the same objects) but the transforms on the axes are not as the `Axis` objects are _not_ shared.  I have a clean way to fix this (PR coming)

 2. the auto limit on shared axes only looks at the last axes (it probably _does_ look at all of them, just independently and sense the shared axis means the `Axis` object backing each of them is the same object the limits on the last axes it looks at wins.  As this works correctly with linear scales I suspect that the special case code for dealing with logs   This is annoying, but can be fixed by manually setting the limits.

**Comment by tacaswell** [comment]
Re opening this as #4709 only fixed one of two problems reported.

**Comment by afvincent** [comment]
@tacaswell @anntzer Is this issue still active? 

2edf1e3 seems to be the switching point between between some wrong behavior and something that looks OK to me:

* mwe with dc13688
![mwe_with_dc13688](https://user-images.githubusercontent.com/17270724/32256966-92a4ff2a-be6f-11e7-9e7e-dfc9ea861aa8.png)

* mwe with 2edf1e3
![mwe_with_2edf1e3](https://user-images.githubusercontent.com/17270724/32256963-903449a8-be6f-11e7-8ee4-7c5c7d68c5c5.png)

**Comment by anntzer** [comment]
Indeed, the issue is fixed now.
