### ISSUE TITLE
Error converting to_rgba while using `color` syntax versus `c` syntax

### ISSUE THREAD

**Issue by dhhagan** [matplotlib/matplotlib#4484]
If a third variable is used to color a scatter plot, a `ValueError` is thrown using the keyword `color` whereas no error is thrown if `c` is used instead.

Error:

    plt.scatter(xdata, ydata, color = colordata, cmap = colormap)

    ValueError: to_rgba: Invalid rgba arg XX
    to_rgb: Invalid rgb arg XX
    cannot convert argument to rgb sequence
   
No Error:

    plt.scatter(xdata, ydata, c = colordata, cmap = colormap)

**Comment by efiring** [comment]
I think this is a misunderstanding, not a bug.  There is no intention that keyword "color" be able to specify a set of values to be colormapped.  Is there something in the docs indicating otherwise?

**Comment by mwaskom** [comment]
`c` and `color` are pretty much interchangable almost anywhere else in matplotlib...

**Comment by efiring** [comment]
@mwascom,  I don't see this.  At least in a fairly quick scan, I see scads of variations on `color` (`colors`, `facecolor`, etc.) but `plot()` looks like the only place where there is a `c` alias for it.  I could be missing others.  In any case, the scatter documentation is clear and explicit on this point; and the `c` argument is not a full 'color-style' argument.  It is more like 'zdata', since it is used only for color-mapping.  It does not work with actual color specifications.

**Comment by WeatherGod** [comment]
We do "facecolor" == "fc", "edgecolor" == "ec".
