### ISSUE TITLE
linewidth antialiased=False image is not the same as matlab

### ISSUE THREAD

**Issue by orena1** [matplotlib/matplotlib#4523]
Hello,
I have a post here:
http://stackoverflow.com/questions/30828617/compare-differences-between-matlab-and-python-images-from-the-same-data

about the difference between matlab figure and matplotlib figure. It seems that I could not make the images the same, and it got to do with the linewidth can not be lower then 1 when antialiased=False

**Comment by tacaswell** [comment]
I do not think mpl has ever claimed to produce pixel-identical graphs to matlab (we do not guarantee pixel identical output between our backends). 

Looking at what is going on I suspect that the problem is matlab doing a bad job of rendering.  With anti-aliasing on the amount of color that gets added to a pixel during rasterization is proportional to how much of the line goes through that pixel.  With anti-aliasing off in mpl it looks like every pixel the line touches gets the full color.   If you want to make that line thinner, turn up the dpi (for screen set `figure.set_dpy` or `figure.dpi' in the rcparams).

With out knowing your data, I suspect that the 'features' you are seeing the the MATLAB figure are just rendering artifacts.

As a side note, I have been told that the newest version of matlab has caught up with mpl and uses anti-aliasing to draw lines.
