### ISSUE TITLE
The future of Idle event - (GTK warning on window close)

### ISSUE THREAD

**Issue by OceanWolf** [matplotlib/matplotlib#4534]
A brief history
----
* MPL's idle event gets used for performing events in the idle cycle for animation, see http://matplotlib.org/examples/event_handling/idle_and_timeout.html which gives an example of this
* This example however didn't work for GTK3 and #3769 fixed this but brought about the unintended side effect of #4092 whether or not one actually used it, because of this #3769 got reverted in #4533.
* Since the creation of idle event, we now have matplotlib.animation so we no longer need idle events for that task, but other uses may exist (@mdboom ?).

Current Status
----
So we now have warning messages back on GTK3 on close and the example not working again (no change from the stable release 1.4.x).

Several discussions got started in #4092 describing possible workarounds, but also whether we should scrap idle event altogether.  This issue serves to continue that now discussion now that the side effects stated in #4092 have been reverted and thus closed.

**Comment by ahaldane** [comment]
A few points in favor of simply removing it:

1) Idle event didn't even work in gtk: Before #3769 the idle_event callback was removed after the first callback and became nonfunctional.

2) qt and tk backends do not support it. In light of the fact that it was nonfunctional in gtk, this means the only backend that actually supported it is wx.

3) It looks like it has undergone an overhaul or two even in the wx backend: There is leftover cruft like the `IDLE_DELAY` global variable. I think this is because wx has significantly changed the way it sends idle events over the years.

I somewhat doubt anyone is using it. A github searches for "mpl_connect idle_event" only turns up lots of copies the the matplotlib example code using it, as far as I can see.

**Comment by OceanWolf** [comment]
I urge caution over a search on github, it just means that no large projects based on matplotlib use it, lots of users use matplotlib standalone and we have no idea of knowing how many people use it...

I think we could get rid of idle-event on gtk and other backends on which it doesn't work, perhaps leaving behind a simple 'deprecated this function does nothing and will get removed in 2.0', to cover users who have it in their code without realising.  Also we should add a deprecation warning to the backends that do work suggesting that they migrate to the animation module.
