### ISSUE TITLE
nbagg canvas size

### ISSUE THREAD

**Issue by feldman4** [matplotlib/matplotlib#4575]
Plots generated with `%matplotlib nbagg` are sized about 4X larger than they should be (there are no issues with `%matplotlib inline`). Creating a figure canvas with nbagg generates errors like 
`[IPKernelApp] ERROR | No such comm: 53faa31a655d4f14a36aeafd8d18541` 
on the notebook server, and 
`QPixmap::scaled: Pixmap is a null pixmap` 
if a qtconsole instance is connected from a remote computer.

The notebook server is running linux with IPython 3.2.0 and matplotlib 1.4.3 installed as part of an Anaconda distribution.

**Comment by tacaswell** [comment]
What do you mean by '4x what they should be'?

nbagg is not expected to work with qt console.

**Comment by feldman4** [comment]
The entire plot appears scaled up by a factor of 4 compared to inline. I render the plot from a notebook cell, but I noticed that if qtconsole is connected remotely the pixmap error pops up on stderr when the notebook cell executes.



________________________________

**Comment by tacaswell** [comment]
I suspect that there is a DPI issue as inline renders the pngs at very low
DPI.  Do you have any dpi related rcparam set?  Does
`fig.get_size_inches()` return the same thing in both cases?  Is this a mac
with a retnia display?

The qtconsole + notebook looking at the same kernel is something we need to
discuss with the IPython folks and probably provide a mixed (!?) backend
which lets the figure decide how to present it's self (probably by having
the *FigureCanvas objects have a shared Agg canvas).

Tom

**Comment by pelson** [comment]
> The qtconsole + notebook looking at the same kernel is something we need to
discuss with the IPython folks and probably provide a mixed (!?) backend.

Whoaaa - that doesn't sound like fun. I think I've opened up a can of worms by making a single figure displayed multiple times within the *same* backend - doing that across multiple backends could be a real headache.

**Comment by tacaswell** [comment]
The problem is that by design the kennels do not know what front end they
are talking to so what makes sense for a notebook does not make sense in
anything else.

Now that I type this out it is becoming more clear that to make this work
we will have to adopt their model and have GUI specific back ends that talk
to comms (or comm like things). I don't think that is too bad as we just
need to send json documents of events one way and binary blobs of the
raster data the other.

**Comment by OceanWolf** [comment]
Tagging myself as Comms feels MEP27 related.  What do you mean by "kernel", I presume not the Linux Kernel.

> I don't think that is too bad as we just need to send json documents of events one way and binary blobs of the raster data the other.

I thought we did this anyway... we do in ``WebAgg``, and in MEP27 I clear up that communication a great deal...

**Comment by WeatherGod** [comment]
@OceanWolf, he is referring to the Jupyter kernel (formerly the IPython
kernel). We do do comms interface for WebAgg and NbAgg, but not for the
backends like TkAgg and GtkAgg. That would be a huge undertaking, but it
would better align with the whole rework of the data object model and
serialization... probably should stay out of MEP27 for now, though.

**Comment by OceanWolf** [comment]
Okay, I have no idea of that.  Yes, I didn't mean to suggest we apply such comms for other backends (perhaps I will change my mind once I learn about this in ``NbAgg``), but I don't see any need to, we only need to do it for ``NbAgg`` because the backend lies inside of the iPython notebook so it forms part of the backend.

In terms of MEP27 I just referred to the communications we do via websockets in ``WebAgg``, right now I see that as similar functionality to what the Comms in ``NbAgg``, but again perhaps my idea of this will change when I come to refactor the ``NbAgg`` backend...

**Comment by petehuang** [comment]
What's the latest on this particular issue?

**Comment by dstansby** [comment]
Going to close since this is old and needs clarification - feel free to comment if it's still a problem!
