### ISSUE TITLE
Documentation - Basemap

### ISSUE THREAD

**Issue by chiragnagpal** [matplotlib/matplotlib#4706]
http://matplotlib.org/users/screenshots.html

Basemap demo say, "could not load basemap" Probably sphinx compiled on a machine without Basemap?

**Comment by tacaswell** [comment]
yup, that would be my fault, sorry about that!

**Comment by jenshnielsen** [comment]
This happens easily because https://github.com/matplotlib/matplotlib/blob/master/doc/pyplots/plotmap.py just fails silently when basemap is not installed. I vote for either removing the silent failure, replac that example with a static image or removing it al together. We are already linking to basemap from http://matplotlib.org/mpl_toolkits/index.html with a static image

**Comment by WeatherGod** [comment]
my vote is for a static image.

**Comment by tacaswell** [comment]
:+1: on static image

**Comment by mdboom** [comment]
Yes.  Disk space is much cheaper than mental bandwidth!

**Comment by jenshnielsen** [comment]
Fixed by #6243
