### ISSUE TITLE
That colorbar.set_ticks can take a locator is not documented sufficently

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#4748]
Should be an easy fix, just add the set_ methods and send them to the right axis.

**Comment by tacaswell** [comment]
This already exists, `cb.set_ticks` can take a locator as input.

There is badly documented in several ways.  The auto-generated docs are not getting inserted correctly (http://matplotlib.org/api/colorbar_api.html#matplotlib.colorbar.Colorbar) see https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colorbar.py#L99  and the code at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colorbar.py#L384

**Comment by pierre-haessig** [comment]
As a side issue, I just got hit by the fact that the `locator` attribute of a Colorbar is `None` when no locator is provided, although a default locator is generated internally (I found it in the [ColorbarBase._ticker](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/colorbar.py#L565) method).

This seems inconsistent with other plot functions, where the default locator is accessible (like `ax.xaxis.major.locator`). Should I file a separate issue or is this behavior intentional (since some other code may depend on `self.locator is None` tests). Or maybe it is just a matter of adding

```
self.locator = locator
```

at the end of this `ColorbarBase._ticker` method ?

**Comment by tacaswell** [comment]
@efiring is probably best positioned to answer colorbar questions.

**Comment by efiring** [comment]
@pierre-haessig: Adding `self.locator = locator` to the end of `_ticker` would have the undesired effect of freezing that choice of locator; when the original `None` default is given, the dynamic automatic selection should prevail.
What is the use case where you ran into trouble?  What did you want to do, that you found difficult or impossible?
I need to figure out whether the problem can be solved by improved documentation, or whether the API needs to be changed.
The colorbar is a rather special sort of object--it is not just another Axes--so there are limits to the degree to which trying to make it look like an ordinary Axes is beneficial.

**Comment by pierre-haessig** [comment]
Use case: I wanted to reduce the `nbins` param as I often do with Axes (but I guess mpl 2.0 has a better default...). 

Since the locator object being used is not accessible, I did:

```
cbar = fig.colorbar(im)
cbar.set_ticks(mpl.ticker.MaxNLocator(nbins=3, steps=[1, 2, 5, 10]))
```

which in effect recreates manually a new `AutoLocator` (as of mpl 1.5) with a smaller `nbins`.
It works well, but it slightly complicated.

@efiring : just to be sure I got your explanation. There situation where the type of locator might be changed multiple times after the creation of the colorbar?

In that case, there are maybe other ways to flag the "automatic" behavior. For example, would it be possible to assign a string `'auto'` (or `None`) to `self.ticks` instead of `None` to `self.locator` ?

**Comment by efiring** [comment]
On 2016/09/08 9:42 PM, Pierre Haessig wrote:
> Use case: I wanted to reduce the |nbins| param as I often do with Axes
> (but I guess mpl 2.0 has a better default...).

The MaxNLocator has an 'auto' mode now, and AutoLocator uses that, so 
for normal Axes the default often turns out looking better than before. 
When using MaxNLocator, however, colorbar is not using the auto mode. 
Probably it should.

>
> Since the locator object being used is not accessible, I did:
>
> |cbar = fig.colorbar(im) cbar.set_ticks(mpl.ticker.MaxNLocator(nbins=3,
> steps=[1, 2, 5, 10])) |

To me, this is a perfectly good solution.  Alternatively one can make 
the locator instance first and pass it in via the 'ticks' kwarg.

>
> which in effect recreates manually a new |AutoLocator| (as of mpl 1.5)
> with a smaller |nbins|.
> It works well, but it slightly complicated.
>
> @efiring <https://github.com/efiring> : just to be sure I got your
> explanation. There situation where the type of locator might be changed
> multiple times after the creation of the colorbar?

That's what I was thinking, but now I'm not sure.  Changing the attached 
mappable's norm would do it, but it looks like that is not being 
tracked--which is probably a bug in the on_mappable_changed method.

>
> In that case, there are maybe other ways to flag the "automatic"
> behavior. For example, would it be possible to assign a string |'auto'|
> (or |None|) to |self.ticks| instead of |None| to |self.locator| ?
>

Agreed, this can be done.

Regardless, I'm not convinced that providing access to the selected 
locator, which could be any of several types, is an improvement over the 
method of setting the locator explicitly when one wants a particular 
behavior.

Eric

**Comment by pierre-haessig** [comment]
Thanks @efiring for your feedback. As you said, colorbar should probably use the new 'auto' mode, so that people will probably have even less needs to override the default locator.

Now, coming back to the initial issue, there is indeed a small hole in the docstring. The `ticks` keyword for colorbar creation properly mentions the locator option, but not `set_ticks`.
