### ISSUE TITLE
Add API to register styles

### ISSUE THREAD

**Issue by astrojuanlu** [matplotlib/matplotlib#4781]
(This comes from [this SO question](http://stackoverflow.com/q/31559225/554319) by suggestion of @tacaswell)

I want to distribute a custom matplotlib style sheet, but right now the only way I can think of is uploading it to Gist or some other website and tell my users to manually download it to some configuration directory.

It would be nice to have a way to distribute a style sheet as if it were a Python package, or as part of a module. Something easy like `pip install mpl_fancy`. Something similar is already done with IPython extensions.

**Comment by tacaswell** [comment]
I think it is ok to add this for 2.0 as it is very closely related to visual style and the control there of.

attn @tonysyu Thoughts on the best way to do this?

**Comment by tonysyu** [comment]
The actual code for this would be fairly simple, but there are a couple of design decisions that might require a bit more thought:
- User interface (not necessarily graphical) for adding/installing styles
- Registry of styles (optional)

**User interface**
I don't think `pip install` is appropriate for stylesheets, but a similar CLI distributed with matplotlib would be fairly easy to write (e.g. something like `mplstyle install <url>`). This could just be an entry point distributed with matplotlib, so it's guaranteed to be installed. There are many other possibilities, though.

**Registry of styles**
Instead of `mplstyle install <url>`, for example, you could write `mplstyle install <style-name>` assuming that `<style-name>` was added to some agreed upon registry (similar to PyPI). In that case, we could even have `matplotlib.style.use` check the registry when no matching name is found locally. (The difference between distributed styles and those in the registry is that the later would be downloaded on-demand and registration wouldn't require PRs to the main codebase.)

The implementation could be as simple as a github repo containing style sheets. On the other hand, something more like PyPI (where PRs are not involved) might be desirable.

**Comment by Juanlu001** [comment]
I do not have a strong opinion against implementing `mplstyle install <url>`, but perhaps doing something simpler would help shipping this feature. For instance, when one wants to install the Read the Docs Sphinx theme, one does just

```
pip install sphinx_rtd_theme
```

and Sphinx takes care of the rest. Perhaps we can use a namespace in a similar fashion than `scikits` so the projects under `mplthemes`, when imported, would put the corresponding stylesheet under `$MPLCONFIG/styles` or whatever it is.

Another option would be to take advantage of setuptools entry points, which serve as a plugin system:

https://github.com/RichardBronosky/entrypoint_demo

although this might require some internal refactoring, and probably providing some cookiecutter, template or documentation for users to help them ship their own styles.

What do you think about these alternatives?

**Comment by Juanlu001** [comment]
And by the way, this was @tacaswell suggestion so it stays here:

> Currently you can reach into mpl.style.core, add a path to `USER_LIBRARY_PATHS` to point to your files and then re-run `mpl.style.core.reload_library()`

**Comment by anntzer** [comment]
I'm going to ambitiously claim that this is covered by #24257.  Feel free to ping for reopen if you disagree.
