### ISSUE TITLE
The following required packages can not be built: png

### ISSUE THREAD

**Issue by wlsherica** [matplotlib/matplotlib#4794]
I got error msg when I tried to install matplotlib on python 2.7, Centos 6, it said, "The following required packages can not be built: png".

Then I did $yum search libpng libpng-devel for libpng installation, however, it said "Package 2:libpng-1.2.49-1.el6_2.x86_64 already installed and latest version." 

Do anyone know how to fix this?

**Comment by tacaswell** [comment]
Install pkg-config as well.

**Comment by tacaswell** [comment]
@wlsherica Did installing pkg-config solve your build issues?

**Comment by wlsherica** [comment]
Problem solved!
Thank you so much.

**Comment by tacaswell** [comment]
Great, closing.

This is something that _should_ be in our docs.

**Comment by AbdealiJK** [comment]
This confused one of my users too. 
The error message that appears when the `png` package fails should mention this I think.
https://justpaste.it/v0if
At the bottom, it just says "The following required packages can not be built: freetype, png" and somewhere in between the huge dump, it says "IMPORTANT WARNING: pkg-config is not installed."

Can the important warning also be dumped at the bottom of the log ? As most users will look at that first

**Comment by goldyfz** [comment]
I am on RHELL 5.7, python 2.7.2, I have an old version of matplotlib 1.1 installed which doesn't work
[The error is  
>>>import sys
>>> sys.path.insert(0,"/<mypath>/3rd_party_libs/lib/python2.7/site-packages")
>>>import matplotlib (works!)
>>>import matplotlib.pyplot 
ImportError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by /depot/python/lib/python2.7/site-packages/matplotlib/_path.so)


I can't upgrade even though i have sudo access because the file system where it is installed is readonly, hence trying to install matplotlib 2.0 on my own path where I have full read/write access, which again gives below error

Hence trying to install the latest mpl 2.0
% pip list|grep mat
matplotlib (1.1.0)

 % rpm -qa | grep pkgconfig
pkgconfig-0.21-2.el5
 % rpm -qa | grep freetype
freetype-devel-2.2.1-32.el5_9.1
freetype-2.2.1-32.el5_9.1
freetype-2.2.1-32.el5_9.1
freetype-devel-2.2.1-32.el5_9.1
freetype-demos-2.2.1-32.el5_9.1
 % 

%sudo ./pip install --install-option="--prefix=/<mypath>/3rd_party_libs" --upgrade matplotlib
<snip>

============================================================================

                        * The following required packages can not be built:

                        * freetype

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/matplotlib
Storing complete log in /tmp/tmpccCScM


trying to install mpl 2.0 from source gives the exact same error too

Would like to make either the v1.1 work or much better if I can make the v2.0 work

P.S. Just joined github so feel free to point out posting and format guidelines (if any) :)
Thanks in advance!

**Comment by QuLogic** [comment]
> RHELL 5.7

I assume this typo was intentional. But also, why? RHEL5 is practically EOL in 6 days unless you buy the Extended Support, but why would anyone want to do that? I remember 5.4 felt ancient and that was about 7 years ago; I can't imagine what 5.7 must feel like at this point.

You have snipped too much from the log and it doesn't really appear related to this issue at all; please open a new issue with the full log.
