### ISSUE TITLE
Wrong coordinate transform on jupyter notebook (inline backend)

### ISSUE THREAD

**Issue by gabrielelanaro** [matplotlib/matplotlib#4865]
Hi, I've been trying to the example http://matplotlib.org/pyplots/annotate_transform.py in jupyter notebook (inline backend) as described in the transformation tutorial http://matplotlib.org/users/transforms_tutorial.html

However the picture I obtain is somehow shifted from the expected output:
![download](https://cloud.githubusercontent.com/assets/239875/9073233/cfb05ff4-3ab4-11e5-9cad-7584e0d99c4a.png)

Is this something you can reproduce? How can I fix that?
I'm using the matplotlib version just pulled from git

**Comment by tacaswell** [comment]
maybe related to https://github.com/matplotlib/matplotlib/issues/4375 ?

**Comment by gabrielelanaro** [comment]
I think this is definitely related even though I wasn't able to have it working in any way

**Comment by tacaswell** [comment]
The documentation does warn in the note that it might not work correctly in the interactive cases.

The reason is that the transformation from data space -> screen space depends on the dpi and figure size.  In this case the pixel location of the point is being computed.  IPython turns the dpi on the figures produced by inline way down, hence why you get the shift.

I think the behavior you are seeing is the correct and expected behavior.  You should do your best to avoid working in screen units.

**Comment by gabrielelanaro** [comment]
What I'm trying to do is connect points between two inset axes (similarly to #4375). I was wondering, if I run savefig, isn't that supposed to work properly? I still get a different offset.

**Comment by tacaswell** [comment]
The problem is still that you are computing the pixel to point to with one set of transforms and rendering the final figure (most likely either the figure size or dpi changed).  Unless you are super careful and/or re-compute the pixel location on every draw stay I strongly advise against using absolute pixels for anything.

As with #4375 the transforms on inset axes may not be initialized until after the first draw.  Attach the annotation to the inset axes with the highest zorder.

It would be helpful if you posted a minimal example demonstrating your problem.
