### ISSUE TITLE
Remove lena.jpg/png, it is undistributable and violating copyright

### ISSUE THREAD

**Issue by sandrotosi** [matplotlib/matplotlib#4927]
Hello,
Lenna images are not distributable and currently violanting the copyright of Playboy, some references:

https://en.wikipedia.org/wiki/Lenna
https://en.wikipedia.org/wiki/File:Lenna.png
https://lintian.debian.org/tags/license-problem-non-free-img-lenna.html
http://bugs.debian.org/794854

there is already https://github.com/matplotlib/matplotlib/commit/5da2608950866c9e821177b20b6cfadfd76d3b7a#diff-8f9a4136c7213fb5de70d2a382ed8fbf which is in public domain, please let's use that one and remove Lenna from the repo and the distributed tarball.

Regards,
Sandro

**Comment by WeatherGod** [comment]
If I remember correctly, Playboy and Lenna has granted rights to
redistribute the cropped image for non-profit image processing purposes.
This is a very old argument that was settled a long time ago.

**Comment by WeatherGod** [comment]
Quote from the wiki page:

"While *Playboy* often cracks down on illegal uses of its material and did
initially send out notices to research publications and journals that used
the image,[11] <https://en.wikipedia.org/wiki/Lenna#cite_note-Thompson-11>
over time it has decided to overlook the wide use of Lena. Eileen Kent, VP
of new media at *Playboy* said, "We decided we should exploit this, because
it is a phenomenon.""

**Comment by sandrotosi** [comment]
actually Playboy never did, they just ignore it (for the moment)

exactly "overlook" it doesnt mean anybody other than Playboy has any right to distribute that image

**Comment by jenshnielsen** [comment]
We have already removed al usage of it in #1581 so I am surprised that the image wasn't deleted from the repository at that point. I see absolutely no reason to keep it around.

**Comment by WeatherGod** [comment]
It was kept around at the time because it was an accessible sample image,
and thus needed to go through a deprecation cycle.

**Comment by WeatherGod** [comment]
Furthermore, this has been discussed on wikimedia with a decision that it
was fair-use: https://en.wikipedia.org/wiki/File:Lenna.png

**Comment by efiring** [comment]
Ben,
It evidently still causes more trouble than it is worth, so I merged the PR.
Case closed.
Eric

**Comment by WeatherGod** [comment]
This does raise a bigger question, though. I don't think we have any
copyright notices for *any* of the images.

**Comment by WeatherGod** [comment]
Just for the record, I take no position on whether the image is
"acceptable" or not for inclusion in mpl_data/. To me, it is just data. I
fully supported removing the image from documentation and examples. The
question that I am contesting here is one of whether its inclusion is a
violation of our BSD license:

estoppel precludes "a person from denying, or asserting anything to the
contrary of, that which has, in contemplation of law, been established as
the truth, either by the acts of judicial or legislative officers, or by
his own deed, acts, or representations, either express *or implied*"
(emphasis mine).

So, I seriously doubt there is any real licensing/copyright issues at play
here. Contrast this with our official position on MathWork's perula
colormap, which they have expressly stated that they did not want it
redistributed in any other plotting packages. All that being said, I will
not push for a deprecation cycle for the Lenna image since it was de-facto
deprecated by virtue of it no longer being included in our documentation
and examples.

I did just take a quick peek at our source tree for any licensing for
anything in mpl-data/sample_data. I could find none. Even the Grace Hopper
image needs to have a copyright notice. I'll open a new issue on this
regard, as it is important.

**Comment by tacaswell** [comment]
I am :+1: on the outcome of this.  The image should go anyway and it is not worth the effort to argue with Debian about it.  They have also hit scikit-image with a similar request.

It probably does require a note in API changes though.
