### ISSUE TITLE
axis('equal') in mplot3d plots causes duplicate z axis in the nbagg backend 

### ISSUE THREAD

**Issue by jenshnielsen** [matplotlib/matplotlib#4971]
This is on current master I can't reproduce this using 1.4.3. I guess it relates to the stale auto redraw handling? 

```
from mpl_toolkits.mplot3d import Axes3D


fig = plt.figure(figsize=(6.5,5.5))
ax = fig.add_subplot(1, 1, 1, projection='3d')
xs = np.random.rand(10)
ys = np.random.rand(10)
zs = np.random.rand(10)
ax.set_aspect('equal')

ax.scatter(xs, ys, zs)
ax.set_xlim(0,1)
ax.set_ylim(0,1)
ax.set_zlim(0,1)
fig.tight_layout()
```
results in

![download 2](https://cloud.githubusercontent.com/assets/548266/9378877/db5c894e-471c-11e5-89e4-b7d1611c3f53.png)

Rotating the figure restores the correct axes.  I can't reproduce it with QT5Agg or GTK3Agg

It seems like both the equal axis z and the original z axis are drawn on top of each other. It doesn't seem to happen in regular 2D plots.

**Comment by tacaswell** [comment]
What backends does this happen on?

**Comment by jenshnielsen** [comment]
nbagg  (Bug title ;) 

I can't reproduce it with any of the GUI Backends that I have tried.

**Comment by tacaswell** [comment]
Ha!  Sorry I can't read.

nbagg has two canvas instances that it swaps between (so that in can compute the diffs).  I bet there is something sutble going on with draw order/it's draw_idle not being good enough at snarfing duplicate draws.

I am thinking of putting the non-propagation of stale state past an already stale artist back in.  Always propagating prevents a corner case annoyance in vanilla python repl where an error in drawing prevents auto-draw from working on that figure until it is manually kicked (via `plt.draw_all()` or `fig.canvas.draw()` or `plt.draw()` if it is the active figure) but is introducing all sorts of re-entrant issues with backends that don't fully implement draw_idle correctly.

attn @mdehoon

**Comment by mdehoon** [comment]
@tacaswell  Which backend does not implement draw_idle correctly?

**Comment by mdehoon** [comment]
I am seeing this bug also with the MacOSX backend and the tkagg backend; I haven't tried the other backends.

**Comment by tacaswell** [comment]
Having issues with Qt, but I think those are sorted.  I am not sure about nbagg.

**Comment by WeatherGod** [comment]
Just curious... what is special about mplot3d that would trigger this
problem? mplot3d doesn't mess around with draw/draw_idle, and it doesn't do
blitting or anything of that sort. The only thing I can think of is that it
performs a lot of extra computation at each artist draw(), but that's all.

**Comment by jenshnielsen** [comment]
It's totally possible that this can be triggered without mplot3d. That's just where I happened to spot it. I can't reproduce it with a regular scatter plot but there might be some other way.

**Comment by mdehoon** [comment]
@tacaswell  OK. If you notice any other implementation problems with draw_idle in any of the backends, I'd be happy to have a look.

**Comment by tacaswell** [comment]
The issue seems to be that the z-axis is in the draw tree twice, once before things get updated and once after.  It look mostly ok most of the time because they are getting over-drawn on top of each other.

**Comment by WeatherGod** [comment]
A possible clue on that... the ZAxis is basically implemented as a XAxis
subclass rather than creating a whole new class like YAxis. There are
several spots in the codebase where the z-axis basically "steals" from the
x-axis, but I really don't know how it would end up putting itself into the
draw-tree twice.
