### ISSUE TITLE
Contourf Colorbar

### ISSUE THREAD

**Issue by lkilcher** [matplotlib/matplotlib#5055]
The `contourf` `colorbar` doesn't work as expected.

The following code:

    import matplotlib.pyplot as plt
    import numpy as np
    import matplotlib.colors as mplc

    x, y = np.mgrid[0:1:0.01, 0:1:0.01]
    r = np.sqrt(x ** 2 + y ** 2)
    z = np.sin(6 * np.pi * r)

    norm = mplc.Normalize(0, 0.5)
    fig0, ax0 = plt.subplots(1, 1, )
    cf0 = ax0.contourf(x, y, z, np.arange(-1., 1.001, .01), norm=norm)
    cbar0 = plt.colorbar(cf0,)

Produces the following figure:

![conf](https://cloud.githubusercontent.com/assets/2273361/9838321/a8fc2dd4-5a17-11e5-8520-6889bf681e0f.png)

Compare this with the colorbar of, e.g. a `pcolormesh`:

    fig2, ax2 = plt.subplots(1, 1)
    pc2 = ax2.pcolormesh(x, y, z, norm=norm)
    cbar2 = plt.colorbar(pc2)

![pcol](https://cloud.githubusercontent.com/assets/2273361/9838327/00bdc320-5a18-11e5-8148-e0844ab96637.png)

That's a nice colorbar, and it's what I expect the default behavior to be for `contourf` also. Is there a reason the `contourf` colorbar behaves this way? I've looked at using the `vmin`,`vmax` args, and the result is the same. Also, the result is the same for `tricontourf` colorbars as well.

**Comment by lkilcher** [comment]
I've already worked a little bit on creating a fix for this [here](https://github.com/lkilcher/matplotlib/commit/8ad6f0e32cd2144bc44554fd94dd31a14a3c436a). The issue seems to be related to trying to handle creation of `colorbar` `contour` lines (not `contourf`), but I have no idea if this fix causes other issues.

**Comment by tacaswell** [comment]
That color bar does look "correct". You asked `countourf` to make contours from [-1, 1] so the color bar covers that range.  Outside of [0, .5] the color maps to the limits of the colormap as you asked it to.

attn @efiring

**Comment by tacaswell** [comment]
If you do 

```python
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.colors as mplc

x, y = np.mgrid[0:1:0.01, 0:1:0.01]
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(6 * np.pi * r)

norm = mplc.Normalize(0, 0.5)
fig0, ax0 = plt.subplots(1, 1, )
cf0 = ax0.contourf(x, y, z, np.arange(0, .5, .01), norm=norm,
                   extend='both', cmap='viridis')
cbar0 = plt.colorbar(cf0,)

```

you get 
![so](https://cloud.githubusercontent.com/assets/199813/9838459/30a9890c-5a2c-11e5-92de-374fb2ec8b97.png)

which is what I _think_ your intent wast.

**Comment by lkilcher** [comment]
Got it. I was unaware of the `extend` kwarg. Thanks and sorry. I was starting to think there is a need for a `cbar.set_lim` method, but I suppose this kind of functionality removes any need for it (i.e. one should always control the color limits via the mappable, rather than the cbar itself). Is that correct?

**Comment by tacaswell** [comment]
I could have sworn there _was_ a `cbar.set_lim` method as I remember using it in the past, but I could not find it (which either means my memory is bad or we have that functionality someplace really strange).   I suspect that what you say is true (that you should control the color bar limits through the mappable object), but defer that question to @efiring .

This is something where there are multiple places where it might make sense to be able to control it, we may not always be consistent on where it should be controlled, there is a high degree of 'do the right thing' required, and we can't break back compatibility. 

I am only aware of the `extend` kwarg because there was another bug report related to it last week :wink: .  I have a patch on the way that will make the extend on the color bar a bit more controllable.  

Where would you have looked in the docs to try and find out this sort of stuff?

**Comment by lkilcher** [comment]
Looking more closely I see that it's in the `contourf_demo.py`, but it's not highlighted as prominently as I'd think. Is it worth creating a Q+A on SO about how to do this (I don't see one that uses `extend`), or is this issue good enough?

**Comment by tacaswell** [comment]
I am indifferent to creating on SO post on this.

**Comment by AnkitBarik** [comment]
The 'extend' keyword gives a line instead of a colorbar.
Matplotlib version: 2.0.0rc2+2827.gab98852
Numpy version: 1.13.0.dev0+2498b74
Compiler: gcc

Here's the same piece of code generating the following

`import matplotlib.pyplot as plt
import numpy as np
import matplotlib.colors as mplc

x, y = np.mgrid[0:1:0.01, 0:1:0.01]
r = np.sqrt(x ** 2 + y ** 2)
z = np.sin(6 * np.pi * r)

norm = mplc.Normalize(0, 0.5)
fig0, ax0 = plt.subplots(1, 1, )
cf0 = ax0.contourf(x, y, z, np.arange(0, .5, .01), norm=norm,
                   extend='both', cmap='viridis')
cbar0 = plt.colorbar(cf0,)`

![figure_1](https://cloud.githubusercontent.com/assets/13730345/21478977/36db3784-cb51-11e6-9ee3-446fd3e19e9a.png)

**Comment by WeatherGod** [comment]
Does the problem still happen if you remove the comma in the colorbar()
call?

Also, next time, please file a new issue rather than resurrecting an old
issue, unless the problem is identical.

**Comment by efiring** [comment]
The comment above refers to what has now been opened as #7686.
