### ISSUE TITLE
axes.properties calls get_axes internally

### ISSUE THREAD

**Issue by TomAugspurger** [matplotlib/matplotlib#5089]
This results in a un-fixable warning

```python
In [2]: import matplotlib.pyplot as plt

In [3]: fig, ax = plt.subplots()

In [4]: ax.properties()
/Users/tom.augspurger/Envs/dev/lib/python3.4/site-packages/matplotlib-1.5.0rc1+0.gab00a04.dirty-py3.4-macosx-10.10-x86_64.egg/matplotlib/artist.py:221: MatplotlibDeprecationWarning: This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set.
  warnings.warn(_get_axes_msg, mplDeprecation, stacklevel=1)
```
The root cause is a call to `ax.get_axes()`.

This is on the RC by the way, and probably is from https://github.com/matplotlib/matplotlib/pull/4686

**Comment by WeatherGod** [comment]
ooh boy... yeah... This is harmless, but annoying. And can be an issue in
the future.

When calling `properties()` for an artist, it will `dir()` the object
itself, and find any "get_*" methods that are callable. It tosses any
aliases, and builds up a dictionary of results from calling all of those
getters. Therefore, it also picks up the `get_axes()` method, thereby
incurring the warning.

If we are deprecating `get_axes()`, then that means we are changing the
output of `properties()`. We should probably modify this method so that we
filter out deprecated "get_*" methods, and fetch them via their respective
property instead, I think.

Thoughts?

**Comment by tacaswell** [comment]
@WeatherGod Sounds right to me.   I remember doing this in some functions, may `setp` and `getp`?

**Comment by josePhoenix** [comment]
Just came across this warning myself and found this issue, +1 to the proposed solution

**Comment by tacaswell** [comment]
The first thing that feel through the cracks for 1.5.0

**Comment by TomAugspurger** [comment]
Not the worst issue to miss!

For people looking for a workaround.

```python
In [1]: from matplotlib.cbook import MatplotlibDeprecationWarning

In [2]: import warnings

In [3]: fig, ax = plt.subplots()

In [4]: warnings.simplefilter('ignore', MatplotlibDeprecationWarning)

In [5]: _ = ax.properties()
```

*cavet emptor* and all that, you could be silencing important warnings.
