### ISSUE TITLE
shifted(?) bin positions when plotting multiple histograms at the same time

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5212]
Consider
```
import numpy as np
from matplotlib import pyplot as plt

mu, sigma = 1500, 100
x = mu + sigma * np.random.randn(1000, 3)

_, (ax1, ax2) = plt.subplots(2)
ax1.hist(x[:, 0], 30, range=(0, 3000), width=100)
ax1.hist(x[:, 1], 30, range=(0, 3000), width=100)
ax1.hist(x[:, 2], 30, range=(0, 3000), width=100)
ax2.hist(x, 30, range=(0, 3000), width=100)
plt.show()
```
![hist](https://cloud.githubusercontent.com/assets/1322974/10372702/08ccc20c-6d9e-11e5-98a9-d9cfa9c52135.png)

**Comment by tacaswell** [comment]
This is nominally a feature, if you make the bars narrower they will line up in groups of 3 per bin.

**Comment by anntzer** [comment]
Perhaps some sort of warning when `width` is explicitly set then?  (It seems more appropriate to use `rwidth` in that case).

**Comment by tacaswell** [comment]
It looks like `width` is only doing something because it is falling through to the `update` call at the bottom of `hist` ( [`width` is not explicitly documented](http://matplotlib.org/api/axes_api.html) and not really _implicitly_ documented either as the kwargs point to `patch` properties and `width` is a `Rectangle` property).

If you don't pass `width`, it 'does the right thing':

```python
import numpy as np
from matplotlib import pyplot as plt

mu, sigma = 1500, 100
x = mu + sigma * np.random.randn(1000, 3)

_, (ax1, ax2) = plt.subplots(2)
ax1.hist(x[:, 0], 30, range=(0, 3000))
ax1.hist(x[:, 1], 30, range=(0, 3000))
ax1.hist(x[:, 2], 30, range=(0, 3000))
ax2.hist(x, 30, range=(0, 3000))
plt.show()
```

![so](https://cloud.githubusercontent.com/assets/199813/10376200/95cfc718-6dca-11e5-9a03-296e17143c9a.png)

Explicitly passing `width` in over-determines several things (like if you change bins or range, you can now pass in a `width` which is wrong).
