### ISSUE TITLE
Notebook backend: possible to remove javascript/html when figure is closed?

### ISSUE THREAD

**Issue by jorisvandenbossche** [matplotlib/matplotlib#5219]
Using the notebook backend with `%matplotlib notebook` stores several outputs in the ipynb file: both javascript code and a png figure embedded in a html data object. 
When you close a figure in the notebook, the interactive figure is replaced by a static image, and then seems to the user similar as to using `%matplotlib inline` (apart from the default resolution). But, in the notebook file itself, it still is a javascript + html output and not a png image as with the inline backend.

I was wondering if it would be possible/desirable to also have the data that is stored in the notebook file be converted to a 'real' image ("image/png") when the figure is closed. 
This question comes from two drawbacks I noticed with the current situation when using `%matplotlib notebook`:

- The javascript 'clutters' the notebook file: the notebook format is already not friendly to diffs, but this makes it even more difficult (the javascript takes a lot of lines, while the image itself is only 1 line). Once, the figure is closed, I don't think the javascript is still useful?
- Figures that are created with the notebook backend will not be visible for untrusted notebooks (so eg every notebook that you get from somebody else has first be trusted before you can see the figures in the notebook)

Note: I am not familiar with the backend stuff and the ipython comms, so I don't know this is even possible.

**Comment by tacaswell** [comment]
The logic of replacing interactive figure with a static figure happens [here](https://github.com/tacaswell/matplotlib/blob/master/lib/matplotlib/backends/web_backend/nbagg_mpl.js#L57).

It looks like that is only touching the DOM on the browser side so I am not really clear how that get reflected back to the IPython notebook side.

Some of this may get better when we replace nbagg with something based directly in IPython widgets, rather than injecting our own divs.

attn @pelson @blink1073
