### ISSUE TITLE
Link to PyPI, rather than SourceForge, for direct download links

### ISSUE THREAD

**Issue by mdboom** [matplotlib/matplotlib#5227]
Now that PyPI meets our needs wrt filesizes, we should also stop sending people to SF through the [downloads page on matplotlib.org](http://matplotlib.org/downloads.html).  That page has some pretty hairy code just to keep it updated that I'd like to drop.  I think, instead, we should just link to PyPI's pages like this, maybe for the latest bugfix releases of the past two major releases:

https://pypi.python.org/pypi/matplotlib/1.4.3

It's not a super pretty page, but it does list all of the download options without any additional work from our end.

This is an easy enough fix, just want feedback before implementing.  @tacaswell, @efiring

**Comment by tacaswell** [comment]
:+1:

**Comment by tacaswell** [comment]
the code to reach out to SF to rebuild that page is one of the more annoying bits of doing a release.

**Comment by efiring** [comment]
OK, but it is unfortunate that the pypi page doesn't at least sort the downloads by platform.
On our front page, instead of a bare link to the pypi page, it might be good to start with a brief note about installation methods and a link to http://matplotlib.org/devdocs/users/installing.html?highlight=installing for more info.  I think we should not make the pypi page too prominent, because as I see it, it should rarely be the place for prospective users to go.

**Comment by mdboom** [comment]
@efiring: I agree 100%.
