### ISSUE TITLE
Default changes: legend

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#5269]
I actually think  that the current defaults for legend too spacious. Reducing the fontsize, spacing and padding is what i am thinking of. The current setting is only usable if one only has one or two items, and even then i think the legend is to big. Also the location should default to 'best'.

**Comment by mdboom** [comment]
Thanks.  We'll take this all into consideration as we change defaults for 2.0

**Comment by lstagner** [comment]
May I also suggest defaulting to `frameon=False`. I often feel the frame adds unnecessary information to the plot.

**Comment by efiring** [comment]
I'm inclined to agree with the suggestions here.  I often have to reduce the legend size.  Leaving the frame out by default would fit in with the idea of minimizing inessential elements.
I'm not sure whether this issue was simply dropped by accident, or whether a decision was made not to act on it--I'm guessing it was the former.  But maybe not; there were some changes to legend (default location is now 'best', and the box is fancy).  @Tillsten, what default values would you suggest?

**Comment by tacaswell** [comment]
This just fell off the radar.

**Comment by efiring** [comment]
To elaborate, the `legend.fontsize` is 'large' while the `axes.labelsize` is 'medium'--that definitely accounts for some of the sense of imbalance!

**Comment by efiring** [comment]
Closed by #6424.
