### ISSUE TITLE
Proper way of setting the current image for a specific axes

### ISSUE THREAD

**Issue by MaxNoe** [matplotlib/matplotlib#5394]
The `ax._sci()` method is private, `plt.sci()` does not work if the artist is not on the current axis. 

Is there a special reason,  why the axes method is private? What is the correct way to do it? 

See https://github.com/cta-observatory/ctapipe/issues/28 and https://github.com/cta-observatory/ctapipe/pull/30

**Comment by WeatherGod** [comment]
There have been previous discussions about `plt.sci()` (and `plt.sca()`), and I think it was a mistake to add them to the pyplot public API. The whole notion of `gca` and `gcf` came from MATLAB, and even they don't have `sca`. Their own documentation for `gca` and states "User interaction can change the current axes. If you need to access a specific axes, store the axes handle in your program code when you create the axes and use this handle instead of gca."

The bug you are seeing is exactly why the entire sca/sci concept is a flawed design in the first place, and it paints other libraries like yourselves into a corner.

I'll take a deeper look into your particular bug and suggest a better approach. I would certainly discourage from using `ax._sci()` or `plt.sci()`. While I have no plans to axe them, there are a number of other core devs who are licking their chops for the opportunity to rid themselves of the pyplot interface altogether.

**Comment by MaxNoe** [comment]
Ok, thanks a lot for the information.

The idea was to make `plt.colorbar()` work for the plot.

**Comment by jenshnielsen** [comment]
You can always pass the image as mappable to `colorbar()`

I normally prefer using the object oriented interface as much as possible i.e. something like.

```
import matplotlib.pyplot as plt
import numpy as np
a = np.random.rand(100, 100)
fig,ax = plt.subplots(1,1)
im = ax.imshow(a, interpolation='none', cmap=plt.cm.viridis)
fig.colorbar(im)
```
Which image you want to generate a colorbar from and does not rely on any notion of a current image.

**Comment by QuLogic** [comment]
Downstream appears to have solved this with the OO API, and I don't think there's much appetite for adding much more global state API.
