### ISSUE TITLE
fill_between wrong edge line color

### ISSUE THREAD

**Issue by tritemio** [matplotlib/matplotlib#5423]
On python 3.4 and matplotlib 1.5 I get different results on different runs. Sometimes the color of the edge is wrong, other times is correct. The code to reproduce the issue is:

```
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

plt.fill_between(np.arange(200), np.random.randn(200), 
                 color='r', edgecolor='k', linewidth=2)
```

Sometimes gives the right result:
![mpl_right](https://cloud.githubusercontent.com/assets/4156237/11005703/4315b58a-8474-11e5-90a5-269a0824436e.png)

and sometimes the wrong one:

![mpl_wrong](https://cloud.githubusercontent.com/assets/4156237/11005710/4e173ecc-8474-11e5-9f29-198324bfe428.png)

It usually requires restarting the interpreter to trigger the switch between right and wrong, but I have sometimes seen the switch just inverting the `color` and `edgecolor` keywords.

This is probably an old bug affecting also seaborn violinplot (https://github.com/mwaskom/seaborn/issues/678) which is based on `fill_between[x]` functions. It may be also related to https://github.com/matplotlib/matplotlib/issues/4083.

Tested on Windows x64, Anaconda distribution, python 3.4 and matplotlib 1.5 from Christoph Gohlke's [matplotlib wheel](http://www.lfd.uci.edu/~gohlke/pythonlibs/).

**Comment by tacaswell** [comment]
This is due to the order of dictionaries being randomized between python processes, #4083 is definitely the right analogy.

As a work around 

```python
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

art = plt.fill_between(np.arange(200), np.random.randn(200), 
                 color='r', edgecolor='k', linewidth=2)

art.set_edgecolor('k')
```

will always work.

**Comment by tacaswell** [comment]
Also, you should checkout `%matplotlib notebook` in 1.5, we fixed a number of the issues you reported against 1.4.

**Comment by WeatherGod** [comment]
I think I might have a clue what is happening. The confusion is with what
does "color" refer to. As I have noted in my property-cycling work, some
artists treats color as overriding edgecolor, while other artists have
edgecolor overriding color. This is made more complicated by the fact that
in functions like bar() and fill_between(), color really means facecolor,
and the name "color" gets elided to "facecolor" in the argument-handling
deep in the bowels of the codebase.

I bet I missed some possible codepath somewhere when I was doing the
property-cycling work. I would be curious if the same problem happens for
plt.bar().

Could you try specifying `facecolor='r'` instead of `color='r'` and see if
the problem goes away?

**Comment by tritemio** [comment]
Trying only a dozen of times the problem does not show up with `facecolor='r'`.

**Comment by tacaswell** [comment]
If this was not fixed previously, this is definitely fixed by https://github.com/matplotlib/matplotlib/pull/7173
