### ISSUE TITLE
Matplotlib 1.4.3 broken on Windows

### ISSUE THREAD

**Issue by rddaz2013** [matplotlib/matplotlib#5431]
https://github.com/conda/conda/issues/1753

Pls look into it, perhaps you can help with the _png import error.

  File "C:\Anaconda3\lib\site-packages\matplotlib\mathtext.py", line 63, in <module>
    import matplotlib._png as _png
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.

**Comment by tacaswell** [comment]
`_png` is one of the complied c extensions which links to `libpng`.  The problem here is probably that the version of libpng that your `_png` extension is built against is no longer available.  This is 100% a packaging problem on binaries that we do not maintain.  The linked conda issue or a new one is the correct place to take this up.

**Comment by rddaz2013** [comment]
It's because why using libpng if matplotlib is using Pil/Pillow?

**Comment by mdboom** [comment]
matplotlib also uses libpng directly because it needs lower-level control of libpng than Pillow provides.
