### ISSUE TITLE
Incomplete dependency list for installation from source

### ISSUE THREAD

**Issue by khinsen** [matplotlib/matplotlib#5449]
The list of required dependencies in the [installation instructions](http://matplotlib.org/users/installing.html) is incomplete. One dependency, [setuptools](http://pypi.python.org/pypi/setuptools), is missing completely. For a few others, no links are supplied. Here is a complete list with links:

 - [zlib](http://www.zlib.net/) (an indirect dependency through setuptools)
 - [Python](http://www.python.org/)
 - [numpy](http://www.numpy.org/)
 - [setuptools](http://pypi.python.org/pypi/setuptools)
 - [six](http://pypi.python.org/pypi/six)
 - [cycler](http://pypi.python.org/pypi/Cycler)
 - [pyparsing](http://pypi.python.org/pypi/pyparsing)
 - [python-dateutil](http://pypi.python.org/pypi/python-dateutil)
 - [pytz](http://pypi.python.org/pypi/pytz)
 - [libpng](http://www.libpng.org/pub/png/libpng.html)

**Comment by mdboom** [comment]
I don't think we should be in the business of listing indirect dependencies.  Where does one stop?  There's just too many variables there.

As of matplotlib 1.5, six is shipped with matplotlib.

So that leaves just setuptools.  We plan to start recommending installation through pip (which requires setuptools) in #5428, so that will likely take care of that one.

**Comment by khinsen** [comment]
@mdboom I should have added a link to the [story behind this issue](http://blog.khinsen.net/posts/2015/11/06/a-rant-about-software-deployment-in-2015/): the difficulty of installing matplotlib in an environment where `pip` is not an option (lack of network connection). I therefore hope that matplotlib will continue to support installation from tarballs, with appropriate documentation. This issue is about improving that documentation.

As for the indirect dependencies, I agree in principle, but given that (1) there is exactly one such indirect dependency and (2) it is a particularly nasty one because it needs to be installed before Python itself, I think it is helpful for users to mention it.

**Comment by jenshnielsen** [comment]
It makes sense to update the docs with all dependencies but the install from source instructions see less and less use as more and more users are installing using a package manager (pip, conda or something else)

The point of using pip is that you can use pip it install from a tar ball with `pip install .` rather than `python setup.py install` which provides a much better installation experience including working uninstall and pip rather than easy install of missing dependencies which solves a bunch of other issues.

**Comment by mdboom** [comment]
I'll reassure you that matplotlib will continue to support installation from tarballs.  We even have no plans to make `setup.py install` to stop working.  But `pip` will give a better experience, even without the network downloading functionality.

As for indirect dependencies, I'm still not sold on that.  If we list all the direct dependencies, installing those dependencies (which one has to do first) will reveal the indirect ones... indirectly.

**Comment by jenshnielsen** [comment]
I guess it is ok to note that python needs to be build with zlib support. Im not sure how much that helps thou

**Comment by tacaswell** [comment]
:-1: on indirect dependencies.  The dependencies page does note that we vendor `six` as well.

Agree `cycler` should be better linked.

**Comment by jenshnielsen** [comment]
It would be nice to get this documentation only thing fixed for 1.5 too

**Comment by jenshnielsen** [comment]
Closed by #5818
