### ISSUE TITLE
Feature request: allow a default line alpha to be set in mpl.rcParams

### ISSUE THREAD

**Issue by evandhall** [matplotlib/matplotlib#5461]
Currently, one can set default line properties like color, marker style, line width, etc. with `mpl.rcParams`. However, the ability to set a default line alpha seems to be missing. It would be great to have `'lines.alpha'` as a key in the `rcParams` dict, similar to `'lines.color'`, `'lines.marker'`, etc.

**Comment by mdboom** [comment]
You can choose a color that includes alpha, i.e. #ffffff88.

**Comment by evandhall** [comment]
Thanks, I also see this is a duplicate of issue #5132.

**Comment by WeatherGod** [comment]
@mdboom, the hex colorspec does not support the optional alpha channel. It
is an open feature request to add such support. If the support is there
deep in the colors.py code and I did not see it, then the validator needs
to be updated.

**Comment by mdboom** [comment]
Ok -- sorry for creating confusion.  If it isn't supported, I think it should be.  I think separating color from alpha has been a long term mistake.  To the extent that we're cleaning up color usage and specification, I think we should encourage more use of RGBA.

**Comment by anntzer** [comment]
This issue also makes #6196 (Qt editor drops alpha) difficult to solve.  I am willing to tackle this but would also like to take advantage of this to deprecate some old stuff (because there's going to be some API breakage anyways).

I think the public color conversion API should be something like:
- `is_color_like` (any -> bool),
- `to_hex` (3-tuple -> #rrggbb, 4-tuple or other color-like -> #rrggbbaa),
- `to_rgba` (any -> 4-tuple),
- `to_rgba_array`
(module-level functions)

and drop out `rgb2hex`, `hex2color` (both are confusing in the presence of alpha) and the whole colorConverter class (by the way I haven't managed to make the "Cn" syntax work but it looks like caching on that class would lead to issues if someone changes the rcParams in between?).

**Comment by tacaswell** [comment]
It is not obvious to me that this requires breaking any API or removing any functionality.

We need to keep the rgb only version around because some backends (ps) do not support alpha.

**Comment by anntzer** [comment]
I think this and #5132 should be closed by #6382.

**Comment by WeatherGod** [comment]
closed via #6382
