### ISSUE TITLE
BUG: legend.get_frame() should throw an error, return None, or show a warning if frameon was False

### ISSUE THREAD

**Issue by musically-ut** [matplotlib/matplotlib#5472]
Currently, it returns a frame. Doing operations on that frame has no effect on the legend being displayed on the screen and [causes much grief](http://stackoverflow.com/questions/30729473/seaborn-legend-with-background-color?lq=1).

The fix will involve touching [these lines](https://github.com/matplotlib/matplotlib/blob/5ac32f3ad0f3464c4e996cb723dec0351d76d7ce/lib/matplotlib/legend.py#L778) and making sure that all the calls to `self.get_frame()` present inside execute.

This can be done by first including a deprecation warning and then dropping support over two releases to catch corner issues and maintain some measure of backwards compatibility.

**Comment by tacaswell** [comment]
A better fix would be to use the `visible` attribute of the `_legendPatch` to control if it is drawn instead of an attribute in the `Legend` class, that way the artist you get back form `get_frame` will give `leg.get_frame().get_visible() is False`

Raising or returning `None` on this seems like an API change that would cause many _other_ kinds of havoc.

**Comment by musically-ut** [comment]
If I understand you correctly, then you are suggesting:

  1. Removal/deprecation of the attribute `self._drawFrame`
  2. The value of `frameon` (or `rcParams['legend.farmeon']`) will set/unset the `visible` attribute of the underlying `_legendPatch`?

That does sound like a better fix.
