### ISSUE TITLE
annotate doesn't trigger redraw

### ISSUE THREAD

**Issue by mdehoon** [matplotlib/matplotlib#5476]
Using this example:
```python
import matplotlib
matplotlib.use("tkagg")
import matplotlib.pyplot as plt
plt.subplot(1,1,1)
plt.annotate("hello", xy=(0.5,0.5))
```
in interactive mode, does not trigger a redraw, and the text is not drawn. After resizing the figure or plotting something else, the text appears. This is with matplotlib 1.5.0.

**Comment by tacaswell** [comment]
The problem is that for all of the other artists they get added to the `Axes` object through a `add_*` method which does a bunch of boiler plate / state management, for `annotate` (and `plt.text`) the `Axes` methods just append attributes to `self.text` which is not instrumented to flip the stale flag.

I will have a patch for this tonight.
