### ISSUE TITLE
Contouring decreasing levels

### ISSUE THREAD

**Issue by ianthomas23** [matplotlib/matplotlib#5477]
This is a bug in the contouring code, as reported on matplotlib-devel under the title 'Use of contourf changed?'  Actually it is a choice of bugs, depending on your perspective.  I've condensed the problem and explanation of what is going on into the following example code

```
import numpy as np
import matplotlib.pyplot as plt

n = 30
x, y = np.meshgrid(np.linspace(-1, 1, n), np.linspace(-1, 1, n))
data = np.exp(-6*x*x)*np.exp(-6*y*y)

decr_levels = [0.9, 0.5, 0.1, 0.0]
incr_levels = list(reversed(decr_levels))
colors = ['b', 'b', 'b']

plt.subplot(3, 2, 1)
plt.contourf(data, levels=decr_levels, corner_mask='legacy', alpha=0.25, colors=colors)
plt.title("corner_mask='legacy', decreasing levels")

plt.subplot(3, 2, 2)
plt.contourf(data, levels=decr_levels, corner_mask=True, alpha=0.25, colors=colors)
plt.title('corner_mask=True, decreasing levels')

plt.subplot(3, 2, 3)
plt.contourf(data, levels=incr_levels, corner_mask='legacy', alpha=0.25, colors=colors)
plt.title("corner_mask='legacy', increasing levels")

plt.subplot(3, 2, 4)
plt.contourf(data, levels=incr_levels, corner_mask=True, alpha=0.25, colors=colors)
plt.title('corner_mask=True, increasing levels')

plt.subplot(3, 2, 5)
plt.contourf(data)
plt.title('defaults')

plt.subplot(3, 2, 6)
for level in decr_levels[:-1]:  # Ignore lowest level.
    plt.contourf(data, levels=[level, np.inf], corner_mask='legacy', alpha=0.25, colors='b')
plt.title('contourf each level to infinity')

plt.show()
```

and output
![contour_bug3](https://cloud.githubusercontent.com/assets/580326/11144039/8143c234-89f1-11e5-9302-f10101d35aba.png)

The OP obtained results like subplot 1 using mpl 1.4, or 1.5 and the contourf kwarg `corner_mask='legacy'` (i.e. the old contouring code in `cntr.c`).  Using mpl 1.5 and the new corner masking code the results are like subplot 2.  The new code is clearly wrong (though prettier).  The old code is actually wrong too, but in a way that looks OK so it is a more subtle and insidious form of wrong.

The test data is a 2D gaussian, rising from 0 to 1 at the centre.  Subplot 5 shows the default contour plot of this data, using either old or new code.

The problem is that the OP is passing a list of **decreasing** levels to `contourf`.  This is the first time I have heard of anyone using decreasing contour levels.  The documentation doesn't say the levels should be increasing, but all of our examples have them increasing.  The old contour code does not check that the levels increase, nor the python wrapper of the contouring code.  When I wrote the new code it didn't occur to me that I needed to check that the levels increase given that the old code didn't bother.  Oops!

The new code is trying to follow the contours going backwards.  We are lucky (!) that we don't get an infinite loop or segmentation violation.

The old code uses, at its top level, a single function call for both `contour` and `contourf`.  This is `Cntr_trace()`, line 1877 in `cntr.c`.  It takes two contour levels, `levels[0]` and `levels[1]`.  If `levels[1] <= levels[0]` it assumes that it is a `contour` call returning a non-filled polyline, if not it is a `contourf` call returning a filled polygon.  In our example then it assumes it is a `contour` call whereas it is in fact a `contourf` call.  The returned polyline is rendered as a filled polygon.  The output is identical to that produced by taking each of the required contour levels in turn and performing a `contourf` call between that level and infinity.  Subplot 6 does just this to show that it is identical to subplot 1.

Finally, if we reverse the contour levels in our test code so that they are increasing, we get the results shown in subplots 3 and 4.  These are correct, given that we are contouring everything from 0 to 0.9, which just leaves a circle in the middle.

So we have a bug, or at least a lack of appropriate checking of specified contour levels.  I assume that it has been around since the dawn of time.  The OP's results are not what she asked for, but are presumably what she wants.  Anyone else who has been using decreasing contour levels has been getting output that probably looks fine but is incorrect.  At least my new code fails spectacularly and highlights the problem.

What do we do?  Do we enforce increasing contour levels only, or do we allow decreasing ones?  If the latter, do we only allow monotonically increasing or decreasing levels, or do we allow them to go up and back down again?

Whatever we opt for, I need to add a check in the new C++ code to only allow `(lower, upper)` pairs of contour levels.  If they are reversed, I will raise an exception.  At the python level we could be more permissive, but ensure the C++ code is called with them in the correct order.

My preference is to only allow increasing levels.  We have been assuming, but not enforcing, that policy for many years.  But I would like other developers' opinions on the subject.

**Comment by WeatherGod** [comment]
Good job recognizing the problem, Ian. I must have looked at that contourf call in the OP a dozen times and I just didn't realize that the order was descending.

My opinion for the path forward is to get a warning into 1.5.1 and 2.0, if the inputs are not sorted. This will at least help people know that there may be issues with their code, or, in the case of the newer contouring code, they will know why their results look messed up.

Then, for 2.1, we can enforce input order in some way. I am -0 on sorting the inputs ourselves because it might mask a bug in the user's code.

**Comment by efiring** [comment]
I like your suggestions, @weathergod.  I think that we should require ascending order rather than sorting.

**Comment by mdboom** [comment]
I agree with @WeatherGod and @efiring.  And I hope it goes without saying -- we shouldn't devote much effort to the old code other than this sort of warning/documenting/helping at this point.

**Comment by pelson** [comment]
Because we have been forced to turn anti-aliasing off on filled contours (many many years ago), the result of rendering small contours is hugely affected by whether they are drawn before or after larger contour outlines.

Essentially, I'm trying to say that ```levels=levels, colors=colors``` does not produce the same plot as ```levels=levels[::-1], colors=colors[::-1]```, and so am concerned at limiting the choice available to users by enforcing increasing levels.

**Comment by WeatherGod** [comment]
@pelson, the problem is that for the new contouring algorithm, passing the
decreasing levels results in completely wrong contours. Like... terribly
wrong. The old contouring algorithm happened to produce something
resembling correct if given decreasing levels, but was not identical to
increasing levels. These are called "stacked contours", and they do sort of
solve the gappy rendering issue we have seen elsewhere, but they would be
wrong if given transparent colors. This patch just warns about the issue
when using the old algorithm, but errors out for the new algorithm because
the results are wrong otherwise.

**Comment by pelson** [comment]
> The old contouring algorithm happened to produce something
resembling correct if given decreasing levels

I'm totally ok with the contour algorithm requiring monotonically increasing levels.

> These are called "stacked contours"

I was surprised at this, I don't recall that being the behaviour I witnessed, but maybe I mis-diagnosed all that time ago.

> but errors out for the new algorithm because
the results are wrong otherwise

This is the bit I don't necessarily think we need to do. If there is little added complexity from doing so, we can pass increasing levels to the contour algorithm and still *draw* the contours in the order that they were requested increasing or decreasing, right?

**Comment by efiring** [comment]
It's not that simple.  I think that if you do this with the present or the old algorithm, the order won't matter.  It would matter only if the regions are, e.g., everything above level 1, then everything above level 2, etc, but this only works in such a simple fashion in the special case where there is a simple hill, with no dips.  Something like this, but a little more complicated, seems to be what most other routines do; patches are stacked on top of patches, so that there are no problems with adjacent patch boundaries, provided no transparency is used.

**Comment by WeatherGod** [comment]
I *guess* we could do that, but that won't solve the problem introduced by
turning antialiasing off. The results from the contouring algorithm will be
unstacked. Changing the order of the draws will make no difference. The
difference you saw a long time ago is due to the polygons being stacked,
which prevents any gaps from appearing, but messes up rendering of
transparent contours.

And to pre-empt and suggestions that stacked contours should be considered
as a way to fix the aliasing problem permanently, I should point out that
changing the output from unstacked to stacked would break code of a few
high-profile insurance companies that utilizes the raw output from contourf
(I have personally experienced angry phone calls when one of our processing
scripts accidentally started putting out stacked contours).

**Comment by efiring** [comment]
If we were to introduce a stacked option, it would have to be a non-default option.  Also, the problem we have now was not introduced by turning antialiasing off; I think we have artifacts regardless of the antialiasing setting, but they are usually *less* severe with antialiasing off, which is the reason it is off.  It is all renderer-dependent and varies with alpha, though, and I always forget the details soon after walking away from it.

**Comment by marscher** [comment]
I get this error for a contour plot with the built in colormap matplotlib.cm.bwr if and only if using the Agg backend. In an interactive session in jupyter notebook the same code works fine. I can provide a a minimal test example if desired.

**Comment by tacaswell** [comment]
This should have been closed as fixed.

@marscher Are you using the svg backend in the notebook?  Other wise `%matplotlib notebook` and `%matplotlib inline` both use `agg` for the actual rendering so I do not see how it would work in the notebook and not when using `Agg` directly.

**Comment by marscher** [comment]
> @marscher <https://github.com/marscher> Are you using the svg backend in the notebook? Other wise |%matplotlib notebook| and |%matplotlib inline| both use |agg| for the actual rendering so I do not see how it would work in the notebook and not when using |Agg| directly.

No, actually I'm enforcing the usage of Agg by setting it in a matplotlibrc file.

**Comment by greglucas** [comment]
If the contour levels are not increasing we now raise `ValueError: Contour levels must be increasing`. Closing as I don't think there is anything more to be done here.
