### ISSUE TITLE
 Ipe backend

### ISSUE THREAD

**Issue by Etn40ff** [matplotlib/matplotlib#5630]
Dear All,
while looking for a way to interface sage and ipe, I came across this third party backend for matplotlib:
https://github.com/otfried/ipe-tools/tree/master/matplotlib

I made a patch to include it into the version of matplotlib shipped with sage but it was suggested that I should report upstream for a possible inclusion in the standard matplotlib. 
You can find the relevant discussion here:
http://trac.sagemath.org/ticket/19667

**Comment by tacaswell** [comment]
What are ipe files?

Have you contacted the authors of the backend about this?

We should consider inviting the authors to move their package under the mpl organization, but not merge the code in to the main repo.

I skimmed the source very briefly, it looks like an xml based file format and looks like it shares a lot of code with the svg backend.  If this does end up in mainline we should look into refactoring that.

The xml file types might also be worth re evaluating how we implement them once we have serialization working as the json to xml translation might be easier.

**Comment by Etn40ff** [comment]
Ipe is a drawing editor. Here is the official web site: http://ipe.otfried.org/
.ipe is its native file format and, as you point out, is just some type of xml.
I might not be the right person to contact the author of the matplotlib backend since I never contributed anything though.

**Comment by otfried** [comment]
I'm the author of Ipe and the maintainer of the Ipe backend for matplotlib.

Yes, the Ipe file format is xml-based.  But one distinguishing feature of Ipe is that all text processing is done through (pdf/xe)latex, and so the backend actually reuses the LatexManager of the PGF backend (by simply importing it).  The backend currently contains a copy of the XMLWriter class which I copied from the SVG backend - I'm not sure why I didn't simply say "from matplotlib.backends.backend_svg import XMLWriter' - perhaps there were problems with different versions.

I published the backend as a standalone module and gave up on registering it as a matplotlib backend because the registration mechanism has changed (several times?) during the lifetime of matplotlib - and my users seem to run quite diverse versions (see e.g. https://github.com/otfried/ipe-tools/issues/6 and https://github.com/otfried/ipe-tools/issues/1).

It would be great if it could become part of the distribution - maybe in a couple of years I don't need to maintain the standalone version then.

But what does "move the package under the mpl organization, but not merge the code in to the main repo" mean?

**Comment by Etn40ff** [comment]
Any progress here? Is there anything I could do to contribute?

**Comment by anntzer** [comment]
I would suggest closing the issue.  As far as I can tell, if you already bothered installing IPE, then you should also be able to install ipe-tools, and an external backend can be used just as easily as an internal one (set the backend to `module://backend_ipe`).

**Comment by tacaswell** [comment]
> But what does "move the package under the mpl organization, but not merge the code in to the main repo" mean?

Move it on github to it's url would be `github.com/matplotlib/ipe-tools`

**Comment by Etn40ff** [comment]
Closing this issue as is would mean that ipe will never end up being supported in sage. This is not necessarily a bad thing (I have not seen a great interest in this integration anyway and I might be the only person using it) but surely it is a missed occasion.

**Comment by anntzer** [comment]
In agreement with https://trac.sagemath.org/ticket/19667#comment:10 and https://trac.sagemath.org/ticket/19667#comment:11 I would tend to think that this is trying to push code complexity (support for an additional format) from where it really belongs (the editor itself) to some dependency repo (mpl or sage).

Additionally it is possible for backend_ipe to register itself as "I can export ipe files" by hooking into https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backend_bases.py#L90 (which can be done at the moment you do "import backend_ipe", which can go into your $PYTHONSTARTUP or equivalent of sage); I have no idea how sage does stuff but I'd think it should be able to save to any format that mpl can save to (as it can just defer the job to mpl).

**Comment by anntzer** [comment]
Closed due to apparent general lack of interest on moving this forward.
