### ISSUE TITLE
Segfault on plotting with PySide as backend.qt4

### ISSUE THREAD

**Issue by JCorson** [matplotlib/matplotlib#5687]
The following code is failing with a segfault on Mac and Linux with `backend : Qt4Agg` and `qt4.backend : PySide`.

    import matplotlib.pyplot as plt
    plt.plot(range(10))

Setting qt4.backend to PyQt4 does not produce a segfault and this code works as expected. 
Running %matplotlib in ipython also prevents this segfault.

I have reproduced this on both Enthought and Anaconda releases of matplotib 1.5.0 on Mac (OSX 10.11) and Linux (Ubuntu 14.04).

**Comment by tacaswell** [comment]
I can confirm this.  It is a regression from 1.4.3 in the sense that it didn't used to seg-fault, but I also can not get it to show a window at all.

**Comment by tacaswell** [comment]
err, I can get it to work with 1.4.3 + pyside + ipython magic and 1.5.0 + pyside + ipython magic.

the matplotlib ipython magic installs their own version of input hook 

This makes me think that the underlying problem is that pyqt is (forcibly) installing it's PyOS_InputHook where as pyside does not.

**Comment by tacaswell** [comment]
And I can not figure out how to get pyside to install it's own version of the input hook.  The best I could get out of a quick google search is a link that says that functionality was never implemented (but it is from 2011 https://groups.google.com/forum/#!topic/pyside/EZxnlxEy94o )

I suspect that the other part of this is that the auto-redraw is forcing a redraw on an object that does not exist yet because it should have been created by the first draw to the screen (which never happens under pyside because the qt event loop is not spinning).
