### ISSUE TITLE
Invalid caching of long lines with nans

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5693]
```
import numpy as np, matplotlib.pyplot as plt
x = [3, 5] + [np.nan] * 10000 + [0, 2]
plt.plot(x, x)
plt.xlim([0, 2])
plt.show()
```
As of matplotlib 1.5.0, this fails to plot the section of the line between 0 and 2 (which can be seen by replacing 10000 by e.g. 1).

This is due to incorrect caching logic in `Line2D.recache` and more specifically in `Line2D._is_sorted`, which believes that the line's x-points are sorted because `nanmin(diff(x)) > 0` (but this skips across the zero).

Related to #5365.

I believe a proper fix for both issues would be to replace the implementation of `_is_sorted` by something like `x = x[~np.isnan(x)]; return len(x) == 0 or np.diff(x).min() >= 0`.

**Comment by tacaswell** [comment]
Is this also on master?  This seems very familiar.

**Comment by anntzer** [comment]
Yes.

**Comment by mdboom** [comment]
Indeed this needs to be fixed, but very carefully.  This is on a very critical path, and is intended as a performance optimization.  If the check becomes more costly than just drawing the line, we are in real trouble.  Whatever solution we arrive at should be adequately benchmarked -- and it may require writing a very simple C function to perform this check (which no doubt would be many times faster in practice because it could "fail quickly" in a way that Numpy can't).
