### ISSUE TITLE
Using internal qhull despite the presence of pyqhull installed in the system

### ISSUE THREAD

**Issue by yurivict** [matplotlib/matplotlib#5745]
I have pyqull installed https://pypi.python.org/pypi/pyhull, yet matplotlib still says:
```
                 qhull: yes [pkg-config information for 'qhull' could not be
                        found. Using local copy.]
```

Is this the naming problem: pyhull vs. qhull? But sources seem the same.

FreeBSD 10.2

**Comment by jenshnielsen** [comment]
`pyqhull` is not the same as `qhull` and matplotlib does not use `pyqhull` 

`qhull` is a c library where as `pyqhull` is a python wrapper to `qhull`. Matplotlib does not use the `pyqhull` wrappers but it's own wrapper to `qhull` 

`pyqhull` probably also ships it's own `qhull` so that is why the source is the same.

**Comment by yurivict** [comment]
Ok, so matplotlib is looking for latest version of http://www.qhull.org/ C lib. But it doesn't supply .pc for pkg-config to find it.

**Comment by tacaswell** [comment]
Closing this as upstream fix required.

You can also provide a `setup.cfg` file as part of the FreeBSD build process to override where mpl looks for headers when package-config fails (see https://github.com/matplotlib/matplotlib/blob/master/setup.cfg.template#L6)

**Comment by tacaswell** [comment]
Similarly, the `tests` entry can be set to `False` which will not install the test images (which saves about 40M of space).
