### ISSUE TITLE
Figure.suptitle does not respect `size` argument

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#5747]
I noticed this when running the documentation, `suptitle` does not correctly obey the `size` argument:
```python
y, x = np.mgrid[-4:2:200j, -4:2:200j]
z = 10 * np.cos(x**2 + y**2)

fig, (ax1, ax2) = plt.subplots(ncols=2, figsize=(8, 4.5))

ax1.imshow(z)
ax1.set_title('First title')

ax2.imshow(z)
ax2.set_title('Second title')

fig.suptitle('Suptitle', size='x-large')

for c in fig.get_children():
    if isinstance(c, mtext.Text):
        print(c.get_size())
```
After 1000 trials, 1.4.3 is consistently large, while 1.5.x is more often than not the default size:
```
$ sort mpl143 | uniq -c
   1000 17.28
$ sort mpl15x | uniq -c
    616 12.0
    384 17.28
```

**Comment by tacaswell** [comment]
Suspect that this is another case of dict iteration order being randomized and a default over-riding the user input.

**Comment by tacaswell** [comment]
It looks like the problem is that in c8698b978e6f5ceaf54de0df0e6a0a07da3c280c
a look up was added to hit rcparams for the defaults.  It checks for and adds a `fontsize` entry in kwargs.  Passing in `size` does not trigger that logic and you end up with both `size` and `fontsize` in the `kwargs`.   I don't quite understand the ratio, I think it should be 50/50....
