### ISSUE TITLE
Widget event issue

### ISSUE THREAD

**Issue by enkhee0906** [matplotlib/matplotlib#5812]
I have an issue on widget events. I have created a figure which contains several subplots. When click on one of the subplots, it shows another figure. This new figure contains button and rectangle selector widgets. Until this it works fine. Problem is nothing happens if I click on the buttons or draw rectangle on this new figure. It works well (i mean button onclick, line_select_callback events raise ), if I just create figure not after click the subplots. I do not know what I am doing wrong. Please help me.

By the way, I am using: 
matplotlib.__version__ : '1.4.3'
matplotlib.get_backend() : Qt4Agg
python: 2.7.10 | Anaconda 2.3.0 (64-bit)

**Comment by tacaswell** [comment]
Can you provide a minimal example demonstrating the problem you are having?

This question is probably better suited from the mailing list (matplotlib-users@python.org https://mail.python.org/mailman/listinfo/matplotlib-users you have to subscribe to post)

I am going to close this as I suspect that this is a usage question (better handled on the mailing list) rather than a bug in mpl (better handled on gh).  If this _is_ a bug in mpl please ping to have this re-opened.

In either case, we will need to see the code to help you.

**Comment by enkhee0906** [comment]
I am sorry that creating usage question in here. Soon, I'll send more detailed information to this e-mail.

**Comment by tacaswell** [comment]
No worries!  Sorry that your first interaction with mpl devs was slightly hostile/negative.

The advantage of sending usage question to the mailing list is that a) they get seen by a wider range of people (increasing the chances that someone will answer it!) and b) helps keeps our issue tracker for bugs/feature requests (which as you can see we have over 600 open issues, if we added user support in there too it would be even more unmanageable).

Also, rough advice totally guessing, use the OO interface and hold/pass `Axes` objects around rather than using `pyplot` + the global state to keep track if where to draw things.
