### ISSUE TITLE
tests.py is missing from pypi tarball

### ISSUE THREAD

**Issue by jlec** [matplotlib/matplotlib#5831]
Please include ```tests.py``` so that downstream maintainers can properly test.

**Comment by tacaswell** [comment]
Have we ever included `tests.py` in the pypi tarball?

I suggest pulling the src tarball from gh instead?

**Comment by jenshnielsen** [comment]
I suspected that it might have been removed in #4668 but that does not seem to be the case.

**Comment by jlec** [comment]
Many downstream distro like fedora, debian, gentoo and so are using the pypi tarball, as this is what you are intending to ship to the end user. Therefor I rather dislike the idea to fetch directly from GH. Shouldn't be a big deal to include that file. Currently we are running ```${PYTHON} -c "import sys, matplotlib as m; sys.exit(0 if m.test(verbosity=2) else 1)"``` but I really want to run the tests in the same way as you are doing it.

**Comment by tacaswell** [comment]
Fair enough. I am biased towards pulling directly from the tag on gh as it
is the ground truth, but I will not argue with packagers about packaging. (
I was just trying to be helpful and suggest work arounds for right now).

Unless this is a regression I don't think this is enough to force a new
release, but will be fixed in the next one.

**Comment by jlec** [comment]
> Unless this is a regression I don't think this is enough to force a new release, but will be fixed in the next one.

no, that can be done in the next release. thanks.
