### ISSUE TITLE
mathtext mishandling of certain exponents

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#5864]
From [the second example for twin axes in AxesGrid1](http://matplotlib.org/mpl_toolkits/axes_grid/users/overview.html#example-2-twin), where the intent was probably to have a "seconds of angle" symbol:
```
$ python
Python 3.5.1 (default, Dec  7 2015, 12:58:09) 
[GCC 5.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt; plt.gca().set_xlabel("$^{''}$/yr"); plt.show()
<matplotlib.text.Text object at 0x7f6451604f98>
```
(same result from within ipython with `%matplotlib` active)
![screenshot_20160116_211600](https://cloud.githubusercontent.com/assets/1322974/12376067/89f58854-bc96-11e5-93b4-7bd371027a44.png)

> EDIT: This part is invalid and should be ignored
> Weirdly enough, running the same command from with `python -c` a different result:
```
$ python -c 'import matplotlib.pyplot as plt; plt.gca().set_xlabel("$^{''}$/yr"); plt.show()'
```
![screenshot_20160116_211836](https://cloud.githubusercontent.com/assets/1322974/12376084/e5a082bc-bc96-11e5-9361-18d534865454.png)

> (checked without any matplotlibrc).

Preempting @tacaswell to @zblz this time :-)

**Comment by QuLogic** [comment]
The result with `python -c` is different because the single quotes in the middle end and start two Bash strings.

**Comment by anntzer** [comment]
Oops, failed at triple nesting my quotes.  The main issue still stands though.

**Comment by zblz** [comment]
The first result is definitely weird, I have no idea where that phi comes from. I'll take a look to try to find the culprit.

For the record, the proper way of of typesetting arcseconds would be with primes `$^{\prime\prime}$`.

**Comment by zblz** [comment]
Also note that this only happens with the Computer Modern mathtext fontset (which is default in 1.5.x but will not be in 2.x). with the dejavusans fontset the rendering is better but there is still some weirdness with the first `'`:
![2016-01-17-122456_1366x768_scrot](https://cloud.githubusercontent.com/assets/576258/12377417/74723994-bd15-11e5-9e45-13840c3ec7cc.png)

**Comment by zblz** [comment]
So I narrowed the behaviour down to two effects:

- mathtext will convert apostrophes into `^\prime`, so that's why the second apostrophe gets typeset correctly, but it will only do this change to apostrophes coming after a nucleus (so it will change `$a'$`  into `$a^{\prime}$` but not $'$ into $^\prime$).
- the `latex_to_bakoma` dictionary does not have an entry for `'`, and the Bakoma fonts included do not have a `quotesingle` character, only `quoteleft` and `quoteright`. I don't know why the lack of a entry results in `\phi`, though.

The second part could be fixed by adding an entry in the `latex_to_bakoma` dict, and in latex a single `'`. However, I think fixing the behaviour of the first part (converting all `'` to superscripted primes) is better. I am still having some trouble implementing that, though.

**Comment by efiring** [comment]
On 2016/01/17 10:40 AM, Victor Zabalza wrote:
> However, I think fixing the behaviour of the first part (converting all
> |'| to superscripted primes) is better.

If I understand correctly, this is making mathtext *less* compatible 
with LaTeX.  Is this a desired result?  Granted, `$^\prime$` is clunky 
and ugly.

**Comment by anntzer** [comment]
Actually I just learnt that [`'` is an active character in tex that gets converted to `^\prime` (plus some more)](http://tex.stackexchange.com/questions/87134/what-is-the-advantage-of-using-f-prime-instead-of-f).  So it's actually more compatible.

**Comment by zblz** [comment]
@anntzer - I did not know about `'` being an active character (hence my comment above about a proper way...), it looks very useful. I tried to add the full functionality of that in #5880 so that even apostrophes as first charachters get recognised as primes.
