### ISSUE TITLE
Better document how to set font

### ISSUE THREAD

**Issue by shirish93** [matplotlib/matplotlib#5941]
Hello,

The title says it all. If you will see in [this Jupyter notebook](https://github.com/shirish93/CoLing/blob/master/Experiments.ipynb), the text in the axes appears as undefined squares, whereas the string is accurately displayed elsewhere.

I'm using the latest release of matplotlib, installed today, on Python 3.4.3 on Windows 7.

**Comment by mdboom** [comment]
Matplotlib uses its own basic text layout algorithm, rather than something like Pango, which can handle internationalized text.  This is the main purpose of MEP14 -- to get this working properly, but it will be a great deal of work.

The other issue you are running into is that the default font that ships with matplotlib, "Bitstream Vera" does not have any non-European characters.  matplotlib 2.0 will replace this font with "Deja Vu", which has a much broader character set, but that still won't help if the language requires specialized layout.

One *possible* workaround is to set the rcParam `usetext=True` if you have a working xetex or luatex installation.

In the meantime, this is a long-known bug that we haven't been able to find the time or resources to resolve.

**Comment by shirish93** [comment]
Thank you for the quick turnaround! Is there something I can do to help?

**Comment by tacaswell** [comment]
I think you can change the default font to one that contains the code-points you need.

**Comment by mdboom** [comment]
With 2.0 we have more character coverage -- we're not doing any fancy text layout, but that's hopefully coming in the future.

**Comment by jklymak** [comment]
I think it's safe to close this with the newer font handling documentation.
