### ISSUE TITLE
How to linearly interpolate the colormap between vertices of a surface?

### ISSUE THREAD

**Issue by danijar** [matplotlib/matplotlib#6027]
In surface plots, steep slopes result in large faces to be drawn. When using a colormap, matplot chooses the color on a per-face basis. This causes hard jumps in color even though the plotted function is perfectly smooth.

Increasing the resolution of the surface is a sub-optimal solution, because the plotted function has to be evaluated quadratically more often. In my example, I needed a very high resolution for the color jumps to disappear. The plotting for this takes over two minutes on my machine.

Is there an option to linearly interpolate the color between vertices on a per-pixel basis? If not, do you think this would be a worthwhile addition to matplot?

![Cross entropy](http://i.imgur.com/rpdXZzA.png)

**Comment by tacaswell** [comment]
attn @WeatherGod

**Comment by WeatherGod** [comment]
The problem is that what is returned is a Poly3DCollection, which is just a
subclass of PolyCollection. The "mesh" is many polygons, each with its own
color. We don't have the capability to assign a gradient color to any
polygon (would be a neat feature, though!). If we had that capability, then
it is possible to support what you want in mplot3d because the function
also computes normal vectors, which could be used to describe a 3d gradient.

I should point out something else that trips up a lot of people. By
default, plot_surface() will only use the data at every 10th data point
(cstride, rstride defaults to 10). There is a bunch of historical reasons
for this related to the poor performance of the mesh-generation code. But,
if you haven't been setting them to something lower, then you don't have to
have a finer grid for your mesh, just reduce rstride/cstride to something
like 1 or 2.

**Comment by danijar** [comment]
Thanks for the reply. Strides are already set to 1.

I think we just need a color per vertex rather than per face. Not sure if we'd even need the normal for that. The pixel color would just be interpolated linearly based on the distance to the three points, i.e. using barycentric coordinates.

Not sure if I find the time, but I'd consider implementing that. Do you have some hints/material for me to get started?

**Comment by WeatherGod** [comment]
The problem is that there is no mechanism within matplotlib to support
color interpolation, except within the Image framework. Until very
recently, the Image framework didn't work properly with arbitrary
projections/transforms. In any case, mplot3d doesn't work off of the
transforms framework anyway, so mplot3d has never supported Image plotting.

I have made a few attempts to port mplot3d over to fully utilize the
transforms framework over the years, but I have been stymied every time. It
is number one on my wish list, and it would solve so many problems (see the
never-ending +1's in the bug report about supporting log scaling). Even
little steps towards implementing that would be welcomed, such as just
implementing the 3d->2d projection as an official transform with unit tests
would be a huge step in that direction.

**Comment by WeatherGod** [comment]
sorry, I am not aware of anybody contributing anything to make this more
feasible.

**Comment by claell** [comment]
Alright. Can you redirect me to the project page blocking this, so I can create an issue there in order to get the missing fuctionality?

**Comment by jklymak** [comment]
A solution is for you to grid your data more finely and do the interpolation yourself using one of the many available tools.  I actually feel this is significantly better than Matplotlib choosing an interpolation scheme for you.  https://stackoverflow.com/questions/37822925/how-to-smooth-by-interpolation-when-using-pcolormesh
