### ISSUE TITLE
specgram(x) should warn if x.size < 256

### ISSUE THREAD

**Issue by roger-** [matplotlib/matplotlib#6064]
The default `NFFT` size of 256 gives misleading results if `x.size` << 256, for example this chirp:

``` python
import numpy as np
import pylab as pyl
from scipy.signal import chirp

fs = 200
t = np.arange(0, 1, 1/fs)

signal = chirp(t, t1=1, f0=0, f1=100)

pyl.specgram(signal, Fs=fs)
pyl.show()
```

Gives [this](http://i.imgur.com/NT7PbFC.png). Passing `NFFT=32, noverlap=16` to `specgram()` gives [this](http://i.imgur.com/TQYOfEe.png) more reasonable result.

Simplest fix is probably just to warn users when their data is too small.

**Comment by tacaswell** [comment]
Are the results _wrong_ or just misleading?  Warnings tend to not be read by users who should read them and just annoy users who read them, but know what they are doing.

I would prefer to either raise if the length of the data is less than `NFFT` or add a comment to the docstring.

**Comment by roger-** [comment]
Well with the default parameters and a small array the spectrogram is wrong since it shows a static distribution of power. 

I don't know if there's ever a case when it's useful to have an `NFFT` that's bigger than your data, but an exception could work too. An alternative is have an 'auto' option by default that picks better values.

**Comment by tacaswell** [comment]
Thinking about this a bit more, the result is 'correct', in that there is only one window and it gives you back time point sample, just not terribly useful.

**Comment by flothesof** [comment]
Looking at this problem, I agree with @tacaswell : the result is what the user asked the specgram function to produce.

Because when asking for 
`pyl.specgram(signal, Fs=fs, NFFT=64, noverlap=32, pad_to=1024)` the result becomes what @roger-  might have expected: an upward trending slope for frequency.
![image](https://cloud.githubusercontent.com/assets/2360669/13602840/738c2ffc-e539-11e5-96cd-9ba2cf88f0b2.png)

So the point is not that the spectrogram is wrong, rather that the default value for NFFT (which is 256) is not adapted to a case where you only have 200 points in the input signal, I would say.

Hope this clarifies the issue a bit.

Best, Florian

**Comment by roger-** [comment]
@flothesof: well I guess "wrong" in the sense that the default `NFFT=256` is unable to produce a useful spectrogram if you have less than a certain number of points.

I think a simple check and a warning would be good in this case so it doesn't bite anyone with a misleading representation of their signal.

**Comment by dstansby** [comment]
Looks like this is fixed and good to be closed!

**Comment by roger-** [comment]
Awesome!
