### ISSUE TITLE
matplotlib.animate writes png frames in cwd instead of temp files

### ISSUE THREAD

**Issue by prinsherbert** [matplotlib/matplotlib#6135]
When creating an mp4 using pyplot.annimate.FuncAnimation.save, a set of temporary png-files are created in the current working directory.

I could not find out whether this is ffmpeg of matplotlib, in case of matplotlib: please use tempfiles.

In case of ffmpeg, consider executing this in a temporary directory, such that the cwd doesn't get cluttered with temp png's.

**Comment by elijahbal** [comment]
I would humbly suggest that you provide a test script for reproducing this behaviour. It could be a good starting point to debug the problem.

**Comment by prinsherbert** [comment]
That's fair of course.

    import numpy, time, os
    from threading import Thread
    from matplotlib import pyplot, animation

    def print_temporary_files():
        time.sleep(2)
        print(os.listdir('.'))

    def update_line(num, line):
        line.set_data(numpy.arange(10), numpy.random.randn(10))
        return [line]

    fig = pyplot.figure()
    line0 = pyplot.plot(numpy.arange(10), numpy.random.randn(10), 'r-')
    line_animation = animation.FuncAnimation(
        fig,
        update_line,
        50,
        fargs=(line0),
        interval=50,
        blit=True
    )

    Thread(None, print_temporary_files).start()
    line_animation.save('random-lines.mp4', writer=animation.FFMpegFileWriter())


The separate thread shows the following:

    ['_tmp0000002.png', '_tmp0000015.png', '_tmp0000009.png', '_tmp0000004.png', '_tmp0000008.png', '_tmp0000020.png', '_tmp0000001.png', '_tmp0000010.png', '_tmp0000019.png', '_tmp0000005.png', '_tmp0000013.png', '_tmp0000016.png', '_tmp0000014.png', '_tmp0000000.png', '_tmp0000007.png', '_tmp0000011.png', 'mwe.py', '_tmp0000018.png', '_tmp0000006.png', 'mwe.py~', '_tmp0000017.png', '_tmp0000003.png', '_tmp0000012.png', 'im.mp4']

Of course, you need to generate enough frames for the files to not be cleaned up within the 2 seconds race condition.

Moreover, the files are only created when one specifies `writer=animation.FFMpegFileWriter()`

**Comment by WeatherGod** [comment]
This is a feature of any movie writer that inherits FileMovieWriter, not
just FFMpegFileWriter. The way these file-based writers work is that the
files are all created before-hand, and then the command-line is invoked,
passing it the list of files (or the filename prefix) to process. Most
importantly, that list of filenames has to be sortable, so we need tight
control over the exact naming because different movie writers expect
something slightly different.

Using tempfiles wouldn't work, because we need actual, named files for this
to work. Using a temporary directory might be possible, though. That would
solve other issues such as accidental filename collisions from two or more
processes working from the same current working directory.

Of course, if a cluttered working directory is your main concern, then why
not just simply use FFMpegWriter()? That will pipe the bytes directly to
FFMpeg while the animation is being made. Not that we shouldn't look into
using a tempdir, of course, just trying to address your stated concern.

**Comment by prinsherbert** [comment]
Thank you for your feedback. I'm not really concerned on whether or not this gets solved, especially since I'm not using the animation functionality anymore at the moment :) I created the issue such that developers may decide whether or not to address this. Good luck in any case!

**Comment by efiring** [comment]
#7191 is related, in that it identifies an obstacle to the user who wants to specify a directory for the temporary files.  I think the present issue can be closed.
