### ISSUE TITLE
No Easy Way to add a "Break" in an Axis

### ISSUE THREAD

**Issue by yongzhez** [matplotlib/matplotlib#6223]
This feature request pertains to the following stack overflow question. http://stackoverflow.com/questions/32185411/break-in-x-axis-of-matplotlib

The answer for making a break works, however how the method works for a user should probably be abstracted away since it is not only unintuitive, but also quite lengthy for a simple break. I wish to create set_axis_break_x and set_axis_break_y functions that would take a tuple and create the break between the 2 data points without need for those long lines of code.

**Comment by tacaswell** [comment]
:+1: in principle, but I expect there to be a lot of surprisingly sharp edges (mostly that you have to copy the artists that already exist in the first axes to the new one.

Doing something with compound artists to represent the artists in each of the axes draw trees would also be interesting to think about (so that `ln.set_ydata` correctly broadcasts to both).

Should probably be a figure-level method as it manages creating a new axes (and resize the host axes).  Sharex/sharey will probably help here as well.

**Comment by anntzer** [comment]
Closing as essentially a duplicate of https://github.com/matplotlib/matplotlib/issues/11682, which has a bit more discussion on the topic.
