### ISSUE TITLE
Rendering vector graphics: parsing polygons?

### ISSUE THREAD

**Issue by Makosak** [matplotlib/matplotlib#6258]
- Matplotlib 1.5.1, Python 2.7.11, OSX 10.11.3
- installed via pip, conda virtual env

Is the rendering of a map (or collection of polygons) in MatPlotLib hardcoded? I'd like to parse out the polygons for interaction, and was exploring ways do it with matplotlib and mpld3 extensions. Parsing out points in a scatter plot is no problem, but the polygons only show lat/long coordinates, where I'd like to hover on a specific polygon and pull its attributes and info. From mpl3d documentation there were some comments of hardcoding certain parameters, so perhaps that's the same issue? In other words, I'd like my vector graphics appear as vectors, not flattened rasters.

I also tried adding a line to force rendering as an SVG image, to potentially parse the polygons that way, but had the same result. (%config InlineBackend.figure_format = 'svg' ) It looks like a file i/o workflow would be required to get get around this, but ideally could visualize in matplotlib all the way (or at least in a way that could be easily pulled into mpld3).

<img width="473" alt="screen shot 2016-04-01 at 10 44 43 am" src="https://cloud.githubusercontent.com/assets/4277692/14215547/7e61cd52-f7f8-11e5-81c1-0ea2d3ae23c3.png">

<img width="616" alt="screen shot 2016-04-01 at 10 44 33 am" src="https://cloud.githubusercontent.com/assets/4277692/14215637/04ddad9c-f7f9-11e5-964a-ea196a36cd25.png">

**Comment by tacaswell** [comment]
You should probably report this against `pysal` not mpl.

If you have the ploygons you can use `path.contains` to check if the current location is in a given polygon. However without knowing how `pysal` is doing the plotting under the hood (or a way to convince pysal to return the artist it is creating instead of an axes pre-plotted?!) there is not much more that we can do.

**Comment by Makosak** [comment]
I'll post some examples using a different library or two this weekend-- had the same issues no matter what dependency was used. Pysal uses matplotlib; it's primarily an analytics toolbox not viz, so that's why. I wouldn't want to check locations against polygons, but retain the vector nature of the polygons used as an input (which could then be parsed for dynamic exploration). Will post more soon.

**Comment by Makosak** [comment]
Here's another example, using shapefile with maplotlib to visualize the same S. Carolina dataset. (Pysal is only being imported to bring in sample data in this example; you could use any other option.) Again, the entire collection of polygons is flattened (to raster) so I can only explore via lat/long, not the actual, individual vector objects of the Polygons, or collection of polygons... If this is just how matplotlib does it, that's fine, but I was hoping there was a hack or other way of rendering that I was missing?

This is also true of examples here -- http://matplotlib.org/basemap/users/examples.html -- The coordinate plot is beautiful for static renderings, but not 2d vector graphics that we may want to dynamically interact with. Is there any way to preserve the individual components of the polygons?

<img width="543" alt="screen shot 2016-04-01 at 11 03 36 pm" src="https://cloud.githubusercontent.com/assets/4277692/14224813/99dd59fa-f85e-11e5-9642-7f5a28585673.png">

**Comment by tacaswell** [comment]
In your second example you are plotting each county via `plot` which gives you back a `Line2D` object (which you could be capturing to work with).  You probably want to be working with [`Polygon`](http://matplotlib.org/api/patches_api.html#matplotlib.patches.Polygon) artists (which should be exported to the vector backends as vectors) rather than `Line2D` artists as polygons have a notion of 'closed' which is helpful here.

Using the mpl callback system you can set up pick callbacks on each artist (trigger an event via mouse clicks) and you can use the `mouse_move` events to trigger actions on mouse motion.  `mpldatacursor` is a project which makes good use of this sort of thing.  If you have mpl 1.5+ you can also hook into the built-in mouseover machinery.

To get any of the interactive features you have to use the `notebook` backend.

I really do not understand what you mean by "Again, the entire collection of polygons is flattened (to raster)"

Please paste in code as text, not as images.

This discussion might do better on the mailing list than as an issue.

**Comment by Makosak** [comment]
Vector vs raster are different ways of representing map objects. I found the same challenges in mpl examples as listed above via link, and multiple other examples from different sources. I'll keep on looking into it. Thanks for the comments.

**Comment by tacaswell** [comment]
Internally mpl keeps everything as `Artist` objects (which map very closely to a vector representation).  Things are not rasterized until the last possible moment at draw-time.
