### ISSUE TITLE
restore_region is not documented as a method of FigureCanvas

### ISSUE THREAD

**Issue by janssen** [matplotlib/matplotlib#6295]
[The current documentation](http://matplotlib.org/api/backend_bases_api.html#matplotlib.backend_bases.FigureCanvasBase) does not mention `restore_region`.  I note that the Kivy backend does not implement it; thus MPL animation fails.

**Comment by WeatherGod** [comment]
I think it is because it isn't a method of FigureCanvasBase. Not all
backends can do a restore_region, so only those that can have it
implemented. Perhaps a stub method should be put in the base class that
provides the basic documentation, but raises a NotImplementedError.

Animations can work without restore_region, but the backend needs to have
"support_blit" attribute set to False.

In fact, that might be the more appropriate bug. In the base class,
`support_blit` is True, but `restore_region()` is not implemented.
`support_blit` really should default to False.

**Comment by mdboom** [comment]
> In fact, that might be the more appropriate bug. In the base class, `support_blit` is True, but `restore_region()` is not implemented. `support_blit` really should default to False.

That's probably right.  But we'll have to update all subclasses for the change (and technically it breaks backward compat for third-party backends, etc...)

**Comment by janssen** [comment]
That's "supports_blit", not *support_blit".
