### ISSUE TITLE
all matplotlibrc files should be loaded in order

### ISSUE THREAD

**Issue by awelkie** [matplotlib/matplotlib#6320]
Only one matplotlibrc file is loaded instead of loading them in order of decreasing scope. So when I added a matplotlibrc file in my home directory it unexpectedly changed the backend that was being set in `INSTALL/matplotlib/mpl-data/matplotlibrc` because that file was no longer being loaded. I expected matplotlib to load the global (install) config and then apply my config on top of that.

**Comment by tacaswell** [comment]
That would be a major API/behavior change.

If you want to have 'cascading' styles, use `mpl.style.use` which applies the given style on top of the current rcparams.

**Comment by WeatherGod** [comment]
Note that I don't think that would solve the problem of backend changes
since backends aren't style. But I agree, nowhere in any documentation do
we state that the rcfiles are cascading. Instead, the selection of rcfiles
is documented as a fallback mechanism (current dir > ~/.config > built-in
defaults).

On Wed, Apr 20, 2016 at 10:34 AM, Thomas A Caswell <notifications@github.com

**Comment by rcomer** [comment]
If settings from all available matplotlibrc files were applied, I would need a new solution for my StackOverflow question here
https://stackoverflow.com/questions/67210631/restore-rcdefaults-by-environment-setting

**Comment by jklymak** [comment]
Yes not sure why this has dragged around for 7 years.  We don't cascade style sheets and the backend mechanism has been overhauled.
