### ISSUE TITLE
Master requires cycler 0.10.0

### ISSUE THREAD

**Issue by etgalloway** [matplotlib/matplotlib#6325]
Master requires cycler 0.10.0, not 0.9.0+ (as specified in setupext.py).

For 0.9.0, importing matplotlib fails:
```python

    In [1]: import matplotlib

        <<< SNIP >>>

        807     for prop in cycler_inst.keys:
        808         norm_prop = _prop_aliases.get(prop, prop)
    --> 809         cycler_inst.change_key(prop, norm_prop)
        810 
        811     return cycler_inst

    AttributeError: 'Cycler' object has no attribute 'change_key'
```
`change_key` was added to 0.10.0 according to the cycler release notes.

**Comment by WeatherGod** [comment]
Huh, you are right. That got missed in my pull request. For some reason, I
thought it was added in 0.9...

**Comment by zcarver** [comment]
I have got this error as well, is there a way to remedy this??

**Comment by etgalloway** [comment]
@zcarver: try installing cycler 0.10.0.

**Comment by tacaswell** [comment]
update cycler, we need to fix the dependency tracking.

**Comment by akrherz** [comment]
For whatever it is worth, I just built matplotlib 2.0.0 via `python setup.py bdist_rpm` and during the seemingly successful build it reported
```
REQUIRED DEPENDENCIES AND EXTENSIONS
    ...snipped...
                cycler: yes [using cycler version 0.9.0]
```

and of course later errored out as above when I attempted to use it.

**Comment by tacaswell** [comment]
what is `bdist_rpm` and does it do anything to the dependency tracking?

attn @tomspur

**Comment by WeatherGod** [comment]
bdist_rpm builds the RPM package so that it can be installed via yum. I
have no clue what it does with dependencies, though.

**Comment by tomspur** [comment]
It seems the documentation of `bdist_rpm` on [python 3](https://docs.python.org/3.6/distutils/apiref.html?highlight=building%20rpm#module-distutils.command.bdist_rpm) is not very helpful. The one with [python 2](https://docs.python.org/2.0/dist/creating-rpms.html) used to be more verbose.
We are not using it though because you have not much influence about the generated rpm and the resulting rpm is not complying with our rpm guidelines. 

[`bdist_rpm`](https://github.com/enthought/Python-2.7.3/blob/master/Lib/distutils/command/bdist_rpm.py) is/was running the usual `bdist` and `build` commands then internally, so it should check for the dependencies as usual.
