### ISSUE TITLE
clim doesn't update after draw

### ISSUE THREAD

**Issue by kingjr** [matplotlib/matplotlib#6352]
I am running under 1.5.1 and am having trouble getting the color limit of a figure when only one bound is given. I think this is a bug, and not and intended feature (it used to work in the past):

```
# no bound given
im = plt.matshow([[1, 2,], [3, 4]])
print(im.get_clim())  # (1, 4)

# only give one bound
im = plt.matshow([[1, 2,], [3, 4]], vmin=0)
print(im.get_clim())  # (1, None)

# draw should update the clim but doesn't
plt.draw()
print(im.get_clim())  # (1, None), expected (1, 4)

# show() updates clim
plt.show()
print(im.get_clim())  # (1, 4)
```

**Comment by tacaswell** [comment]
This is a consequence of an intentional change.  In 1.5 we made `plt.draw` use `canvas.draw_idle` under the hood which defers the _actual_ rendering until it needs to end up on the screen.  This is a performance feature (to not waste cpu cycles rendering an image that will never make it to the screen/file).

If you really need to force the canvas to render you can do

```python
fig = plt.gcf()
# or better
fig, ax = plt.subplots()
fig.canvas.draw()
```

**Comment by kingjr** [comment]
ok thanks!
