### ISSUE TITLE
function to raise plot window to the front?

### ISSUE THREAD

**Issue by stevengj** [matplotlib/matplotlib#6378]
Somewhat related to #596, it would be good to have a function, analogous to [Matlab's shg](http://www.mathworks.com/help/matlab/ref/shg.html), to bring a desired plot window to the front.

This was discussed [on StackOverflow](http://stackoverflow.com/questions/8202228/make-matplotlib-plotting-window-pop-up-as-the-active-one), but the only solution there was to use a `raise_` method that seems to be specific to the Qt backend.

**Comment by h44rd** [comment]
Hello! I would like to contribute to this project and start off with this issue. Since I'm very new to Github and contributing to open source, I would really appreciate some help to get started. Thanks in advance!

**Comment by tacaswell** [comment]
I do not want to dissuade you from contributing, but this may not be the best starter project as it involves a messy part of the code base and touches multiple GUI toolkits + OS.

**Comment by fariza** [comment]
Just to keep track of what is already merged

- [X] Gtk
- [X] Gtk3
- [ ] Qt4
- [ ] Qt5
- [ ] Tk
- [ ] Wx

**Comment by jenshnielsen** [comment]
For qt4/5 https://github.com/matplotlib/matplotlib/pull/6384

**Comment by fariza** [comment]
@h44rd I guess you decided for this particular issue because you have some experience in GUI frameworks.
Am I right?
If yes, try modifying the Tk or Wx backend to raise the window on show. 
If you don't have experience with GUI frameworks, I really recommend going for something a little bit less complex to start. Start with the low hanging fruit issues https://github.com/matplotlib/matplotlib/issues?q=is%3Aopen+is%3Aissue+label%3A%22low+hanging+fruit%22

In any case, to get the basics of github + matplotlib development follow http://matplotlib.org/devel/gitwash/git_development.html for me that text was of great help, if you have any questions, don't hesitate, just open another issue an tag me in it, so I will get notified

**Comment by stevengj** [comment]
For Tk, see: http://stackoverflow.com/questions/1892339/how-to-make-a-window-jump-to-the-front

**Comment by richardsheridan** [comment]
@tacaswell despite the comment by @fariza and label from @dstansby this appears to work fine for Tk, also see the current [FigureManagerTk](https://github.com/matplotlib/matplotlib/blob/627dd18e18cfb8e157fdc65ddae964a3ea0a4ece/lib/matplotlib/backends/_backend_tk.py#L461) which was added with the [tkcairo backend](https://github.com/matplotlib/matplotlib/blame/bdeb21e9db6a70405a9ef771a42e497a7d0e6784/lib/matplotlib/backends/_backend_tk.py#L553).

The GUI/tk label should be removed.

**Comment by oscargus** [comment]
It seems like this is fixed in Wx as well. If the rcParams `figure.raise_window` is set, `show` can be called to raise the window. See #15440
