### ISSUE TITLE
clabels plotting outside of projection limb

### ISSUE THREAD

**Issue by mikecharles** [matplotlib/matplotlib#6436]
- OS: Mac OS 10.11.4 (El Capitan)
- Matplotlib version: 1.5.1
- Basemap version: 1.0.7
- Both installed via anaconda

The issue is that when I plot data over a basemap, and the region plotted is a subset of the globe, calling `matplotlib.pyplot.clabel` will place some clabels outside of the projection limb. I'm assuming it's because pyplot will create all the clabels first, and then plot the appropriate subset of data.

To illustrate this issue, [here's](https://gist.github.com/mikecharles/47e8cec98c56d34e60d69c5b124beb03) a Jupyter notebook. The plot of the masked data represents the plot I would have expected pyplot to produce in the first place. If I choose to plot a small subset of data, clabels should be place on all visible contours, regardless of what region I plot.

**Comment by tacaswell** [comment]
This should probably be reported against `basemap`.

I suspect it is not an order issue, the code that decides where to put labels may not be checking if they would be visible.

The code for this lives at https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/contour.py#L58
if you would like to take a crack at this!

**Comment by WeatherGod** [comment]
This might actually be fixed on basemap's master as of a few days ago.
On May 16, 2016 7:33 PM, "Thomas A Caswell" <notifications@github.com>
wrote:

This should probably be reported against basemap.

I suspect it is not an order issue, the code that decides where to put
labels may not be checking if they would be visible.

The code for this lives at
https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/contour.py#L58
if you would like to take a crack at this!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/matplotlib/matplotlib/issues/6436#issuecomment-219579067>

**Comment by mikecharles** [comment]
Thanks @WeatherGod, do you know what PR that was? If this was fixed, would the milestone be the next release instead of 2.1?

**Comment by WeatherGod** [comment]
It would have been matplotlib/basemap#290

Keep in mind that basemap is on its own release "schedule" (I use the term extremely loosely here) separate from matplotlib. The next release will be version 1.1.0 -- keeping in mind that the last release was 4 years ago. Development has picked up in the past 6 months, but I have been hard-pressed to find time to actually do a release. So, I'd suggest working off of master for the time being.

**Comment by WeatherGod** [comment]
If you find that the clabels are still outside the projection limbs (quite possible, since I wasn't considering them at the time), do open a new issue over at basemap's issue tracker.

**Comment by mikecharles** [comment]
Thanks @WeatherGod I've opened an issue against `basemap`, since the basemap master still doesn't fix the issue.
