### ISSUE TITLE
Hexbin with log scale takes extent range as logarithm of the data along the log axis

### ISSUE THREAD

**Issue by kgabor** [matplotlib/matplotlib#6479]
```
X=np.arange(1.,100.,0.1)
Y=1.1**X

plt.figure()
plt.hexbin(X,Y,yscale='log',mincnt=1,extent=[1,50,10,100])
# 
plt.figure()
plt.hexbin(X,Y,yscale='log',mincnt=1,extent=[1,50,1,2])
```
The first plot shows an y range from 10\*\*10 .. 10\*\*100 with an empty plot. The second one shows the 
range in 10..100 along the y axis. Is this the intended behavior of the extent keyword arg?

Matplotlib version 1.5.1 , Python version 3.4.4, Platform Ubuntu 14.04 LTS

**Comment by tacaswell** [comment]
Interesting. 

The docs on `extent` are a bit ambigious

```
        *extent*: [ *None* | scalars (left, right, bottom, top) ]
           The limits of the bins. The default assigns the limits
           based on gridsize, x, y, xscale and yscale.
```

But if you look at the code it is intentional (if either scale is log the log of the input is taken an the top and then things proceed normally and the limits are exponentiation).

Could you put in a PR updating the docstring to be clearer?  I think updating the `xscale` and `yscale` entries would be best.
