### ISSUE TITLE
2.0 beta: Boxplot patches zorder differs from lines

### ISSUE THREAD

**Issue by Tillsten** [matplotlib/matplotlib#6510]
See the example from the devdocs:

http://matplotlib.org/devdocs/examples/statistics/boxplot_color_demo.html

The patches are behind the grid while the lines are in front of it.
Maybe patches should be in front of grid by default also, which i 
think is the more common case.

**Comment by efiring** [comment]
@Tillsten would you like to submit a PR?  I think there are two possible ways to address it: either make the default grid lines zorder below patches and then explicitly set the zorder for filled contours (patch collections) and probably others to be above, or leave the default grid lines zorder where it is and elevate the boxplot patches.  My preference is for the second option because I suspect that there will be common cases in addition to filled contours (bar plots? Histograms? Step-filled plots?) where having the patches above the grid will not be what users intend.
Part of the problem here is that the switch from dashed to solid grid lines made them more prominent and obtrusive.  That is the reason I moved them behind lines.  My rationale for leaving them above patches was that patches are often big (or cover everything, as in the contourf case), so putting the grid behind them would defeat the purpose of having a grid.  This is also the reason that the grid is above images.

**Comment by jenshnielsen** [comment]
fixed by #6766

**Comment by tacaswell** [comment]
attn @Tillsten do you agree that this is fixed?

**Comment by Tillsten** [comment]
Yes, would have totally do the same, set eqaul zorder with small delta!
