### ISSUE TITLE
Feature request: contourf to produce solid polygons as well as isobands

### ISSUE THREAD

**Issue by systemed** [matplotlib/matplotlib#6579]
contourf currently produces isobands - a polygon representing the area between (say) 100m and 200m in the input data. This is used by [isobands_matplotlib.py](https://github.com/rveciana/geoexamples/tree/master/python/raster_isobands) to create polygons from raster elevation data, and in my experience produces better polygons, faster, than any other solution I've found.

For many uses, it's preferable to have complete polygons rather than isobands: in other words, a polygon representing all land above 100m, rather than just that between 100m-200m.

This is trivially patchable in matplotlib by using the `_get_lowers_and_uppers` method in `contour.py`. The `uppers` array needs simply to be set to the highest possible value. For my purposes, I've added a quick-and-dirty `uppers = [10000]*len(uppers)` before the `return` (10000m being higher than Everest!), though I guess `inf` would be more correct.

It would be good to have this as an option to contourf rather than having to patch the code.

**Comment by tacaswell** [comment]
attn @efiring 

One concern that comes to mind immediately is that this introduces a z-order dependency (or the polygons need to have holes in them) to account for wells.  I might be confused though.

**Comment by WeatherGod** [comment]
What matplotlib currently produces are "unstacked" polygons. This is
generally the right choice because if alpha is less than 1, the polygons
don't blend with each other. Event picking would also result in at most one
polygon picked for a given click.

This user is asking for a way to produce "stacked" polygons as an option. I
don't know if messing around with `_get_lowers_and_uppers()` is the right
way to achieve this, but if it is that simple, then it might be worth
investigating further as an option. Some other things to consider are input
images that are integers or some other data type which may not have a
concept of Inf (but I think everything gets converted to floats under the
hood, though). Also, it might be worth double-checking how this behaves for
tricontourf(), but I don't think it'll break there, either.

**Comment by tacaswell** [comment]
I am going to close this as there are good reasons we render filled contours the way we do (primarily so that alpha <1 works) and we do not want to support people using Matplotlib as a contour computation library.

To compute contours we now suggest using https://github.com/contourpy/contourpy (which we now depend on for all of our contour computation!) instead.
