### ISSUE TITLE
BUG: saving image to png changes colors

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6607]
On v2.x, (qtagg backend on OSX) run:
```python
import numpy as np
import matplotlib.pyplot as plt

small_im = np.array([[0.25, 0.75, 1.0], [0.1, 0.65, 0.5],
                     [0.6, 0.3, 0.0]])

fig, ax = plt.subplots()
ax.imshow(small_im, interpolation='nearest')
fig.savefig('t1.png')
fig.savefig('t1.pdf')
plt.show()
```
Consider the yellow block in the upper RH corner.  Using the OSX DigitalColor Meter, the color is (253, 231, 36).  Now use Preview to look at the two saved files.  The color in the pdf is the same as in the figure window, but the color in the saved png is (252, 229, 63), and visibly differs from the color in the pdf and on the screen.
I ran into this while trying to fix #6591.

**Comment by QuLogic** [comment]
This may be your viewer playing tricks with you by applying an ICC profile to the image. I'm seeing a similar thing here, with a little different value (253, 230, 38), _but_ if I open the PNG in GIMP and check the square then the value is correct.

Now maybe we can set a different colour profile in the PNG, but I'm not sure if we can avoid the colour correction entirely.

**Comment by efiring** [comment]
@QuLogic Thanks.  I think my problem originates with using preview to make the static png from the pdf.  I'm testing now with using convert instead.

**Comment by efiring** [comment]
Problem solved.  In making the static png image from the pdf for interpolation_none_vs_nearest.py, the following works:
```
convert -density 80x80 None_vs_nearest-pdf.pdf None_vs_nearest-pdf.png
```
Using Apple's preview does not; it applies a correction such that the static png no longer matches the png generated directly by mpl.

**Comment by felker** [comment]
Sorry to revive an old thread, but I am a bit stumped on this. I am writing identical (rasterized) `pcolormesh()` output to both a `.pdf` and `.png` file. The colors of the PDF are much lighter when viewed in Apple Preview.app, Adobe Reader, etc. versus the colors of the PNG file viewed in Preview.app. 

They appear identical when viewed in Google Chrome, GIMP, etc. Probably because the default color profile is sRGB for these applications (unlike the PDF viewers), and the PDF file does not have an embedded ICC profile. 

There was a discussion in 2007 about adding an option to matplotlib to render PDFs with embedded ICC profiles or as PDF/X-3: https://sourceforge.net/p/matplotlib/mailman/message/10699395/
but it seems that nothing has come of it. 

Converting my PDF image to PDF/X-3 seems to fix the color discrepancy in the PDF viewers, but I wonder if there is a better way to maintain color consistency between PDFs and PNGs rendered by matplotlib.
