### ISSUE TITLE
DOC: gallery supplies 2 pngs, neither of which is default

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6636]
The gallery generates a png and a high-res png, but neither is at the default dpi so neither shows what one would see if running the example directly.  
I suggest simplifying the gallery to supply a single png at the default dpi.

**Comment by tacaswell** [comment]
:+1:

**Comment by afvincent** [comment]
I would like to advocate for still supplying a high-res png in the gallery. *Of course along with a png at the default dpi as @efiring  suggested.* 

I often find it frustrating when I see a nice example in the gallery, with a part I want to to have a closer look, and that I have to copy-paste and run the source code on my computer to zoom in, instead of just displaying the higher-res png from the web gallery. 

I don't know however if there is a bandwidth issue with supplying “high-res” files (like at 200 or 300 dpi instead of the default 100 dpi)…

**Comment by efiring** [comment]
Doesn't the pdf serve that purpose?

**Comment by afvincent** [comment]
@efiring I apologize, lately I've been mainly looking at the devdocs version of the gallery, which only supplies “low-res” png files and I totally forgot that there is also a pdf on the non-devdocs gallery. In that case, why you suggested totally makes sense and my previous comment doesn't…
