### ISSUE TITLE
Qt window does not give accurate maximum size

### ISSUE THREAD

**Issue by ekipmanager** [matplotlib/matplotlib#6661]
Just updated to Matplotlib 1.5.1 and had to change my code to resize window, using

```
fig_manager = plt.get_current_fig_manager()
fig_manager.window.resize(16777215, 16777215) 
```

with big numbers crashes the kernel. I got the numbers using fig_manager.window.maximumHeight() (same for width) even with slightly smaller numbers doesn't work. It tries to maximize and then crashes.
- [ ] Matplotlib 1.5.1, Python 2.7.11, Linux Fedora 23
- [ ] I pip installed matplotlib

**Comment by tacaswell** [comment]
Which backend are you using (I assume one of the qt ones?) and which binding?

This used to work?

I can reproduce this, I suspect the issue is that the maximum sizes are bogus (I do not think there is a screen which is 16,777,215px in either direction).

mpl is trying to render a huge image (~1.5million inches x 1.5million inches) and something is segfaulting.

**Comment by tacaswell** [comment]
It looks like that by default those values are just 'big' place holders: http://doc.qt.io/qt-4.8/qwidget.html#maximumSize-prop

**Comment by ekipmanager** [comment]
Yes I suspected the values are too big, I was using something like `    fig_manager.resize(fig_manager.window.maxsize()[0], fig_manager.window.maxsize()[1])
` so it would be great if the code checks the actual size and clip the values so it does not crash.
I am using Jupyter QtConsole 4.1.1 with Qt4Agg backend

**Comment by tacaswell** [comment]
Probably the right place to do this is to over-ride the maxsize to be aware of the Agg raster limit (2**16 on a side iirc) and the current figure DPI.

**Comment by tacaswell** [comment]
#6666 will prevent the segfault, but leaving this open and pushing the milestone out to update the widget.

**Comment by tacaswell** [comment]
This now does:

```
In [3]: import matplotlib.pyplot as plt

In [4]: fig_manager = plt.get_current_fig_manager()
   ...: fig_manager.window.resize(16777215, 16777215)

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/matplotlib/backends/backend_qt.py", line 468, in _draw_idle
    self.draw()
  File "/usr/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 394, in draw
    self.renderer = self.get_renderer()
  File "/usr/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 384, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/usr/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 411, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/usr/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 84, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi)
ValueError: Image size of 24466686x24466629 pixels is too large. It must be less than 2^16 in each direction.
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
File /usr/lib/python3.10/site-packages/matplotlib/backends/backend_qtagg.py:50, in FigureCanvasQTAgg.paintEvent(self, event)
     48 # create a buffer using the image bounding box
     49 bbox = Bbox([[left, bottom], [right, top]])
---> 50 buf = memoryview(self.copy_from_bbox(bbox))
     52 if QT_API == "PyQt6":
     53     from PyQt6 import sip

File /usr/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py:386, in FigureCanvasAgg.copy_from_bbox(self, bbox)
    384 def copy_from_bbox(self, bbox):
    385     renderer = self.get_renderer()
--> 386     return renderer.copy_from_bbox(bbox)

MemoryError: In copy_from_bbox: Out of memory
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
File /usr/lib/python3.10/site-packages/matplotlib/backends/backend_qtagg.py:50, in FigureCanvasQTAgg.paintEvent(self, event)
     48 # create a buffer using the image bounding box
     49 bbox = Bbox([[left, bottom], [right, top]])
---> 50 buf = memoryview(self.copy_from_bbox(bbox))
     52 if QT_API == "PyQt6":
     53     from PyQt6 import sip

File /usr/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py:386, in FigureCanvasAgg.copy_from_bbox(self, bbox)
    384 def copy_from_bbox(self, bbox):
    385     renderer = self.get_renderer()
--> 386     return renderer.copy_from_bbox(bbox)

MemoryError: In copy_from_bbox: Out of memory
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
File /usr/lib/python3.10/site-packages/matplotlib/backends/backend_qtagg.py:50, in FigureCanvasQTAgg.paintEvent(self, event)
     48 # create a buffer using the image bounding box
     49 bbox = Bbox([[left, bottom], [right, top]])
---> 50 buf = memoryview(self.copy_from_bbox(bbox))
     52 if QT_API == "PyQt6":
     53     from PyQt6 import sip

File /usr/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py:386, in FigureCanvasAgg.copy_from_bbox(self, bbox)
    384 def copy_from_bbox(self, bbox):
    385     renderer = self.get_renderer()
--> 386     return renderer.copy_from_bbox(bbox)

MemoryError: In copy_from_bbox: Out of memory
```

with 3.7.1.  I think the issue is still that we are not resizing the Qt window down to something that would fit on the screen.  However, I'm not sure that there is anything we should do here.  The user has asked for something that is ~impossible and sorting out how to clip the requested size to is a bit ambiguous (do we clip to 2^16 which is what Agg will render, clip to available memory, clip to available screen size (and in those two cases how do we reliably _get_ the values to cilp to?)).

As the OP points out we already have a "full screen" functionality (that is cross UI toolkit) and is probably a better solution for a vast majority of our users.  The set of people who where that is _not_ the right solution are likely embedding us in their own UI and in that case we should not be helpful and let them deal with the resource limitations in what ever way in right for their application.
