### ISSUE TITLE
2.0 dev legend breaks on scatterplot

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#6685]
With the changes to legend introduced with #6424, it can be really hard to differentiate the legend from the scatter points: 

![index](https://cloud.githubusercontent.com/assets/1300499/16551438/ad68b0ca-4186-11e6-8ad4-51391698a69b.png)

This was generated using:
```python
import matplotlib.pyplot as plt
import numpy as np

fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.scatter(np.random.rand(50), np.random.rand(50), label="r1")
ax.scatter(np.random.rand(50), np.random.rand(50), label="r2")
ax.legend(frameon=True, fancybox=True)
```
This code also displays a secondary issue, which is that frameon/fancybox appear to no longer work, so the user can't manually rectify the issue. 

@tacaswell suggested that 2.0 introduce a gray background for legend so there's differentiation. Should this be universal? (I dunno if there's a way to inspect the plot type & if it's worth putting that overhead in legend)

**Comment by efiring** [comment]
The problem here is that the meaning of the rcParams is confusing.  By default, `frameon` *is* True, and so is `fancybox`.  The 'frame' actually refers to the background *Patch*, however, which has a facecolor and an edgecolor.  By default the facecolor is inherited from the Axes, and the edgecolor is 'none', so no boundary is drawn.  The 'framealpha' is 0.8, so although the legend and its 'frame" are on top of the plot, the plot elements show through.
To make things even more confusing, legend had no kwargs to control the patch edgecolor and facecolor; apart from controlling them with rcParams, they can only be adjusted directly, like this:
```python
leg = ax.legend()
leg.legendPatch.set_edgecolor('k')
```
I think the solution to this problem is to add edgecolor and facecolor kwargs, and clarify the meanings of kwargs and rcParams, both in the legend docstring and in matplotlibrc.template.

As for the question of the default: the point of dropping the bounding box was to reduce clutter, distraction, and blocking of data; it works fine in many cases, but you correctly point to a case where it doesn't.  Setting edgecolor or facecolor to a pale gray is worth considering as an alternative for the default.  I think that setting just the edgecolor might be the better of these alternatives; I'm not yet sure whether either alternative is a better default than the present one, however.

**Comment by story645** [comment]
> I think the solution to this problem is to add edgecolor and facecolor kwargs, and clarify the meanings of kwargs and rcParams, both in the legend docstring and in matplotlibrc.template.
I'm all for this as an "easier to simplify" things. But, I also think frameon should be `False` by default if the legend default appears to not have a frame, and that setting it `True` should then pop up a frame as users shouldn't have to mess with two or three kwargs to do the thing 1 kwarg says it'll do.

But (and it seems you agree) I think there needs to be an out of the box default that also works well with scatter.

**Comment by efiring** [comment]
@mdboom, how much of a redesign is necessary or desired for a release?  Regarding appearance and functionality, I think that the best modification for addressing the problem with scatter would be to change the edgecolor to gray--minimally intrusive visually, just enough to delineate the legend.  I think that the alternative of making the background itself gray would be more intrusive, and would be less versatile in working with a variety of underlying plots.
I will make a PR.
