### ISSUE TITLE
style.use('classic') differs from defaults in 1.5

### ISSUE THREAD

**Issue by xflr6** [matplotlib/matplotlib#6696]
I would like to use the classic style to make plots look the same across 1.5 and 2 and expected that `plt.style.use('classic')` would basically be a non-op on 1.5 (no visual differences), which does not seem to be the case (but is intended?).

Jupyter notebook with `1.5.2`:
![snap1](https://cloud.githubusercontent.com/assets/6342379/16614505/eafc685e-4371-11e6-8a10-9dfba2503ca8.png)

Gray background and larger with classic style:
![snap2](https://cloud.githubusercontent.com/assets/6342379/16614509/f231f5f8-4371-11e6-90ed-054b25f1fcb0.png)

Trying to reproduce the defaults with rc settings:
![snap3](https://cloud.githubusercontent.com/assets/6342379/16614513/f7c9106e-4371-11e6-90d5-aadb30b982e1.png)

However, the vertical layouts in [1] and [3] still differ a little bit (can they be made byte-identical?).

**Comment by tacaswell** [comment]
The background issue is that the inline backend (which is maintained by IPython/Jupyter) has different defaults than upstream.

Not sure what you mean by 'vertical layout'

attn @Carreau

**Comment by xflr6** [comment]
Thanks: Maybe there is a way to load those defaults in `1.5` and `2`?

The vertical differences: When I compare the two saved `png`-files, (some of) the distances between the ticks on the y-axis in [1] and [2] are slightly different. Though the image size is the same, the plot box in [2] is a little taller (maybe different rounding methods?).

**Comment by afvincent** [comment]
Indeed the y-ticks are not exactly spaced the same in the two png files: 
![vertical_layout_issue](https://cloud.githubusercontent.com/assets/17270724/16619005/8114742a-438c-11e6-8c9a-f7c0cc3d6a59.png)

**Comment by WeatherGod** [comment]
This is likely because the ipython backends applies bbox_inches='tight' by
default and does tight_layout, too, IIRC. Most likely, applying the classic
style might be turning those things off. You won't notice any difference
outside of ipython, though. The 'classic' style is utilized throughout our
test suite so that we wouldn't have to update our test images en mass for
the 2.0 changes. So we know 'classic' style works.

**Comment by tacaswell** [comment]
We should probably exclude the figure face color from the classic style (as it does not get saved and should only be affecting the GUIs).

If you want a 'classic-inline' style sheet, I think that should come from the jupyter team.

**Comment by xflr6** [comment]
Thanks for the hints, I found the wanted settings [here](https://github.com/ipython/ipykernel/blob/master/ipykernel/pylab/config.py#L53-67): with another `plt.rc('figure.subplot', bottom=.125)` the plots are identical.

Yes, a 'classic-inline' style sheet with the said settings would be great: Can `ipykernel` make `mplstyle` files available for use by `matplotlib`?

**Comment by Carreau** [comment]
This overwriting of default is really annoying, and we should definitively find a better way to have our inline backend. Add to the list of things to discuss again at SciPy.

Opened an IPython issue to track that.

**Comment by xflr6** [comment]
A workaround to preserve styling is to simply do `%matplotlib inline` *after* `plt.style.use('classic')`.

**Comment by timhoffm** [comment]
I'm closing this because I don't think we want to invest any time in a better classic compatibility.

Apart from that, the new 'classic' style has been around for so long that it's a de-facto standard of its own. Changing that now would also break some user code (I could even imagine that nowadays more people use the 'classic' style than the original matplotlib 1.5).
