### ISSUE TITLE
DOC: missing second y-axis in `demo_parasite_axes2`

### ISSUE THREAD

**Issue by afvincent** [matplotlib/matplotlib#6836]
It looks like the example [demo_parasite_axes2](http://matplotlib.org/devdocs/examples/axisartist/demo_parasite_axes2.html) lost its “Temperature” second y-axis in the devdocs gallery. See [the non-devodcs version](http://matplotlib.org/examples/axes_grid/demo_parasite_axes2.html) for a comparison.

For those who do not like to click, here are the two PNGs with default dpi:
- _devdocs version_
  ![devdocs_demo_parasite_axes2_00_00](https://cloud.githubusercontent.com/assets/17270724/17132940/3f06a6dc-5324-11e6-8d86-6be2d8911208.png)
- _non devdocs version_
  ![non-devdocs_demo_parasite_axes2_00_00](https://cloud.githubusercontent.com/assets/17270724/17132972/5f071afc-5324-11e6-8bdc-ee025dde2ed1.png)

NB: a diff between the code source of each example results in an empty file.

**Edit**: “twin y-axis” ← “second y-axis”, which should be more correct.

**Comment by afvincent** [comment]
Besides, I do not use that much the `mpl_toolkits` but is it normal that `mpl_toolkits.axisartist` uses “inward” tick marks? (I mean, while mpl defaults are now to use “outwards” tick marks)

**Comment by efiring** [comment]
It works correctly on v2.x...
Tick direction: good point.  If you are looking for a challenge, see if you can figure out what is determining the tick direction and other properties...

**Comment by afvincent** [comment]
@efiring What version of mpl 2.x did you test? On my computer, with mpl `2.0.0b3.post1859+g80a3f3e` (retrieved a few hours ago from GitHub), I get the same picture as in the devdocs gallery, with the second y-axis missing.

I will try to have a look at it, as well as at the tick direction and Cie.

**Comment by efiring** [comment]
In [5]: matplotlib.__version__
'2.0.0b3+23.g18ffa3e'

**Comment by QuLogic** [comment]
This is broken on `master`, but not `v2.x`. Bisect points to d268abf8fd9c41fdc37b9bfeb8b1d576b4b288d3:
```
d268abf8fd9c41fdc37b9bfeb8b1d576b4b288d3 is the first bad commit
commit d268abf8fd9c41fdc37b9bfeb8b1d576b4b288d3
Author: productivememberofsociety666 <productivememberofsociety666@sol.fr.am>
Date:   Fri Aug 14 19:54:02 2015 +0200

    Changed twin* functions so the corresponding host axes are invisible; updated _remove_method.

:040000 040000 27e94ea209af1f49c24fe81628ad97d51f772a11 c1bbecea359621967069ba84b1e81a1ee6ffd2a5 M	lib
```

**Comment by afvincent** [comment]
@QuLogic Thank you for figuring out the bisecting point!

I think I may have found the reason why the 2nd y-axis is not visible after d268abf. For example in `twinx` from `axes_grid1.parasite_axes.py`,  one has (the comments are my own understanding of the code):
-  before:
```python
# 1/ Deactivate the right side of the parent axis, but its line.
self.axis["right"].toggle(all=False)
self.axis["right"].line.set_visible(True)

# 2/ Hide all the sides of the parasite axe but the right side.
ax2.axis["right"].set_visible(True)
ax2.axis["left","top", "bottom"].toggle(all=False)
ax2.axis["left","top", "bottom"].line.set_visible(False)

# 3/ Setup the right side of the parasite ax.
ax2.axis["right"].toggle(all=True)  # Do not forget to activate tick & labels!
ax2.axis["right"].line.set_visible(False)  # the one from parent ax is visible
```
- after:
```python
# 1/ Simply make the right side of the parent ax not visible.
self.axis["right"].set_visible(False)

# 2/ Make all sides of the parasite ax not visible but the right one.
ax2.axis["right"].set_visible(True)
ax2.axis["left", "top", "bottom"].set_visible(False)

# 3/ Setup the right side of the parasite ax.
# Empty!
```
and if I add `ax2.axis["right"].toggle(all=True)` in the 3/, then the demo seems to be OK. 

_I did not have time to look carefully to the related PR (#4898) yet_: I cannot tell for the moment that this is not going against the aim of #4898. I will have a better look at this tomorrow or this weekend.

**Comment by smheidrich** [comment]
@afvincent Everything that #4898 was meant to achieve has been put into the ``mpl_toolkits.tests.test_axes_grid1.test_twin_axes_empty_and_removed`` test and is illustrated by the difference between the pictures in [this comment](https://github.com/matplotlib/matplotlib/pull/4898#issuecomment-131194493). Your proposed change doesn't seem to make the test fail, so it should be fine.

Although I don't really get why it doesn't work the way it is. I think it has something to do with the ``AA.Axes`` class (which I never really understood to be honest and didn't consider when writing #4898 - sorry about that :worried:): if I [remove everything that has anything to do with that class](https://gist.github.com/smheidrich/dab92a6e73fcf284e0723c78a9b4ed77), I at least get both twin axes visible, although of course it looks like garbage because I can't have the offset:
![result image](https://cloud.githubusercontent.com/assets/3827982/17279496/4cb897ae-5775-11e6-9084-125ac2605150.png)

**Comment by afvincent** [comment]
@smheidrich Thank you for the explanations as well as for the experiments :)!

I have played a bit with the test you added in #4898 (doing more or less the same kind of things as you did in gist) and it seemed to me too that the problem has to do with `AA.Axes`. I will try to investigate this in the next few days, to see if there is a deeper ground to the issue, that could also explain the minor issue with tick directions & Cie.

**Comment by smheidrich** [comment]
All right, so to me it seems this comes down to the difference between **axis artists** that are used by the default axes vs ``mpl_toolkits.axisartist.Axes``, specifically what exactly their **``set_visible``** methods do:

- The default ones use [``mpl_toolkits.axes_grid1.mpl_axes.SimpleAxisArtist``](https://github.com/matplotlib/matplotlib/blob/88ce601f18a5b08f2e0ce9d62a74de13ee4bc766/lib/mpl_toolkits/axes_grid1/mpl_axes.py#L77).
  - [``set_visible``](https://github.com/matplotlib/matplotlib/blob/88ce601f18a5b08f2e0ce9d62a74de13ee4bc766/lib/mpl_toolkits/axes_grid1/mpl_axes.py#L109) here automatically calls ``toggle(all=...)``, so **all child elements (labels, ticks, ...) become visible.**
- ``mpl_toolkits.axisartist.Axes``, by contrast, uses [``mpl_toolkits.axisartist.AxisArtist``](https://github.com/matplotlib/matplotlib/blob/88ce601f18a5b08f2e0ce9d62a74de13ee4bc766/lib/mpl_toolkits/axisartist/axis_artist.py#L925)
  - ``set_visible`` isn't explicitly implemented but inherited from the basic [``matplotlib.artist.Artist.set_visible``](https://github.com/matplotlib/matplotlib/blob/88ce601f18a5b08f2e0ce9d62a74de13ee4bc766/lib/matplotlib/artist.py#L832) method, which of course doesn't know about toggling or anything else, so the **child elements that were toggled off stay off.**

So that explains why my code worked for default axes *without* the explicit ``toggle`` call, but not for the ``axisartist`` axes.

I [tested this](https://github.com/smheidrich/matplotlib/commit/b6d4d8b91376174f3368346d3c9fd95aa523470d) by making ``axisartist.AxisArtist.set_visible`` behave like ``axes_grid1.mpl_axes.SimpleAxisArtist.set_visible`` and then ``demo_parasite_axes2.py`` works again, although knowing my luck this probably breaks something else. :P

Also I think the better solution might be to do the exact opposite and make ``axes_grid1.mpl_axes.SimpleAxisArtist.set_visible`` behave like ``axisartist.AxisArist.set_visible``? Or maybe leave both methods as they are? In either case you would then have to add the ``toggle`` code to ``twin*`` like you originally suggested.

But in general one problem with the axes grid toolkit it's that it's so damn inconsistent, so perhaps having at least ``set_visible`` behave the same might be nice.

**Comment by tacaswell** [comment]
:+1: making `set_visible` apply to the children and making AA more consistent.

**Comment by smheidrich** [comment]
@tacaswell It might be better to make it consistent the other way round, i.e. by having ``set_visible`` *not* any toggle children ever. I guess the way to think about it is that ``toggle`` changes the properties of the ``axisartist``. Then ``set_visible`` just determines whether the ``axisartist`` as a whole is shown, whatever its properties (with/without ticks or ticklabels) might be. In more practical terms, I think it's plausible that some people do use ``axisartist``s with e.g. their ticklables turned off as a conscious choice, and they don't expect ``set_visible`` to override this choice. I'm not sure though.

**Comment by QuLogic** [comment]
Was fixed by above PRs.
