### ISSUE TITLE
BUG: endless loop with MaxNLocator integer kwarg and short axis

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#6849]
In v2.x:
```python
fig, ax = plt.subplots()
ax.plot([0.5, 1.5], [1, 2])
ax.locator_params(axis='x', integer=True)
```
This leads to an infinite loop in `MaxNLocator._raw_ticks`.

**Comment by efiring** [comment]
The choices are to allow fewer than 2 ticks (as few as zero) in the integer case, or to expand the viewLim as needed to include at least 2 ticks.

**Comment by tacaswell** [comment]
This is tough.  Expanding the viewLim is bad because we could be over-riding user input, no ticks is bad because that is a useless plot.

**Comment by afvincent** [comment]
Is there a way to warn the user in the case he/she asked for integer ticks but the viewLim is too narrow for displaying any tick? Because _one solution might be to opt for allowing fewer than 2 ticks in the integer case, and throw a warning if in the end there is 0 tick plotted._ That way, one does not override any user input and the user is aware that he might have asked for a “useless” plot (meaning a plot with integer tick positions but with no integer values plotted, for example).

**Comment by efiring** [comment]
There is one more alternative: document the 'integer' kwarg as a *preference* that will be overridden if it would lead to fewer than 2 ticks.  I think this is the way to go.

**Comment by tacaswell** [comment]
backported to v2.x as 9982e40
