### ISSUE TITLE
How to get rid of power button in nbagg backend?

### ISSUE THREAD

**Issue by alexanderwhatley** [matplotlib/matplotlib#6896]
Matplotlib version 1.5.1, Windows 10.

Is there a way to get rid of the power button created by a graph in the nbagg backend. There is no documentation on this at all.

```
import matplotlib
matplotlib.use("nbagg")
import matplotlib.pyplot as plt

plt.plot([1,2,3],[4,5,6])
plt.show()
```

![image](https://cloud.githubusercontent.com/assets/14192598/17382048/e469c36a-5983-11e6-8ffb-7e01b231cba8.png)

**Comment by QuLogic** [comment]
If you don't want it to be interactive, you can use the inline backend instead of nbagg.

**Comment by alexanderwhatley** [comment]
No, I want it to be interactive. I was just giving a reduced example.

**Comment by WeatherGod** [comment]
The power button is what ends the interactivity. If you press it, the
figure is then saved to your notebook as-is. The button should then
disappear. Similar to the X button in many windows (in the sense that it
ends interactivity), but different in that you can still see the figure. It
used to be an X, but others advocated for a different icon because it
didn't get rid of the figure, so we are left with a power button instead.

**Comment by tacaswell** [comment]
On the notebook side the figure is built of out of a bunch of js tied to some divs.  I am pretty sure some clever css can hide it (but said cleverness is beyond me).

**Comment by QuLogic** [comment]
The button does not have a specific class, but as it is the only button in the titlebar, it can be styled away with:
```css
.ui-dialog-titlebar button {
  display:none;
}
```
