### ISSUE TITLE
pcolorfast results in invalid cursor data

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6905]
mpl2.0b3 (and likely ever since `get_cursor_data` exists).
The PcolorImage class does not redefine the `get_cursor_data` method, so it displays incorrect cursor data:
```
In [1]: plt.gca().pcolorfast([0, 1, 3], [0, 2, 3], np.arange(4).reshape((2, 2)))
```
then hover the cursor over the image to see incorrect values in the status bar.

**Comment by anntzer** [comment]
By the way, the NonUniformImage class suffers from the same problem.  This is less obvious from the example (`pylab_examples/image_nonuniform.py`) as it directly adds the image to `ax.image`, so the image is not added to the mouseover set.  But switching these lines to use `ax.add_image(im)` reveals the same issue.

**Comment by efiring** [comment]
Yes, I'm aware of that, but it is lower priority because as far as I know we have no direct `Axes` interface like `pcolorfast` to the NonUniformImage class; I suspect it is rarely if ever used.  (I don't know how much use pcolorfast gets, for that matter; I wrote it because I wanted it, and I use it, but maybe no one else does.) Also, handling the data cursor for PcolorImage is fast and easy.  It's not so obvious to me how to handle NonUniformImage.
