### ISSUE TITLE
Cleanup of event handling examples

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#6906]
- [x] http://matplotlib.org/devdocs/examples/event_handling/idle_and_timeout.html should just be removed?  (funnily the note about being only tested on gtk is probably incorrect as idle_event only works on wx)

- [ ] http://matplotlib.org/devdocs//examples/event_handling/pipong.html seemingly does nothing, even after adding `Game(plt.gca()); plt.show()`

- [x] http://matplotlib.org/devdocs/examples/event_handling/pong_gtk.html seems to work at the beginning but the game cannot actually be played; a traceback is displayed upon exit.

- [x] http://matplotlib.org/devdocs/examples/event_handling/resample.html is technically fine but the resampling choice is a bit puzzling; I'd expect _up_sampling of the data upon zooming rather than downsampling.

**Comment by afvincent** [comment]
I find the last example puzzling too. Here is what a [modified version](https://gist.github.com/afvincent/cfca2e58cc8d9f6f97103086e93e8815) of this example could look like. It downsamples the data if there are too many samples too display and display all the data when zoom is high enough.

**Comment by anntzer** [comment]
The resample example is still a bit weird...

**Comment by timhoffm** [comment]
Only the pong example does still exists, but is not working. https://matplotlib.org/devdocs/gallery/event_handling/pong_sgskip.html

While it's a "fancy" usage example, IMHO it's not essential. Practical teaching is more effective with real-world-like use cases. Creating a game is not a core use case for matplotlib, so everything that could be learned in here is likely better taught by other examples. Because this is currently not working, I suggest to just delete it - unless there are volunteers to fix it.

**Comment by anntzer** [comment]
Actually the example is working for me?

**Comment by timhoffm** [comment]
You are right. (Copy&paste error).

In that case I propose to just leave it and close the issue.

**Comment by anntzer** [comment]
Yup, everything is working now.
