### ISSUE TITLE
ax.vlines adds unwanted padding, changes ticks

### ISSUE THREAD

**Issue by myyc** [matplotlib/matplotlib#6953]
Hi. I understand this is a cosmetic feature and it's often a good thing (I'm all for aesthetics) but sometimes this functionality comes at the expense of other stuff

    from matplotlib import pyplot as plt

    f, (a1, a2) = plt.subplots(1, 2)
    a1.plot([1.1,2,2.9])
    a2.plot([1.1,2,2.9])
    a2.vlines(1, *a2.get_ylim())

This code produces two plots, the right one has some padding on top (and completely different ticks). There should be an option to disable it. Not sure whether it has to do with the `hold` feature (which is `True` by default so if that's the issue then it's ignored).

**Comment by jenshnielsen** [comment]
Im not completely sure that I understand your issue but it sounds to me like what you want is to use `axvline` which is deigned to span the entire view without changing the limits


```
from matplotlib import pyplot as plt

f, (a1, a2) = plt.subplots(1, 2)
a1.plot([1.1,2,2.9])
a2.plot([1.1,2,2.9])
a2.axvline(1)
plt.show()
```

**Comment by myyc** [comment]
I didn't know that, my bad. So yeah that would help my case, but why would `a2.vlines(1, *a2.get_ylim())` change the limits?

**Comment by jenshnielsen** [comment]
I assume that this is with 2.0 betas since the logic for this has changed and I can't reproduce the issue with 1.5. In the future please include matplotlib version in your bug report. There is a reason that we ask for it in the issue template!

Why should it not. Autolim does it's best to ensure that all you plot is within the limits that is regardless of what you plot. In the case of a vertical line the end points may be significant but if it ends at the edges there is no way of knowing from the plot if it's clipped or actually ends there.

**Comment by myyc** [comment]
It is with the betas. Not sure why it would be a bad idea to (optionally) disable autolim for vline then.

**Comment by jenshnielsen** [comment]
Because:

* There is already another function that does what you want.
* If we add it to this we should also add it to plot, scatter ...
* We already have way to many methods with way to many keyword arguments making apis to complicated.

**Comment by myyc** [comment]
OK, understood
