### ISSUE TITLE
Docstring for ArtistAnimation is incorrect

### ISSUE THREAD

**Issue by typograph** [matplotlib/matplotlib#6964]
The docstring for the [ArtistAnimation](http://matplotlib.org/api/animation_api.html#matplotlib.animation.ArtistAnimation) class mentions `frame_info`, although the argument to the constructor is called `artists`. I would suggest changing the argument name back to `frame_info`, as `artists` makes one think this should be a simple collection.

**Comment by dopplershift** [comment]
Changing the name of the parameter would technically be an API break, since someone could be passing it as a keyword argument. I'd be happy to take a Pull Request to fix the docstring and change `frame_info` to `*artists*` (asterisks should be there as well since it's documenting the method parameter).
