### ISSUE TITLE
Text ignores rotational part of transformation

### ISSUE THREAD

**Issue by stefanv** [matplotlib/matplotlib#698]
When specifying a transformation to `plt.text`, the rotational part of the transformation is ignored.  I'm aware of the `rotation` keyword, but in my use case, I need some more fine-grained control.

Here's an example, in which a box and text receives the same transformation, but displays differently:

``` python
from matplotlib import patches, transforms
import matplotlib.pyplot as plt
import numpy as np

ax = plt.gca()

theta = np.deg2rad(30)
S = np.sin(theta)
C = np.cos(theta)
R = transforms.Affine2D(matrix=np.array([[ C, -S, 0.5],
                                         [ S,  C, 0.5],
                                         [ 0,  0, 1.]]))

rect = patches.Rectangle((0, 0), 0.5, 0.1, transform=R + ax.transData)
text = plt.text(0, 0, 'hello', size=50, transform=R + ax.transData)

ax.add_patch(rect)

plt.show()
```

**Comment by story645** [comment]
@bearstrong are you still working on this?

**Comment by immaxchen** [comment]
My proposal is to add a Boolean argument to `Text`, say, something like `transform_rotation_too` (just kidding, for illustration only), if it is set to True, then we transform the rotation angle accordingly, otherwise, the rotation angle stays. Does it make sense?

![image](https://user-images.githubusercontent.com/26521816/67588488-d30d7c00-f788-11e9-95ff-5f36c103cb7b.png)

**Comment by immaxchen** [comment]
Have sent a PR to address this issue, not quite sure if this is the way you want to do it.

**Comment by QuLogic** [comment]
The linked PR #15532 adds an option enabling this.
