### ISSUE TITLE
plt.annotate(): segmentation fault when coordinates are too high

### ISSUE THREAD

**Issue by FilipDominec** [matplotlib/matplotlib#6984]
- [x] Matplotlib version 1.5.1-1ubuntu1, Python version2.7.12, Platform Ubuntu 16.04 x64
- [x] I installed Matplotlib and Python from apt repository
- [x] Example:

```
#!/usr/bin/env python
import matplotlib.pyplot as plt
plt.annotate('blah',  xy      = (1e6, 1),  xycoords  ='data')  ## 1e6 or more causes the crash.
#plt.xlim((0, 2e12))                                       ## does not help
plt.savefig("output.png", bbox_inches='tight')
```

Returns:
```
filip@comp:/tmp/$ python a.py 
Segmentation fault (core dumped)
```

A workaround is to establish the plot limits before the use the plt.annotate(), and call the command conditionally only if it fits into the view. But this surely is not the way Matplotlib should work (and localizing this source of crashes also took quite a long time, since the corresponding code was embedded in a 2000-line simulation script that worked until today).

**Comment by tacaswell** [comment]
The segfault is fixed in 604e06eaa82bb04f33f19961ed871525dd5419b9 (and backported to 1.5.x as 84f3a6f ).  Trying to make too-big figures now raises instead of segfaulting.

If I set the limit (on current master) I can not reproduce the issue with master or 1.5.1.

There are a couple of overlapping issues here:

 - by default the `Annotation` artists are not clipped to the axis
 - you are using `bbox_inches='tight'` which resizes the figure to fit all of the artists

As a work around I suggest either passing `clip_on=True` to `annotate` or not using `bbox_layout='tight'`.

Closing this as the segfault is fixed and the other behavior is correct (if annoying).

**Comment by FilipDominec** [comment]
OK, thank you.

**Comment by tacaswell** [comment]
Your welcome, sorry I do not have a better answer for you.

**Comment by WeatherGod** [comment]
I noticed your initial statement " it also takes quite a long time to
establish which part of 2000-line simulation script causes the segfault"

A really useful tool that is now in the standard library is "faulthandler":
https://docs.python.org/3/library/faulthandler.html#example

It has saved me lots of time when I used to just add print statements
everywhere to find the fault.

**Comment by FilipDominec** [comment]
@WeatherGod Excellent tip! I believed that there is no way to get any info on segfaults when they happen.
