### ISSUE TITLE
autoscale does not work for axes added by fig.add_axes()

### ISSUE THREAD

**Issue by barpaum** [matplotlib/matplotlib#7070]
- Matplotlib version: 2.0.0b4+1.g4e507ae, Python version: 3.5.2 and Platform: Ubuntu 16.04 64bit 
- Matplotlib from source and Python is shipped with system
- If you run the code either within "ipython3 --pylab" or within a cli, the ax.autoscale() fuction does not work. But strangely, it works inside jupyter or just change "add_axes" to "add_subplot".

```python
import matplotlib as mpl
import matplotlib.pyplot as plt
fig = plt.figure()
xmin=0
xmax=1.6
ymin=0
ymax=1.6
ax = fig.add_axes([xmin,ymin,xmax-xmin,ymax-ymin])
#ax=fig.add_subplot(111)
l=mpl.lines.Line2D([xmin,xmax],[(ymin+ymax)/2,(ymin+ymax)/2])
ax.add_line(l)
ax.autoscale()
print(type(ax))
plt.show()
```

From "ipython3 -pylab"
![screenshot from 2016-09-09 15-41-56](https://cloud.githubusercontent.com/assets/3433058/18379353/b2b2fe8e-76a4-11e6-9ed7-c20a8c6a1e04.png)

from "jupyter notebook"
![index](https://cloud.githubusercontent.com/assets/3433058/18379415/06777a22-76a5-11e6-99db-702202c47c05.png)

**Comment by tacaswell** [comment]
It looks like something else is going wrong in the desktop case as the axis is not visible either.

Which backends are you using in the two cases?

**Comment by tacaswell** [comment]
The ploblem is that you are using `fig.add_axes` wrong.  The inputs are the location and size of the `Axes` in figure fraction uints.  Thus, you have put the lower left of the axes (which is the lower left of visible data-space) at the lower left of the figure (hence you see no ticks) and then made the axes bigger than the figure (1, 1 is the top right and you are setting the axes to be 1.6 figure fractions wide / tall).

It looks like it works in the notebook because you are using the inline backend which creates the png with the `bbox_inches='tight'` kwarg to savefig which effectively 'shrink wraps' the figure. 

If you get the `ax.get_xlim()` and `ax.get_ylim()` before and after the call to `autoscale` you will see that it is doing it's job.

Why are you creating Line2D objects directly rather than using `ax.plot`?

**Comment by barpaum** [comment]
It's amazing. Your answer just solved the problem! Thanks!
I'm not patient enough to notice the meaning of the argument of add_axes is ratio other than absolute coordinate.
By the way, my backend for cli is "Qt4Agg".
I'm creating Line2D objects as I'm trying to create interactive applications with matplotlib and I need deeper understanding of the hierarchy of matplotlib other than just using matlab style code.
