### ISSUE TITLE
Using a linestyle cycler with plt.errorbar results in strange plots

### ISSUE THREAD

**Issue by Chroxvi** [matplotlib/matplotlib#7074]
If the linestyles used in a `plt.errorbar` plot are adjusted manually, results are as expected. However, when using a `linestyle` cycler, the linestyles are simply ignored whereas using a `ls` cycler results in errorbar end points being connected by lines.

Consider the following minimal example

``` python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from cycler import cycler

x = np.arange(0.1, 4, 0.5)
y = np.exp(-x)
offsets = [0, 1]


linestyles = ['-', '--']

plt.figure()
for offset, linestyle in zip(offsets, linestyles):
    plt.errorbar(x, y + offset, xerr=0.1, yerr=0.3, ls=linestyle, color='b')
plt.title('manual plots')
plt.savefig('manual_plots.png')


linestyle_cycle = cycler('linestyle', linestyles)
mpl.rcParams['axes.prop_cycle'] = linestyle_cycle

plt.figure()
for offset in offsets:
    plt.errorbar(x, y + offset, xerr=0.1, yerr=0.3, color='b')
plt.title('Linestyle cycler plots')
plt.savefig('linestyle_cycler_plots.png')


ls_cycle = cycler('ls', linestyles)
mpl.rcParams['axes.prop_cycle'] = ls_cycle

plt.figure()
for offset in offsets:
    plt.errorbar(x, y + offset, xerr=0.1, yerr=0.3, color='b')
plt.title('ls cycler plots')
plt.savefig('ls_cycler_plots.png')
```

which produces the following set of figures

![manual_plots](https://cloud.githubusercontent.com/assets/5367057/18388683/e20efd1a-76a2-11e6-8c96-364205a656b0.png)
![linestyle_cycler_plots](https://cloud.githubusercontent.com/assets/5367057/18388687/e670a52a-76a2-11e6-8f56-9c01664443c0.png)
![ls_cycler_plots](https://cloud.githubusercontent.com/assets/5367057/18388690/e93dad52-76a2-11e6-8883-d2a526cab9d1.png)

I ran the above example using Anaconda 4.1.1 with Python 3.5.2 and Matplotlib 1.5.1 on Linux.

**Comment by WeatherGod** [comment]
I believe this was fixed in subsequent versions of matplotlib v1.5.x
branch. Note that we are right now trying to get Continuum to push out a
v1.5.3 package through conda which was tagged last night. For some reason,
conda never picked up v1.5.2 (but I don't remember if that release
contained the needed fixes for this).

**Comment by QuLogic** [comment]
The same set of figures is produced with 1.5.3. On the `v2.x` branch, both `linestyle` and `ls` cyclers produce the same results, though I'm not sure they're the _expected_ results.
![manual_plots](https://cloud.githubusercontent.com/assets/302469/18401561/10fc9078-76a9-11e6-9350-6fa1580bc40e.png)
![linestyle_cycler_plots](https://cloud.githubusercontent.com/assets/302469/18401567/13dd758c-76a9-11e6-9ded-a545a061ab35.png)
![ls_cycler_plots](https://cloud.githubusercontent.com/assets/302469/18401570/15f9a9ee-76a9-11e6-8949-6cf84ff0bf92.png)

**Comment by WeatherGod** [comment]
Hmm, I wonder if the plot() calls inside of errorbar() might be mishandling
some things...

The ls cycler image using 1.5.1 shows that the ls cycler is being used for
the plot()'s of the errorbar markers. This is obviously incorrect, and is
somehow fixed in v2.x. The next problem is how to get the main plot() call
to utilize the cycler if no linestyle is specified. I wonder if errorbar()
is passing in its own linestyle?

**Comment by tacaswell** [comment]
The guts of errorbar were almost completely re-written in https://github.com/matplotlib/matplotlib/pull/5593
