### ISSUE TITLE
Superscripts in axis label cut when saving .eps with bbox_inches="tight"

### ISSUE THREAD

**Issue by DTHaydon** [matplotlib/matplotlib#7075]
I have been saving some .eps plots using:
`matplotlib.pyplot.savefig(file.eps, bbox_inches="tight")`
 and this works as expected; however, when using:
`matplotlib.rcParams['text.usetex'] = True` 
`matplotlib.pyplot.savefig(file.eps, bbox_inches="tight")`
the y axis label is cut. 

It has been noted before that there has been some issues with .eps fies and usetex (Bounding box no longer works for EPS files if usetex=True #85) but I don't know in what way the bounding box was wrong and I am also using a matplotlib version that is 5 years on.

Here is a somewhat forced example and the results.
## Example

```
import numpy
from matplotlib import pyplot
from matplotlib import gridspec
from matplotlib.collections import LineCollection

def plotLines(file_name):

    # -- Misc ----------------------------------------------------------------
    axis_font_size = 50.
    line_thickness = 3.

    # -- Data ----------------------------------------------------------------
    angles = numpy.linspace(-180., 180, num=201)
    amp_values = [1., 2., 3.] 

    line_values = []     
    for amp in reversed(amp_values):
        sine = amp * (numpy.sin(angles * (numpy.pi/180.)))**-1
        line_values.append(zip(angles, sine))

    amp_values = numpy.array(amp_values)
    lines = LineCollection(
        line_values, 
        array=amp_values, 
        cmap=pyplot.cm.viridis,
        linewidth=line_thickness
        )

    # -- Init Plot -----------------------------------------------------------
    pyplot.clf()  # Clear plot area
    fig = pyplot.figure()
    ax_grid = gridspec.GridSpec(
        1, 2, wspace=0.05, hspace=0.00,
        width_ratios=[20, 1]
        )

    # -- Plot ----------------------------------------------------------------
    plot = pyplot.subplot(ax_grid[0])

    plot.add_collection(lines)

    # Axis limits
    plot.set_xlim([numpy.min(angles), numpy.max(angles)])
    plot.set_ylim([-numpy.max(amp_values), numpy.max(amp_values)])

    # Axis labels
    plot.set_xlabel(
        "$\\mathrm{Angle} \\, \\left[^{\\circ}\\right]$", 
        fontsize=axis_font_size
        )
    plot.set_ylabel(
        "$\\mathrm{Amp} \\,"
        "\\times \\, \\left[\\mathrm{sine} \\,"
        "\\left(\\mathrm{Angle}\\right)\\right]^{-1}$",
        fontsize=axis_font_size,
        )

    # -- Colour Bar ----------------------------------------------------------
    cbar_axis = pyplot.subplot(ax_grid[1])

    cbar = pyplot.colorbar(lines, ticks=amp_values, cax=cbar_axis)

    # CBar Label
    cbar.ax.set_ylabel(
        "$\\mathrm{Amp}$",
        fontsize=axis_font_size,
        )

    # -- Save ----------------------------------------------------------------
    pyplot.savefig(
        "{:s}.eps".format(file_name),
        bbox_inches="tight",
        dpi=600
        )
    pyplot.close()


if __name__ == "__main__":
    plotLines("Without")
    import matplotlib as mpl
    mpl.rcParams['text.usetex'] = True  # Process all text with TeX
    plotLines("With")
```
### Without

As expected
![without](https://cloud.githubusercontent.com/assets/15086793/18393424/8d1b959e-76b5-11e6-9ced-2d6a23db2166.png)
### With

Y axis label cut
![with](https://cloud.githubusercontent.com/assets/15086793/18393415/874e90a8-76b5-11e6-883b-e2c1f6a3386d.png)
## System

Matplotlib 1.5.1
Python 2.7.12 (Anaconda install)
CentOS Linux release 7.2.1511
GPL Ghostscript 9.07 (2013-02-14)

**Comment by tohojo** [comment]
I've been having some issues with text bounding boxes being wrong for axis labels on 2.0 (when saving PDFs in my case). Will investigate if this is the same bug...

**Comment by tohojo** [comment]
And to follow up on this, my issue is unrelated to usetex, so I don't think it's the same issue...

**Comment by Warbo** [comment]
I was having trouble with y-axis labels being cut off: it was fine for pgf output, but broke when using EPS. Googling brought me here, so I tried removing 'usetex = True' and it solved the problem.

**Comment by pyZerrenner** [comment]
For me this bug is DPI dependent. With the default DPI of 100 the following code gives a good result:

``` python
import matplotlib.pyplot as plt

plt.rcParams['figure.dpi'] = 100

fig, ax = plt.subplots(1, 1, figsize=(2,1))
ax.set_ylabel(r'$X^{SUPERSCRIPT}$')

fig.savefig('test_superscript.png', bbox_inches='tight', pad_inches=0)
```

![test_superscript_DPI100](https://user-images.githubusercontent.com/47388301/56956893-c0055080-6b45-11e9-82d3-c382998ed79f.png)

However, when I increase the DPI, the superscript of the y-label is cut off. With `plt.rcParams['figure.dpi'] = 300` the result is:

![test_superscript_DPI300](https://user-images.githubusercontent.com/47388301/56956994-0fe41780-6b46-11e9-9711-4fb352cf69ac.png)

The same happens for saving as pdf or when setting `'savefig.dpi'` instead of `'figure.dpi'`. My current solution is to increase the value of `pad_inches` until everything is visible. This increases the padding on all sides, which is not too bad, but still annoying.

When using TeX for text rendering, the issue appears for all DPI, like in the comments above. With `plt.rcParams['figure.dpi'] = 100` and `plt.rcParams['text.usetex'] = True` I get:
![test_superscript](https://user-images.githubusercontent.com/47388301/56957945-145dff80-6b49-11e9-8730-07b73fe3bf12.png)
Maybe the DPI and TeX issues are somewhat unrelated, but I didn't want to open a new issue unnecessarily.

I am using matplotlib 2.2.4 on Python 3.6 myself. Unfortunately, I cannot verify this with the latest version (matplotlib 3.0.3) right now, so I hope this has not been resolved yet. (Or rather I _do_ hope it has been resolved, then this issue could be closed.)

**Comment by jklymak** [comment]
This is still a bug on master...  Its obviously the superscript that is causing the problem, with the text bounding box not surrounding the superscript.

**Comment by jklymak** [comment]
... same thing happens for a title.

**Comment by jklymak** [comment]
I'll close this in favour of #21653, which is the same thing, but perhaps easier to follow (bug doesn't depend on clipping or eps, etc)
