### ISSUE TITLE
DOC: Clarify the relationship between `plot` and `scatter`

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#7083]
The Notes section of the `scatter` docstring should point out that the simplest scatter plots can be made more efficiently with `plot`.  There are probably also examples and other places in the docs where this could be illustrated or mentioned.

This came up in the discussion of #7072.

**Comment by NelleV** [comment]
I can do a PR for this, thought I am very much convinced this will not fixed the issue.
Users get confused because it is a design flaw in matplotlib, and expect to plot scatter plots with the scatter function.

**Comment by WeatherGod** [comment]
it goes deeper than matplotlib. The forums for matlab has similar arguments
about what scatter and plot are for.

**Comment by NelleV** [comment]
The problem isn't IMO in the arguments. I am totally fine with the functions having different arguments (well, no I am not, but you have to choose your battles…).  The problem is that we are telling users to use plot instead of scatter in cases where anyone in their right mind would use the scatter function because of the name: the users are trying to do a scatter plot, so why not use the scatter function?

I understand the challenges in fixing the design problem in the scatter function, but we've been trying to teach to users to use plot instead of scatter when colors and size are identical for now 4 years, and it clearly hasn't worked. We can try teaching users better by improving the documentation, but I don't believe users will read the documentation : I sure never read the documentation, unless I have no clue of what I am doing or the program is not behaving the way I expect it to.

It would actually be interesting to select a number of advanced users from the scientific python community, and ask them to do a scatter plot with identical with a large number of points to see whether these advanced users know to use plot instead of scatter.
