### ISSUE TITLE
fix building pdf docs

### ISSUE THREAD

**Issue by hiccup7** [matplotlib/matplotlib#7090]
http://matplotlib.org/Matplotlib.pdf returns 404 "File not found".

**Comment by tacaswell** [comment]
Are you actually using the pdf version of the docs?  The 1.5.3 version did not build cleanly, so it did not get uploaded (and I think I removed the links to it).

http://matplotlib.org/1.5.1/Matplotlib.pdf still exists.

**Comment by hiccup7** [comment]
My PC with Python has no internet connection, so I rely on the PDF for documentation.  I have the 1.5.1 version, but I would like the 1.5.3 version if there are changes.

Here is an example of a site that links to the URL:
http://stackoverflow.com/questions/14428056/matplotlib-documentation-in-html-format
So it would be good to maintain a working URL at all times, even if the PDF is not exactly for the latest version.

P.S.  matplotlib is of great service to the Python community.  Thanks for all the effort of the team!

**Comment by tacaswell** [comment]
Between 1.5.1 and 1.5.3 there are only bug fixes.  This is more of a problem for the 2.0 release.

**Comment by tacaswell** [comment]
@hiccup7 Would you be ok with a zip file of the html docs instead?

**Comment by tacaswell** [comment]
The pdf for 1.5.3 is now posted, http://matplotlib.org/Matplotlib.pdf (which is the 'current' docs) and http://matplotlib.org/1.5.3/Matplotlib.pdf (tied to 1.5.3).  At some point we well probably have to cull the older docs, but at this point they should be stable as long as a release is used in the wild.

The issue was fixed by @QuLogic in #7135
