### ISSUE TITLE
Feature request: auto locate minor ticks on log scaled color bar

### ISSUE THREAD

**Issue by breedlun** [matplotlib/matplotlib#7141]
Matplotlib version 1.5.1, Python version 2.7.6 (Enthought Canopy) and OSX

As detailed in this [stack overflow post](http://stackoverflow.com/questions/20079270/minor-ticks-in-matplotlibs-colorbar/20079644#20079644), you have to explicitly specify the minor tick locations on a log scaled color bar.  It would be nice if matplotlib would do this for you, instead of having to call `minorticks = p.norm(np.hstack([np.arange(2, 10, 1)/10.0, np.arange(2, 10, 1)/1.0])` in the code below

``` python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

x = np.linspace(1,10,10)
y = np.linspace(1,10,10)
X, Y = np.meshgrid(x,y)
Z = np.abs(np.cos(X**2 - Y**2) * X**2 * Y)
f, ax = plt.subplots()
p = plt.pcolormesh(X, Y, Z, norm=LogNorm(), vmin=1e-2, vmax=1e2)
cb = plt.colorbar(p, ax=ax, orientation='horizontal', aspect=10)
# We need to nomalize the tick locations so that they're in the range from 0-1...
minorticks = p.norm(np.hstack([np.arange(2, 10, 1)/10.0, np.arange(2, 10, 1)/1.0]))
cb.ax.xaxis.set_ticks(minorticks, minor=True)
plt.show()
```

**Comment by story645** [comment]
Can you please provide a picture? Might be easier to evaluate what you're after that way.

**Comment by Kojoley** [comment]
![default](https://cloud.githubusercontent.com/assets/2743474/18681370/71320bd8-7f70-11e6-9ade-ddbb24a7c0f0.png)
![with minor ticks](https://cloud.githubusercontent.com/assets/2743474/18681369/7131805a-7f70-11e6-9964-955f1f703f8b.png)

**Comment by Kojoley** [comment]
`cb.ax.minorticks_on()` works in a different way:
![cb.ax.minorticks_on()](https://cloud.githubusercontent.com/assets/2743474/18681435/b8e32cf0-7f70-11e6-96e7-c1a64d33cb34.png)

**Comment by breedlun** [comment]
Thanks, @Kojoley.  ``cb.ax.minorticks_on()`` gives evenly spaced minor tick marks in log space, which is not what I want.  In my opinion, the default should be evenly spaced tick marks in linear space, which translate to unevenly spaced tick marks in log space.

**Comment by tacaswell** [comment]
attn @efiring

**Comment by QuLogic** [comment]
On current `v2.x`, this:
```
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm

x = np.linspace(1,10,10)
y = np.linspace(1,10,10)
X, Y = np.meshgrid(x,y)
Z = np.abs(np.cos(X**2 - Y**2) * X**2 * Y)
f, ax = plt.subplots()
p = plt.pcolormesh(X, Y, Z, norm=LogNorm(), vmin=1e-2, vmax=1e2)
cb = plt.colorbar(p, ax=ax, orientation='horizontal', aspect=10)
plt.show()
```
looks like this by default:
![figure_1](https://cloud.githubusercontent.com/assets/302469/21078834/835f7dac-bf4b-11e6-84b3-b0de63ea2826.png)
so I guess this has been fixed?

**Comment by efiring** [comment]
Closed by #7438.

**Comment by breedlun** [comment]
I am glad to see that minor ticks are placed properly now, but tick length on minor tick should be shorter than major ticks, IMHO.   That's how it used to be (see Kojoley's Sep 20th post).  Perhaps the minor tick length is just a rcParams setting...

**Comment by efiring** [comment]
No, it will take more work to fix that.  It won't happen for 2.0.  It requires substantial change to the colorbar tick-handling, which differs from normal axis tick handling because there is an additional transformation between the colorbar tick values and the axis coordinates.  The colorbar does not support major and minor ticks; it has only major ticks.  It has a single `ticks` kwarg and a single `format` kwarg, together with the machinery to use their values, or suitable defaults based on the norm.  Directly setting the minor ticks as in the example at the top of this issue will not work correctly in general because the data limits don't necessarily correspond to the (0, 1) colorbar axis coordinates.
This is related to the confusing intersection among scales, transforms, norms, tickers, and the necessarily unique characteristics of a colorbar.  I would prefer to see it handled in the course of a larger code cleanup and refactoring rather than by merely adding a bunch of code to the already-complex colorbar.  (Actually, my mind is wavering; hacking minor ticks into the colorbar is conceptually straightforward, and probably the API changes--adding 2 kwargs--would be the same as we would end up with after a major re-write.)
I will open a separate issue for this.

**Comment by breedlun** [comment]
Ok.  Thank you for the detailed reply.  I probably would have spent 30 minutes figuring that out on my own.
