### ISSUE TITLE
Hexbin default edgecolors kwarg is misnamed

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#7185]
Hexbin has a default 'edgecolors' kwarg value of 'none', which it internally translates to 'face'.  This is highly confusing and inconsistent, and it blocks the user from specifying 'none'.  Granted, the 'none' value may be undesirable because of patch boundary artifacts, but it should not be interpreted as a completely different value.
The 'face' value is used to prevent artifacts by adding boundary lines.  hexbin sets the default 'linewidths' to 1, which is probably much larger than it needs to be for this purpose, resulting in prominent artifacts when the number of hexagons is large.

**Comment by DrNightmare** [comment]
It looks like someone has worked on fixing this issue quite some time back, although I'm not sure if they submitted a PR:
https://github.com/tonysyu/matplotlib/commit/39e28540d30a55c18975533fe3625c47506c5908
I'm sure a lot of files changed since this commit, but the solution seems to hold: make 'edgecolors' default to 'face' to ensure backward compatibility.
