### ISSUE TITLE
style blacklist includes hardcopy.docstring but it should be docstring.hardcopy

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7198]
All's in the title.

Compare https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/style/core.py#L43 and https://github.com/matplotlib/matplotlib/blob/master/matplotlibrc.template#L553.

(To be honest I don't know why this parameter needs to be exposed...)

**Comment by JunTan** [comment]
I believe the 'hardcopy.docstring' in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/style/core.py#L43 
should be "docstring.hardcopy" 
This parameter is there because in https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/style/core.py#L46 it makes sure that the "docstring.hardcopy" is not used and not assigned a val to it. But since originally 'hardcopy.docstring' is something not exists, then it will be assigned a val to it but cannot be used.
