### ISSUE TITLE
BUG: mencoder-generated animations fail on Quicktime

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#7209]
On v2.x, with the default mpeg4 codec, switching the Writer to 'mencoder' in examples/animation/basic_example_writer.py yields files that Quicktime can't open.  This is on Mavericks with mencoder installed via homebrew.  

As a side issue, this mencoder has no h264 support.

Overall, it seems to me that trying to support mencoder in the animation module is more trouble than it is worth.

**Comment by tacaswell** [comment]
Not strictly convinced that the problem isn't quicktime :smiling_imp: 

I am in favor of deprecating mencoder and pushing the code to it's own repository.

**Comment by WeatherGod** [comment]
Are we sure the problem is with mencoder? Does the same codec/format combo
work with another writer? According to my tests from a couple years ago,
mpeg4 codec with .mp4 format did work for QuickTime on MacOSX.
Unfortunately, I didn't record which writer I used at that time.

I am not totally surprised that h264 support might not be available in a
stock install of mencoder, but it should be trivial to install the codec,
IIRC.

**Comment by anntzer** [comment]
The mencoder writer was removed in 2.2.
