### ISSUE TITLE
get_geometry() wrong if subplots are nested (e.g., subplots with colorbars)

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#7225]
_Note:_ This is from [a stackoverflow question](http://stackoverflow.com/q/39719709/353337).

---

Consider
```python
import numpy as np
import matplotlib.pyplot as plt

data = np.zeros((3, 3))

fig = plt.figure()

ax1 = plt.subplot(131)
ax2 = plt.subplot(132)
ax3 = plt.subplot(133)
axes = [ax1, ax2, ax3]

for ax in axes:
    im = ax.imshow(data)
```
The resulting figure `fig` has 3 `AxesSubplot` children, one for each subplot. Their geometry
```python
for child in fig.get_children():
    try:
        print(child.get_geometry())
    except AttributeError:
        pass
```
```
(1, 3, 1)
(1, 3, 2)
(1, 3, 3)
```
makes sense.

Now let's add some color bars:
```python
for ax in axes:
    fig.colorbar(im, ax=ax, orientation='horizontal')
```
Now the geometries are reported as
```
(2, 1, 1)
(2, 1, 1)
(2, 1, 1)
(1, 3, 2)
(1, 3, 2)
(1, 3, 2)
```
All information about how the plots are arranged seems lost.

I guess I would have expected a nested structure: The three plots are children of `fig` with the ordering 
`(1, 3, 1), (1, 3, 2), (1, 3, 3)`, and each of those has two subplots with the ordering `(2, 1, 1), (2, 1, 2)`.

**Comment by anntzer** [comment]
This is because the image and the colorbar live in "different" gridspecs: the image is the first element of a (2, 1) gridspec (to make room at the bottom for the colorbar) and the colorbar in the center element of a (1, 3) gridspec (to leave some margins on both ends).

You can retrieve the original gridspec coordinates with `child.get_subplotspec().get_topmost_subplotspec().get_geometry()` (where the first two numbers are nrows and ncols, the third the axes index (zero-based!), and the fourth, if not None, indicates the range spanned by the subplotspec (third-to-fourth)).

**Comment by nschloe** [comment]
This fixes it then, I guess. Thanks!
