### ISSUE TITLE
better document how to configure artists for picking

### ISSUE THREAD

**Issue by adailsonfilho** [matplotlib/matplotlib#7238]
I'm trying to handle some events to perform user interactions with embedded subplots into a Tkinter frame. Like in this [example](http://matplotlib.org/examples/user_interfaces/embedding_in_tk.html)

Works fine with "key_press_event" and "button_press_event", but does not work with "pick_event".

I modified that example from the link, just adding the following piece of code after the mpl_connect calling:

```
def on_button_press(event):
    print('you pressed mouse button')

canvas.mpl_connect('button_press_event', on_button_press)

def on_pick(event):
    print('you picked:',event.artist)

canvas.mpl_connect('pick_event', on_pick)
```

Why "pick_event" doesn't work into embedded graphs? And how do get it to work?

My configurations detailed:

Windows 10
Python 3.5 (conda version)
Matplotlib 1.5.3 installed via pip

**Comment by anntzer** [comment]
This is because you need to set the `picker` property on the artist, as mentioned in the docs: http://matplotlib.org/users/event_handling.html#object-picking.  For this example, it is
```
a.plot(t, s, picker=True) # or =5, =10, ... for specifying the tolerance
```

Closing the issue, but feel free to ask more questions.

**Comment by adailsonfilho** [comment]
Well, I was doing something wrong.... But it think something could be better.

Most events we just need to use mpl_connect method to the magic happen. My mistake is that I didn't notice that we need to say explictly that our plot is "pickable" putting a argument picker=True to only triggers the event if clicked exacly into the artist, and `picker=x` where `x` is an integer that is the pixel tolerance for the trigger. So beyond the changes I inserted for pick in the question, we should replace

`a.plot(t, s)` for `a.plot(t, s,picker=True) `or `a.plot(t, s,picker=10)`, e.g.

By coherence I think would be better when calling mpl_connect for 'pick_event' all the plots in the figure become "pickable". What do you think guys?

Thanks for the great job with the lib!

**Comment by anntzer** [comment]
Hum, I guess there is something to be said for artists to default to `picker=True`...

**Comment by anntzer** [comment]
The default tolerance would be whatever you get when `picker=True`, so that's not a problem.  You'd get your callback called once for every artist that was picked.

(If you want to get *all* picked artists at the same time (e.g. in order to keep just one of them), you can connect to `button_press_event` and do the filtering yourself.)

**Comment by adailsonfilho** [comment]
I got the idea, but as far as I understood when we set `picker=True` there is no tolerance, the callback will only be called in exact clicks.

**Comment by anntzer** [comment]
... which sounds like the reasonable default to use?
@QuLogic pointed out to me that there are many more artists than one may expect on an axes, e.g. axes ticks would show up too.  While filtering them away in the callback is probably not too hard, it may or may not be too much of an inconvenience / a backwards incompatibility.

**Comment by tacaswell** [comment]
I am :-1: on changing this default.  

Hit testing can be expensive and should be opt-in (in addition to the back-compatibility / annoyance factor).

**Comment by adailsonfilho** [comment]
@tacaswell , I got your concerns, but if someone have called `mpl_connect('pick_event', anyfunction)`, in my point of view is clear that the developer want the hit testing, and it would be ran anyway. I'm more concerned with the following fact:

If someone is calling `mpl_connect` for any event besides 'pick_event` it works, but with 'pick_events' it doesn't, because we need to set the tolerance in another place. I really don't know the best way to do this or its implications. I just thought that could be more coherent for the `mpl_connect` usage.

**Comment by WeatherGod** [comment]
Connecting to an event doesn't automatically mean that that event should be
emitted by everybody and anybody. Remember, any event can be used in the
connect call, including user-defined ones. Matplotlib, by default, sets up
some simple event emitters for convenience such as window handling,
panning, zooming, limit changes, etc., but none of those setups are
triggered by any connect calls. They are baked in by default and always
exists.

So, we can't trigger 'pick_event' emissions by a simple mpl_connect() call
(plus, it would be entirely unclear what should be turned on). So that
leaves turning pick_event=True as the default, which has several drawbacks,
namely performance, but also information overload as way more artists would
be emitting pick_event than the user would have expected.

Think about it this way. If pick_event=True was the default, then imagine
how much code would be needed to go through all of the artists except the
desired artists and turn off pick_event emissions.

Better documentation may be called for, or just simply order a copy of my
book "Interactive Applications Using Matplotlib", where I discuss
pick_events in detail and provide several examples.


On Sun, Oct 9, 2016 at 4:47 PM, Adailson de Castro <notifications@github.com

**Comment by tacaswell** [comment]
I also suggest writing functions like

```python
def install_my_picker(art):
    art.set_picker(True)
    art.figure.canvas.mpl_connect('pick_event', my_pick_function)
```

In addition see http://matplotlib.org/users/event_handling.html?highlight=event%20picking#object-picking and https://github.com/tacaswell/interactive_mpl_tutorial (which will probably get folded back into the main docs).

**Comment by adailsonfilho** [comment]
Thank you guys! I've learned so much with this conversation. And thanks for the great job with the lib! =D

**Comment by NelleV** [comment]
@adailsonfilho Maybe you'd be a good fit to improve the documentation on this :)

**Comment by adailsonfilho** [comment]
@NelleV , right now my life (personal, professional and academic) is a mess ... When the things cool down, if nobody have picked it already, I would love study a little more of it and help out with the docs.
