### ISSUE TITLE
ipython loses auto-show/auto-redraw behavior after call to `plt.rcdefaults()`

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7289]
matplotlib 2.0b4, ipython 5.1.0, python 3.5.2.

After calling `plt.rcdefaults()` in an ipython session, plotting commands (e.g. `plt.plot([1, 2])`) do not auto-show/auto-redraw the figure anymore (explicit calls to `plt.show()`/`fig.canvas.draw()` becomes needed).  It would certainly be better if the auto-show/auto-redraw behavior was kept.

**Comment by anntzer** [comment]
I guess this may be related to the fact that `rcdefaults` resets the backend to `agg`?

**Comment by tacaswell** [comment]
It is `rcParams['interactive']` which is conuslted by `mpl.is_interactive()` which is consulted by the `post_execute` function installed on the callback for IPython (or `_auto_draw_if_interactive` for plain python shell).

`plt.ion()` and `plt.ioff()` change this rcParam.

I do not see a nice way out of this, but all you need to do is call `plt.ion()` and the auto-draw should be back.

`'interacitive'` is in the set of things black-listed by `mpl.style`, I suspect you want to be using `mpl.style.use('default')` instead of `mpl.rcdefaults()` ?

**Comment by anntzer** [comment]
Fair enough, and I don't think there's anything to do other than improving the docs.  I'd suggest mentioning this in http://matplotlib.org/devdocs/users/customizing.html?highlight=rcdefaults#dynamic-rc-settings and http://matplotlib.org/devdocs/api/pyplot_api.html#matplotlib.pyplot.rcdefaults, then?  (I'd guess most of the times it is `style.use('default')` that should be used rather than `rcdefaults`.)
