### ISSUE TITLE
Histogram compatibility with numpy

### ISSUE THREAD

**Issue by rancomp** [matplotlib/matplotlib#7364]
In the documentation of numpy's histogram: https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html It is specified the keyword _normed_ will be removed in V2.0 and be replaced with _density_ (due to buggy behavior).

Should matplotlib be compatible with this naming, and atleast accept the keywoard _density_?

**Comment by tacaswell** [comment]
:+1: 

We do the our own norm computation for a long fixed issues in numpy < 1.5.  Our minimum numpy is 1.6 (and has been since mpl1.4) so we can remove all of that code + update the kwarg.

This is in principle easy, but touching `hist` can get surprisingly complex surprisingly quickly, so tagging as 'medium' for that reason.  However, this change will be relatively self-contained (and should not require touching code _outside_ of `hist`, hence 'new contributor friendly'.

There is a bunch of special casing farther down the function for when the histogram is normed that will need to be checked to still work.

I think we should differ from numpy a bit here and: 

 - set both `normed` and `density` to `None` by default.
 - if both are not `None` raise
 - covert to 'density' fully internally
 - maintain default behavior of counts (not density)

----

Bit of git forensics

doing the norm our selves introduced in 2840392e9e20142e836e4d1c902cdff6c69d1a39

The code around it has been refactored a bit and the note re-formatted, but it looks like it has not been fundamentally changed.

---

attn @efiring @neggert
