### ISSUE TITLE
Incorrect KeyPressEvent shift+alt key combinations using Qt4Agg backend

### ISSUE THREAD

**Issue by Erotemic** [matplotlib/matplotlib#7368]
Info: Python 2.7.6 matplotlib 1.5.1 installed from source on Ubuntu Linux 14.04 64bit using pyqt4 backend. The `QtCore.PYQT_VERSION_STR='4.10.4'`. The `QtCore.QT_VERSION_STR='4.8.6'`.

I've come across an error that occurs in the Qt4Agg backend, but not in the WebAgg. I was unable to test other interactive backends, so I'm not sure how far the issue goes. 

The error is in the key_press_event callback. On each callback I print out event.key. When I press alt+shift I get the correct output of `alt+shift`, but when I press shift+alt, I get the incorrect output of `shift+super` only when using the Qt4Agg backend. When switching to the WebAgg backend everything works fine. 

Here is a script that I used to reconstruct the error. The specific sequence of key presses and releases is listed in a comment at the bottom. 

```python

backend = 'QtAgg'
# backend = 'WebAgg'

if backend == 'QtAgg':
    try:
        import PyQt4 as PyQt  # NOQA
        pyqt_version = 4
        backend = 'Qt4Agg'
    except ImportError:
        import PyQt5 as PyQt  # NOQA
        pyqt_version = 5
        backend = 'Qt5Agg'

print('backend = %r' % (backend,))

import matplotlib as mpl  # NOQA
mpl.use(backend, warn=True, force=False)
import matplotlib.pyplot as plt  # NOQA


def on_key_press(event):
    print(event.key)

fig = plt.figure()
fig.canvas.mpl_connect('key_press_event', on_key_press)
# show something to make interaction happen
plt.plot([1, 2], [3, 4])  
plt.show()


"""
The user must now select the window and execute the following sequence of 
key press and release events. 

PRESS alt
# stdout: alt

PRESS shift
# stdout: alt+shift

RELEASE ALT
RELEASE SHIFT

PRESS shift
# stdout: shift

PRESS alt
# stdout: shift+super
# but should be alt+shift
# This happens in Qt4Agg, but in WebAgg the expected output is printed. 
"""
```

**Comment by tacaswell** [comment]
That is a bit wild.  'alt' then 'shift' give 'alt+shift', 'shift' then 'alt' gives 'shift+super'.

This is process in `_get_key` in qt5_backend.py.  There is nothing obvious wrong, I am a bit worried that this is some how a 'feature' to turn the alt key into a meta/super key.

**Comment by tacaswell** [comment]
@Erotemic Thank you for the very clear bug report!

**Comment by QuLogic** [comment]
And shift + left alt + right alt produces `shift+alt+super`.

**Comment by anntzer** [comment]
Actually this seems to happen at the level of the X keyboard handling itself.  On Arch Linux, after `setxkbmap us`, start `xev` to see X input events.

Pressing left alt by itself produces
```
KeyPress event, serial 40, synthetic NO, window 0x3c00001,
    root 0xd6, subw 0x0, time 30766076, (42,129), root:(858,158),
    state 0x0, keycode 64 (keysym 0xffe9, Alt_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```
whereas doing so after having pressed shift produces
```
KeyPress event, serial 40, synthetic NO, window 0x3c00001,
    root 0xd6, subw 0x0, time 30822047, (79,131), root:(895,160),
    state 0x1, keycode 64 (keysym 0xffe7, Meta_L), same_screen YES,
    XLookupString gives 0 bytes: 
    XmbLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

One can dump the keymap with `xkbcomp $DISPLAY /tmp/out.xkb`, the relevant line is
```
key <LALT> {         [           Alt_L,          Meta_L ] };
```
which again indicates that the left alt key is to be interpreted as a meta key when shift is pressed.

See also http://askubuntu.com/questions/567731/why-is-shift-alt-being-mapped-to-meta which notices the same issue specifically for Ubuntu.  Actually, I don't have an Ubuntu available for testing, but @Erotemic, can you look up the menu mentioned in http://askubuntu.com/questions/19558/what-are-the-meta-super-and-hyper-keys and see whether this behavior can be changed from that menu?

Note that for some reason `backend_qt5.py` reports `Qt.Key_Meta` as `super` instead of `meta`, I'm not really sure why (especially becase there's an *actual* super key, namely the "windows" key -- which is reported as `super` by `xev` and matplotlib/Qt5, and standard according to Wikipedia (https://en.wikipedia.org/wiki/Super_key_(keyboard_button)))...  I would guess that such a conflation of `super` and `meta` is a mistake.

I'm not sure about webagg but I've noticed that tkagg also doesn't suffer from this issue; on the other hand it seems to have some other issues with double-modifiers: shift-then-control is reported as "shift" and "control" (whereas control-then-shift is reported as "control" and "control-shift"), and shift-then-alt is reported as "shift" and "None" (whereas alt-then-shift is reported as "alt" and "alt+shift".

**Comment by QuLogic** [comment]
I guess this is a slight confusion of Qt's cross-portability, as `MetaModifier` is the Windows key _on Windows_. So the mapping in `backend_qt5.py` is to cover that case as if it were Linux, but that makes it seem wrong on Linux.

Qt only provides `Super_L` and `Super_R` as keys and not modifiers (which I guess makes sense, since they aren't really.)

**Comment by QuLogic** [comment]
We no longer support Qt4. Please re-open if this is still a problem with Qt5.
