### ISSUE TITLE
`test_log_margins` test failure

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#7452]
It was broken by #7144. The tests passed in the PR because at the point when they were made there was no `test_log_margins` test (it was restored by #7435).

**Comment by efiring** [comment]
I think the solution might be to add an `atol=1e-16` argument to the assertion.  It looks like the problem is that it is using an atol of 0, which allows for no floating point slop in a comparison to 0.
Or, change each `[1, 10]` to `[10, 100]`, so that the test values would be (1, 2) instead of (0, 1).
(I haven't tried either of these option.)
