### ISSUE TITLE
missing trigger for autoscale

### ISSUE THREAD

**Issue by ahed87** [matplotlib/matplotlib#7466]
Hi,
I wonder if there is a missing trigger for autoscale when using patches?
The minimal example shows up as a quarter circle with axis bounds 0,1.
I noticed this when using bigger patches and the canvas appeared completely empty.
After some moments of wondering why the patch was not there I noticed the axis bounds.
A call to ax.autoscale() puts the full circle in view.

mpl 1.5.3

If you consider this to be a feature I'm fine with closing the issue.
If you consider that it should be fixed and you think it's an easy fix, please give me some hints of where to make the trigger(s), If so I will make an attempt to fix it. If you think it belongs to the larger autoscale discussion that seems to be ongoing at the moment, maybe it could be considered there.

minimal example:
```
import matplotlib.pyplot as plt
from matplotlib.patches import Wedge
fig, ax = plt.subplots()
w = Wedge((0, 0), 1, 0, 360, width=0.2)
ax.set_aspect('equal')
ax.add_patch(w)
plt.show()
```

**Comment by tacaswell** [comment]
I think leaving the `add_*` methods _not_ doing auto scaling in the right thing.  If users call them directly (rather than through the plotting methods) it is on the user to call auto-scale.  

This is a very quick reaction, can definitely be talked out of it.

attn @efiring 

thanks for bringing this up @ahed87 !

**Comment by efiring** [comment]
Yes, this is my reaction also; it is quite a basic aspect of the design, consistent over all of the `add_*` methods.  The Axes methods typically call `autoscale_view` after `add_*`, but with varying arguments.

**Comment by ahed87** [comment]
Makes perfect sense to not have autoscale triggered on ```add_*```,
however does this mean that it should also not be triggered by ```plt.show()```?
I guess your point is that autoscale is triggered if one adds a line with ```ax.plot([0, 1])```, or similar, putting the full circle in view.

I should close this one with the comment that it is intended behaviour?

**Comment by efiring** [comment]
The question of where autoscaling should be triggered (or queued) and where it should actually be carried out is under discussion.  The latter would not be in `show` itself, but it might be in `Figure.draw`.  This would be part of a considerable overhaul, though, and would not change the fact that the present behavior, in which high-level commands like `plot` trigger it and low-level commands do not, is intentional and will remain.
