### ISSUE TITLE
better input validation on `fill_between`

### ISSUE THREAD

**Issue by robertsawko** [matplotlib/matplotlib#7510]
Hi,

So I am running on Python 3.5.2 and Matplotlib 1.5.3 and everything is installed via OS packet manager on Arch Linux. Here's the code I am having issue with:

```python
from matplotlib.pyplot import figure
from numpy import linspace

fig = figure()
ax = fig.gca()

x = linspace(0, 1).reshape(50, 1)

ax.fill_between(x, x, -x)  # That doesn't work!
ax.fill_between(x[:, 0], x[:, 0], -x[:, 0])  # And that ugliness does!
```
I've already checked that this is due to `where=None` setting which constructrs `where` variable via `len` function. This seems inadequate in many `numpy` scenarios as occasionally arrays will pop up with or without second dimension. If they do have a second dimension though the `where=None` will force the error below.

```
Traceback (most recent call last):
  File "fill_between_test.py", line 11, in <module>
    ax.fill_between(x, x, -x)  # That doesn't work!
  File "/usr/lib/python3.5/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 4596, in fill_between
    raise ValueError("Argument dimensions are incompatible")
ValueError: Argument dimensions are incompatible
```
Please advise.

**Comment by tacaswell** [comment]
What should `fill_between` do if it gets a greater than 1D array?

I think the change we should make here is to clarify that the inputs should be 1D and raise a better exception.

`np.squeeze` might be a better option that the above slicing.

**Comment by robertsawko** [comment]
The problem originally came out when reading data from a file. The vectors were one dimenional but second dimension was fixed to 1 rather than empty. I think that case should be handled even when `where=None`.

**Comment by tacaswell** [comment]
If `data.ndim != 1` it is not 1D data (in the most pedantic way).   

If we start to take `(N, 1)` as input, then we should probably take `(1, N)` as valid input as well.  We then would have to decide how to deal with the user providing a mix if `(N,)`, `(N, 1)`, and `(1, N)`. Should we just squeeze them or is that an error?  I suspect that either answer will be wrong in some contexts which is why I think it is better if mpl requires 1D inputs (that is `np.array(v).ndim == 1`) and leave the decisions about how to go from the application data -> what mpl needs to the application developers.

**Comment by robertsawko** [comment]
Ok. I see your point. I am ok with using `squeeze`. Maybe then just change the error message. I was initally not aware of `where` parameter. The confusing thing was that all arguments I was giving explictly had agreeing dimensions.

**Comment by tacaswell** [comment]
The exact work here:

  - [ ] validate the inputs to `fill_between` and `fill_betweenx` are 1D (because we can also take in lists, numpy arrays, and pd.Series this should probably be `cbook.is_scaler(cbook.safe_first_element(inp))`  to check that it is a) an iterable b) the things that come out of iteration look like scalars).
 - [ ] raise a clear error if not

**Comment by gauthamzz** [comment]
Can i try this , if it is still open ?

**Comment by tacaswell** [comment]
@gauthamzz Please do!  I do not think anyone is currently working on this.

**Comment by gauthamzz** [comment]
Can you tell me the names of the associated files ?

**Comment by tacaswell** [comment]
Both of those methods are in `lib/matplotlib/axes/_axes.py`

**Comment by timhoffm** [comment]
What the error message says: *y1* must be a 1-dimensional array. You've passed in something else.

**Comment by viswanath69** [comment]
F:\Anaconda\lib\site-packages\matplotlib\axes\_axes.py in fill_between(self, x, y1, y2, where, interpolate, step, **kwargs)
   5052             if array.ndim > 1:
   5053                 raise ValueError('Input passed into argument "%r"' % name +
-> 5054                                  'is not 1-dimensional.')

**Comment by viswanath69** [comment]
this was working 2 weeks back. After I installed OS due to some reason, installed Anaconda python v3.7 this error I got

**Comment by timhoffm** [comment]
Please check the shape of y1 in your code and make it 1D.

I'm sorry this is popping up for you. However, this change just enforces what was implicitly assumed and explicitly documented on the data already. The former tolerance towards multi-dimensional arrays may or may not have worked properly depending on the actual data. And we don't want to risk wrong plots due to sloppy data verification.
