### ISSUE TITLE
Figure.show() fails with Qt5Agg on Windows (plt.show() works)

### ISSUE THREAD

**Issue by aivarannamaa** [matplotlib/matplotlib#7521]
Problem occurs with Matplotlib 1.3.5 coming with Anaconda3 (Windows 10, 64bit) and 2.0.0b4 installed with pip into the same Anaconda3.

Following code flashes a window (opens and closes quickly so that nothing can be seen):

```
import matplotlib
matplotlib.use("Qt5Agg")
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(1,1,1)
ax.hist([0,1,1,2,2,3,3,3,3,4,5,6,6,6,7,7,8,8,8,8,8,9])
fig.show()
```

When I change last line to `plt.show()`, then everything works fine.

**Comment by tacaswell** [comment]
Did you mean `v1.5.3`?

This is the expected behavior.  `fig.show()` falls back through to the underlying `QMaiWindow.show` method, however this does not start the Qt event loop.  The flash you see is from the QApp being ripped down as python exits.

`plt.show` (when not in 'interactive mode') starts the event loop and blocks the program until all windows are closed.
