### ISSUE TITLE
Document `get_transform`, `get_data_transform`, `get_patch_transform` for patches

### ISSUE THREAD

**Issue by ondrejdee** [matplotlib/matplotlib#7543]
- matplotlib 1.5.3 (pip install)
- python 2.7.6 (apt-get from ubuntu repository)
- ubuntu 14.04

- issue: if `c` is a handle to a circle, calling `c.set_transform(c.get_transform())` should not change the circle. However (see below) it does. It seems that the size of circle is scaled by its radius in each call, plus there is translation as well. Indeed, the same effects appear with ellipses.  

``` python
import matplotlib as mpl 
import matplotlib.pyplot as plt

colors = ('r', 'g', 'b')
circles = [mpl.patches.Circle((1, 0), .5, color = color) for color in colors]

ax = plt.gca() 
ax.set_xlim(0, 2.5) 
ax.set_ylim(-1, 1) 
ax.set_aspect(1) 

# add all three circles to ax: 
for c in circles: 
    ax.add_artist(c) 

# leave the first one as-is

# transform the second one: 
c = circles[1]
c.set_transform(c.get_transform())

# transform the third one twice: 
c = circles[2]
c.set_transform(c.get_transform())
c.set_transform(c.get_transform())
```
![three_circles](https://cloud.githubusercontent.com/assets/24156020/20792380/b17ea820-b7c1-11e6-871c-6d5971de5e6e.png)

**Comment by tacaswell** [comment]
The issue is that the transform for patches is stored in two parts.  The first part (accessed via `p.get_data_transform` falls back to the `Artist` version of `get_transform` which is what you are trying to get here.  The second part is the 'patch transform' which scales a (typically) unit patch to the correct size.  The two transforms are combined on the way out of `get_transform` (so that things 'just work' with the backends), but doing what you are doing ends up applying the 'patch' transform N times (I understand why it keeps getting smaller, but would have to work through the exact transforms to understand the shift to the left).

To get the behavior you want do the following:

```python
import matplotlib as mpl 
import matplotlib.pyplot as plt

colors = ('r', 'g', 'b')
circles = [mpl.patches.Circle((1, 0), .5, color=color, alpha=.25) for color in colors]

ax = plt.gca() 
ax.set_xlim(0, 2.5) 
ax.set_ylim(-1, 1) 
ax.set_aspect(1) 

# add all three circles to ax: 
for c in circles: 
    ax.add_artist(c)

# leave the first one as-is

# transform the second one: 
c = circles[1]
c.set_transform(c.get_data_transform())

# transform the third one twice: 
c = circles[2]
c.set_transform(c.get_data_transform())
c.set_transform(c.get_data_transform())
```

![so](https://cloud.githubusercontent.com/assets/199813/20823177/e3b5af4c-b81f-11e6-9751-0aeaf1292045.png)


We need to better document this in the docstrings of those functions / in prose.

**Comment by QuLogic** [comment]
> I understand why it keeps getting smaller, but would have to work through the exact transforms to understand the shift to the left

The circle starts at (0, 0) and needs to be moved to the specified (1, 0).

**Comment by QuLogic** [comment]
Unfortunately seems to still need documenting.
