### ISSUE TITLE
Edge cases in eventplot are likely broken

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7560]
The eventplot code currently contains the snippet
```
        if len(lineoffsets) == 0:
            lineoffsets = [None]
        if len(linelengths) == 0:
            linelengths = [None]
        if len(linewidths) == 0:
            lineoffsets = [None] # oops
        if len(linewidths) == 0:
            lineoffsets = [None] # oops
        if len(colors) == 0:
            colors = [None]
```
which is certainly incorrect.

**Comment by dstansby** [comment]
For reference, some code that currently fails:


```
import matplotlib.pyplot as plt
plt.eventplot([1, 2, 3], lineoffsets=[], linelengths=[], linewidths=[], linestyles=[], colors=[])
```

**Comment by tacaswell** [comment]
It is not obvious that this is wrong, these values get passed into an `EventCollection` `__init__` which may use it's default in place of the `None` (but I have not chased down the code path to see if it actually happens).

**Comment by oscargus** [comment]
I hijack this issue as this is also an edge case.

Is `eventplot(1)` supposed to work?

It is handled in the code:
https://github.com/matplotlib/matplotlib/blob/1791022ad019f351ed7f66e05732904dda70af7b/lib/matplotlib/axes/_axes.py#L1263-L1264

But breaks later since the content is not a 1D-array.

Replacing the second line with `positions = [np.asanyarray([positions])]` makes it work, but maybe there should be an error already there?

The docs says:
https://github.com/matplotlib/matplotlib/blob/1791022ad019f351ed7f66e05732904dda70af7b/lib/matplotlib/axes/_axes.py#L1176-L1177

Also, (related from the perspective that I am trying to increase test coverage) these two lines seems impossible to trigger:
https://github.com/matplotlib/matplotlib/blob/1791022ad019f351ed7f66e05732904dda70af7b/lib/matplotlib/axes/_axes.py#L1270-L1271

**Comment by oscargus** [comment]
Considering the original issue, #7602 fixed the copy-paste-error, but was not considered a suitable solution.

What about just deleting those lines? Then there will be an error for empty (not the same length), which is fair enough. Or error already when detected that they are empty? (As they actually do not have to be the same length, just not empty.)

**Comment by timhoffm** [comment]
> Is `eventplot(1)` supposed to work?

I'd say no. It's not documented to work, it does not work and nobody has complained that it should. Making it work would need additional code, documentation and tests. So let's not jump extra hoops here.

**Comment by QuLogic** [comment]
There is an open PR for this #22286; I guess a decision needs to be made there, so I added it to the agenda.
