### ISSUE TITLE
Some properties are set lazily and behaved inconsistently

### ISSUE THREAD

**Issue by lspvic** [matplotlib/matplotlib#7640]
```python
fig, ax = subplots()
ticks = ax.xaxis.get_major_ticks()
print([tick.get_loc() for tick in ticks])
```
always get 
```python
[0, 0, 0, 0, 0, 0]
```
```[tick for tick in ticks if tick.get_loc() > 0] ```behaves unexpected and the document of Tick.get_lock provides nothing about this. Although finally I found  ```[tick for tick,loc in zip(ticks, ax.xaxis.get_majorticklocs() if tick.get_loc() > 0] ``` , Only after the drawing process finished, the property behaves normal, but this could lead beginners to struggle a lot if he want do something with the property before drawing.

Another lazily setting and behaved unexpected property is about ```Spine:get_path```, as below:
```python
fig, ax = subplots()
spine = ax.spines['left']
path = spine.get_path()
print(path)  #path [[0,13],[0,13]], cannot use path to do something
spine._adjust_location()
print(spine.get_path())  # correct after invoke _adjust_location
spine.set_position(('data', .5))
spine._adjust_location()
print(spine.get_path())  # get_path behaves inconsistently and unchanged
#  but spine has been set to other locations.
```

I think it should have the correct property values  without lazily setting when Ticks or Spine are created. Or the document gives some explanations of the ```Tick:get_loc``` or ```Spine.get_path``` method.

**Comment by tacaswell** [comment]
We do need a through write-up of how the tick system works.  In short we keep a pool of tick / ticklabel objects around and at draw time move them around / change their text at draw time via the locator/formatters (see http://matplotlib.org/api/ticker_api.html).  This is because we do not know until draw time some of the things we need to know compute where (or even how many) ticks there will be.

For the spine that is behaving as intended, changing the position changes the transform which is combined with the path at draw time.
