### ISSUE TITLE
Redrawing canvas causes subplot positions to change when aspect='equal' used with rcParams['figure.autolayout'] = True

### ISSUE THREAD

**Issue by ndeadly** [matplotlib/matplotlib#7648]
As the title states, subplots with equal aspect ratio drift around within the figure when the canvas is redrawn with `figure.autolayout ` set. The following code demonstrates the issue

```
import matplotlib.pyplot as plt
plt.rcParams['figure.autolayout'] = True

fig = plt.figure()
ax1 = fig.add_subplot(121, aspect='equal')
ax2 = fig.add_subplot(122, aspect='equal')
fig.canvas.mpl_connect('button_press_event', lambda event: event.canvas.draw())
fig.canvas.set_window_title('Click to redraw canvas')
plt.show()
```

The issue doesn't appear to occur with the default figure size, but if you resize the window horizontally the subplots drift around with each redraw until eventually settling on a position. 

Platform: Windows 7
matplotlib: 1.5.3
python: 2.7.12

**Comment by tacaswell** [comment]
Interesting.  There is obviously some coupled constraints here as the tight_layout code is trying to resize the axes to fill as much of the figure as possible and the equal aspect is trying to resize them so that the ratio between x/y is fixed in both data and screen space.  We apply these constraints in sequence and they have now knowledge of each other.

Calling draw is apparently running a steps of an iterative optimization!

**Comment by efiring** [comment]
Yes, aspect-ratio handling and tight_layout are essentially hacks developed independently to solve two different problems in the absence of any integrated layout system, and in the context of the existing paradigm with most positioning being done in normalized coordinates.

**Comment by jklymak** [comment]
For simple systems layout='compressed' helps a lot with this issue.  For more complex systems you probably need to do the layout by hand.  I'd vote to close this.

**Comment by tacaswell** [comment]
I'm going to close this as no-action.  This is an unintended, but mostly harmless, interaction between two systems that adjust the layout late in the draw cycle.  For back-compatibility reasons we really can not make siginifacnt changes to either and as Jody notes, `layout='constrained'` works correctly in this case:

```python
import matplotlib.pyplot as plt


fig = plt.figure(layout='constrained')
ax1 = fig.add_subplot(121, aspect='equal')
ax2 = fig.add_subplot(122, aspect='equal')
fig.canvas.mpl_connect('button_press_event', lambda event: event.canvas.draw())
# fig.canvas.set_window_title('Click to redraw canvas')
plt.show()
```

In summary: 
 - the bug is mostly harmless
 - fixing it could be very disruptive 
 - we have a new layout system that works better
