### ISSUE TITLE
rc on conda-forge

### ISSUE THREAD

**Issue by ahed87** [matplotlib/matplotlib#7669]
Hi,

I got the below for rc2 (was same with rc1).
It's win64 with latest anaconda install.
Stops me from trying it out.

The following packages will be DOWNGRADED due to dependency conflicts:

    qt:         5.6.0-vc14_0                  [vc14] --> 4.8.7-vc14_9                              [vc14]

PS: Unrelated, but for what it's worth. I have recently seen a bar plot on a py34 install on win64 with rc1 that looked a bit funny. Supposedly it was a conda-forge update on py34/qt4. The bars were clearly not where intended, it seemed like the x-data had changed behaviour to go from left to center of bar, i.e. the bars were offset using same code. I don't have that install so maybe something else was going on, might be worth double checking that before letting 2.0 go.

**Comment by QuLogic** [comment]
> The bars were clearly not where intended, it seemed like the x-data had changed behaviour to go from left to center of bar, i.e. the bars were offset using same code.

This change was intended; bars moved from placed by edge to placed by center.

**Comment by tacaswell** [comment]
@ahed87 See http://matplotlib.org/2.0.0rc2/users/dflt_style_changes.html#bar-and-barh

As for the qt5 vs qt4 issue, that is related to how continuum and conda-forge are dealing with the qt dependency (which has to be pinned due to using PyQt4 vs PyQt5 which ties back to what the default backend is). See https://github.com/conda-forge/matplotlib-feedstock/issues/59.

Try installing from pypi instead (as long as you remove conda's mpl it _should_ work fine), but I recommend testing in an enviroment.

**Comment by ahed87** [comment]
good choice on centered bars!
(I did a quick check in docs when seeing it, but obviously not looking in the right place :-))

regarding qt, thanks for the hints.
