### ISSUE TITLE
Deprecation warning for finance is very unclear

### ISSUE THREAD

**Issue by akkana** [matplotlib/matplotlib#7761]
In 2.0.0~rc2-1 (on debian testing under Python 2.7), either
from matplotlib.finance import quotes_historical_yahoo_ohlc as yahoo
or even just
import matplotlib.finance
prints the following deprecation warning:

MatplotlibDeprecationWarning: The finance module has been deprecated in mpl 2.0 and will be removed in mpl 2.2. Please use the matplotlib toolkit finance instead.

This is very unclear and I have no idea what I need to change. Googling matplotlib toolkit finance yields nothing useful. Googling finance toolkit site:matplotlib.org likewise gives nothing useful. Where is "matplotlib toolkit finance" and how is it different from "matplotlib.finance"? I can't seem to find any mention of the new module or how to use it. Please give a hint in the deprecation message so users know where to look to change their code.

**Comment by jenshnielsen** [comment]
I agree that it should include a link to the repository https://github.com/matplotlib/mpl_finance and that a release should be done of that package on pypi so that it is easy pip installable. I also don't think it should be described as a matplotlib toolkit since it's just a package that uses matplotlib and does not live in the mpl_toolkits namespace

**Comment by ntom** [comment]
Finance module says its been deprecated, and yet the new module, mpl_finance says, "The code is provides as is and it basically un-maintained."  ????

**Comment by tacaswell** [comment]
@ntom We are looking for a maintainer!

**Comment by dmcnic** [comment]
The Finance module is dependent upon the ichart.yahoo.com site. I have noticed it has been offline for the past week with a notice the engineers are working on it. I also received an email with a change of terms notice because of the Verizon purchase of Yahoo. If the Yahoo data source doesn't come back online, there will be more than a maintainer needed to make the module viable. Have there been any discussions about a potential alternative source of data?

**Comment by WeatherGod** [comment]
Most of us are physicists, atmospheric scientists, or statisticians. Feel
free to suggest alternative sources of data. The Yahoo one has been flaky
for many years.

**Comment by tacaswell** [comment]
This discussion should be moved to https://github.com/matplotlib/mpl_finance
