### ISSUE TITLE
fill_between color / facecolor / edegcolor resolution not deterministic

### ISSUE THREAD

**Issue by Zaharid** [matplotlib/matplotlib#7840]
Hatches in the fill_between function are not rendered with the Agg backend.

For example, the following code:

```python
import numpy as np

import matplotlib as mpl
mpl.use("agg")
import matplotlib.pyplot as plt

color = 'blue'
xgrid = np.linspace(0,10,100)
err68up = 2*xgrid
err68down = 3*xgrid
hatch = "///"
alpha=0.3

plt.figure()
plt.fill_between(xgrid, err68up, err68down, color='None', alpha=alpha,
                    edgecolor=color, hatch=hatch, zorder=1)
plt.savefig("test.png")
```
results in an empty figure. However it works as I expect in the pdf or Qt4Agg backends.

I am using the conda-forge matplotlib 1.5.3 package on python 3.5.

**Comment by QuLogic** [comment]
I don't think this is a hatching problem with Agg, but rather some conflicting parameters. `color`+`edgecolor` is ambiguous and it depends on the order of the keyword argument dictionary. Try using `facecolor` instead of `color`.

**Comment by afvincent** [comment]
Have only access to Matplotlib 1.5.1 right now, but @QuLogic may be right, as I got the following exports when replacing `color='None'` with `facecolor='None'`:
PDF
[test.pdf](https://github.com/matplotlib/matplotlib/files/707706/test.pdf)
PNG
[test.png](https://cloud.githubusercontent.com/assets/17270724/21976959/6bf229f8-dbd4-11e6-9f22-4565b98da03d.png)

**Comment by Zaharid** [comment]
Indeed switching `color` with `facecolor` seems to fix the problem for me.

**Comment by tacaswell** [comment]
Re-named this as the bug here is the randomness in the edegcolor / color resolution.  The fix is to use https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/cbook.py#L2513 normalize_kwargs to eliminate all of the aliaces (ec vs edgecolor etc) and to resolve the color / edgecolor / facecolor conflicts consistently (this also requires tracking down where else we do this and making sure the resolution order is consistent).  This normalization should be down as far 'down' the call stack as reasonable.

**Comment by DhrumilSoft** [comment]
I have applied the fix for the color alias and it works for @Zaharid's case. Can you please let me know other aliases for edgecolors and facecolors that need to be normalized?

**Comment by QuLogic** [comment]
Keyword argument normalization was added in #7173.
