### ISSUE TITLE
savefig() renders paths and text differently than show()

### ISSUE THREAD

**Issue by karmel** [matplotlib/matplotlib#786]
After customizing a number of parameters in my matplotlibrc file, I was able to generate figures as desired in with pyplot.show(). However, using pyplot.savefig() with the same parameters resulted in images with thicker lines and bigger fonts, even when the dpi was the same for the default figure and the saved image.

This issue was described by another user here: http://stackoverflow.com/questions/7906365/matplotlib-savefig-plots-different-from-show/9814313

I was able to find a solution for myself as described here: http://stackoverflow.com/questions/7906365/matplotlib-savefig-plots-different-from-show/9814313#9814313

But, it would be really nice if a fix were built in for all the rendering backends, or, alternately, there was at least an easy way to scale paths and fonts so that savefig() and show() resulted in similar images.

**Comment by gepcel** [comment]
I was googling something, and found this closed issue from long time ago. But I've come across this issue multiple times. Can anyone take a look?

The code as following:

```python
mpl.rcParams['font.sans-serif'] = 'SimHei'
d = [19, 14, 8, 21, 17, 10, 16, 11, 8]
cmap=plt.get_cmap('Set1', 6)

fig = plt.figure(dpi=400)
for i, x in enumerate(d):
    plt.bar(i, x, color=cmap(i%3))

ax = gca()
xlim(-0.2, 9)
_ = plt.xticks(range(9), ['合计', '鱼卵', '仔稚鱼']*3, rotation='horizontal')
w = width = ax.patches[0].get_width()

ax.xaxis.set_minor_locator(FixedLocator(np.arange(9)+width/2))
ax.xaxis.set_minor_formatter(FixedFormatter(['合计', '鱼卵', '仔稚鱼']*3))
ax.xaxis.set_major_locator(FixedLocator(np.array([1, 4, 7])+width/2))
ax.xaxis.set_major_formatter(FixedFormatter(['2012年6月', '2013年6月', '2014年6月']))
ax.xaxis.set_tick_params(which='major', pad=17)
ax.xaxis.set_tick_params(which='both', tick1On=False, tick2On=False)
ax.yaxis.set_tick_params(which='both', tick1On=False, tick2On=False, label1On=False)

for r in ax.patches:
    h = r.get_height()
    ax.text(r.get_x()+w/2, h+0.4, int(h), ha='center', va='center')
legend(ax.patches[:3], ['合计', '鱼卵', '仔稚鱼'], loc='upper right')
plt.tight_layout()
fig.savefig('a.png', dpi=fig.dpi)
```

Since I've turned '%matplotlib inline' on, so I got the fig as following(which I supposed is the result of show()):
![image](https://cloud.githubusercontent.com/assets/4179106/12354502/6723ae16-bbd1-11e5-9ea8-5797ffb26ddb.png)

And the 'a.png' from 'savefig()' is as following:
![a](https://cloud.githubusercontent.com/assets/4179106/12354529/931fe80e-bbd1-11e5-9a84-17a8c589c85e.png)

I'm doing some quick plot and formatting, using both 'pyplot' and 'pylab', sorry for the dirty code.
Some backgroud:

    Windows 10;
    matplotlib  '1.5.1rc1'
    python 3.4
    ipython 3.2.1
    %matplotlib inline
    %config InlineBackend.figure_format = 'svg'

**Comment by jenshnielsen** [comment]
@gepcel I don't think your issue is related to this one. The inline backend actually calls savefig behind behind the scenes so what you are seeing is a difference between plt.savefig('a.png') and plt.savefig('a.svg') I am not sure why the Agg backend (which saves pngs) don't handle your fonts correctly but that seems to be what happens. 

Can you open a new issue coping you post from here so that the issue isn't lost

**Comment by gepcel** [comment]
OK. Thanks. @jenshnielsen
