### ISSUE TITLE
Unit length quiver arrow not drawn with a unit length

### ISSUE THREAD

**Issue by dstansby** [matplotlib/matplotlib#7909]
```
import matplotlib.pyplot as plt
import numpy as np

x = 1
y = 0

ux = 0
uy = 1


ax = plt.subplot()
ax.quiver(x, y, ux, uy, angles='xy')
plt.show()
```

I would expect this to plot a single arrow, with the tail at (0 ,1) and the head at (1, 1), but instead it seems to be shrunk and the head is at (1.01, 0):

![figure_1](https://cloud.githubusercontent.com/assets/6197628/22177560/990f8dfc-e018-11e6-92f0-026fc97b4445.png)

Note the values of `ux` and `uy` can be changed to any positive numbers and exactly the same plot is generated.

This is on master, using the MacOSX backend.

**Comment by efiring** [comment]
This is the intended behavior with the defaults for all kwargs.  This entry from the docstring shows how to get the result you are expecting:
```
  *scale_units*: *None*, or any of the *units* options.
    For example, if *scale_units* is 'inches', *scale* is 2.0, and
    ``(u,v) = (1,0)``, then the vector will be 0.5 inches long.
    If *scale_units* is 'width', then the vector will be half the width
    of the axes.

    If *scale_units* is 'x' then the vector will be 0.5 x-axis
    units.  To plot vectors in the x-y plane, with u and v having
    the same units as x and y, use
    "angles='xy', scale_units='xy', scale=1".
```

**Comment by dstansby** [comment]
What does `scale_units` revert to if its value is `None`?

In my head 

> U, V: Give the x and y components of the arrow vectors

should mean that `U, V` are specified in the same dimensions as `X` and `Y`. I can also change the value of `uy` to anything (>0) in my example, and the length of the arrow doesn't change at all which seems odd.

**Comment by dstansby** [comment]
Ah, I see what you mean, but I get the same result setting the `angle` kwarg to `'xy'`, I will update the example above

**Comment by efiring** [comment]
To get the behavior you expect, see the last line I quoted in the docstring fragment; all of these kwargs are needed.  Maybe this should have been the default, but it isn't--I don't think that kind of behavior was even in mind when I originally wrote much of the quiver code, because it doesn't match the sorts of application I had in mind.  Quiver was designed to, by default, make a field of arrows, autoscaled for a "reasonable" size, regardless of whether there are a very large number or a small number (but more than one).  Specifically, I use it for ocean current vectors, so the locations are in completely different coordinates than the magnitudes, and the angles need to be fixed in screen coordinates in some cases, (e.g., a time series of current profiles, with time on the x-axis), or modified to match compass directions on a map in others (as done by Basemap).

**Comment by dstansby** [comment]
Ah sorry for my confusion, I will close this and open a general quiver docstring cleanup issue then if that's okay?

**Comment by efiring** [comment]
Yes, thank you.  The docstring certainly could use work.  The code could, too; it is hard for me to follow, even though I wrote most of it.  It was a long time ago, and the options are mind-boggling.
