### ISSUE TITLE
saving a square image constrained to the extent of axis without any border doesn't work

### ISSUE THREAD

**Issue by gboeing** [matplotlib/matplotlib#7940]
### Bug report

**Bug summary**

I want to save a square image constrained to the extent of my axis without any border around it. However, setting the bbox argument in fig.savefig() does not properly trim the saved image in mpl 2.0.0 as it did in 1.5.3 because ax.get_window_extent() produces different output.

**Code for reproduction**

Here, using mpl 1.5.3, I save a square image constrained to the extent of my axis without any border around it:

```python
# matplotlib 1.5.3
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(4,4), facecolor='c')
ax.set_axis_bgcolor('c')
ax.axis('off')
ax.plot([0,1],[0,1], color='r', linewidth=4)
print(ax.get_window_extent())
print(fig.dpi_scale_trans.inverted())
print(ax.get_window_extent().transformed(fig.dpi_scale_trans.inverted()))
extent = ax.get_window_extent().transformed(fig.dpi_scale_trans.inverted())
fig.savefig('test.png', dpi=200, bbox_inches=extent, format='png', facecolor=fig.get_facecolor(), transparent=True)
```
Produces:
```
TransformedBbox(Bbox([[0.125, 0.125], [0.9, 0.9]]), BboxTransformTo(TransformedBbox(Bbox([[0.0, 0.0], [4.0, 4.0]]), Affine2D(array([[ 72.,   0.,   0.],
       [  0.,  72.,   0.],
       [  0.,   0.,   1.]])))))
Affine2D(array([[ 0.01388889,  0.        ,  0.        ],
       [ 0.        ,  0.01388889,  0.        ],
       [ 0.        ,  0.        ,  1.        ]]))
Bbox(x0=0.5, y0=0.5, x1=3.5999999999999996, y1=3.5999999999999996)
```
![mpl 1.5.3](https://i.imgur.com/Gi6PVWa.png)

This correctly trims the saved figure to the extent of the axis (using mpl 1.5.3) and the dimensions are square (619x619).

However...

```python
# matplotlib 2.0.0
import matplotlib.pyplot as plt
fig, ax = plt.subplots(figsize=(4,4), facecolor='c')
ax.set_facecolor('c')
ax.axis('off')
ax.plot([0,1],[0,1], color='r', linewidth=4)
print(ax.get_window_extent())
print(fig.dpi_scale_trans.inverted())
print(ax.get_window_extent().transformed(fig.dpi_scale_trans.inverted()))
extent = ax.get_window_extent().transformed(fig.dpi_scale_trans.inverted())
fig.savefig('test2.png', dpi=200, bbox_inches=extent, format='png', facecolor=fig.get_facecolor(), transparent=True)
```
Produces:
```
Bbox(x0=32.5, y0=32.5, x1=262.7, y1=256.94)
Affine2D(array([[ 0.01388889,  0.        ,  0.        ],
       [ 0.        ,  0.01388889,  0.        ],
       [ 0.        ,  0.        ,  1.        ]]))
Bbox(x0=0.45138888888888884, y0=0.45138888888888884, x1=3.648611111111111, y1=3.5686111111111107)
```
![mpl 2.0.0](https://i.imgur.com/Mjxe74D.png)

This (mpl 2.0.0) does not trim the saved figure to the correct extent (as in did in 1.5.3) and the dimensions are not square (639x623).

How can I trim this saved figure's extent using mpl 2.0.0 like I did in the past using 1.5.3?

**Matplotlib version**

- matplotlib 2.0.0 (and 1.5.3 for comparison), Python 3.5, Windows 64bit
- installed via anaconda

**Comment by QuLogic** [comment]
This is really more of a mailing list question, but there are a couple of reasons:
 * It is not square because you didn't really ask it to be. Use `ax.set_aspect('equal')` to get a square axis, followed by `fig.canvas.draw()` to re-calculate the sizes correctly.
 * The extra margins are on purpose (which is a bit more evident if you start drawing the axis), but they can be turned off with `ax.margins(0)`.
 * There's still a little gap, and that's because the ticks are facing outward and still contribute to the Axes extent even though they aren't visible. You can make them face inward with `ax.tick_params(which='both', direction='in')`.

With those changes, you get a square plot just like 1.5.3, though with a slightly different size:
![test](https://cloud.githubusercontent.com/assets/302469/22273582/8b3a73aa-e26f-11e6-9f2f-0559b31e1b3a.png)
I haven't tried with 1.5.3, so I'm not sure why the size is a bit different; possibly it's rounding error due to different DPI.

**Comment by gboeing** [comment]
Thanks. That works well. I'll update all my code using mpl 2.0.0 accordingly to replicate the former 1.5.3 behavior.
