### ISSUE TITLE
gridlines from secondary axis above data

### ISSUE THREAD

**Issue by nschloe** [matplotlib/matplotlib#7984]
In plots with a secondary y-axis, the grid lines of the second axis aren't below the data (as opposed to the grid lines of the primary axis). This becomes very visible with stackplots and styles like `ggplot` or `seaborn`.

MWE:
```python
from matplotlib import pyplot as plt
plt.style.use('ggplot')

x = [1, 2, 3]
y = [1, 2, 3]
plt.stackplot(x, y)

ax1 = plt.gca()
ax2 = ax1.twinx()

plt.show()
```
![figure_1](https://cloud.githubusercontent.com/assets/181628/22408764/9c3ad51a-e67e-11e6-8948-fe1a4e603f80.png)

**Comment by dstansby** [comment]
I've had a bit of a look into this but am a bit stuck. I think this is something to do with `zorder` not really working properly. One workaround is to explicitly set `zorder=2` on the stack plot:

```python
[stack] = ax.stackplot(x, y)
stack.set_zorder(2)
```

**Comment by nschloe** [comment]
Thanks for the hint! Unfortunately,
```python
import matplotlib.pyplot as plt
plt.style.use('ggplot')

x = [1, 2, 3]
y = [1, 2, 3]
[stack] = plt.stackplot(x, y)
stack.set_zorder(2)

ax1 = plt.gca()
ax2 = ax1.twinx()

plt.show()
```
doesn't do the trick either.

**Comment by efiring** [comment]
When the Figure is drawn, its Axes are sorted based on zorder with a stable sort, and then drawn in that order.  Then within each Axes, artists are sorted based on zorder.  Therefore you can't interleave the drawing orders of artists from one Axes with those from another.

What is the result you actually want?  Do you really want the grid from ax2 on top of the grid from ax1?

Note that twinx sets the visibility of the ax2 patch to False; it is transparent, so that whatever is plotted on ax1 shows through.

Maybe what you want is achieved by making your stackplot in ax2 instead of ax1?

In any case, we are not dealing with a bug here, but with the basic design of mpl.

**Comment by nschloe** [comment]
Thanks @efiring for the comment.

Indeed, plotting the data in `ax2` fixes it:
```python
from matplotlib import pyplot as plt
plt.style.use('ggplot')

ax1 = plt.gca()
ax2 = ax1.twinx()

x = [1, 2, 3]
y = [1, 2, 3]
plt.stackplot(x, y)

plt.show()
```
![figure_1](https://cloud.githubusercontent.com/assets/181628/26538643/66aac61c-4448-11e7-8181-564c09485129.png)

It's a little funny that it shouldn't work if added to the first axis, but this behavior apparently is woven into mpl. Let's close this.

**Comment by colinfang** [comment]
Inspired by the explanation from @efiring  , I tend to do this

```python

x = [1, 2, 3]
y = [1, 2, 3]
plt.stackplot(x, y)

ax1 = plt.gca()
ax2 = ax1.twinx()

ax2.set_zorder(-1)
ax.patch.set_visible(False)
ax2.patch.set_visible(True)
    
plt.show()
```

![image](https://user-images.githubusercontent.com/1499555/65684095-b4677880-e056-11e9-8c66-0ecb6c2243d7.png)
