### ISSUE TITLE
Coordinates of text not properly set in pgf files

### ISSUE THREAD

**Issue by JakobJakobson** [matplotlib/matplotlib#8067]
**Bug summary**
The coordinates of text (legends, titles) are not properly set in pgf files.

**Code for reproduction**
Producing the pgf figure with a slightly altered pylab_examples "tex_demo.py":

```python
import numpy as np
import matplotlib.pyplot as plt

plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.figure(1, figsize=(6, 4))
ax = plt.axes([0.1, 0.1, 0.8, 0.7])
t = np.linspace(0.0, 1.0, 100)
s = np.cos(4 * np.pi * t) + 2
plt.plot(t, s)
plt.xlabel(r'\textbf{time (s)}')
plt.ylabel(r'\textit{voltage (mV)}', fontsize=16)
plt.title(r"\TeX\ is Number $\displaystyle\sum_{n=1}^\infty"
          r"\frac{-e^{i\pi}}{2^n}$!", fontsize=16, color='r')
plt.grid(True)
plt.savefig('tex_demo.pgf')    # altered line
plt.show()
```

Taking this pgf file ("tex_demo.pgf") in my latex file:

```latex
\documentclass{article}
\usepackage{pgf}
\begin{document}
\input{tex_demo.pgf}
\end{document}
```

**Actual outcome**
This gives the output "Bugreport.pdf".
[Bugreport.pdf](https://github.com/matplotlib/matplotlib/files/769449/Bugreport.pdf)

**Expected outcome**
The graphic should look like in the example:
http://matplotlib.org/examples/pylab_examples/tex_demo.html

**Matplotlib version**
- Matplotlib 1.5.2rc2, Python 3.5.2 and Fedora 25 (Workstation Edition)
- All components were installed via the Fedora specific system tools (dnf) from Fedora repositories

**Comment by tacaswell** [comment]
attn @pwuertz

**Comment by pwuertz** [comment]
I assume what is happening here is that matplotlib uses a fixed position for titles and legends and aligns them by their baseline. As far as I can remember the traditional matplotlib backends never took baseline offset of LaTeX elements into account. This means that text rendered via LaTeX is simply shifted upwards so the bottom of the text box sits on the baseline, which is actually incorrect but wouldn't result in this overlap you are seeing now (hence nobody identifies this as incorrect behaviour).

I'm pretty sure the font metrics returned from the PGF backend are correct, especially the alignment of the baselines. So what is probably happening here is that matplotlib by default baseline-alignes the LaTeX text at the fixed title position, the large formula goes way below the baseline and overlaps with the figure. Matplotlib won't automatically adapt the figure layout for you, even if text elements are larger/overlapping.

Perhaps `tight_layout` is able to clean up such situations, but its magic is limited. You could also try to align such large texts by bottom instead of base alignment, which should get rid of the overlap.

**Comment by JakobJakobson** [comment]
Thanks for the response. Using the modification

plt.title(r"\TeX\ is Number $\displaystyle\sum_{n=1}^\infty"
          r"\frac{-e^{i\pi}}{2^n}$!", fontsize=16, color='r', verticalalignment='bottom')

helps with this issue.

**Comment by JakobJakobson** [comment]
Sorry, I accidently closed the issue without your consent. If you consider it closed, close it again.

Regards Jakob
