### ISSUE TITLE
Inconsistency between " and ' in the code

### ISSUE THREAD

**Issue by Naereen** [matplotlib/matplotlib#8079]
Hi,
That's not a bug per say, but I noticed a strong inconsistency in the codebase between strings with simple and double quotes.
For instance, see [that line (`def hist` in `_axes.py`)](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L5903):
```python
@_preprocess_data(replace_names=["x", 'weights'], label_namer="x")
```
I don't think there is a semantic reason for this difference between `"x"` and `'weights'` (if there is, it's not clear).

If a maintainer thinks this should be corrected, I think a carefully designed regexp and `sed` command line can do the job quickly.

**Comment by tacaswell** [comment]
The inconsistency is not great, but basically harmless.

I am deeply skeptical of massive automated changes like this.  We do not have 100% test coverage so it may introduce bugs we miss on review, they are hard to review (do to large number of almost trivial changes), and I do not see much of a pay-off on this.

In some cases the `'` or `"` as the outer quote is to due to wanting to use the other one inside which may pose some difficulty with the regex.

**Comment by WeatherGod** [comment]
I really have never cared about consistency with quote marks myself,
especially since my editor colors them the same anyway. Even if we were to
"fix" this, it'll still creep back in as the library gains more changes
unless we put in an automated tool to check for that. While I am a huge fan
of PEP8, I think including consistent quote marks into the review process
would turn off contributors as it would definitely come across as
nit-picking.

On Wed, Feb 15, 2017 at 10:24 AM, Thomas A Caswell <notifications@github.com

**Comment by Naereen** [comment]
I agree it should not be made automatic, and not be enforced.

But maybe it could at least be fixed in the actual codebase?
It feels weird to see both `"..."` and `'...'` on the same line.

**Comment by dopplershift** [comment]
I like enforcing the consistency (by which I mean `'`) in my own project--I would not go back and make a massive change to matplotlib.

If for some reason we were to want to enforce this, there's the `flake-quotes` plugin for `flake8`, which we could run with `pytest-flake8`.

**Comment by Naereen** [comment]
@dopplershift Great, I wasn't aware of that plugin.

OK for not brutally changing anything.

**Comment by anntzer** [comment]
It looks like the agreement is to close the issue.
