### ISSUE TITLE
Request: function for plotting with error bands

### ISSUE THREAD

**Issue by beojan** [matplotlib/matplotlib#8184]
Currently, matplotlib provides an interface for plotting a curve with error bars at the data points. However, plotting errors as a shaded band requires explicitly using `fill_between` and specifying colors rather than relying on the color cycle. Can we have a similar high-level interface for error bands, that automatically uses the same color as the line (with a provided alpha value)?

**Comment by anntzer** [comment]
I think a reasonable improvement would be to make `fill_between{,x}` follow the color cycle as well (I don't see any reason not to).

**Comment by beojan** [comment]
That would mean the error band and the centre line have neighboring colors from the cycle rather than a transparent version of the same color.

**Comment by anntzer** [comment]
True.  OTOH I've always wanted to have some way to not advance the color cycle (which is would be more generally useful), e.g.
```
with do_not_advance("axes.prop_cycle"):
   ax.plot(...)
   ax.plot(...)
```

**Comment by beojan** [comment]
That would be useful, but I think an errorband implementation compatible with the error bar implementation (so it can be used with histograms in 'step' mode, and so on) would be preferable.

**Comment by ruijpbastos** [comment]
If you're using custom colors, I guess it's easy to use the same color for the error band. If you're going with the color cycle, the `fill_between` appears to just follow the color cycle independently ([example](https://gist.github.com/ruijpbastos/2704166a133da62084f6894b15b7202e)), so I guess you just need to plot the confidence bands immediately after your plot and then order your plots to make sure that the ones with confidence bands are plotted first.

I can see, however, how it would just be easier to have an option when plotting to include error bands. Don't know if it's worth the trouble, though.

**Comment by timhoffm** [comment]
Using `plot()` and `fill_between()` consecutively plays nicely with the colorcycle:
~~~
x = np.linspace(-5, 5, 101)
y = 2 * x
y2 = 3.5* x - 3
err = 1 + 0.2 * x**2

fig, ax = plt.subplots()
ax.plot(x, y)
ax.fill_between(x, y - err, y + err, alpha=0.2)
ax.plot(x, y2)
ax.fill_between(x, y2 - err, y2 + err, alpha=0.2)
~~~

![grafik](https://user-images.githubusercontent.com/2836374/100153031-db604b00-2ea3-11eb-9d16-e325a28b7c3d.png)


You can create a simple helper for this if you want, e.g.:

~~~
def errorband(x, y, err, ax=None, **kwargs):
    if ax is None:
        ax = plt.gca()
    ax.plot(x, y, **kwargs)
    ax.fill_between(x, y - err, y + err, alpha=0.2)

fig, ax = plt.subplots()
errorband(x, y, err)
errorband(x, y2, err)
~~~

Creating such helpers to customize and simplify your plotting is a pattern we explicitly encourage.

I'm reluctant to make this a core Matplotlib function though, because the API gets quite unwieldy. You'd have to include all `plot()` and  `fill_between()` parameters, i.e. configuring the center and the filled region.

**Comment by timhoffm** [comment]
Closing for now as "won't fix".

You are still welcome to upvote and add further comments. We may revisit later if this gets more traction.

**Comment by story645** [comment]
Also, seaborn implements bands as part of it's lineplot: https://seaborn.pydata.org/generated/seaborn.lineplot.html
![image](https://user-images.githubusercontent.com/1300499/100156742-71ca4780-2e77-11eb-95db-c1550248b829.png)
