### ISSUE TITLE
Legend does not show 'annotate'

### ISSUE THREAD

**Issue by jlecoeur** [matplotlib/matplotlib#8236]
When using `annotate` to draw an arrow, it does not show up in the legend.

Example code:
```python
import matplotlib.pylab as plt
%matplotlib inline

fig, ax = plt.subplots(1)
ax.plot([0, 1], [0, 0], label='line1')
ax.plot([0, 1], [1, 1], label='line2')
ax.annotate("",
            xy=(0.4,1.0),
            xytext=(0.4,0.0),
            arrowprops={'arrowstyle':'<->', 'color':'C7' },
            label='distance')
ax.legend()
```
gives:
![annotate](https://cloud.githubusercontent.com/assets/1379463/23705362/c466052a-0409-11e7-886a-45e28b55fb7f.png)

I would expect an entry "distance" in the legend, with a grey double-sided arrow as symbol.

(I use Python 3.6.0 and Matplotlib 2.0.0 from Archlinux repository)

**Comment by tacaswell** [comment]
Because they are not in the list of things the that are looked for to be added to the legend by default. Start from https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/axes/_axes.py#L546 and trace back.

You will probably also have to add a LegendHandler.

Exact work:

 - get annotations to be included in the list of artists found by `Axes.get_legend_handles_labels`
 - write a legend handler to display annotations in a nice way.

@jlecoeur want to take a crack at this?

**Comment by tacaswell** [comment]
Tagged as new contributor friendly because it is self-contained, but medium difficulty as it involves understanding the legend machinery (which is powerful, but a bit under-documented).

**Comment by bendichter** [comment]
Would the best approach here be to create HandlerFancyArrowPatch in legend_handler.py that handles fancy arrow patches in general, and then a HandlerAnnotation that takes an Annotation object and calls HandlerFancyArrowPatch if the annotation has an arrow associated with it?

**Comment by jlecoeur** [comment]
Thanks @bendichter @tacaswell, I will try to implement it and I'll let you know!
