### ISSUE TITLE
Invalid certificate at https://matplotlib.org.

### ISSUE THREAD

**Issue by duesee** [matplotlib/matplotlib#8302]
Don't know where to report it, but the certificate of https://matplotlib.org/ is only valid for *.github.com, github.com and *.github.io. Therefore users get a security warning.

**Comment by phobson** [comment]
Interesting. I normally go to http://matplotlib.org instead. I didn't know there was an https version.

**Comment by QuLogic** [comment]
GitHub Pages do not support TLS on custom domains, unfortunately.

**Comment by QuLogic** [comment]
GitLab Pages _would_ support it, for free with Let's Encrypt if we wanted to mirror the docs there (not too difficult, but might need a bit of care for initial setup.)

Also, a CloudFlare cache in front could do pseudo-TLS.

**Comment by duesee** [comment]
I am not quite sure what you are talking about, since I don't know how the GitHub Pages work, sorry :-) But I would recommend to disable the https version as long as there is no fix available. The reason is, that firefox makes it rather difficult to skip invalid certificate errors (for a good reason) and basically users with an active HTTP-everywhere plugin get locked out.

**Comment by tacaswell** [comment]
@duesee where did you find the https version?

**Comment by duesee** [comment]
The https version came up when googling "matplotlib pyplot tutorial". The search result `pyplot - matplotlib` refers to the https version.

**Comment by tacaswell** [comment]
Well, that is less than great....I was hoping it was a link someplace we could get fixed...

**Comment by tacaswell** [comment]
I have reached out to github support, will send an email to the dev list looking for someone who understands this stuff and can take point from our side.

**Comment by nicktimko** [comment]
On balance, Google "accidentally" linking to the HTTPS version of a page that's broken is one way to speed uptake of HTTPS among domain operators.

**Comment by jkseppan** [comment]
I'll copy what I wrote on the mailing list:

I have set up a CloudFlare front for another organization's GitHub pages, and did not find it difficult at all with all the instructions available online. I suspect that the hardest thing will be the management of credentials. Whoever does this will need access to the domain registrar to change the DNS records, and to our CloudFlare account (we'll need to set one up). *Then* these credentials need to be stored so that if there is some problem later and the person who does this now is not around to help, someone else can help. Also, when pages are changed on the site, it's useful to be able to invalidate CloudFlare caches.

I'm willing to help, but I don't know where to store the passwords or who to talk to about the domain registrar. Do we have something in place for the credentials of existing accounts, such as the GitHub matplotlib account, our Twitter handle, etc?

**Comment by jkseppan** [comment]
One way for https links to get generated is if someone uses the HTTPS Everywhere browser extension, ignores the certificate errors and posts links somewhere that Google can see them. Certainly this will speed up the adoption of any solution that gets you a nice green lock icon in the browser address bar, but currently the easiest such solution is Cloudflare's free tier, which turns them into the site where most SSL encryption terminates. It's probably a net win in security compared to completely unencrypted connections but shouldn't be mistaken for end-to-end encryption.

**Comment by tacaswell** [comment]
This should now be fixed (Thanks @jkseppan for taking care of this!)
