### ISSUE TITLE
Artifact at border with tricontourf and float32 positions

### ISSUE THREAD

**Issue by stefanstoeckl** [matplotlib/matplotlib#8355]
### Bug report
With a non-rectangular grid and using tricontourf under certain circumstances (see below) there appear too high values at the border, but only if the coordinates have dtype=float32, not with float64.

**Code for reproduction**
```python
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm
# DATA CREATION
nx = 21
xx32 = np.zeros((nx, 51), dtype=np.float32)
yy32 = np.zeros((nx, 51), dtype=np.float32)
xx64 = np.zeros((nx, 51), dtype=np.float64)
yy64 = np.zeros((nx, 51), dtype=np.float64)
c1 = np.zeros((nx, 51), dtype=np.float32)
arcmax = [2.98145599e+02, 7.95787903e+02, 4.01827979e+03, 1.04372139e+04,
          6.40266260e+03, 2.09335645e+03, 1.34447083e+03, 8.78844849e+02,
          6.10013123e+02, 4.49552063e+02, 3.47982056e+02, 2.71610840e+02,
          2.14410492e+02, 1.73040222e+02, 1.40513336e+02, 1.14466042e+02,
          9.48751144e+01, 8.04448853e+01, 6.70684586e+01, 5.69564018e+01,
          4.89454384e+01]
sy = [0.01,  0.8158474,  2.92461777,  7.07167196, 14.83065224,
      21.79951477, 27.91436768, 36.08686066, 42.10681152, 47.50948334,
      51.89228439, 55.50826263, 58.47971344, 61.91854095, 65.29727173,
      68.90505981, 72.35230255, 76.10240936, 80.18096161, 84.58132172,
      88.53439331, 92.99449921, 97.21809387, 101.78314209, 106.35783386,
      111.00331879]
for i in range(0, nx):
    for j in range(0, 51):
        phi = (j - 25) * 2.5 * np.pi / 180.
        r = 110. / 80. * i**2
        xx32[i, j] = r * np.cos(phi)
        yy32[i, j] = r * np.sin(phi)
        xx64[i, j] = r * np.cos(phi)
        yy64[i, j] = r * np.sin(phi)
        c1[i, j] = (arcmax[i] / (2 * np.pi * sy[i]) *
                    np.exp(-(r * phi)**2 / (2. * sy[i]**2))) + 1
xx32 = xx32.flatten()
yy32 = yy32.flatten()
xx64 = xx64.flatten()
yy64 = yy64.flatten()
c1 = c1.flatten()
clevels = np.logspace(int(np.floor(np.log10(1))),
                      int(np.ceil(np.log10(c1.max()))), 200)
# FIGURE
fig = plt.figure(0)
# ax1
ax1 = fig.add_subplot(321)
im1 = ax1.scatter(xx32, yy32, c=c1, s=0.3, cmap='copper_r', norm=LogNorm())
fig.colorbar(im1)
ax1.set_title('32 bit locations: data')
# ax2
ax2 = fig.add_subplot(322)
im2 = ax2.scatter(xx64, yy64, c=c1, s=0.3, cmap='copper_r', norm=LogNorm())
fig.colorbar(im2)
ax2.set_title('64 bit locations: data')
# ax3
ax3 = fig.add_subplot(323)
im3 = ax3.tricontourf(xx32, yy32, c1, 200, cmap='copper_r')
fig.colorbar(im3)
ax3.set_title('32 bit locations: tricontourf linear - BUG?')
# ax4
ax4 = fig.add_subplot(324)
im4 = ax4.tricontourf(xx64, yy64, c1, 200, cmap='copper_r')
fig.colorbar(im4)
ax4.set_title('64 bit locations: tricontourf linear - OK')
# ax5
ax5 = fig.add_subplot(325)
im5 = ax5.tricontourf(xx32, yy32, c1, cmap='copper_r',
                      norm=LogNorm(), levels=clevels)
fig.colorbar(im5)
ax5.set_title('32 bit locations: tricontourf log - BUG?')
# ax6
ax6 = fig.add_subplot(326)
im6 = ax6.tricontourf(xx64, yy64, c1, cmap='copper_r',
                      norm=LogNorm(), levels=clevels)
fig.colorbar(im6)
ax6.set_title('64 bit locations: tricontourf log - OK')

plt.tight_layout()
plt.show()
```

**Actual outcome**
![tricontourf_bug](https://cloud.githubusercontent.com/assets/16414280/24140923/ff51ddd6-0e21-11e7-8bc2-51c9cc03cf18.png)
In the panels at the middle left and and bottom left a "line" of high values at the border is visible.

**Expected outcome**
As you can see in the top row of the figure, the data has a maximum near the origin and levels off towards the borders and the right. There are no high values near the border.
The expected outcome can be see in the panels at the middle right and bottom right, where no high value "lines" are visible at the borders.
The only difference between the left side and the right side is the data type of the position vectors: float32 at the left and float64 at the right.
Converting the already calculated float64-coordinates to float32 also leads to the 'lines', whereas the reverse does not remove them.
The problem also happens for SymLogNorm-norming (not shown), so the norm probably doesn't play a role. It's just much more visible in a log-scale.

**Background**
The dataset is an artificial, exaggerated example of model output, which is in float32. That's where I found the artifacts first. Then I created the artificial dataset in Python (default float64) and the "lines" disappeared. It wasn't easy to find a dataset that recreates the problem, hence the elaborate code for that. The maximum at (or near) the origin is necessary for the "lines" to appear.
If you wonder why anyone would create such a grid: it's not a computational grid, just for postprocessing. The the arcs are needed,  rectangular matrices a lot easier to handle, and most of the interesting stuff happens a little bit away from the origin.

The obvious workaround for me is to recreate my position vectors in float64, but I though I'd file a bug report too.

**Matplotlib version**
- Ubuntu 14.04
- matplotlib 2.0.0 (from pip)
- numpy 1.12.0 (from pip)
- Python 2.7.6 with GCC 4.8.2 (from Ubuntu repositories)

**Comment by ianthomas23** [comment]
@stefanstoeckl Thanks for the clear example.

All internal calculations are performed using float64, so your float32 arrays are copied to new float64 arrays when you call tricontourf.

As your calls to tricontourf do not include an array of triangle indices, you are asking matplotlib to create a Delaunay triangulation for you.  This uses qhull under the hood.  Using float64 this is giving you what you expect to see.  Using float32, the 'straight' edges of your regions of interest are actually slightly concave due to finite numerical precision inherent in all computers.  This slight concavity causes qhull to create a very slim triangle along each of the straight edges.  The slim triangle has a very high value on the left and a low value on the right, hence contouring some intermediate value will result in drawn pixels in the slim triangle.  Tricontourf is correctly contouring the triangles it is given, and qhull is doing the best job it can of triangulating your limited-precision vertices.

If you tinkered with the locations of your vertices slightly you could probably get the problem to disappear and reappear again.  If you tried the same problem on different hardware, or even the same hardware but a different numpy/matplotlib compiler or different compiler flags you could get different results.

You should indeed use float64 for your vertices.  Any form of computational geometry should be performed at 64-bit precision.  If you were using 32-bit floats to save memory then don't bother - float32 arrays are copied to float64 within tricontour whereas float64 arrays are used without modification so that using float32 arrays actually uses more memory.

As an aside, I'm sure you wouldn't normally use more than one tricontourf call with the same x and y arrays as in your example code, but for the benefit of others who read this issue, instead of using

    ax1.tricontourf(x, y, z, ...)
    ax2.tricontouf(x, y, z, ...)

you should instead create a single triangulation and reuse it, like
 
    import matplotlib.tri as mtri
    triang = mtri.Triangulation(x, y)
    ax1.tricontourf(triang, z, ...)
    ax2.tricontourf(triang, z, ...)

as it will be faster and require less RAM.

**Comment by stefanstoeckl** [comment]
@ianthomas23 
Thank you very much for your detailed reply. Especially for the `Triangulation`-trick, I had not know that.
I use 32-bit because that's the output of my Fortran model. On my current hardware/compiler using 32-bit is about 20% faster than 64-bit and the model isn't sensitive to the precision.

I'm closing this issues, since your explanation makes perfect sense, the "problem" is therefore not a bug and I know how to work around it.
