### ISSUE TITLE
restore rebase documenation

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#8398]
This content is no longer on the master branch, not sure if it is also gone from 2.0.x

http://matplotlib.org/devel/gitwash/development_workflow.html?highlight=rebase#rebasing-a-pull-request-pr

This needs to be put back.

**Comment by tacaswell** [comment]
https://github.com/matplotlib/matplotlib/pull/2742 <- most of this content is gone

**Comment by tacaswell** [comment]
Looks like this is a result of #8137

**Comment by choldgraf** [comment]
Just a quick thought on this text - it might be worth highlighting the interactive rebase earlier on. This is probably going to be more useful for committers who are asked to squash before merge.

Right now it's in a section after the first mention of rebase:

http://matplotlib.org/devel/gitwash/development_workflow.html?highlight=rebase#rewriting-commit-history

It isn't the easiest to discover. Maybe the rebase section just needs a "see <link> for more ways to rebase", or maybe just adding in the words "squash before merge" etc so that people can ctrl+f it more easily. WDYT?

**Comment by tacaswell** [comment]
Which text is 'this text'?

Compare what we publish now with https://github.com/tacaswell/matplotlib/blob/9efe5e36b57bf11fb2bfd7e9229c06656fd10bff/doc/devel/gitwash/development_workflow.rst

**Comment by choldgraf** [comment]
I'm just saying that if I were a new user opening a PR, looking for an explanation of how to squash a bunch of commits before merging, then this:

http://matplotlib.org/devel/gitwash/development_workflow.html?highlight=git%20rebase#rewriting-commit-history

is what I should use, but it'd be hard for me to find it. I think if the words "squash and merge" or something like this were in there, it'd be easier to find, `ctrl+f` for, etc. Also I think if there were something like

```
.. note::
   For interactive rebasing (used to squash multiple commits together),
   see :ref:`rewriting-commit-history`.
```
in this section:

http://matplotlib.org/devel/gitwash/development_workflow.html?highlight=git%20rebase#rebasing-on-trunk

it'd be easier to find

**Comment by tacaswell** [comment]
https://github.com/matthew-brett/gitwash/pull/13 ports the missing text to upstream gitwash.

**Comment by timhoffm** [comment]
Done per https://github.com/matplotlib/matplotlib/issues/8398#issuecomment-1608273409.
