### ISSUE TITLE
Insufficient OS/X installation Documentation

### ISSUE THREAD

**Issue by nanodots** [matplotlib/matplotlib#8433]
To help us understand and resolve your issue, please fill out the form to the best of your ability. You can feel free to delete the sections that do not apply.

### Bug report

**Bug summary**

OSX 10.12.3 first attempt to install failed

>pip install --user matplotlib
```
   error: command 'clang' failed with exit status 1
    
    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/private/var/folders/m4/sdh_jsyx3vvf2hq3m19x06mr0000gn/T/pip-build-09cla8/subprocess32/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/m4/sdh_jsyx3vvf2hq3m19x06mr0000gn/T/pip-plIr2B-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/var/folders/m4/sdh_jsyx3vvf2hq3m19x06mr0000gn/T/pip-build-09cla8/subprocess32/
```

after several web searches, Xcode tools needed to be updated:

>xcode-select --install

It would be nice to put this somewhere on the SCIPY installation page instructions
https://scipy.org/install.html

**Comment by story645** [comment]
If you want that added to the scipy docs, then I suggest you open a bug report on https://github.com/scipy/scipy/issues

**Comment by anntzer** [comment]
I'm more curious why this doesn't pick up the macos wheel that is present on pypi...

**Comment by matthew-brett** [comment]
I'm curious about the wheel as well.   What do you get for:

```
pip --version
```

Do you get the wheel if you do:

```
# Install latest pip as user
pip install --user --upgrade pip
# Make sure new version of pip is read from PATH
hash -r
# Check pip version (may need to add user install bin dir on PATH)
pip --version
# Try mpl install again
pip install --user matplotlib
```

**Comment by matthew-brett** [comment]
From the discussion over at https://github.com/scipy/scipy/issues/7270 - this is probably an error caused by `subprocess32`, which doesn't have any wheels on OSX or Linux, and doesn't show any signs of activity suggesting that they will be uploaded any time soon, despite the fact that I already made automated build scripts for them : https://github.com/google/python-subprocess32/issues/14 .

See the original report, where the long error line ends with `subprocess32` : 
https://github.com/matplotlib/matplotlib/issues/8433#issue-219737922
