### ISSUE TITLE
Default ScalarFormatter ignores usetex font setting

### ISSUE THREAD

**Issue by ImportanceOfBeingErnest** [matplotlib/matplotlib#8436]
The default ScalarFormatter for axes ignores font setting when used with `usetex = True`.

Consider the following example, where we use latex and set the font-family to 'sans-serif':

```
import matplotlib.pyplot as plt 

plt.rc( 'text', usetex=True ) 
plt.rc('font',family = 'sans-serif',  size=20)

fig , ax = plt.subplots(figsize=(5,3))

ax.set_xlabel( r'\textit{x} in a.u.' )
ax.set_ylabel( r'\textit{y} in a.u.' )

plt.tight_layout()
plt.show()
```
resulting in this image:
![image](https://cloud.githubusercontent.com/assets/23121882/24748697/ca3f9c0e-1ac0-11e7-879f-b1c00f192d84.png)

As can be seen, the axis labels are in sans-serif font. However, the ticklabels are unexpectedly still in serif font. 

The reason seems to be the ScalarFormatter in use. If we change the formatter to e.g. a `StrMethodFormatter`, we get the expected result:

```
import matplotlib.pyplot as plt 
import matplotlib.ticker

plt.rc( 'text', usetex=True ) 
plt.rc('font',family = 'sans-serif',  size=20)

fig , ax = plt.subplots(figsize=(5,3))

ax.set_xlabel( r'\textit{x} in a.u.' )
ax.set_ylabel( r'\textit{y} in a.u.' )

fmt = matplotlib.ticker.StrMethodFormatter("{x}")
ax.xaxis.set_major_formatter(fmt)

plt.tight_layout()
plt.show()
```
![image](https://cloud.githubusercontent.com/assets/23121882/24748915/890105ba-1ac1-11e7-84c5-73b3b9258e53.png)

Since the use of a ScalarFormatter is desirable for many applications, I think this should be fixed.

**Comment by jkrumbiegel** [comment]
I've found the culprit for this behavior, after struggling with the problem myself for quite some time. In the file ticker.py and the class ScalarFormatter, there is a method _set_format(). This method checks if tex is used and formats accordingly:
`if self._usetex:`
`    self.format = '$%s$' % self.format`
The dollar signs cause the behavior because they mark the tick label numbers as a LaTeX math string. I deleted them and now it works as expected.
