### ISSUE TITLE
pep8 not running on examples on master

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#8498]
https://github.com/matplotlib/matplotlib/pull/8324 passed on master, but failed when backported to 2.0.x
https://travis-ci.org/matplotlib/matplotlib/jobs/222656753

**Comment by QuLogic** [comment]
Odd, I can see it being installed and the argument specified, and it properly fails locally too.

**Comment by QuLogic** [comment]
The test count is definitely off; I get 717 more tests run locally when using `--pep8`, so it looks like most files are not being checked.

**Comment by tacaswell** [comment]
It might not be running at all, https://github.com/matplotlib/matplotlib/pull/8513 passed, but failed when backported.

**Comment by QuLogic** [comment]
So this is semi-caused by switching from `pytest` to `python tests.py`. When using `tests.py`, we run whatever's in `default_test_modules`, which is _only_ the tests (`['matplotlib.tests', 'matplotlib.sphinxext.tests', 'mpl_toolkits.tests']`) and that means it's the only thing that gets pep8-checked. If we switch up to the top-level module `['matplotlib', 'mpl_toolkis']`, we'll be able to check those ones also, but we won't be able to check the examples like we should.

**Comment by tacaswell** [comment]
sigh, if the choice is `tests.py` or pep8 checking lets drop `tests.py` :disappointed: .

**Comment by QuLogic** [comment]
So we've not been running pep8 for a while. The core library is pretty minor:
```
commit 8fbcfa3aeaf4437c975edf195ad8dad61eaaa3f7
Author: Elliott Sales de Andrade <quantum.analyst@gmail.com>
Date:   Tue May 9 02:42:24 2017 -0400

    Fix PEP8 issues in core library.

 lib/matplotlib/axes/_axes.py | 4 ++--
 lib/matplotlib/axes/_base.py | 3 ++-
 lib/matplotlib/figure.py     | 4 ++--
 lib/matplotlib/legend.py     | 9 +++++----
 lib/matplotlib/ticker.py     | 6 +++---
 5 files changed, 14 insertions(+), 12 deletions(-)
```

But examples were pretty bad (note that I did try to use `subplots` a bit more, so this is slightly larger than just pep8):
```
commit ee607436fec56f456756266386b9b3223e871b56
Author: Elliott Sales de Andrade <quantum.analyst@gmail.com>
Date:   Tue May 9 16:35:37 2017 -0400

    Cleanup examples for PEP8 and some style.
    
    Try and use `plt.subplots` more and remove extraneous `plt.draw`.

 62 files changed, 232 insertions(+), 334 deletions(-)
```

And the new `tutorials` directory has a _lot_ of long lines:
```
$ git di --shortstat
 18 files changed, 424 insertions(+), 378 deletions(-)
```
Note that I generally had `vim` reflow the whole paragraph which is what makes this so big.  However, I wonder if we should disable the line length check in these tutorials and not make any of these changes. There are still several places that go over due to long URLs. The pep8 checker would normally allow this in docstrings, but doesn't seem to do so in comments like used in the tutorials. The tutorials also seem to have a lot of cross-references to auto-generated sphinx-gallery items which tend to be rather long. WDYT @choldgraf?
