### ISSUE TITLE
text object clipping

### ISSUE THREAD

**Issue by ahed87** [matplotlib/matplotlib#8506]
Hi,
I stumbled over a bit of surprising behaviour when working with some plots with text and panning them.

Apperantly the default behaviour of text is not to have a clipbox/viewbox attached to them (other than figure canvas?).

A small sample code here.

```python
plt.text(.5,.5,'center')
plt.text(.8,.8,'panned')
plt.text(1.1,0.3,'original position outside plot canvas')
plt.plot([0,1])
```
And the picture after a bit of panning.
![figure_1](https://cloud.githubusercontent.com/assets/9150231/25147190/ecb48190-2476-11e7-9262-cd7b7a95422a.png)

Clearly the text object is not passed through the same clipping box as the line, I think that should be the default, and if someone wants to place text outside of the current viewbox of the axis, that could be a kwarg somehow.

Thanks for a great library.

**Comment by anntzer** [comment]
See https://github.com/matplotlib/matplotlib/issues/5554.
Closing but feel free to discuss more.

**Comment by WeatherGod** [comment]
Just as a quick summary of the issue (for those who don't want to click
through), text objects added by ax.text() are not clipped by default (for a
variety of reasons). If you want them clipped, then the `clip_on=True`
parameter should be passed.

**Comment by ahed87** [comment]
got it, had a feeling someone would have commented on it earlier...

any objections to an update of the docstring? if not I will give it a go.

**Comment by WeatherGod** [comment]
Docstring improvements are some of the best improvements!

On Apr 18, 2017 6:16 PM, "ahed87" <notifications@github.com> wrote:

got it, had a feeling someone would have commented on it earlier...

any objections to an update of the docstring? if not I will give it a go.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/matplotlib/matplotlib/issues/8506#issuecomment-295000104>,
or mute the thread
