### ISSUE TITLE
incomplete display when rotate the xaxis.ticks

### ISSUE THREAD

**Issue by aeloyq** [matplotlib/matplotlib#8649]
when i rotate the text of Xaxis's ticks
there is a part of the text didn't show in image
like this:
![default](https://cloud.githubusercontent.com/assets/20637250/26278339/a66d3b38-3dca-11e7-8226-55c8b2d982e9.JPG)

**Comment by anntzer** [comment]
please provide a minimum example to reproduce the issue

**Comment by tacaswell** [comment]
Unfortunately, this is expected behavior (not sure about that black bar at the bottom).  You will either need to manually make you `Axes` object smaller or use `fig.tight_layout()` to auto-size it.

I think this is better handled either through https://gitter.im/matplotlib/matplotlib or matplotlib-users@python.org .  Closing as I do not think this is a bug.  If you have  a MWE that you think should work please ping to have this re-opened.

**Comment by WeatherGod** [comment]
I don't think `fig.tight_layout()` would address this. Rather, the
`fig.save(..., bbox_inches='tight')` would definitely address this, though
(but that doesn't solve it for display purposes).
