### ISSUE TITLE
Figure background is transparent when saving png from notebook backend.

### ISSUE THREAD

**Issue by efiring** [matplotlib/matplotlib#8654]
### Bug report
In Jupyter notebook with `%matplotlib notebook`:
**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.plot([1,2])
fig.savefig('test.png')
```
I used a screenshot below instead of the file 'test.png' because the odd background only shows up in preview, which evidently uses a light gray background instead of the usual white.
**Actual outcome**
![screenshot_gray_background](https://cloud.githubusercontent.com/assets/85125/26334867/aeff9662-3f03-11e7-9030-b543c700522a.png)

**Expected outcome**
I expect the white figure background that results in the above example when saving a pdf, or when using a different backend.

**Matplotlib version**

  * Operating System: OS X 10.12.4
  * Matplotlib Version: 2.0.2+7.ge6295a4a7
  * Python Version: 3.5.2
  * Jupyter Version (if applicable): 4.2.1

**Comment by WeatherGod** [comment]
wasn't it a part of the 2.0 work to make the background transparent?

**Comment by anntzer** [comment]
Nah, this is controlled by the nbagg.transparent rcparam which has defaulted to true, well, probably ever since nbagg existed (https://github.com/matplotlib/matplotlib/pull/3560/files).

TBH I don't see why this was even introduced (well, perhaps @pelson can comment on that :-)), although this may be related to defaulting to a *white* background in 2.0.  Unless there's a compelling reason to keep it I would suggest deprecating this (figure.facecolor should be more than enough, especially now that you can set it using a RRGGBBAA string).

**Comment by Atcold** [comment]
This was hard to debug... There is already a `figure.facecolor` which should be controlling the figure's colour. What's this additional parameter?

**Comment by anntzer** [comment]
Feel free to put up a PR deprecating the rcparam (I would support doing so).

**Comment by QuLogic** [comment]
This was deprecated in #10024 and removed in #12763.
