### ISSUE TITLE
Rectangle with zero height inconsistent rendering

### ISSUE THREAD

**Issue by wombatonfire** [matplotlib/matplotlib#8663]
### Bug report

**Bug summary**

A rectangle with zero height and without ```color``` kwarg is not rendered, while a rectangle with zero height and with ```color``` specified is rendered as a line.

**Code for reproduction**

```python
# no `color` kwarg, not rendered
fig, ax = plt.subplots()
ax.add_patch(Rectangle((1, 1), 2, 0))
ax.set_xlim(0, 4)
ax.set_ylim(0, 2)
plt.show()

# adding `color` parameter, rendered as a line
fig, ax = plt.subplots()
ax.add_patch(Rectangle((1, 1), 2, 0, color='#000000'))
ax.set_xlim(0, 4)
ax.set_ylim(0, 2)
plt.show()
```

**Expected outcome**

I suppose, zero height should lead to no patch, that is the latter behaviour (with color kwarg) is a bug.

**Matplotlib version**

  * Operating System: Windows 10
  * Matplotlib Version: 2.0.0
  * Python Version: 2.7.13
  * Jupyter Version (if applicable): 4.2.1

Matplotlib and Python are installed as part of Anaconda 4.3.1.

**Comment by anntzer** [comment]
This is because the first rectangle has a transparent edgecolor (as can be checked with `.get_ec()`), whereas the second one has a black edgecolor (as set by the user...).
There's no reason to special-case zero-height (e.g. negative heights are supported too).  Set the edgecolor to transparent if you do not want this behavior.
