### ISSUE TITLE
Large markers escape legend

### ISSUE THREAD

**Issue by amueller** [matplotlib/matplotlib#8705]
### Bug report

**Bug summary**

Increasing marker size leads to markers that escape the legend boundaries (or even the figure)

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt

a, = plt.plot(np.random.uniform(size=10), np.random.uniform(size=10), '*',  markersize=40)

b, = plt.plot(np.random.uniform(size=10), np.random.uniform(size=10), '*',  markersize=40)
plt.legend([a, b],
           ["training data/target", "test data", "test prediction"],
           ncol=3, loc=(.1, 1.025))
```

**Actual outcome**

![image](https://cloud.githubusercontent.com/assets/449558/26741546/0ed01678-47da-11e7-9b60-6e8f853a6274.png)

**Expected outcome**

Legend box grows to capture whole marker.

**Matplotlib version**
  * Operating System: Ubuntu 17.04
  * Matplotlib Version: 2.0.1 (conda default channel)
  * Python Version: 3.5

**Comment by amueller** [comment]
Similarly it can happen that the markers overlap:
![image](https://cloud.githubusercontent.com/assets/449558/26745307/32cd6b2e-47ea-11e7-9050-b5a678933f5c.png)

**Comment by UTSC-SISYPHUS** [comment]
I have a PR ready for this fix which considers marker size when drawing the legend. My fix causes one of the old tests to fail because the marker size causes the legend to be drawn bigger with the fix. The test that fails is test_cycles -> test_marker_cycle. How should I handle this? Should I fix the old test?
Expected
![marker_cycle-expected](https://user-images.githubusercontent.com/31746196/37182110-d30b35a0-22fd-11e8-986b-8ea18e1f0add.png)
After the fix
![marker_cycle](https://user-images.githubusercontent.com/31746196/37182112-d6c505b8-22fd-11e8-9535-d0abc12d5a35.png)
