### ISSUE TITLE
xticks behavior inconsistent for logscale plot

### ISSUE THREAD

**Issue by kain88-de** [matplotlib/matplotlib#8793]
### Bug report

**Bug summary**

I can not reliable set xticks on a plot using a logarithmic scale.  If setting the xticks works depends on the functions called, `set(xscale='log')` compared to `set_xscale('log')`, and the range of value in xticks.

**Code for reproduction**

See [notebook](https://gist.github.com/kain88-de/e2b994a62ee6612caa3c1ec955e354f7) for a complete list of examples. Below is one of the examples not working as expected.

```python
fig1, ax1 = plt.subplots()
ax1.plot([10, 100, 1000], [1,2,3])
ax1.set(xscale='log', xticks=[20, 200, 500])
ax1.get_xaxis().set_major_formatter(mpl.ticker.ScalarFormatter())
```

github won't let my upload a plot. Please have a look at the linked notebook above.

**Expected outcome**

My manual set xticks are used.

**Matplotlib version**
  * Operating System: Fedora 25 
  * Matplotlib Version:  2.0.2 / conda-forge
  * Python Version: 2.7 / conda using conda-forge channel

**Comment by efiring** [comment]
Background: setting the scale to log changes the default formatters and locators, including turning on minor ticks *and* labeling some of them when the view limit does not include two major ticks.

Regarding the three examples in your notebook:
1) The first works correctly, as you note.
2) The second fails because it turns out that the order in which things are done when `set` is given multiple arguments is not the order in which the kwargs are given.  This is inherent; kwargs come in as a dictionary, and dictionaries do not preserve order.  In principle we could put in logic to ensure that scale setting kwargs are applied first, but I suspect this is not worth the added complexity.
3) The problem here is that in contrast to the first example, the xlim is so small that the automatic  log ticking is adding labels to some of the minor ticks.  If you want the minor ticks, as in your first example, but do not want them labeled, then you can set the minor formatter to a NullFormatter instance.  If you don't want the minor ticks, you can set the minor locatter to a NullLocator instance.

**Comment by kain88-de** [comment]
> In principle we could put in logic to ensure that scale setting kwargs are applied first, but I suspect this is not worth the added complexity.

It still is a strange result for a user. Semantically for me there is no difference between the two. 


> If you want the minor ticks, as in your first example, but do not want them labeled, then you can set the minor formatter to a NullFormatter instance

That indeed solved my immediate problem. But to me these labels look exactly like the major tick labels. Kind of hard to differentiate.

**Comment by tacaswell** [comment]
> This is inherent; kwargs come in as a dictionary, and dictionaries do not preserve order

In python 3.6 they now guarantee that kwargs come ordered (https://www.python.org/dev/peps/pep-0468/) :smiling_imp:

**Comment by kain88-de** [comment]
> In python 3.6 they now guarantee that kwargs come ordered

That is only true for CPython. Other implementations might not make that guarantee. 

Would it be helpful to add an example about this behavior of the logscale plot to your example list? It's an odd behavior here that the minor ticks look to be plotted below the major ticks, in contrast to the [anatomy](http://matplotlib.org/examples/showcase/anatomy.html) example where the major tick labels are plotted lower then the minor tick labels. I assume that is because the minor ticks are written as `3 x 10^1` and need more horizontal space.

**Comment by anntzer** [comment]
> That is only true for CPython. Other implementations might not make that guarantee.

No, that is part of the language spec now.
Whether another implementation implements 3.6 is a separate issue (but then, I'm genuinely curious what other implementation actually supports matplotlib?).

**Comment by ksunden** [comment]
Closing as it boils down to the dict being ordered issue, which is now part of the language spec for all supported versions of Python.
