### ISSUE TITLE
Masked pcolormesh is not tested correctly

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#8802]
The `pcolormesh` test says that [masked colour arrays are supported](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/tests/test_axes.py#L991-L992), but this masked `Zm` variable is never used in the test. It appears that this has been the case since the test was added.

I'm not sure exactly how the "correct" masked result should look, or I would update this myself. I hope one of the assignees should have some idea what to do here.

**Comment by jkseppan** [comment]
#14414 added alpha channel support for triangle meshes in the pdf backend, but I think the question remains how masked results pcolormesh results should look. With flat shading the quads with masked vertices are removed but with Gouraud shading the color is interpolated between the data color and the "bad value" color, which defaults to (0,0,0,0) (black but transparent) so the intermediate colors are a blurry grey. I can't think of an application where someone would want the latter result, but as noted in the #14414 discussion, we don't actually know who's using this feature.

**Comment by efiring** [comment]
I think that adding Gouraud shading to pcolormesh is fundamentally confusing; I would prefer that it be broken out into its own function.  pcolor, pcolormesh, and pcolorfast are all for coloring quadrilaterals with specified *boundaries*; the colors are not specified at *vertices* but for regions.  Vertices are not masked; quadrilaterals are. Gouraud shading, with colors specified at vertices, is different.  It is more closely related to an image than to a pcolormesh.
I suspect that masking should be handled with an algorithm that sets a triangle to the "bad value" color if any vertex is masked.  I also suspect we should leave this as low priority unless and until there is evidence that users need it.

**Comment by karlwx** [comment]
I feel I should chime in here since I am actually one of the people using these features. Recently, I've been dealing with a problem with pcolormesh when dealing with masked arrays or transparency. I think it has to do with the interpolation issues mentioned here, but not sure - maybe one of you all can provide some guidance. 

I recently posted a [question on stackoverflow](https://stackoverflow.com/questions/62158505/matplotlib-pcolormesh-with-transparency-produces-noisy-plot) about this issue, with no response so far. Basically, when using pcolormesh with non-masked arrays or without a transparent colormap, the results are normal. When I plot masked arrays or have transparent colormaps, the plot becomes a bit more noisy and pixelated. I think it comes down to how the colors are interpolated from nan or transparent values (effectively treated the same by matplotlib). 

Here are some examples in addition to the stackoverflow article:

First, just a plot of radar reflectivity - no nans and no transparency below 10 on the colormap. This behaves as expected. 
![pcolormesh_test_normal](https://user-images.githubusercontent.com/45180714/84077176-ecc0a400-a9a4-11ea-85fc-c45fa313057e.png)

My ultimate goal was to produce a plot of radar reflectivity with precip type, which involves 3 separate arrays. To get it all on the same map, I first plot the regular radar (rain), then plot mix, and snow last. To prevent the latter two pcolormesh calls wiping out all the colors from the first, I either have to mask non-frozen precip areas or make the colormaps transparent in the "white" regions. You can see that this produces a more pixelated result in all areas of precipitation (most noticeable around the cutoff between green and white, and better seen in the stackoverflow post):
![pcolormesh_test_transparent](https://user-images.githubusercontent.com/45180714/84077887-f991c780-a9a5-11ea-868a-4e6954a37579.png)

I tried using gouraud shading to try to smooth out that mess, but it arguably produces a worse result - it has the weird grey/white boundaries described in this thread:
![pcolormesh_test_transparent_gouraud](https://user-images.githubusercontent.com/45180714/84077772-d9fa9f00-a9a5-11ea-9588-7614b6cab786.png)

I tried contourf, but like gourad shading, white boundaries remain. Ideally, there would be a smooth transition between the colors (like the pcolormesh plot, but not noisy). Also, contourf is too slow to be viable operationally, regardless. 
![contourf_test_transparent](https://user-images.githubusercontent.com/45180714/84077463-5e98ed80-a9a5-11ea-9600-007911dd5f30.png)

As a note, I need a solution that works with the Agg backend, as the scripts that make these images will be run via cron. 

I hope this is helpful, and I would be grateful for any solutions you all can provide!

**Comment by tacaswell** [comment]
attn @WeatherGod @dopplershift
