### ISSUE TITLE
Type-check on axes-instances created with subplots() fails

### ISSUE THREAD

**Issue by Khris777** [matplotlib/matplotlib#8810]
### Bug report

**Bug summary**

Creating an axes object using the `subplots()`-method creates an object of type `matplotlib.axes._subplots.AxesSubplot`, but the object can't be tested on this type, while an axes-object of type `matplotlib.axes._axes.Axes` can be tested successfully.

**Code for reproduction**

    import matplotlib.pyplot as mp
	import matplotlib.pyplot as mpp
	fig,axes = mpp.subplots()
	print(isinstance(axes,mp.axes._subplots.AxesSubplot))

>Out: AttributeError: module 'matplotlib.axes._subplots' has no attribute 'AxesSubplot'

Compared to:

	fig = mpp.Figure()
	axes = fig.add_axes([0,0,1,1])
	print(isinstance(axes,mp.axes._axes.Axes))

>Out: True

**Matplotlib version**
Windows 10
Matplotlib 2.0.2
Python 3.6.1
Anaconda Distribution

**Comment by tacaswell** [comment]
Why do you want to do this? It is better to do duck typing.

The reason it is failing is the Axes classes returned by subplots are dynamically (ish) created and are not in the `matplotlib.axes._subplots` namespace (which is why you are getting an `AttributeError`). 

If you must do type checking, I would use `maxes.Axes` or `maxes.SubplotBase` (check `type(ax).mro()` to see what classes are in the inheritance tree).
