### ISSUE TITLE
Wasted space in table depending on column size and cellLoc

### ISSUE THREAD

**Issue by tscheggsches** [matplotlib/matplotlib#8830]
### Bug report

**Bug summary**

1. If text is centred, the effect is not so apparent.
2. If text is left or right aligned in a wide table, the padding algorithm seems to waste space on one side.

The implemented algo seems to work good for narrow tables though. It would be ideal if the padding algo could be optimized to work for both wide and narrow tables without the need of tweaking from the users side.
Is there a reason why the padding algo does not depend on the fontsize but rather on the col width?

**Code for reproduction**
```python
import pandas as pd
import matplotlib.pyplot as plt

size_x, size_y = 12, 4
fig = plt.figure (figsize=(size_x, size_y))
ax  = fig.add_subplot(111)

col_ID    = pd.Series ([ "R001", "R002", "R003", "R005", "R006", "R007" ])
col_Title = pd.Series ([ 50*"*", 10*"-", 70*"x", "R005", "R006", "R007" ])
col_x     = pd.Series ([  3,      1,      3,      4,      2,      3 ])
col_y     = pd.Series ([  4,      2,      3,      2,      4,      3 ])

legend_df = pd.DataFrame ({ "ID"    : col_ID,
                            "Title" : col_Title,
                            "X-Pos" : col_x,
                            "Y-Pos" : col_y,
                            "Value" : col_x * col_y })
rowLabels = legend_df.index
colLabels = legend_df.columns
cellText  = legend_df.values

# Center-Aligned text looks ok
the_table = plt.table (cellText=cellText, rowLabels=rowLabels, colLabels=colLabels, loc='upper center', cellLoc="center", colWidths=[0.05, 0.52, 0.05, 0.05, 0.05, 0.05])

# Bogus: Same colWidths, but left OR right aligned -> unwanted space in title column
# the_table = ax.table (cellText=cellText, rowLabels=rowLabels, colLabels=colLabels, loc='upper center', cellLoc="left", colWidths=[0.05, 0.52, 0.05, 0.05, 0.05, 0.05])

the_table.auto_set_font_size(False)
the_table.set_fontsize (8)

ax.xaxis.set_visible (False)                                            # Grafik-Achsen ausschalten, wir wollen nur Plot
ax.yaxis.set_visible (False)
# the_table.scale(2, 2)

plt.show()
```

**Actual outcome**
[1. Centered text - padding OK](https://i.stack.imgur.com/YqeVp.png)
[2. Text left aligned - wasted space](https://i.stack.imgur.com/N0xnp.png)

**Expected outcome**
With this workaround, the padding can be adjusted manually:
```
def set_pad_for_column(col, pad=0.1):
    cells = [key for key in the_table._cells if key[1] == col]
    for cell in cells:
        the_table._cells[cell].PAD = pad

set_pad_for_column(col=1, pad=0.01)
```
[3. Text left aligned with workaround](https://i.stack.imgur.com/9zwYt.png). See also this thread on [Stackoverflow](https://stackoverflow.com/questions/44798364/matplotlib-text-alignment-in-table)

**Matplotlib version**

  * Operating System: Windows
  * Matplotlib Version: 2.0.2
  * Python Version: 3.5
  * Jupyter Version (if applicable):
  * Other Libraries:

Installed via conda, default channel.

**Comment by QuLogic** [comment]
Maybe this is something that #8325 improves?

**Comment by ImportanceOfBeingErnest** [comment]
It does not look like #8325 touches the padding, which causes this issue here.

The problem is that the padding is hardcoded as 10% of the column width on each side of the cell. This looks good for normal sized cells but the larger a cell is, the more padding it gets. 

I guess ideally one would provide an option to connect the padding to the absolute value of the fontsize and not relative to the cell width.

**Comment by swfiua** [comment]
The padding is based on width, because that was the first thing that came to mind back in the day.

Might be better to go to some multiple of the width of an "m", based on the font.

One thing that greatly complicates the code here is that it is not until you have a renderer that you can do things like measure text.

The goal of the table widget is to make the best use of the space available, so making the padding smarter should move this in the right direction.

I will see what I can do -- unless someone beats me to it.

**Comment by swfiua** [comment]
PS note that #8325 did improve the sizing somewhat, but this looks like an additional improvement.
