### ISSUE TITLE
Matplotlib 1.4.3 interactive mode not working

### ISSUE THREAD

**Issue by cathoderaymission** [matplotlib/matplotlib#8844]
### Bug report

Using python 2.7 and matplotlib 1.4.3 I cannot get either plt.ion() or plt.show(block=False) to actually show a barchart. Oddly, both of these work in ipython. I've also tried the same variations of code in python3, nada.

It works fine with a regular plt.show()

I've tried the sys.ps1 = "SOMETHING" mentioned in a bug report from 2014 as well as plt.draw() and fig.show(). 

```python
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import animation

def startup():
    global totBars, barCollection, anim, fig, x

    fig = plt.figure()
    x = range(0, 100)
    barCollection = plt.bar(x, np.arange(0, 100))
    for i, b in enumerate(barCollection):
        b.set_height(1)
    # removed frames= and blit=False
    plt.show(block=False)

```

No plot is shown.

**Matplotlib version**

  * Operating System: Ubuntu 14.04
  * Matplotlib Version: 1.4.3
  * Python Version: Repository version, 2.7
  * Jupyter Version (if applicable):
  * Other Libraries: Using Ubuntu repository 14.04 python-qt packages

Matplotlib 1.4.3 and numpy 1.8.2 both instaled from pip

**Comment by dstansby** [comment]
It looks like you're using an old version of Matplotlib; the most recent version is `2.0.2`. Please could you upgrade to Matplotlib `2.0.2` and let us know if there is still a problem?

**Comment by tacaswell** [comment]
I suspect that the issue is you are using a version of pyqt which does not automatically install the input hook try running `PyQt.QtCore.pyqtRestoreInputHook()` at the top (see http://pyqt.sourceforge.net/Docs/PyQt4/python_shell.html).  IPython takes care of that if you use the matplotlib / pylab magics.  Try switching to the tkagg backend which is more aggressive about installing the input hook.

**Comment by cathoderaymission** [comment]
I upgraded to matplotlib 2.02 and no dice.
I tried the pyqt call (which oddly doesn't work after directly importing PyQt4, it has to be called after importing matplotlib), again no dice.

**Comment by tacaswell** [comment]
How are you calling this?  I assume there is a `startup()` at the bottom of that clip.  If you call this as `python some_file.py` 'no plot' is the expected behavior (as the GUI loop does not block, everything else is done so python [correctly] exits).

**Comment by cathoderaymission** [comment]
I'm calling this before running a loop, a simple test program:

```
#!/usr/bin/python
import PyQt4
import matplotlib.pyplot as plt
from matplotlib import animation
import time

PyQt4.QtCore.pyqtRestoreInputHook()

def barlist(n): 
    return [1/float(n*k) for k in range(1,100)]

fig=plt.figure()

n=1000 #Number of frames
x=range(1,100)
barcollection = plt.bar(x,barlist(1))

def animate(i):
    y=barlist(i+1)
    for i, b in enumerate(barcollection):
        b.set_height(y[i])

plt.show(block=False)
while True:
    time.sleep(1)
```

**Comment by tacaswell** [comment]
That is also the expected behavior.  While your loop is running the GUI event loop is not running hence the gui is non-responsive.  See the text in https://github.com/matplotlib/matplotlib/pull/4779 for more details.

If you want your figure to be interactive while your loop is running you have to do

```python
fig.canvas.flush_events()
```

in your loop at some reasonable frequency (~10-20hz is the edge of feeling 'responsive').

**Comment by cathoderaymission** [comment]
Wow, I thought I tried that. Thanks! It works now.
