### ISSUE TITLE
%matplotlib notebook backend captures scroll events

### ISSUE THREAD

**Issue by wjakob** [matplotlib/matplotlib#8911]
### Bug report

The "notebook" (formerly nbagg?) backend of Matplotlib breaks scrolling using the mouse wheel. This is very annoying since scrolling through a large document immediately stops whenever the cursor encounters a figure.

To reproduce, paste the following lines into a new Jupyter notebook session and resize the window so that a scrollbar appears. Try scrolling when the cursor is within and outside of the figure.

```python
import matplotlib.pyplot as plt
import numpy as np
%matplotlib notebook
plt.plot(np.random.rand(10))
```
**Expected outcome**

Scrolling works, and the position of the cursor makes no difference.

**Actual outcome**

Scrolling stops as soon as the cursor is within the bounding box of a figure.

**Matplotlib version**
  * Operating System: MacOS
  * Matplotlib Version:  2.0.0
  * Python Version: anaconda-4.3.1 (Python 3.5)
  * Jupyter Version (if applicable): 1.0.0

**Comment by wjakob** [comment]
^ @SylvainCorlay

**Comment by tacaswell** [comment]
This is the correct and expected behavior.  

Figure areas get mouse and keyboard events, including scroll events, and do not forward them on to the browser.  If it did, then using scroll for something like zooming would be unusable as the figure would both zoom and scroll off the screen.  Similarly most jupyter keyboard shortcuts do not work with your cursor inside of a figure.

This is similar to the behavior you see with text entry boxes that have scroll bars, when the mouse is inside scrolling moves the text in the box rather than the whole window (granted in that case the text boxes tend to be special cased to when at the extreme in the direction of scrolling to start forwarding again).

**Comment by wjakob** [comment]
In that case, it would be desirable if this behavior could be deactivated.

Most default plots don't actually consume the mouse wheel events, and this effectively breaks the default way of navigating through long documents.

**Comment by WeatherGod** [comment]
zoom is hooked up to scrolling, so all plots consume the scroll event.

**Comment by WeatherGod** [comment]
I take that back... might be broken?

**Comment by wjakob** [comment]
> zoom is hooked up to scrolling, so all plots consume the scroll event.

Not so -- please try the example I posted. The mouse wheel events don't actually do anything, the widget just silently eats them.

**Comment by ZGainsforth** [comment]
A way to disable this would be great.  When I am at the top of a notebook and want to scroll down several screens past many images, then I have to find the 10 pixel wide margin of the page and scroll exactly there to make it past my images.  While I understand there is a use case where widgets may consume the scroll, it is (for me at least) an issue that breaks 90% of my notebooks so from a UX standpoint widget scrolling takes the backseat.  Since a very common use case of jupyter notebooks is to handle data represented as images, this is undoubtedly breaking (in a UX sense) for other people too.

**Comment by WeatherGod** [comment]
I don't know if this problem would have to be addressed at the jupyter
level or at the backend level (or some combination thereof?).

**Comment by jklymak** [comment]
I understand the complaint, but I don't understand the problem.  On my machine I can scroll anywhere in the red circled areas.  Its considerably larger than 10 pts.  Yeah, its sometimes a pain if I try and scroll when the cursor is on the figure, but its pretty easy to move...

Fn-dn/up arrow also works as a page-up/page-down, and just using the arrow keys skips from cell to cell.  

<img width="1276" alt="untitled_and_6__jupyter-notebook_and_3__jklymak_valdez_____zsh_" src="https://user-images.githubusercontent.com/1562854/32561266-bfcc36ac-c460-11e7-9de9-89376b6c7a4d.png">

**Comment by ZGainsforth** [comment]
So I realize now that the margins are actually a bit larger for most folks as you say.  I have set my notebooks to take the full HTML width so that my images are bigger and I can see details using:

```
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

```

Overall, this is useful, but it does mean that a typical screen for me often looks like:

![pastedgraphic-1](https://user-images.githubusercontent.com/6864619/32567041-d303d622-c46e-11e7-96ca-8481750c1ac5.png)

I have no idea if this is a matplotlib or Juypter issue then, so I’ll just discuss it.

One obvious way to fix this would be to pass scrolls in to the images if they were specifically clicked on.  Otherwise, scrolls would continue to be passed onto the container.  That way if a person is scrolling his webpage it scrolls as expected.  If he has a widget which consumes scrolls, he can still do that so long as he clicks on it.  

My two cents.

**Comment by tacaswell** [comment]
Changed the title as the problem here is that it works ;)

**Comment by jklymak** [comment]
I think its a very reasonable idea that the user should have to click on the figure before the figure keybindings become active.

**Comment by KristianHolsheimer** [comment]
Although I see the argument for wanting this behavior, it's making want to throw my laptop out the window. It's incredibly frustrating.

**Comment by SylvainCorlay** [comment]
> Although I see the argument for wanting this behavior, it's making want to throw my laptop out the window. It's incredibly frustrating.

It sounds like you are ready to open a PR!
