### ISSUE TITLE
Matplotlib doesn't work in .py files (ModuleNotFoundError)

### ISSUE THREAD

**Issue by Killen911** [matplotlib/matplotlib#8927]
I can not use matplotlib in .py files. IDLE and PyCharm write this:

> Traceback (most recent call last):
>   File "D:\matplotlib2.py", line 1, in <module>
>     import matplotlib.pyplot
>   File "D:\matplotlib.py", line 1, in <module>
>     import matplotlib.pyplot as plt
> ModuleNotFoundError: No module named 'matplotlib.pyplot'; 'matplotlib' is not a package

If I use Python Shell (console), it works fine. [Image](https://i.imgur.com/KSG42lP.png)

  * Operating System: Windows 7 x64
  * Matplotlib Version:  2.0.2
  * Python Version: 3.6 (x32)

Matplotlib installed by pip in cmd (pip install matplotlib).

Help, please.

**Comment by choldgraf** [comment]
I'd try installing the Anaconda distribution

https://www.continuum.io/downloads

it sounds like you have a confusion in paths. Also try running `which python` and `which pip` to make sure they're in the same general folder.

**Comment by Killen911** [comment]
> which python and which pip 
How I can run this? Thanks.

**Comment by efiring** [comment]
I'm sorry, but we need to reserve this github issue tracker for matplotlib-specific bugs and feature requests rather than general python installation and usage questions.  Therefore I am closing this now.  Last thought, though:

Your traceback indicates that you have a "matplotlib.py", which is trying to import the matplotlib package, but is not finding it because it is instead finding itself: "matplotlib.py".  The first thing to do, therefore, is rename the scripts you are trying to run---don't name them after any package you are going to try to import.
