### ISSUE TITLE
Uneven bin widths for log scale

### ISSUE THREAD

**Issue by rageTrue** [matplotlib/matplotlib#8969]
if you run something like this:
d = [1, 10, 100, 1000, 10000]
plt.xscale('log')
plt.hist([d, d, d, d, d, d], bins=d)

Result: 
![histogram](https://user-images.githubusercontent.com/1891594/28790411-c952f67e-75dd-11e7-8fab-57a73fef15c8.png)

You will expect equal bin widths for bins corresponding to the same range of values but the widths are different (most likely because they are transformed through a log scale).

**Comment by tacaswell** [comment]
The bins are even width in dataspace which due to the log-scaling varies the size in screen space.

This is a compelling case that auto-broadcasting hist this way to make adjacent bars is a miss-feature as the edges of the drawn bins no longer map to the data range which they contain.

**Comment by ncbishop** [comment]
Sorry, it took a while for me to understand what the code above was doing, mostly because of the repeated use of `d`.  This makes more sense:

`import matplotlib.pyplot as plt`
`# data sets`
`m = [2, 2, 2, 20, 20, 2000, 2000]`
`n = [2, 2, 20, 20, 20, 200, 200, 2000]`
`# logarithmic bins`
`d = [1, 10, 100, 1000, 10000]`
`plt.xscale('log')`
`plt.hist([m, n], bins=d)`
`plt.show()`

![figure_1](https://user-images.githubusercontent.com/595129/29000288-39baff38-7a34-11e7-8672-075d93933c9a.png)

Also, something is up with the plot by @rageTrue - why does the last/highest ordinal bin have y=2?

**Comment by tacaswell** [comment]
Because the `np.histogram` is implemented, if you pass in bin edges as a length `n` array, you get `n-1` bins the first `n-2` of which are right-open internals (ex `[d[i], d[i+1])`) and the last of which is a closed internal (ex `[d[n-2], d[n-1]]`).  In the OP it is effectively counting how many bin edges fall into each bin, hence the first `n-2` are 1 (as they all contain their left edge) and the last one is 2 (as it contains both it's left and right edges.
