### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by g0chan** [matplotlib/matplotlib#9014]
I actually have the type1cm.sty package on my machine but I'm still getting the error saying I don't. Any ideas?

### Bug report

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
#
#
```

**Actual outcome**

```
# If applicable, paste the console output here
#
#
```

**Expected outcome**

**Matplotlib version**

  * Operating System:
  * Matplotlib Version: 
  * Python Version:
  * Jupyter Version (if applicable):
  * Other Libraries:

**Comment by WeatherGod** [comment]
Please use the form to supply relevant information such as a description of the error, the traceback, which operating system, the version of matplotlib, the version of python, and how they were installed.

From the little bit of information here, it does seem like this question might be more suited for the mailing list, but if you feel that there is an actual bug here, feel free to update this issue with the relevant information.

**Comment by tacaswell** [comment]
This is likely a configuration or installation issue.  I suggest subscribing to the [mailing list](https://mail.python.org/mailman/listinfo/matplotlib-users) and asking any follow up questions there.
