### ISSUE TITLE
feature request: support for append in backend_pdf

### ISSUE THREAD

**Issue by bayesfactor** [matplotlib/matplotlib#9016]
### Feature request: 
allow append operations to multipage pdf objects. I believe this can be addressed via altering backend_pdf.py from:
```python
class PdfFile(object):
    """PDF file object."""

    def __init__(self, filename):            
        self.nextObject = 1     # next free object id
        self.xrefTable = [[0, 65535, 'the zero object']]
        self.passed_in_file_object = False
        self.original_file_like = None               
        self.tell_base = 0
        if is_string_like(filename):
            fh = open(filename, 'wb')
```
To something like this, while making sure the args get passed in __init__:
```python
class PdfFile(object, *args):
    """PDF file object."""

    def __init__(self, filename, *args):            
        self.nextObject = 1     # next free object id
        self.xrefTable = [[0, 65535, 'the zero object']]
        self.passed_in_file_object = False
        self.original_file_like = None               
        self.tell_base = 0
        writemode = 'wb'
        if ('a' in args):
          writemode = 'ab'
        if is_string_like(filename):
            fh = open(filename, writemode)
```

**Code for reproduction**

```python
with PdfPages(r"multipage_pdf1.pdf") as pdf:
   plt.plot([1,2,3,4], [3,4,5,3])
   pdf.savefig()
   plt.close()
pdf = PdfPages("multipage_pdf1.pdf", "a")
   plt.plot([1,2,3,4], [3,4,5,6])
   pdf.savefig()
   plt.close()
   pdf.close()
```

**Actual outcome**

A pdf with one page.

**Desired outcome**

A pdf with 2 pages.

**Matplotlib version**

  * Operating System: CentOS
  * Matplotlib Version: matplotlib.__version__ = 1.5.1
  * Python Version: python3.3.0

matplotlib installed via pip

**Comment by WeatherGod** [comment]
That's a very interesting idea. Would you like to put together a pull
request with this feature? Note, your psuedo-code is a bit incorrect (you
don't do `*args` at all in `PdfPages(object, *args)`, only in the function
signatures. I also wouldn't do *args anyway, but have an argument like
`save_mode='w'`, so that the default is to save, but then document that it
could be `a` as well.

The Pull Request would also need tests and documentation, but we can walk
you through that when you put together the feature.

**Comment by anntzer** [comment]
Actually, just appending two pdf files like this doesn't (AFAICT) create a valid pdf file with two pages (at least the OP's example doesn't work for me).  I guess doing so would require parsing the first pdf's structures to make it know there's a second page.

One may just keep the first PdfPages object around instead of immediately closing it, so I'm not sure it's worth keeping this open.

**Comment by jklymak** [comment]
closing based on above...
