### ISSUE TITLE
DayLocator is returning incorrect times around daylights switch over

### ISSUE THREAD

**Issue by LanceJenkinZA** [matplotlib/matplotlib#9018]
### Bug report

**Bug summary**

`DayLocator` returning incorrect times around daylights switch over, resulting in duplicate day labels.

**Code for reproduction**

```python
import datetime

import pylab
import matplotlib.dates as mdates
import pytz

x = [datetime.datetime(2017, 3, 30), datetime.datetime(2017,4,4)]
y = [0, 1]

pylab.plot(x, y)

ax = pylab.gca()

tz = pytz.timezone("Australia/Sydney")
ax.xaxis.set_major_locator(mdates.DayLocator(tz=tz))
ax.xaxis.set_major_formatter(mdates.DateFormatter("%a", tz=tz))

pylab.show()
```

**Actual outcome**
The day labels for the day of the daylight switch over are duplicated, see figure below:

![image](https://user-images.githubusercontent.com/6415805/29203748-4c12a116-7e73-11e7-8671-e80f78a59050.png)

**Expected outcome**
The labels should not be duplicated.

**Matplotlib version**

  * Operating System: Kubuntu 17.04
  * Matplotlib Version: 2.02
  * Python Version: Python 2.7.13 
  * pytz: 2017.2

**Comment by pganssle** [comment]
FWIW, this is specifically an issue with `pytz` time zones:

```python
import datetime

import pylab
import matplotlib.dates as mdates
import pytz
from dateutil import tz

x = [datetime.datetime(2017, 3, 30), datetime.datetime(2017,4,4)]
y = [0, 1]

pylab.plot(x, y)

ax = pylab.gca()

tz = tz.gettz('Australia/Sydney')
ax.xaxis.set_major_locator(mdates.DayLocator(tz=tz))
ax.xaxis.set_major_formatter(mdates.DateFormatter("%a", tz=tz))

pylab.show()
```

![daylocator](https://user-images.githubusercontent.com/1377457/29244989-0ea13164-7f7f-11e7-969a-3bade427e578.png)

**Comment by pganssle** [comment]
I'm not sure why it just works for `dateutil` and not for `pytz`, but I think the issue is that by passing `tz` to the `DayLocator`, you're telling the `DayLocator` that your points should represent that *absolute time* (it's possible it's represented internally as UTC), and by passing `tz` again to the formatter, you're converting that back, and that's where the error lies. If you want to keep with the `pytz` zones, this version of the code will also work as expected:

```python
TZ = pytz.timezone('Australia/Sydney')
ax.xaxis.set_major_locator(mdates.DayLocator())
ax.xaxis.set_major_formatter(mdates.DateFormatter("%a %Y-%m-%d %Z", tz=TZ))
```

**Comment by pganssle** [comment]
OK, I found the problem, I can prepare a patch for this. The issue is that the `rrule` is being constructed using timezone-aware dates. This is problematic even for `dateutil` zones, for various reasons, but it's especially problematic for `pytz` zones, which do not implement the `tzinfo` interface in the recommended fashion.

What needs to happen is that `RRuleLocator` needs to generate naive dates, which, in the case of `pytz` zones, are then `localized` (I think it doesn't matter which side of DST they end up on in ambiguous situations, but I think we should default to the DST side for PEP-495 related reasons), and for `dateutil` zones, they can just be attached as normal.

One thing to note (and I will make a separate issue to discuss this if my suspicions prove correct) is that I am fairly certain that the current approach will have this same bug if there's ever a DST transition that starts at midnight (i.e. if midnight doesn't exist in a given zone) - though it may be less obvious.

**Comment by LanceJenkinZA** [comment]
Thanks for looking into the problem, and creating a patch fixing it!
