### ISSUE TITLE
'clear' kwarg in plt.figure() not clearing figure

### ISSUE THREAD

**Issue by jennirinker** [matplotlib/matplotlib#9092]
### Bug report

Passing in "clear=True" to plt.figure() on a figure that has already been created does nothing to the figure. 

**MWE**

```
import matplotlib.pyplot as plt
fig = plt.figure(1)
plt.plot(1,1,'x')

plt.figure(1, clear=True)  # expected this to clear the figure
```

**Actual outcome**

Figure 1 is not cleared.
![figure_1](https://user-images.githubusercontent.com/11503804/29714331-08d00f3e-89a3-11e7-8fc0-09b457b0d928.png)

**Expected outcome**

Expected figure 1 to be cleared.

**Matplotlib version**
  * Operating System: Windows 7 (miniconda)
  * Matplotlib Version: 4.3.25 (conda install/update matplotlib)
  * Python Version: 3.6.1
  * Jupyter Version (if applicable): n/a
  * Other Libraries:  n/a

**Comment by dstansby** [comment]
This is working for me on the `master` branch (ie. the figure gets completely cleared). Your Matplotlib version can't be right (we're only up to version 2!). What version gets printed if you try:

```python
import matplotlib
print(matplotlib.__version__)
```

**Comment by afvincent** [comment]
I suspect 4.3.25 to be the version of conda: it is actually the one that I currently have. I can reproduce the MWE with Matplotlib 2.0.2 installed from conda, while as @dstansby reported it, I get the expected behavior with the master branch of Matplotlib.

However, in the first case (2.0.2), there is no mention of the keyword argument `clear` in the docstring of `pyplot.figure`, while `clear` is indeed described in the same docstring from the master branch.

Closing as the behavior is consistent with the docstrings. @jennirinker, thank you for reporting and please feel free to reopen the issue if you disagree with me. Besides, you should be able to use the keyword argument `clear` in a near future with Matplotlib 2.1 :).

**Comment by jennirinker** [comment]
Sorry for the delayed response -- I was attending a scientific python workshop in Greece. :)

Yes, I was absolutely wrong in my version numbers. I have matplotlib version 2.02 which, as noted, does not mention the "clear" kwarg in the docstring. Obviously I confused what was on master with what has been released. I'll try to figure out how to distinguish versions in the future. Thanks for the responses!

**Comment by afvincent** [comment]
No problem.

To get the version of Matplotkib that you are currently using, an easy way is:
```python
import matplotlib as mpl

mpl.__version__  # or print(mpl.__version__) if not in an interactive shell like IPython.
```

By the way, the release candidate for Matplotlib 2.1 is out, which includes the `clear` keyword argument for `plt.figure` ;).

**Comment by jennirinker** [comment]
Well, I usually just use `conda list` if I don't have an iPython console booted up, but my ignorance is more on knowing which version is master on GitHub and when it will be released as a new version.
