### ISSUE TITLE
Annotate arrow zorder mismatch with grid

### ISSUE THREAD

**Issue by Tjstretchalot** [matplotlib/matplotlib#9170]
### Bug report

**Bug summary**

When using [axes.annotate](http://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.annotate.html#matplotlib.axes.Axes.annotate) to generate an arrow, sometimes, regardless of zorder, the arrow is drawn below the grid. It's expected that with zorder >2.5 it should draw above the grid. 

This does not happen for all arrows. For the arrows that do have this behavior it is consistent. So for example, on the default settings an arrow from (0.2, 0.2) to (0.8, 0.2) has the expected behavior, but in the reproduction example it does not.

This is particularly obvious when the grid is dashed.

**Possibly related issues**

https://github.com/matplotlib/matplotlib/issues/5045

**Code for reproduction**

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.set_xlim(-1, 7)
ax.set_ylim(-1, 6)
ax.grid(True, linestyle='dashed')
an = ax.annotate("", xy=(2, 1), xytext=(6, 1), arrowprops=dict(arrowstyle="-", shrinkA=0, shrinkB=0, color='g', zorder=4))
plt.show()
```

**Actual outcome**

![figure_1](https://user-images.githubusercontent.com/931176/30222698-8848f9b8-947c-11e7-9d1c-633fd55160a2.png)

**Expected outcome**

The line should cover the grid

**Working example**

```python
import matplotlib.pyplot as plt
fig, ax = plt.subplots()
ax.grid(True, linestyle='dashed')
an = ax.annotate("", xy=(0.2, 0.2), xytext=(0.8, 0.2), arrowprops=dict(arrowstyle="-", shrinkA=0, shrinkB=0, color='g', zorder=4))
plt.show()
```

![figure_2](https://user-images.githubusercontent.com/931176/30222765-d7570c16-947c-11e7-9c0b-523a0fc012ef.png)

**Matplotlib version**
  * Operating System: Windows 10
  * Matplotlib Version: 2.0.2
  * Python Version: 3.6.2

Installed using pip install

**Comment by anntzer** [comment]
This is actually not related to zorder -- the line is indeed drawn after the grid, as can be checked by setting a large linewidth.  However the line is also drawn slightly shifted, due to path snapping.
Set `plt.rcParams["path.snap"] = False` to fix the issue.

Basically, in order to draw crisp lines, you want them to be aligned with pixel centers (if their linewidth round to an odd number) or to the midpoint between pixel centers (if their linewidth round to an even number) (basically, to minimize the smear into neighboring pixels).  Here I believe the grid and the line use different rounding modes, and thus appear slightly offset from each other.  Setting `path.snap` to False fixes the issue, but causes the lines to appear less crisp.  AFAICT there is no really better solution there.

**Comment by Tjstretchalot** [comment]
Interesting. THank you for the response.

If it is due to rounding issues, is there a way to switch the grid to how the lines are rounded rather than the lines to how the grid is rounded?

**Comment by anntzer** [comment]
Right now you can turn on/off rounding via the path.snap rcparam, but there is no additional control.  I don't think we should add fine control of the rounding (this would be seriously overengineered IMO), but we may want to switch to always round to pixel centers as argued above.

**Comment by efiring** [comment]
Snapping makes sense only for exactly horizontal and vertical lines, so unless I am misunderstanding, a "switch to always round to pixel centers" is a non-starter.  I'm going to close this issue because it doesn't seem to be pointing clearly to a bug or action item, and I think the discussion to date explains the original observation.

**Comment by anntzer** [comment]
Actually the requested item *does* make sense, but is already discussed in depth in https://github.com/matplotlib/matplotlib/issues/12934 so this can be left closed as a duplicate.
