### ISSUE TITLE
Suggested amendments to docstring style guide

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#9271]
I would like to propose the following amendments to the docstring style guide.

- Drop the "optional" note next to optional parameters:
  * Most tools that I can think of for viewing a function docstring will also display the function signature, which displays whether a parameter is optional in a much more prominent manner.
  * "Optional" is not sufficient to indicate whether a parameter is keyword-only or not (currently rare, but possibly less so in the future).
  * Due to Matplotlib's API design, the vast majority of parameters are optional anyways.

- Stop mentioning the default value for optional arguments, unless it has a non-obvious meaning (typically when `None` means `rcParams["foo"]`).
  Likewise this is mostly duplicating information available in the signature; moreover, right now the default value is given at the end of the doc for each parameter which is not even a really obvious place to find it (it would have been better if it went right next to the parameter name, but what can you do...).
  Note that numpydoc says "Optional keyword parameters have default values, which are displayed as part of the function signature. They *can* also be *detailed* in the description." (emphasis mine).  The example they give is in fact one where the default has a non-obvious meaning.
```
Description of parameter `x` (the default is -1, which implies summation
over all axes).
```

- Progressively switch to using type hints syntax for "composite" types (`List[int]`, etc.).  I'm actually not a huge fan of the direction that the Python dev team is taking on explicit type hints everywhere in general (I think it's a step in the wrong direction - compare with C++ which is moving towards `auto` everywhere), but it does provide a standard syntax that is reasonable.  The only exception is that I would keep `type1 or type2` (which is understood by Sphinx) rather than `Union[type1, type2]`.  We also need to decide whether to have a standard syntax for array-likes, although that's probably more of an upstream (i.e. numpydoc-level) issue and can be done in a later stage.

**Comment by ImportanceOfBeingErnest** [comment]
I'm not a big fan of leaving out the default values from the documentation. If there is some redundancy, so be it, but the default value often is not clear from the signature alone. And if the signature tells `param=None`  one does not automatically know if this will default to `None` or `rcParams["param"]` or even `rcParams["synonymforparam"]`.  At least it would require to know that there actually is a `"param"` in `rcParams` which could be the replacement for `None` - and if one doesn't know it, one would need to look through the complete rcParams list. 
(Rethinking about the statement above, this may actually be the intention and I may misunderstand to which part of the sentence the brackets belong (??))

In any case I would even like to see the default values from rcParams being written down in the documentation itself, e.g. have the `hist` doc string directly telling me that it uses 10 bins by default, not only that it takes the values from what the `hist.bins` value is.

Also there are some functions like e.g. `contour` that simply have `contour(*args,**kwargs)` as signature. Even now the documentation leaves it unclear what the default number of autmatically chosen levels is, if it is not given (because it is optional).

**Comment by anntzer** [comment]
Just to be clear, I am saying that None == rcParams["foo"] should (of course) remain explicitly indicated in the docstring.

**Comment by tacaswell** [comment]
:-1: on dropping 'optional', the kw-only issue needs to be raised with the numpydoc folks.

I think moving dropping the default from the docstring _only_ when there is a real value (ex, not `None`) in the signature makes some sense.  I think in cases where we fall back to an rcParam or the signature is `*args, **kwargs` the defaults need to be in the docstring. On the other hand, being consistent and always including it (which I do not think we currently do) also has an appeal .

I am mixed on including the default rcparam in the docstring (as the two can get out of sync), improving the rcparams class (which is a custom dict subclass) to make looking up the current value may help here.  On the other hand, making it frictionless to know what values it really gets called with is good.

:+1: to using the mypy notation where sensible.

**Comment by dopplershift** [comment]
I'm with @tacaswell here. 'optional' is a good thing to have IMO.

Consistently putting into the docs what rcParams are relevant to parameters is a really good thing.

**Comment by anntzer** [comment]
FWIW I went back to the numpydoc guide and noted, regarding the defaults, that they say (emphasis mine):

> Optional keyword parameters have default values, which are displayed as part of the function signature. They *can* also be *detailed* in the description:

    Description of parameter `x` (the default is -1, which implies summation
    over all axes).

and the example is clearly one where the default has a non-trivial meaning (where, once again, I'd agree that the meaning of default -- for us, typically, matching a rcParam -- needs to be kept documented).

Updated the OP with this point.

**Comment by anntzer** [comment]
Most of the non-rejected parts of this have been enacted.
