### ISSUE TITLE
Feature Idea: Make subplots return an AxisList object instead of a numpy array

### ISSUE THREAD

**Issue by AKuederle** [matplotlib/matplotlib#9434]
Hey,

This is a short idea I had when creating complex graphs with multiple subplots.
Sometimes you want to apply the same actions to multiple subplots and a way that feels very natural would be something like this:

````python
fig, axs = plt.subplots(2, 2)
axs[:, 0].set_ylabel('test')
````

This does of course not work, but could be easily be achieved by returning a custom object that wraps a list of axes instances and overwrites the `__getitem__` method.
Of course it would need to reimplement all axes methods, but it might be possible to do that by just forwarding all call in a modified  `__getattribute__` or by automatically creating wrapped classmethods in a metaclass.

With such a custom object it might even be possible to support something like this:
````python
axs[:, 0].set_ylabel(['test1', 'test2'])
````

If there is interest in such functionality, I would try to build a working prototype.

Other than that, thanks to everybody for all the awesome work you put into matplotlib!
Regards,
Arne

**Comment by tacaswell** [comment]
That is a pretty good idea, however I have some back-compatibility concerns as the returned object would have to _also_ be a `ndarray` subclass (or at least fully duck-typed).

I think the best course of action is to prototype it (maybe dropping the full numpy compatibility).  Instead of  it being the default return type of `subplots`, have it a stand-alone class

```python
fig, ax_grid = plt.subplots()
nice_grid = NiceGrid(ax_grid)
nice_grid[:, 1].set_ylabel()
``` 

If the prototype goes well we can then sort out if this would be better as a small package on pypi or someplace as a helper in Matplotlib core.

**Comment by AKuederle** [comment]
Thank you for your response!

Not making that a default sounds reasonable. I will try to prototype as a small independent package and update here as soon as I've made progress.

**Comment by jklymak** [comment]
Plus one on this idea!   I’m not even sure how big a deal it is for backwards compatibility so long as it supports most of the indexing and reshaping ndarray commands.

**Comment by anntzer** [comment]
I think this can also help with avoiding the `squeeze=False` dance.

**Comment by AKuederle** [comment]
Could you explain that further?

**Comment by anntzer** [comment]
Right now if you write `fig, axs = plt.subplots(m, n)` (as opposed to literal values for `m` and `n`) and then later try to use `axs[i, j]` then this will fail if `m == 1` or `n == 1` because `subplots` implicitly squeezes dimensions that are equal to 1; i.e., it returns a 1D array (or not an array at all if `m == n == 1` instead of a 2D array).  Of course, that behavior makes it possible to write e.g. `fig, (ax1, ax2) = plt.subplots(2)` or `fig, ax = plt.subplots()` which is not unreasonable.  Right now the safe way around this (unless you are certain that `m` and `n` will never be equal to 1 -- I wouldn't count on it) is to use `plt.subplots(..., squeeze=False)` which always returns a 2D array.

Now, if the AxesList object (however we name it) returned also has whatever methods an Axes has, then you're fine even if you don't pass `squeeze=False`, because we can decide to *always* return an AxesList and drop the need for squeeze.  Now you always just call whatever method you want on the AxesList (need to fully flesh out the idea as to how indexing would exactly work).

On the other hand, having thought about it again, I think another reasonable (unrelated) option would have been (probably too late to change it...) to have the signature `plt.subplots(nrows=None, ncols=None, ...)` with `None` meaning "squeeze this dimension" and 1 meaning "don't squeeze this dimension".  In this way, `plt.subplots(m, n)` always give a 2D array, whereas `plt.subplots(2)` or `plt.subplots(ncols=2)` or `plt.subplots(None, 2)` can be unpacked to `(ax1, ax2)` (but `plt.subplots(1, 2)` would return an array of size `(1, 2)` as one would expect).

**Comment by jklymak** [comment]
But I really like the basic idea here.  There is no need for axes to be ndarrays, other than the fact we like them to be iterable as a 2-D array.  Being able to do `ax[:,1:].set_xticklabel('')` would be a lot of fun!

**Comment by anntzer** [comment]
On the other hand, note that the desired functionality is already available as (e.g.) `plt.setp(axs[:, 0], xticklabels="")` (modify accordingly; and yes that capability may not be easily discoverable -- that's why I didn't even think of it initially)... which is really not that much harder to type, and I would consider this an argument against adding what is likely to be non-trivial proxying code...

**Comment by jklymak** [comment]
![dc-cover-7hqlji2fu754ccr38i0mr9sal2-20170519113544 medi](https://user-images.githubusercontent.com/1562854/31632818-25a217da-b273-11e7-8a2d-2530a93dfbc9.jpeg)

**Comment by AKuederle** [comment]
Wow I did not know that you could pass multiple objects to plt.setp.
This covers indeed the basic functionality I was missing.
So is there a need for a AxesList object beside the fancy syntax?

**Comment by anntzer** [comment]
I would consider this at least an argument against it.

**Comment by AKuederle** [comment]
Btw. Is there a good place in the docs were setting properties of multiple axis at once could be shown? I don't think many people are aware of that.

**Comment by anntzer** [comment]
It's implicitly (but not very clearly) documented at http://matplotlib.org/gallery/misc/set_and_get.html#sphx-glr-gallery-misc-set-and-get-py (when setp is called on `lines`).

But yes the docs could use some improvement.

**Comment by AKuederle** [comment]
I just realised that we would also need to support nested attributes, like `ax.xaxis.grid()`. I think this can not be done with `plt.setp` but would also not be trivial to implement in a AxList class

**Comment by timhoffm** [comment]
Superseded by #25937
