### ISSUE TITLE
No Bugs at all

### ISSUE THREAD

**Issue by cycleuser** [matplotlib/matplotlib#9537]
Everything is just fine, there is no bugs at all.
The world is peaceful.

**Comment by tacaswell** [comment]
attn @QuLogic 

Why are you setting the xlimits to `(-90, 450)`?  Removing that line generates the expected graph.

**Comment by cycleuser** [comment]
because the data to plot is in the range between -90 and 450.
and i see no need to forbid people to use this kind data.

**Comment by tacaswell** [comment]
But your labels are in the range [0, 360].  I do not understand how your expected figure maps at (-90, 450), can you explain a bit more?

**Comment by cycleuser** [comment]
@tacaswell 

I think there seems to be no need to spend time on explaining some details about setting boundaries of data.

How about let us try to find the reason of this different plotting generate by different version of Matplotlib with same code?

**Comment by tacaswell** [comment]
One of the big features of 2.1 is major improvements to polar plotting (see http://matplotlib.org/users/whats_new.html#enhancements-to-polar-plot and examples there in).  

The first step is to understand what you are trying to do, why, and what the expected behavior is.  I do not understand what the expected behavior of `axes.set_xlim(-90, 450)` on a polar graph which is limited to a 360 degree range.  Does it rescale to 360? does it do mod360?  If the first, why are the labels going to the right place / are they misleading?  If the second, why bother setting range?

**Comment by cycleuser** [comment]
so, how do you think about  axes.set_xlim(10, 350)?

**Comment by tacaswell** [comment]
@cycleuser Why did you delete all of your comments?  Even if there is no bug, the discussion may have helped someone in the future.
