### ISSUE TITLE
Puzzling change in contour for data entirely on contour levels 

### ISSUE THREAD

**Issue by arosen93** [matplotlib/matplotlib#9588]
### Bug report

**Bug summary**

The `contour` and `contourf` functions do not show the correct number of levels.

**Code for reproduction**

```python
import numpy as np
import matplotlib.pyplot as plt
x = np.loadtxt(open('x.txt','rb'),delimiter=',')
y = np.loadtxt(open('y.txt','rb'),delimiter=',')
z = np.loadtxt(open('z.txt','rb'),delimiter=',')
fig, ax1 = plt.subplots()
ax1.contour(x,y,z,np.unique(z),colors='k')
plt.show()
```

**Actual outcome**

Note that in the test data I uploaded, `np.unique(z)` has a length of 6, so there should be 6 levels, but there are only 5. See image here: ![figure_1](https://user-images.githubusercontent.com/8674072/32070651-ac2835a0-ba52-11e7-8271-0b447612f441.png)

**Expected outcome**

See image here from an older version of matplotlib, which has the correct number of levels: ![figure_2](https://user-images.githubusercontent.com/8674072/32070750-f2d0c454-ba52-11e7-8426-6b292f8f2715.png)

**Matplotlib version**

  * Operating system: Windows
  * Matplotlib version: 2.1.0 (it works fine on 2.0.2)
  * Matplotlib backend (`print(matplotlib.get_backend())`): `Qt5Agg`
  * Python version: 3.x and 2.x

Installed using default Anaconda settings. Data used in this bug report can be found here:
[x.txt](https://github.com/matplotlib/matplotlib/files/1419668/x.txt)
[y.txt](https://github.com/matplotlib/matplotlib/files/1419670/y.txt)
[z.txt](https://github.com/matplotlib/matplotlib/files/1419671/z.txt)

**Comment by arosen93** [comment]
[x.txt](https://github.com/matplotlib/matplotlib/files/1419665/x.txt)
[y.txt](https://github.com/matplotlib/matplotlib/files/1419666/y.txt)
[z.txt](https://github.com/matplotlib/matplotlib/files/1419667/z.txt)

**Comment by jklymak** [comment]
Your data set is very digitized in that all the numbers are round numbers and equal to your contour levels.  It looks like  a <= got turned to a < somewhere between 2.0.2 and 2.1.  

If you do `ax1.contour(x,y,z+0.00000000001,np.unique(z), colors='k')` then you get the right answer.  

Not saying you should have to do this, but just to a) give you a way forward until this is fixed, and b) help whoever changed `contour.py` last see what happened...

**Comment by arosen93** [comment]
I see. Thanks for the reply. It's very "digitized" because the real data isn't numerical, so I'm using an integer identifier as `z` values. Thanks for the workaround until this gets solved.

**Comment by WeatherGod** [comment]
Are you claiming that this is a regression? There are two contouring
methods in matplotlib now, and it is possible that the new default one
might now behave differently (although, I doubt it). To activate the old
method, set `corner_mask='legacy'` in the contour() call. If it works for
legacy but not for the default, then we know something is wrong with the
new contouring method.

**Comment by arosen93** [comment]
I activated the old method and it does not change the resulting image. Yes, I am claiming that this is a regression, as there should be 6 levels yet there are only 5, which is not accurate and is also misleading.

**Comment by jklymak** [comment]
By regression, I think @WeatherGod  meant did it behave differently in 2.0.2, which you indicate above that it did.  If it behaved differently in 2.0.2 that that is mysterious, because there is nothing in the "whats' new" section about a change. Doesn't mean there wasn't one...

**Comment by QuLogic** [comment]
Bisect points to 6ac197fd58404633499c3fb7bacc461c3c1666f9
```
commit 6ac197fd58404633499c3fb7bacc461c3c1666f9
Author: Eric Firing <efiring@hawaii.edu>
Date:   Sun Jun 4 11:09:24 2017 -1000

    BUG: handle empty levels array in contour, closes #7486
    
    This relates to line contours only, not to filled contours.
    
    This handles the case where an empty array is provided as the
    "levels" kwarg, or where for any reason there are no levels within
    the data range.  An example is the case of uniform z. The
    levels array is then set to the minimum value of z so that
    the plotting can proceed, and a warning is generated.

:040000 040000 87983432a1b32b8f09c22e9401ae1c0d77d33ac9 9ba9828dba25a02bcf0b20573bd8e40fa01dbadb M	lib
```

**Comment by WeatherGod** [comment]
Interesting. As near as I can tell, the thing that changed was that the levels array got cast to float64, when it didn't do that before (although, I would have assumed that it would have been implicitly upcasted in the comparison stage).

It is clear, though, in this code that the comparison operator itself hasn't changed, which matches my expectations. I regularly `contourf()` highly quantized data, and I have always needed to add on a little bit to the data to get it to behave like I want. I will concede that I don't do `contour()`, so I don't know how it was supposed to work before.

Thoughts @efiring?

**Comment by efiring** [comment]
I'm looking at it.  I don't see yet what might have changed; the data are being read by numpy as float64, so the call to unique is returning float64, so I don't think the cast to float64 is doing anything--although it was my first suspicion.

I would note that there are only 4 levels, not 5 or 6, because only levels *inside* the data range, exclusive of the end points, are being kept.  The rationale is that line contours *separate* regions, so it doesn't make sense to draw a line contour at an extreme value--there is no region on the other side.

Testing with contourf, and looking at the data array along the LHS of the plot, it is evident that the problem is not a missing level, but a missing contour *line*: the 21 level is present, but it's line is not.  The extreme values of the array are 20 and 60; the valid levels for contour are 
```
In [11]: cs.levels
array([ 21.,  30.,  31.,  42.])
```
Contourf correctly uses the extreme values--so all 6 values are in the array--but it also treats the "21" values and the "20" values as being in the same "20 to 21" range, so, consistent with what contour is doing, it has no horizontal division in the upper LH corner.

**Comment by efiring** [comment]
Here is a simpler example, using a small subregion of the original array:
```
In [78]: z
array([[ 20.,  20.,  20.,  20.,  20.,  30.,  30.],
       [ 20.,  20.,  20.,  20.,  20.,  30.,  30.],
       [ 20.,  20.,  20.,  20.,  20.,  30.,  30.],
       [ 21.,  21.,  21.,  21.,  21.,  30.,  30.],
       [ 21.,  21.,  21.,  21.,  21.,  21.,  30.],
       [ 21.,  21.,  21.,  21.,  21.,  21.,  21.],
       [ 21.,  21.,  21.,  21.,  21.,  21.,  21.]])

In [79]: fig, ax = plt.subplots()
In [80]: csc2 = ax.contourf(z, levels=np.unique(z), cmap='nipy_spectral')
In [81]: cbar = fig.colorbar(csc2, ax=ax)
In [82]: ax.invert_yaxis()
In [83]: csc2.levels
array([ 20.,  21.,  30.])
```
![contour_3_integers](https://user-images.githubusercontent.com/85125/32080414-2e75bf58-ba4b-11e7-8577-17011ad22ad8.png)
There can be only two regions because there are only 3 boundary values, so there is some ambiguity about how the 3 values will be grouped. Here is what the documentation says:
```
Note: contourf fills intervals that are closed at the top; that
is, for boundaries *z1* and *z2*, the filled region is::

    z1 < z <= z2

There is one exception: if the lowest boundary coincides with
the minimum value of the *z* array, then that minimum value
will be included in the lowest interval.
```
This is consistent with what we see with contourf, and contour is then being consistent with contourf in not drawing that contour. It is a reasonable way to resolve the ambiguity. 

@arosen93, I think that the solution for your use case is to pick levels that are mid-way between your unique values.

**Comment by arosen93** [comment]
Thanks for looking into this. I can certainly do that. I'd be remiss not to at least mention though that I (personally) don't think that's the most logical procedure to rely on. In my opinion, the data should not have to be modified, and if I didn't know in advance how many lines there should have been, this could have gone unnoticed. I'm still a little confused why there is ambiguity in how the values should be grouped when I am (trying) to tell the `contour` function that I'd like there to be as many unique regions in the contour plot as there are unique elements in `z`.

**Comment by jklymak** [comment]
@arosen93 In the usual run of things contour lines denote a boundary *between* field values.  The contour is rarely the value of  any individual data point in the field.  If you want contour lines to denote the boundary between integer values, it makes sense to define the contour levels *between* the discrete values.  

Its exactly the same issue as binning discrete data.  If you put all your bin *edges* at the same values as your discrete data, which bin gets the data value?  If you put the bin edges between the discrete values, your bins are unambiguous.

Or, if you don't want to move the bins/contour levels (maybe for labelling purposes), just move the data epsilon higher or lower so if falls definitively on one side of the bins/contours or the other.

I'm going to close this, because while the behaviour may have changed in 2.1 its not a bug per-se, as the code is doing what the docs say.  Integer data will always have this problem, and its better to proactively handle the ambiguity at the user's end.  If you disagree, please don't hesitate to re-open!

**Comment by arosen93** [comment]
A very thoughtful reply. Thank you, @jklymak. While it has changed since the prior version and in the way MATLAB handles it, I can understand the logic and will keep that in mind as I use the feature going forward.

**Comment by jklymak** [comment]
Well, it is strange that it changed, that is for sure!

**Comment by WeatherGod** [comment]
It would make sense to add a test to make sure that this behavior doesn't
change again. I also still don't have that warm fuzzy feeling closing out a
bug report because we don't know the source of the behavior change.

**Comment by jklymak** [comment]
OK, lets reopen it then!

**Comment by efiring** [comment]
Triage question: do you really want to spend time trying to figure out why the behavior is now correct?  I agree, I'm curious--but given all the other more pressing issues, surely this is low priority! I'm going to change the title, since this is not a bug.
