### ISSUE TITLE
Unable to draw horizontal arrow using annotation

### ISSUE THREAD

**Issue by inxp** [matplotlib/matplotlib#9591]
### Bug report

Unable to draw straight horizontal arrow using annotation

**Code for reproduction**

```

from pylab import figure, show, np

t = np.arange(0.0, 2.0, 0.01)
s1 = np.sin(2*np.pi*t)
fig = figure()
ax1 = fig.add_subplot(111)
xstmark=0.5
xenmark=1.0
ystmark=0.5
an1=ax1.annotate(s=' ',xy=(xstmark, ystmark), xycoords='data',
				xytext=(xenmark, ystmark),textcoords='data',
				arrowprops=dict(arrowstyle="<->"))
ax1.annotate(s='tr',xy=(((xstmark+xenmark)/2), ystmark), xycoords='data',fontsize=12.0,textcoords='data',ha='center')
ax1.plot(t, s1)

show()
```

**Matplotlib 2.1.0 outcome**

![figure_2](https://user-images.githubusercontent.com/6796654/32088633-606c4b96-bb02-11e7-9f5e-15b2c4ca5b0e.png)

**Expected outcome (Matplotlib 2.0.2 outcome)**
![figure_1](https://user-images.githubusercontent.com/6796654/32088653-7fe9955a-bb02-11e7-8fbc-000d2afe9d65.png)

  * Operating system: Windows 7 64 bit
  * Matplotlib version: 2.1.0
  * Matplotlib backend: qt4agg
  * Python version: 2.7.10
  * Jupyter version (if applicable): NA
  * Other libraries: NA
  * Installed using whl files

**Comment by anntzer** [comment]
Using some text (e.g. `'foo'`) for the annotation shows the origin of the "problem":
![figure_1](https://user-images.githubusercontent.com/1322974/32089590-b5370bf6-ba9f-11e7-88c3-519696aa6ee7.png)
the arrow is pointing towards the *center* of the text, not the baseline (which seems very reasonable behavior).

You are using a space (`' '`) as text, and we consider the y-center of thet space as the same as the y-center of a letter (more precisely, the y-center of `'lp'`) (see Text._get_layout: "full vertical extent of the font, including ascenders and descenders").  If using an empty string instead (`''`), then we consider the y-center to be at the baseline (which in fact seems a bit inconsistent; I'd think empty strings should just be treated the same -- in other words, right now you can have the workaround of using `''` instead of `' '` but I'm suggesting to break *that* case too).

Of course, the fact that `annotate` is the "recommended" API to get a FancyArrowPatch rather than a FancyArrow (see bottom of https://matplotlib.org/api/_as_gen/matplotlib.axes.Axes.arrow.html) is not a great API, nor is the fact that FancyArrow and FancyArrowPatch are actually completely different things :/

**Comment by inxp** [comment]
Thanks for replying...
It makes sense. I'll use the workaround for now :)

**Comment by inxp** [comment]
or I can add va='center' while drawing arrow. This works with space.
```
an1=ax1.annotate(s=' ',xy=(xstmark, ystmark), xycoords='data',
				xytext=(xenmark, ystmark),textcoords='data',
				arrowprops=dict(arrowstyle="<->"),va='center')
```

**Comment by jonnyhtw** [comment]
> or I can add va='center' while drawing arrow. This works with space and empty string.
> 
> ```
> an1=ax1.annotate(s=' ',xy=(xstmark, ystmark), xycoords='data',
> 				xytext=(xenmark, ystmark),textcoords='data',
> 				arrowprops=dict(arrowstyle="<->"),va='center')
> ```

IMHO this is really the answer that should be recommended since it isn't a 'workaround', rather an actual solution to the problem. 😄
