### ISSUE TITLE
path.contains_points returns different points based on the direction of the path

### ISSUE THREAD

**Issue by alexsb92** [matplotlib/matplotlib#9704]
### Bug report

**Bug summary**

The result of running path.contains_points on an underlying uniform grid will be different depending on the orientation/direction of the specified path (specified counter-clockwise vs clockwise). In both results, it returns points laying on some edges but not others.

**Code for reproduction**

```python
import matplotlib.path as mpltPath

#polygon = [(5,5),(10,5),(10,10),(5,10)]
polygon = [(5,5),(5,10),(10,10),(10,5)]
width =11
height =11

points = [[0,0],[1,0],[2,0],[3,0],[4,0],[5,0],[6,0],[7,0],[8,0],[9,0],[10,0],[11,0], \
          [0,1],[1,1],[2,1],[3,1],[4,1],[5,1],[6,1],[7,1],[8,1],[9,1],[10,1],[11,1],\
          [0,2],[1,2],[2,2],[3,2],[4,2],[5,2],[6,2],[7,2],[8,2],[9,2],[10,2],[11,2],\
          [0,3],[1,3],[2,3],[3,3],[4,3],[5,3],[6,3],[7,3],[8,3],[9,3],[10,3],[11,3],\
          [0,4],[1,4],[2,4],[3,4],[4,4],[5,4],[6,4],[7,4],[8,4],[9,4],[10,4],[11,4],\
          [0,5],[1,5],[2,5],[3,5],[4,5],[5,5],[6,5],[7,5],[8,5],[9,5],[10,5],[11,5],\
          [0,6],[1,6],[2,6],[3,6],[4,6],[5,6],[6,6],[7,6],[8,6],[9,6],[10,6],[11,6],\
          [0,7],[1,7],[2,7],[3,7],[4,7],[5,7],[6,7],[7,7],[8,7],[9,7],[10,7],[11,7],\
          [0,8],[1,8],[2,8],[3,8],[4,8],[5,8],[6,8],[7,8],[8,8],[9,8],[10,8],[11,8],\
          [0,9],[1,9],[2,9],[3,9],[4,9],[5,9],[6,9],[7,9],[8,9],[9,9],[10,9],[11,9],\
          [0,10],[1,10],[2,10],[3,10],[4,10],[5,10],[6,10],[7,10],[8,10],[9,10],[10,10],[11,10],\
          [0,11],[1,11],[2,11],[3,11],[4,11],[5,11],[6,11],[7,11],[8,11],[9,11],[10,11],[11,11]]

path = mpltPath.Path(polygon)
inside = path.contains_points(points)
print(inside)
print(path.contains_point([5,5]))
```

**Actual outcome**

```
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True  True  True  True False False
 False False False False False False  True  True  True  True False False
 False False False False False False  True  True  True  True False False
 False False False False False False  True  True  True  True False False
 False False False False False False  True  True  True  True False False
 False False False False False False False False False False False False]
0

```

**Expected outcome**

Depending on whether contains_points considers points laying on the edges as being inside or outside the polygon, the result of contains_points should be:
```
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False False False False False False False False]
```
for when points on edges are considered being inside, and:
```
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True  True  True  True False False
 False False False False False False  True  True  True  True False False
 False False False False False False  True  True  True  True False False
 False False False False False False  True  True  True  True False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False]
```
for if points on edges are not considered to be inside.

path.contains_point returns 0 when the point is [5,5] which leads me to believe that points on the path should not be considered, and therefore the second expected result is the right one.

If the path is specified as polygon = [(5,5),(10,5),(10,10),(5,10)] instead, the following (still inconsistent) result is returned:
```
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False  True  True  True  True  True  True False
 False False False False False False False False False False False False]
```

**Matplotlib version**

  * Operating system: Ubuntu 14.04
  * Matplotlib version: 1.3.1
  * Matplotlib backend (`print(matplotlib.get_backend())`): TkAgg
  * Python version: Python 3.4
  * Jupyter version (if applicable):
  * Other libraries: 

I believe matplotlib was either installed when i installed python, or i installed it using pip.

**Comment by ImportanceOfBeingErnest** [comment]
Since the true/false matrices may be a bit hard to grasp, the following rephrases the issue (initially brought up [here](https://stackoverflow.com/questions/47143754/matplotlib-path-contains-points-returns-false-for-points-on-some-edges-but-not-o)). 
The issue is visualized in the following plot where `matplotlib.path.Path.contains_points` is used to determine if some points lie inside a given path. Some of those point lie on the edge of the graph. The **result given by `contains_points` is inconsistent** in the sense that some point which are on the path's edge are considered to be inside, some others are not. The result also depends on the orientation of the path.

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.path

a,b = 5,10
polygon = [(a,a),(b,a),(b,b),(a,b),(a,a)]

x,y = np.meshgrid(np.arange(a-1,b+2,1),np.arange(a-1,b+2,1))
points = list(zip(x.flatten(),y.flatten()))

path = matplotlib.path.Path(polygon, closed=True)
inside = path.contains_points(points)

path2 = matplotlib.path.Path(polygon[::-1], closed=True)
inside2 = path2.contains_points(points)


fig,(ax,ax2)=plt.subplots(ncols=2, figsize=(6,3))
# plot ccw path
patch = plt.Polygon(polygon, zorder=0, fill=False, lw=2)
ax.add_patch(patch)
ax.scatter(x.flatten(),y.flatten(), c=inside.astype(float),cmap="RdYlGn", vmin=-.1,vmax=1.2)
# plot cw path
patch2 = plt.Polygon(polygon[::-1], zorder=0, fill=False, lw=2)
ax2.add_patch(patch2)
ax2.scatter(x.flatten(),y.flatten(), c=inside2.astype(float),cmap="RdYlGn", vmin=-.1,vmax=1.2)

ax.set_title("ccw path")
ax2.set_title("cw path")
plt.show()
```

![image](https://user-images.githubusercontent.com/23121882/32462750-cbc45cfe-c33a-11e7-904c-0c0a2efcae9f.png)

Red dots are outside (`contains_points() == False`), green dots are inside (`contains_points() == True`). ccw means counterclockwise orientation, cw means clockwise. 

The **expected outcome** would be either of the following two

![image](https://user-images.githubusercontent.com/23121882/32462879-41621f32-c33b-11e7-99b1-5e447010d0ad.png)
which are obtained by setting the `radius` argument to `contains_points`

```
inside = path.contains_points(points, radius=1e-9)
inside2 = path2.contains_points(points, radius=1e-9)
```

**Comment by WeatherGod** [comment]
Oh, wow... this might explain a whole class of bug reports in the past that
we shrugged off with "use shapely instead".

**Comment by alexsb92** [comment]
@ImportanceOfBeingErnest Thanks for rephrasing the issue much better than I did. The diagrams definitely make things more clear than my True/False tables.

**Comment by ImportanceOfBeingErnest** [comment]
@QuLogic This issue is about the path not containing all points that it should when `radius = 0`. 

The other issue (#6199) is about the orientation of the path changing the sign of the radius. (That may actually even make sense mathematically, so [I did not think that to be a problem](https://stackoverflow.com/a/45986805), just a matter to handle correctly.) 

In any case those issues may originate from the same piece of code somewhere down the road, but are distinct otherwise.

**Comment by royalosyin** [comment]
Very interesting.
inside = path.contains_points(points, radius=1e-9)

This one used a minus radius. They will the same results.
inside2 = path2.contains_points(points, radius=-1e-9)

**Comment by T81** [comment]
This is worst than I thought

```
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.path

polygon = ((-80, 0), (80, 0), (80, 60), (-80, 60))

x,y = np.meshgrid(np.arange(-90,90,10),np.arange(-10,80,10))
points = list(zip(x.flatten(),y.flatten()))
print(points)

path = matplotlib.path.Path(polygon, closed=True)
inside = path.contains_points(points)

path2 = matplotlib.path.Path(polygon[::-1], closed=True)
inside2 = path2.contains_points(points)


fig,(ax,ax2)=plt.subplots(ncols=2, figsize=(6,3))
# plot ccw path
patch = plt.Polygon(polygon, zorder=0, fill=False, lw=2)
ax.add_patch(patch)
ax.scatter(x.flatten(),y.flatten(), c=inside.astype(float),cmap="RdYlGn")
# plot cw path
patch2 = plt.Polygon(polygon[::-1], zorder=0, fill=False, lw=2)
ax2.add_patch(patch2)
ax2.scatter(x.flatten(),y.flatten(), c=inside2.astype(float),cmap="RdYlGn")

ax.set_title("ccw path")
ax2.set_title("cw path")
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/1782711/64494666-7a495900-d298-11e9-9b7a-f99b9d13cd0b.png)

**Comment by royalosyin** [comment]
Hi, T81

I just changed a little bit of your code. It should work now.
You can have a try.

`path   = matplotlib.path.Path(polygon)
inside = path.contains_points(points, radius=1e-9)

path2   = matplotlib.path.Path(polygon[::-1])
inside2 = path2.contains_points(points,radius=-1e-9)`

Good luck.

**Comment by T81** [comment]
Thanks @royalosyin.
So the problem seems to be the `closed` argument, right?
It seems that it does not close the polygon the right way.
BTW, how comes the polygon is plotted closed now?

**Comment by timhoffm** [comment]
Some more observations:

- Paths with only 2 nodes do not contain anything; see also https://github.com/matplotlib/matplotlib/issues/18879#issuecomment-723334948
- If the angle is (close to) 0, the valid region extends to `2*radius` whereas perpendicular to a line, it's only `0.5*radius`. This is not directly a bug but seems a bit large.
- We get artifacts if bounding lines start to overlap due to *radius* shifts.

~~~
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.path import Path
from matplotlib.patches import PathPatch

def draw_path_contains(ax, path, radius=0):
    x = y = np.arange(-0.5, 1.5, 1/30)
    X, Y = np.meshgrid(x, y)
    points = np.array([X.ravel(), Y.ravel()]).T

    c = path.contains_points(points, radius=radius).reshape(len(y), len(x))
    ax.scatter(points[:,0], points[:,1], c=c, s=20, cmap='PiYG')
    
    ax.add_patch(PathPatch(path, facecolor='none', lw=3, zorder=10))
    ax.plot(path.vertices[:,0], path.vertices[:,1], 'ro', zorder=11)


fig, axs = plt.subplots(3, 2, figsize=(12, 18))

path1 = Path([(0, 0), (1, 0), (0, 0)], closed=True)
draw_path_contains(axs[0, 0], path1, radius=0.2)
axs[0, 0].set_title('2 vertices: always False')

path2 = Path([(0, 0), (0.5, 0), (1, 0), (0, 0)], closed=True)
draw_path_contains(axs[0, 1], path2, radius=-0.2)
axs[0, 1].set_title('(close to) 0 angles: Extent is 2*radius')

path3 = Path([(0, 0), (0.5, 0), (1, 0), (0.5, 0.3), (0, 0)], closed=True)
draw_path_contains(axs[1, 0], path3, radius=-0.3)

path4 = Path([(0, 0), (1, 0), (1, 1), (0.8, 1), (0.8, 0.5), (0.2, 0.5), (0.2, 1), (0, 1), (0, 0)], closed=True)
draw_path_contains(axs[1, 1], path4, radius=-0.26)

path5 = Path([(0, 0), (1, 0), (1, 1), (0.6, 1), (0.6, 0.5), (0.4, 0.5), (0.4, 1), (0, 1), (0, 0)], closed=True)
draw_path_contains(axs[2, 0], path5, radius=0.3)

path6 = Path([(0, 0), (1, 0), (1, 1), (0.6, 1), (0.6, 0.5), (0.4, 0.5), (0.4, 1), (0, 1), (0, 0)], closed=True)
draw_path_contains(axs[2, 1], path6, radius=0.5)
~~~

![grafik](https://user-images.githubusercontent.com/2836374/98747676-4b58d680-23b8-11eb-94b8-b12c8d698975.png)

**Comment by snowzky** [comment]
Could this unintended behaviour _please_ be added to the docs as a warning? For the average user that is just using Matplotlibs tools and is not super knowledgeable about paths, contain_points, or other geometric stuff, one really depends on the documentation being accurate.

The conflation of handedness of the path and sign of the radius is especially confusing, because as it is stated now, the radius can be used to control how the "pixels" on the edge is handled; but given all the examples here, this is clearly not working as intended.

**Comment by jklymak** [comment]
PRs are welcome!  

The general problem here, however, is just floating point dithering.  A point mathematically on the path is going to be undefined as to whether it is inside or outside the path.

**Comment by AI-ML-Enthusiast** [comment]
How can I use it for 3D?

**Comment by timhoffm** [comment]
@AI-ML-Enthusiast You cannot use this for 3D. This is meaningful only in 2D.

**Comment by jklymak** [comment]
I'm going to close this.  I don't think there is anything sensible to be done on our side.  If data lies exactly on a line, whether it is "contained" or not is poorly defined in a floating point world.
