### ISSUE TITLE
Blanks in colorbar just inside of 'extend' arrowpoints when using AxesGrid

### ISSUE THREAD

**Issue by spencerahill** [matplotlib/matplotlib#9778]
Sorry if this is a duplicate...it seems like this would have come up for somebody else before, but I can't find anything about it.

### Bug report

**Bug summary**
When using AxesGrid and the 'extend' option for filled contours, the last rectangular color levels before the arrow-shaped endpoints are blank.  A workaround is to manually create the colorbar via `mpl.colorbar.ColorbarBase`.

**Code for reproduction**

```python
import numpy as np

import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import AxesGrid
import matplotlib as mpl

levels = np.arange(0., 1.2, 0.15)

# This yields blank values just before the end arrows in the colorbar.
fig = plt.figure()
axgrid = AxesGrid(fig, 111, 
                  nrows_ncols=(1, 1), 
                  ngrids=1,
                  cbar_mode='single')
ax = axgrid[0]
cs = ax.contourf(np.random.random((10, 20)),
                 extend='both')
cbar = axgrid.cbar_axes[0].colorbar(cs)

# This problem does not occur when not using AxesGrid.
fig, ax = plt.subplots()
cs = ax.contourf(np.random.random((10, 20)),
                 extend='both')
cbar = plt.colorbar(cs, ax=ax)

# The problem also doesn't occur if using AxesGrid + manually creating the colorbar.
fig = plt.figure()
axgrid = AxesGrid(fig, 111, 
                  nrows_ncols=(1, 1), 
                  ngrids=1,
                  cbar_mode='single')
ax = axgrid[0]
cs = ax.contourf(np.random.random((10, 20)),
                 extend='both', levels=levels)

cmap = mpl.cm.viridis
cb = mpl.colorbar.ColorbarBase(axgrid.cbar_axes[0], cmap=cmap,
                               boundaries=levels,
                               orientation='vertical', extend='both')
```

**Actual outcome**
<img width="432" alt="bug" src="https://user-images.githubusercontent.com/6200806/32759626-3b36ad88-c8e2-11e7-89b7-2dfe12b86ae7.png">
<img width="432" alt="no_bug" src="https://user-images.githubusercontent.com/6200806/32759627-3b6412fa-c8e2-11e7-9190-49a1ecf35bfe.png">
<img width="432" alt="workaround" src="https://user-images.githubusercontent.com/6200806/32759628-3b814aaa-c8e2-11e7-8351-306cdb6fafe1.png">

See the attached images.

**Matplotlib version**

  * Operating system: MacOS + Jupyter Notebook
  * Matplotlib version: 2.1.0
  * Matplotlib backend (`print(matplotlib.get_backend())`): MacOSX
  * Python version: 3.6
  * Jupyter version (if applicable): 4.3.0
  * Other libraries: 

Matplotlib installed via `conda install -c conda-forge matplotlib`

**Comment by afvincent** [comment]
@spencerahill Thank you for the detailed report :).

AFAICT, this behavior exists at least since Matplotlib 1.5.0.

**Comment by tacaswell** [comment]
There is something odd going on with the level as well, the middle one has 7, the top one has 5 + 2 blanks and the bottom one has 5.  They all seem to pick the tick locations differently as well....

**Comment by efiring** [comment]
@tacaswell, the different tick locations between the second and third plots is a red herring; it is expected given the way the colorbars are being made.  The first plot is just plain broken.  I don't know why.  Note, however, that the axes_grid1 toolkit has its own colorbar.py, which appears to have been copied from the matplotlib version when the toolkit was written, at least 8 years ago, and presumably modified a little bit at that time.  It has hardly been touched since then.  I don't think that any of the axes_grid1 examples have ever used the 'extend' kwarg; maybe it never worked.

**Comment by guziy** [comment]
I see the same problem with AxesGrid colorbar.. 

Has anyone found a workaround?

![Screenshot_20191020_111659](https://user-images.githubusercontent.com/900941/67161730-40558300-f32b-11e9-8bc9-868d2fd4560e.png)

**Comment by jklymak** [comment]
I think we recently did away with the axesgrid colorbar so this should be fixed?

**Comment by anntzer** [comment]
Indeed, setting `plt.rcParams["mpl_toolkits.legacy_colorbar"] = False` (to use the new colorbar) fixes the issue.  But one also needs https://github.com/matplotlib/matplotlib/pull/15460 given that the example above has actually been broken for 1.5y (since 2.2) for unrelated reasons with no one complaining... :)
