### ISSUE TITLE
how to autoscale y axis in different [x1,x2] range?

### ISSUE THREAD

**Issue by lj3278** [matplotlib/matplotlib#9890]
### Bug report
y axis does not autoscale according to x range ([x1,x2])

**Bug summary**

**Code for reproduction**

```python
# Paste your code here
import matplotlib.pyplot as plt

x=[1,3,5,7,9,11,13,15,17,20,23]
y=[100,2,-10,20,15,16,13,50,-62,55,150]
y1=[20,50,80,-30,16,23,45,68,49,20,170]

fig=plt.figure()

ax=fig.add_subplot(211)
ax.plot(x,y)
ax.set_xlabel('x')
ax.set_ylabel('y')

ax1=fig.add_subplot(212,sharex=ax)
ax1.plot(x,y1)
ax1.set_xlabel('x')
ax1.set_ylabel('y')

xmin=input('please input a min x:')
xmax=input('please input a max x:')
ax.set_xlim(xmin,xmax)

plt.show()

**Actual outcome**




<!--The output produced by the above code, which may be a screenshot, console output, etc.-->




# If applicable, paste the console output here

```
the whole x range:
![image](https://user-images.githubusercontent.com/34123634/33430447-da2c7ce2-d5d0-11e7-9f59-46293554815d.png)

partial x range:
![image](https://user-images.githubusercontent.com/34123634/33430331-6bbbe9fa-d5d0-11e7-8369-53ebe9b87c0d.png)

**Expected outcome**
![image](https://user-images.githubusercontent.com/34123634/33430385-ac7a45ea-d5d0-11e7-9227-d3d66833963b.png)

**Matplotlib version**

  * Operating system: win10 Enterprise  64bit
  * Matplotlib version: 1.4.3
  * Matplotlib backend (`print(matplotlib.get_backend())`): Qt4Agg
  * Python version: 2.7.10
  * Jupyter version (if applicable):
  * Other libraries: 

pip install matplotlib.xxx.whl

**Comment by dstansby** [comment]
The latest version of matplotlib is `2.1`. Could you try upgrading to that and seeing if this is still an issue?

**Comment by lj3278** [comment]
thanks David Stansby, I have undated matplotlib to the latest version, but it still does not work.

I googled the problem, tried set_autoscale_view and sth others, but seems do not work

anyway, thank you

**Comment by tacaswell** [comment]
Matplotlib does not automatically adjust the y-axis if you change the x limit.  If it did, we would have lots of issue asking for that _not_ to happen!  

The auto-limit code currently does not appear to look at the current view limits at all.

Although I see why it would be convenient for Matplotlib to do this, getting this right in the general case seems hard (but I would be happy to be proved wrong).  In your case, I would suggest doing something like:

```python
visible_y = y[xmin < x < ymax]
if len(visible_y):
    ax.set_ylim(np.min(visible_y), np.max(visible_y)
```
as part of the UI it seems you are building.

I am inclined to close this as 'wont-fix' but leaving open for now to get a second opinion.

**Comment by anntzer** [comment]
Strongly agree with wontfix.

**Comment by lj3278** [comment]
Thank you Thomas A Caswell, I have solved this problem with your suggestion

**Comment by tacaswell** [comment]
@lj3278 Great!  Glad to hear you got it working.

**Comment by vincenzooo** [comment]
I was trying to solve the exact same problem. Thanks for the solution!

Wouldn't it be a nice feature to be able to call autoscale (once) for one axis (or semiaxis) only, for example by setting limits with None?
For example with plt.ylim(None) or plt.ylim([0,None]) 

Alos, there is a typo in the above code (ymax instead of xmax in first line)

**Comment by timhoffm** [comment]
I *think* this does not work/help. `None` already means "do not change". Additionally `plt.ylim()` does not actually do the scaling. It can just unset the autoscaling flag, but the scaling would have to triggered separately. Therefore, it's simplest to save the limits, autoscale and reapply selectively, e.g.

~~~
x = np.linspace(-10, 10)
plt.plot(x, x**2)

plt.ylim((20 ,60))

ybottom, top = plt.ylim()
plt.autoscale(axis='y')
plt.ylim(bottom=ybottom)
~~~~

This is are rather rare request as it should only be relevant in interactively manipulated plots. I think it's better to have three lines of code for this and not make the API more complicated.

**Comment by vincenzooo** [comment]
I hadn't notice the behaviour about None, then I agree it would be bad to break the interface. 
However the same result of None is easily obtainable with plt.xlim([0,plt.xlim()[1]]), while the autoscaling is not so immediate (not three lines of code when you have multiple datasets).

Also, I don't understand the objection that is relevant only for interactive manipulation. Typically I plot the entire data for a set of curves, then I change the limits on a range of interest on x that has a smaller span in y, but the curves are then too small to be visualized and it is not immediate or always possible to adjust the plot from the data.
The x span is fixed in code, but the y span depends on data. 

Maybe there is a simple solution and I am missing it, so far I have used plt.gca().get_lines(), then get_xlim to find the corresponding range of y (from get_xydata) , and then adjusting the plot. I am not sure at all this is a solid solution and it will not break if other kind of objects (i.e. which are not lines) are plotted.

**Comment by ImportanceOfBeingErnest** [comment]
The problem here is clearly not the interface, but rather to make a solution that would apply to the general case of arbitrary artists in the axes. As @tacaswell pointed out above, this is hard.  
I do agree that it *looks* easy for lines; but even then people might have different expectations: Should the first and last *data point* be taken as reference, or should lines be interpolated at the view limit boundaries? For arbitrary artists, e.g. patches, it would even be harder; it would require to calculate intersections of all geometric shapes in the axes.  
Therefore I would also agree to previous comments in the sense that this is something the user need to calculate for themselves - this ensures they get exactly the solution that matches their requirements.

Concerning interactive usage, [this stackoverflow Q & A](https://stackoverflow.com/questions/53326158/interactive-zoom-with-y-axis-autoscale) shows a possible solution.

**Comment by gsteele13** [comment]
I must say I find the attitude "wontfix" pretty irritating here...

This is a functionality I often want, and is provided by nearly every other plotting software in existance. While, at least gnuplot, which I used for 20 years...

True, there are alternatives, but they are ugly and involve a lot of overhead / boilerplate. 

My best solution so far, aside form effectively implementing autoscaling code myself (again, of course, I can do it, but it's a pain...) is actually to slice the data before plotting: 

<img width="260" alt="Screenshot 2021-04-08 at 16 11 02" src="https://user-images.githubusercontent.com/16204006/114042098-68210980-9885-11eb-8897-0b3eabee132b.png">

Sure, works, but is an ugly set of lines of code that could be replaced with a single flag option to the autoscale function of an axis. 

On this basis, I would suggest that "wontfix" is not an appropriate label...?

**Comment by jklymak** [comment]
"won't fix" refers to it being a bug.  If you want to ask for a new kwarg or function to get this behaviour, I imagine that could be considered.   But, as pointed out above, auto limits are somewhat complicated...

**Comment by gsteele13** [comment]
Thanks, that makes it a bit more clear, am not so 100% familiar with the various terms in bug terminology....a bit of a noob...to unexperienced ears, it sounds maybe worse than it is. 

I will give some thought to what would be a reasonable behaviour. Off the top of my head, I would say that if the user has specified a xlim but not a ylim, then the ylim should be adjusted based on the specified x-range. It is strange to make a plot and have the ylim determined by data that is not visible based on the chosen x-range. 

This is of course based on the idea of having y as a "dependent" variable and x as an "independent" variable, as is a pretty common convention in science. This makes things asymmetric with respect to the x-axis, giving it a special status. As an example in this context, it would make not make intuitive sense to have a behaviour where `xlim` was automatically adjusted based on a manually specified `ylim`.

This is the behaviour of gnuplot for example. Example: create a dataset in python:

```
import numpy as np
x = np.linspace(0,10,100)
y = x**2
np.savetxt("test.dat", np.array([x,y]).T)
```

Then plot it in gnuplot:

```
plot "test.dat"
```

<img width="958" alt="Screenshot 2021-04-09 at 14 33 39" src="https://user-images.githubusercontent.com/16204006/114180633-b9420380-9940-11eb-82fd-b34b62f79855.png">

If I zoom x in gnuplot:

```
set xrange [4:6]
replot
```

then ylimits are adjusted:

<img width="914" alt="Screenshot 2021-04-09 at 14 33 55" src="https://user-images.githubusercontent.com/16204006/114180736-e2fb2a80-9940-11eb-9079-764db49800f2.png">

But if I do the same and set ylimits, xlimits are not adjusted:

```
set autoscale; replot; set yrange [10:20]; replot
```

<img width="958" alt="Screenshot 2021-04-09 at 14 36 21" src="https://user-images.githubusercontent.com/16204006/114180795-fa3a1800-9940-11eb-9ffd-7910e9849e68.png">

Maybe my point is that this is a common workflow that is used in scientific plotting, and there is no easy way to implement this workflow right now in matplotlib, and it does the opposite of what people would intuitively expect. 

Now, of course, if I have parametric plots, or more complicated patch drawings, then this behaviour no longer makes sense. But I feel that for scientific plotting, these are relatively less common use cases, and ones in which it makes sense that the user would likely want to either work with purely "automatic" limits, or fully manual for both x and y. So this behaviour may not be desired for such cases, but in any case in those cases people will most likely be implementing both limits by hand anyway, and so it does not really do any harm. 

I am curious what people think

**Comment by jklymak** [comment]
I think you are used to a particular set of behaviours from gnuplot, whereas matplotlib is derived from Matlab, which had a different behaviour.  

Again, we will not break the long-standing API. If you would like to propose a new backwards-compatible API, that could be entertained.

**Comment by drmcnelson** [comment]
I agree with gsteele13.   The behavior is not normal, and wontfix is a bit frustrating.    This theoretical approach is not well connected to the reality of actually using it.   The idea that you zoom into some range in x, where the signal may be small, and it persists with the range set over the entire data set, is not practical and it is hard to thing of why or where it would be useful.

And,  set_ylim() is not a useful answer.   (And BTW,  relim(), autscale_view() also doesnt work in so far as respecting the range set by xlim.) 

We need the "pretty limits" like those chosen by the auto scaling, not the limits with umpteen significant figures that you might get by setting them to min() and max().  So, the best solution is "will fix it", and in any case, it would be useful to also have a call that will set the more decorious choice of limits and better still, with an optional argument for a data array for it to consider.

So, please do fix it, and in the meantime, at least provide something that works as a workaround.

**Comment by jankaWIS** [comment]
@tacaswell 
> Matplotlib does not automatically adjust the y-axis if you change the x limit. If it did, we would have lots of issue asking for that _not_ to happen!
> 
> The auto-limit code currently does not appear to look at the current view limits at all.
> 
> Although I see why it would be convenient for Matplotlib to do this, getting this right in the general case seems hard (but I would be happy to be proved wrong). In your case, I would suggest doing something like:
> 
> ```python
> visible_y = y[xmin < x < xmax]
> if len(visible_y):
>     ax.set_ylim(np.min(visible_y), np.max(visible_y)
> ```
> 
> as part of the UI it seems you are building.
> 
> I am inclined to close this as 'wont-fix' but leaving open for now to get a second opinion.

Although at first sight nice fix, this is becoming quite difficult if you start thinking about more complex plots. Let's assume that you want to add error bars. Then this simple fix is not necessarily providing the right answer because suddenly, you need to check the minimum/maximum of the sum of the two arrays - the one for the data and the other for the errorbars. And now imagine that you want to plot several lines, each one with errorbars. How do you proceed then? Your code grows because you now need a condition for every piece of data. Although I do understand that this is a hard problem, I also think there should be a way how to update the y-lim automatically... 

```python
import numpy as np
import matplotlib.pyplot as plt
x = np.arange(1,40)
y1 = 1/x
y2 = 1/x+1
yerr1 = x/20
yerr2 = 10/x

fig, ax = plt.subplots(1,1)
ax.errorbar(x,y1, yerr=yerr1)
ax.errorbar(x,y2, yerr=yerr2)
ax.set_xlim(5, x.max())
plt.show()
```
![image](https://user-images.githubusercontent.com/54404810/210772397-bb7f0d05-6616-42c6-8275-ec8bdf050115.png)

when the full figure looks like this:
![image](https://user-images.githubusercontent.com/54404810/210772466-9800375e-71e1-437b-add4-9727ba996098.png)

**Comment by drmcnelson** [comment]
Maybe provide a call to cause it to look at the current view limits and
update, that for example can be invoked in an animation.

**Comment by jankaWIS** [comment]
@drmcnelson and how would you do that? I hoped that I could, for example, check the current `xlim` or `ylim` using `ax.get_ylim()` but that does not update either. It shows the original value and I don't know where to find the one that is then showed.
