### ISSUE TITLE
Colormap order on documentation page

### ISSUE THREAD

**Issue by gregcolyer** [matplotlib/matplotlib#9953]
At http://matplotlib.org/users/colormaps.html, there seems to be an inconsistency for the "Sequential colormaps" between the lightness plots (http://matplotlib.org/_images/lightness_01.png) and the grayscale plots (http://matplotlib.org/_images/grayscale_01_01.png). The former run dark to light (left to right) whereas the latter run light to dark. I think the latter are correct (assuming left to right is index order). Other sections e.g. "Sequential (2) colormaps" appear to be consistent in this respect.

**Comment by tacaswell** [comment]
I see the inconsistency (I assume that was intentional in the code that generates those) and also suspect that both where done for aesthetic reasons.

If we are going to make them consistent they should both be made to map the values [0, 1] from left to right.

**Comment by tacaswell** [comment]
Due to some issues with how we update the website, that is an old page, the content has moved to

https://matplotlib.org/tutorials/colors/colormaps.html#sphx-glr-tutorials-colors-colormaps-py

which is sourced from https://github.com/matplotlib/matplotlib/blob/master/tutorials/colors/colormaps.py

**Comment by gregcolyer** [comment]
Thanks. (Same issue with the new page though.)

**Comment by jklymak** [comment]
The source tutotial this comes from pretty clearly says that the plots are that way for esthetic reasons.  I don't find this "inconsistent".

**Comment by afvincent** [comment]
Well, if I remember correctly, this was already here when I tweaked a bit the script a few months ago and TBH I did not really pay attention to it. However, I guess we could actually get rid of it: the affected color maps are all the same figure¹, so simply reverting the order should not result in overlapping or another kind of unpleasant behavior. I'll try to give it a shot today if I can.

¹: this may be the original reason. I do not remember exactly but the color maps may originally have been all in the *same* figure, in which case the current trick may make more sense.

**Comment by jklymak** [comment]
I expect it was done to be parallel w/ the diverging colormaps.  I think @kthyng originally wrote this?

**Comment by kthyng** [comment]
Yes I made that page originally. I apparently didn't feel icky about the inconsistency between the lightness plots and the greyscale plots since I probably set it up that way originally. I do personally prefer that the sequential colormaps "match" the direction of the diverging colormaps, yes.

I do think it's a bit weird-looking the way they are now, where they switch dark to light or light to dark during a given plot, like in [this lightness plot](http://matplotlib.org/users/plotting/colormaps/lightness_02.png) or in [this greyscale plot](http://matplotlib.org/users/plotting/colormaps/grayscale_01_02.png). Also sort of annoying is that the light-to-dark direction changes between greyscale plots (for example, [this](http://matplotlib.org/users/plotting/colormaps/grayscale_01_00.png) vs. [that](http://matplotlib.org/users/plotting/colormaps/grayscale_01_01.png)). 

Since this is an informational page about choosing colormaps, and it is so easy to switch direction of a given colormap, I don't feel the need to have the colormaps be in the "correct" direction. For a documentation page that is demonstrating what colormaps exist, for example, maybe it does make sense to not use the reverse of the colormap.

**Comment by gregcolyer** [comment]
Just to be clear, I wasn't complaining about any inconsistency between the maps themselves, which may be unfortunate but presumably shouldn't now be changed as this would break old scripts.

I don't really understand what aesthetic principle is at stake. The diverging maps each go in one direction and then the other, so surely reversed Sequential maps would match them just as well? And the Sequential (2) figure already has some reversed, presumably consistent with the maps themselves.

I do think the documentation should match the maps, and always show index order in the same direction. Otherwise, it seems the user is just left to guess which way round the map goes, i.e. trial and error, which seems a little unnecessary. Or is the order documented somewhere else?

**Comment by gregcolyer** [comment]
Great
