### ISSUE TITLE
Help page on concepts and mechanisms in matplotlib

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#9967]
## Feature request

We do not have a description of the concepts and mechanisms used in matplotlib. Some information is available in the respective classes or in examples. But I haven't found a concise overview giving the big picture.

It would be valuable for users (and also developers) to have a single help page collecting this information.

In particular:

### Elements of a plot
- Figure
- Axes
- Axis
- Artists
- Patches
- ...

### Coordinates and scaling
- Figure / Axes / Data coordinates
- Bbox
- aspect handling (original and active axes positions)
- transforms
- ...

The above are just the topics that came to my mind right now. It's work in progress and I plan to work on this later on. Comments and additions are welcome.

**Comment by jklymak** [comment]
I think improving the usage guide is a place to start.  It has most of your first subsection.

http://matplotlib.org/tutorials/introductory/usage.html#sphx-glr-tutorials-introductory-usage-py

**Comment by timhoffm** [comment]
That's indeed a good place, already conating some of my points (though I haven't yet read it completely).

Maybe even more important than changing the contents is making this more accessible. To find it from the main page, I had to

1) http://matplotlib.org/index.html: "To get started, read the User's Guide."
2) http://matplotlib.org/users/index.html: Tutorials -> Introductory
3) http://matplotlib.org/tutorials/index.html#introductory -> Usage Guide

Step 1 is fine, I would never have guessed that I have to follow the links in 2 and 3 to find that information. Maybe part of the problem is the naming. It's more a reference than a tutorial. Also, it's more "Concepts/Structure of matplotlib" than a "User Guide".

**Comment by jklymak** [comment]
Agreed. I think that right now there is no user documentation.   The advice I've received is to go ahead and add documentation to the existing structure, which for better or worse is the "tutorials" section, and then a re-organization will happen using that raw material.  I think the only caveat there is that tutorials are `*.py` files, whereas straight `*.rst` with `..plot::` directives might be a nicer editing format.  But its pretty easy to translate the `*.py` tutorial files to `*.rst` (because it already happens during the build process).  The other issue with tutorials is that they are not in any sensible order, which is another argument for `*.rst`.  Sphinx Gallery arranges them by their *length*, of all things.

**Comment by anntzer** [comment]
FWIW I believe that although sphinx-gallery is *really good* for "unstructured" examples where the main focus is sample code and plot, it doesn't work so well for "tutorial/guide" style docs where text is the most important part.
I would support switching these parts of the docs back to plain rst.

**Comment by story645** [comment]
wonder how much this ties in w/ MEP #17446

**Comment by timhoffm** [comment]
Loosely. #17446 is more specific in that it defines a method how to handle „porperty“ concepts. The docs part of #17446 and this one would live in the same part of the documentation.

**Comment by timhoffm** [comment]
@story645 Thanks for the ping. I'll check what is available now and reconsider what I want here. Will get back on this later.
